### ISSUE TITLE
Allow the Datadog API key to be set on events in-flight

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#10009]
I have a use-case where I'd like to set the Datadog API key used in the `datadog_logs` sink based on event metadata.

Currently we support storing the API key used to send logs to the `datadog_agent` source that is then propagated through to be used in the `datadog_logs` sink. This allows Vector to act as a sort of pass-thru transformation layer for the Datadog Agent. The API key is stored in [the event metadata](https://github.com/vectordotdev/vector/blob/ed044b35d21e24c009cf327d475157c9652828e4/lib/vector-core/src/event/metadata.rs#L17-L19) and so is not accessible in transforms (like `remap`).

I'd like to use an enrichment table to look up the API key to use based on event metadata and configure Vector to use this API key in the sink.

A couple of ideas:

1. Move the API key storage/lookup out of event metadata to a field directly on the event.
Pros: straight-forward to manipulate.
Cons: users are more likely to accidentally expose the API key if sending the event to a sink other than the Datadog Logs sink. `store_api_key` on the `datadog_agent` source defaults to `true`.
2. Add a VRL method for setting (and maybe reading?) event metadata. This could look like:
```
set_event_metadata("datadog_api_key", "ABCDEFG")
```

Or a specific method just to set the Datadog API key metadata like:

```
set_datadog_api_key("ABCDEF")
```

Pros: API key is kept hidden and the risk of exposing it is lower.

Cons: this method is a bit odd in the context of VRL in that it directly modifies the event without taking the value to modify as an argument.

I'm currently inclined towards option 2 here but am curious to get thoughts.

**Comment by JeanMertz** [comment]
I prefer 2, but:

> Cons: this method is a bit odd in the context of VRL in that it directly modifies the event without taking the value to modify as an argument.

I do agree with this. It is unfortunate.

I can see several solutions to this, which would allow us to use all regular built-in assignment/query expressions in VRL:

1. Use the `.`, but with a special notation to signify metadata access (e.g. `.(metadata.datadog_api_key)` or `.%metadata%.datadog_api_key`), none of my suggestions are ideal, but someone might have a solution.
2. Use a different notation than `.` (e.g. `&`) to access metadata (`&datadog_api_key` or nested `&foo.bar`). This basically means we have `foo` for variables, `.foo` for event fields and `&foo` for metadata fields. The upside of this is that it fits nicely in the existing constructs of VRL, but a potential downside is that it's easier to accidentally write `&datadog_api_key` when you meant `.datadog_api_key`, which could potentially expose secrets into the event, but I don't think this is a particular high risk, and we could optionally disallow assigning metadata fields directly to event fields without some intermediate step (e.g. the compiler rejects `.my_key = %datadog_api_key`)

The upside to one of the above solutions (I'm leaning to the second) is that all existing "field" functions, such as `set`, `get`, `del`, `exists`, and `remove` would work out of the box.
