### ISSUE TITLE
Loki: no out-of-order-action

### ISSUE THREAD

**Issue by ulrichSchreiner** [vectordotdev/vector#10012]
hi,

the loki sink has the field `out_of_order_action` with the values `rewrite_timestamp` or `drop` (default). it would be great to have an option `none` or something similar because loki 2.4 now supports out-of-order events.

https://grafana.com/docs/loki/next/configuration/#accept-out-of-order-writes

**Comment by nazar554** [comment]
Duplicate of #9223 ?

**Comment by spencergilbert** [comment]
Yep - duplicate of #9223 thanks @nazar554 !
