### ISSUE TITLE
Docs: encoding.codec never specified as required

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#10051]
Example: https://vector.dev/docs/reference/configuration/sinks/console/

All encoding options are marked optional, but vector will not start without a codec

**Comment by spencergilbert** [comment]
I suspect this was introduced by this: https://github.com/vectordotdev/vector/pull/9036/files

**Comment by jszwedko** [comment]
@spencergilbert Ah hmm, yeah, I neglected that some sinks _do_ require it. I think the right fix would be to have the sinks specify whether it is required or not by adding a `required` field to:

https://github.com/vectordotdev/vector/blob/c0da3b314f70c6dde177b86b8e4022947b797f89/website/cue/reference/components.cue#L275-L277

**Comment by spencergilbert** [comment]
@jszwedko who uses those sinks anyways! :P

**Comment by spencergilbert** [comment]
Why shouldn't this just be unset and sinks need to set it? https://github.com/vectordotdev/vector/blob/master/website/cue/reference/components/sinks.cue#L179

**Comment by jszwedko** [comment]
> Why shouldn't this just be unset and sinks need to set it? https://github.com/vectordotdev/vector/blob/master/website/cue/reference/components/sinks.cue#L179

Given the current cue organization with "features" I think what I suggested above would be better, that is, add a `required` field to `#FeaturesEncoding`.
