### ISSUE TITLE
Rendering a long list of tabs results in the list extending far to the right

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#10138]
See:

<img width="1028" alt="Screen Shot 2021-11-22 at 9 55 53 AM" src="https://user-images.githubusercontent.com/316880/142911380-985b69e4-93d8-4cf1-a46e-7373c7dcc98f.png">

Here the list of tabs extends past the container.

I'm not sure exactly what the right fix is here. Maybe changing the tabs to a drop down when it is a long list?

**Comment by DavidWeid** [comment]
I think just wrapping the tags is good visually. A dropdown might be too much visually with the tabs section being a box and the example being a box, a dropdown would be another layer on top. Let me know what you think

**Comment by jszwedko** [comment]
Yeah, agreed, I see how it looks with wrapping and that seems sufficient to me. Thanks for the quick fix!
