### ISSUE TITLE
[docs] Automatic Namespacing Section

### ISSUE THREAD

**Issue by chadwagoner-sf** [vectordotdev/vector#10136]
### Vector Version

```
0.18.0-alpine [running within docker]
```

### Additional Context

The website documentation seems to have a typo for the example of automatic namespacing. It references a config name `transforms/remap.toml` and should be called `transforms/apache_parser` based on the input of `transforms/apache_sampler.toml`. I believe this is what the example is trying to show, just the file name doesn't name the transforms.<name> as it should.

**Comment by jszwedko** [comment]
Yeah, you are right, thanks for noticing that!
