### ISSUE TITLE
Datadog_log sink not working with AWS PrivateLinks with Datadog

### ISSUE THREAD

**Issue by szibis** [vectordotdev/vector#10155]
### Description
Because of cost-saving, we use AWS private link setup with Datadog - https://docs.datadoghq.com/agent/guide/private-link/?tab=useast1.

### Vector Version

alpine docker 0.18.0 but it also not working on 0.17.x and 0.16.x

### Vector Configuration File

```
[sinks.datadog_logs_nomad]
  # General
  type = "datadog_logs" # required
  # we do not sending any stdout to DD because of huge traffic and logs are not ready in format to be added in such amount of traffic
  inputs = ["add_fields_stderr", "add_fields_stdout_system"] # required
  api_key = "${DATADOG_API_KEY}" # required
  # on Vector 0.16.1 our peered with DD VPC endpoints not working and this need to be investigated. We fallback to public DD endpoint.
  endpoint = "https://http-intake.logs.datadoghq.com:443" # optional, default
  healthcheck = true # optional, default

  proxy.enabled = false

  # Buffer
  buffer.type = "memory" # memory/disk optional, default
  buffer.max_events = 500 # optional, default, events, relevant when type = "memory"
  buffer.when_full = "block" # optional, default

  # Encoding
  encoding.codec = "json" # required
  encoding.except_fields = [] # optional, no default
  encoding.timestamp_format = "rfc3339" # optional, default

  tls.enabled = true
  tls.verify_certificate = true # optional, default
  tls.verify_hostname = true # optional, default

```
### Log
```
2021-11-23T18:12:22.607434Z ERROR sink{component_kind="sink" component_id=datadog_logs_nomad component_type=datadog_logs component_name=datadog_logs_nomad}: vector::sinks::util::retries: Non-retriable error; dropping the request. error=Client request was not valid for unknown reasons.
2021-11-23T18:12:22.607501Z ERROR sink{component_kind="sink" component_id=datadog_logs_nomad component_type=datadog_logs component_name=datadog_logs_nomad}: vector_core::stream::driver: Service call failed. error=BadRequest request_id=18
```

### Expected Behavior

We should be able to send data via AWS private links https://docs.datadoghq.com/agent/guide/private-link/?tab=useast1

### Actual Behavior

Stop working after some changes from 0.16.x, previously works with private link endpoints.

**Comment by jszwedko** [comment]
Hi @szibis ! Could you try setting endpoint to `https://http-intake.logs.datadoghq.com/api/v2/logs`?

**Comment by szibis** [comment]
@jszwedko Yes. I can confirm that this is working with Private links and any other Datadog endpoint when full API path is added `/api/v2/logs` into the endpoint. 

Current endpoint documentation is confusing. Can this be added into docs for later cases like that ??

**Comment by jszwedko** [comment]
Hi @szibis ! Yeah, agreed, the docs should make that clearer. I'll open a PR to adjust them.

**Comment by szibis** [comment]
I think nothing more here. Thanks for the help.
