### ISSUE TITLE
With --config-dir example config and .rpmnew files are active unless deleted

### ISSUE THREAD

**Issue by flyingflo** [vectordotdev/vector#10166]
### Vector Version

```
vector --version
vector 0.18.0 (x86_64-unknown-linux-gnu c77e085 2021-11-18)
```

### Vector Configuration File

As packaged in the RPM, with some changes, such that `.rpmnew` is created. The content doesn't matter.

### Expected Behavior
With `--config-dir` only config files with valid suffix should be picked up. 
The RPM package manager creates `.rpmnew` files during upgrades, when a packaged config file is changed.
Thus, `vector.toml.rpmnew` shall be ignored.
The vector RPM ships a bunch of examples /etc/vector/examples. Those should not be enabled by default.

### Actual Behavior
With 0.18, running with `--config-dir` or the env var `VECTOR_CONFIG_DIR`, `.rpmnew` files and all example become active.
This was not the case with 0.17.
It is a side effect of [implicit namespacing](https://vector.dev/highlights/2021-11-18-implicit-namespacing).
Vector is not usable unless the config dir is cleaned up manually after upgrading, because `examples/` doesn't fit the naming scheme (sources, sinks, ..).

**Comment by jszwedko** [comment]
@jdrouet do you mind taking a look at this one? I think we could just ignore any subdirectories that don't match the configuration schema (e.g. `examples` here).

**Comment by jszwedko** [comment]
Alternatively we could consider making this an opt-in feature. Something like a `--directory-namespacing` flag.

**Comment by jszwedko** [comment]
Followed up with Ben offline, we'd like to just ignore any directories that don't result in valid configuration keys.

**Comment by flyingflo** [comment]
Cool! 
Please don't forget to bring back the file name suffix filter, to pick up only valid YAML and TOML file names and ignore `.rpmnew` files, as it was in 0.17 and before. .. for full RPM friendliness ;)

**Comment by flyingflo** [comment]
https://github.com/vectordotdev/vector/commit/28bae91e9fbd4c6b4086e2946b45da94ce98a6c9#diff-bec02ad84008e669cb6ec2cd41a2b5736260324d26b3318dd22bc9e038bc5070L156

It might have been this line, that filtered the invalid file name suffixes, when loading directories, before.

**Comment by binarylogic** [comment]
Thanks @flyingflo, I also don't think it addresses [@jszwedko's comment](https://github.com/vectordotdev/vector/issues/10166#issuecomment-978156363). @jdrouet, we want to ignore those directories entirely. There should no warning or logging at all. In other words, we should be whitelisting the valid directories [as described in your RFC](https://github.com/vectordotdev/vector/blob/master/rfcs/2021-10-12-9568-automatic-namespacing.md#plan-of-attack).

**Comment by apollo13** [comment]
Personally I think the `examples` folder would be better off in `/usr/share/vector/examples` or so, the rpm shouldn't ship to many things in `/etc`
