### ISSUE TITLE
Improve pipeline filtering by avoiding clones

### ISSUE THREAD

**Issue by jdrouet** [vectordotdev/vector#10200]
# Problem
In the current implementation, when a `pipelines` transform is used and a `pipeline` uses a `filter`, the following topology is generated.

```text
             +-(clone) -> Filter -> (...transforms) -+
(previous) --+                                       +-> (next pipeline)
             +-(clone) -> Not(Filter) ---------------+
```
Due to the `Parallel` expand, the events are cloned to be dropped by one of the branch after. (If it matches the filter, it's kept by the first one, but dropped by the other).
This means we do a clone for nothing and could lead to a performance issue with a large topology.

# Potential solution

Introducing a proper router that wouldn't clone the event but forward the event to a dedicated output would allow to fix this problem and would be a good independent component.

```text
                  +-> (...transforms) -+
(previous) --(router)                  +-> (next pipeline)
                  +--------------------+
```

# Food for thoughts

- `Transform` only gives a single output, maybe this should change
- The `expand` method from the `Transform` trait doesn't allow to specify which input goes to which component when expanding. The `TransformConfig` trait being in `vector_core` and the `TransformOuter` being in `vector`, we cannot expand a transform and return a `TransformOuter` containing the inputs.

**Comment by tobz** [comment]
Related to https://github.com/vectordotdev/vector/pull/9169

**Comment by binarylogic** [comment]
Just throwing it out there, could we use the `route` transform, or use this as an opportunity to improve the `route` transform so that we could use it?

**Comment by jszwedko** [comment]
Closing since this transform was removed.
