### ISSUE TITLE
Update GraphQL Blog post

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#10238]
https://vector.dev/blog/graphql-api/#get-configured-topology--metrics no longer works against https://playground.vector.dev:8686/playground

Typo: https://vector.dev/blog/graphql-api/#our-first-api-clien-top should be `client`

**Comment by leebenson** [comment]
Ah, this was actually [answered in this discussion](https://github.com/vectordotdev/vector/discussions/10022).

TL;DR - The playground is running Vector 0.12.0. The query in the blog post was updated in #10028 for 0.17.0+

**Comment by spencergilbert** [comment]
Ooof, can we keep the playground up to date? Either that or remove it IMHO.

**Comment by leebenson** [comment]
For sure... if anyone that can figure out where it's hosted 😄

**Comment by jszwedko** [comment]
I tore it down and removed it from the docs in #10242
