### ISSUE TITLE
Add integration tests with the datadog-agent to cover metrics

### ISSUE THREAD

**Issue by prognant** [vectordotdev/vector#10249]
Two alternatives:
* Either an integration test relying on a single agent container (like the [humio integration test](https://github.com/vectordotdev/vector/blob/b273b78/Makefile#L405-L414)) and we cover Datadog source & sinks.
* Or we extend the k8s end-to-end tests that cover the agent (the metric receiving part should be easily covered by sending at statsd metrics to the agent and checking that the `datadog_agent` sources decodes it properly, as statsd distribution are turn into sketches by the agent, this would be relatively easy to also cover sketches).
* Or both

**Comment by spencergilbert** [comment]
I don't believe we have _any_ integration test for `datadog_agent` so any work should include logs tests too

**Comment by prognant** [comment]
We do have https://github.com/vectordotdev/vector/blob/master/lib/k8s-e2e-tests/tests/vector-dd-agent-aggregator.rs that does the strict minimum about testing logs reception from an agent. But it's rather limited and don't do any extensive validation.

That being said, I agree we should add an integration test that cover the whole `datadog_agent` source and perform extensive validation. We could probably plan to add datadog sinks integration test using real ddog endpoints (at least for logs).

**Comment by spencergilbert** [comment]
> We do have https://github.com/vectordotdev/vector/blob/master/lib/k8s-e2e-tests/tests/vector-dd-agent-aggregator.rs that does the strict minimum about testing logs reception from an agent. But it's rather limited and doesn't do any extensive validation.

Yeah, I was more thinking the `make test-integration-*` tests we have. Especially now that we're part of Datadog we can probably get some nicer integration tests setup here 😄

**Comment by jszwedko** [comment]
We also have https://github.com/vectordotdev/vector/issues/10249 . I think this is largely the same as that one, so I'll link it there and close this one.
