### ISSUE TITLE
Reduce clones when converting VRL values to/from Vector values

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#10256]
We've identified via performance analysis that we spend a bunch of time cloning collections when converting Vector event fields (`vector_core::Value`) to / from `vrl::Value` so that they can be operated on in VRL.

One idea we have for reducing this is leveraging `unsafe` to do a zero-copy clone given the memory layout should be the same (or if it isn't we can unify them). We'd like to spike this to see its feasibility.

**Comment by JeanMertz** [comment]
Closing this issue, as the `Value` type is now shared across Vector and VRL, removing any unneeded cloning.
