### ISSUE TITLE
Enable e2e acks for relevant soak tests

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#10290]
Should we be simply turning on acknowledgements in existing soak tests in order to see the before-and-after impact of this change, or do we want to add new sinks that are clones of the existing ones? If the latter, would it be worth adding a bit to the soak test infrastructure to be able to run multiple variants within one soak run, where each variant only changes a configuration variable?

**Comment by blt** [comment]
> If the latter, would it be worth adding a bit to the soak test infrastructure to be able to run multiple variants within one soak run, where each variant only changes a configuration variable?

Changed variables are different experiments, in the current soak infrastructure notion. Easiest thing for now would be to copy the experiment setup and fiddle with what you want changed, though I can see a world in which this gets unwieldy. To pull this off we'd need to figure out the naming scheme for the variant, and then have a mechanism to do small tweaks. The tweak bit would be interesting; we make our runs parallel with no coordination in part based off reliance on dynamically reading the directories present under `soaks/tests`, both in the workflow and the local script. 

Early on I did have a META file at the top of each test that held throughput goals, but I abandoned that. No reason why we couldn't revive that idea to pull off runtime test generation etc if we get a good pitch, a party interested to doing the work lined up.

**Comment by bruceg** [comment]
> Changed variables are different experiments, in the current soak infrastructure notion.

Right. I was thinking more of being able to have different experiments within the same run that differ only on variables in the configs rather than on the shape of the topology. My concern was the proliferation of runs caused by the multiplication effect of changed variables making the CI reports unwieldy.

**Comment by blt** [comment]
> > Changed variables are different experiments, in the current soak infrastructure notion.
> 
> Right. I was thinking more of being able to have different experiments within the same run that differ only on variables in the configs rather than on the shape of the topology. My concern was the proliferation of runs caused by the multiplication effect of changed variables making the CI reports unwieldy.

Just so the terminology is clear, an 'experiment' is the collection of configuration, load generation etc infra that gets compared between two SHA instances. A 'run' is a collection of all the experiments for a given SHA pair. Varying the value of a configuration variable would create a new experiment, though one obviously related to others in some important way. The analysis step needs to be able to see these experiments as different to make comparisons. Though that's not to say we can't introduce the idea of relatedness between separate experiments.

**Comment by blt** [comment]
> > Changed variables are different experiments
> 
> To add business context, e2e acks will eventually be on by default (#10273) since we want to [default to not losing data](https://github.com/vectordotdev/vector/blob/master/docs/USER_EXPERIENCE_DESIGN.md#dont-lose-data). Therefore, I'm not sure this is a changed variable. Obviously, if flipping this on has a meaningful performance impact we should fix that before making it the default.

The soaks introduced in #10255 suggest we aren't in a place where we can enable acks by default yet.

**Comment by binarylogic** [comment]
> Varying the value of a configuration variable would create a new experiment

Right, and I agree with that. But turning acks on by default would not change any configuration, hence why I think it should be part of the same experiments. Again, we should not turn acks on by default if they significantly regress performance.

**Comment by blt** [comment]
> > Varying the value of a configuration variable would create a new experiment
> 
> Right, and I agree with that. But turning acks on by default would not change any configuration, hence why I think it should be part of the same experiments. Again, we should not turn acks on by default if they significantly regress performance.

Gothca. Yeah, to be clear, from the point of view of the soaks they would be. So the PR that introduces flipping on acks by default would get soaked and if that causes regressions that'd be flagged, since we intentionally do not configure most default flags in the soak configuration. It'd just be part of the baseline/comparison SHA analysis.

**Comment by blt** [comment]
Which is to say, I think it's clear from `http_to_http_ack` that there's some performance issue that needs to be worked here. If we want to see how broad the problem is one cheap way to do that is to issue a PR that flips acking to on by default and see which of the soaks register a regression.
