### ISSUE TITLE
Prometheus Push Gateway Source

### ISSUE THREAD

**Issue by csolidum** [vectordotdev/vector#10304]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Current Vector Version
```
0.16.1
```

### Use-cases

-  Use vector to accept Prometheus Push Gateway metrics requests 

We'd like to set up a vector cluster to  accept push metrics from lambda functions and cron jobs and fan them out to several sinks.

### Attempted Solutions

We can implement this currently with a combination of the http source and a custom lua filter. This is non ideal due to the performance penalty that using lua filters incur.   

### Proposal

Create a new Prometheus Push Gateway source that will accept the prometheus push gateway format and translate it into vector's internal metric format. We would like to be able to pull out some http headers on this request as well and add that as tags to the metric.

**Comment by bruceg** [comment]
Given that the largest part of this work appears to be the encoding, I wonder how much of this could be accomplished with a codec specific to the Prometheus text or protobuf format combined with the `http_server` source. Certainly that would not help with any of the caveats listed above, but if it's just a matter of data formatting, we would very much prefer a codec over a new source.

**Comment by Sinjo** [comment]
So that should be partly possible, but if I've understood the HTTP server source's code, it would introduce another caveat.

From what I can tell the request path [gets encoded as a key on the event](https://github.com/vectordotdev/vector/blob/5dff0ed37a89e8cfc9db3ca499454dfe8198eadf/src/sources/http_server.rs#L384-L391) which wouldn't match the behaviour of the Prometheus Pushgateway, where alternating path components are treated as key-value pairs to add to all metrics in that push.

**Comment by Sinjo** [comment]
@bruceg Just wanted to check in and see if you have thoughts on that.

I think not supporting metric labels from the URL would be a reasonably big caveat to add. I'm not sure if there's something I missed in the HTTP server source's code that would let me access the URL and parse the relevant content from it (rather than the whole thing just being encoded as a key on the event).

**Comment by jszwedko** [comment]
Ah, yeah, given the fields are encoded in the URL as well, I don't think a codec would be sufficient. This does seem like it would need to be a standalone source; it could reuse shared bits from the existing `http_server` source though.

**Comment by Sinjo** [comment]
Sounds good! I'll look at how this source can make use of the code that's already in `http_server`, and any commonality that can be extracted out.

I'm just finishing up on an unrelated project at work, and then I'll have some time to work on this.

**Comment by Sinjo** [comment]
Hey, just wanted to give a little update.

I've started working on this properly now. I'm mostly figuring out my way around Rust and the Vector codebase (working [here](https://github.com/Sinjo/vector/tree/sinjo-add-pushgateway-source), but there's nothing much to see yet).

One thing I realised during this early part of the work is that there are two pretty distinct use-cases for this source:

  - As an aggregator for receiving metrics at the end of a batch job
    - In this use case, we want counters and histograms to be summed across metric pushes 
    - This is the use case that got me interested in building this source to begin with
  - As a push target for a long-running service which periodically pushes its internal registry to a Pushgateway
    - In this case, we want counters to replace their previous values
    - This is closer to what the existing Prometheus Pushgateway does, though with the difference that Vector offers features like TTL, and can re-expose the metrics in formats other than Prometheus

While the first one is my motivation for building this, I think it would be cool to support both. I also don't think it should be too difficult, assuming I've understood Vector's event model properly.

I noticed that there's this [`MetricKind`](https://github.com/vectordotdev/vector/blob/3968325707f90937e91b0ba12a6dbdae4719854b/lib/vector-core/src/event/metric/mod.rs#L519-L525) enum that supports `Incremental` and `Absolute` metrics. My thinking right now is to have a config flag (something like `enable_aggregation`) to toggle between the two. Having looked at a few different sources, I think I've understood this right, but please tell me if I haven't.

**Comment by Sinjo** [comment]
I've got something working, and left it in a draft PR at #18143. I figured that was the easiest way to start talking about specific implementation details.

**Comment by Sinjo** [comment]
I don't have data on relative usage, but there's a pretty large world of applications out there already using Prometheus for their metrics, and I don't see that disappearing any time soon even as OpenTelemetry Metrics start gaining support.

For anyone who already has a heavily-instrumented codebase with a mixture of long-running (i.e. easy to scrape the normal way with Prometheus) and short-lived batch jobs, using OpenTelemetry for the short-lived jobs is going to involve a big migration.
