### ISSUE TITLE
enhancement(sinks): add batching metrics

### ISSUE THREAD

**Issue by tobz** [vectordotdev/vector#10347]
Batching represents a potentially significant consumer of memory within Vector.  As many aggregator workloads will be striving to collect large batches, in turn to afford better compression efficiency, or generating larger files that are more efficient to process, this represents an often unbounded, or effectively unbounded, memory usage situation.

As part of surfacing how much batching is contributing to memory usage, we should expose basic statistics about batching.  The following metrics represent the most important facets to expose, and in turn can be used to derive the answer to many related questions:

- total number of pending batches
- total size of pending batches
- batch TTL (how long a batch lives before being flushed, either due to max limits or timeout)
- total batches created
- total batches flushed, by status (did it hit max bytes? max events? timeout?)

**Comment by jszwedko** [comment]
I think this is a duplicate of https://github.com/vectordotdev/vector/issues/9719 but I like the additional metrics you added here. Would you want to copy them there and then close this?

**Comment by tobz** [comment]
You're right, I'll close this and amend the linked ticket.

**Comment by tobz** [comment]
Closed in favor of #9719.
