### ISSUE TITLE
Detect Elasticsearch version to handle doc_type appropriately

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#10342]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Based on discussion from #9970 it would be a nicer user experience for Vector to detect Elasticsearch's version and appropriately handle the type name. [Example from fluentd](https://github.com/uken/fluent-plugin-elasticsearch/blob/7c14910d5b0caacc940cdef2f6f308b6ec73b68d/lib/fluent/plugin/out_elasticsearch.rb#L344-L358)

**Comment by StephenWakely** [comment]
As per the comment [here](https://github.com/vectordotdev/vector/pull/13881#issuecomment-1216680508) the api is not always authorized. We may need to provide a fallback config option to specify the version.

**Comment by ktff** [comment]
It's possible to detect the version at startup as mentioned in https://github.com/vectordotdev/vector/pull/13881#issuecomment-1213219185, else fallback to configured version, else error during build if version isn't configured.

**Comment by jszwedko** [comment]
Yep! That is my thought.

**Comment by jszwedko** [comment]
Re-opening since we had to temporarily revert PR.
