### ISSUE TITLE
Force the inclusion or exclusion of metadata in the `*_event_metadata` functions

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#10375]
A follow up issue for https://github.com/vectordotdev/vector/pull/10198#issuecomment-989457579. At some point in the future, we should force the inclusion/exclusion of each metadata field for the new VRL `*_event_metadata` functions.

**Comment by JeanMertz** [comment]
Metadata storage and access is being reworked in #12767 as free-form data, similar to event data, which makes this issue obsolete.
