### ISSUE TITLE
Interactive playgrounds / demos

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#1038]
There are use cases where we can provide interactive demos in a low-friction manner. A couple of good examples:

1. [Telegraf's interactive demo](https://rootnroll.com/d/telegraf/)
2. [Benthos labs](https://lab.benthos.dev/)

I'd like to explore something similar for Vector. Perhaps we can start with popular use cases (Kafka, Elasticsearch, K8s, etc.)?

cc @Jeffail

**Comment by Jeffail** [comment]
This is somewhat related to https://github.com/timberio/vector/issues/232 as both a unit test specification and a playground would benefit from a consistent way of isolating a graph of transforms from a wider Vector configuration. I'll spec out the unit testing work with this in mind.

**Comment by Jeffail** [comment]
Stuff what needs to happen for this thing what we will do:

- Spec out and implement https://github.com/timberio/vector/issues/232, that gives us:
    - A mechanism for injecting and extracting data from a Vector config at specific points
    - A way for users to express input events
- Compile topology as a webassembly library. We might need to restrict which sources and sinks are included in this build.
- Create a UI for compiling and executing a Vector topology within the browser.

**Comment by LucioFranco** [comment]
> A mechanism for injecting and extracting data from a Vector config at specific points

When you say this, do you mean the ability to add/remove sources/transforms/sinks from the config via a runtime api?

> Compile topology as a webassembly library. We might need to restrict which sources and sinks are included in this build.

This one I think will be very difficult since everything is built around tokio, futures and a few C libraries. But it is something we should 100% investigate and I'd love to see this.

**Comment by Jeffail** [comment]
>> A mechanism for injecting and extracting data from a Vector config at specific points
>
> When you say this, do you mean the ability to add/remove sources/transforms/sinks from the config via a runtime api?

Yeah, so in the case of unit testing configs I'd be looking to identify a subset of the topology being tested and isolate it. That would potentially involve placing a source with static test data with the ID matching what our target has as an input, we'd then also need to place sinks that aggregate the outputs of the last components of the target topology.

For digging into this further it's probably best to move into https://github.com/timberio/vector/issues/232

**Comment by binarylogic** [comment]
Given the 4-week time frame of this project, I don't think we'll have time to address this. We also have ideas to use this as a marketing hack that we need to further discuss. As such, I'm removing it from this milestone.

**Comment by jszwedko** [comment]
Closing this since we don't expect to be working on it its current form We do plan to have a VRL playground and potentially a broader Vector playground, but we'll open new issues when we spec out that work.
