### ISSUE TITLE
refactor(buffers): eschew `Acker` in favor of `EventFinalizer`

### ISSUE THREAD

**Issue by tobz** [vectordotdev/vector#10380]
### Context

Currently, event acknowledgements are potentially split into two categories: passthrough and segmented.

When Vector is operating with an in-memory buffer -- the default -- the `EventFinalizer`s attached to an `Event` flow through from source to sink without ever being dropped or mangled, which is the "passthrough" mode.  This allows finalizers attached by a source to be managed directly by the sink processing the events.

When Vector is operating with a disk buffer, the event is encoded to a format suitable for writing to disk, which effectively acknowledges the event at the time of encoding, as it takes ownership of the `Event` and drops it, leading to a default finalizer response.  When the event is read from the buffer, Vector also wants to be able to acknowledge when the event is processed by a sink so it can be removed from the disk buffer.  This is accomplished with `Acker`, which requires sinks to maintain an in-order list of processed events such that the acker can inform how many consecutive events, from the last acknowledgement point, can be deleted from the buffer.

In this way, acknowledgements are "segmented": one acknowledgement happens between source and buffer, and another between buffer and sink.

This is clunky because it adds a secondary way to acknowledge events that the sinks must be aware of, and `Acker` itself is not misuse-resistant: while `EventFinalizer` provides drop guard-like behavior, always providing a finalization result no matter what, `Acker` requires a manual call by sinks to indicate progress, which means that a faulty usage could lead to subtle bugs.

Additionally, with the imminent introduction of buffer topologies, there's a limitation of providing a single `Acker` instance that can correctly provide acknowledgements to a multi-stage buffer topology, given the inherent potential for events to be returned by any stage within the buffer topology.

### Solution

We should explore a solution which reattaches `EventFinalizer`s to an `Event` that come out of a buffer when the buffer type is not passthrough capable.

Buffer stages would become responsible for indicating if they required managed acknowledgement handling. The new buffer topology infrastructure would become responsible for attaching an appropriate `EventFinalizer` to any `Event` emitted by a buffer stage which required such handling, as well as actually providing the ordering facilities to track when the next contiguous range of events could be acknowledged, etc.

Additionally, a new trait would be introduced -- name TBD -- that buffer stages would be required to implement which would allow the buffer topology to report acknowledgement progress in-band to the buffer stage itself, allowing a single implementation of acknowledgement tracking to be applied generically to any buffer stage that required it.

**Comment by bruceg** [comment]
Completed by #13457
