### ISSUE TITLE
(loki sink): Update internal events

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#10401]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Current Vector Version

```
❯ vector --version
vector 0.18.1 (x86_64-apple-darwin c4adb60 2021-11-30)
```

### Proposal

Loki's OutOfOrder internal events are both logged at WARN and emit `processing_error` counters, I'd propose when we emit these logs they are the _intended_ configured behavior.

When rewriting the timestamp it's not necessarily a processing error as the event is processed and sent to Loki. Dropping an event emits both a discarded event and processing error metric.

I'd propose neither log should be WARN, and the metrics could be updated to be more accurate/user friendly.

### References

- #10364

cc @jszwedko @bruceg @binarylogic

**Comment by binarylogic** [comment]
Works for me

**Comment by jszwedko** [comment]
Likewise. I think this makes sense.

**Comment by bruceg** [comment]
Agreed. If it is defined behavior, it should not cause a warning. Emitting a metric to know how often this happens is still good, but not an error metric.
