### ISSUE TITLE
Flatten (or HTTP sink) behaviour changed from 17 to 18.1?

### ISSUE THREAD

**Issue by adam-mrozik** [vectordotdev/vector#10422]
Related to #10416 : 
We have noticed that our pipelines started to fail and all the messages that were wrapped in a JSON like:
```
{message: {a: 1, b:2}}
```
Are now completely unnested:

{a: 1, b:2} 
Is this something expected?

**Comment by jszwedko** [comment]
Hi @adam-mrozik !

Could you share:

* The Vector version it worked on
* The first Vector version it does not work
* Your Vector configuration

?

**Comment by adam-mrozik** [comment]
Oh, this was in ticket, but I could have added it.

Initial version 17.0
Current version 18.1

Configuration:

```
    [sources.http_in]
      type = "http"
      address = "0.0.0.0:8001"
      encoding = "json"

      # Auth
      auth.username = "user"
      auth.password = "pwd"

      path = "/xxx"

    [transforms.flatten]
      type = "remap"
      inputs = ["http_in"]
      source = '''
      if exists(.message) {
        structured = parse_json(.message) ?? {}
        ., err = merge(., structured)

        if err != null {
          log("Unable to merge message: " + err, level: "error")
        }
      }

      . = flatten(.)
      '''
```

**Comment by jszwedko** [comment]
Hi @adam-mrozik ! Could you share the sink config too? I'm not seeing anything that changed with `flatten` between those two Vector versions so I'm thinking it might have something to do with a change in sink encoding. You could add a `log(.)` in your VRL program after `flatten()` to see what it looks like in the `flatten` transform in-between the two versions.

**Comment by jszwedko** [comment]
If you could share an example input HTTP request that would help with reproducing too.

**Comment by jszwedko** [comment]
Closing due to lack of response, but please re-open if you are still running into this!
