### ISSUE TITLE
Vector's `prometheus_remote_write` source tests don't work with Prometheus 2.32.0

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#10458]
Discovered this via https://github.com/vectordotdev/vector/runs/4525200218?check_suite_focus=true

After investigating I discovered the failure was because Vector wasn't receiving any events from Prometheus's remote_write. We should investigate and see why this is.

I pinned to a working version of prometheus in https://github.com/vectordotdev/vector/pull/10457. We could unpin whenever we figure out the issue to continue catching regressions from upgrades.

**Comment by jszwedko** [comment]
Hrm, actually, now it is working for me locally with `v2.32.0` and `latest`.

**Comment by spencergilbert** [comment]
The failing test passes for me locally, but continues to fail in CI.
