### ISSUE TITLE
Add attributes (CN) from peer/client TLS certificate as label

### ISSUE THREAD

**Issue by abh** [vectordotdev/vector#10530]
For TLS sources it'd be a great to have a way to add attributes from the peer certificate as labels. For example adding the commonName from a client certificate.

**Comment by spencergilbert** [comment]
Hey @abh thanks for the request! I _think_ I've seen this request before but I'm having trouble finding the issue. I see both https://github.com/vectordotdev/vector/issues/2931 and https://github.com/vectordotdev/vector/issues/7308 which are similar but perhaps not exactly the same.

@jszwedko perhaps your github fu can dig up the issue I'm remembering?

**Comment by jszwedko** [comment]
Hey! Yeah, I think this is the same as https://github.com/vectordotdev/vector/issues/2931 . I think #7308 could be closed for https://github.com/vectordotdev/vector/issues/2931 too.

I'll close this as a duplicate, but please feel free to leave additional thoughts on https://github.com/vectordotdev/vector/issues/2931!

**Comment by abh** [comment]
Thanks @jszwedko & @spencergilbert; yup -- that is indeed the same! I added the solution I found for my need in that ticket.
