### ISSUE TITLE
Clarify aggregator helm chart documentation

### ISSUE THREAD

**Issue by abh** [vectordotdev/vector#10531]
The documentation isn't clear on which is the helm chart that'll be better supported/maintained in the future for an `aggregator` role. The `vector-aggregator` chart or the `vector` chart configured as an aggregator?

`vector-aggregator` had a recent announcement, but the `vector` chart looks like it had more care and feeding (at least in the default `values.yaml` file).

(For anyone else reading, I went with the `vector` chart; but if that's correct having a note in the other charts that they are deprecated or at least that the `vector` chart appropriately configured is recommended would be helpful).

**Comment by spencergilbert** [comment]
Hey @abh - as you noted the `vector` chart will be the maintained chart going forward. I'm updating the documentation and be marking the old charts as deprecated this week ahead of the 0.19 release.

**Comment by jszwedko** [comment]
Indeed, apologies for the confusion. This is being tracked by #10004

**Comment by abh** [comment]
thank you both, again! 😄
