### ISSUE TITLE
parse_apache_log "error" format is incomplete

### ISSUE THREAD

**Issue by ghost** [vectordotdev/vector#10597]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
vector 0.18.1 (x86_64-unknown-linux-gnu c4adb60 2021-11-30)
```

### Vector Configuration File

```toml
[transforms.parse_apache_error]
type = "remap"
inputs = ["apache_error"]
source = '''
.data = parse_apache_log!(.message, "error", "%a %b %d %H:%M:%S.%f %Y")
'''
```

### Debug Output

```
2021-12-27T22:39:16.998321Z  WARN transform{component_kind="transform" component_id=parse_apache_error component_type=remap component_name=parse_apache_error}: vector::internal_events::remap: Mapping failed with event. error="function call error for \"parse_apache_log\" at (8:71): failed parsing common log line" internal_log_rate_secs=30
```

### Expected Behavior

Line is parsed as an error log line with no associated client

### Actual Behavior

Line is not parsed (and Vector appears to try to parse it as a 'common' format, according to the warning, despite being told it is an 'error' line!)

### Example Data

```
[Mon Dec 27 16:39:10.968303 2021] [proxy:error] [pid 23964] (113)No route to host: AH00957: HTTP: attempt to connect to 10.1.0.244:9000 (hostname.domain.com) failed
```

### Additional Context

I'm guessing the error is because the parser assumes `[client 1.2.3.4:1234]` will always be present, as below. Clearly this is not a valid assumption.
```
[Mon Dec 27 16:39:10.968492 2021] [proxy_http:error] [pid 23964] [client 172.16.0.149:58386] AH01114: HTTP: failed to make connection to backend: hostname.domain.com, referer: https://external.domain.com/
```

Furthermore it's quite confusing that the function falls back(?) to trying to parse it as a "common" log.

In a semi-related note, it's a bit annoying that I must specify the timestamp format even though it is using the [default](https://httpd.apache.org/docs/current/mod/core.html#errorlogformat) error-log timestamp format (and in fact the default error-log format altogether).

In fact I'm not sure why the [regex](https://github.com/vectordotdev/vector/blob/bd8f097e82f8e3f1c30a4ed28e86c3e6ec97fc00/lib/vrl/stdlib/src/log_util.rs#L63-L75) expects a `-` in so many places. Apache's default error log format does NOT replace empty fields with dashes, but rather removes them (along with nearby characters). The only field which could be replaced by a dash is the module-name, yet your regex wrongly looks for all of the following being replaced by a dash: timestamp (??? how would this be empty), PID (??? how would this be empty), client IP, message.

The comment on the client port line of the regex is also misleading since it will in fact NOT match `[` in any case, and the comment just plain doesn't match the logic of the regex.

**Comment by zonidjan** [comment]
`        ((-|\[\s*client\s*(-|(?P<client>.*:?):      # Match `-` or `[` followed by `client`, `-` or any character until the first or last `:` for the port.`
Also misleading, this will never (luckily, since IPv6 is a thing) go until the first colon. `.*` is greedy and will consume everything until the last :. No idea what that `:?` is doing inside the capture group. At least I think I'm reading it right, I honestly am not sure because this regex is several times more complicated and less maintainable than it needs to be.

Frankly, this regex was clearly written by someone who didn't bother to read the docs, so here they are:

> It can happen that some format string items do not produce output. For example, the Referer header is only present if the log message is associated to a request and the log message happens at a time when the Referer header has already been read from the client. If no output is produced, the default behavior is to delete everything from the preceding space character to the next space character. This means the log line is implicitly divided into fields on non-whitespace to whitespace transitions. If a format string item does not produce output, the whole field is omitted. 

> **For example, if the remote address `%a` in the log format `[%t] [%l] [%a] %M`  is not available, _the surrounding brackets are not logged either_**.

> **Space characters can be escaped with a backslash to prevent them from delimiting a field**. The combination '% ' (percent space) is a zero-width field delimiter that does not produce any output.

> The above behavior can be changed by adding modifiers to the format string item. **A - (minus) modifier causes a minus to be logged if the respective item does not produce any output.** In once-per-connection/request formats, it is also possible to use the + (plus) modifier. If an item with the plus modifier does not produce any output, the whole line is omitted.




> #Example (default format for threaded MPMs)
> ErrorLogFormat "[%{u}t] [**%-m**:%l] [pid %P:tid %T] %7F: %E: **[client\ %a]** %M% ,\ referer\ %{Referer}i"

(all emphasis mine)

**Comment by zonidjan** [comment]
And here is a regex which is actually functional (at least for the lines in my error_log, and in Python):

```
regex = r"""(?x)                                     # Ignore whitespace and comments in the regex expression.
        ^\s*                                        # Start with any number of whitespaces.
        \[(?P<timestamp>[^\]]+)\]\s+ # [%{u}t]
        \[(-|(?P<module>[^:]+)):(?P<severity>[^\]]+)\]\s+ # [%-m:%l]
        \[pid\s+(?P<pid>\d+)(:tid\s+(?P<thread>\d+))?\]\s+ # [pid %P:tid %T]
        (?P<message1>[^\[]*?:\s+([^\[]*?:\s+)?)? # %7F: %E:
        (\[client\s+(?P<client>.+?):(?P<port>\d+)\]\s+)? # [client\ %a]
        (?P<message2>.*) # %M
        (, referer .*)? # ,\ referer\ %{Referer}i
        \s*$                                        # Match any number of whitespaces (to be discarded).
    """
```

Note that the error message is split before and after the client (if present). The first portion will have some low-level details like the OS error code ("no route to host" or "permission denied"), while the second portion has the actual error message. If the client info is not present, these fields can not reliably be split (they're just text followed by `: `, might not be present, and the actual error message might include `: ` in it), so they need to be combined instead.

**Comment by StephenWakely** [comment]
Related #8431
