### ISSUE TITLE
Enable soaks on Dependabot PRs

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#10637]
Today dependbot isn't capable of running soaks due to permissions so we avoid running them on dep upgrade PRs - it's definitely possible that a dependency could introduce a regression or an improvement and it'd be good to validate this prior to merging.

**Comment by spencergilbert** [comment]
https://github.com/kube-rs/kube-rs/blob/master/.github/workflows/ci.yml#L94

`kube` pushes the image directly into the cluster after building, we could probably do something similar to avoid needing permissions to push to the gh image registry

**Comment by blt** [comment]
@jszwedko I believe you made this possible, yes?

**Comment by jszwedko** [comment]
Oh yes per https://github.com/vectordotdev/vector/pull/11474
