### ISSUE TITLE
function "to_timestamp" supports only seconds.

### ISSUE THREAD

**Issue by StefanSa** [vectordotdev/vector#10655]
hi there,
function "to_timestamp" supports only seconds.

unix-time = `1641202469000000000` with `.event.stop = to_timestamp(.event.stop)` i get this error:
```
Mapping failed with event. error="function call error for \"to_timestamp\" at (430:455): unable to coerce 1641202469000000000 into \"timestamp\"" internal_log_rate_secs=30
```
The same behavior with 'milliseconds'

According to the documentation the function `to_timestamp` is fallible, but with `to_timestamp!` i get this error message:
```
error[E620]: can't abort infallible function
   ┌─ :12:15
   │
12 │ .event.stop = to_timestamp!(.event.stop)
   │               ^^^^^^^^^^^^- remove this abort-instruction
   │               │
   │               this function can't fail
```

**Comment by spencergilbert** [comment]
Hey @StefanSa - are you getting that fallibility error at Vector runtime, or in the VRL REPL?

Looking through the code, the seconds only _seems_ intentional - so this would likely be a feature request. However I'll verify this ASAP.

**Comment by jszwedko** [comment]
Hi @StefanSa !

That's correct, `to_timestamp` only takes unix timestamps. If you know the timestamp is a nanosecond timestamp, as it appears to be here, I recommend using `to_timestamp(.timestamp / 1000000000)`.

The fact that `to_timestamp` fails there even though it compiles as infallible is being tracked by #9501 .

I'll close this out since I don't think there is anything to do here, but please feel free to reopen if you have any other thoughts.

**Comment by StefanSa** [comment]
> Hi @StefanSa !
> 
> That's correct, `to_timestamp` only takes unix timestamps. If you know the timestamp is a nanosecond timestamp, as it appears to be here, I recommend using `to_timestamp(.timestamp / 1000000000)`.
> 
> The fact that `to_timestamp` fails there even though it compiles as infallible is being tracked by #9501 .
> 
> I'll close this out since I don't think there is anything to do here, but please feel free to reopen if you have any other thoughts.

@jszwedko 
I get the error `E630`, no matter with or without `!`
```
error[E630]: fallible argument
   ┌─ :14:29
   │
14 │ .event.stop = to_timestamp!(.event.stop / 1000000000)
   │                             ^^^^^^^^^^^^^^^^^^^^^^^^
   │                             │
   │                             this expression can fail
   │                             handle the error before passing it in as an argument
```

**Comment by spencergilbert** [comment]
> @jszwedko 
> I get the error `E630`, no matter with or without `!`
> ```
> error[E630]: fallible argument
>    ┌─ :14:29
>    │
> 14 │ .event.stop = to_timestamp!(.event.stop / 1000000000)
>    │                             ^^^^^^^^^^^^^^^^^^^^^^^^
>    │                             │
>    │                             this expression can fail
>    │                             handle the error before passing it in as an argument
> ```

You can't divide a non int/float, so you would need to ensure it's dividable first, `int!(.event.stop) / 10000000000`

**Comment by StefanSa** [comment]
thanks again Spencer / Jesse
