### ISSUE TITLE
enhancement(observability): update to the latest `metrics` release

### ISSUE THREAD

**Issue by tobz** [vectordotdev/vector#10658]
Once a new minor release is cut upstream by `metrics` (including subcrates), we should update `vector` as well.

This will give us the ability to better describe metrics (without actually emitting them at a default zero value) ahead of time, as well as the ability to opt-in to using "metric handles", which provide a means to reduce the overhead of updating a specific metric by a significant amount.  In most cases, updating metrics would be as fast as directly operating on an atomic integer.

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/13663
