### ISSUE TITLE
Decide which other transforms should have additional outputs

### ISSUE THREAD

**Issue by 001wwang** [vectordotdev/vector#10660]
The following transforms are documented as of `v0.19.0`
- Remap
- Aggregate
- AWS Cloudwatch Logs Subscription Parser (marked as deprecated)
- AWS EC2 Metadata
- Dedupe
- **Filter** 
  - Output for dropped events?
- GeoIP
- **Log to metric**
  - Output per configured metric?
- **Lua**
  - Output for dropped events?
- Metric to Log
- Reduce
- **Route**
  - Refactor to use named outputs rather than the macro expansion?
- Sample
- Tag Cardinality Limit
- Throttle
- WASM (marked as deprecated)

Of these, it seems like it may make sense to add additional outputs to `filter`, `log_to_metric`, `lua`, and `route` (refactoring). The potential added outputs are listed above. The selection is based on whether the transform can drop events that users might then want to handle and whether the transform produces multiple events from a single event. cc: @jszwedko @lukesteensen

**Comment by lukesteensen** [comment]
> Remap

We have `dropped` already, which I think is a good start. Longer term we could consider some way to natively send to user-defined outputs via remap, but I think that's outside of the scope of this issue.

> Aggregate
> AWS Cloudwatch Logs Subscription Parser (marked as deprecated)
> AWS EC2 Metadata
> Dedupe
> Metric to Log
> Reduce
> Sample
> Throttle
> WASM (marked as deprecated)

Nothing useful I can think of for these. 

> Filter: Output for dropped events?

I think this would start to overlap with `route` too much. With some improvements there (e.g. an optional `else` output, exclusive routing), this would be redundant.

> GeoIP

Maybe an output for events that don't find a match? Not sure if that's common/useful or not. We could also consider deprecating this as a standalone transform and encouraging use via remap, which would make changes unnecessary.

> Log to metric: Output per configured metric?

I'm skeptical that an output per metric would be useful, but maybe an output for logs that fail to process into a metric?

> Lua: Output for dropped events?

I can see a good argument for dropped, similar to remap, but I'd consider it pretty low priority if we do it at all. Same with the remap idea of user-specified outputs.

> Route: Refactor to use named outputs rather than the macro expansion?

Yes, I think removing expansion would be a big win here. At first it'd just be for efficiency, but it'd also enable exclusive routing (i.e. send only to the first match) and an `else` output, etc. And being one step closer to removing macro expansion 😄 

> Tag Cardinality Limit

@jszwedko brought up the idea of emitting some kind of notification from this transform when the limit is hit. I think it's an interesting idea, but I hesitate to just go ahead and do it without thinking through the potential overlap that pattern might have with the internal logs source.

**Comment by 001wwang** [comment]
Nice, the above makes sense to me. It seems like the most relevant thing to work on while discussion continues would be refactoring `route`. Would it make sense to get started on that?

**Comment by spencergilbert** [comment]
Agree with everything @lukesteensen said above - GeoIP is probably early, but perhaps a contender to be folded into the existing enrichment table work in `remap`?

**Comment by lukesteensen** [comment]
@001wwang 

> It seems like the most relevant thing to work on while discussion continues would be refactoring `route`. Would it make sense to get started on that?

Sure, that would be a good place to start since we know we want to do it and the first version wouldn't involve any user-facing changes that we'd need to agree on.

**Comment by jszwedko** [comment]
Thanks for this write-up!

> > Remap
> 
> We have `dropped` already, which I think is a good start. Longer term we could consider some way to natively send to user-defined outputs via remap, but I think that's outside of the scope of this issue.

Agree.

> > Aggregate
> > AWS Cloudwatch Logs Subscription Parser (marked as deprecated)
> > AWS EC2 Metadata
> > Dedupe
> > Metric to Log
> > Reduce
> > Sample
> > Throttle
> > WASM (marked as deprecated)
> 
> Nothing useful I can think of for these.

Agree

> > Filter: Output for dropped events?
> 
> I think this would start to overlap with `route` too much. With some improvements there (e.g. an optional `else` output, exclusive routing), this would be redundant.

Agree

> > GeoIP
> 
> Maybe an output for events that don't find a match? Not sure if that's common/useful or not. We could also consider deprecating this as a standalone transform and encouraging use via remap, which would make changes unnecessary.

I'm assuming that currently, when this happens, the event just isn't enriched. I think users can route on this if needed.

> > Log to metric: Output per configured metric?
> 
> I'm skeptical that an output per metric would be useful, but maybe an output for logs that fail to process into a metric?

Agreed, I could see routing log events that can't be processed into metrics.

> > Lua: Output for dropped events?
> 
> I can see a good argument for dropped, similar to remap, but I'd consider it pretty low priority if we do it at all. Same with the remap idea of user-specified outputs.

I think, with the `lua` transform, we won't know when events are dropped since it is a task-style transform that can consume multiple events before emitting an event.

We could allow capturing "events" that couldn't be marshaled back into Vector events, but I agree this seems low priority. If this occurs, it generally indicates an issue with the user's Lua script which the internal logs should prompt them to correct.

> > Route: Refactor to use named outputs rather than the macro expansion?
> 
> Yes, I think removing expansion would be a big win here. At first it'd just be for efficiency, but it'd also enable exclusive routing (i.e. send only to the first match) and an `else` output, etc. And being one step closer to removing macro expansion 😄

👍 to working on this first.

> > Tag Cardinality Limit
> 
> @jszwedko brought up the idea of emitting some kind of notification from this transform when the limit is hit. I think it's an interesting idea, but I hesitate to just go ahead and do it without thinking through the potential overlap that pattern might have with the internal logs source.

I agree with Luke that some use-cases we _could_ use named outputs for could overlap with `internal_logs` (like emitting an event when `tag_cardinality_limit` limits a metric). This would bring Vector's logs into its compatibility guarantees though which is a big enough shift that an RFC would likely be warranted. I'd suggest just deferring those use-cases for now.

So it sounds like, for now, we should just refactor `route`.

**Comment by 001wwang** [comment]
Sounds good, the `route` refactor to using multiple outputs is done as of #10738.

**Comment by jszwedko** [comment]
Sweet, I think we can close this out then. Nice work!
