### ISSUE TITLE
Github Support button does not work.

### ISSUE THREAD

**Issue by ryansliceup** [vectordotdev/vector#10681]
Hello, if you were to go to issues, Click New Issue, and then click Support. The page does not work. I am trying to get a hand on parsing the severity of cisco logs, but don't know where to ask. 

ryan@vader:~$ dig @8.8.8.8 discussions.vector.dev

; <<>> DiG 9.16.1-Ubuntu <<>> @8.8.8.8 discussions.vector.dev
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 20015
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;discussions.vector.dev.                IN      A

;; AUTHORITY SECTION:
vector.dev.             1800    IN      SOA     dns1.p04.nsone.net. domains+netlify.netlify.com. 1638688502 43200 7200 1209600 3600

;; Query time: 72 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Jan 04 12:34:37 UTC 2022
;; MSG SIZE  rcvd: 132

ryan@vader:~$ dig @8.8.8.8 discussions.vector.dev

**Comment by spencergilbert** [comment]
It looks like there's not an entry for that anymore, but appears to be duplicative of `Chat`. I'm verifying internally and will fix today 👍

**Comment by spencergilbert** [comment]
Took some finagling, but looks like I've gotten it fixed now!
