### ISSUE TITLE
format time using a custom time zone

### ISSUE THREAD

**Issue by RuiFG** [vectordotdev/vector#10690]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Current Vector Version

```
0.19.0
```

### Use-cases
I'm a Chinese programmer, so I use `UTC+08:00` in all programs for convenience, I found that the time zone used to format time is `UTC` when use vector's `key partitioner`,and it can't be change.

`1641349047 %Y-%m-%d %h`  Got : `2022-01-05 02`  Expected : `2022-01-05 10`

### Attempted Solutions

```
[sources.kafka]
type = "kafka"
bootstrap_servers = "127.0.0.1:9092"
group_id = "vector-s3"
topics = ["vector-k8s"]
auto_offset_reset= "latest"

[transforms.parse]
type = "remap"
inputs = [ "kafka" ]
drop_on_error= true
source = """
. =parse_json!(.message)
...................................
# fix me, wait for formatting time to support the custom time zone.
# now the label is a key partition.
.label= to_timestamp(to_unix_timestamp(now())+28800), format: "%Y-%m-%d/%H-")
"""

[sinks.s3]
type = "aws_s3"
inputs = [ "parse" ]
bucket = "ic-k8s"
key_prefix = "{{ label }}"
compression = "gzip"
encoding.codec= "ndjson"
endpoint= "http://xxxxx.com"
auth.access_key_id= "xxxxxxx"
auth.secret_access_key= "xxxxxx"
batch.max_bytes= 209715200
batch.timeout_secs= 600
filename_extension= "gz"
```
### Proposal

add  global config `partitioner.timezone` or use `timezone`, use it as the time zone of the key partition format

**Comment by jszwedko** [comment]
Closing in-lieu of https://github.com/vectordotdev/vector/issues/14160
