### ISSUE TITLE
Add HTTP ready check

### ISSUE THREAD

**Issue by LucioFranco** [vectordotdev/vector#1073]
# Motivation

As a user, I'd like to be able to query a vector http endpoint that could tell me when vector is ready to receive traffic or crashed due to a config error.

## Prior art

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request

# Proposal

Add an HTTP endpoint that returns `status: 200` once vector is ready to start receiving events.

# Question

- What type of url do we want to serve this on?
- Is there any specific information we might want to expose as well?

**Comment by a-rodin** [comment]
Is this different from a general health check endpoint that can be called regularly to ensure that Vector is still working without issues?

Also, would it make sense to additionally provide health checks for separate sources/sinks? For example, if Vector writes data to HTTP sink and currently it is not healthy, we might want to expose this information to stop writing data to Vector.

**Comment by afoninsky** [comment]
I would say that the most flexible solution will be - to provide endpoint where user can choose what components he wants to check. Examples:
- "/health" will return healthiness of all components and can be used for readiness probe
- "/health?names=tcp-out,kafka" will act as liveness check

**Comment by leebenson** [comment]
This is implemented in #3514 as a `/health` endpoint. I'll close this for now since it's being tracked in that issue.

**Comment by binarylogic** [comment]
Noting that this was actually implemented in https://github.com/timberio/vector/pull/3708.
