### ISSUE TITLE
Adjust GraphQL API for multiple outputs

### ISSUE THREAD

**Issue by lukesteensen** [vectordotdev/vector#10745]
As part of #10640, we changed the modeling of component outputs to make them more flexible. This ran into a bit of trouble with the GraphQL API, which has some relatively baked-in assumptions about the shape of such things. For example, there is a single output type field on sources which is wired in to be sortable, etc, in a way that made it non-obvious how best to translate to the new model.

As a followup to that PR, we should have someone more familiar with the API, its backwards-compatibility concerns, etc, weigh in on the best path forward. It'd also be nice to think of ways to reduce this kind of coupling in the future.

**Comment by leebenson** [comment]
I'll get familiar with #10640 and consider the GraphQL changes required.

**Comment by lukesteensen** [comment]
Thanks @leebenson! The short version is basically that `output_type: DataType` and `named_outputs: Vec<String>` are now combined into a more general `outputs: Vec<Output>` where `Output { port: Option<String>, ty: DataType }`, for both sources and transforms. So the scalar field is now an array and types can vary independently.

**Comment by leebenson** [comment]
Thanks @lukesteensen. That seems reasonable. I'll wait for #10640 to land, then will follow up with some proposed GraphQL changes to reflect the new model.

**Comment by leebenson** [comment]
(Unless you are/anticipating running into GraphQL issues as part of that same PR preventing compilation. In which case, I could work against that same branch.)

**Comment by lukesteensen** [comment]
It's not a blocker for the PR, so no rush!

**Comment by lukesteensen** [comment]
@001wwang was this done as part of your work on `top`?

**Comment by 001wwang** [comment]
Ah, yes, I think this can be considered complete from #10964.
