### ISSUE TITLE
Install script installs wrong version on Alpine Linux

### ISSUE THREAD

**Issue by ilcylic** [vectordotdev/vector#10740]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

As the title says, running the install command as found here: https://vector.dev/docs/setup/installation/

```
curl --proto '=https' --tlsv1.2 -sSf https://sh.vector.dev | bash
```

results in the wrong version being installed on my Alpine Linux 3.15 system..

```
# curl --proto '=https' --tlsv1.2 -sSf https://sh.vector.dev | bash
                                   __   __  __
                                   \ \ / / / /
                                    \ V / / /
                                     \_/  \/

                                   V E C T O R
                                    Installer


--------------------------------------------------------------------------------
Website: https://vector.dev
Docs: https://vector.dev/docs/
Community: https://vector.dev/community/
--------------------------------------------------------------------------------

>>> We'll be installing Vector via a pre-built archive at https://packages.timber.io/vector/0.19.0/
>>> Ready to proceed? (y/n)

>>> y

--------------------------------------------------------------------------------

musl libc (x86_64)
Version 1.2.2
Dynamic Program Loader
Usage: /lib/ld-musl-x86_64.so.1 [options] [--] pathname
>>> Unknown architecture from ldd: 
>>> Downloading Vector via https://packages.timber.io/vector/0.19.0/vector-0.19.0-x86_64-unknown-linux-gnu.tar.gz ✓
>>> Unpacking archive to /root/.vector ... ✓
>>> Adding Vector path to /root/.zprofile>>> Adding Vector path to /root/.profile ✓
>>> Install succeeded! 🚀
>>> To start Vector:

    vector --config ~/.vector/config/vector.toml

>>> More information at https://vector.dev/docs/
```

I expect it's an issue with either the script calling alpine's ldd incorrectly, or parsing its output incorrectly.  But I could be wrong.

### Vector Version

```
0.19.0
```

### Expected Behavior

Download and install vector-0.19.0-x86_64-unknown-linux-musl.tar.gz

### Actual Behavior

Downloaded and installed vector-0.19.0-x86_64-unknown-linux-gnu.tar.gz

### Additional Context

```
# uname -vr
5.15.12-0-lts #1-Alpine SMP Fri, 31 Dec 2021 13:23:07 +0000

# cat /etc/alpine-release 
3.15.0

# ldd --version
musl libc (x86_64)
Version 1.2.2
Dynamic Program Loader
Usage: /lib/ld-musl-x86_64.so.1 [options] [--] pathname
```

### Workaround

Download and install vector-0.19.0-x86_64-unknown-linux-musl.tar.gz manually.

**Comment by spencergilbert** [comment]
So looking at the [`install.sh`](https://github.com/vectordotdev/vector/blob/master/distribution/install.sh), we should be getting the correct `ldd` based on your output and [this](https://github.com/vectordotdev/vector/blob/master/distribution/install.sh#L219-L228).

I suspect the error may be coming from [this](https://github.com/vectordotdev/vector/blob/master/distribution/install.sh#L273-L447) section.

Could you run `uname -s` and `uname -m` and we can compare them with the logic there?

**Comment by ilcylic** [comment]
```
# uname -sm
Linux x86_64
```

**Comment by spencergilbert** [comment]
Actually, it looks like the problem is [here](https://github.com/vectordotdev/vector/blob/master/distribution/install.sh#L219-L228), testing across a number of different platforms I keep getting:

```bash
>>> Unknown architecture from ldd:...
```
