### ISSUE TITLE
Handle non UTF-8 payloads for the splunk_hec source

### ISSUE THREAD

**Issue by 001wwang** [vectordotdev/vector#10778]
As a user highlighted, the `splunk_hec` source errors when a request to `/services/collector/event` includes a JSON event with non UTF-8 characters. For example, `{"event": "\xe4"}` results in 
```
ERROR source{component_kind="source" component_id=in component_type=splunk_hec component_name=in}: vector::internal_events::splunk_hec::source: Invalid request body. error=Custom { kind: InvalidData, error: Error("invalid unicode code point", line: 1, column: 37) } error_type="parse_failed" stage="processing" internal_log_rate_secs=10
```
This is because the `splunk_hec` source parses the request body into JSON with `serde_json::Deserializer::<serde_json::Value>` where `Value::String` involves a Rust `String` that must be `UTF-8`. 

On the other hand, an actual Splunk HEC instance (tested using `v8.2.4`) does accept such payloads, replacing invalid characters with a replacement char �. 

We should consider performing some sort of lossy conversion and/or redirecting the invalid input to a separate output of the source to handle this scenario.

**Comment by tobz** [comment]
I was really hoping they just rejected non-UTF-8 payloads. 😂 

Well, if they use the replacement character, we could probably implement that as the default behavior, with an optional configuration to send invalid payloads to a named output specifically designated for such requests?

Matching behavior is likely priority #1 if we can do it safely -- which I think we can with `String::from_utf8_lossy` -- but having an off-ramp for further auditing would likely prove fruitful for customers, hence the named outputs optional bit.
