### ISSUE TITLE
401 Unauthorized for GCP related sinks after a while

### ISSUE THREAD

**Issue by dacaga** [vectordotdev/vector#10828]
After executing properly for a while on a GKE pod, both of my GCP related sinks (Stackdriver and Google Cloud Storage) start giving me 401 Unauthorized errors.

~The underlying librairies~ GcpAuthConfig/GcpCredentials don't seem to be handling ~JWT~ access token renewal/refetch from the [Metadata Server](https://cloud.google.com/kubernetes-engine/docs/concepts/workload-identity#metadata_server) properly (since I'm not using a service account private key).

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version
From the Docker image `timberio/vector:0.18.1-debian`

```
0.18.1
```

### Vector Configuration File
```toml
[sinks.stackdriver]
type = "gcp_stackdriver_logs"
inputs = [ "stdin" ]
log_id = "logid"
project_id = "projectid"

[sinks.stackdriver.resource]
type = "global"

[sinks.gcs]
type = "gcp_cloud_storage"
inputs = [ "stdin" ]
bucket = "bucket"
key_prefix = "%F/"
compression = "gzip"
storage_class = "COLDLINE"

[sinks.gcs.encoding]
codec = "ndjson"
```
### Actual Behavior
After a few hours of execution, the ~JWT~ access token expires and every time Vector tries to flush to its GCP related sinks I get this from stderr:
```
ERROR sink{component_kind="sink" component_id=gcs component_type=gcp_cloud_storage component_name=gcs}:request{request_id=6}: vector::sinks::util::retries: Not retriable; dropping the request. reason="response status: 401 Unauthorized"

...

ERROR sink{component_kind="sink" component_id=stackdriver component_type=gcp_stackdriver_logs component_name=stackdriver}:request{request_id=192}: vector::sinks::util::sink: Response failed. response=Response { status: 401, version: HTTP/1.1, headers: {"www-authenticate": "Bearer realm=\"https://accounts.google.com/\", error=\"invalid_token\"", "vary": "X-Origin", "vary": "Referer", "vary": "Origin,Accept-Encoding", "content-type": "application/json; charset=UTF-8", "date": "Mon, 10 Jan 2022 00:10:14 GMT", "server": "ESF", "cache-control": "private", "x-xss-protection": "0", "x-frame-options": "SAMEORIGIN", "x-content-type-options": "nosniff", "accept-ranges": "none", "transfer-encoding": "chunked"}, body: b"{\n  \"error\": {\n    \"code\": 401,\n    \"message\": \"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.\",\n    \"status\": \"UNAUTHENTICATED\",\n    \"details\": [\n      {\n        \"@type\": \"type.googleapis.com/google.rpc.ErrorInfo\",\n        \"reason\": \"ACCESS_TOKEN_EXPIRED\",\n        \"domain\": \"googleapis.com\",\n        \"metadata\": {\n          \"method\": \"google.logging.v2.LoggingServiceV2.WriteLogEntries\",\n          \"service\": \"logging.googleapis.com\"\n        }\n      }\n    ]\n  }\n}\n" }
```

**Comment by dacaga** [comment]
> Is the auth tied to the ServiceAccount being used with the Vector pod?

Yes and I double checked, the owner of the created objects on the GCS bucket is the pod's ServiceAccount.

>What version of Kubernetes are you running?

1.18.20-gke.4501

**Comment by spencergilbert** [comment]
I'm wondering if it's similar to https://github.com/vectordotdev/vector/issues/8616#issuecomment-1010281331, seems like Kubernetes has added some rotation times to service accounts.

**Comment by dacaga** [comment]
I don't think it's related since, in this case, the GCS and Stackdriver sinks are authenticating using a token grabbed from the GKE Metadata Server here: https://github.com/vectordotdev/vector/blob/316089253076748428012292be39771b197fc4ff/src/sinks/gcp/mod.rs#L60-L86

It's kept up-to-date with the task: https://github.com/vectordotdev/vector/blob/ea0d002f4f26522764314f176af6a0e6c3adc28c/src/sinks/gcp/mod.rs#L131-L150

FYI: It has now been running in production for 2 days without any 401 error. It makes me think that it might be related to some sporadic and uncaught error with the Metadata Server.

Also, prior to the 401 errors I had, there are no signs in the logs that there had been a problem with the token renewal (nothing in the logs that says "Failed to update GCP authentication token.")

**Comment by spencergilbert** [comment]
Ah, gotcha - wasn't sure what it got tied to for auth. We could look to add more logging into the regen process if it comes up again, otherwise I'm not sure there's a good course of action.

**Comment by dacaga** [comment]
My thoughts too. It has not happened again yet. I'll keep en eye on it. You can close the issue if you want and I'll reopen if it happens again and I manage to catch more data.

**Comment by mloughran** [comment]
I am also seeing this sporadically. Scanning through vector logs this seems to recover automatically after < 1 minute, however I just experienced a 15 minute log outage on 1 VM, which again automatically recovered.

Running vector 0.19.1 on debian buster.

**Comment by jdoupe** [comment]
I am having this issue as well.  At first it seemed to happen hourly and I thought it might be related to token expiration, but now sometimes it'll run for several hours.

```
2022-05-06T00:30:17.542658Z ERROR sink{component_kind="sink" component_id=mylogs component_type=gcp_cloud_storage component_name=mylogs}:request{request_id=709}: vector::sinks::util::retries: Not retriable; dropping the request. reason="response status: 401 Unauthorized"
```

```
vector 0.20.0 (x86_64-unknown-linux-gnu 2a706a3 2022-02-11)
```

**Comment by bruceg** [comment]
I think this should be fixed by #12645, which should be in tonight's nightly build. Could you test and see if this is still happening for you?

**Comment by jdoupe** [comment]
Unfortunately it still occurred.
```
...
2022-05-11T21:31:02.875038Z  INFO vector: Vector has started. debug="false" version="0.22.0" arch="x86_64" build_id="e584ef2 2022-05-11"
...
2022-05-11T22:32:52.009788Z ERROR sink{component_kind="sink" component_id=mylogs component_type=gcp_cloud_storage component_name=gcs_doppler_logs}:request{request_id=12781}: vector::sinks::util::retries: Not retriable; dropping the request. reason="response status: 401 Unauthorized"
```

**Comment by bruceg** [comment]
I think this has been fixed by #12757 which was just merged, at least I was unable to reproduce the problem after several hours of continuous running. Are you set up to build from sources to test if this fixes the problem for you?

**Comment by jdoupe** [comment]
🤞  I've built and have it running.  I'll let it run overnight and post any updates.

**Comment by jdoupe** [comment]
In case you were wondering about how how much data we have flowing through, attached is a screenshot of vector top after an hour, right after the token goes bad (not that this indicates anything)

![image](https://user-images.githubusercontent.com/2040703/169395222-5ca8779a-2d56-4929-baf4-4c4af3c07903.png)

I ran today's nightly with debug, and there's no mention of it even trying to renew the token.

**Comment by jszwedko** [comment]
@jdoupe which nightly did you run with (what does `vector --version` say?)? The nightly build actually failed due to a network issue so it was only published ~7 hours ago when I reran it.

**Comment by jdoupe** [comment]
vector 0.22.0 (x86_64-unknown-linux-gnu 50dd7a7 2022-05-19)

**Comment by jszwedko** [comment]
Thanks for confirming @jdoupe . That should be after https://github.com/vectordotdev/vector/pull/12757 so it seems like maybe something is still amiss here. cc/ @bruceg

**Comment by bruceg** [comment]
I have set up a test configs sending to both `gcp_pubsub` and `gcp_cloud_storage` and have yet to reproduce this problem. I added a debug statement in the code and verified that the refresh is happening. I'm not sure how to diagnose this further.

**Comment by jdoupe** [comment]
Should I see the renewal debug output with the current nightly?  (With just a single -v?)

**Comment by bruceg** [comment]
No, I will be submitting a PR for adding the details, as it would be useful for future diagnosis.

**Comment by jdoupe** [comment]
Running `vector 0.22.0 (x86_64-unknown-linux-gnu b002bfb 2022-05-22)` for a few hours now... 

Things looking good thus far.

```
$ grep -i "vector::gcp" vector.log.0.22.0.b002bfb.t8v
2022-05-22T15:34:47.368968Z DEBUG vector::gcp: Fetching GCP authentication token. ...
2022-05-22T16:04:46.691864Z DEBUG vector::gcp: Renewing GCP authentication token.
2022-05-22T16:04:46.691958Z DEBUG vector::gcp: Fetching GCP authentication token. ...
2022-05-22T16:34:45.692488Z DEBUG vector::gcp: Renewing GCP authentication token.
2022-05-22T16:34:45.692595Z DEBUG vector::gcp: Fetching GCP authentication token. ...
2022-05-22T17:04:44.692505Z DEBUG vector::gcp: Renewing GCP authentication token.
2022-05-22T17:04:44.692617Z DEBUG vector::gcp: Fetching GCP authentication token. ...
2022-05-22T17:34:43.692100Z DEBUG vector::gcp: Renewing GCP authentication token.
2022-05-22T17:34:43.692201Z DEBUG vector::gcp: Fetching GCP authentication token. ...
2022-05-22T18:04:42.691824Z DEBUG vector::gcp: Renewing GCP authentication token.
2022-05-22T18:04:42.691934Z DEBUG vector::gcp: Fetching GCP authentication token. ...
```

**Comment by bruceg** [comment]
Great, thanks for confirming.

**Comment by RobertSLane** [comment]
Hey @bruceg . I appreciate this issues has been closed for some months now, however we are seeing this problem when trying to send data to our GCS bucket from Vector.

We have Vector running in Kubernetes, and we have found that we can send data to GCS for some time after restarting our Vector pods, but after a while we start getting 401s (assuming because Vector has failed to refresh its token). Any possibility this problem has been reintroduced?

The Vector image we are using is timberio/vector:0.24.1-alpine

**Comment by bruceg** [comment]
@RobertSLane Do you have healthchecks disabled by chance? The code for these sinks only starts the token refresh after a response from a healthcheck. See #13058 for details.

**Comment by jkachmar** [comment]
i have health checks enabled but i'm seeing this with the [GCP Cloud Monitoring sink](https://vector.dev/docs/reference/configuration/sinks/gcp_stackdriver_metrics/). it seems to consistently fail with 401 errors after about an hour or so.

i've looked through the code and i guess this is the addition which is present in a couple different sinks (but not, afaict, the cloud monitoring one):
https://github.com/vectordotdev/vector/blob/ea17c1f2c95c3b6b950f20079f1ec11b6efe03b7/src/sinks/gcp/pubsub.rs#L111

i have a local branch that i'm using with a workaround for #14890, so i'll see if it's not too much to add a similar health check to the cloud monitoring code path as well.

**Comment by ansel1** [comment]
@jkachmar did you resolve this?  We're still seeing this behavior with v0.29.1.  After running for an hour, we get token expired errors: 

2023-04-27T12:03:47.174065Z ERROR sink{component_kind="sink" component_id=gcp component_type=gcp_stackdriver_metrics component_name=gcp}:request{request_id=6983}: vector::sinks::util::sink: Response failed. response=Response { status: 401, version: HTTP/1.1, headers: {"www-authenticate": "Bearer realm=\"https://accounts.google.com/\", error=\"invalid_token\"", "vary": "Origin", "vary": "X-Origin", "vary": "Referer", "content-type": "application/json; charset=UTF-8", "transfer-encoding": "chunked", "date": "Thu, 27 Apr 2023 12:03:47 GMT", "server": "ESF", "cache-control": "private", "x-xss-protection": "0", "x-frame-options": "SAMEORIGIN", "x-content-type-options": "nosniff"}, body: b"{\n  \"error\": {\n    \"code\": 401,\n    \"message\": \"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.\",\n    \"status\": \"UNAUTHENTICATED\",\n    \"details\": [\n      {\n        \"@type\": \"type.googleapis.com/google.rpc.ErrorInfo\",\n        \"reason\": \"ACCESS_TOKEN_EXPIRED\",\n        \"domain\": \"googleapis.com\",\n        \"metadata\": {\n          \"method\": \"google.monitoring.v3.MetricService.CreateTimeSeries\",\n          \"service\": \"monitoring.googleapis.com\"\n        }\n      }\n    ]\n  }\n}\n" }

**Comment by spencergilbert** [comment]
@ansel1 would you mind filling out a new bug report and fill out the sections in the template?
