### ISSUE TITLE
retry behavior in elasticsearch sink

### ISSUE THREAD

**Issue by uburro1** [vectordotdev/vector#10839]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Current Vector Version

```
latest
```

### Use-cases

Our logs delivery stack is filebeat -> kafka -> vector -> elasticsearch. Currently vector retries occur in the following cases: Vector will retry failed requests (status == 429, >= 500, and != 501).

That is, if for some reason the user does not pass authorization in elasticsearch (wrong roles, no user, wrong password) - the logs will be lost because elasticsearch will return the 403 code.

### Proposal

 Need to change the behavior of the elasticsearch plugin. Retry any response that is not 200, with the exception of codes 400, 404 and 409, retry is not needed in this case.

**Comment by jszwedko** [comment]
Hi @uburro1 !

This is a problem I've been thinking about as well and is not limited to just the Elasticsearch sink. I opened a new issue for discussion around this: https://github.com/vectordotdev/vector/issues/10870 . I'll close this one out, but feel free to leave any additional thoughts there.
