### ISSUE TITLE
New `splunk_hec` source

### ISSUE THREAD

**Issue by ktff** [vectordotdev/vector#1088]
### Description

A new source that partially implements Splunk HTTP Event Collector REST API. This `splunk_hec source` will be able to recieve logs in splunk format.

### Motivation

One of use cases for this is being able to collect logs from Docker over `splunk` log driver. This is usefull in constrained enviorments like ECS where Fargate only supports three log drivers, one AWS propriatery, one custom for fluentd, and splunk. (#813)

### Prior art

Vector already has [`splunk_hec sink`](https://docs.vector.dev/usage/configuration/sinks/splunk_hec). Implementation of this will be it's counterpart.

### Behavior

In short, `splunk_hec source` will listen for incoming `http` POST request, and construct log events from them.

Out of whole [Splunk HEC REST API](https://docs.splunk.com/Documentation/Splunk/7.3.2/Data/HECRESTendpoints), access points to be supported will be:
 - services/collector/event/1.0, for receiving logs in `inline` and `json` format
 - services/collector/raw/1.0, for receiving logs in `raw` format
 - services/collector/health, for passing health checks

Additionally:
 - `gzip`
 - `http` token authorization

will be supported.

This is a minimal set of functionalities that enable `splunk_hec source` to fully support receiving logs from Docker `splunk` log driver, Vector` splunk_hec sink`, and any other source which uses HEC only as a destination for logs.

### Configuration

```
[sources.my_source_id]
  type = "splunk_hec" 

  # The address to bind the socket to.
  # 
  # * optional
  # * default 0.0.0.0:8088
  address = "0.0.0.0:8088"

  # Splunk HEC token.
  # 
  # * required
  # * no default
  token = "A94A8FE5CCB19BA61C4C08"
```

### Implementation

Access point services/collector/event/1.0, will parse body of the request with `json` parser whose results will be flattened and turned into log events.

Access point services/collector/raw/1.0, will create a log event with body of the request as a `message`.

**Comment by LucioFranco** [comment]
All seems good to me 👍

**Comment by binarylogic** [comment]
Yep, looks fantastic, thanks for the detailed write-up.

**Comment by binarylogic** [comment]
Updated comment with an important question ^

**Comment by ktff** [comment]
Now that you mentioned it. I see one interesting version of `http` source. 


```
[sources.my_source_id]
  type = "http" 

  # Where requests are received
  # 
  # * required
  # * no default
  access_point = "http://localhost:9000/services/collector/event/1.0"

  # HTTP autohorization token.
  # 
  # * optional
  # * no default
  token = "A94A8FE5CCB19BA61C4C08"
```

It's simple, but would enable us/users to construct arbitrary `http` apis for receiving logs with configuration only.

`splunk source` could then be implemented with multiple of these sources configured and spun up, plus a health check.

**Comment by ktff** [comment]
@binarylogic if we would want a `http` source like the above, then it makes sense to implement it first. The reason being the difference in implementation, where independent `splunk source` implementation can use port for itself, the above `http` source can not. As such, `http` source will have to use a demultiplexer.

**Comment by ktff** [comment]
I would like to apply one more change to the specification. That is, also making token field optional. 

The benefit would be having one field less to configure from the start. But that would also make authorization an opt in feature. Which may or may not be a downside.

**Comment by ktff** [comment]
Completed with #1178
