### ISSUE TITLE
kubernetes log ordering

### ISSUE THREAD

**Issue by beorereleverion** [vectordotdev/vector#10883]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Current Vector Version

0.19.0

### Platform
Kubernetes with cri-o runtime

### Vector Configuration File
```[transforms.k8slog]
type = "remap"
inputs = ["kubernetes_logs"]
source = """
        if .kubernetes.container_id != null{
        .id=parse_regex!(.kubernetes.container_id,r'(?P<shortid>\\w{12})$').shortid
        .cn=.kubernetes.container_name
        .pn=.kubernetes.pod_name
        .ns=.kubernetes.pod_namespace
        if .kubernetes.pod_annotations.vectoraddress != null && .kubernetes.pod_annotations.vectortype != null{
                .va=.kubernetes.pod_annotations.vectoraddress
                .vt=.kubernetes.pod_annotations.vectortype
        }
        del(.timestamp)
        del(.file)
        del(.kubernetes)
        del(.source_type)
        del(.stream)
        }else{
        del(.)        
        abort 
        }
"""

[sinks.stdout]
type = "console"
inputs = ["k8slog"]
target = "stdout"
encoding = "json"
```

### Expected Behavior
All logs reads in right order

### Actual Behavior
Logs per pods can be shuffled(per file order) when k8s log file rotates by kubelet

### Use-cases

Reading the logs in the correct order simplifies their further processing

### Attempted Solutions

All log events from kubernetes logs, reads in right order

### Proposal

I propose to collect everything from the files to be read into the buffer. And also separately have FIFO files with an inode, which are sequentially added to it and removed as they are subtracted (or any other way to uniquely identify a file). and send files in the correct order according to the first file from FIFO, after successful sending - remove the file from the queue

### References

Discord conversation(last message https://discord.com/channels/742820443487993987/753400475545501836/931610741583249429)

**Comment by sillent** [comment]
Hi, we made the patch.
```
diff --git a/src/sources/kubernetes_logs/lifecycle.rs b/src/sources/kubernetes_logs/lifecycle.rs
index 9f6abdfc2..87d441a0d 100644
--- a/src/sources/kubernetes_logs/lifecycle.rs
+++ b/src/sources/kubernetes_logs/lifecycle.rs
@@ -8,7 +8,7 @@ use futures::{
     channel::oneshot,
     future::{select, BoxFuture, Either},
     pin_mut, ready,
-    stream::FuturesUnordered,
+    stream::FuturesOrdered,
     FutureExt, StreamExt,
 };

@@ -22,7 +22,7 @@ use crate::shutdown::{ShutdownSignal, ShutdownSignalToken};
 /// completing their work.
 #[derive(Debug)]
 pub struct Lifecycle<'bound> {
-    futs: FuturesUnordered<BoxFuture<'bound, ()>>,
+    futs: FuturesOrdered<BoxFuture<'bound, ()>>,
     fut_shutdowns: Vec<oneshot::Sender<()>>,
 }

@@ -43,7 +43,7 @@ impl<'bound> Lifecycle<'bound> {
     /// Create a new [`Lifecycle`].
     pub fn new() -> Self {
         Self {
-            futs: FuturesUnordered::new(),
+            futs: FuturesOrdered::new(),
             fut_shutdowns: Vec::new(),
         }
     }
```
We checked that patch and he solve the problem described here.
All read logs now correctly (with order) written to the sinks.

What do you think it is a normal solution?

**Comment by jszwedko** [comment]
Hi @sillent ! That is interesting! I actually don't see how that would impact how Vector reads from the pod log files. That change should just change the ordering of how the `kubernetes_logs` source shuts down (the source manages several independent tasks to read from the k8s API and the log files). Are you sure that it had the desired effect to file reading.

**Comment by sillent** [comment]
@jszwedko, yes, i don't know how, but it's really work.
we checked situation when one file is still handled,  kubelet rotate the log file and create another, and next file also run for handling too, but into the sink write lines from first file, after first file handling is done, line from other file is continuing write to the sink

**Comment by beorereleverion** [comment]
Thx, for @sillent . Issue can be closed
