### ISSUE TITLE
Update VRL error message URLs to use vector.dev

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#10937]
The VRL error messages use vrl.dev when we were more inclined to isolate the language. We should update these to use vector.dev

- [ ] Update VRL error messages to use vector.dev
- [ ] Ensure redirects work properly

**Comment by jszwedko** [comment]
We decided to keep vrl.dev for now. It has the advantages of:

* Keeping the URLs short due to not requiring a longer path that a `vector.dev` URL would need
* We may split the language out so canonical URLs for VRL content is useful
