### ISSUE TITLE
Warn when soaks are not synced with master

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#10931]
It'd be nice to throw a warning on soak results that have significant drift from master. For example, the [regressions reported here](https://github.com/vectordotdev/vector/pull/10890#issuecomment-1017309979) are likely due to improvements on master not included in this branch. Without the warning it looks as if the actual PR is a regression.

**Comment by blt** [comment]
We have a PR in-flight that will address: https://github.com/vectordotdev/vector/pull/10546
