### ISSUE TITLE
Remove transform expansion

### ISSUE THREAD

**Issue by lukesteensen** [vectordotdev/vector#10977]
While a creative solution given the limitations of Vector's model at the time, the macro-style expansion system for transforms should be replaced with something simpler that doesn't have the following drawbacks:

1. Confusing design where implementation of `TransformConfig` should be either expanded or built but never both, despite no API limitations around either
2. Potential recursion where expanded components must be themselves expanded, making it hard to reason about the concrete structure of a transform using expansion
3. Ambiguity about whether or not the expanded components should be considered equal to user-defined components in terms of observability, visibility as inputs, etc, or simply an implementation detail of a single logical component
4. Suboptimal performance characteristics when used as an implementation detail, where a direct implementation of the same functionality would easily be able to elide channel hops, extra copies and allocations, etc.

One potential solution could look roughly like the following:
* Introduce the idea of a compound transform within the `Transform` model directly, allowing internal composition of both branching and sequences of simpler transforms
* Add convenient helpers for composing and returning a compound transform from `TransformConfig::build`
* Migrate existing uses (the `compound` and `pipelines` transforms) to returning the new primitives directly from `build`, using those cases to flesh out the design (especially issues like the logical identity ambiguity mentioned above)
* Remove the `expand` system entirely once it's unused

**Comment by jszwedko** [comment]
Removed by https://github.com/vectordotdev/vector/pull/15577
