### ISSUE TITLE
Improve non-pipelines soaks

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#10986]
This issue focuses on soaks that do not include the `pipelines` transform since we have another issue focused on those soaks.

While our soak test results have improved significantly in the past few quarters, we still have work to do in order to hit the minimum 10mib/s/core goal that we set. We'd like to do another pass of profiling on non-pipelines soaks that fail to hit this minimum for the reported baseline mean.

The purpose of this issues is not to actually improve the performance, but to motivate upcoming work to ensure it's data driven and accurate.

## Requirements

The following soaks are the highest priority soaks that fall below 10mib/s/core for the reported baseline mean:

- [x] Improve `splunk_transforms_splunk3` soak (currently at 5.2MiB)
- [x] Improve `syslog_splunk_hec_logs` soak (currently at 9.5 MiB)
- [x] Improve `splunk_hec_route_s3` soak (currently at 2.02 MiB)
- [x] Improve `socket_to_socket_blackhole` soak
- [x] Improve `syslog_loki` soak (currently at 7.11 MiB)
- [x] Improve `syslog_regex_logs2metric_ddmetrics` soak (currently at 7.42 MiB)

**Comment by lukesteensen** [comment]
To close the loop on this one, all of these soaks are now above the threshold:

* `splunk_transforms_splunk3`: 12.0MiB
* `syslog_splunk_hec_logs`: 18.72MiB
* `splunk_hec_route_s3`: 15.72MiB
* `socket_to_socket_blackhole`: 23.5MiB
* `syslog_loki soak`: 16.69MiB
* `syslog_regex_logs2metric_ddmetrics`: 13.51MiB

There were a lot of changes that accumulated into these results, but a few of the most notable were:

* https://github.com/vectordotdev/vector/pull/11072#issuecomment-1050849652=
* https://github.com/vectordotdev/vector/pull/11587#issuecomment-1058394911
* https://github.com/vectordotdev/vector/pull/11289#issuecomment-1036863943=
* https://github.com/vectordotdev/vector/pull/11124#issuecomment-1038797411=
* https://github.com/vectordotdev/vector/pull/11605#issuecomment-1063128808=
* https://github.com/vectordotdev/vector/pull/11592#issuecomment-1054333207=
* https://github.com/vectordotdev/vector/pull/11365#issuecomment-1042117163=
