### ISSUE TITLE
Vector GCS Source

### ISSUE THREAD

**Issue by atibdialpad** [vectordotdev/vector#11015]
I noted that Vector has a GCS Sink but not a GCS source. 
Corresponding Logstash Plugin : https://www.elastic.co/guide/en/logstash/current/plugins-inputs-google_cloud_storage.html

**Comment by jszwedko** [comment]
Thanks @atibdialpad ! I realized this is actually a duplicate of https://github.com/vectordotdev/vector/issues/7501
