### ISSUE TITLE
TLS and Auth for prometheus_exporter sink

### ISSUE THREAD

**Issue by psi-4ward** [vectordotdev/vector#11041]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use-cases

The [prometheus_exporter sink](https://vector.dev/docs/reference/configuration/sinks/prometheus_exporter/) should provide `auth` and `tls` settings as counterpart to the [scrape config](https://vector.dev/docs/reference/configuration/sources/prometheus_scrape/#auth) so external connections can be secured without the need to setup an auth-proxy.

**Comment by zamazan4ik** [comment]
TLS configuration is supported right now: https://vector.dev/docs/reference/configuration/sinks/prometheus_exporter/#tls

The only missing part is `auth` support (Basic and Bearer).
