### ISSUE TITLE
Extract CN from client's SSL certificate

### ISSUE THREAD

**Issue by fpytloun** [vectordotdev/vector#11083]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Current Vector Version

```
0.19.1
```

### Use-cases

We use Vector's fluent input with mTLS to forward logs from Fluentbit instances. I would like to know which instance sent given log and I would like to extract it from CN of client's TLS certificate. This would also increase credibility of given log by mitigating flaw where client can fake log's content to act being someone else.

This is applicable to all inputs that supports client certificate verification.

### Proposal

Extract client's SSL certificate fields as defined by configuration (eg. Common Name) into record. These fields can then be used by transformations, filters, etc.

**Comment by hhromic** [comment]
This would be a very useful feature, in our team we fully support adding this as well 👍

**Comment by jszwedko** [comment]
Hi @fpytloun ! This is a good idea. I think it is covered by https://github.com/vectordotdev/vector/issues/2931 ? I'll close this one as a duplicate, but please feel free to add any additional thoughts there (and a 👍 emoji reaction to the issue which we use as one measure of demand).
