### ISSUE TITLE
Remove dependencies on shared/vector-common in VRL crates

### ISSUE THREAD

**Issue by JeanMertz** [vectordotdev/vector#11094]
https://github.com/vectordotdev/vector/pull/11087 is working to merge the `shared` and `vector-common` crates. Pulling in Vector-specific dependencies in VRL has long been avoided, since we're still potentially willing to pull out VRL into its own repository, possibly sometime this year.

This issue merely exists to track the progress of removing any hard dependencies on Vector in VRL, it is not something we want to do right now, but it's good to keep track of this situation for when we _do_ want to act on it.

**Comment by fuchsnj** [comment]
finished in https://github.com/vectordotdev/vector/pull/16953
