### ISSUE TITLE
[vrl] cannot index into array with variable

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#11108]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
vector 0.19.1 (x86_64-apple-darwin 3cf70cf 2022-01-25)

```

### Vector Configuration File

```
$ foo = [1]
$ offset = 0
$ foo[offset]

error[E203]: syntax error
  ┌─ :1:5
  │
1 │ foo[offset]
  │     ^^^^^^
  │     │
  │     unexpected syntax token: "Identifier"
  │     expected one of: "integer literal"
  │
  = see language documentation at https://vrl.dev
```

### Expected Behavior

VRL allows indexing into an array with a variable.

### Actual Behavior

VRL rejects this expression at compile time.

As a work around, `get` can be used:

```
get!(foo, [offset])
```

**Comment by JeanMertz** [comment]
Closing this in favour of #12547.
