### ISSUE TITLE
Support Kubernetes auth token rotation

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#11146]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Current Vector Version

```
vector 0.19.1 (x86_64-apple-darwin 3cf70cf 2022-01-25)
```

### Use-cases

Kubernetes >1.22 requires refreshing the auth token once an hour. Vector doesn't support this and so fails when the token becomes invalid.

### Attempted Solutions

It was suggested in https://github.com/vectordotdev/vector/issues/8616#issuecomment-1010281331 that one might be able to mount the token from the outside, but I'm not sure exactly what that would look like.

### Proposal

Implement auth token refresh.

### References

- Broken off from https://github.com/vectordotdev/vector/issues/8616#issuecomment-1010281331 to track separately.
- https://github.com/kube-rs/kube-rs/pull/768 adds support to `kube-rs` which we plan to migrate to

**Comment by spencergilbert** [comment]
If we opened an epic around the rewrite of the source already we should include this issue there

**Comment by jszwedko** [comment]
> If we opened an epic around the rewrite of the source already we should include this issue there

👍 created https://github.com/vectordotdev/vector/issues/11147 and added it there.
