### ISSUE TITLE
Building from source feature flags are woefully out-of-date

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#11173]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

We have a set of feature flags listed on https://vector.dev/docs/setup/installation/manual/from-source/#feature-flags but this list has not been kept up-to-date. I think we may want to consider dropping it and just pointing users to the Cargo.toml which we can ensure has better documentation.

**Comment by tshepang** [comment]
Maybe people aren't using that section much, otherwise there'd already be reports on it being outdated. I think pointing to Cargo.toml is a kool idea, at least until that part of the docs gets auto-generated.
