### ISSUE TITLE
Add SASL GSSAPI support to Kafka source/sink

### ISSUE THREAD

**Issue by Thor77** [vectordotdev/vector#11192]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Current Vector Version

```
vector 0.19.1 (x86_64-unknown-linux-gnu 3cf70cf 2022-01-25)
```

### Use-cases

I want to use Vector to read and write data from and into a Kafka cluster secured with SASL/GSSAPI.

### Proposal

As librdkafka has support for SASL/GSSAPI, it should be trivial to manipulate https://github.com/vectordotdev/vector/blob/master/src/kafka.rs to add the required options. This needs the --enable-gssapi flag when compiling librdkafka as well, though.

### References

- #4866
- #2897

**Comment by jszwedko** [comment]
Hi @Thor77 !

We are actually already compiling in GSSAPI support for Linux binaries. You can configure it via the `rdkafka` options:

* https://vector.dev/docs/reference/configuration/sources/kafka/#librdkafka_options
* https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

You can see where it is included here:

https://github.com/vectordotdev/vector/blob/9572c7d0a37d54447d14335fcc058a010a98c9e9/Cargo.toml#L393

**Comment by Thor77** [comment]
@jszwedko oh, I completely missed that option, thanks for the hint!
