### ISSUE TITLE
Instrument transforms with event processing metrics

### ISSUE THREAD

**Issue by jdrouet** [vectordotdev/vector#11217]
This issue represents the work required to bring all transforms into compliance with the event processing metrics [in the component observability spec](https://github.com/vectordotdev/vector/blob/master/docs/specs/component.md).

- [x] `add_fields`
- [x] `add_tags` (nothing to do)
- [x] `aggregate` (nothing to do)
- [x] `ansi_stripper`
- [x] `aws_cloudwatch_logs_subscriptions_parser`
- [x] `aws_ec2_metadata`
- [x] `coercer`
- [x] `compound` (nothing to do)
- [x] `concat`
- [x] `dedupe`
- [x] `field_filter` (nothing to do)
- [x] `geoip`
- [ ] `grok_parser`
- [x] `json_parser`
- [ ] `key_value_parser`
- [ ] `log_to_metric`
- [ ] `logfmt_parser`
- [ ] `lua`
- [x] `merge` (nothing to do)
- [ ] `metric_to_log`
- [x] `noop` (nothing to do)
- [ ] `pipelines`
- [x] `reduce` (nothing to do)
- [ ] `regex_parser`
- [ ] `remap`
- [x] `remove_fields` (nothing to do)
- [x] `remove_tags` (nothing to do)
- [x] `rename_fields` (nothing to do)
- [x] `route` (nothing to do)
- [x] `sample` (nothing to do)
- [ ] `split`
- [x] `tag_cardinality_limit` (nothing to do)
- [ ] `throttle`
- [ ] `tokenizer`

**Comment by jszwedko** [comment]
Copying https://github.com/vectordotdev/vector/pull/11219#pullrequestreview-875121301 over here:

> I think you could ignore updating deprecated transforms if you wanted though (look for development: "deprecated" in the cue docs or the lack of any docs for a given component).

**Comment by jdrouet** [comment]
All the transforms have been treated so we can close this
