### ISSUE TITLE
Internal metrics registry grows unbounded

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#11225]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Current Vector Version

```
vector 0.19.1 (x86_64-apple-darwin 3cf70cf 2022-01-25)
```

### Use-cases

Creating this as a more general representation of the issue in https://github.com/vectordotdev/vector/issues/10147. That is: metrics series in Vector's internal metrics registry never expire and so for metrics where the labels change over time will cause Vector to accumulate these metrics in definitely. An example of this is the `kubernetes_logs` source which tags metrics with `pod_name` which will have an unbounded cardinality over time.

### Proposal

Vector should expire metrics in the internal registry after a configurable time period.

**Comment by jszwedko** [comment]
Closing this in-lieu of https://github.com/vectordotdev/vector/issues/11995

**Comment by nabokihms** [comment]
We faced the same problem with kubernetes_logs sources. The problem affects more in the dynamic environments with vertical and horizontal autoscaling of pods (as was mentioned in linked issues). 

500 samples each two days per node.

![image](https://user-images.githubusercontent.com/32434187/169337351-dad745ce-9e66-4958-977b-5b9e66f992eb.png)

If the issue about expiring metrics (the `#11995`) is available to pick, I would like to work on it.

**Comment by jszwedko** [comment]
Hey @nabokihms !

You've been on a roll lately 😄 

This is a little bit of a bigger project (as outlined in #11995), but if you are up for it, we'd love the contribution. @tobz has thought a lot about this issue and should be able to provide any additional pointers or answer questions as you have them. Let us know if you do want to take a shot at it.

I meant to close this issue before in-lieu of https://github.com/vectordotdev/vector/issues/11995 but feel free to leave any additional thoughts or questions on that issue as you have them.

**Comment by nabokihms** [comment]
@jszwedko, I would love to work on this one, thanks. The plan is crystal clear. I used to work on the equivalent customization to make metrics storage with expiration, yet it was implemented in Go.

I will reach `@tobz` out on Monday to get more details.
