### ISSUE TITLE
ci image should install the latest version of nodejs.

### ISSUE THREAD

**Issue by StephenWakely** [vectordotdev/vector#11226]
Ubuntu 20.04 only gives us version 10 of nodejs. This requires us to implement workarounds such as https://github.com/vectordotdev/vector/pull/11224.

We should change the ci image so it pulls a later version of nodejs - possibly the one from https://nodejs.org/dist/v16.13.2/node-v16.13.2-linux-x64.tar.xz.

**Comment by jszwedko** [comment]
Closing since this hasn't seemed to have been an issue.
