### ISSUE TITLE
VRL's `del` function is infallible, but deletion can fail

### ISSUE THREAD

**Issue by JeanMertz** [vectordotdev/vector#11264]
The `del` function in VRL is infallible, but there are cases where actual deletion can fail. We currently silently ignore those errors.

1. Deleting root path (`del(.)`)
2. Deleting using a coalesced path segments (`del(.(foo | bar))`)
3. Deleting using a negative array index (`del(.foo[-1])`)

None of these are impossible to support, but we currently don't, and `del` doesn't expose that we don't, it silently ignores the error.

**Comment by fuchsnj** [comment]
All of these operations are supported now, but the type definitions are not accurate. There is already an issues filed for this, so I'm going to go ahead and close this one in favor of the other.

https://github.com/vectordotdev/vector/issues/13460
