### ISSUE TITLE
validation error when using `only_fields` with `elasticsearch` sink

### ISSUE THREAD

**Issue by shamil** [vectordotdev/vector#11266]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
vector 0.19.1 (x86_64-unknown-linux-musl 3cf70cf 2022-01-25)
```

### Vector Configuration File

```yaml
sinks:
  elasticsearch:
    inputs: ['destination.elasticsearch']
    type: elasticsearch
    endpoint: http://localhost:9200
    encoding:
      only_fields:
      - '@timestamp'
      - data
      - event
      - origin
```

### Debug Output

```
$ RUST_BACKTRACE=full vector -vvv --config configs/main.yaml 
2022-02-09T12:00:45.482862Z  INFO vector::app: Log level is enabled. level="vector=trace,codec=trace,vrl=trace,file_source=trace,tower_limit=trace,rdkafka=trace,buffers=trace"
2022-02-09T12:00:45.482979Z  INFO vector::app: Loading configs. paths=["configs/main.yaml"]
2022-02-09T12:00:45.483639Z ERROR vector::cli: Configuration error. error=sinks.elasticsearch: invalid type: string "@timestamp", expected a sequence at line 3 column 11
```

### Expected Behavior

Vector should be able to start, since exacly same configuration but for `console` sink works as expected.

### Actual Behavior

`vector` exits with an error

**Comment by jszwedko** [comment]
Hi @shamil . I think this is the same as https://github.com/vectordotdev/vector/issues/11196. We'll be releasing a fix for that today in v0.19.2. Thanks for reporting!
