### ISSUE TITLE
Sanitizing transform

### ISSUE THREAD

**Issue by lukesteensen** [vectordotdev/vector#1129]
We should implement a transform that enables users to remove sensitive data from their events before forwarding them upstream. There are a few different levels of sophistication for this type of task and we'll probably be better off starting simple.

The simplest version would be akin to a `sed` script run on incoming events. We would support a list of regex and replacement pairs that would be run over a given field or set of fields (or all fields, or just the message field).

The next level of sophistication would likely involve a built-in set of recognizers (see [here](https://github.com/microsoft/presidio/tree/master/presidio-analyzer/analyzer/predefined_recognizers) for some examples. This would keep users from having to write their own regex and potentially just let them opt into sanitizing "all" potentially sensitive data.

Beyond that, there are significantly more sophisticated systems like those build by large cloud providers (e.g. [Macie](https://aws.amazon.com/macie/) and [Cloud DLP](https://cloud.google.com/dlp/)). These may be an option further into the future, but likely aren't something we'll worry about for a long time.

For now, it'd be great to gather requirements from potential users of this transform. For example:

1. Do you expect to define your own regex patterns for sanitation or for them to be built into the tool?
2. About how many patterns do you expect to run over events? Or would you prefer an option to run all available patterns (assuming some are built-in)?
3. Would you want to run these patterns over one field (e.g. the raw log message), a set of fields, or every field in the document?

These will help us spec out the work and decide on the most useful defaults.

**Comment by binarylogic** [comment]
Good write up 👍. I'd like to package this up as a privacy/compliance project so we can address any other related tasks. I have this on the roadmap for Novement, actually:

https://timber.productboard.com/feature-board/867981-vector/features/3088924/detail/expanded

**Comment by jnatherley** [comment]
Thanks for writing this up!

1) We would like to define regex patterns for sanitation against a raw log or perhaps since we often have event data in json format perhaps we would like to just omit values if they match a particular key. Similar to Elixir Logger configuration.
2) An option to run all available patterns or to pick and choose would work well.
3) To run the pattern over the raw log message or select the fields would be good to start.

**Comment by karlseguin** [comment]
Maybe this belongs in a separate issue, but, could the conversation (and feature) be expanded to include other privacy techniques, such as making data pseudonymous? 

I think it's reasonable for this to operate only on structured fields, so it's tempting to think _I'll use the lua transformer_, but it would be nice if everyone didn't have to roll their own - especially if Timber.io could offer subject matter expertise. As a simple example, a transform that did field hashing with a configured key. (I'd suggest having another piece of secure data that can be configured to change after a configurable amount of time, but a) I have no clue if that actually helps and b) I don't see how you'd coordinate that across multiple vector instances)

P.S. A lot of the links on timber.io are broken. Scroll to the footer and click on virtually any link, like Console or Ruby. They all give 404s, e.g. https://docs.timber.io/app/console

**Comment by jszwedko** [comment]
Closing this since VRL has a `redact` function now.
