### ISSUE TITLE
Elasticsearch sink endpoint redundancy

### ISSUE THREAD

**Issue by ccmsi** [vectordotdev/vector#11297]
Thanks for this great project, so much more efficient ...
Proposal / request for making the "endpoint" configuration item in sinks of type = "elasticsearch" an array to define alternative Elasticsearch URLs for failover redundancy.
Thanks and best regards.

**Comment by spencergilbert** [comment]
Thanks for opening this issue @ccmsi - it's actually a duplicate of https://github.com/vectordotdev/vector/issues/3649 so I'll close this one out. Please 👍 the linked issue to help prioritize the work!
