### ISSUE TITLE
configuration docs sinks elasticsearch tls.

### ISSUE THREAD

**Issue by yxyx520** [vectordotdev/vector#11332]
https://vector.dev/docs/reference/configuration/sinks/elasticsearch/#tls 
In this url, docs of sinks elasticsearch tls configuration, there is no option of `tls.verify_certificate`, but when I set `tls.verify_certificate` in my config and it works. So I think if docs missing explain of  `tls.verify_certificate`

**Comment by jszwedko** [comment]
Hi @yxyx520 ! Yeah, I think we just need to document that option. We are tracking that in https://github.com/vectordotdev/vector/issues/6132 so I'll close this out in-lieu of that issue.

**Comment by yxyx520** [comment]
@jszwedko ok, thanks for your reply
