### ISSUE TITLE
influxdb codec

### ISSUE THREAD

**Issue by alileza** [vectordotdev/vector#11337]
### Current Vector Version

```
vector 0.20.X
```

### Use-cases

So currently we're using statsd client that emits format like 

```
"user.logins,service=payroll,region=us-west:1|c"` that works fine with telegraf and pushed to influxdb.
```

but, vector does seem to expect a different format https://github.com/vectordotdev/vector/blob/master/src/sources/statsd/parser.rs#L17  
which is stated there https://docs.datadoghq.com/developers/dogstatsd/datagram_shell/#datagram-format

```
user.logins:1|c|#service:payroll,region:us-west
```

this would require us to update all of our client libraries to change the client. 

### Attempted Solutions

Implement new parser method for `statsd` source, that accept influxdb datagram, that way we can configure sources.statsd like

```
sources:
  statsd:
    type: "statsd"
    address: "0.0.0.0:8125"
    mode: "udp"
    format: "influxdb" // dogstatsd|librato|influxdb|signalfx
 ```

that uses different parser function that parse `"user.logins,service=payroll,region=us-west:1|c"` format instead of datadog datagram

Would this be something acceptable? or is there better way for me to get this working with vector without requiring changes on the statsd source?

**Comment by jszwedko** [comment]
Hi @alileza ,

Thanks for writing this up. I think what you suggested seems reasonable to me.

We also have a new codecs framework that this could fit in. This would make the configuration something like:


```toml
sources:
  statsd:
    decoding:
      codec: "influxdb" // dogstatsd|librato|influxdb|signalfx
```

Up until now the codecs have largely been focused on decoding logs (e.g. JSON decoding), but I think the basic idea here is the same. You can see the decoder definitions here: https://github.com/vectordotdev/vector/tree/master/lib/codecs/src/decoding/format

I think this would be a good issue for anyone interested in contributing since it is hopefully fairly straightforward.

**Comment by bfg111** [comment]
If there was a generic TCP interface for decoding data would something like

**Comment by spencergilbert** [comment]
> If there was a generic TCP interface for decoding data would something like this make sense?
> 
> ```
> sources:
>   socket:
>     decoding:
>       codec: "influxdb" // statsd|dogstatsd|librato|influxdb|signalfx```
> ```

That would likely be added in [lib/codecs](https://github.com/vectordotdev/vector/tree/master/lib/codecs) as a new [format](https://github.com/vectordotdev/vector/tree/master/lib/codecs/src/decoding/format)

**Comment by bfg111** [comment]
So the plan is to use the "statd" source for all of these other decoded types? Or would there be a new source type that could handle "statsd", "influxdb", and other codecs/formats in a more generic way?

**Comment by jszwedko** [comment]
> So the plan is to use the "statd" source for all of these other decoded types? Or would there be a new source type that could handle "statsd", "influxdb", and other codecs/formats in a more generic way?

My thought is to model these all as codecs that can be used with the `socket` source:

- `statsd` codec
- `dogstatsd` codec
- `influxdb` codec

**Comment by bfg111** [comment]
@jszwedko @spencergilbert - is this something that will realistically be worked on at some point in the near future?

**Comment by jszwedko** [comment]
> @jszwedko @spencergilbert - is this something that will realistically be worked on at some point in the near future?

It's not on our roadmap at the moment, but this area, codecs, is an area that I think contributors can more easily contribute to than other areas of Vector. We'd be happy to help guide in a contribution here from a motivated contributor. You can see these recent PRs for a `gelf` codec as an example:

- https://github.com/vectordotdev/vector/pull/13333
- https://github.com/vectordotdev/vector/pull/13288

**Comment by MichaHoffmann** [comment]
This would be useful to me I think! There is https://docs.rs/influxdb-line-protocol/latest/influxdb_line_protocol/ too, so I imagine this could be fairly straight forward; @jszwedko is this still an interesting feature for the upstream too?

**Comment by jszwedko** [comment]
> This would be useful to me I think! There is https://docs.rs/influxdb-line-protocol/latest/influxdb_line_protocol/ too, so I imagine this could be fairly straight forward; @jszwedko is this still an interesting feature for the upstream too?

Hey! Yes, we'd be happy to see a codec for the influxdb line protocol.

**Comment by MichaHoffmann** [comment]
@jszwedko One question: how can i actually use an influxdb decoder? I wanted to test it now and dont think there are sources that can process line inputs and have a metrics output.

**Comment by jszwedko** [comment]
> @jszwedko One question: how can i actually use an influxdb decoder? I wanted to test it now and dont think there are sources that can process line inputs and have a metrics output.

I think the `native_json` codec would be a good model since it takes raw text and can output logs, metrics, or traces. For example, you could test with the `stdin` source which takes in text and can emit different data types depending on the configured codec.

This is implemented by https://github.com/vectordotdev/vector/blob/b2c9f27d4360cbdb211d9f7230ae90e6becfee8d/src/sources/file_descriptors/mod.rs#L225-L228 (the `SourceOutput::new_logs` is a bit misleading, it's the bit using `decoding.output_type()` that says "I can emit any data type my codec emits"). So you should be able to configure your new `influxdb` codec.

Let me know if that makes sense!

**Comment by MichaHoffmann** [comment]
New logs checks that the codec can produce logs I think. This means I would have to configure the influxdb codec to output logs too ( but never actually output any ), right?

**Comment by MichaHoffmann** [comment]
At least in my tests it crashed with asserting error from within new_logs

**Comment by jszwedko** [comment]
> New logs checks that the codec can produce logs I think. This means I would have to configure the influxdb codec to output logs too ( but never actually output any ), right?

It actually doesn't. That's the confusing bit I mentioned. The first argument of `new_logs()` is what controls the output type.

**Comment by jszwedko** [comment]
If you want to push up your crashing test to your PR we could take a look and see if anything seems amiss.

**Comment by MichaHoffmann** [comment]
Will do in a minute!

**Comment by MichaHoffmann** [comment]
Ok i pushed the latest state to the PR, and if i start with config 
```
sources:
  in:
    type: stdin
    decoding:
      codec: influxdb

sinks:
  out:
    type: console
    inputs: [in]
    encoding:
      codec: json
```

It crashes with:
```
$ echo "foo" | ./target/debug/vector --config-yaml vector.yaml
2024-01-17T20:31:36.432267Z  INFO vector::app: Log level is enabled. level="info"
2024-01-17T20:31:36.436029Z  INFO vector::app: Loading configs. paths=["vector.yaml"]
thread 'main' panicked at lib/vector-core/src/config/mod.rs:128:9:
assertion failed: ty.contains(DataType::Log)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/714b29a17ff5fa727c794bbb60bfd335f8e75d42/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/714b29a17ff5fa727c794bbb60bfd335f8e75d42/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
```

**Comment by jszwedko** [comment]
Ah, I see the issue. It's that `SourceOutput::new_logs()` expects that logs be _included_ in the output type. That's why it doesn't fail for `native_json` or `native` since the output type of that codec is "any". This might require some more refactoring. I think `SourceOutput` should have a `new` function that just takes the data type and schema definition and doesn't make any assertion on the type.

**Comment by MichaHoffmann** [comment]
After removing the assertion as a test,I think the decoder works, sort-of. I'm not sure if we can get a better mapping then using gauge for everything though.

**Comment by jszwedko** [comment]
> After removing the assertion as a test,I think the decoder works, sort-of. I'm not sure if we can get a better mapping then using gauge for everything though.

Yeah, I think `gauge` would be the correct data type to be used for influx's "measurement".

**Comment by RedForza** [comment]
Linking PR #19637

**Comment by jorgehermo9** [comment]
Can this issue be closed @jszwedko? Or should be closed after the influxdb encoder is implemented? I thought this issue was requesting only the decoder

**Comment by jszwedko** [comment]
Agreed, thanks @jorgehermo9 . This issue does just seem to be requesting a decoder, which was added by https://github.com/vectordotdev/vector/pull/19637. We can let people request an encoder if they have need.
