### ISSUE TITLE
Option to create a single Vector executable with bundled config

### ISSUE THREAD

**Issue by a-rodin** [vectordotdev/vector#1137]
This is mostly just an idea now, as I want to understand how does this relate to our recommended approach to Vector deployment.

The idea is to add an option to Vector that would pack all configs together with Vector itself into a single binary. This would be similar to fat JARs or Go binaries containing all resources, which might be especially useful if entire configuration is scattered over multiple files and/or scripts.

It would not need the user to recompile Vector, as such binaries can be created by a Vector subcommand from an existing Vector executable concatenated with the config files, for example like this:

```
vector --config vector.toml bundle --output vector-production
```

The examination of configs bundled inside the binary could then be performed by mechanisms discussed in #1039 and #1075.

**Comment by jszwedko** [comment]
Closing as won't do. Feel free to leave a comment if this would be useful to you though.
