### ISSUE TITLE
`splunk_channel` gets added in splunk_hec sync when acknowledgement is disabled

### ISSUE THREAD

**Issue by graffzon** [vectordotdev/vector#11387]
Hi dear Vector team,
huge thumbs up for the great work :)

To the business. We upgraded to 0.19.0 and noticed a strange behaviour of the splunk_hec sink.
Our setup looks as follows:
```
(app-1): splunk hec source -> transforms -> splunk
                                                                     -> app-2
(app-2): splunk hec source -> transforms -> s3
```

Which leads to the fact that `splunk_hec` sink of the first application adds this field to the payload and sends it to Splunk and app-2.
For Splunk it's not a biggie as it expects it. However app-2 just dumps the payload to s3 (with minimal transformation) which means that this field ends up in our s3.
As a workaround we will implement a transform that removes this field, but I would be good if this field wouldn't appear out of nowhere when the acknowledgement feature is disabled.

**Comment by 001wwang** [comment]
Hey @graffzon!

We discussed this more internally and have decided to preserve the channel behavior of the `splunk_hec` sink(s) for now. We'll document this in the `0.19.0` upgrade guide and elsewhere to make it clear. Apologies for any inconvenience and for mis-speaking when I said we'd change the behavior. Our ideal solution is that a source (in this case, `splunk_hec`) would not add metadata (in this case, the `splunk_channel`) directly to the event but instead add it to a separate and more easily managed area. However, we're a ways off from that.

For posterity, to add more color here on why the above is happening, the `splunk_hec` sink now (`v0.19.0+`) includes a channel header in the HTTP request it sends whether or not indexer acknowledgements is enabled. This is, as mentioned, fine when sending directly to Splunk. However, if you send from a `splunk_hec` sink to a `splunk_hec` source, the sink will have included channel information as a request header which the source then parses into an additional `splunk_channel` field.
