### ISSUE TITLE
Multiple issues with Vector internal metrics

### ISSUE THREAD

**Issue by vpedosyuk** [vectordotdev/vector#11447]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I just upgraded Vector from 0.18.0 to 0.20.0 and noticed a few issues with the `internal_metrics` source:
#### 1
`http` sink doesn’t report `vector_processed_events_total` anymore
#### 2
`throttle` transform doesn’t report `vector_events_discarded_total` but this is what remains unchanged since 0.18.0 and is actually the reason for the upgrade. Unfortunately, I couldn’t find another way to inspect "how many events got throttled".
#### 3
`http` sink now constantly reports non-zero rate of `vector_buffer_discarded_events_total` even though `vector_buffer_events` reports 0 most of the time.

<img src="https://user-images.githubusercontent.com/16594968/154517366-4ed5f372-27d9-48f4-abe1-c6a3dcb0d94e.png" width="500">

<img src="https://user-images.githubusercontent.com/16594968/154517375-93015c4a-d73e-44bd-bb95-6d131c99a627.png" width="500">

I don’t know if it’s really Vector who constantly discards events or just a telemetry issue. Before the upgrade, the `vector_buffer_discarded_events_total` counter could increase only if `vector_buffer_events` reached `buffer.max_events` setting.

### Configuration

```text
[sources.vector-internal-metrics]
  type = "internal_metrics"
  scrape_interval_secs = 15

[transforms.vector-internal-metrics-transform]
  type = "remap"
  inputs = ["vector-internal-metrics"]

  source = '''
  .tags.internal_metrics = "true"
  .tags.cluster = "< setup_name >"
  .tags.node = "${HOSTNAME}"
  '''

[sinks.vector-internal-telemetry]
  type = "vector"
  version = "2"
  inputs = ["vector-internal-metrics-transform"]
  address = "<address>"
  healthcheck = true

  buffer.max_events = 200000
  buffer.type = "memory"
  buffer.when_full = "block"

[sources.logs]
  type = "file"
  include = ["/var/log/*.log", "/var/log/*/*.log"]
  ignore_older_secs = 3600
  ignore_not_found = true
  max_read_bytes = 2048
  fingerprint.strategy = "device_and_inode"
  read_from = "end"

[transforms.logs-setup]
  type = "remap"
  inputs = ["logs"]

  source = '''
  .setup = "<setup_name>"
  '''

[transforms.throttle]
  type = "throttle"
  inputs = ["logs-setup"]
  threshold = 45000000
  window_secs = 300

[sinks.vector-logs]
  type = "http"
  inputs = ["throttle"]
  uri = "<uri>"
  healthcheck = true

  buffer.max_events = 3000000
  buffer.type = "memory"
  buffer.when_full = "drop_newest"

  encoding = "ndjson"
  compression = "gzip"
```

### Version

0.20.0

**Comment by jszwedko** [comment]
Hi @vpedosyuk !

Thanks for this report. Responses in line:

> `http` sink doesn’t report `vector_processed_events_total` anymore

> #### 1
> `http` sink doesn’t report `vector_processed_events_total` anymore

This metric was dropped in-lieu of `vector_component_sent_events_total`, you should see that metric for v0.20.0.

> #### 2
> `throttle` transform doesn’t report `vector_events_discarded_total` but this is what remains unchanged since 0.18.0 and is actually the reason for the upgrade. Unfortunately, I couldn’t find another way to inspect "how many events got throttled".

`vector_events_discarded_total` is the correct metric (though we will be renaming this to `vector_component_events_discarded_total` in the nearish future). I ran a local test and did see it being published. It will only be published if events are actually throttled though (#6532 discusses publishing these with an initial value and the challenges of doing so).

> #### 3
> `http` sink now constantly reports non-zero rate of `vector_buffer_discarded_events_total` even though `vector_buffer_events` reports 0 most of the time.

I think this is the same as #11557 so we can follow up on that there.

Apologies for the internal metrics confusion. They've been in quasi-implemented state for a while, but we've finally made a push to standardize them. Once that finishes the ground should be shifting a lot less with the metric names and tags.

**Comment by jszwedko** [comment]
Closing this given the responses above and the fact that we are tracking the discarded events issue in https://github.com/vectordotdev/vector/issues/11557. Let me know if you have any other questions though!

**Comment by jszwedko** [comment]
Hi @vpedosyuk ,

The metrics have been a bit in flux. We are hoping it is settled in this next release (including adding the expected metrics for the `http` sink). The `vector_processed_events_total` is kept for compatibility but is deprecated and will be removed in a future release.

The internal metrics have been on a long road since their introduction, going through multiple cycles of renaming, but I think it is nearing the point where they will be stable 🙂  I realize it has been confusing and frustrating for users along the way and regret not approaching it differently with more design up-front.

**Comment by vpedosyuk** [comment]
Hi @jszwedko, yes, I understand. Thanks for your hard work on this.
