### ISSUE TITLE
Support Authorization for HTTP(S) Proxy

### ISSUE THREAD

**Issue by akutta** [vectordotdev/vector#11455]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

All of our hosts require traffic bound for external sources to proxy their requests via an authenticated proxy.  By default, our env vars are defined in the format: `user:pass@proxyserver.com:port`

### Attempted Solutions
```
 HTTPS_PROXY="user:pass@proxyserver.com:port"
```
### Proposal

Support configuration via ENV vars:

```
HTTPS_PROXY="user:pass@proxyserver.com:port"
```

or via Global Configuration:

```
proxy.https = "user:pass@proxyserver.com:port"
```

HyperProxy claims that the above format is deprecated.  So an alternative could be to enable users to set the auth information at a global / per sink level, although could quickly become overly verbose. Especially if the proxy username:password are different for http vs https.

https://github.com/vectordotdev/vector/blob/bd8f097e82f8e3f1c30a4ed28e86c3e6ec97fc00/lib/vector-core/src/config/proxy.rs#L130

Should then be changed to conditionally call 

```
proxy.set_authorization(Authorization::basic("user", "pass"));
```

### Version

vector 0.20.0 (x86_64-apple-darwin 2a706a3 2022-02-10)

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/12016
