### ISSUE TITLE
Docker-compose

### ISSUE THREAD

**Issue by KaMaToZzz** [vectordotdev/vector#11467]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Hello,

Where I can find docker-compose for deploying vector agent in my docker swarm?

### References

7023

**Comment by jszwedko** [comment]
Closing as stale.
