### ISSUE TITLE
`socket`/`tcp` source: Vector stops processing if multiple connections are left open

### ISSUE THREAD

**Issue by hhromic** [vectordotdev/vector#11475]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Vector seems to stop processing incoming TCP data if a number of connections are left open by the sending system. When some of the open connections are closed, Vector seems to resume processing immediately but hangs again if more connections are made again.

The following is a simple Python program that simulates the described behaviour:
```python
import socket
import time

NUM_CONNECTIONS = 10
NUM_MESSAGES = 3
TARGET = ("localhost", 8080)

sockets = []
for idx in range(NUM_CONNECTIONS):
    sck = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    print(f"[{idx}] connecting to target ...")
    sck.connect(TARGET)
    sockets += [sck]

    print(f"[{idx}] sending {NUM_MESSAGES} messages ...")
    for idx2 in range(NUM_MESSAGES):
        msg = f"hello world {idx2} from {idx}\n"
        sent = sck.send(msg.encode("utf8"))
        if sent == 0:
            raise RuntimeError(f"[{idx}] socket connection broken")

    print("waiting before creating next connection ...")
    time.sleep(0.5)

print("sending data to the last connected socket ...")
sck = sockets[-1]
idx = 0
while True:
    msg = f"hola mundo {idx}\n"
    sent = sck.send(msg.encode("utf8"))
    if sent == 0:
        raise RuntimeError("socket connection broken")
    time.sleep(0.5)
    idx += 1
```

This program will create `NUM_CONNECTIONS` connections (one by one) to a running Vector instance with a `socket` source in `tcp` mode. After each connection is made, it will send `NUM_MESSAGES` messages before creating the next one and leaving the current one open. In the end, it will just keep sending data on the last connection made. Again, while keeping all the previous connections open in purpose but without any data being sent.

If you run the above test program against the Vector configuration shown below, you will see that Vector will stop processing incoming data after the second connection is made and the third is attempted:
```
$ vector -c vector.yaml
2022-02-19T12:01:40.987805Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info"
2022-02-19T12:01:40.988054Z  INFO vector::app: Loading configs. paths=["/vector.yaml"]
2022-02-19T12:01:40.990736Z  INFO vector::topology::running: Running healthchecks.
2022-02-19T12:01:40.990858Z  INFO vector::topology::builder: Healthcheck: Passed.
2022-02-19T12:01:40.990901Z  INFO vector::topology::running: Starting source. key=socket
2022-02-19T12:01:40.991076Z  INFO vector::topology::running: Starting sink. key=console
2022-02-19T12:01:40.991198Z  INFO vector: Vector has started. debug="false" version="0.20.0" arch="x86_64" build_id="2a706a3 2022-02-11"
2022-02-19T12:01:40.991252Z  INFO vector::internal_events::api: API server running. address=0.0.0.0:8686 playground=off
2022-02-19T12:01:40.995816Z  INFO source{component_kind="source" component_id=socket component_type=socket component_name=socket}: vector::sources::util::tcp: Listening. addr=0.0.0.0:8080
hello world 0 from 0
hello world 1 from 0
hello world 2 from 0
hello world 0 from 1
hello world 1 from 1
hello world 2 from 1
(... Vector stops here despite the Python program still sending data and making connections...)
```

If at this point you stop the Python program, it will close all the currently opened connections and Vector will process all the pending data sent up to this point:
```
(... Vector was stopped here ...)
hello world 0 from 2
hello world 1 from 2
hello world 2 from 2
hello world 0 from 3
hello world 1 from 3
hello world 2 from 3
hello world 0 from 4
hello world 1 from 4
hello world 2 from 4
hello world 0 from 5
hello world 1 from 5
hello world 2 from 5
hello world 0 from 6
hello world 1 from 6
hello world 2 from 6
hello world 0 from 7
hello world 1 from 7
hello world 2 from 7
hello world 0 from 8
hello world 1 from 8
hello world 2 from 8
hello world 0 from 9
hello world 1 from 9
hello world 2 from 9
hola mundo 0
hola mundo 1
hola mundo 2
hola mundo 3
hola mundo 4
hola mundo 5
...
```

If you run the example Python program again, without stopping Vector at this point, you will be able to reproduce this blocking behaviour multiple times.

**Note:** This MRE affects Vector `0.20.0` but I didn't manage to reproduce in `0.19.x`. Even with large amounts of connections and messages and repetitions configured in the example Python program above. However, I do observe this behaviour in our larger feed processing (around 12K EPS per connection and hanging after 32 open connections are left open) in `0.19.x`. Setting a `keepalive` timeout does help to keep connections down and thus Vector not hanging in this case.

I did NOT observe this problem in Vector `0.18.1`.

### Configuration

```yaml
sources:
  socket:
    type: socket
    mode: tcp
    address: 0.0.0.0:8080

sinks:
  console:
    type: console
    inputs:
      - socket
    encoding: text
```

### Version

vector 0.20.0 (x86_64-unknown-linux-gnu 2a706a3 2022-02-11)

**Comment by diegomontoya** [comment]
Possible related to this http source not responding issue which depends on the tcp code? 

https://github.com/vectordotdev/vector/issues/12068
