### ISSUE TITLE
Internal metrics not provide information about queue, performance and errors

### ISSUE THREAD

**Issue by SirEdvin** [vectordotdev/vector#1148]
Hello.

Actually, title say the things, internal metrics now is quite unuseful, they don't have sink, source or transform tag and not response about errors with sink, for example.

Did you have plans to fix this? Or I can try to provide pull request with possible fix/feature?

**Comment by SirEdvin** [comment]
As I see, vector use hotmic, that was replaced with `metrics` infrastructure.

If I rewrite current metrics logic from hotmic to metrics, will this be suitable? As I can see, hotmic doesn't support labels for metrics

**Comment by SirEdvin** [comment]
Actually, additional suggestion to this is remove current metrics collection system based on tracing listening and replace it with `metrics` crate. 

What do you think about it ?

**Comment by binarylogic** [comment]
Thanks, @SirEdvin, you are correct, we are working to improve our internal metrics. It's on our roadmap to 1.0. Our intent is to product an "internal" metrics source that can run through Vector itself, allowing you to emit metrics to any metrics sink we support. I assume that would cover this?

**Comment by SirEdvin** [comment]
@binarylogic Will you include something like something like transfer/sink processing histograms?

Also, can I try to help and provide pull request (In case, I will able to implement it correctly), or someone currently work on this?

**Comment by jszwedko** [comment]
Closing this since internal instrumentation has come a long way and metrics do include component tags like component type and name now.
