### ISSUE TITLE
Adhere installation targets to target specification 

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#11491]
This is a meta issue to drive work to improve how Vector support installation targets motivated by the new "going to production" documentation.

- [x] #10943

Packages
- [x] #12551
- [x] #12201
- [x] #12553
- [x] #12554
- [x] #12260
- [x] #12552

Platforms
- [x] #12440
- [x] #12555

Manual
- [x] #12556

**Comment by spencergilbert** [comment]
Related: https://github.com/vectordotdev/vector/issues/8336
Related: https://github.com/vectordotdev/vector/issues/8531

**Comment by jszwedko** [comment]
Closing as complete given the MSI issue was deprioritized.
