### ISSUE TITLE
Sample by key

### ISSUE THREAD

**Issue by adam-mrozik** [vectordotdev/vector#11528]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Hey,

My goal is to sample messages based on a given field -> meaning, that if `rate` equals 5 and `sample_key` would equal `user_id`, I would get exactly 1/5 messages for each user.

### Attempted Solutions

I first thought `key_field` is the way to go, but it just chooses consistently, which unique fields will be always sampled and which will never be sampled. But, it seems that `key_field` has to store hashes somewhere to determine whether given value will be sampled or not -> This means that we could store values with some counters and refer to them to determine if the next message should be sampled or not.

### Proposal

Add a `sample_key` option to `transforms.sample`

### References

-

**Comment by adam-mrozik** [comment]
Hi @spencergilbert - It is actually very close! I am missing one key aspect though:

With sample_rate, I knew that with rate 10, I drop 90% of events. Since I then want to calculate number of events per user, I could just simply multiply number of output events for this user by 10 (since I know only every 10th is kept per user_id)

With `throttle`, the issue is that I do not know how many events did I drop. So if I go with:
```
threshold: 1000
key_field: user_id
```
I am actually unable to determine how many events has been dropped for the given user_id. Or, at least I do not know how to do it, so if you have an idea, please let me know!

**Comment by jszwedko** [comment]
Closing since this was answered. Feel free to reopen if you have more questions though!
