### ISSUE TITLE
Upgrade to Rust 1.59

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#11559]

**Comment by jszwedko** [comment]
Blocked by https://github.com/rust-lang/rust-clippy/issues/8470

**Comment by spencergilbert** [comment]
FWIW I'm not running into this issue with my M1, fully updated

**Comment by lukesteensen** [comment]
Reopening as the upgrade was reverted.

**Comment by jszwedko** [comment]
Closing since we upgraded to 1.61.0.
