### ISSUE TITLE
can not dedot and nested message in vector transforms

### ISSUE THREAD

**Issue by yxyx520** [vectordotdev/vector#11575]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

do_dot and nested like logstash: https://www.elastic.co/guide/en/logstash/current/plugins-filters-de_dot.html

### Version

0.19.1

### Example Data

resource data: `{"a.b.c": "1"}`  

expect output: 
```
{ "a":
  {"b":
    {"c": "1"
    }
  }
}
```

**Comment by yxyx520** [comment]
logstash config:
```
            json {
                source => "[log][original]"
            }
            de_dot {
                nested => true
            }
```

**Comment by hhromic** [comment]
Looks like this feature request is asking for the complement of the [`flatten()` function](https://vector.dev/docs/reference/vrl/functions/#flatten).

**Comment by jszwedko** [comment]
Yeah, agreed, this seems to be `unflatten` which we have an issue for: https://github.com/vectordotdev/vector/issues/11066 . I'll close this in-lieu of that one.
