### ISSUE TITLE
VRL: Add support to the to_timestamp method for millisecond format (13 digit) epoch timestamps

### ISSUE THREAD

**Issue by naveedyahyazadeh** [vectordotdev/vector#11591]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Currently, a user can input a 10 digit epoch timestamp (which represents seconds since 1/1/1970) into the `to_timestamp()` field. 13 digit timestamps are another common format that epoch timestamps can be packaged as, and they will provide granularity down to the millisecond (AWS sources are an example of this). 

It would be great to have the to_timestamp method be able to natively convert both formats, either via automatic detection or with a manual toggle to indicate that the input to the method is ms-based.

**Comment by JeanMertz** [comment]
We could add a toggle, but automatic detection could never work. It's ambiguous whether `to_timestamp(1000)` is 1 or 1000 seconds after epoch.

**Comment by hhromic** [comment]
Maybe it would be a good idea to mirror the `unit` argument from [`to_unix_timestamp()`](https://vector.dev/docs/reference/vrl/functions/#to_unix_timestamp) ?

**Comment by JeanMertz** [comment]
> Maybe it would be a good idea to mirror the `unit` argument from [`to_unix_timestamp()`](https://vector.dev/docs/reference/vrl/functions/#to_unix_timestamp) ?

I'm a fan of that approach 👍 If anyone wants to PR the change, I'd be happy to provide a review and get that merged in. It should be fairly straightforward to duplicate the `to_unix_timestamp` implementation in https://github.com/vectordotdev/vector/blob/f39c3c63e42f7384dd3f641ece7512783e9e2c88/lib/vrl/stdlib/src/to_unix_timestamp.rs.
