### ISSUE TITLE
Datadog Traces subsequent work

### ISSUE THREAD

**Issue by prognant** [vectordotdev/vector#11648]
Once #11033 and #11489 will be merged it will provide initial traces capabilities, but the following subsequent tasks will be required as some point in the future:

- [x] Traces path in pipelines (see [this comment](https://github.com/vectordotdev/vector/pull/11489#issuecomment-1047558907))
- [x] Newer datadog traces format support :
  - [x] In `datadog_agent` source
  - [x] In `datadog_trace` source
- [x] #12780
- [x] #13275
- [x] Traces doc improvement (#11021)

**Comment by jszwedko** [comment]
Closing this since initial work is done.
