### ISSUE TITLE
Set specific upper limits to batch size for S3 sink

### ISSUE THREAD

**Issue by prashansa** [vectordotdev/vector#11677]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

AWS S3 sets an upper limit to the maximum size an object can be. For uploads via API, for example, an object can be maximum 5 GB in size. 

When I connect Vector with S3 sink, I need to estimate the size and number of objects to uploaded, especially when incoming data is large (order of TBs a day). 

Vector allows max_bytes to be set for batch, but does not set an upper limit for it. It seems like generic batch configuration is being used, and no specific validation is done for batch size of S3. 

This upper limit should ideally be added to avoid footgunning in the future. 

### Version

vector 0.20.0

**Comment by pront** [comment]
Hi @prashansa, the [buffer.max_size](https://vector.dev/docs/reference/configuration/sinks/aws_s3/#buffer.max_size) is the upper limit for a buffer's disk size. Can clarify further what upper limit you want here?

**Comment by jszwedko** [comment]
Closing as stale. `batch.max_bytes` is what controls (uncompressed) object sizes in S3. Please leave a comment if I'm misunderstanding the request here.
