### ISSUE TITLE
allow to drop specific events without them reaching .dropped

### ISSUE THREAD

**Issue by tshepang** [vectordotdev/vector#11703]
I want to be able to use `reroute_dropped`, but don't want certain events reaching re-route destination.

If I were to choose a word for this, it would be `drop`, but that would confuse it with `abort` which actually does a drop. So perhaps something like `skip`/`ignore` is more suitable.

_Originally posted by @tshepang in https://github.com/vectordotdev/vector/discussions/11679_

**Comment by tshepang** [comment]
Another name I like is `discard`, though it feel like has same meaning as `drop`.

**Comment by jszwedko** [comment]
Related: https://github.com/vectordotdev/vector/issues/7496

**Comment by jszwedko** [comment]
Rolling this into https://github.com/vectordotdev/vector/issues/7496
