### ISSUE TITLE
Some soak replicas "take a while" to start up

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#11772]
Consider https://github.com/vectordotdev/vector/pull/11768#issuecomment-1064093887. We have a plot that looks like so:

![samples](https://user-images.githubusercontent.com/3579/157706518-3b13ec70-5acf-4cd1-9604-ed5c43208d2c.png)

A single replica takes +2 minutes to properly start. We are unsure if this is a consequence of the runner rig or Vector itself.

**Comment by 001wwang** [comment]
Just noting that we're also seeing a bit of this in https://github.com/vectordotdev/vector/pull/11732#issuecomment-1064180726. For instance, the plot for the `socket_to_socket_blackhole` soak
![samples](https://user-images.githubusercontent.com/43912346/157713277-ad5f9fa2-aa45-4e86-89bc-9aa2a1d61e1c.png)

**Comment by jszwedko** [comment]
A couple of other flakes:

https://github.com/vectordotdev/vector/pull/11024#issuecomment-1062801451

The baseline for `syslog_log2metric_humio_metrics` seemed to have the same behavior seen here:

![samples](https://user-images.githubusercontent.com/316880/157721485-6b298480-652e-475b-859f-e4aa590cbf0b.png)

`http_to_http` acks looks very strange:

![samples](https://user-images.githubusercontent.com/316880/157722032-4ee05bf4-a5de-4c0b-82d8-cd1465c9bc7c.png)

This appears to be a different oddity.

**Comment by jszwedko** [comment]
Another data point:

https://github.com/vectordotdev/vector/pull/11771#issuecomment-1064300129

`syslog_splunk_hec_logs`

![samples](https://user-images.githubusercontent.com/316880/157725407-45428f9b-d975-4907-a170-e98ff81711f1.png)

**Comment by blt** [comment]
Hmm, well. Here's the 'up' plot -- REF #11775 -- for the most recent `syslog_splunk_hec_logs`:

![up](https://user-images.githubusercontent.com/3579/157728055-ed903196-0769-4dca-8ca7-ff69b3a9e08c.png)

Online and online through the whole run, looks like.

**Comment by jszwedko** [comment]
Another particularly odd set of soaks:

https://github.com/vectordotdev/vector/pull/11774#issuecomment-1064342054

The change there doesn't seem like it should have affected any of the soaks and yet I do see plots like this one for `http_to_http_json`:

![samples](https://user-images.githubusercontent.com/316880/157730398-22b9b3a6-9209-455a-ba3c-54c0ce301b3d.png)

**Comment by jszwedko** [comment]
> Hmm, well. Here's the 'up' plot -- REF #11775 -- for the most recent `syslog_splunk_hec_logs`:
> 
> ![up](https://user-images.githubusercontent.com/3579/157728055-ed903196-0769-4dca-8ca7-ff69b3a9e08c.png)
> 
> Online through the whole run, looks like.

Hmm, interesting, it sure seems that way.

**Comment by 001wwang** [comment]
> Another particularly odd set of soaks:
> 
> [#11774 (comment)](https://github.com/vectordotdev/vector/pull/11774#issuecomment-1064342054)

I think the branch for that PR is somewhat old. Curious to see it merged with master.

**Comment by jszwedko** [comment]
Ah, you are right, thanks for noticing @001wwang . I didn't realize the branch was based off an old commit. I'll merge in master.

**Comment by blt** [comment]
> With some luck we'll get a ding in https://github.com/vectordotdev/vector/actions/runs/1964661682. Up to date when I created the branch.

No luck.

**Comment by blt** [comment]
> I'm going to see if I can't reproduce locally with `socket_to_socket_blackhole`. I'll post configs here in a second.

https://gist.github.com/blt/a43ecc0e890dd70cf3874c42b0a45d91

**Comment by jszwedko** [comment]
I saw this behavior again for the `syslog_regex_logs2metric_ddmetrics ` in https://github.com/vectordotdev/vector/pull/11799#issuecomment-1065327654 . This is after the [k8s static CPU manager policy](https://github.com/vectordotdev/vector/pull/11782) was merged so it seems like that didn't fix the issue we are seeing.

![samples](https://user-images.githubusercontent.com/316880/157937172-dfa09e41-a0d1-4c24-b5b3-182b0dca28b1.png)

**Comment by blt** [comment]
> I saw this behavior again for the `syslog_regex_logs2metric_ddmetrics ` in [#11799 (comment)](https://github.com/vectordotdev/vector/pull/11799#issuecomment-1065327654) . This is after the [k8s static CPU manager policy](https://github.com/vectordotdev/vector/pull/11782) was merged so it seems like that didn't fix the issue we are seeing.
> 
> ![samples](https://user-images.githubusercontent.com/316880/157937172-dfa09e41-a0d1-4c24-b5b3-182b0dca28b1.png)

Well, shoot. It was worth a shot.

**Comment by blt** [comment]
I believe #11891 addresses this but I am holding off on closing this until we have long-term data.

**Comment by jszwedko** [comment]
@blt I feel comfortable closing this if you are. We haven't had any reports of this issue since https://github.com/vectordotdev/vector/pull/11891 was merged.

**Comment by blt** [comment]
> @blt I feel comfortable closing this if you are. We haven't had any reports of this issue since #11891 was merged.

Excellent. Yes, I'll close this.
