### ISSUE TITLE
Search broken on vector.dev

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#11791]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Search currently doesn't work on vector.dev. We are in the process of restoring it.

### Version

n/a

**Comment by nsollecito** [comment]
Algolia API key updated to fix build failures

**Comment by jszwedko** [comment]
This is partially fixed, but still not working on the front-end.
