### ISSUE TITLE
Use relative time units in timeout values used in tests

### ISSUE THREAD

**Issue by a-rodin** [vectordotdev/vector#1180]
Many of Vector's tests have timeouts which are hardcoded in the tests code. This approach is simple and keeps the tests code easy to read. However, it is somewhat fragile because running tests on a slow CPU might break them.

One approach to solve this is to rewrite the tests that are using timeouts in a way that doesn't involve any waiting at all. However, I want to propose an alternative, which is to make all timeouts relative to performance of the CPU on which the tests are being executed.

In order to do it, we can introduce a test-time constant which would represent effective CPU speed, then use it as a scaling factor for all timeouts used in the tests. This constant can be initialized using `lazy_static!` macro with a function performing a loop to measure number of iterations per second. The idea of such constant is similar to [BogoMips](https://en.wikipedia.org/wiki/BogoMips) used in Linux kernel.

Ref #1113 #1180.

**Comment by lukesteensen** [comment]
This is an interesting idea! It's certainly a lot less intrusive than flipping everything inside out to make it test-drivable.

It does seem like a simple `lazy_static` would be enough to make this work. We should still consider other options to make tests less timing-dependent, but this could give us a quick and easy boost to reliability.

**Comment by jszwedko** [comment]
Closing as I don't anticipate us doing this. Instead of explicit timeouts, we should instead have tests retry assertions, with a back-off, up to a limit. This allows fast systems to pass tests more quickly while slow systems will still pass eventualy.
