### ISSUE TITLE
Missing metrics for vector/fluent source when starting vector with -q

### ISSUE THREAD

**Issue by tuananhnguyen-ct** [vectordotdev/vector#11844]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When starting vector with -q or environment variable VECTOR_LOG=WARN, internal_metrics stopped emitting metrics for vector and fluent source.

Metrics missing include vector_processed_bytes_total, component_received_events_total and events_in_total

Another source (aws_s3) is not affected.

Metric vector_component_received_events_total and vector_component_sent_event_bytes_total without any label is present. The value for vector_component_received_events_total without label matches the value of corresponding metric for related transform that use the vector source.

### Version

0.19.2

**Comment by jszwedko** [comment]
Thanks for reporting this @tuananhnguyen-ct ! We fixed it in https://github.com/vectordotdev/vector/pull/11856 which will be included in the next release.
