### ISSUE TITLE
how to change map to clickhouse Nested structure?

### ISSUE THREAD

**Issue by dengc367** [vectordotdev/vector#11848]
### Discussed in https://github.com/vectordotdev/vector/discussions/11834

<div type='discussions-op-text'>

<sup>Originally posted by **dengc367** March 15, 2022</sup>
I use vector to `parse_json` from json file to clickhouse,  because the json  like below

`{"res":"5e60bbc17f068d0ba4f156e5","_id":"622e150183d43d02dca5139b","properties":{"key1":"value1", "key2":2, "key3": 3.0}}`

and the clickhouse columns have a `Nested` structure like below:
```
res String,
_id String,
properties.key Array(Nullable(String)),
properties.value Array(Nullable(String)),
```

so I need change the above json to the clickhouse format:

`{"res":"5e60bbc17f068d0ba4f156e5","_id":"622e150183d43d02dca5139b","properties.key": ["key1","key2","key3"],"properties.value": ["value1","2","3.0"]`

@binarylogic  how to transform it use the `vector vrl`?</div>

**Comment by jszwedko** [comment]
Hi @dengc367 ,

I think this currently isn't possible in VRL. You can use the `lua` transform to do it though. It will be possible when #11230 lands to add iteration support to VRL.  I also created a separate issue for `keys` and `values` functions that would have also helped here: https://github.com/vectordotdev/vector/issues/11888

I'll close this in-lieu of those two issues, but you can follow along there and add any additional thoughts.
