### ISSUE TITLE
Add refresh_interval xm[minutes] / xh[hours] option under enrichment_tables.file

### ISSUE THREAD

**Issue by iamyourexpert** [vectordotdev/vector#11874]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

We refresh enrichment table csv file every hour. We would like to have a global option under  enrichment_tables.file so it gets reloaded after x minutes/seconds without having to restart the vector.

### Proposal

a global option under  enrichment_tables.file 
called refresh_interval which can take inputs like xh [hour] xm[minutes] . x is a non zero whole number.

**Comment by blake-mealey** [comment]
An alternative here would be to add a watcher for enrichment table files with the `--watch-config` option. Or even have a separate `--watch-enrichment-tables` option just for enrichment tables.

Our use case is that we'd like engineers to be able to deploy changes to an enrichment table which affects routing of events without needing to restart the vector instances.

**Comment by jszwedko** [comment]
Agreed, I think including support for this via `--watch-config` would be consistent. As a workaround, the files should be reloaded on SIGHUP so you can issue that on a schedule.

**Comment by jszwedko** [comment]
We discussed this issue today and came to two conclusions:

1.. Enrichment tables should respect `--watch-config`. That is: they should reload automatically on-change when `--watch-config` is used.
2. For reloading on an interval we encourage users to issue a SIGHUP using `cron` or a SystemD timer

I repurposed https://github.com/vectordotdev/vector/issues/11817 to cover (1) here. Given (2) we think should be covered by an external SIGHUP rather than Vector I'll close this issue, but please leave any additional thoughts!

**Comment by jszwedko** [comment]
> Thanks for the update! Is this work prioritized? I could take a stab at a PR if not.

Hey! It's unlikely we'd be able to get to it soon so we'd be happy to review a PR for it! Feel free to hop into the [Discord](https://chat.vector.dev/) if you want to chat at all during implementation. Also happy to review draft PRs early to give you more guidance.

**Comment by jszwedko** [comment]
Also, just to confirm, we would support having `--watch-config` watch enrichment tables. I think we'd want to have some more discussion before implementing a schedule refresh function since that feels fairly well covered by something like `cron` or SystemD.

**Comment by blake-mealey** [comment]
Right, I'm mostly interested in the watch config support :+1:
