### ISSUE TITLE
Kafka source/sink with "long" as message_key unreadable as long

### ISSUE THREAD

**Issue by smlgbl** [vectordotdev/vector#11878]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Input: kafka topic with Long as message keys, e.g. 123456, a.k.a. 8-byte number
Expected: kafka topic with 8-byte Long as message keys.
Result: message keys get up to 10 bytes in size...

Example input that works: 123
Example input that doesn't work: 1234

Output of console consumer when sending messages (first msg with long-key '123', second msg with '1234':
```
$ ./kafka-console-consumer --bootstrap-server kafka-server --topic sml-test --property print.key=true --key-deserializer "org.apache.kafka.common.serialization.LongDeserializer"

123	{"shopId":123,"offerKey":"abcdefg123456lasdfaiew"}
ERROR Unknown error when running consumer:  (kafka.tools.ConsoleConsumer$)
org.apache.kafka.common.errors.SerializationException: Size of data received by LongDeserializer is not 8
```

Output of the same console consumer on the source topic (christoph-test in the example config):
```
$ ./kafka-console-consumer --bootstrap-server kafka-server --topic christoph-test --property print.key=true --key-deserializer "org.apache.kafka.common.serialization.LongDeserializer"

123	{"shopId":123,"offerKey":"abcdefg123456lasdfaiew"}
1234	{"shopId":1234,"offerKey":"abcdefg123456lasdfaiew"}
```

Output of the console sink for the example messages:
```
{"headers":{"app.name":"Conduktor"},"message":"{\"shopId\":123,\"offerKey\":\"abcdefg123456lasdfaiew\"}","message_key":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000{","offset":13,"partition":3,"source_type":"kafka","timestamp":"2022-03-17T13:13:58.214Z","topic":"christoph-test"}
{"headers":{"app.name":"Conduktor"},"message":"{\"shopId\":1234,\"offerKey\":\"abcdefg123456lasdfaiew\"}","message_key":"\u0000\u0000\u0000\u0000\u0000\u0000\u0004�","offset":6,"partition":4,"source_type":"kafka","timestamp":"2022-03-17T13:14:03.217Z","topic":"christoph-test"}
```

### Configuration

```text
[sources.kafka_in]
type = "kafka"
topics = [ "christoph-test" ]
bootstrap_servers = "kafka-server"
group_id = "vector.aiven.bridge"
auto_offset_reset = "latest"

[sinks.kafka_out]
type = "kafka"
inputs = ["kafka_in"]
bootstrap_servers = "kafka-server"
topic = "sml-test"
encoding.codec = "text"
key_field = "message_key"
headers_field = "headers"
tls.enabled = false
sasl.enabled = false

[sinks.console_out]
type = "console"
inputs = [ "kafka_in" ]
target = "stdout"
encoding.codec = "json"
```

### Version

version="0.20.0" arch="x86_64" build_id="2a706a3 2022-02-11"

**Comment by amexboy** [comment]
@smlgbl Thank you for reporting :D


I just found this line and it seems like the key is always decoded as a string. 

    let msg_key = msg
      .key()
      .map(|key| Value::from(String::from_utf8_lossy(key).to_string()))
      .unwrap_or(Value::Null);

https://github.com/vectordotdev/vector/blob/master/src/sources/kafka.rs#L216

Maybe it makes sense to use the decoder codec for the key as well. 


I

**Comment by jszwedko** [comment]
Indeed, thanks for reporting @smlgbl .

Both the source and sink expect string keys right now. We'll need to adjust that to allow it to be non-string.

The source deserialization is linked above. The sink serialization happens here:

https://github.com/vectordotdev/vector/blob/0103e64e4d813ad8fb66e67f2056b6d10930f68b/src/sinks/kafka/service.rs#L95

As you can see it also always serializes as a string.

**Comment by smlgbl** [comment]
But actually on the serialization part, the key is treated as a byte array, is it not?
See https://github.com/vectordotdev/vector/blob/0103e64e4d813ad8fb66e67f2056b6d10930f68b/src/sinks/kafka/service.rs#L31
Why is it not treated as a byte array on deserialization?

**Comment by jszwedko** [comment]
> But actually on the serialization part, the key is treated as a byte array, is it not? See
> 
> https://github.com/vectordotdev/vector/blob/0103e64e4d813ad8fb66e67f2056b6d10930f68b/src/sinks/kafka/service.rs#L31
> 
> 
> Why is it not treated as a byte array on deserialization?

Ah, yeah, you are right, I think we could just read it as bytes.
