### ISSUE TITLE
debian packages published with wrong file name convention

### ISSUE THREAD

**Issue by ccmtaylor** [vectordotdev/vector#11885]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Quoting the Debian [packaging documentation](https://www.debian.org/doc/manuals/debian-faq/pkg-basics.en.html#pkgname):

> The Debian binary package file names conform to the following convention: `<foo>_<VersionNumber>-<DebianRevisionNumber>_<DebianArchitecture>.deb`

However, the vector packages released to the Vector [debian repo](https://vector.dev/docs/setup/installation/operating-systems/debian/) are named `<foo>-<VersionNumber>-<DebianArchitecture>.deb` (note the dashes instead of underscores).

This has caused some issues for us when vendoring the packages into an internal repo for deployment because the software we use (mini-dinstall) validates that packages adhere to the naming convention. I've filed an [upstream bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1007839), and was able to work around it internally, but it would be nice if Vector adhered to the conventions for release artifacts.

### Configuration

```text
n/a
```

### Version

vector 0.20.0 (x86_64-unknown-linux-gnu 2a706a3 2022-02-11)

### References

* https://www.debian.org/doc/manuals/debian-faq/pkg-basics.en.html#pkgname
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1007839

**Comment by jszwedko** [comment]
Hi @ccmtaylor !

Good catch. I've updated the package names to match the convention in https://github.com/vectordotdev/vector/pull/11887 .

**Comment by ccmtaylor** [comment]
Wow, that was quick! Thank you!
