### ISSUE TITLE
Add `keys` and `values` functions to VRL

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#11888]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Motivated by https://github.com/vectordotdev/vector/issues/11848 where a `values` function that returns the values from an object in VRL would have allowed them do accomplish what they were trying to.

#11230 will also allow for this, but I think these functions are common enough that we should have them too.

### Proposal

* Add a `keys` function that returns the keys from a VRL object.
* Add a `values` function that returns the values from a VRL object.

### Version

vector 0.20.0 (x86_64-apple-darwin 2a706a3 2022-02-10)

**Comment by jonathanpv** [comment]
closing due to mentioned issue that was merged 15 days ago
