### ISSUE TITLE
Include aws account id in `aws_ec2_metadata` transform

### ISSUE THREAD

**Issue by AFriemann** [vectordotdev/vector#11900]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

This helps querying log events depending on the AWS account

### Attempted Solutions

according to the docs only `[instance-id local-hostname local-ipv4 public-hostname public-ipv4 ami-id availability-zone vpc-id subnet-id region]` are available

### Proposal

add a field `account-id` to the list

### Version

vector 0.16.1 (x86_64-unknown-linux-gnu 739e878 2021-08-26)

**Comment by jszwedko** [comment]
Just leaving a note for whoever picks this issue up, the account id does appear to be in the `instance-identity` document:

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-identity-documents.html

I think we could probably just add all of the ability to add all of the fields from that document.

**Comment by jszwedko** [comment]
Ah, we already are fetching some fields from that document so this is just a new one 😄
