### ISSUE TITLE
Change of name "Vector"

### ISSUE THREAD

**Issue by Esc4iCEscEsc** [vectordotdev/vector#11972]
Searched around and couldn't find any existing issues about this problem.

Vector seems really interesting, but the name is... Unfortunate at best.

Not only is Vector a really common word, which makes it hard to search for when the search space is already filled with things using the same name for multiple things.

It's also one of the most common (if not the) Rust data structures, so adding "rust" to the search term makes it almost worst.

Since it's relatively early (at least publicly), I'm hereby formally requesting the consideration of changing the name to something unique, to facilitate better user experience when it comes to searching for Vector (the name) related subjects.

**Comment by jszwedko** [comment]
Hi @Esc4iCEscEsc,

Thanks for filing this! This discussion has come up before in different forums and so a recorded answer here will be useful.

While we do recognize that the name can make it hard to search as independent search term, it is unlikely that we will change it at this point given we've already built up the branding and a community around the current name that we would harm with a name change. We also don't see the current name as inhibiting Vector's growth. Searching `vector` along with another term (like `log`, `metric`, `transform`, `syslog`, etc.) generally does return relevant results.

Similar to Go, with Golang, Rust with Rustlang, we may try to standardize a variant on the name that makes it easier to search (like "vector.dev" or "vectordotdev") though. Open to suggestions here 🙂
