### ISSUE TITLE
Audit and test components for adherence to component spec

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#11991]
I discovered that the `datadog_logs` and `datadog_metrics` sink are not publishing `component_sent_bytes_total` even though we thought we had audited all of the sinks as part of https://github.com/vectordotdev/vector/pull/11383.

We should do another pass across all components and ensure they are publishing the expected metrics. We should also add tests for this.

**Comment by binarylogic** [comment]
Closing in favor of #12921
