### ISSUE TITLE
Add a `char_length` VRL function

### ISSUE THREAD

**Issue by StephenWakely** [vectordotdev/vector#12019]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Currently [`length`](https://vector.dev/docs/reference/vrl/functions/#length) returns the number of bytes of a string. It might be useful to have a function that returns the number of characters.

### Attempted Solutions

A current workaround is:

```coffee
 length(split("ñandú", "")) - 2
```

But that's not really ideal.

### Version

v0.20

**Comment by hhromic** [comment]
Perhaps instead of a new function, an argument for `length()` could be introduced to set the counting mode for strings?

For example (didn't spend much time on argument naming!):
```coffee
length("ñandú", use_chars: true)
length("ñandú", string_mode: "chars")
length("ñandú", string_mode: "bytes")
```

**Comment by jszwedko** [comment]
Another suggestion: `strlen`.
