### ISSUE TITLE
Vector 0.20.0 fails to parse valid syslog

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#12013]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

From https://github.com/vectordotdev/vector/issues/11723#issuecomment-1082125819

The message field:

```
{"host":"xxx.xxx.xxx.xxx","message":"<150>1 2022-03-29T18:04:30.415522+02:00 xxx xxx: [2022-03-29T18:04:30.415+0200] xxx.xxx.xxx.xxx - - - \"CONNECT xxx.xxx.xxx.xxx:xxx HTTP/1.0\" 200 0 65 \"-\" \"xxx/xxx\" TCP_DENIED:HIER_NONE","source_type":"socket","timestamp":"2022-03-29T16:04:30.416001945Z"}
```

_seems_ to be valid syslog.

At the least, https://github.com/EasyPost/syslog-rfc5424-parser parses it correctly.

### Version

vector 0.20.0 (x86_64-apple-darwin 2a706a3 2022-02-10)

### Debug Output

```text
$ . = {"host":"xxx.xxx.xxx.xxx","message":"<150>1 2022-03-29T18:04:30.415522+02:00 xxx xxx: [2022-03-29T18:04:30.415+0200] xxx.xxx.xxx.xxx - - - \"CONNECT xxx.xxx.xxx.xxx:xxx HTTP/1.0\" 200 0 65 \"-\" \"xxx/xxx\" TCP_DENIED:HIER_NONE","source_type":"socket","timestamp":"2022-03-29T16:04:30.416001945Z"}
{ "host": "xxx.xxx.xxx.xxx", "message": "<150>1 2022-03-29T18:04:30.415522+02:00 xxx xxx: [2022-03-29T18:04:30.415+0200] xxx.xxx.xxx.xxx - - - \"CONNECT xxx.xxx.xxx.xxx:xxx HTTP/1.0\" 200
 0 65 \"-\" \"xxx/xxx\" TCP_DENIED:HIER_NONE", "source_type": "socket", "timestamp": "2022-03-29T16:04:30.416001945Z" }
$ parse_syslog!(.message)
function call error for "parse_syslog" at (0:23): unable to parse input as valid syslog message
```

**Comment by sim0nx** [comment]
Hi
Fore completeness sake, my pre v0.20 config was similar as in #11723 i.e.:
```
[sources.syslog]
type = "syslog"
address = "0.0.0.0:9009"
mode = "tcp"
```

only with the addition of TLS config as well.

Just trying stuff, I tested:
- socket+decoder=syslog
- socket+decoder=bytes and then in VRL parse_syslog

both failed.

With source=syslog I get the same error messages as noted earlier:
```
Mar 29 17:26:18 xxxxxx vector[3666345]: 2022-03-29T15:26:18.037107Z  WARN source{component_kind="source" component_id=xxxxxx component_type=syslog component_name=xxxxxx}:connection{peer_addr=xxx.xxx.xxx.xxx:55108}: vector::internal_events::decoder: Failed deserializing frame. error=unable to parse input as valid syslog message internal_log_rate_secs=10
Mar 29 17:26:18 xxxxxx vector[3666345]: 2022-03-29T15:26:18.058462Z  WARN source{component_kind="source" component_id=xxxxxx component_type=syslog component_name=xxxxxx}:connection{peer_addr=xxx.xxx.xxx.xxx:55108}: vector::internal_events::decoder: Internal log [Failed deserializing frame.] is being rate limited.
Mar 29 17:26:28 xxxxxx vector[3666345]: 2022-03-29T15:26:28.052380Z  WARN source{component_kind="source" component_id=xxxxxx component_type=syslog component_name=xxxxxx}:connection{peer_addr=xxx.xxx.xxx.xxx:40192}: vector::internal_events::decoder: Internal log [Failed deserializing frame.] has been rate limited 1313 times.
```

This was working as expected up to v0.19.3 (to which I have downgraded for the time being).

**Comment by StephenWakely** [comment]
So, from what I can see that message is not valid [5424](https://www.rfc-editor.org/rfc/rfc5424.html). If we look at the spec for the header:

```
 HEADER          = PRI VERSION SP TIMESTAMP SP HOSTNAME
                        SP APP-NAME SP PROCID SP MSGID
```

And the header of that message:

```
<150>1 2022-03-29T18:04:30.415522+02:00 xxx xxx: [2022-03-29T18:04:30.415+0200] xxx.xxx.xxx.xxx 
 ```

What would be the `PROCID` is  `[2022-03-29T18:04:30.415+0200]`, and the MSGID would be `xxx.xxx.xxx.xxx`. Neither of which are valid.

This is not a regression in terms of parsing. Testing this on v0.16 also fails to parse this message. I'm curious what https://github.com/EasyPost/syslog-rfc5424-parser is doing here and will need to take a look.

I suspect the regression has been caused by #11244. Previously we would allow invalid messages through - the entire message would be placed in the  `.message`. Now this raises an error.

I'm not sure what the best way forward here is. I'm leaning towards reverting #11244, but others may have different opinions. @jszwedko do you have any suggestions?
