### ISSUE TITLE
[aws_cloudwatch_logs sink] Log retention is not configurable

### ISSUE THREAD

**Issue by amanmahajan26** [vectordotdev/vector#12038]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Hi, I am using aws_cloudwatch_logs sink to push logs to CloudWatch. I want to be able to set the retention period for the logs, but I do not see any attribute with which I can configure this. Want to understand if this is possible using this plugin.
https://vector.dev/docs/reference/configuration/sinks/aws_cloudwatch_logs/

**Comment by jszwedko** [comment]
Hi @amanmahajan26 !

If you are relying on Vector to create the log groups, you are correct that this isn't currently configurable.

**Comment by jszwedko** [comment]
We can leave this issue open to make it configurable though 😄

**Comment by jfavellar90** [comment]
+1 for this feature

**Comment by jszwedko** [comment]
> Hello @jszwedko I wanted to work on this if its not already taken up by someone Would you be willing to provide more details or point me to similar implementation to work on it
> 
> thanks in advance

Hi @swapz-z ! We'd be happy to accept a contribution for this. https://github.com/vectordotdev/vector/tree/master/src/sinks/aws_cloudwatch_logs is the code for this sink. Hopefully you can get a sense of it from there, but let us know if you need more pointers.

**Comment by mmerickel** [comment]
Just ran across this while porting my config from fluentd and it would really help me a lot. We create log groups dynamically based on kubernetes namespace and want to be able to specify retention. Since we can't know the log groups up front our only other choice would be some lambda eventbridge subscriber to modify the retention on newly created log groups which I'm... not looking forward to doing.

**Comment by hawkesn** [comment]
@swapz-z - this might be helpful:
- PutRetentionPolicy: https://docs.rs/aws-sdk-cloudwatchlogs/0.22.0/aws_sdk_cloudwatchlogs/operation/struct.PutRetentionPolicy.html
- DeleteRetentionPolicy: https://docs.rs/aws-sdk-cloudwatchlogs/0.22.0/aws_sdk_cloudwatchlogs/operation/struct.DeleteRetentionPolicy.html

**Comment by s33kers** [comment]
+1 for this feature
