### ISSUE TITLE
Prometheus Scrape fails when encountering a _bucket value greater than MAX:u32

### ISSUE THREAD

**Issue by Ardiea** [vectordotdev/vector#12043]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Prometheus Scrape fails when encountering a _bucket value greater than MAX:u32

When scraping a concourse metrics endpoint using vector, concourse presents the following histogram metric:

```
go_gc_heap_allocs_by_size_bytes_total_bucket{le="24.999999999999996"} 1.8939392877e+10
```

Vector, in turn presents the following error message about this line: 
```
Mar 31 14:21:08 ip-10-1-1-200 vector[76587]: 2022-03-31T14:21:08.003924Z ERROR source{component_kind="source" component_id=collect_concourse_metrics component_type=prometheus_scrape component_name=collect_concourse_metrics}: vector::internal_events::prometheus: Parsing error. url=http://localhost:9391/metrics error=ValueOutOfRange { value: 18939392877.0 } error_type="parse_failed" stage="processing" internal_log_rate_secs=1
```

Which I believe I have traced down to these bits of code:

https://github.com/vectordotdev/vector/blob/a398504fe21ff64a065f97b203539ce986e4e889/lib/prometheus-parser/src/lib.rs#L169-L178

https://github.com/vectordotdev/vector/blob/a398504fe21ff64a065f97b203539ce986e4e889/lib/prometheus-parser/src/lib.rs#L238-L244

And 18939392877 is, indeed, larger than 4294967295. But I feel like is a valid value for a metric, is it not? There shouldn't really be a limit?

I don't actually care about this particular metric, I even discard it in my transforms, but as a result of this parse failure, vector seems to discard the entire scrape and nothing is passed through to my transforms or sinks.

### Configuration

```text
sources:
  collect_concourse_metrics:
    type: prometheus_scrape
    endpoints:
    - http://localhost:9391/metrics
    scrape_interval_secs: 10
```

### Version

vector 0.20.0 (x86_64-unknown-linux-gnu 2a706a3 2022-02-11)

**Comment by hhromic** [comment]
This is an important issue that also would affect us :(

According to the [Prometheus text-based exposition format](https://prometheus.io/docs/instrumenting/exposition_formats/#line-format):

> `value` is a float represented as required by Go's [ParseFloat()](https://golang.org/pkg/strconv/#ParseFloat) function. In addition to standard numerical values, NaN, +Inf, and -Inf are valid values representing not a number, positive infinity, and negative infinity, respectively.

The `ParseFloat()` function says:
> ParseFloat converts the string s to a floating-point number with the precision specified by bitSize: 32 for float32, or 64 for float64. When bitSize=32, the result still has type float64, but it will be convertible to float32 without changing its value.

Unfortunately the Line format documentation is not clear on the `bitSize` to use. However, looking at Prometheus' source:
https://github.com/prometheus/prometheus/blob/ed0c68224ee7a76d93230c1b38af369d330ee007/model/textparse/promparse.go#L420-L426

It is clear now that they mean 64-bit float representation. In other words, the sample you are trying to scrape is correct and Vector should handle this range correctly.

**Comment by hhromic** [comment]
> whether it would make sense to store `f64` bucket values for histograms.

Note that _all_ metrics in Prometheus follow the same `f64` value format, not only buckets. This is specially important for counters that reach really large numbers in time. Some metrics can very well exceed 32-bit ranges.

> This would be a breaking change to the metrics model.

In my humble opinion, I think in this case is more important for Vector to align to the correct numeric representation from Prometheus. Otherwise Vector simply is losing information from the scraped metrics.

**Comment by hhromic** [comment]
Hey @jszwedko, my bad! I wrongly read yesterday that _all_ metric values are being parsed as `u32` by Vector. I now realised that only the `_bucket` and `_count` metrics are being parsed from `f64` to `u32`. So the impact is way smaller than I thought.

With that being said, I think using `u64` for these metrics should be ok.. If a metric value breaks `u64`, then it would break OpenMetrics as well, so Vector would not be going off-spec here anyway.
