### ISSUE TITLE
Loki sink should emit a warning if it errors when it expands a label template

### ISSUE THREAD

**Issue by StephenWakely** [vectordotdev/vector#12055]
Currently if an error occurs while the Loki Sink is expanding a label template it just silently drops the label. This could happen if the template includes a field that doesn't exist in the event.

It would be useful if we could at least emit a warning so the user has an indication as to why the label is missing.

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/17052
