### ISSUE TITLE
Kafka Source consumes some messages more then once when HPA scales up in EKS

### ISSUE THREAD

**Issue by bhataprameya** [vectordotdev/vector#12084]
### Problem

When HPA triggers in EKS, the Kafka source consumes some duplicate message that is already consumed by some other pod. This causes the payloads to be written twice in the sink

### Configuration

```text
sources:
    kafka:
      type: kafka
      acknowledgements:
        enabled: true
      auto_offset_reset: largest
      bootstrap_servers: abc:9092
      commit_interval_ms: 1000
      fetch_wait_max_ms: 100
      group_id: vector
      topic_key: topic
      session_timeout_ms: 10000
      socket_timeout_ms: 60000
      topics:
        - MY_TOPIC
```

### Version

0.20.0

**Comment by jszwedko** [comment]
Hi @bhataprameya !

Apologies for the delayed response.

As you discovered, this can happen when rebalancing consumers. A new consumer may receive a partition that a previous consumer had, but is still in the middle of processing messages from. This may result in duplicate messages. In general, Kafka maintains "at least once" delivery semantics.

Let me know if that makes sense.

**Comment by bhataprameya** [comment]
yes, that makes sense. Is there any way to avoid it as of today ?

**Comment by jszwedko** [comment]
> yes, that makes sense. Is there any way to avoid it as of today ?

Unfortunately, I don't think so. I'd recommend designing whatever downstream system is being used to be able to deal with duplicates (e.g. you can specify a unique id for an `elasticsearch` sink to deduplicate on).

**Comment by jszwedko** [comment]
Closing this as expected behavior, but let me know if you have any other questions!
