### ISSUE TITLE
Document native codecs

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#12096]
For the initial documentation, we would like to:

* Generate a JSON schema for event that is tested against our corpus of encoded events
* Add it to the list of supported codecs for all sources that support it, for example: https://vector.dev/docs/reference/configuration/sources/exec/#decoding, but mark it as experimental. It should link to the protobuf and JSON schema definitions in Github. Later we will integrate these into the website.

**Comment by lukesteensen** [comment]
Closed by #12048
