### ISSUE TITLE
Fix handling of negative acknowledgements in stream sources

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#12109]
Sources that lack protocol-level support for selective acknowledgements (for example, the `file` or `kafka` sources) have no way of indicating to their upstream that a single message or batch of messages was rejected. In the interest of continuing to make progress, those sources ignore the status value of the end-to-end acknowledgement signal, and simply acknowledge everything once Vector has completed handling the data.

This leads to some bad consequences. For example, if a Kafka API key is revoked, this will result in Vector dropping all subsequent messages.

The following sources need to be reworked to simply stop processing (ie shut down) when they encounter a negative acknowledgement, so that the operator can fix the situation and restart Vector before data is lost. This may also be worked around within Vector with a dead letter queue.

- [x] #12936 
- [x] #12913
- [x] #12901

**Comment by bruceg** [comment]
In discussion, we have decided to make these sources stop updating the checkpoint on whichever stream receives a negative acknowledgement (if applicable, `journald` only has one stream). This will allow progress on the other streams while avoiding a false acknowledgement on streams with failed deliveries.

**Comment by bruceg** [comment]
All parts of this issue are now completed.

**Comment by jszwedko** [comment]
Nice work!
