### ISSUE TITLE
`datadog_metrics` sink does not support sending aggregated summaries

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#12126]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Mentioned by https://github.com/vectordotdev/vector/issues/8626#issuecomment-1091964819

Aggregated summaries cannot be made incremental and so are dropped by:

https://github.com/vectordotdev/vector/blob/82ea429a7fe42ce48c5d52dffb2801507c6ca81b/src/sinks/datadog/metrics/normalizer.rs#L34

Which calls:

https://github.com/vectordotdev/vector/blob/82ea429a7fe42ce48c5d52dffb2801507c6ca81b/src/sinks/util/buffer/metrics.rs#L188-L193

In turn:

https://github.com/vectordotdev/vector/blob/82ea429a7fe42ce48c5d52dffb2801507c6ca81b/src/sinks/util/buffer/metrics.rs#L247-L254

Which hits the `else` block since `subtract` skips AggregatedSummaries.

### Version

vector 0.20.0 (x86_64-apple-darwin 2a706a3 2022-02-10)

### Additional Context

Some ideas for dealing with this:

* Breaking up `AggregatedSummary`s at the source and publishing them as counters (`sum`, `count`) and gauges (`percentiles`). This would break up the incoming metric into X metrics.
* Updating normalization to handle aggregated summaries in a special manner

**Comment by prognant** [comment]
Ultimately we should probably support both mode through a config option as either emitting the summary as a bundle of Datadog "[well known](https://github.com/DataDog/datadog-agent/blob/221c333/pkg/config/config_template.yaml#L183-L200)" metrics or convert the summary to a Datadog native distribution/sketch are perfectly legit.

There are pros/cons for both, switching from one to another may not be possible. While native sketches allow better merging capability when aggregating multiple host on Datadog dashboards, this is still somehow flagged as [beta](https://github.com/DataDog/datadog-agent/blob/221c333/pkg/config/config_template.yaml#L202-L213) for custom dogstatsd metrics. But IMHO we should really aim to support both.
