### ISSUE TITLE
Support surpressing timestamp in `splunk_hec` sink

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#12128]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Splunk is capable of parsing timestamps out of messages, but Vector always adds a `timestamp` to the event sent to Splunk, even if the timestamp is not set it the incoming event (it defaults to the current timestamp). It'd be nice to suppress this behavior to let Splunk handle setting the event timestamp.

### Proposal

A new configuration option, `timestamp_key`, is added to the `splunk_hec_logs` sink. It should default to the configured [log schema `timestamp_key`](https://vector.dev/docs/reference/configuration/global-options/#log_schema.timestamp_key) but be settable to `""` to disable setting the timestamp in the event sent to Splunk.

As part of this, we should check what Splunk's behavior is if no timestamp is sent and it cannot parse a timestamp out of the sent message. If it defaults to the event ingestion time (my expectation) we should remove the behavior in Vector that defaults the current timestamp in the `splunk_hec_logs` sink if the timestamp is missing or not the correct type. Instead, Vector should log a warning and leave the timestamp out and let Splunk handle setting it.

### Version

vector 0.20.0 (x86_64-apple-darwin 2a706a3 2022-02-10)

**Comment by JeanMertz** [comment]
I'm assuming the [`encoding.except_fields`](https://vector.dev/docs/reference/configuration/sinks/splunk_hec_logs/#encoding.except_fields) option isn't working for this particular case?
