### ISSUE TITLE
tls.verify_certificate option is undocumented for some sources/sinks -- please document

### ISSUE THREAD

**Issue by johnalotoski** [vectordotdev/vector#12129]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

prometheus scrape source does not document a `tls.verify_certificate` option [here](https://vector.dev/docs/reference/configuration/sources/prometheus_scrape/#tls.verify_hostname), only a `tls.verify_hostname` option.

For testing, I needed to use the `tls.verify_certificate` option which took a while to find by digging through source.  Otherwise, I kept receiving:
```
ERROR source{component_kind="source" component_id=prom component_type=prometheus_scrape component_name=prom}: vector::internal_events::prometheus: HTTP request processing error. url=https://$IP:$PORT/metrics error=CallRequest { source: hyper::Error(Connect, Custom { kind: Other, error: ConnectError { error: Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 337047686, library: "SSL routines", function: "tls_process_server_certificate", reason: "certificate verify failed", file: "ssl/statem/statem_clnt.c", line: 1914 }]))) }, verify_result: X509VerifyResult { code: 20, error: "unable to get local issuer certificate" } } }) } error_type="request_failed" stage="receiving" internal_log_rate_secs=10
```
Using the documented option `tls.verify_hostname`, did not resolve this error during testing.  It looks like this option is also undocumented for a number of other sources and sinks.

### Configuration

```text
"sources": {
    "prom": {
      "endpoint_tag": "endpoint",
      "endpoints": [
        "https://$IP:$PORT/metrics"
      ],
      "instance_tag": "instance",
      "scrape_interval_secs": 10,
      "tls": {
        "verify_certificate": false
      },
      "type": "prometheus_scrape"
    },
    ...
```

### Version

vector 0.20.0 (x86_64-unknown-linux-gnu)

### Additional Context

Unless there is a special reason not to, please document this to save others from spending unnecessary time looking for this option also.  I recognize it is considered insecure.  Logs are also emitted clearly stating this:
```
WARN vector::tls::settings: The `verify_certificate` option is DISABLED, this may lead to security vulnerabilities.`
```

**Comment by spencergilbert** [comment]
Hi @johnalotoski thanks for opening - I'm having trouble finding the exact PR which we've recently merged. But this was fixed recently and can be seen on the [latest version of the docs site](https://master.vector.dev/docs/reference/configuration/sources/prometheus_scrape/#tls.verify_certificate) the "stable" site will be updated when we cut `0.21` (aiming for early next week).
