### ISSUE TITLE
Implement configuration schema RFC

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#12141]
Implement https://github.com/vectordotdev/vector/blob/master/rfcs/2022-02-23-9481-config-schema.md

## End Goal

Ability to run a single Vector subcommand that generates a JSON Schema document that can be used to validate any configuration that Vector itself would already accept.

**Comment by tobz** [comment]
Task list for implementation as defined by the RFC:

- [] #12221
- [] #12223
- [] #12224
- [] #12228

**Comment by jszwedko** [comment]
The RFC has been implemented.
