### ISSUE TITLE
Local variable scoping breaks local variables in the VRL CLI

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#12204]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The local variable scoping feature, introduced in #12017, prevents local variables from working in the VRL CLI:
```
$ x=5
5

$ x

error[E701]: call to undefined variable
  ┌─ :1:1
  │
1 │ x
  │ ^
  │ │
  │ undefined variable
```

### Version

0.21 (current master)

**Comment by jszwedko** [comment]
When resolving this, we should get some more comprehensive tests that verify the scoping rules.
