### ISSUE TITLE
chore(config): add subcommand to generate configuration schema

### ISSUE THREAD

**Issue by tobz** [vectordotdev/vector#12224]
(_This issue is a task related to #12141: **Implement configuration schema RFC**_)

Once #12223 is complete, we'll need a way to start easily and consistently emitting the resulting configuration schema that we get for the primary Vector configuration. We'll provide this capability by adding a Vector subcommand -- `vector generate-config-schema` -- that provides the simple glue logic for actually utilizing `Configurable` and outputting a valid JSONSchema document.

List of outcomes/acceptance criteria:
- `vector generate-schema` will emit a valid JSONSchema document
- the schema document will include top-level metadata that includes the information about the Vector release itself (whether an official release version (v0.20.0, etc) or a commit hash in the case of a local or nightly build)

**Comment by spencergilbert** [comment]
Now that we have at least three "generating" commands would it make sense to reorganize them under `vector generate`?

- `vector generate`: produces a populated Vector configuration
- `vector generate-config-schema`: produces the entire schema of Vector's configuration
- `vector config`: produces a single JSON object from the provided configuration files
- I _thought_ there were issues for command/s to generate the schemas for Vector Native codecs (both protobuf and JSON schema)

**Comment by tobz** [comment]
Yeah, that's a good point.

I'll make a note to research where we're at as far as the generation
subcommands for native encoding schema stuff, and come up with a solution
to switch to a parameterized subcommand instead.

**Comment by tobz** [comment]
We're going to defer the bit about Vector version, etc, being top-level metadata as it depends on more sophisticated logic for parsing the metadata helper attributes and passing things other than flags/string literals.
