### ISSUE TITLE
File sink writes have synced with GCP Bucket sink writes

### ISSUE THREAD

**Issue by gschier** [vectordotdev/vector#12225]
### Problem

We use Vector at [Railway](https://railway.app) to aggregate logs for all of our users' applications. Here's our setup:

1. User Docker container writes to local Vector syslog source over UDP
2. Local Vector forwards all logs to central Vector
3. Central Vector writes to both filesystem (for realtime log tailing) and GCP Bucket (for longer-term queries) every 10 minutes

**We just started seeing a very strange issue where writing to the filesystem sink only happens when data is flushed to the GCP bucket (it no longer streams).**  We're also seeing timeouts in the log forwarder Vector logs when trying to send data to the Vector aggregator, which may or may not be related.

<img width="1565" alt="image" src="https://user-images.githubusercontent.com/587576/163475870-d3b01ec2-cc4c-4000-aa7f-70026380fe89.png">

## Questions 

1. Is there anything that could be causing this issue, such as internal back-pressure? It seems like the GCP sink is somehow blocking writes to the file sink
2. How can I debug the parts in this chain that may be causing issues?

### Configuration

```toml
# ---------------------- LOG FORWARDER CONFIG

[api]
enabled = true
playground = false

[sources.in_syslog]
type = "syslog"
address = "0.0.0.0:5142"
mode = "udp"

[sinks.out_vector]
type = "vector"
inputs = [ "in_syslog" ]
address = "${VECTOR_HOST}:5143"
version = "2"
buffer.type = "disk"
buffer.max_size = 100_000_000 # 100 MB

# Internal metrics for reporting to DataDog

[sources.in_internal]
type = "internal_metrics"
namespace = "vector"
scrape_interval_secs = 60

[sinks.out_datadog]
type = "datadog_metrics"
inputs = [ "in_internal" ]
api_key = "${DD_API_KEY}"
```

```toml
# ---------------------- LOG AGGREGATOR CONFIG

data_dir = "${LOGGER_VECTOR_PATH}"

[api]
enabled = true
playground = false

[sources.in_vector]
type = "vector"
version = "2"
address = "0.0.0.0:5143"

[sinks.out_file]
type = "file"
inputs = ["in_vector"]
compression = "none"
encoding = "ndjson"
path = "${LOGGER_VECTOR_PATH}/out_file/logs/%F_%H/{{ appname }}.log"

[sinks.out_gcp]
type = "gcp_cloud_storage"
inputs = ["in_vector"]
bucket = "${LOGGER_BUCKET_NAME}"
key_prefix = "logs/{{ appname }}/"
compression = "none"
buffer.type = "disk"
buffer.max_size = 104_900_000
batch.timeout_secs = 600
filename_append_uuid = false
encoding = "ndjson"
# Note: Time in `filename_time_format` uses time-of-last-log unlike `key_prefix` which uses time-of-first-log
filename_time_format = "%F/%T"

# Internal metrics for our reporting to DataDog

[sources.in_internal]
type = "internal_metrics"
namespace = "vector"
scrape_interval_secs = 60

[sinks.out_datadog]
type = "datadog_metrics"
inputs = ["in_internal"]
api_key = "${DD_API_KEY}"
```

### Version

vector 0.20.1 (x86_64-unknown-linux-gnu 60886d3 2022-04-07)

### Example Data

I'm not sure if these are related, but here are the timeouts we're seeing in the Vector -> Vector communication:

```text
Apr 14 21:17:14 production-stacker-33 vector[62811]: 2022-04-14T21:17:14.396440Z  WARN sink{component_kind="sink" component_id=out_vector component_type=vector component_name=out_vector}:request{request_id=91}: vector::sinks::util::retries: Request timed out. If this happens often while the events are actually reaching their destination, try decreasing `batch.max_bytes` and/or using `compression` if applicable. Alternatively `request.timeout_secs` can be increased.
Apr 14 21:17:14 production-stacker-33 vector[62811]: 2022-04-14T21:17:14.402756Z  WARN sink{component_kind="sink" component_id=out_vector component_type=vector component_name=out_vector}:request{request_id=92}: vector::sinks::util::retries: Request timed out. If this happens often while the events are actually reaching their destination, try decreasing `batch.max_bytes` and/or using `compression` if applicable. Alternatively `request.timeout_secs` can be increased.
Apr 14 21:17:14 production-stacker-33 vector[62811]: 2022-04-14T21:17:14.406945Z  WARN sink{component_kind="sink" component_id=out_vector component_type=vector component_name=out_vector}:request{request_id=93}: vector::sinks::util::retries: Request timed out. If this happens often while the events are actually reaching their destination, try decreasing `batch.max_bytes` and/or using `compression` if applicable. Alternatively `request.timeout_secs` can be increased.
Apr 14 21:17:14 production-stacker-33 vector[62811]: 2022-04-14T21:17:14.434171Z  WARN sink{component_kind="sink" component_id=out_vector component_type=vector component_name=out_vector}:request{request_id=94}: vector::sinks::util::retries: Request timed out. If this happens often while the events are actually reaching their destination, try decreasing `batch.max_bytes` and/or using `compression` if applicable. Alternatively `request.timeout_secs` can be increased.
```

### Additional Context

- We are writing to ~1000 `{{ appname }}` (meaning files and GCP objects) at a given time
- Vector aggregator is using < 1% CPU

**Comment by bruceg** [comment]
This does sound consistent with backpressure happening on the aggregator if the GCS sink is saturated for whatever reason. Are you seeing errors on the aggregator instance as well? Is this behavior something you are seeing all the time, or only after a certain period of activity? When did it start happening?

**Comment by gschier** [comment]
Thanks for the quick response!

It seems strange that it would be back-pressure because CPU usage is so low and data volume isn't even that high at around ~500MB/minute to a GCP bucket in the same region. Is it possible that somehow the writing of all ~1000 bucket objects somehow synced up and caused Vector to try writing ~1000 at the same time, every 10 minutes, potentially triggering this issue? Is there any way to get more insight into what the GCP sink is doing?

**_When did it start happening?_**
It started happening today about 6 hours ago. 

**_Are you seeing errors on the aggregator instance as well?_**
There are no errors at all on the aggregator, just a few warnings every so often saying that sending to the DataDog sink timed out (probably unrelated).

**_Is this behavior something you are seeing all the time, or only after a certain period of activity?_**
It seems to happen all the time now, since it started 6 hours ago. Restarting the forwarders and aggregator doesn't help at all. It doesn't even seem to be related to an increase in log throughput. Here's a screenshot of our metrics over the past month, which shows how stable things have been. The drop at the end is when this issue began.

<img width="2341" alt="image" src="https://user-images.githubusercontent.com/587576/163489653-02fee6c4-1440-44d0-ab63-cc1c6682d628.png">

**Comment by gschier** [comment]
I just tried disabling the GCP Bucket sink temporarily, and the file sink started working again immediately, so there's definitely something funky going on with the bucket sink.

**Comment by gschier** [comment]
Alright, this ended up being a silly mistake.

Our config uses `buffer.max_size` which I was reading as `batch.max_size` so I didn't think it was a problem. **The issue was that the sum of 5 minutes of buffered logs exceeded our relatively small buffer size of 100MB, causing blocking back pressure to build.** I adjusted the buffer max sized to 50 GB (half the total disk size) and added `batch.max_bytes` at 1MB.
