### ISSUE TITLE
Download links broken for 0.21.0 deb packages

### ISSUE THREAD

**Issue by saez0pub** [vectordotdev/vector#12243]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hello,

I have a problem downloading the new version of vector.
If I follow the download instruction for debian packages of https://vector.dev/releases/0.21.0/, I have a 404
These links in documentation are broken: Linux (deb)
* ARM64
* ARMv7
* x86_64

Is the documention pointing to the wrong link ?

I noticed that the asset files have now an extra -1 befor the architecture.

### Version

0.21.0

### Additional Context

```
for link in https://packages.timber.io/vector/0.21.0/vector-0.21.0-arm64.deb https://packages.timber.io/vector/0.21.0/vector-0.21.0-armhf.deb https://packages.timber.io/vector/0.21.0/vector-0.21.0-amd64.deb               
for> do
for> echo $link;curl -sfI "$link" | head -1
for> donehttps://packages.timber.io/vector/0.21.0/vector-0.21.0-arm64.deb
HTTP/2 404 
https://packages.timber.io/vector/0.21.0/vector-0.21.0-armhf.deb
HTTP/2 404 
https://packages.timber.io/vector/0.21.0/vector-0.21.0-amd64.deb
HTTP/2 404 
```

**Comment by saez0pub** [comment]
Looking at the github release page: https://github.com/vectordotdev/vector/releases

Usually, we would expect `vector-0.21.0-amd64.deb` but now we have `vector_0.21.0-1-amd64.deb`

There are two differences:
* `_` instead of `-` before the version
* `-1` after the version

**Comment by jszwedko** [comment]
Thanks for reporting this @saez0pub ! It should be fixed in a few minutes when the site redeploys.
