### ISSUE TITLE
Vector '-c' doesn't work any more with wildcards and multiple filenames

### ISSUE THREAD

**Issue by atibdialpad** [vectordotdev/vector#12257]
### A note for the community

Discussed here https://discord.com/channels/742820443487993987/746070591097798688/965585966658101349
FYI: 
@jszwedko 

### Problem

Earlier this used to work
a) vector -c *.toml OR
b) vector -c a.toml b.toml ...

With v21 this if failing
```
error: Found argument 'b.toml' which wasn't expected, or isn't valid in this context
```
However,
vector -C <dir> works

### Configuration

```text
Run Vector with '-c' and multiple config file OR wildcard pattern.
a) vector -c *.toml OR
b) vector -c a.toml b.toml ...
```

### Version

vector 0.21.0

### Debug Output

```text
vector -c *.toml
error: Found argument 'b.toml' which wasn't expected, or isn't valid in this context
```
With couple of config files a.toml b.toml
```


### Example Data

_No response_

### Additional Context

_No response_

### References

https://discord.com/channels/742820443487993987/746070591097798688/965585966658101349

**Comment by spencergilbert** [comment]
I suspect this came from a Clap upgrade - but a couple of things to note:

- `vector -c "*.toml"`: quoting the wildcard section expands properly
- `vector -c a.toml,b.toml`: comma separating loads properly as well

I've no good idea on how space separating the config paths worked in the past and suspect it stemmed from a bug/oddity in Clap's parsing. I don't understand how we could parse the input properly and know that the space separated paths were all for the `-c` option.

Checking with `0.20.0` makes me feel like this _was_ a bug as the `-c` option does try and consume _everything_ after it as an additional path. Ex:

`0.20.0`
```shell
vector -c /tmp/vector.toml /tmp/vector2.toml help
2022-04-18T14:12:36.018941Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info"
2022-04-18T14:12:36.019104Z ERROR vector::config::loading: Config file not found in path. path="help"
```

`0.21.0`
```
❯ vector -c /tmp/vector.toml,/tmp/vector2.toml help
vector 0.21.0 (x86_64-apple-darwin c1edb89 2022-04-14)

USAGE:
    vector [OPTIONS] [SUBCOMMAND]
...
```

I personally lean towards not "fixing" this - but documenting it on the upgrade guide

**Comment by atibdialpad** [comment]
makes sense. 
What about vector -c *.toml used to work earlier but not now, I guess the recommendation would to use "vector -C <dir>"

Need to check if this works for multiple directories or do we need -C for each 'dir'

**Comment by spencergilbert** [comment]
> makes sense ! What about vector -c *.toml used to work earlier but not now. I guess the recommendation would be to use "vector -C dir_name"
> 
> Need to check if this works for multiple directories or do we need -C for each 'dir_name'

`-c` with wildcards should work still, the wildcard just needs to be quoted in `0.21.0`

```shell
vector -c "/tmp/*.toml"
2022-04-18T14:19:20.816127Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info,kube=info"
2022-04-18T14:19:20.816350Z  INFO vector::app: Loading configs. paths=["/tmp/vector.toml", "/tmp/vector2.toml"]
```

Without checking the code, it appears to expand into something like `vector -c /tmp/vector.toml /tmp/vector2.toml` which runs into the "this is another command/option", when it's quoted the shell expansion keeps it as part of the `-c` option 👍

**Comment by atibdialpad** [comment]
>  "quoting wildcards seems like best practice"
This is perfect !!!

**Comment by atibdialpad** [comment]
Can you point me to where the shell expansion / parsing code is.  I am seeing an interesting thing. When I run vector as a Linux Service, "-c" works with the quotes like in earlier versions
```
root@eqx-sjc-engine1-staging:~/sample_vector_test# service vector status
● vector.service - Vector
   Loaded: loaded (/lib/systemd/system/vector.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/vector.service.d
           └─vector_systemd_override.conf
   Active: active (running) since Mon 2022-04-18 13:40:07 UTC; 1h 56min ago
     Docs: https://vector.dev
  Process: 2478 ExecStartPre=/usr/bin/vector validate (code=exited, status=0/SUCCESS)
 Main PID: 2519 (vector)
    Tasks: 54
   Memory: 276.3M
   CGroup: /system.slice/vector.service
           └─2519 /usr/bin/vector --config /etc/vector/conf.d/*.toml
```

but when I run on the shell 
```
 /usr/bin/vector --config /etc/vector/conf.d/*.toml
```
fails but 
```
 /usr/bin/vector --config "/etc/vector/conf.d/*.toml"
```
works as you pointed out.

**Comment by spencergilbert** [comment]
> Can you point me to where the shell expansion / parsing code is. I am seeing an interesting thing. When I run vector as a Linux Service, "-c" works **without** the quotes like in earlier versions

Ah - so this is because `systemd` doesn't do wildcard expansion: https://github.com/vectordotdev/vector/discussions/12088

I believe the function that ends up handling globs for us is here: https://github.com/vectordotdev/vector/blob/master/src/config/loading/mod.rs#L70

So, in summary the issue here is that in `0.21` we need the values to be comma separated to parse the CLI flags properly. When quoting the path/s your shell _doesn't_ expand the wildcard and allows Vector to glob properly, when unquoted it does expand the wildcard and ends up passing space separated paths to the cli.
