### ISSUE TITLE
`lookup::lookup_v2::OwnedPath::serialize` not implemented

### ISSUE THREAD

**Issue by kierdavis** [vectordotdev/vector#12256]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Since updating from 0.20.11 to 0.21.0, vector now crashes on startup with:

```
2022-04-18T09:43:47.551748Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info,kube=info"
2022-04-18T09:43:47.551944Z  INFO vector::app: Loading configs. paths=["/etc/vector/vector.toml"]
thread 'main' panicked at 'not yet implemented', /project/lib/lookup/src/lookup_v2/mod.rs:30:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:48:5
   3: <lookup::lookup_v2::OwnedPath as serde::ser::Serialize>::serialize
   4: serde::ser::impls::<impl serde::ser::Serialize for &T>::serialize
   5: serde::ser::impls::<impl serde::ser::Serialize for &T>::serialize
   6: <T as erased_serde::ser::Serialize>::erased_serialize
   7: core::ops::function::FnOnce::call_once
   8: <T as erased_serde::ser::Serialize>::erased_serialize
   9: <erased_serde::ser::erase::Serializer<T> as erased_serde::ser::Serializer>::erased_serialize_some
  10: <T as erased_serde::ser::Serialize>::erased_serialize
  11: <serde_json::ser::Compound<W,F> as serde::ser::SerializeStruct>::serialize_field
  12: core::ops::function::FnOnce::call_once
  13: <T as erased_serde::ser::Serialize>::erased_serialize
  14: core::ops::function::FnOnce::call_once
  15: <T as erased_serde::ser::Serialize>::erased_serialize
  16: vector::config::builder::_::<impl serde::ser::Serialize for vector::config::builder::ConfigBuilderHash>::serialize
  17: vector::config::builder::ConfigBuilder::sha256_hash
  18: vector::config::compiler::compile
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  20: vector::app::Application::prepare_from_opts::{{closure}}
  21: vector::app::Application::prepare_from_opts
  22: vector::app::Application::prepare
  23: vector::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

A `vector.toml` that reproduces this issue is attached.
Notably, if I remove the `encoding.only_fields` property of the http sink, vector starts up without panicking.

### Configuration

```text
[sources.journal]
type = "journald"

[sinks.out]
type = "http"
uri = "https://localhost/"
inputs = ["journal"]
encoding.codec = "ndjson"
# Removing this line makes the panic go away:
encoding.only_fields = ["message", "timestamp", "host", "systemd_unit", "file"]
```

### Version

vector 0.21.0 (x86_64-unknown-linux-gnu c1edb89 2022-04-14)

### References

#11759 introduced this `todo!`, with some discussion about whether it's possible to hit this panic.

**Comment by stephenflorencio** [comment]
hi I have a similar issue that Vector panicking but I just have an errant tar where the initial configuration file is when you use a -C in invoking vector. This is how my directory structure looks like. I just deleted the tar and the error went away 
<img width="716" alt="image" src="https://user-images.githubusercontent.com/100839327/163801966-24b1de23-3cce-41ee-a9e9-4926fc045cf4.png">

**Comment by spencergilbert** [comment]
@pablosichert did this sneak in with your change https://github.com/vectordotdev/vector/pull/11759?

**Comment by bruceg** [comment]
@spencergilbert @pablosichert I confirm that was introduced in #11759 [in this change](https://github.com/vectordotdev/vector/pull/11759/files#diff-29a3703c3fcd47808ed5e20f7ef445df0e98e0ee9507925a122e3d0c8d058a87) which received some discussion during review.

**Comment by pablosichert** [comment]
Thank you for filing this @kierdavis!

Very embarassed that this slipped thorough and didn't follow-up on https://github.com/vectordotdev/vector/pull/11759#discussion_r823259014. That comment has been added after I merged and got lost somewhere in my GitHub notifications 🙇‍♂️

I'm working on a fix right now
