### ISSUE TITLE
Excessive internal logs from "vector top" starting on 0.21.0

### ISSUE THREAD

**Issue by jvperrin** [vectordotdev/vector#12251]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When running `vector top` with 0.21.0 the internal log file gets lots of logs with the `TRACE` log level from various libraries (such as https://github.com/snapview/tokio-tungstenite/blob/614a4b12eb0eaf7ef20629e44cce19c3f05084df/src/compat.rs#L193, shown at the top here):
```
{"host":"92d9850b79c3","log":{"file":"/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-tungstenite-0.15.0/src/compat.rs","line":193,"module_path":"tokio_tungstenite::compat","target":"tokio_tungstenite::compat"},"message":"WouldBlock","metadata":{"kind":"event","level":"TRACE","module_path":null,"target":"log"},"pid":1,"source_type":"internal_logs","timestamp":"2022-04-16T01:35:46.278615043Z"}
{"host":"92d9850b79c3","log":{"file":"/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-tungstenite0.15.0/src/lib.rs","line":223,"module_path":"tokio_tungstenite","target":"tokio_tungstenite"},"message":"/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-tungstenite-0.15.0/src/lib.rs:223 WebSocketStream.with_context","metadata":{"kind":"event","level":"TRACE","module_path":null,"target":"log"},"pid":1,"source_type":"internal_logs","timestamp":"2022-04-16T01:35:46.278623373Z"}
{"host":"92d9850b79c3","log":{"file":"/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-tungstenite-0.15.0/src/compat.rs","line":178,"module_path":"tokio_tungstenite::compat","target":"tokio_tungstenite::compat"},"message":"/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-tungstenite-0.15.0/src/compat.rs:178 Write.flush","metadata":{"kind":"event","level":"TRACE","module_path":null,"target":"log"},"pid":1,"source_type":"internal_logs","timestamp":"2022-04-16T01:35:46.278628664Z"}
```
(for a longer log output I've uploaded to https://gist.github.com/jvperrin/634ddb7afab4e60e88c6529f860b9706, if that's helpful at all)

### Configuration

```text
data_dir = "/var/lib/vector"

[api]
enabled = true
address = "127.0.0.1:8686"

[sources.vector_internal_log]
type = "internal_logs"

[sinks.vector_internal_log_file]
type = "file"
inputs = ["vector_internal_log"]
compression = "none"
path = "/var/log/vector.log"

[sinks.vector_internal_log_file.encoding]
codec = "ndjson"
```

### Version

vector 0.21.0 (x86_64-unknown-linux-gnu c1edb89 2022-04-14)

### References

I think this is likely due to changes to logs and tracing in #11954 since it touches some things like `"tokio=trace"`, but I haven't done much at all with Rust so I might be off on that one.

**Comment by jszwedko** [comment]
Bisected this down to the referenced PR: 1d398321a87dd53eadad68a2f29b4a8de850fc39

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/12300 . This will be part of the forthcoming v0.21.1.
