### ISSUE TITLE
`aws_cloudwatch_logs` sink healthcheck fails with group or stream template

### ISSUE THREAD

**Issue by tomjohn1028** [vectordotdev/vector#12269]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When healthcheck is set to true && templates are used in the _group_name_ or _stream_name_ the initial request to cloudwatch fails because the event data is not there to fill in. The following error occurs

`Apr 19 02:32:59 ip-REDACTED-ec2.internal vector[5229]: 2022-04-19T02:32:59.634892Z ERROR vector::topology::builder: msg="Healthcheck: Failed Reason." error=DescribeLogGroups failed: 1 validation error detected: Value '/my_group/{{ host }}/{{ _SYSTEMD_UNIT }}' at 'logGroupNamePrefix' failed to satisfy constraint: Member must satisfy regular expression pattern: [\.\-_/#A-Za-z0-9]+ component_kind="sink" component_type="aws_cloudwatch_logs" component_id=cloud_watch_logs component_name=cloud_watch_logs`

### Configuration

```text
[sources.journald_logs]
  type = "journald"
  include_units = ["vector"]
  batch_size = 100

[sinks.cloud_watch_logs]
  type = "aws_cloudwatch_logs"
  inputs = ["journald_logs"]
  group_name = "/my_group/{{ host }}/{{ _SYSTEMD_UNIT }}"
  healthcheck = true
  region = "${region}"
  stream_name = "{{ _SYSTEMD_UNIT }}"
  encoding = "json"
  create_missing_group = true
  create_missing_stream = true
```
```


### Version

vector-0.21.0-1

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

**Comment by wtchangdm** [comment]
Yeah we encountered this as well. I think it's expected since it's unlikely for vector to know where to check. So we just disabled health check.

**Comment by spencergilbert** [comment]
I think this is duplicated by: https://github.com/vectordotdev/vector/issues/10787
