### ISSUE TITLE
Docs: administration/monitoring/metrics cuts off in the middle of a sentence

### ISSUE THREAD

**Issue by danielhoherd** [vectordotdev/vector#12264]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

<https://vector.dev/docs/administration/monitoring/#metrics>

> Here’s an example configuration that

Has me like:

![](https://c.tenor.com/I-2ap9ikwycAAAAd/tenor.gif)

### Configuration

```text
N/A
```

### Version

N/A

### Debug Output

```text
N/A
```

### Example Data

N/A

### Additional Context

N/A

### References

N/A

**Comment by bruceg** [comment]
Reference: https://github.com/vectordotdev/vector/blob/788e989a6e32d51a6f497094de01fb26fc0ae222/website/content/en/docs/administration/monitoring.md?plain=1#L90-L92

**Comment by bruceg** [comment]
And more just above it: https://github.com/vectordotdev/vector/blob/788e989a6e32d51a6f497094de01fb26fc0ae222/website/content/en/docs/administration/monitoring.md?plain=1#L85-L86

**Comment by spencergilbert** [comment]
Thanks for the report @danielhoherd - not sure where the rest of that sentence went 😅
