### ISSUE TITLE
Route transform test not working since 0.21.0

### ISSUE THREAD

**Issue by bakito** [vectordotdev/vector#12272]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Unit Tests for route transform fail since version 0.21.0.
Until 0.20.1 the same tests were running.

It seems routing is broken in unit tests. 

The same routing works flawless in productive mode. 
So it seems there is 'only' something wrong in the test framework.

### Configuration

```text
transforms:
  route_to_target:
    type: route
    inputs:
      - container_logs
    route:
      foo: |
        (.kubernetes.pod_labels."logging.target" == "foo" )
      bar: |
        (.kubernetes.pod_labels."logging.target" == "bar" )

tests:

  - name: route_to_target - no match
    inputs:
      - type: log
        insert_at: route_to_target
        log_fields:
          kubernetes.pod_labels.logging\.target: "xxx"
    no_outputs_from:
      - route_to_target.foo
      - route_to_target.bar

  - name: route_to_target - match foo
    inputs:
      - type: log
        insert_at: route_to_target
        log_fields:
          kubernetes.pod_labels.logging\.target: "foo"
    outputs:
      - extract_from: route_to_target.foo
        conditions:
          - type: vrl
            source: |-
              true
    no_outputs_from:
      - route_to_target.bar

  - name: route_to_target - match bar
    inputs:
      - type: log
        insert_at: route_to_target
        log_fields:
          kubernetes.pod_labels.logging\.target: "bar"
    outputs:
      - extract_from: route_to_target.bar
        conditions:
          - type: vrl
            source: |-
              true
    no_outputs_from:
      - route_to_target.foo
```

### Version

vector 0.21.0

### Debug Output

```text
vector test --config-yaml ./tmp/route-test.yaml
Running tests
test route_to_target - no match ... passed
test route_to_target - match foo ... failed
test route_to_target - match bar ... failed

failures:

test route_to_target - match foo:

checks for transforms ["route_to_target.foo"] failed: no events received. Topology may be disconnected or transform is missing inputs.


test route_to_target - match bar:

checks for transforms ["route_to_target.bar"] failed: no events received. Topology may be disconnected or transform is missing inputs.
```

### Example Data

see configuration

### References

Might be related with #11875

**Comment by jszwedko** [comment]
Bisected this down to b6edb0203f684f67f8934da948cdf2bdd78d5236

**Comment by fuchsnj** [comment]
@bakito, The upgrade to version 0.21.0 contained [breaking changes](https://vector.dev/highlights/2022-03-22-0-21-0-upgrade-guide/#path-syntax-changes) with the path syntax.

The unit tests are still using the old paths (`kubernetes.pod_labels.logging\.target`). Just switch those to `kubernetes.pod_labels."logging.target"` and it should start working again.

Due to the way this is implemented, you may not receive an error if you use an invalid path. We plan on improving this in the future. For now, please make sure to use the new syntax.

**Comment by bakito** [comment]
@fuchsnj Thank you very much for the hint, I missed that. 
All my tests work fine after applying the new path syntax
