### ISSUE TITLE
`aws_cloudwatch_logs` sink with endpoint only, fails healthcheck

### ISSUE THREAD

**Issue by Gundersanne** [vectordotdev/vector#12270]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Vector 0.20.* works without having to specify `region`, just having the `endpoint`. This broke in vector 0.21, where the healthcheck now explicitly requires `region`.

Relevant error:
```
ERROR vector::topology::builder: msg="Healthcheck: Failed Reason." error=DescribeLogGroups
failed: failed to construct request: NoRegion component_kind="sink"
component_type="aws_cloudwatch_logs" component_id=out component_name=out
```

### Configuration

```text
[sources.journald]
type = "journald"
exclude_units = ["vector.service"]

[sinks.out]
type = "aws_cloudwatch_logs"
inputs = [ "journald" ]
endpoint = "https://logs.us-east-1.amazonaws.com"
group_name = "some_log_group"
stream_name = "syslog_$HOST"
encoding.codec = "json"
```

### Version

vector 0.21.0 (x86_64-unknown-linux-gnu c1edb89 2022-04-14)

**Comment by Gundersanne** [comment]
https://master.vector.dev/highlights/2022-03-22-0-21-0-upgrade-guide/#aws-sdk-migration should've read this, sorry for the noise.

**Comment by jszwedko** [comment]
No worries @Gundersanne . We meant to actually make `region` a required config field so that you get a better error message rather than failing the healthcheck later. This was fixed in https://github.com/vectordotdev/vector/pull/12313.
