### ISSUE TITLE
chore(buffers): clean up extant usage of `leveldb` feature flag

### ISSUE THREAD

**Issue by tobz** [vectordotdev/vector#12289]
As part of working on #12273, I discovered there were some spots I missed when originally removing the `leveldb` feature flag that forced us to always build the LevelDB-based disk buffer implementation.

This primarily affects tests now, where code is feature flagged behind `leveldb`, and potentially other flags, and so it is no longer run during normal test execution, either locally or in CI.

We should go through and remove all such instances of the `leveldb` feature flag gating some piece of code.  As well, we should ensure it's no longer set directly or specified in any sort of build configuration as it no longer functions as an actual feature flag.

**Comment by jszwedko** [comment]
Closing this since we intend to drop leveldb shortly (including the flag).
