### ISSUE TITLE
`vector config --include-defaults` duplicates array fields

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#12329]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Running `vector --config ... config --include-defaults` duplicates elements in array fields.

### Configuration

```text
[sources.source0]
type = "stdin"

[sinks.sink0]
inputs = ["source0"]
type = "console"

[sinks.sink0.encoding]
codec = "json"
only_fields = ["foo"]
```

### Version

vector 0.21.0 (aarch64-apple-darwin)

### Debug Output

```text
{
  "data_dir": "/var/lib/vector/",
  "api": {
    "enabled": false,
    "address": "127.0.0.1:8686",
    "playground": true
  },
  "schema": {
    "enabled": false
  },
  "enterprise": null,
  "healthchecks": {
    "enabled": true,
    "require_healthy": false
  },
  "enrichment_tables": {},
  "sources": {
    "source0": {
      "type": "stdin",
      "max_length": 102400,
      "host_key": null,
      "framing": {
        "method": "newline_delimited"
      },
      "decoding": {
        "codec": "bytes"
      }
    }
  },
  "sinks": {
    "sink0": {
      "inputs": [
        "source0",
        "source0"
      ],
      "healthcheck_uri": null,
      "healthcheck": {
        "enabled": true,
        "uri": null
      },
      "buffer": {
        "type": "memory",
        "max_events": 500,
        "when_full": "block"
      },
      "type": "console",
      "target": "stdout",
      "encoding": {
        "codec": "json",
        "only_fields": [
          "foo",
          "foo"
        ]
      }
    }
  },
  "transforms": {},
  "tests": [],
  "provider": null
}
```

**Comment by jszwedko** [comment]
This appears to be due to the way the builder defaults are merged around here: https://github.com/vectordotdev/vector/blob/efb58498a90e70d6c3deebbecee28c6b1be2190a/src/config/cmd.rs#L19-L36

For array fields, if a user provides a value, it should take the place of any default.

**Comment by 001wwang** [comment]
Just to note, with the example configuration above and running on `0.21.0`

```
vector -c {{config here}} config --include-defaults 
```

I get the following error (documented in https://github.com/vectordotdev/vector/issues/12256)

```
thread 'main' panicked at 'not yet implemented', /Users/runner/work/vector/vector/lib/lookup/src/lookup_v2/mod.rs:30:9
```

Not sure if I've missed something. The following configuration also works to reproduce this issue

```
[sources.source0]
type = "stdin"

[sources.source1]
type = "stdin"

[sinks.sink0]
type = "blackhole"
inputs = ["*"]
```

**Comment by jszwedko** [comment]
@001wwang ah, apologies, I was actually using #12256 to test, which fixes that panic. I neglected to mention that above.
