### ISSUE TITLE
Sinks that do not support `tls.enabled` still document its presence

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#12343]
The standard documentation for any sink that accepts TLS options includes a stanza for the `tls.enabled` option. However, many of these sinks do not actually make use of the option. As such, that option should only be included conditionally into the documentation.

For example, [the `splunk_hec` sink documentation includes the `enabled` option](https://vector.dev/docs/reference/configuration/sinks/splunk_hec_logs/#tls.enabled), but that only uses the `TlsOptions` in its configuration source code, which does not include the option.

**Comment by jszwedko** [comment]
@bruceg should any component be using `TlsOptions` directly? I'm wondering if all of them should be updated to use `TlsSettings`.

**Comment by bruceg** [comment]
Did you mean `TlsConfig` instead of `TlsSettings` (maybe we should rename them to clarify)? If so, I'm doubtful. For example, all the HTTP-based components should be using the `http:` vs `https:` to determine if TLS is enabled, and so only need `TlsOptions` (which does not have the `enabled` field).

**Comment by jszwedko** [comment]
> Did you mean `TlsConfig` instead of `TlsSettings` (maybe we should rename them to clarify)? If so, I'm doubtful. For example, all the HTTP-based components should be using the `http:` vs `https:` to determine if TLS is enabled, and so only need `TlsOptions` (which does not have the `enabled` field).

Ah, gotcha, yeah, I see. Any components where the use of TLS is controlled by the scheme in the endpoint wouldn't have this extra field.

**Comment by gsalisbury** [comment]
Ran into this issue when upgrading from 0.21.2 to 0.22.3 with the HTTP sink configured with tls.enabled set to true.
