### ISSUE TITLE
nats: cannot connect to ipv6 host

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#12374]
### Discussed in https://github.com/vectordotdev/vector/discussions/12373

<div type='discussions-op-text'>

<sup>Originally posted by **jbergstroem** April 22, 2022</sup>
Hello, after the auth fixes in `0.21.1` I'm attempting to connect to a ipv6 host, but vector doesn't seem to like my config. Something like:

```toml
[sources.my_nats]
  type = "nats"
  url = "nats://[::1]:4222"
  connection_name = "logs"
```

Gives:
```console
2022-04-22T18:56:08.769003Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info,kube=info"
2022-04-22T18:56:08.769115Z  INFO vector::app: Loading configs. paths=["/etc/vector/vector.toml"]
2022-04-22T18:54:44.030456Z ERROR vector::topology: Configuration error. error=Source "my_nats": NATS Connect Error: failed to lookup address information: Name does not resolve
```

I've tried variations of the host but are running out of options. Any input much appreciated!</div>

**Comment by jszwedko** [comment]
Blocked by https://github.com/nats-io/nats.rs/issues/322 fixed by https://github.com/nats-io/nats.rs/pull/386.

**Comment by jszwedko** [comment]
cc/ @jbergstroem

**Comment by jszwedko** [comment]
@jbergstroem I think using a domain name that resolves to an IPv6 address would work, if that is a feasible workaround.

**Comment by jbergstroem** [comment]
> @jbergstroem I think using a domain name that resolves to an IPv6 address would work, if that is a feasible workaround.

I'm unfortunately not in control of dns resolution. Can hack around `/etc/hosts` by mounting it via Docker I guess. Thanks for providing solutions and fixing the bug!

**Comment by wjordan** [comment]
For anyone following along, a `nats.rs` version bump (#13494) landed in Vector a couple weeks ago so this should be fixed in the next release. I can confirm it already works in the nightly Docker-image builds.

**Comment by jszwedko** [comment]
Thanks for verifying @wjordan !
