### ISSUE TITLE
Failed Healthcheck does not give reason of failure

### ISSUE THREAD

**Issue by JohannesM24** [vectordotdev/vector#12398]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I think I have some kind of network issue using the datadogs log sink but the error message is not helping me to debug it. Similar issue https://github.com/vectordotdev/vector/issues/8260

**Expected behaviour**

Log output should contain useful information about why healthcheck failed

**Actual behaviour**

`2022-04-25T13:38:39.610572Z ERROR vector::topology::builder: msg="Healthcheck: timeout." component_kind="sink" component_type="datadog_logs" component_id=datadog_logs component_name=datadog_logs`

### Configuration

```text
[sinks.datadog_logs]
type = "datadog_logs"
```

### Version

vector 0.20.0 (x86_64-pc-windows-msvc 2a706a3 2022-02-10)

### References

https://github.com/vectordotdev/vector/issues/8260

**Comment by jszwedko** [comment]
Hi @JohannesM24 !

In this case I think the output _is_ giving the failure reason: the request timed out. I'll close this, but let me know if you think that log is still unclear.
