### ISSUE TITLE
`vector vrl` forgets a variable

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#12400]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I was attempting to debug some VRL in `vector vrl` and discovered that `vector vrl` seems to forget a variable when I do:

```
$ t = "2022-04-21T15:22:23.754+0000"
"2022-04-21T15:22:23.754+0000"

$ parse_timestamp!(t, "%Y-%m-%d %H:%M:%S%.3f%z")
function call error for "parse_timestamp" at (0:46): Invalid timestamp "2022-04-21T15:22:23.754+0000": input contains invalid characters

$ t

error[E701]: call to undefined variable
  ┌─ :1:1
  │
1 │ t
  │ ^
  │ │
  │ undefined variable
  │ did you mean "true"?
  │
  = see language documentation at https://vrl.dev
```

### Version

vector 0.21.1

**Comment by hhromic** [comment]
Ha! I also discovered this issue on Friday, ironically also while playing with `parse_timestamp()`, but in the middle of writing up the issue reporting this I thought it was already solved by #12210 and scraped it out. I guess next time I'll not give up! :D

Anyway, great that it was solved quickly! 💯
