### ISSUE TITLE
Support template syntax on ClickHouse's table name.

### ISSUE THREAD

**Issue by d2gr** [vectordotdev/vector#12408]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Proposal

It would be nice to have [this](https://vector.dev/docs/reference/configuration/template-syntax/) in ClickHouse's table name.

### Version

vector 0.20.1 (x86_64-unknown-linux-gnu 38b806e 2022-04-07)

**Comment by jszwedko** [comment]
Thanks for opening this @d2gr ! We actually have an issue for it already: https://github.com/vectordotdev/vector/issues/7912 . I'll close this one, but feel free to follow along there.
