### ISSUE TITLE
Swap `parse_groks` key/value filter with new lookup code

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#12402]
Per https://github.com/vectordotdev/vector/issues/10144#issuecomment-1103268164

> https://github.com/vectordotdev/vector/issues/7070, specifically we spend a lot time [right here](https://github.com/vectordotdev/vector/blob/2fcf5686545192dc51456867f92bb6ca7b883560/lib/datadog/grok/src/filters/keyvalue.rs#L146-L148). Lookup parsing contributes roughly 7% of execution time.

I talked with @fuchsnj today and he thinks we might be able to replace _just_ this lookup (rather than all of VRL) after doing the preliminary work of making the lookups compatible. We could expand out usage after that.

**Comment by fuchsnj** [comment]
I looked through the code a bit, and it seems reasonable to swap out this specific usage before putting this in all of VRL.
The full list of changes for the new lookup code are here: #7070 

There are 2 things that the new lookup code doesn't support yet that will _technically_ be breaking changes,
but these are things that are probably unlikely to be used in this context so adding support might be able to be skipped for now.
- Supporting negative array indices
- Coalescing support (which we haven't decided if we are keeping in VRL yet)

After that, a new `target_insert` function needs to be added which supports the new lookup code. There might be a small amount of error handling changes necessary to make this behave similar to how it does now. Once this is done, the rest of the work to get it working is trivial.

**Comment by fuchsnj** [comment]
After thinking about this more, I don't think it makes sense to apply Vector's path syntax in this situation. The key comes directly from the log, and you aren't able to for example escape characters. We should probably just treat the entire key as a single segment, which means the new lookup code isn't required for this change.
