### ISSUE TITLE
Allow extra_namespace_label_selector on kubernetes_logs source

### ISSUE THREAD

**Issue by anapsix** [vectordotdev/vector#12432]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

If would be awesome for Vector to natively support `extra_namespace_label_selector` in `kubernetes_logs` source, similar to how `extra_label_selector` works, but instead of targeting Pod labels, it would target Pod's Namespace labels.
The `extra_namespace_label_selector` would specify an extra Namespace label selector, in addition to the built-in `vector.dev/exclude!=true`.

With `extra_namespace_label_selector`, one could use it to set custom opt-in / opt-out labels on the namespace to enable / disable log collection from Pods running in appropriately labeled Namespace.
For example:
- opt-in: `extra_namespace_label_selector: collect_logs=true`
- out-out:  `extra_namespace_label_selector: do_not_collect_logs!=true`

### Attempted Solutions

The approximation of the described functionality can be achieved with transformation
- opt-out
  ```
  kube_namespace_value = to_string!(.kubernetes.pod_namespace)
  exclude_ns_label_value = to_string!(.kubernetes.namespace_labels."vector.dev/exclude")
  if (exclude_ns_label_value == "true") {
    log(kube_namespace_value + " namespace is explicitly excluded", level: "info", rate_limit_secs: 60)
    abort
  }
  ```
- out-in
  ```
  kube_namespace_value = to_string!(.kubernetes.pod_namespace)
  include_ns_label_value = to_string!(.kubernetes.namespace_labels."vector.dev/include")
  if (include_ns_label_value != "true") {
    log(kube_namespace_value + " namespace is not included", level: "info", rate_limit_secs: 60)
    abort
  }
  ```

### Proposal

The `extra_namespace_label_selector` in `kubernetes_logs` source would work similarly to `extra_label_selector`, but instead of targeting Pod labels, it would target Pod's Namespace labels: it would specify an extra Namespace label selector, in addition to the built-in `vector.dev/exclude!=true`.

### References

As opposed to the #4214 proposal to support Namespace annotation based selector, Namespace label based extra selector seems simpler.

### Version

vector 0.21.1 (x86_64-unknown-linux-gnu 18787c0 2022-04-22)

**Comment by anapsix** [comment]
I took a naive pass at it in #12438 🤷‍♂️ - hoping to test it locally as soon as my `DOCKER_DEFAULT_PLATFORM=linux/amd64 make environment-prepare` completes 😬

**Comment by spencergilbert** [comment]
> I took a naive pass at it in #12438 🤷‍♂️ - hoping to test it locally as soon as my `DOCKER_DEFAULT_PLATFORM=linux/amd64 make environment-prepare` completes 😬

Thanks! I'll look to get that reviewed soon, appreciate the contribution!
