### ISSUE TITLE
Platform-specific components and configuration

### ISSUE THREAD

**Issue by a-rodin** [vectordotdev/vector#1245]
Some components are supported on a limited number of operating systems. In particular, `journald` is supported only in Linux.

This prompts a question about the correct way to handle configs containing such components on unsupported platforms.

## Current approach

Currently configs with `journald` source would be parsed without errors on macOS and Windows, but it would not produce events because there is no `libsystemd.so.0` library on these platforms.

In particular, it makes it possible to ensure that a config is valid, for example, on macOS, and then deploy to Linux.

## (Simple to implement) alternative approach

An alternative approach would be to completely disable this component on unsupported platforms with `#[cfg(...)]` flags. This would make configs with unsupported components stop working at config parsing step, with an error indicating that this components is unknown to Vector.

## Another approach

Another approach would be to parse and validate configs for unsupported components, but show warning at start up about a component being unsupported and thus disabled on the current platform. I think this is the most correct way to deal with this problem.

**Comment by LucioFranco** [comment]
+1 on the warning, I'd prefer to avoid cfg's everywhere.

**Comment by jszwedko** [comment]
Closing since we implemented this through cfg flags.
