### ISSUE TITLE
`kubernetes_logs` source leaks watcher tasks during reload

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#12472]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Spotted by https://github.com/vectordotdev/vector/discussions/12386

During reload, the source will shutdown, but there doesn't appear to be anything shutting down these spawned tokio tasks:

https://github.com/vectordotdev/vector/blob/45166b0d1d24d92e95123625518b2337053ddfbd/src/sources/kubernetes_logs/mod.rs#L310-L331

These will continue to live and potentially put additional load on the API server.

### Version

vector v0.21.1

**Comment by nabokihms** [comment]
I would like to work on this one. Is this issue available to pick?

**Comment by jszwedko** [comment]
Hey @nabokihms !

Yes, we'd happily accept a PR for it. We hadn't scheduled this one yet.
