### ISSUE TITLE
Branching strategy for releases

### ISSUE THREAD

**Issue by a-rodin** [vectordotdev/vector#1252]
We might need to do patch releases before next "normal" releases. In particular, it might be necessary to timely upgrade some dependencies, such as OpenSSL, before the next release is ready.

I propose the following process for this:

* When we are ready to tag new `0.x.0` release from `master`, we create a special branch, for example called `v0.x` and tag version `0.x.0`.
* All new changes by default go to `master`.
* Then, if some of the changes need to be backported to current minor version, the corresponding commits are cherry-picked from master to `v0.x` branch.
* After these commits are cherry-picked, a new patch release is tagged in `v0.x` branch.

It would play well with our approach to automated version check (https://github.com/timberio/vector/issues/1083) and it would allow us to use this branch to maintain a version of docs for the latest minor (`v0.x`) release. So if we decide to implement https://github.com/timberio/vector/issues/1250, it would be possible to just use version from `Cargo.toml` for docs generation instead of relying on Git tags.

**Comment by binarylogic** [comment]
I agree, this makes sense to me. For each release, I create a dedicated branch for that version. This was primarily done for documentation reasons since Gitbook required branches for previous documentation versions, but it could also be used for this.

**Comment by lukesteensen** [comment]
Yep, I think this is a good way to do it.

**Comment by jszwedko** [comment]
Closing as we maintain one release branch per minor version.
