### ISSUE TITLE
Dedicated syntax to fetch event metadata in VRL

### ISSUE THREAD

**Issue by JeanMertz** [vectordotdev/vector#12557]
We currently have three functions to access event metadata in VRL:

- `get_metadata_field`
- `set_metadata_field`
- `remove_metadata_field`

As we start using metadata more (see f.e. #12351), we should invest in dedicated syntax to make metadata access as seamless as regular event field access.

Given path access works as such:

```coffee
.foo.bar[2]
```

It's important to note how this syntax is constructed:

- `.` The first dot indicates "access the external event from within VRL
- `foo.bar[2]` is the path used to query the external event (in this case, field `foo`, then nested within field `bar`, and then the third index within the array)

This syntax works the same for other query types. All of these are valid:

```coffee
# variable query (note the missing `.` at the start)
foo.bar[2]

# static object access
{ "foo": { "bar": [0, 1, 2] } }.foo.bar[2]

# function call return-type access
parse_json!(.message).foo.bar[2]
```

The event metadata syntax should work similar to above queries, except that we'd choose a different prefix to indicate metadata access.

For example:

```coffee
&foo.bar[2]
```

Where `&` sets the query target to "metadata".

Once this syntax is in place, all other existing VRL features and functions will work as expected:

```coffee
if exists(&foo) { ... }
del(&foo.bar)
&foo = "foo"
```

**Comment by spencergilbert** [comment]
> . The first dot indicates "access the external event from within VRL

Can you explain what you mean by this? What makes the event "external"? I've never thought about it in this way, so I'm curious what you're reasoning is.

👍 the `&` though, I love me some ampersands.

**Comment by JeanMertz** [comment]
"external" is the term we use _internally_ (heh) to reference "data that does not originate from within the program". In this case, all the event data is external, and it's accessed (in a technical sense) through the `Target` trait.

**Comment by spencergilbert** [comment]
> "external" is the term we use _internally_ (heh) to reference "data that does not originate from within the program". In this case, all the event data is external, and it's accessed (in a technical sense) through the `Target` trait.

Makes sense, thanks!
