### ISSUE TITLE
GCP Bucket Sink Rate Limiting Itself via Duplicate Requests

### ISSUE THREAD

**Issue by JakeCooper** [vectordotdev/vector#12578]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

With the GCP log sink, we're noticing Vector sending multiple requests to the same bucket, which results in getting rate limited

<img width="863" alt="CleanShot 2022-05-03 at 23 48 21@2x" src="https://user-images.githubusercontent.com/5499880/166634276-0b969e34-2577-4f65-b40b-b6f999580e71.png">

### Configuration

```text
data_dir = "${LOGGER_VECTOR_PATH}"

[api]
enabled = true
playground = false

[sources.in_vector]
type = "vector"
version = "2"
address = "0.0.0.0:5143"

[sinks.out_file]
type = "file"
inputs = ["in_vector"]
compression = "none"
encoding = "ndjson"
path = "${LOGGER_VECTOR_PATH}/out_file/logs/%F_%H/{{ appname }}.log"

[sinks.out_gcp]
type = "gcp_cloud_storage"
inputs = ["in_vector"]
bucket = "${LOGGER_BUCKET_NAME:-railway-develop-logs}"
key_prefix = "logs/{{ appname }}/"
compression = "none"
buffer.type = "disk"
buffer.max_size = 50_000_000_000 # 50 GB
batch.timeout_secs = 600 # 10 Minutes
batch.max_bytes = 1_000_000 # 1 MB
filename_append_uuid = false
encoding = "ndjson"
# Note: Time in `filename_time_format` uses time-of-last-log unlike `key_prefix` which uses time-of-first-log
filename_time_format = "%F/%T"

# Internal metrics for our reporting to DataDog

[sources.in_internal]
type = "internal_metrics"
namespace = "vector"
scrape_interval_secs = 60

[sinks.out_datadog]
type = "datadog_metrics"
inputs = ["in_internal"]
api_key = "${DD_API_KEY}"

# Forward logs to local logger for inspection
#[sinks.out_inspector]
#type = "http"
#inputs = ["in_vector"]
#uri = "http://127.0.0.1:8087/inspect"
#compression = "none"
#encoding = "ndjson"
#request.headers = { "x-access-token" = "${RAILWAY_ACCESS_TOKEN}" }
#batch.timeout_secs = 10
#buffer.when_full = "drop_newest"
```

### Version

0.21.0

**Comment by jszwedko** [comment]
Hi @JakeCooper !

I think this is likely to be because Vector is making concurrent requests that are using the same object key name. By default, Vector will build and send batches concurrently. In this case the configuration of:

```
key_prefix = "logs/{{ appname }}/"
filename_time_format = "%F/%T"
```

could result in conflicts if two batches happen to be built during the same second. Normally `filename_append_uuid` avoids this issue by appending a UUID to each file name, but here you have that option disabled.

To test this theory, you could try enabling `filename_append_uuid` to see if the errors go away.

**Comment by jszwedko** [comment]
Ah, actually, thinking about this more, I think I'm wrong. Vector should be partitioning the batches along the key and so will only have one batch in-flight for a given key. I do see here that it seems like that might not be behaving properly since it does seem like you have multiple requests trying to write to the same key. We'll dig in and try to reproduce.

**Comment by JakeCooper** [comment]
>  Vector should be partitioning the batches along the key and so will only have one batch in-flight for a given key.

This was my impression as well, but please let me know if it's incorrect! The filename_append_uuid stuff is probably worth doing as well because of how GCP buckets shard, B U T, I think it's also a separate issue

Thanks!

**Comment by JakeCooper** [comment]
Any update here?

**Comment by jszwedko** [comment]
Hi @JakeCooper !

I am curious if adding `filename_append_uuid` fixes it for you. That would help narrow down where the issue is.

Otherwise, I think you've given enough context to reproduce, thank you! This has been prioritized in our backlog.

**Comment by zsherman** [comment]
@JakeCooper just a bump on this—did you get a chance to try @jszwedko's proposal?

**Comment by bruceg** [comment]
@JakeCooper could you copy in the text of the logs image you pasted above? There are some details missing in the image (notably the timestamps) that would be most informative.

**Comment by bruceg** [comment]
Second thought: Is this configuration sending more than 1MB/sec to that destination? If so, the posted configuration will end up overwriting each object multiple times such, that the result will be only the _last_ 1MB worth of data for that second. This is likely _not_ what you actually want to happen, even if the rate limiting per-object can be resolved somehow.

To fix this, you would either need to increase the batch size to be much larger than one second worth of data, or remove it entirely, or to add a UUID to each filename with the `filename_append_uuid` option.

**Comment by JakeCooper** [comment]
Hey @bruceg. I'll try that this evening.

We seem to be running into this issue once again. Is there any way to, while it's occuring, get observability into whether the max batch size is the culprit?

I'd add teh filename_append_uuid option but it will change the way we query logs from our frontend so it will require some additional changes.

I'll attempt to up the batch size this evening and report back

**Comment by jszwedko** [comment]
Hi @JakeCooper !

Could you share the full logs, including the timestamps? I think that would help us determine if what we suspect, that it is sending more than 1 MB/s to the sink, is what is happening.

**Comment by jszwedko** [comment]
Hey @JakeCooper !

Just wanted to bump this once more. If you could share the full logs including timestamps that should help make it clearer what is going on here.
