### ISSUE TITLE
`datadog_agent` source, support /api/v2/series (protobuf encoded series)

### ISSUE THREAD

**Issue by prognant** [vectordotdev/vector#12610]
The datadog agent can ship metrics using protobuf on the [/api/v2/series path ](https://cs.github.com/vectordotdev/vector/blob/e1fceb79808998e0b7e6889a706d39fc4b8b6b76/src/sources/datadog/agent/metrics.rs#L141), this is currently non supported (vector only support json-encoded metrics series)

The protobuf schema has been introduced by this [commit](https://github.com/DataDog/agent-payload/commit/3120b8a7875c0bde6463255bf45ce0b8fa3ac003).

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/13028
