### ISSUE TITLE
`Kind::is_exact()` is incorrect

### ISSUE THREAD

**Issue by fuchsnj** [vectordotdev/vector#12621]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The `Kind::is_exact()` function is supposed to return `true` if exactly one type is set. It currently returns true if at _least_ one type is set.
https://github.com/vectordotdev/vector/blob/2e529df6d09b07c2f85762515f0d8fc7fe814ea1/lib/value/src/kind/comparison.rs#L182-L195

### Version

master / 2e529df6d09b07c2f85762515f0d8fc7fe814ea1

**Comment by JeanMertz** [comment]
I am not convinced that's the case. `is_bytes()` (etc) only return `true` if _only_ `bytes` is set. This differs from `contains_bytes()`.

**Comment by JeanMertz** [comment]
There are unit tests that validate the correct behaviour.

**Comment by fuchsnj** [comment]
Yep, you are right. Sorry for the noise.
