### ISSUE TITLE
HTTP Source. Body parameters rewrite headers and system variables

### ISSUE THREAD

**Issue by anufrien** [vectordotdev/vector#12636]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

In HTTP source by default BODY parameters rewrite headers data and system variables.

I consider this a bug. Knowing the structure or guessing about it, you can compromise the data.

I propose to introduce an additional parameter that will allow you to take out POST data and request parameters in a separate key, for example, in a "message"

Sample output after changes
```json
{
    "User-Agent": "curl/7.79.1",
    "message":
    {
        "any": "test"
    },
    "path": "/",
    "source_type": "http",
    "timestamp": "2022-05-06T13:50:08.411250549Z"
}
```

### Configuration

```text
[sources.http_logs]
type = "http"
address = "0.0.0.0:80"
encoding = "json"
headers = [ "User-Agent"]
path = "/"
strict_path = true

[sinks.print]
type = "console"
inputs = ["http_logs"]
    [sinks.print.encoding]
    codec = "json"
```

### Version

vector 0.21.0 (x86_64-unknown-linux-musl c1edb89 2022-04-14)

### Debug Output

```text
{"User-Agent":"curl/7.79.1","any":"test","path":"/","source_type":"http","timestamp":"2022-05-06T13:50:08.411250549Z"}

{"User-Agent":"test","any":"test","path":"/","source_type":"http","timestamp":"test"}
```

### Example Data

$ curl -i --header "Content-Type: application/json" \
  --request POST \
  --data '{"any": "test"}' \
  http://localhost:80/
HTTP/1.1 200 OK
content-length: 0
date: Fri, 06 May 2022 13:50:08 GMT

$ curl -i --header "Content-Type: application/json" \
  --request POST \
  --data '{"User-Agent": "test", "timestamp": "test", "any": "test"}' \
  http://localhost:80/
HTTP/1.1 200 OK
content-length: 0
date: Fri, 06 May 2022 13:49:23 GMT

**Comment by jszwedko** [comment]
Hi @anufrien !

This is actually a problem we are working on addressing now. I realized we didn't have an issue for it yet though, so I created https://github.com/vectordotdev/vector/issues/12647. I'll close this in-lieu of that one as it is more general (applies to all sources) but please feel free to leave any additional thoughts there. We have an RFC for an approach in #12351. Your thoughts would be welcome there as well 😄
