### ISSUE TITLE
GCP pub/sub issues

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#12648]
Tracking epic for current GCP PubSub issues that we are addressing.

- [x] https://github.com/vectordotdev/vector/issues/10828
- [x] https://github.com/vectordotdev/vector/issues/12624
- [x] https://github.com/vectordotdev/vector/issues/12608
- [x] https://github.com/vectordotdev/vector/issues/12590
- [x] https://github.com/vectordotdev/vector/issues/12625
- [x] #12660
- [x] #12757

**Comment by bruceg** [comment]
All issues are resolved, closing.
