### ISSUE TITLE
Switch soak.yml over to the native "cancel previous jobs" functionality of GHA

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#12672]
> This also switches test.yml over to the native "cancel previous jobs" functionality of GHA in an effort to see if we can avoid using the workflow action, as it should be faster to avoid having to run it as a full-fledged step which requires a runner instance, and so on.

If this works out I'd like to switch the soaks over as well.

_Originally posted by @blt in https://github.com/vectordotdev/vector/issues/12669#issuecomment-1121640402_

**Comment by jszwedko** [comment]
Closing since we aren't using this workflow anymore.
