### ISSUE TITLE
Sinks have a tls.crt_file configuration option

### ISSUE THREAD

**Issue by StephenWakely** [vectordotdev/vector#12702]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

A large number of sinks (examples - datadog_logs, clickhouse, loki) allow you to set `tls.crt_file`, `tls.key_file` and `tls.key_pass`. To my knowledge, these settings will only be useful for the TLS server, and have no use for the sinks that are acting as clients. 

I suspect this could be a relic of both clients and servers sharing the same `TlsConfig` struct. We should probably separate this out into `TlsClientConfig` and `TlsServerConfig` settings.

### Version

v0.21

**Comment by hhromic** [comment]
I thought these options are used for Mutual TLS in Vector?
In Mutual TLS setups, _both_ the client and server must prove they are who they say they are. For this you usuallly have a cert/key pair for the client and another cert/key for the server that both verify independently on each side.

In the case of sources/sinks that _originate_ connections, I understood the TLS options are for providing a client cert/key pair. For the case of sources/sinks that _listen_ to connections, the TLS options are for providing a server cert/key pair.

Maybe is not a bad idea to name them as "TLS client config" and "TLS server config" for clarity. These configs are normally the same except that the "purpose" of each config is to validate a server or a client respectively.

**Comment by jszwedko** [comment]
Yeah, @hhromic is correct. The options take affect for both clients and servers. For clients, the `crt_file` is provided as the authenticating client certificate for mutual TLS (which requires the `key_file` and potentially the `key_pass`).
