### ISSUE TITLE
Overwriting non-object data in VRL should not be easy

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#12701]
There is a footgun with VRL that allows users to accidentally overwrite non-object data when treating that data like an object. For example, given the following event:

```
.body = "body value"
```

A user can unknowingly overwrite this data by attempting to add attributes to it:

```
.body.key = "key value"
```

In the above script the original `body value` is overwritten. IMO, VRL should error since `.body` is a string, not an object. The user should be required to explicitly turn `.body` into an object before adding keys to it.

**Comment by JeanMertz** [comment]
The biggest hurdle I can see is type information.

If we don't know the type of `.body`, we can't know if it's an object. Or, what if we do know it's either an object or a string, should we allow it then?

This can make usage extremely painful if you can only add to fields that are _known_ to be _exactly_ an object and nothing else.

**Comment by binarylogic** [comment]
I agree, what you describe is not a good UX. Wouldn't the follow through with the schemas support resolve this? If so, let's just wait for all source to get schema information and only enforce this rule when the type is known.

**Comment by JeanMertz** [comment]
We could already implement this, but only if we know the type isn't "any", and isn't an object, if that's the case, reject overwriting the field.
