### ISSUE TITLE
Misspelling a field name in the Kafka sink sasl section produces an obscure error message

### ISSUE THREAD

**Issue by StephenWakely** [vectordotdev/vector#12748]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Given the provided configuration, note that the configuration option for `sasl.mechanism` has been misspelled as `machanism`. This produces the error message:

```
creating kafka producer failed: Client creation error: Invalid sasl.kerberos.kinit.cmd value: Property not available: "sasl.kerberos.keytab"
```

Which is not at all indicative of what the actual problem is. It would be useful to produce a better error message to indicate what needs fixing.

### Configuration

```text
sinks:
  kafka:
    type: kafka
    inputs:
      - vector_gw
    bootstrap_servers: "..."
    topic: "GW-logs"
    sasl:
      enabled: true
      machanism: "SCRAM-SHA-512"
      username: "test"
      password: "test"
    encoding:
      codec: json
```

### Version

v0.21

**Comment by zamazan4ik** [comment]
@neuronull @StephenWakely the issue is not actual anymore - now all fields are spelled properly.
