### ISSUE TITLE
Use Nonroot containers

### ISSUE THREAD

**Issue by jtcarnes** [vectordotdev/vector#12796]
### A note for the community

I am willing to work on this particular issue

### Use Cases

Currently, all published images are run as root (ie: the end user in the container is root). This has a number of security implications that are negative for the user. It is significantly easier for an attacker to breach container if the container is running as root internally.

### Attempted Solutions

There are a number of rootless versions of many base containers used in vector (distroless-static:non-root, distroless-cc-debian10:non-root) and there are common ways of making the other published containers run as nonroot (ie: just add `USER SOME_NON_EXISTANT_USER`).

### Proposal

Ideally, the published containers would run as non-root for security reasons. This is a small change to the dockerfiles that ensure the system is better secured for security conscious users.

Examples: 
- for distroless-static:
  ```docker
  ...
  FROM gcr.io/distroless/static:nonroot
  ...  
  ```

- for debian based:
  ```docker
  ...
  COPY --from=builder /var/lib/vector /var/lib/vector
  USER 65532
  RUN ["vector", "--version"]
  ```

### Version

0.21.2

**Comment by spencergilbert** [comment]
Thanks for the issue @jtcarnes - this should be resolved by some in flight work we're doing for all of our deployment targets.

**Comment by jtcarnes** [comment]
@spencergilbert Thanks for responding. I have the modifications I mentioned ready, but if it's already going to be resolved then I'll hold off on the pr.

**Comment by sdwilsh** [comment]
@spencergilbert, I don't think this actually got resolved by any changes.  All of the containers still appear to be using their root versions.

**Comment by jszwedko** [comment]
> @spencergilbert, I don't think this actually got resolved by any changes. All of the containers still appear to be using their root versions.

You are right. We had to back out the planned changes since it complicated the use of some sources like `kubernetes_logs`. We would like to do it though. We have another open issue for it which we can use for tracking: https://github.com/vectordotdev/vector/issues/1599
