### ISSUE TITLE
VRL failes to validate with events keys that have dashes

### ISSUE THREAD

**Issue by jerny-lantern** [vectordotdev/vector#12839]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hello all

Is it possible in VRL to map a dash to an underscore in a log event key.  My use case is that I am adding ec2 metadata to log events and the templating for an s3 bucket prefix doesn't seem to hande dashes in event keys.

Also any attempts I make in VRL to remap it to an underscore fail in validation.

Thank you!

### Configuration

```text
[api]
enabled = true
address = "0.0.0.0:8686"

[sources.syslog]
type = "syslog"
address = "0.0.0.0:5140"
mode = "tcp"


[transforms.ec2_metadata]
type = "aws_ec2_metadata"
inputs = ["syslog"]
namespace = "aws.ec2"
fields = ["instance-id", "account-id", "local-ipv4", "local-hostname", "region"]
refresh_interval_secs = 10


# attempts at a remap
[transforms.underscore]
inputs = ["ec2_metadata"]
type   = "remap"
source = '''
.instance_id = del!(.instance-id)
'''

### failed before trying a remapping above
[sinks.debug_file]
type = "file"
inputs = ["underscore"]
compression = "none"
path = "/tmp/vector-%Y-%m-%d-{{instance-id}}.log"
encoding = "ndjson"
```

### Version

vector 0.21.2 (x86_64-unknown-linux-gnu 1f01009 2022-05-05)

### Debug Output

```text
May 24 15:03:31 brannan11 vector[12970]: ----------------
May 24 15:03:31 brannan11 vector[12970]: x Transform "underscore":
May 24 15:03:31 brannan11 vector[12970]: error[E701]: call to undefined variable
May 24 15:03:31 brannan11 vector[12970]:   ┌─ :1:31
May 24 15:03:31 brannan11 vector[12970]:   │
May 24 15:03:31 brannan11 vector[12970]: 1 │ .instance_id = del!(.instance-id)
May 24 15:03:31 brannan11 vector[12970]:   │                               ^^
May 24 15:03:31 brannan11 vector[12970]:   │                               │
May 24 15:03:31 brannan11 vector[12970]:   │                               undefined variable
May 24 15:03:31 brannan11 vector[12970]:   │                               did you mean "null"?
May 24 15:03:31 brannan11 vector[12970]:   │
May 24 15:03:31 brannan11 vector[12970]:   = see language documentation at https://vrl.dev
May 24 15:03:31 brannan11 vector[12970]: error[E630]: fallible argument
May 24 15:03:31 brannan11 vector[12970]:   ┌─ :1:21
May 24 15:03:31 brannan11 vector[12970]:   │
May 24 15:03:31 brannan11 vector[12970]: 1 │ .instance_id = del!(.instance-id)
May 24 15:03:31 brannan11 vector[12970]:   │                     ^^^^^^^^^^^^
May 24 15:03:31 brannan11 vector[12970]:   │                     │
May 24 15:03:31 brannan11 vector[12970]:   │                     this expression can fail
May 24 15:03:31 brannan11 vector[12970]:   │                     handle the error before passing it in as an argument
May 24 15:03:31 brannan11 vector[12970]:   │
May 24 15:03:31 brannan11 vector[12970]:   = see documentation about error handling at https://errors.vrl.dev/#handling
May 24 15:03:31 brannan11 vector[12970]:   = see language documentation at https://vrl.dev
```

### Example Data

{"account-id":"redacted","appname":"CRON","facility":"authpriv","host":"redacted","hostname":"redacted","instance-id":"redacted","local-hostname":"redacted","local-ipv4":"redacted","message":"pam_unix(cron:session): session closed for user root","procid":4713,"region":"redacted","severity":"info","source_ip":"127.0.0.1","source_type":"syslog","timestamp":"2022-05-24T14:35:01Z"}

**Comment by jszwedko** [comment]
Hi @jerny-lantern !

For keys with special characters, you'll need to wrap them in quotes like: `."instance-id"`. This is mentioned here: https://vector.dev/docs/reference/vrl/expressions/#path

**Comment by jerny-lantern** [comment]
Hi @jszwedko thank you for pointing me in the right direction and the excellent and quick help!

**Comment by mdaniel** [comment]
> For keys with special characters, you'll need to wrap them in quotes like: `."instance-id"`. This is mentioned here: https://vector.dev/docs/reference/vrl/expressions/#path

Given that's the case, the EC2 metadata transform seems to be the only one that uses `-` delimited terms, unlike what seems to be every other one using `_`, so anyone who touches any of the fields would need to use that verbose `."field-name"` syntax for every one of them

Is there any appetite for adding an option `fields_use_dashes: false` or whatever that would allow more VRL friendly consumption?

**Comment by jerny-lantern** [comment]
@mdaniel thanks for following up.  I imagine there are cases where people pass in keys in their own events that have dashes and may need to do something with them.  First thing that comes to mind that is standard is http headers.

I do think there is an appetite for something that helps with this conversion in VRL would be useful as an option or like you mentioned opt in to allowing event fields with dashes.

In the meantime there are plenty of workarounds I am happy to use.

**Comment by spencergilbert** [comment]
> Is there any appetite for adding an option `fields_use_dashes: false` or whatever that would allow more VRL friendly consumption?

We could consider this option on specific transforms, however our stance is generally leaving the provided data "as-is" as much as possible. If you wanted to open a new issue to discuss that option that'd be great.

> I do think there is an appetite for something that helps with this conversion in VRL would be useful as an option or like you mentioned, opt-in to allowing event fields with dashes.

It's not likely we would add a toggle to VRL in that fashion, as it's fundamental to the way parsing and lookup works in the language.

> In the meantime the workarounds work great

As additional help if your use-case needs to heavily manipulate hyphen-full paths, iteration is landing in `0.22` and you could use that to quickly rename all the keys under `http_headers` (or what not) and replace `-` with `_`.

That would look something like:
```coffee
map_keys(.) -> |key| { replace(key, "-", "_") }
```

**Comment by jerny-lantern** [comment]
@spencergilbert thanks for the explanation.  The iteration feature looks great and I would be happy to use that.
