### ISSUE TITLE
Cannot emit metrics with `file` source.

### ISSUE THREAD

**Issue by silversupreme** [vectordotdev/vector#12851]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

In a customer call, we attempted to emit metrics from `datadog_agent` to a `file` source for local debugging. This failed because the `file` sink only supports logs, apparently.

### Version

0.21.0

**Comment by jszwedko** [comment]
I think this might have been closed by https://github.com/vectordotdev/vector/commit/aa540a21add8971556d4e2fc3dd852cfb31462a6. I'm curious if you still see this behavior on master?

**Comment by jszwedko** [comment]
Yeah, this works on `master`. I tested with:

```
[sources.source0]
type = "host_metrics"
scrape_interval_secs = 1.0

[sinks.sink0]
inputs = ["source0"]
path = "/tmp/vector-%Y-%m-%d.log"
type = "file"

[sinks.sink0.encoding]
codec = "json"
```
