### ISSUE TITLE
datadog_metrics sink logs "connection closed before message completed" errors

### ISSUE THREAD

**Issue by mhaggerty042** [vectordotdev/vector#12850]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Our data dog metrics sink logs warning and error messages about every 5 minutes.

```sh
ERROR sink{component_kind="sink" component_id=datadog_metrics_sink component_type=datadog_metrics component_name=datadog_metrics_sink}:
  request{request_id=1660}:http: vector::internal_events::http_client:
  HTTP error. error=connection closed before message completed error_type="request_failed" stage="processing"
    
WARN sink{component_kind="sink" component_id=datadog_metrics_sink component_type=datadog_metrics component_name=datadog_metrics_sink}:
  request{request_id=1660}: vector::sinks::util::retries:
  Retrying after error. error=Failed to make HTTP(S) request: connection closed before message completed
```

I don't think we're losing any data, but these warning and error logs are noisy and can be distracting while debugging other issues.

### Configuration

```text
{
    "data_dir": "/var/lib/vector",
    "sources": {
        "host_metrics_source": {
            "type": "host_metrics",
            "collectors": [
                "cpu",
                "disk",
                "filesystem",
                "load",
                "host",
                "memory",
                "network"
            ]
        }
    },
    "sinks": {
        "datadog_metrics_sink": {
            "type": "datadog_metrics",
            "inputs": [
                "host_metrics_source"
            ]
        }
    }
}
```

### Version

0.21.2

### References

This looks similar to:
- https://github.com/vectordotdev/vector/issues/12483
- https://github.com/vectordotdev/vector/issues/9671

**Comment by jszwedko** [comment]
Thanks @mhaggerty042 . I'm guessing this is due to Vector re-using connections longer than the Datadog API permits. Just to confirm, do you have any proxies or firewalls in-between Vector and Datadog that might be aborting the connection?

To confirm, Vector will automatically retry these requests. We should probably lower the log level.

**Comment by mhaggerty042** [comment]
👋  Hi @jszwedko. I've confirmed with my team that we do NOT have any firewalls in-between Vector and Datadog that could be aborting the connection. 👍  to lowering log level.
