### ISSUE TITLE
Allow `datadog_metrics` to send standalone tags

### ISSUE THREAD

**Issue by NouemanKHAL** [vectordotdev/vector#12906]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Datadog tags can be in two formats: `value` and `<KEY>:<VALUE>`.
The `tags` field in `datadog_metrics` being of type `object` only support `<KEY>:<VALUE>` tags.

### Proposal

All Datadog tags fields in the API are expected to be a `string` of comma separated tags.
Same thing as `ddtags` field in `datadog_logs`.

Defining tags: https://docs.datadoghq.com/getting_started/tagging/#defining-tags

### References

#11486

### Version

vector 0.21.2 (x86_64-unknown-linux-musl 1f01009 2022-05-05)

**Comment by jszwedko** [comment]
This work was taken up as https://github.com/vectordotdev/vector/issues/14742 and is nearing completion.
