### ISSUE TITLE
parse_nginx_log in "error" mode does not cover all errors.

### ISSUE THREAD

**Issue by Antiarchitect** [vectordotdev/vector#12900]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hi, it seems a bug in `parse_nginx_log` some messages are not parsed by `parse_nginx_log(.message, "error")` See Example Data section

### Version

0.21.2

### Example Data

2022/05/30 20:56:22 [error] 17553#17553: *3806874169 limiting requests, excess: 50.416 by zone "api_access_token", client: 193.9.249.181, server: api.enapter.com, request: "POST /graphql?deviceId=SIM-REFILLING&epc=devices&fnc=deviceGetWRState&access_token=eyJhbGciOiJIUzI1NiJ9.eyJybmxxxiJiYWU5YjVkM2Q2YzQ2NjJkYmM1ZGNjOGY5MTYyYzZhNCIsInVzZXJfaWQiOjExNjIsImVtYWlsIjoidnJvc3RvdkBlbmFwdGVyLmNvbSIsImd1aWQiOiJmNTM2NDM3NS1hNmZkLTQ0Y2QtYTliMC1jYjZmZTc5NDJiMzQiLCJleHAiOjE2NTQwMDU2NzB9.mRbL1fKYEqSVHDnDr_ZkcLmAQXpsfVebqCSdU_1SYn8&locale=ru&mobile_app_request_id=6f5cc158-6cef-4134-a02d-9e92b5c2e991&mobile_app_client_timestamp=1653936982476&mobile_app_version=2.24.0&mobile_app_build=708&mobile_app_client_env=dev HTTP/2.0", host: "api.enapter.com"

### Additional Context

Nginx 1.19.1

**Comment by nabokihms** [comment]
Hello, @Antiarchitect. Vector does not support rate-limiting error labels in Nginx logs. To be precise, the `excess` label.

> excess - Number of requests per millisecond over the configured rate that this request represents.

> excess: 50.416 by zone "api_access_token"

Adding support for the field excess is not a problem, but it would be best to parse the number of requests and the zone's name to separate fields.

```
excess: 50.416 by zone "api_access_token" - > {"excess": 50.416, "zone": "api_access_token"}
```
