### ISSUE TITLE
Invalid password for kafka sasl

### ISSUE THREAD

**Issue by loveyang2012** [vectordotdev/vector#12928]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

if kafka enabled sasl，and the paasword has the special characters，just like ‘@’ or '$', it does not working.

### Configuration

```text
[sinks.z_sink_bigscn]
type = "kafka"
inputs = ["t_bigscn"]
bootstrap_servers = "10.230.111.4:13332"
topic = "TYSS_10"
sasl.enabled = true
sasl.mechanism = "PLAIN"
sasl.username = "kafkaTYSS10"
sasl.password = "c8@i9$CWxNje36dP"
compression = "none"
encoding.codec = "json"
```

### Version

0.21.2

**Comment by jszwedko** [comment]
Hi @loveyang2012 !

I think you might be running into an issue with Vector's support for interpolating environment variables in configuration files. Vector is likely looking for an environment variable called `$CWxNje36dP`. Do you see that in the logs? You can escape the `$` by making it `$$`.

You can see more details about this feature here: https://vector.dev/docs/reference/configuration/#environment-variables

Let me know if that helps!

**Comment by jszwedko** [comment]
Closing since I'm fairly confident https://github.com/vectordotdev/vector/issues/12928#issuecomment-1143795536 describes the issue, but feel free to reopen if you are still seeing it.
