### ISSUE TITLE
chore(website): Invalid links to contributors accounts

### ISSUE THREAD

**Issue by nabokihms** [vectordotdev/vector#12938]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

There is a template for the release page. Links to GitHub accounts of contributors are generated [from it](https://github.com/vectordotdev/vector/blob/ec3e9a7ed57835b7314104a35c209a4538a35ea2/website/layouts/releases/single.html#L123).

Two options:
1. Provide contributor names without `@`.
2. Use HuGo `replace` function - `{{ replace . "@" "" }}` (I think this one is better because @ is not allowed character in GitHub user names anyway).

### Version

v0.22

### Example Data

![image](https://user-images.githubusercontent.com/32434187/171554532-c314f3a4-1794-482c-9a23-834c08631083.png)
![image](https://user-images.githubusercontent.com/32434187/171554573-3a49a053-cd46-4b43-bffe-876a742fae76.png)

**Comment by jszwedko** [comment]
Ugh, thanks @nabokihms . I could have sworn I checked that.
