### ISSUE TITLE
bug(blackhole sink): does not report "network" bytes sent

### ISSUE THREAD

**Issue by tobz** [vectordotdev/vector#12964]
While the `blackhole` sink obviously does not send data anywhere except into the proverbial `/dev/null`, we should still emit the standard `BytesReceived` event to generate a corresponding `component_sent_bytes_total` metric for it.

We'll likely just want to use the event bytes value, but this way we'll at least have conformity in terms of the component specification and expected metrics from a given type of component, etc.

**Comment by jszwedko** [comment]
@tobz I think we are emitting the `EventSent` metric, which includes `component_sent_bytes_total`?

https://github.com/vectordotdev/vector/blob/6a6dcc395ee004c25f6af527e115946d9ce06a4b/src/sinks/blackhole/sink.rs#L92-L96

The received events metric is emitted by the topology layer for sinks.
