### ISSUE TITLE
Can't specify "limit_exceeded_action" on Tag cardinality limit component 

### ISSUE THREAD

**Issue by PGBI** [vectordotdev/vector#12978]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Vector fails to start when I try to use the Tag cardinality limit component with the following error:

```
Failed to load ["/etc/vector/vector.toml"]
------------------------------------------
x invalid type: string "drop_event", expected internally tagged enum LimitExceededAction for key `transforms.block_high_cardinality_metric`
```

### Configuration

```text
[sources.statsd]
type = "statsd"
address = "[::]:8131"
mode = "udp"

[transforms.block_high_cardinality_metric]
type = "tag_cardinality_limit"
inputs = [ "statsd" ]
limit_exceeded_action = "drop_event"
mode = "exact"
value_limit = 200

[sinks.my_sink_id]
type = "console"
inputs = [ "block_high_cardinality_metric" ]
target = "stdout"

[sinks.my_sink_id.encoding]
codec = "json"
```

### Version

0.22.0

### Debug Output

```text
2022-06-03T22:22:38.153739Z  INFO vector::app: Log level is enabled. level="debug"
2022-06-03T22:22:38.153839Z  INFO vector::app: Loading configs. paths=["/etc/vector/vector.toml"]
2022-06-03T22:22:38.158710Z ERROR vector::cli: Configuration error. error=invalid type: string "drop_event", expected internally tagged enum LimitExceededAction for key `transforms.block_high_cardinality_metric`
```

### Additional Context

I tried both `limit_exceeded_action = "drop_tag"` and `limit_exceeded_action = "drop_event"`, both lead to the same type of error. The only way I found to have the component work is to omit the `limit_exceeded_action` parameter (in which case I understand it defaults to "drop_tag").

**Comment by jszwedko** [comment]
Thanks for this report @PGBI ! I can verify the behavior. Oddly it has been this way since the component was introduced.

As a workaround you can use:

```toml
[transforms.transform0]
inputs = ["source0"]
mode = "exact"
type = "tag_cardinality_limit"
value_limit = 500

[transforms.transform0.limit_exceeded_action]
limit_exceeded_action = "drop_tag"
```

But this is definitely a bug.

**Comment by PGBI** [comment]
Thanks for the quick workaround @jszwedko . I guess that up to now everybody was fine with the default behavior (dropping the tag) and I'm the first attempting at killing the whole metric :)
