### ISSUE TITLE
would be nice for "vector top" to allow selecting specific components to display

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#12993]
### Discussed in https://github.com/vectordotdev/vector/discussions/12988

<div type='discussions-op-text'>

<sup>Originally posted by **tshepang** June  6, 2022</sup>
When there are lots of components, they may not fit in a terminal. For that reason, I wish there was a way to limit what gets displayed.</div>

**Comment by zamazan4ik** [comment]
I think we can introduce it with a kind of filters, which are passed via command line. I suggest to start with a filter for `component_id`.

**Comment by spencergilbert** [comment]
Agree! I'm going to close this issue in favor of https://github.com/vectordotdev/vector/issues/14282!
