### ISSUE TITLE
Humio logs `indexed_fields` doesn't work

### ISSUE THREAD

**Issue by ilinas** [vectordotdev/vector#13027]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I am appending a `#site_key` field to messages, and want it to be an indexed field (a tag) in Humio. The field gets appended to messages, but it is not actually treated as a tag. In fact, I cannot even search by the field. The following queries do not return anything, even though I can see the field on individual messages:

`#site_key = test-abc`
`groupBy(#site_key)`

It works just fine with Vector version 0.20.1, but cannot get it to work with either 0.21.0 or 0.22.0.

Am I missing something in my configuration?

Expected behavior (0.20.1):
- `#site_key` is appended to messages
- can search and group by `#site_key` in Humio
- `#site_key` appears as a tag in data sources in Humio

Broken behavior (0.21.0 or 0.22.0):
- `#site_key` is appended to messages
- _cannot_ search and group by `#site_key` in Humio
- `#site_key` _does not_ appear as a tag in data sources in Humio

### Configuration

```text
[sources.dummy_logs]
type = "demo_logs"
format = "syslog"
interval = 1

[transforms.parse_logs]
type = "remap"
inputs = ["dummy_logs"]
source = '''
. = parse_syslog!(string!(.message))
'''

[transforms.site_fields]
type = "remap"
inputs = [ "parse_logs" ]
source = """
.site_name = "Test XYZ"
."#site_key" = "test-xyz"
"""

[sinks.humio_community]
type = "humio_logs"
inputs = [ "site_fields" ]
endpoint = "https://cloud.community.humio.com/"
index = "test1"
host_key = "hostname"
indexed_fields = [ "#site_key" ]
token = "..."
event_type = "json-for-action"
compression = "gzip"
encoding.codec = "json"
healthcheck.enabled = true
```

### Version

0.21.0

**Comment by jszwedko** [comment]
Hey @ilinas !

I think you are hitting a change in 0.21.0: https://vector.dev/highlights/2022-03-22-0-21-0-upgrade-guide/#path-syntax-changes. We made a change to bring field access in configuration options like `indexed_fields` in line with VRL which means that special characters like `#` have to be quoted now. I think:

```
indexed_fields = ['"#site_key"']
```

should work for you (note the extra quotes).

**Comment by ilinas** [comment]
I saw the changelog, but assumed it only applies to VRL syntax, such as `."#site_key" = "test-xyz"`. The documentation for the [Humio sink](https://vector.dev/docs/reference/configuration/sinks/humio_logs/) should be updated to reflect the change.

**Comment by jszwedko** [comment]
Thanks @ilinas ! I see the invalid Humio example. I'll update that.

Yeah, the changelog could maybe be worded more clearly too. The example was supposed to show that it applied to configuration options though: https://vector.dev/highlights/2022-03-22-0-21-0-upgrade-guide/#toml-transform-example
