### ISSUE TITLE
Check lookup path syntax at compile time

### ISSUE THREAD

**Issue by fuchsnj** [vectordotdev/vector#13033]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Proposal

Today lookup paths outside of a VRL context (ex: in a transform config) are parsed at runtime. If the path has an invalid syntax, it is not detected until runtime and will just not match anything. There is no error or warning generated. This is not a great user experience. The path syntax should be checked at compile time and an error shown to the user if the syntax is invalid. Ideally this would happen when the path is pre-parsed (for performance).

### Version

master

**Comment by pront** [comment]
There are very few places where we are still parsing the path.
