### ISSUE TITLE
New `gcp_stackdriver_metrics` sink

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#1304]
Like https://github.com/timberio/vector/issues/572, but for the metrics endpoints:

https://cloud.google.com/monitoring/api/ref_v3/rest/

Before we begin work, we need to create a specification for this. This should be fairly simple, but it is worth understanding exactly how we'll transmit over their endpoints.

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/6666
