### ISSUE TITLE
Does vector support apple arm M1?

### ISSUE THREAD

**Issue by hantmac** [vectordotdev/vector#13137]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Proposal

Hope that `vector` support apple arm64 M1.

**Comment by spencergilbert** [comment]
Hi @hantmac - it does, a good number of the team uses M1's for day-to-day work. There's some pain points, and lack of good support in CI has stopped us from provided pre-built binaries - but you can compile it yourself locally.

```shell
~/C/g/v/vector on  master [!⇣] is 📦 v0.23.0 via 🦀 v1.58.1 
❯ target/debug/vector --version
vector 0.23.0 (aarch64-apple-darwin debug=full)
```

**Comment by spencergilbert** [comment]
Issue for publishing artifacts: https://github.com/vectordotdev/vector/issues/10193
