### ISSUE TITLE
Clean up Datadog target URL options (`site`, `endpoint`, and `region`)

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#13142]
The Datadog sinks offer 3 ways to build a target URL: `site`, `region`, and `endpoint`. These are confusing:

1. We should actually deprecate and remove the `region` option since it's been deprecated for a while now.
2. What is the difference between `site` and `endpoint`? We should clarify this better in the docs.

**Comment by dsmith3197** [comment]
This was done in https://github.com/vectordotdev/vector/pull/18940
