### ISSUE TITLE
Default the `scrape_interval_secs` option to 1 in the `internal_metrics` source

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#13143]
Currently, the `scrape_interval_secs` option defaults to 2 in the `internal_metrics` source. I'd like to change this to 1 since many users (including our UI) will look to get "per second" metrics. For example, "events per second", "bytes per second", etc.

### Open Questions

1. Will this increase downstream cost for users?
2. Is there a performance impact of this?

**Comment by zamazan4ik** [comment]
I do not think that will be a huge perfomance of this nor huge downstream cost for the end-users. However, if some users in some strange scenarios will be affected - they also be able to increase scrape interval.

@neuronull what do you think?

**Comment by jszwedko** [comment]
I think @bruceg and @tobz will probably have thoughts here.

**Comment by tobz** [comment]
There really shouldn't be much of a performance cost in doing so... just the "cost" of pushing more metrics downstream to whatever is consuming the metrics from `internal_metrics`.
