### ISSUE TITLE
Lua doesn't load C module

### ISSUE THREAD

**Issue by anufrien** [vectordotdev/vector#13161]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I have a C module. I'm trying to import the C module in Lua script and get an error

`
14T13:40:50.059949Z ERROR transform{component_kind="transform" component_id=test_lua component_type=lua component_name=test_lua}: vector::internal_events::lua: Error in lua script; discarding event. error=RuntimeErrorHooksProcess { source: RuntimeError("error loading module 'FiftyOneDegreesPatternV3' from file '/usr/local/lib/lua/5.4/FiftyOneDegreesPatternV3.so':\n\tDynamic loading not supported\nstack traceback:\n\t[C]: in ?\n\t[C]: in ?\n\t[C]: in function 'require'\n\t[string \"src/transforms/lua/v2/mod.rs:130:9\"]:4: in function <[string \"src/transforms/lua/v2/mod.rs:130:9\"]:1>") } error_type="script_failed" error_code="runtime_error_hook_process" stage="processing" internal_log_rate_secs=30
`

But your code creates an unsafe Lua instance for loading C modules
https://github.com/vectordotdev/vector/blob/4e6e957238d21af68d75c07cb5badeec1b66ca87/src/transforms/lua/v2/mod.rs#L137

How should I do it?

### Configuration

```text
[transforms.test_lua]
type = "lua"
inputs = [ "parse_logs" ]
version = "2"
    [transforms.test_lua.hooks]
    process = """
function (event, emit)
\tfod=require("FiftyOneDegreesPatternV3")
\tprint('test: ', fod)
\temit(event)
end"""
```

### Version

vector 0.21.0 (x86_64-unknown-linux-musl c1edb89 2022-04-14)

### Debug Output

```text
14T13:40:50.059949Z ERROR transform{component_kind="transform" component_id=test_lua component_type=lua component_name=test_lua}: vector::internal_events::lua: Error in lua script; discarding event. error=RuntimeErrorHooksProcess { source: RuntimeError("error loading module 'FiftyOneDegreesPatternV3' from file '/usr/local/lib/lua/5.4/FiftyOneDegreesPatternV3.so':\n\tDynamic loading not supported\nstack traceback:\n\t[C]: in ?\n\t[C]: in ?\n\t[C]: in function 'require'\n\t[string \"src/transforms/lua/v2/mod.rs:130:9\"]:4: in function <[string \"src/transforms/lua/v2/mod.rs:130:9\"]:1>") } error_type="script_failed" error_code="runtime_error_hook_process" stage="processing" internal_log_rate_secs=30
```

### Example Data

{
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
}

**Comment by anufrien** [comment]
I find this code in file
.cargo/config.toml

```
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-rdynamic"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-rdynamic"]


# for these musl targets libstdc++ will be linked statically (that's configured in e.g. leveldb-sys)
# we provide the location of that library here
[target.x86_64-unknown-linux-musl]
rustflags = ["-Lnative=/usr/local/x86_64-linux-musl/lib"]
```

Maybe the problem is here?

@jszwedko 
not work :(
```
mlua::Lua::unsafe_new_with(mlua::StdLib::ALL_SAFE | mlua::StdLib::FFI, mlua::LuaOptions::default())
```

```
Compiling vector v0.23.0 (/project)
error[E0599]: no associated item named `FFI` found for struct `LuaStdLib` in the current scope
   --> src/transforms/lua/v2/mod.rs:140:79
    |
140 |             mlua::Lua::unsafe_new_with(mlua::StdLib::ALL_SAFE | mlua::StdLib::FFI, mlua::LuaOptions::default())
    |                                                                               ^^^ associated item not found in `LuaStdLib`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `vector` due to previous error
make: *** [target/x86_64-unknown-linux-musl/release/vector] Error 101
```

**Comment by khvzak** [comment]
vector linked with musl libc does not support loading dynamic modules
vector linked with glibc support dynamic modules
This is a (musl) libc limitation.

**Comment by anufrien** [comment]
I am trying to make a gnu package
```
make package-x86_64-unknown-linux-gnu
```
But this image is based on Centos 7 and depends on Glibc-2.18. But centos 7 doesn't have Glibc-2.18 dependency. Centos 7 install max version Glibc-2.17. Make throws an error 

```
error: failed to run custom build command for `libc v0.2.126`

Caused by:
  process didn't exit successfully: `/target/release/build/libc-a6af969fbcf9ea59/build-script-build` (exit status: 1)
  --- stderr
  /target/release/build/libc-a6af969fbcf9ea59/build-script-build: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /target/release/build/libc-a6af969fbcf9ea59/build-script-build)
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [target/x86_64-unknown-linux-gnu/release/vector] Error 101
```

**Comment by jszwedko** [comment]
Ah, thanks for the clarification @khvzak !

@anufrien `make package-x86_64-unknown-linux-gnu` will still use `cross` to build the binary. I'm curious what happens if you just run `cargo build --release` in your CentOS 7 environment?

I'll close this issue out since it doesn't appear to be an actual issue, just a limitation of musl, but happy to continue the discussion about building on CentOS 7 if you want to open a separate issue for that.
