### ISSUE TITLE
Vector logs an error on packets that are too large

### ISSUE THREAD

**Issue by cholcombe973** [vectordotdev/vector#13175]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When processing entries vector encounters some input that is larger than it can handle:
```
 ERROR sink{component_kind="sink" component_id=metrics_to_datadog component_type=datadog_metrics component_name=metrics_to_datadog}: vector::internal_events::datadog_metrics: Failed to encode Datadog metrics. error=A split payload was still too big to encode/compress with…
```
It appears that the maximum payload size is [limited](https://github.com/vectordotdev/vector/blob/a54f0c2b13a0a7fd9c344834d3a6a31d68aceca1/src/sinks/datadog/metrics/config.rs#L37). 
When vector encounters packets that would need to be [split](https://github.com/vectordotdev/vector/blob/a54f0c2b13a0a7fd9c344834d3a6a31d68aceca1/src/sinks/datadog/metrics/encoder.rs#L211) it logs an error instead. 

### Configuration

```text
# Vector's API for introspection
[api]
  enabled = true
  address = "127.0.0.1:8686"

# Vector's own internal metrics
[sources.internal_logs]
  type = "internal_logs"

[sources.internal_metrics]
type = "internal_metrics"
scrape_interval_secs = 2

[sources.datadog_agents]
type = "datadog_agent"
address = "[::]:8564"
multiple_outputs = true

[transforms.tag_logs]
type = "remap"
inputs = [ "datadog_agents.logs" ]
source = """
# Parse the received .ddtags field so we can more easily access the contained tags, set to empty object if parsing fails
.ddtags = parse_key_value(.ddtags, key_value_delimiter: ":", field_delimiter: ",") ?? {}
.ddtags.sender = "vector"
# Re-encode Datadog tags as a string for the `datadog_logs` sink
.ddtags = encode_key_value(.ddtags, key_value_delimiter: ":", field_delimiter: ",")
"""

[transforms.tag_metrics]
type = "remap"
inputs = [ "datadog_agents.metrics" ]
source = """
.tags.sender = "vector"
"""

[sinks.log_to_datadog]
type = "datadog_logs"
inputs = [ "internal_logs", "tag_logs" ]
default_api_key = "REDACTED"

[sinks.metrics_to_datadog]
type = "datadog_metrics"
inputs = [ "internal_metrics", "tag_metrics" ]
default_api_key = "REDACTED"
```

### Version

vector-0.22.0-1

**Comment by tobz** [comment]
So, this error is actually emitted when it tries to split an input batch but fails to do so successfully i.e. the new requests from the split inputs are still too big.

It's definitely a little weird that it would fail after splitting since the limit is 3MB/62MB compressed/uncompressed... which can typically hold a lot of metrics.

What do the `component_discarded_events_total` and `component_errors_total` counters look like for you when this happens? Specifically for the `datadog_metrics` sink. Knowing how many events are discarded, divided by the number of errors, would give us an indication of how large the split-but-still-too-big requests are.. and whether we're dealing with some sort of pathologically-sized distribution or just a lot of series or what.

**Comment by cholcombe973** [comment]
Looks like in the past hour on datadog's graphs that this has averaged 52K `discarded_events_total` and 10.95 `component_errors_total`

**Comment by Sg-23** [comment]
I am also facing a similar issue while sending the metrics from datadog-agent -> vector-agent -> aggregator -> datadog. 
This works fine for a few clusters but as soon as the traffic is deployed to all the clusters, metrics start dropping intermittently with the below errors.
Below are the errors I am able to see at different steps:

In datadog-agent:
`2022-12-01 13:16:17 UTC | CORE | ERROR | (pkg/forwarder/worker.go:180 in process) | Too many errors for endpoint 'http://10.216.176.236:8282/api/beta/sketches': retrying later`

In vector-agent:
`2022-12-01T07:12:22.691704Z WARN sink{component_kind="sink" component_id=metric-ingest component_type=vector component_name=metric-ingest}: vector::sinks::util::retries: Request timed out. If this happens often while the events are actually reaching their destination, try decreasing `batch.max_bytes` and/or using `compression` if applicable. Alternatively `request.timeout_secs` can be increased.`

In aggregator:
`2022-12-01T06:31:48.293477Z ERROR sink{component_kind="sink" component_id=eg_datadog component_type=datadog_metrics component_name=eg_datadog}: vector::internal_events::datadog_metrics: Failed to encode Datadog metrics. error=A split payload was still too big to encode/compress withing size limits. error_code=split_failed error_type="encoder_failed" stage="processing"`

Datadog agent version: 7.40.1-jmx
Datadog cluster-agent version: 7.40.1
Vector version: 0.24.1-debian

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/17764
