### ISSUE TITLE
bug(buffers): disk_v2 reader should not panic on `ReaderError::PartialWrite`

### ISSUE THREAD

**Issue by tobz** [vectordotdev/vector#13178]
Currently, we send any "bad read" error back through to the call of `Reader::next`. This is suboptimal because in all cases, the reader is designed to recover from errors, or at least attempt to skip to the next good record, etc. They are potentially worth logging, or incrementing counters when encountered, but they do not rise to the level of panicking.

This was brought up in #13001 ([comment](https://github.com/vectordotdev/vector/discussions/13001#discussioncomment-2958013)) by a prospective user, and represents a real-world case where users hitting "out of space" limits would almost certainly be perma-stuck until clearing the buffer.

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/13180
