### ISSUE TITLE
Allow configuration of internal log rate limit

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#13185]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Currently internal logs are rate limited at the call site via a tracing label, `internal_log_rate_secs`.  Instead, I think we should let users be able to configure the rate limit and apply it uniformly over all internal logs.

### Proposal

Add a configuration option to control the log rate limiting secs. This could default to 10, which I believe is the most commonly used static limit.

### Version

vector 0.22.2

**Comment by hhromic** [comment]
This issue is related to #9929 where I described (as a solution proposal) to indeed make the rate limit configurable, specially for the use-case of running unit tests. So if this issue is addressed, that other issue should be closed too 👍.
