### ISSUE TITLE
not compressed files for s3 sink:

### ISSUE THREAD

**Issue by Valiev** [vectordotdev/vector#13215]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Even `compression = "gzip"` option is set and vector puts files with `gz` extension, they are not compressed. 

### Configuration

```text
[sources.kafka]
  type = "kafka"
  bootstrap_servers = "%KAFKA_SERVERS%"
  group_id = "vector-reader"
  topics = [ "^[^_].*" ]
  acknowledgements.enabled = true
  decoding.codec = "json"

[sinks.s3_service_name]
  type = "aws_s3"
  inputs = [ "kafka" ]
  bucket = "%BUCKET_LOGS%"
  region = "eu-central-1"
  key_prefix = "vector/{{ topic }}/%Y-%m-%d/%H-"
  compression = "gzip"
  encoding.codec = "ndjson"
```

### Version

0.22.2

**Comment by Valiev** [comment]
You are right! Sorry for confusion!

**Comment by jszwedko** [comment]
No worries! It is a common confusion, especially because the file extension is left intact.
