### ISSUE TITLE
Dnstap parser does not correctly handle DOT, DOH or DnsCrypt SocketProtocol values

### ISSUE THREAD

**Issue by franklymrshankley** [vectordotdev/vector#13234]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The DNSTap parser is based around an older version of the dnstap.proto which, at the time, did not accommodate DoT, DoH, or DnsCrypt SocketProtocols.  This protobuf schema has since been updated, and it is now possible that messages can be received containing these values which should be correctly handled but which will, instead, result in an ERROR log message:

```
2022-06-20T05:29:16.370290Z ERROR source{component_kind="source" component_id=my_source_id component_type=dnstap component_name=my_source_id}:connection: vector::internal_events::dnstap: Error occurred while parsing dnstap data. error="Unknown socket protocol: 6" stage="processing" error_type="parser_failed" internal_log_rate_secs=10
```
Similarly, the parser does not accommodate `Policy` messages within a dnstap message.  Although optional, these messages provide information about policy decisions (e.g. whether to permit or block resolution of a hostname) made by the resolver software, and are very valuable. 

The dnstap.proto should be updated to reflect the new dnstap.proto schema, and the parser updated to extract any Policy message present in the dnstap message.

### Version

0.22.2

### References

#13227 addresses the dnstap.proto and the handling of the new values in the parser, but does not cover the parsing of `Policy` messages.

**Comment by jszwedko** [comment]
Thanks for this contribution @franklymrshankley !

It seems like, with this change, that the:

```
sources::dnstap::parser::tests::test_get_socket_protocol_name
```

test is failing. Does anything jump out to you about that test that would have changed as a result of this? You can run the integration tests via

```
make test-integration-dnstap
```

The rest of the integration tests still passed.
