### ISSUE TITLE
Defer event finalization in `prometheus_remote_write` sink

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#13266]

**Comment by spencergilbert** [comment]
@jszwedko @bruceg - Unless I'm confused I think this is already done by virtue of being built on `ServiceSink`. The `call()` handles [updating status](https://cs.github.com/vectordotdev/vector/blob/39c5f13ac6956a577e3f333b54bc6b7ca2995fbc/src/sinks/util/sink.rs?q=ServiceSink#L455) and the `poll_complete()` handles the [acking](https://cs.github.com/vectordotdev/vector/blob/39c5f13ac6956a577e3f333b54bc6b7ca2995fbc/src/sinks/util/sink.rs?q=ServiceSink#L486) - which should always happen in the correct order.

**Comment by bruceg** [comment]
I think you're right. I was going largely on it not being marked as supporting acknowledgements in the documentation.

**Comment by spencergilbert** [comment]
Opened https://github.com/vectordotdev/vector/pull/13351
