### ISSUE TITLE
`aws_s3` sink tagging internal metrics with high cardinality `endpoint`

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#13284]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Reported by https://github.com/vectordotdev/vector/issues/11821#issuecomment-1162582737 . I was able to reproduce.

It seems like the `aws_s3` sink is tagging internal metrics with an `endpoint` tag that includes the path and query parameters. For example:

```
vector_processed_bytes_total{component_id="sink0",component_kind="sink",component_name="sink0",component_type="aws_s3",endpoint="/timberio-jesse-test/test-metric-cardinality/date%3D2022-06-22/1655913536-cc808697-2d56-43b3-a419-bd6148b9d368.log.gz?x-id=PutObject",protocol="https",region="us-east-1"} 402207 1655913540158```
```

### Configuration

```text
[sources.source0]
type = "stdin"

[sinks.sink0]
inputs = ["source0"]
bucket = "timberio-jesse-test"
key_prefix = "test-metric-cardinality/date=%F/"
type = "aws_s3"
encoding.codec = "ndjson"
region = "us-east-1"

[sources.metrics]
scrape_interval_secs = 2.0
type = "internal_metrics"

[sinks.prometheus]
inputs = ["metrics"]
address = "0.0.0.0:9598"
type = "prometheus_exporter"
```

### Version

vector 0.22.2

**Comment by aavileli** [comment]
thanks @jszwedko
