### ISSUE TITLE
Datadog API key pass-through doesn't work for metrics

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#13357]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Passing `datadog_agent` to `datadog_metrics` does not result in the API key making it through. This appears to be because the metrics endpoints pass the API key as a query parameter `?api_key=....` rather than an HTTP header like Vector expects:

https://github.com/vectordotdev/vector/blob/55228f6da30c22c72321b6680b5de96a99f6c0d0/src/sources/datadog/agent/metrics.rs#L107

We should check for the API key in the query parameters as well.

We should also double check the logic for log and trace ingestion to make sure it correctly looks for both the header and query parameter.

### Configuration

```text
[sources.source0]
type = "datadog_agent"
address = "0.0.0.0:8282"
multiple_outputs = true
store_api_key = true

[sinks.sink0]
inputs = ["source0"]
default_api_key = ""
type = "datadog_metrics"
```

### Version

vector 0.22.0

### Debug Output

```text
2022-06-27T20:58:15.284738Z DEBUG sink{component_kind="sink" component_id=sink0 component_type=datadog_metrics component_name=sink0}:request{request_id=1}:http: vector::internal_events::http_client: Sending HTTP request. uri=https://0-21-2-vector.agent.datadoghq.com/api/v1/series method=POST version=HTTP/1.1 heade
rs={"dd-api-key": "", "dd-agent-payload": "4.87.0", "content-type": "application/json", "content-encoding": "deflate", "user-agent": "Vector/0.21.2 (aarch64-apple-darwin)", "accept-encoding": "identity"} body=[2673 bytes]                                                                                              2022-06-27T20:58:15.373714Z DEBUG sink{component_kind="sink" component_id=sink0 component_type=datadog_metrics component_name=sink0}:request{request_id=1}:http: vector::internal_events::http_client: HTTP response. status=403 Forbidden version=HTTP/1.1 headers={"date": "Mon, 27 Jun 2022 20:58:15 GMT", "content-type
": "application/json", "content-length": "170", "connection": "keep-alive", "cache-control": "no-cache", "via": "haproxy"} body=[170 bytes]                                                                                                                                                                                2022-06-27T20:58:15.373935Z ERROR sink{component_kind="sink" component_id=sink0 component_type=datadog_metrics component_name=sink0}:request{request_id=1}: vector::sinks::util::retries: Not retriable; dropping the request. reason="response status: 403 Forbidden"
```

### Additional Context

Tested with Datadog Agent version 7.35.1 with config:

```yaml
vector:
  metrics:
    enabled: true
    url: "http://localhost:8282"
```

**Comment by neuronull** [comment]
After looking into this, the datadog_metrics source is sending the api key correctly in the event.
The issue seems to be actually that the datadog_logs sink is not using the api_key from the incoming event.
I'll post a PR soon to address it.

**Comment by spencergilbert** [comment]
> After looking into this, the datadog_metrics source is sending the api key correctly in the event. The issue seems to be actually that the datadog_logs sink is not using the api_key from the incoming event. I'll post a PR soon to address it.

I assume you mean the `datadog_agent` source + `datadog_metrics` sink?

**Comment by neuronull** [comment]
> I assume you mean the `datadog_agent` source + `datadog_metrics` sink?

Ah yes, my mistake... I need to calibrate the neurons before writing component names!

**Comment by neuronull** [comment]
> We should also double check the logic for log and trace ingestion to make sure it correctly looks for both the header and query parameter.

Confirmed, the dd traces and log sinks do have the the api key pass through set up.

**Comment by jszwedko** [comment]
> > We should also double check the logic for log and trace ingestion to make sure it correctly looks for both the header and query parameter.
> 
> Confirmed, the dd traces and log sinks do have the the api key pass through set up.

👍 thanks for checking!
