### ISSUE TITLE
Investigate `config::builder::tests::version_json_order` not running in CI

### ISSUE THREAD

**Issue by 001wwang** [vectordotdev/vector#13359]
As part of #13355, it was discovered that the `version_json_order` test was failing [due to an improper assertion](https://github.com/vectordotdev/vector/pull/13355#discussion_r907753643). #13355 fixes the test logic, but it's unclear why CI wasn't catching the test failure: one possibility being that the test isn't running. We should investigate to ensure other tests aren't in a similar position.

### Example

On `master` @ 4b5975038, run `cargo test --no-default-features --features enterprise,api -- config::builder --nocapture`. You will see
```
running 2 tests
thread 'config::builder::tests::version_json_order' panicked at 'assertion failed: map.keys().eq(expected_keys)', src/config/builder.rs:383:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test config::builder::tests::version_hash_match ... ok
test config::builder::tests::version_json_order ... FAILED

failures:

failures:
    config::builder::tests::version_json_order

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 373 filtered out; finished in 0.00s
```

**Comment by jszwedko** [comment]
It seems to be running in CI at least. I can see it ran in this PR: https://github.com/vectordotdev/vector/runs/7082332196?check_suite_focus=true

```
2022-06-27T21:17:07.4606441Z         PASS [   0.014s]                                                vector config::builder::tests::version_hash_match
2022-06-27T21:17:07.4627800Z         PASS [   0.014s]                                                vector config::builder::tests::version_json_order
```

**Comment by jszwedko** [comment]
I'm guessing we just had the hash assertion match whatever was reported in CI. I do see it fails when run locally. I think we can probably close this issue.

**Comment by 001wwang** [comment]
🤔 Huh, that is very interesting. I still don't think I understand why it passes in CI and not locally. This test is for asserting the keys of `ConfigBuilderHash` serialize in a particular order (`vector_hash_match` is the one asserting on an actual hash), but it does so by first serializing to `serde_json::Value`. I would think that this then re-orders the keys (since `Value::Map == BTreeMap` now takes the place of `ConfigBuilderHash`), which is what we see locally. Is there maybe a different version of `serde` in CI that has different behavior (maybe with `preserve_order` feature enabled)?

**Comment by jszwedko** [comment]
Aha, you are exactly right 😄 

If you run `cargo test --no-default-features --features api,enterprise` it does not include the `preserve_order` feature, but if you run with the `default` featureset (which is what CI uses), it does:

```
$ cargo tree --no-default-features --features enterprise,api  -i serde_json -f '{p} {f}' --depth 0 | head -n 1
serde_json v1.0.81 default,raw_value,std
$ cargo tree --no-default-features --features default  -i serde_json -f '{p} {f}' --depth 0 | head -n 1
serde_json v1.0.81 alloc,default,indexmap,preserve_order,raw_value,std
```

**Comment by 001wwang** [comment]
Ahh, TIL, thanks for digging into that. Unfortunate behavior 🤔 -- if I understand correctly, this means some dependency somewhere (underlying `bson` and `jsonpath_lib` crates if I'm using `cargo tree` correctly) requires `preserve_order`, so ultimately Vector under `default` features is compiled with a `serde` with `preserve_order` enabled. And, if `IndexMap` is used, our assumptions fail and our tests along with them.

The best workaround seems to be to explicitly write out our sorting logic (i.e. traverse `Value` and manually convert `Map` into `BTreeMap` and back). What do you think @jszwedko?

**Comment by 001wwang** [comment]
I think it might also make sense to enable `preserve_order` explicitly in our `Cargo.toml` to avoid any future issues.

**Comment by 001wwang** [comment]
From these learnings, I've made necessary changes to #13355. Closing this ticket as the investigation is complete: no CI fixes required, just unexpected mismatching environments.
