### ISSUE TITLE
enhancement(host_metrics source): collect CPU iowait stat on Linux

### ISSUE THREAD

**Issue by tobz** [vectordotdev/vector#13366]
Currently, the `host_metrics` source collects the `user`, `system`, and `idle` values for CPU usage, while additionally collecting the `nice` value on Linux. We should also collect the `iowait` value on Linux, as it's a generally valuable metric and is already available through `heim`'s extension trait for CPU usage metrics.

(https://github.com/vectordotdev/vector/blob/master/src/sources/host_metrics/cpu.rs)

**Comment by charmitro** [comment]
I would like to take this over.
In my belief we should have a `#[cfg(target_os = "linux")]` since we only need this on Linux.

**Comment by jszwedko** [comment]
Hey @charmitro ! Great! We'd happily accept a contribution for this.
