### ISSUE TITLE
Enhance stdin source to more general pipe

### ISSUE THREAD

**Issue by marler8997** [vectordotdev/vector#13379]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

We're currently making use of the `stdin` "source" and would like to expand our usage to multiple pipes.  Our application starts a single instance of vector and spawns multiple processes, we'd like each process to be able to send log events to vector.

### Attempted Solutions

We could use sockets to open separate connections for each process, however, this prevents us from being able to setup the interprocess channels beforehand which means a process could encounter an error before it connects to the vector socket which means it can't report the error to vector.  By using pipes, we can setup all the connections beforehand, so an errors that occur during this time can still be reported.

### Proposal

I propose that a new source be added named "pipe".  It would be identical to the current "stdin" source except it provides a configuration for the "fd number".  A pipe with an fd number of "0" would be identical to the current "stdin" source.

### Version

vector 0.18.0 (x86_64-unknown-linux-gnu)

**Comment by jszwedko** [comment]
Hey @marler8997 !

Thanks for opening this! After thinking about it a bit more, it seems like this might overlap with https://github.com/vectordotdev/vector/issues/3874 ? Would you agree?

**Comment by marler8997** [comment]
A "named pipe" has the same issue as the socket, namely, you set it up after the fact rather than setting it up beforehand.

**Comment by marler8997** [comment]
A variation on this idea would be to enhance the `stdin` source to configure a fd number.  Possibly something like this: https://github.com/marler8997/vector/commit/bfc11f9b061d9744f1f1a45ce26867e251fee98b

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/13389
