### ISSUE TITLE
Provide an ergonomic way to check code with all features

### ISSUE THREAD

**Issue by a-rodin** [vectordotdev/vector#1337]
Before https://github.com/timberio/vector/pull/1331 `make check` was equivalent to `cargo check --all  --all-features --all-targets`.

However, after https://github.com/timberio/vector/pull/1331 the feature pairs `leveldb-plain`/`leveldb-cmake` and `rdkafka-plain`/`rdkafka-cmake` became mutually exclusive. These pairs of mutually exclusive features needed to ensure that all dependencies for `leveldb` and `rdkafka` are correctly written to `Cargo.lock`, so that Vector can be built with `--freeze` build flag. Cargo doesn't support defining mutually exclusive features yet (see https://github.com/rust-lang/cargo/issues/2980), so the command in `make check` was changed to `cargo check --all --all-targets`.

It means that `docker` feature is not checked anymore when `make check` is called, although it is still compiled in CI as part of `test-stable`.

One approach is to change `check-code` target in the `Makefile` to something like

```make
@cargo check --all  --all-targets
@cargo check --all  --features=nightly --all-targets
@cargo check --all  --features=docker --all-targets
```

However, this approach doesn't look like very elegant and there might be a better solution. I'd like to hear @LucioFranco's thoughts about this.

**Comment by LucioFranco** [comment]
So a couple of things, I am curious if there is a solution that doesn't use mutually exclusive feature flags. This in of it self breaks kinda how cargo handles feature flags as you can tell from the issue you linked. For me it's a bit important to not use make as I am using `rust-analyzer` which then uses `cargo watch` thus I would like to make sure we keep a workflow that is workable through cargo.

In the end, if the only feature flag that I need to add beyond default is docker, I think it is fine. But I'm not a big fan of having a huge array of feature flags and combinations which can lead us to missing things sometimes.

**Comment by a-rodin** [comment]
I was thinking about this, it could be fixed by adding support for building new versions of LevelDB on GNU/Linux and macOS without `cmake`, but using only `cc` crate.

It would allow us to keep features for `leveldb` create simple, just `leveldb` and `leveldb,leveldb/cmake_build`, so that two types of the builds would be not mutually exclusive.

**Comment by LucioFranco** [comment]
Seems like a good idea.

**Comment by jszwedko** [comment]
Closing this since it hasn't seemed to be an issue.
