### ISSUE TITLE
Allow config builders to fetch component tracing span

### ISSUE THREAD

**Issue by LucioFranco** [vectordotdev/vector#1338]
# Problem

Since we use tracing's powerful span features we should make sure that each component logging happens within the correct span. For components, like joinable transforms (ex `aws_ec2_metadata`) that spawn a background task we need to ensure that the component span gets attached to the background task. The problem is that we only attach the specific span at component _spawn_ time, not at component _construction_ time. This means that we are not aware of the span until after we have spawned the background task.

# Proposal

We should create the span and enter the span when calling `build` in `build_pieces` to then allow the `build` fn to log within that span but also allow us to use https://docs.rs/tracing/0.1.10/tracing/span/struct.Span.html#method.current to fetch the current span and attach it to the background tasks. Then we must also store the span with the task that will be spawned later.

cc @lukesteensen

**Comment by lukesteensen** [comment]
It'd be helpful to see a small example of what this would look like. It seems like it could be a bit awkward to return spans and stash them alongside tasks. This would definitely be something to keep in mind if we think about reworking how building and spawning and designed.

Also, could you be a little more specific about what we're losing by not doing this?

**Comment by LucioFranco** [comment]
@lukesteensen the biggest downside to this is for example with the `aws_ec2_metadata` transform, since we don't have the span that will be created for that transform at build time we have no way of attaching it to the spawned bg task. Thus we can't correlate logs that come from the same transform via spans, which is the goal of spans.

**Comment by jszwedko** [comment]
Closing since this doesn't appear to be an issue anymore.
