### ISSUE TITLE
Support auth on websocket sink

### ISSUE THREAD

**Issue by bbassingthwaite** [vectordotdev/vector#13386]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

We would like to be able to specify an `Authorization` header on the initial websocket HTTP request.

### Proposal

The `http` sink which has a `auth` [configuration](https://vector.dev/docs/reference/configuration/sinks/http/#auth) section which supports various authentication methods such as bearer tokens. If we had this option on `websocket` that would satisfy our use case.

### Version

vector 0.22.3 (x86_64-unknown-linux-gnu)

**Comment by jszwedko** [comment]
Thanks @bbassingthwaite ! I agree this could be supported in the same manner as the `http` sink.
