### ISSUE TITLE
Excessive component_received_bytes_total internal metrics since 0.21

### ISSUE THREAD

**Issue by cspargo** [vectordotdev/vector#13408]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Since we updated to 0.21 we've seen memory and CPU usage on our vector "aggregator" pods constantly rising.
This was tracked down to this metric, where new values for "peer_addr" were regularly being added and never removed, I presume as different TCP port numbers are used for repeated connections across the clients

```
vector_component_received_bytes_total{container="vector", endpoint="prom-exporter", instance="yy.yy.yy.yy:9090", job="vector-aggregator", namespace="vector", peer_addr="xx.xx.xx.xx:35014", pod="vector-aggregator-0", protocol="tcp"}
```

This is a graph of vector_events_in_total for the internal_metrics source, showing it's receiving more and more metrics over time
![image](https://user-images.githubusercontent.com/4132393/176831780-2fe98fd9-6239-42c1-8f56-bc906ae1d093.png)

We put in a filter to stop these from going to prometheus and memory usage is not rising as fast, but still it seems to consume increasing amounts of CPU. Is there any way to put a limit on this or turn this off?

### Configuration

```text
just using basic source for internal metrics, and prometheus sink, with filter now added to exclude the problematic metric


    sources:
      source_internal_metrics:
        type: internal_metrics
    sinks:
      prom-exporter:
        address: 0.0.0.0:9090
        inputs:
        - filter_internal_metrics
        type: prometheus_exporter
    transforms:
      filter_internal_metrics:
        condition: |
          .name != "component_received_bytes_total"
        inputs:
        - source_internal_metrics
        type: filter

```

vector agents send logs to vector aggregator using vector source/sink. Nothing really special about it.
```


### Version

seen on 0.21.2 and 0.22.1

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

**Comment by jszwedko** [comment]
Hi @cspargo ,

Thanks for this report. We plan to drop these high cardinality tags shortly. I anticipate it being done in time for 0.24.0.

**Comment by pachico** [comment]
Has this been solved in version 0.24?

**Comment by bruceg** [comment]
The ability to expire metrics was introduced in the 0.24 release through #13872. I see it isn't in the release notes, though. This can be enabled by [setting `expire_metrics` in the top-level configuration](https://vector.dev/docs/reference/configuration/global-options/#expire_metrics).

**Comment by pachico** [comment]
Thank you.

**Comment by jszwedko** [comment]
Rolling this into https://github.com/vectordotdev/vector/issues/15426
