### ISSUE TITLE
Ingest Vector logs with Vector?

### ISSUE THREAD

**Issue by pikeas** [vectordotdev/vector#13431]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Dockerized Vector skips its own container logs. This leaves a bit of a blind spot - is there guidance on "who watches the watchers" in prod?

**Comment by jszwedko** [comment]
Hi @pikeas !

You can configure Vector to read its own pod logs by configuring its [pod labels](https://github.com/vectordotdev/helm-charts/tree/develop/charts/vector#vector-values). The default is to ignore its own logs (`{"vector.dev/exclude":"true"}`) to avoid the possibility of creating a feedback loop.

In addition, you can also use the `internal_logs` source to capture and forward Vector's logs.

Hopefully this helps! Let me know if you have any other questions.

**Comment by jszwedko** [comment]
Closing this since I think the above answers the question, but please let me know if not!
