### ISSUE TITLE
Zombie disk buffer data when Non-retriable error on S3 sink

### ISSUE THREAD

**Issue by rodrigo-garcia-edo** [vectordotdev/vector#13455]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When using AWS S3 sink, when vector is not able to send the log event because permissions on a bucket are missing, a non-retriable error happens and the log seems to be lost (this does not happen if there is a connectivity issue for example).
Also, the disk buffer keeps growing as more events arrive to vector.
After giving enough permissions to the sink to S3, new events are sent properly, but all the previous events are lost (while the disk buffer folder is never cleaned).
This leads to potential increasing zombie buffer log events and no way to ensure resilience or robustness like it happens when connectivity fails for a while (in that case, all messages are finally sent to S3).

I expect that the buffer keeps those logs when permissions on S3 fail, and recover the events and send them to S3 once permissions are fixed (you could temporarilly mess with permissions).

### Configuration

```text
[sinks.xxxxxx]
type                    = "aws_s3"
inputs                  = [ "xxxxxx" ]
acl                     = "private"
bucket                  = "${xxxxxxx}"
key_prefix              = "{{ key_prefix }}/"
content_type            = "text/x-log"
filename_append_uuid    = true
filename_extension      = "json.gz"
filename_time_format    = "%s"
compression             = "gzip"
encoding.codec          = "ndjson"

buffer.max_size         = 1_000_000_000
buffer.type             = "disk"
buffer.when_full        = "drop_newest"
```

### Version

0.22.3

### Example Data

`ERROR sink{component_kind="sink" component_id=some-id component_type=aws_s3 component_name=some-component-name}:request{request_id=0}: vector::sinks::util::retries: Non-retriable error; dropping the request. error=Error { code: "AccessDenied", message: "Access Denied",  `

**Comment by jszwedko** [comment]
Hi @rodrigo-garcia-edo !

I think this is related to a couple of existing issues:

* https://github.com/vectordotdev/vector/issues/10870 to have sinks retry all request failures. This is something we will be focusing on in Q3.
* https://github.com/vectordotdev/vector/issues/12145 to ensure that disk buffers don't drop data that wasn't processed successfully by the sink.

I'll close this issue in-lieu of those two, but please feel free to follow along and add any other details there.

> while the disk buffer folder is never cleaned

This should happen eventually, but won't right away. There is a separate compaction process that deletes old data files.

**Comment by rodrigo-garcia-edo** [comment]
Understood.
Do you have at hand the compaction process details?  i didnt success finding documentation (is it configurable?)

Thanks!

**Comment by jszwedko** [comment]
Hi @rodrigo-garcia-edo !

We still have yet to get more complete documentation published for the disk buffers, but you there are some more details about its implementation in https://github.com/vectordotdev/vector/discussions/13001 that might be helpful. Data files should be deleted after all records from them have been processed (errored or not).

**Comment by rodrigo-garcia-edo** [comment]
thanks!
