### ISSUE TITLE
request.headers ignored by healthcheck of elasticsearch sinks

### ISSUE THREAD

**Issue by ypid-work** [vectordotdev/vector#13450]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

https://vector.dev/docs/reference/configuration/sinks/elasticsearch/#request.headers lists:

```json
{
  "Authorization": "${HTTP_TOKEN}",
  "X-Powered-By": "Vector"
}
```

as example. However, for the health check, the request headers are not sent. For `Authorization` it probably makes sense to always send them. I would argue that this is the better/expected behavior when both `request.headers` and `healthcheck` are used.

### Configuration

```text
sources:                                                                                                                                                                                      

  source_stdin:
    type: stdin

sinks:

  sink_elasticsearch_logging_cluster:
    type: 'elasticsearch'
    inputs: ['source_stdin']
    request:
      headers:
        X-Secret: 'my-secret-header'
    endpoint: 'http://localhost:8000'
    bulk:
      index: 'test'
    healthcheck:
      enabled: true
```

### Version

vector 0.23.0 (x86_64-unknown-linux-gnu) (nightly) and 0.22.3 stable

**Comment by jszwedko** [comment]
Ah, good note @ypid-work . Those headers are indeed not sent with healthcheck requests.
