### ISSUE TITLE
`datadog_metrics` sink: Support v2/protobuf API

### ISSUE THREAD

**Issue by prognant** [vectordotdev/vector#13454]
There is a new API ("v2") version for all metrics except sketches (sketches already use the protobuf API).

The `datadog_metrics` should be updated to use it (the `datadog_agent` source already accept incoming request following this API, the protobuf schema is already included in vector source).

**Comment by jszwedko** [comment]
Just dropping a note that we discussed this and think it is ~a half week of work.

**Comment by szibis** [comment]
Any work planned for above ??

**Comment by jszwedko** [comment]
This was actually completed in https://github.com/vectordotdev/vector/pull/18761. It'll be included in the next release (v0.34.0).
