### ISSUE TITLE
Custom path for installer script

### ISSUE THREAD

**Issue by IgnisDa** [vectordotdev/vector#13486]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

The installation script at https://sh.vector.dev is pretty feature complete except it does not allow me to set the installation path. It directly installs to `$HOME/.vector` and adds the `bin` directory to path by modifying bash and zshrc profiles. However this method does not always work for all installations.

For example in a docker alpine environment, I have to do the following:

```dockerfile
RUN apk add --no-cache curl bash && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.vector.dev | bash -s -- -y && \
    cp /root/.vector/bin/vector /usr/bin/vector && \
    chmod +x /usr/bin/vector
```

### Proposal

I suggest the installation script gets a new flag `--bin-dir` which will allow where the bin files get placed. You can see an example from the starship installation script [here](https://github.com/starship/starship/blob/aae1ed04babf4c7d8baaad670c076947d7200675/install/install.sh#L144).

### Version

vector 0.22.3 (x86_64-unknown-linux-gnu)

**Comment by IgnisDa** [comment]
I can make a PR for this if approved

**Comment by jszwedko** [comment]
Hi @IgnisDa ! That is a good idea. We'd be happy to accept a PR for it.

**Comment by IgnisDa** [comment]
@jszwedko Cool will be working on this.

Supplying `--bin-dir` should essentially copy the contents of `$HOME/.vector/bin/*` to the specified location right?

**Comment by jszwedko** [comment]
> @jszwedko Cool will be working on this.
> 
> Supplying `--bin-dir` should essentially copy the contents of `$HOME/.vector/bin/*` to the specified location right?

Yeah, that sounds right to me. Alternatively, you could support for `--prefix` ([that configure scripts often support](https://askubuntu.com/questions/891835/what-does-prefix-do-exactly-when-used-in-configure)) that would put all of the files under the specified prefix. E.g. if I specified `--prefix /usr/local` it would put the binaries under `/usr/local/bin` and the conf files under `/usr/local/etc`.

**Comment by IgnisDa** [comment]
Which of the two would be better? I have implemented `--bin-dir` before, but I like the idea of `--prefix` too, since it won't lead to any confusion as to where the files _other_ than `bin` should be placed.

**Comment by spencergilbert** [comment]
I'd cast my vote for `--prefix` for the same reason you suggested 🙂

**Comment by jszwedko** [comment]
My preference would also be for `--prefix` 😄

**Comment by IgnisDa** [comment]
If i specify prefix to be for example: `/home/ignisda/folder` (ie a directory that is not in path), should it be added to the `.profile`?

**Comment by jszwedko** [comment]
> A solution: we add it to the profile by default and provide an installation flag to disable it.

Yeah, I think you can use the same flag that is already there for that:

```shell
 if [ "$modify_path" = "yes" ]; then
```

**Comment by IgnisDa** [comment]
@jszwedko @spencergilbert I made a PR for the above. Could you please review it? #13618
