### ISSUE TITLE
tls.enabled field for http sink is documented, but does not exist

### ISSUE THREAD

**Issue by tshepang** [vectordotdev/vector#13492]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

> 2022-07-10T10:35:39.101960Z ERROR vector::cli: Configuration error. error=unknown field `enabled`, expected one of `verify_certificate`, `verify_hostname`, `ca_file`, `crt_file`, `key_file`, `key_pass` for key `sinks.out`

Is the [documentation] in error, or is it the sink?

[documentation]: https://vector.dev/docs/reference/configuration/sinks/http/#tls.enabled

### Configuration

```text
[sinks.out]
 inputs = ["foo"]
 type = "http"
 uri = "$URI"
 tls.enabled = true
 tls.ca_file = "/etc/vector/ca.crt"
```

### Version

vector 0.22.3 (x86_64-unknown-linux-gnu)

**Comment by jszwedko** [comment]
Thats @tshepang . This appears to be an issue with the documentation as whether or not TLS is enabled for the `http` sink depends on the scheme of the endpoint (`http://` vs. `https://`).

**Comment by jszwedko** [comment]
I realized this is actually covered by another, more general, issue: https://github.com/vectordotdev/vector/issues/12343 . I'll close this in-lieu of that one but feel free to follow along there. Thanks again!
