### ISSUE TITLE
Allow multiple log field type conversions

### ISSUE THREAD

**Issue by arrrght** [vectordotdev/vector#1350]
May i use one fields in multiple transform?
```
[transforms.some.types]
  timestamp2 = "timestamp|%Y-%m-%d %H:%M:%S%.f"
  timestamp2 = "timestamp|%d.%m.%Y %H:%M:%S"
```

i.e. if first transform type failed then try next
now it just dropped if failed

**Comment by Jeffail** [comment]
Hey @arrrght, unfortunately it's not possible to have duplicate keys within the `types` table as it is invalid TOML. However, we could potentially expand the values to support arrays, where if a conversion fails then the next is attempted, and so on.

Perhaps something like this:

```toml
[transforms.some.types]
  timestamp = [
    "timestamp|%Y-%m-%d %H:%M:%S%.f",
    "timestamp|%d.%m.%Y %H:%M:%S"
  ]
```

We should also capture duplicate keys and report them to the user to make it clear they're being ignored.

**Comment by jszwedko** [comment]
Closing since the `coerce` transform no longer exists. This is possible in VRL using `parse_timestamp` with error handling.
