### ISSUE TITLE
Redis sink still runs health check on startup with healthcheck.enabled = false

### ISSUE THREAD

**Issue by hgiasac** [vectordotdev/vector#13514]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Our system requires exporting logs to multiple sinks. I expect that the vector agent continue to run on startup if one of them is failed to connect to the remote server. However, the Redis sink returns a configuration error and exits. Disabling `healthcheck.enabled=false` doesn't help. 

If the Redis client can connect at startup but loses the connection while running, e.g the Redis server is outage, the client tries to reconnect. That is expected. However, other sinks have to stop ingesting until the Redis sink reconnects. I guess it is because of the Fibonacci backoff behavior of retries https://github.com/vectordotdev/vector/issues/12962. I try to set lower `request.retry_attempts`  and `request.retry_max_duration_secs` values, no luck.

Our team prefers high availability and doesn't want one sink to be the bottleneck of other ones. The workaround is separate each sink into different vector workers. However, it consumes double of resources. Is it possible to make sinks independent of each other that ignore the failure of other sinks?

### Configuration

```text
healthchecks.enabled = false

[sources.docker_logs]
type = "docker_logs"
include_labels = ["vector.enable=true"]

[sinks.redis]
type = "redis"
inputs = ["docker_logs"]
url = "redis://${REDIS_HOST}"
key = "stdout-logs"
data_type = "list"
encoding.codec = "json"
healthcheck.enabled = false

# debug output log
[sinks.print]
type = "console"
inputs = ["docker_logs"]
encoding.codec = "json"
```

### Version

0.23.0

### Debug Output

```text
vector-1  | 2022-07-12T09:51:37.021516Z  INFO vector::app: Log level is enabled. level="vector=trace,codec=trace,vrl=trace,file_source=trace,tower_limit=tra
ce,rdkafka=trace,buffers=trace,kube=trace"
vector-1  | 2022-07-12T09:51:37.021625Z  INFO vector::app: Loading configs. paths=["/etc/vector/vector.toml"]
vector-1  | 2022-07-12T09:51:37.022521Z DEBUG vector::config::loading: No secret placeholder found, skipping secret resolution.
vector-1  | 2022-07-12T09:51:37.023442Z  INFO vector::app: Health checks are disabled.
vector-1  | 2022-07-12T09:51:37.023472Z DEBUG vector::topology::builder: Building new source. component=docker_logs
vector-1  | 2022-07-12T09:51:37.023737Z  INFO vector::sources::docker_logs: Capturing logs from now on. now=2022-07-12T09:51:37.023712633+00:00
vector-1  | 2022-07-12T09:51:37.023793Z  INFO vector::sources::docker_logs: Listening to docker log events.
vector-1  | 2022-07-12T09:51:37.024797Z DEBUG vector::topology::builder: Building new sink component=print
vector-1  | 2022-07-12T09:51:37.024851Z DEBUG vector::topology::builder: Building new sink component=redis
vector-1  | 2022-07-12T09:51:37.024893Z TRACE vector::sinks::redis: Open Redis client.
vector-1  | 2022-07-12T09:51:37.024939Z TRACE vector::sinks::redis: Open Redis client success.
vector-1  | 2022-07-12T09:51:37.024956Z TRACE vector::sinks::redis: Get Redis connection.
vector-1  | 2022-07-12T09:53:53.489753Z TRACE vector::sinks::redis: Get Redis connection success.
vector-1  | 2022-07-12T09:53:53.490269Z ERROR vector::topology: Configuration error. error=Sink "redis": Creating Redis producer failed: Operation timed out
 (os error 110)
vector-1 exited with code 78
```

**Comment by jszwedko** [comment]
Thanks for this report @hgiasac ! I think this is related to the general idea that has been floating around that Vector should be able to start even if if components cannot connect. I created a high-level issue to track this, https://github.com/vectordotdev/vector/issues/13525, so I'll close this in-lieu of that issue. I appreciate all of the context you included here, which helps motivate this direction. Please feel free to track that issue and add any additional thoughts there.
