### ISSUE TITLE
VRL: fallibility / abort type checking incorrect for blocks

### ISSUE THREAD

**Issue by fuchsnj** [vectordotdev/vector#13527]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

This was originally reported in Discord: https://discord.com/channels/742820443487993987/996400622951735437

When calculating the type definition of an expression (with the `Expression::type_def` function) the _final_ state is passed into the function. This means that if there are any assignments inside a block, the previous type of those variables are unknown / incorrect. This can cause issues for both fallibility checking, and early terminations (just the `abort` expression today).

### Incorrect fallibility
```coffeescript
.a = "string"
{
  x = to_string(.a)
  .a = {}
}
```
```text
error[E100]: unhandled error
  ┌─ :2:1
  │
2 │ ╭ ╭ {
3 │ │ │   x = to_string(.a)
4 │ │ │   .a = {}
5 │ │ │ }
  │ ╰─│─^ expression can result in runtime error
  │   ╰─' handle the error case to ensure runtime success
  │
  = see documentation about error handling at https://errors.vrl.dev/#handling
  = learn more about error code 100 at https://errors.vrl.dev/100
  = see language documentation at https://vrl.dev

```

### Incorrect abort
```coffeescript
.a = "string"
{
  x = .a
  .a = abort
}
```
```text
thread 'main' panicked at 'VRL block contains an expression after a terminating expression. This is an internal compiler error. Please submit a bug report.', lib/vrl/compiler/src/expression/block.rs:72:13

```

### Version

0.23.0

**Comment by jszwedko** [comment]
Maybe related? https://github.com/vectordotdev/vector/issues/13378

**Comment by fuchsnj** [comment]
> Maybe related? https://github.com/vectordotdev/vector/issues/13378
These are not related.
