### ISSUE TITLE
Support `auto_extract_timestamp` for `splunk_hec_logs` sink

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#13554]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

A user wants to enable automatic timestamp extraction by Splunk which appears to be possibly by passing `auto_extract_timestamp=true` as an additional query parameter to the [event endpoint](https://docs.splunk.com/Documentation/Splunk/8.0.0/RESTREF/RESTinput#services.2Fcollector.2Fevent) (but notably the raw endpoint does not mention support for this).

### Proposal

We should verify if the raw endpoint does actually support that query parameter. If it does, we can just add another configuration option to the sink to enable it for both. If it doesn't, we may want to model it as a new `target` option that would send to the event endpoint, but with `auto_extract_timestamp=true`.

### Version

vector 0.23.0

**Comment by StephenWakely** [comment]
So can confirm that this works on both event and raw endpoints. I will add `auto_extract_timestamp` as on option on the sink.
