### ISSUE TITLE
vector source: v2 `shutdown_timeout_secs` unused config option

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#13562]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

`shutdown_timeout_secs` is in the source's configuration, but is unused. It's likely been ported from the v1 source but wasn't ever implemented for the new version. I'm not certain it makes sense as an option. We can likely remove this option and rely on global shutdown timers.

### Version

master July 14 2022

**Comment by jszwedko** [comment]
Not a big deal in this case, but in the future, the SHA for the version when building from master is useful :)
