### ISSUE TITLE
unknown variant `loki`, expected `unit_test` for key `sinks.loki`

### ISSUE THREAD

**Issue by happysalada** [vectordotdev/vector#13586]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

undocumented configuration change on vector 0.23.0

### Configuration

```text
❯ ssh yt@10.0.0.148
Last login: Sun Jul 17 18:52:50 2022 from 24.48.87.104

[yt@bee:~]$ cat /nix/store/07i966nw7k0dmllqz7q7z2y1ff5jqhsd-vector.toml
[sinks.loki]
endpoint = "http://localhost:3100"
inputs = ["modify"]
out_of_order_action = "drop"
remove_timestamp = true
type = "loki"

[sinks.loki.encoding]
codec = "json"

[sinks.loki.healthcheck]
enabled = true

[sinks.loki.labels]
level = "{{ level }}"
systemd_unit = "{{ _SYSTEMD_UNIT }}"

[sources.journald]
type = "journald"

[transforms.modify]
inputs = ["journald"]
source = "del(.PRIORITY)\ndel(.SYSLOG_FACILITY)\ndel(.SYSLOG_PID)\ndel(.SYSLOG_TIMESTAMP)\ndel(.SYSLOG_IDESTEMD_SESSION)\ndel(._TRANSPORT)\ndel(._UID)\ndel(.__MONOTONIC_TIMESTAMP)\ndel(.__REALTIME_TIMESTAMP)\ndel(.host)\ndel(.source_type)\nlvl, err = parse_regex(.message, r'le?ve?l=(?P<lvl>\\w+)') \nif err == null {\n  .level = lvl.lvl\n}\nmsg, err = parse_regex(.message, r'me?ss?a?ge?=(?P<msg>.+)')\nif err == null {\n  .message = msg.msg\n}\n"
type = "remap"
```

### Version

0.23.0

### Debug Output

```text
x unknown variant `loki`, expected `unit_test` for key `sinks.loki`
```

### Additional Context

This bug started appearing on the switch from version 0.22.3 to 0.23.0
The configuration was valid, but now isn't anymore.

I've tried to look for this unit_test key, but couldn't find anything in the vector configuration file.

Did something change that wasn't documented ?

**Comment by jszwedko** [comment]
Hi @happysalada !

I wasn't able to reproduce this with Vector version 0.23.0. Based on the error message you have, it seems like the version of Vector you are using might have been compiled without support for the `loki` sink. I see mention of Nix there. Do you know how your version of Vector was built?

**Comment by happysalada** [comment]
On nix, we use the following features
```
 "sinks" "sources" "transforms" "vrl-cli"  "rdkafka?/gssapi-vendored" "unix"
```
I'm verifying right now the version of vector 
`vector 0.23.0 (x86_64-unknown-linux-gnu)`

for reference this was working fine on version 0.22.3, could there have been anything that changed ?

I've got a similar report of someone else with
```
> x unknown variant `http`, expected `unit_test` for key `sinks.logtail`
```

**Comment by happysalada** [comment]
oh before I forget, one warning that I got when building the new version was the following
```
Package `vector v0.23.0 (/build/source)` does not have feature `rdkafka`. It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.
```

I had to replace the flag `rdkafka/gssapi-vendored` with `rdkafka?/gssapi-vendored`. Maybe there are other flags that need to be changed ?

**Comment by jszwedko** [comment]
Thanks for the additional details @happysalada !

There were some dependency changes which include needing to specify `rdkafka?/gssapi-vendored` now rather than `rdkafka/gssapi-vendored`, but I built Vector with:

```
$ cargo build --no-default-features --features  "sinks,sources,transforms,vrl-cli,rdkafka?/gssapi-vendored,unix"
```

and it doesn't seem to have the same issue. Based on yours and the other users' report though, it does sound a lot like Vector is being built without, at least, any of the sink features.

I'm not super familiar with Nix, any chance you could provide the logs from the build? If you wanted, you could also try bisecting down the commits from v0.22.3 and v0.23.0 and see if there is one in particular that causes the package to fail to build. I'm not super familiar with Nix, but I could try building it tomorrow too.

**Comment by happysalada** [comment]
indeed it shows nothing
```
vector list
Sources:

Transforms:

Sinks:
```

**Comment by happysalada** [comment]
just tried the commit from june 30 and had the same error a4ca029eaea4f3a77fa45e2f48b030ee90cc7a87

**Comment by happysalada** [comment]
I've found the issue, it's on our side, sorry for the trouble.
Somehow there is a problem with supplying features with a question mark in them for nix.
I'm looking through to where the problem is.
Thanks a lot for the help!

**Comment by jszwedko** [comment]
Glad you were able to track it down @happysalada !
