### ISSUE TITLE
Http Sink - set HTTP method, set HTTP uri in message

### ISSUE THREAD

**Issue by josepowera** [vectordotdev/vector#13583]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

We must notify downstream servers of processed records (they only accept http Get  method and return http code 204 or http code 200). Calls must be non batched.

We would like to write Http Url into kafka topic (message) and Vector would handle Http calli to remove server.  Remote server Http Urls change to different hostnames, therefore we must allow full http url to be passed in message (we can't have Http Host fixed and  onyl querystring different per message).

### Proposal

Allow to set Url to call in mesage.
Allow to set Http method in message.

**Comment by four-zero** [comment]
This will work for me, but I'm new to rust.

**Comment by jszwedko** [comment]
👍 I'll close this in-lieu of https://github.com/vectordotdev/vector/issues/6759
