### ISSUE TITLE
fix(sink kafka): Lose data when Kafka is down

### ISSUE THREAD

**Issue by KernelErr** [vectordotdev/vector#13714]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Consider the following situation:

File -> Vector -> Kafka

Vector will give an error message when Kafka is down, but the offset will keep going. That will cause if Vector gets restarted at the time, that message didn't send will be lost.

In my test, Fluent Bit and Vector will keep the offset going forward regardless if the message is successfully sent to Kafka.

### Version

vector 0.23.0 (x86_64-unknown-linux-gnu 38c2435 2022-07-11)

**Comment by KernelErr** [comment]
Seems that both Fluent Bit and Vector rely on the `rdkafka` library, wondering if there is a good way to check if the message has been successfully sent. If not, the offset should not be moved.

![image](https://user-images.githubusercontent.com/45716019/180909153-adeb1f89-11b0-4228-9461-9334af1c9617.png)

The offset keeps moving forward at this situation.

**Comment by jszwedko** [comment]
Hi @KernelErr ,

By default, Vector will advance the file offset as it consumes data. There is a new, somewhat experimental, option you can enable on sinks to have any connected sources wait until the sink processed the data: [acknowledgements.enabled](https://vector.dev/docs/reference/configuration/sinks/kafka/#acknowledgements.enabled). Would you want to try that and see if it improves the behavior for you? In the future we want to make that the default behavior, but have some outstanding work to complete first.

**Comment by KernelErr** [comment]
Thanks for your advice. Seems it works! If Kafka is down, the offset will not be moved. We are trying to make the loss of log as less as possible. :)
