### ISSUE TITLE
can't install vector 0.23.0-1 via yum on centos 7

### ISSUE THREAD

**Issue by darjeeling** [vectordotdev/vector#13715]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I can't install vector vector-0.22.3-1.x86_64.rpm on centos 7 system.
```
rpm -Uvh vector-0.23.0-1.x86_64.rpm
Failed dependencies:
	libc.so.6(GLIBC_2.18)(64bit) is needed by vector-0.23.0-1.x86_64
	libstdc++.so.6(CXXABI_1.3.8)(64bit) is needed by vector-0.23.0-1.x86_64
	libstdc++.so.6(GLIBCXX_3.4.21)(64bit) is needed by vector-0.23.0-1.x86_64
```

 but I can install `vector-0.22.3-1.x86_64.rpm` without problem.

### Configuration

```text
No
```

### Version

vector-0.23.0-1.x86_64.rpm

**Comment by jszwedko** [comment]
Hi @darjeeling ! I think this is the same as https://github.com/vectordotdev/vector/issues/13183 . We plan to explore options to link against older libcs to support older OSes. Obviously, if you can upgrade to Centos 8, that would work, but I realize that can be a big ask 😄 I'll close this issue as a duplicate, but please feel free to follow along on that one.
