### ISSUE TITLE
ElasticSearch sink encoder drops the Index field before it can be used in the template

### ISSUE THREAD

**Issue by StephenWakely** [vectordotdev/vector#13728]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Looking at the ElasticSearch sink, the encoder will transform the event [here](https://github.com/vectordotdev/vector/blob/master/src/sinks/elasticsearch/sink.rs#L66) and later on will then process that log entry [here](https://github.com/vectordotdev/vector/blob/master/src/sinks/elasticsearch/sink.rs#L77). Processing the log entry can involve expanding the  `index` template field.

The result is that if the encoder drops any fields (via `only_fields` or `except_fields`) that field will not be able to be used in the template.

We get this error:

```
2022-07-27T10:26:40.589400Z ERROR sink{component_kind="sink" component_id=to_elastic_output component_type=elasticsearch component_name=to_elastic_output}: vector::internal_events::template: Failed to render template for "index"; discarding event. error=Missing fields on event: [".index"] error_type="template_failed" stage="processing" internal_log_rate_secs=30
```

### Configuration

```text
sinks:
  to_elastic_output:
    type: elasticsearch
    inputs:
      - stdin
    endpoint: "http://localhost:9200"
    encoding:
      codec: ndjson
      except_fields:
        - index
    bulk:
      action: index
      index: "{{ .index }}"
```

### Version

v0.23

**Comment by jszwedko** [comment]
Bisected down to bd0bdcd9aeb28850cc8fe0cdd9042a172a9e107c
