### ISSUE TITLE
chore(new_relic sink): add distribution support and send metric type

### ISSUE THREAD

**Issue by tobz** [vectordotdev/vector#13781]
In the `new_relic` sink, among other issues, we currently do not support distributions even though they're supported on the New Relic side. Additionally, we don't send the metric type, which causes all metrics -- counter or gauge -- to be treated as gauges.

We should:
- [ ] #13902
- [ ] #13903
- [x] #13904

**Comment by jszwedko** [comment]
cc/ @asllop . I know you contributed the initial `new_relic` sink so just flagging this in case it is something you are interested to contribute.

**Comment by asllop** [comment]
@jszwedko yes I am! Also interested in https://github.com/vectordotdev/vector/issues/13377, I just don't know when I'm gonna have time to contribute.
