### ISSUE TITLE
Support text delivery for Prometheus remote write sink

### ISSUE THREAD

**Issue by simatos** [vectordotdev/vector#13813]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Vector Prometheus remote write sink deliveries data in snappy/protobuf encoding, but some agents, like VMagent, only received data in text format which leads to errors/incompatibilities. 

Adding the text option will turn the sink more versatile and compatible with more use cases. 

### Version

0.23.0

**Comment by bruceg** [comment]
The remote write protocol is defined through protobuf, which is compressed by snappy. I am aware of no documented alternative encoding described as "remote write" in the context of Prometheus metrics. Can VMagent be configured to have metrics pushed to it in a text form, or would it be configured to scrape an endpoint?

**Comment by zamazan4ik** [comment]
As far as I can understand, Prometheus [Pushgateway](https://github.com/prometheus/pushgateway#put-method) has some kind of fallback from Protobuf-based variant to a text-based: 

> The body of the request contains the metrics to push either as delimited binary protocol buffers or in the simple flat text format (both in version 0.0.4, see the [data exposition format specification](https://docs.google.com/document/d/1ZjyKiKxZV83VI9ZKAXRGKaUKK2BIWCT7oiGBKDBpjEY/edit?usp=sharing)). Discrimination between the two variants is done via the Content-Type header. (Use the value application/vnd.google.protobuf; proto=io.prometheus.client.MetricFamily; encoding=delimited for protocol buffers, otherwise the text format is tried as a fall-back.)

However, I cannot find the information that `vmagent` does not support Protobuf-based messages. @SimaoPedro1 Could you please help with the corresponding links?

Thanks in advance!

**Comment by SimaoPedro1** [comment]
Sorry about the delayed response but somehow i didn't received any notifications.

I was wrong about VMagent. I opened a similar issue [#2931](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2931)  on VictoriaMetrics and it does support protobuf messages.

Also, later i was able to use the prometheus remote write sink with VMagent, but didn't explored further. Probably i had some problem with my network or configuration and misunderstood the problem. 

Thanks for your responses!
