### ISSUE TITLE
array of object not shown on website

### ISSUE THREAD

**Issue by tshepang** [vectordotdev/vector#13880]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

There is no rendering on this link https://vector.dev/docs/reference/configuration/transforms/log_to_metric/#metrics.

The source is at https://github.com/vectordotdev/vector/blob/82ea429a7fe42ce48c5d52dffb2801507c6ca81b/website/cue/reference/components/transforms/log_to_metric.cue#L28.

**Comment by jszwedko** [comment]
Duplicate of https://github.com/vectordotdev/vector/issues/10344
