### ISSUE TITLE
Audit `file` source

### ISSUE THREAD

**Issue by neuronull** [vectordotdev/vector#13887]
- [ ] Refresh configuration documentation: ensure it is accurate and proofread
- [ ] Update examples to be real-world
- [x] Update [component status](https://vector.dev/docs/about/under-the-hood/guarantees/#stability-guarantees) (beta or stable)
- [ ] Ensure `vector generate` generates a valid configuration
- [ ] Document any deprecated metrics on the website
- [ ] For sinks, add a warning to old-style sinks to avoid contributors using them to bootstrap new sinks
- [ ] For sinks, relax allowed input types where possible to match codec support
- [ ] Determine integration test coverage: create an issue if lacking happy or obvious errors paths

Unchanged:
- Component status (stable)

**Comment by hdost** [comment]
Not sure if this is relevant, but is there any plan on having the file source support progress tracking?

**Comment by neuronull** [comment]
> Not sure if this is relevant, but is there any plan on having the file source support progress tracking?

👋  that isn't relevant to this particular issue. In fact, this is stale from a different direction we took to track this, I will likely close this.

I am not aware of nor am I finding an existing GH issue for progress tracking on file source.
I'd recommend opening a feature request issue so we can gauge community demand for this.

**Comment by hdost** [comment]
Created https://github.com/vectordotdev/vector/issues/16393 to followup

**Comment by neuronull** [comment]
Closing this as we created separate issues to track the audit work
