### ISSUE TITLE
healthcheck.uri option for prometheus_remote_write sink 

### ISSUE THREAD

**Issue by johnalotoski** [vectordotdev/vector#13890]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

VictoriaMetrics has a prometheus_remote_write compatible sink endpoint except for the default healthcheck.  A separate sink has previously been requested for it but does not yet exist.

Using the already existing prometheus_remote_write sink type with the victoriametrics write endpoint, the healthcheck will return:
```
ERROR vector::topology::builder: msg="Healthcheck: Failed Reason." error=Unexpected status: 400 Bad Request component_kind="sink" component_type="prometheus_remote_write" component_id=prometheus component_name=prometheus
```

### Attempted Solutions

There is no available `healthcheck.uri` option for this sink, only an enable/disable.  The error can be avoided at the expense of not healthchecking at all.

### Proposal

Add a healthcheck.uri option for the `prometheus_remote_write` sink to enable healthcheck compatibility with the otherwise compatible victoriametrics write endpoint.

### References

https://github.com/vectordotdev/vector/issues/8279
https://github.com/vectordotdev/vector/issues/7998
https://github.com/vectordotdev/vector/issues/6706
https://github.com/vectordotdev/vector/issues/1343
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2253
https://github.com/vectordotdev/vector/issues/15664

### Version

0.21.2

**Comment by jszwedko** [comment]
Rolling into https://github.com/vectordotdev/vector/issues/8279
