### ISSUE TITLE
Remap and Filter in transform not working properly on v0.23.0 and nightly build release

### ISSUE THREAD

**Issue by bachrilq** [vectordotdev/vector#13899]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

So the case is I want to whitelist specific metrics by using metrics name, so other than whitelist metric will drop and not send to Datadog, and I tried using `remap` and `filter` for this case, the configuration is working properly in a lower version like in the version 0.22.3 and below. 

But because I got an issue here https://github.com/vectordotdev/vector/issues/13846, I try using the nightly build release and I don't know why my current config is not working,  I also try on version 0.23.0 the filter, and remap config is not working also. Not working here means no event coming out from the filter. So no metric that send to datadog

- nightly using remap
<img width="718" alt="Screen Shot 2022-08-09 at 13 39 42" src="https://user-images.githubusercontent.com/40727644/183582253-c90be01a-5e89-4fc1-af45-4f7d5582137c.png">

- nightly using filter
<img width="716" alt="Screen Shot 2022-08-09 at 13 35 43" src="https://user-images.githubusercontent.com/40727644/183582274-e961218d-607e-47b6-ac4d-02d1324cd270.png">

- v0.22.3 using remap
<img width="720" alt="Screen Shot 2022-08-09 at 13 40 43" src="https://user-images.githubusercontent.com/40727644/183582305-36902673-ed7b-4bea-8da9-226c8c206053.png">

- v0.22.3 using filter
<img width="715" alt="Screen Shot 2022-08-09 at 13 43 03" src="https://user-images.githubusercontent.com/40727644/183582338-7c1f62d3-8b52-4753-aada-8e161dec13ce.png">

### Configuration

```text
### config that uses remap
## vector.toml
[sources.datadog_agent_forwarder]
type = "datadog_agent"
address = "127.0.0.1:8128"
disable_logs = true
disable_traces = true
multiple_outputs = true

[sinks.datadog_metric]
type = "datadog_metrics"
inputs = ["transform_whitelist_metric"]
api_key = "XXXXXXXXXXXXX"
request.concurrency = "adaptive"

[transforms.transform_whitelist_metric]
type = "remap"
inputs = [ "datadog_agent_forwarder.metrics" ]
file = "/etc/vector/program.vrl"

## program.vrl
list_whitelist_metric=["vector_testing.inc.0testing","vector_testing.inc.2testing"]

if (includes(list_whitelist_metric, .name) == false){
abort
}


### config that uses filter
## vector.toml
[sources.datadog_agent_forwarder]
type = "datadog_agent"
address = "127.0.0.1:8128"
disable_logs = true
disable_traces = true
multiple_outputs = true

[sinks.datadog_metric]
type = "datadog_metrics"
inputs = ["transform_whitelist_metric"]
api_key = "XXXXXXXXXXXXX"
request.concurrency = "adaptive"

[transforms.transform_whitelist_metric]
type = "filter"
inputs = ["datadog_agent_forwarder.metrics"]
condition.type = "vrl"
condition.source = """
includes(["vector_testing.inc.0testing",
"vector_testing.inc.2testing"], .name) """
```

### Version

vector 0.24.0 (x86_64-unknown-linux-gnu 4611307 2022-08-08)

**Comment by tobz** [comment]
Yeah, this is definitely weird and not expected behavior.

We'll investigate.

**Comment by tobz** [comment]
@bachrilq So, this actually _is_ expected, although it's not a bug in the transforms, but a change we made to the `datadog_agent` source. The change was actually meant as a bug fix, which is why we missed documenting it in the upgrade guide... although it has the potential (as we see here) to manifest like a bug for some users. We're going to retroactively update the 0.23.0 upgrade guide to ameliorate that.

Essentially, the change we made was to explicitly parse the namespace of a metric and separate that from the name. When you previously received a metric called `vector_testing.inc.0testing`, the namespace was empty, and the name was `vector_testing.inc.0testing`. Now, in 0.23.0 and above, the namespace would be `vector_testing` and the name would be `inc.0testing`.

In terms of your code examples, you have two options:

- simply drop the `vector_testing.` prefix on the metrics in your allowlist
- join the namespace/name of the metric before checking for inclusion:

```
allowed_metrics = ["...", "..."]
full_metric_name = join([.namespace, .name], ".")
if !includes(allowed_metrics, full_metric_name) {
  abort
}
```

**Comment by bachrilq** [comment]
I see, Thank you for your explanation @tobz, and it seems better if you include this explanation on this [page](https://vector.dev/docs/about/under-the-hood/architecture/data-model/metric/) because I think the difference between `name` and `namespace` is not really clear. Second I want to ask, is there any way to show the metric event that generates by the vector and print it into a log?, so I can show more clearly the data model that generates by the vector, and it will be easier to debug things, Thank you.

**Comment by tobz** [comment]
> I see, Thank you for your explanation @tobz, and it seems better if you include this explanation on this [page](https://vector.dev/docs/about/under-the-hood/architecture/data-model/metric/) because I think the difference between name and namespace is not really clear.

That's a fair point, and I'll open an issue to explore how we can better document the subtleties of how name relates to namespace for metrics. 👍🏻 

> Second I want to ask, is there any way to show the metric event that generates by the vector and print it into a log?, so I can show more clearly the data model that generates by the vector, and it will be easier to debug things, Thank you.

The easiest way to inspect events is to use the `console` sink, with the encoding codec set to JSON. This will expose the fields of the metric, including name, namespace, type, and so on.

**Comment by bachrilq** [comment]
I see, thank you for your clear explanation @tobz 🙏

**Comment by spencergilbert** [comment]
Driving by to note if you've enabled the `api` for Vector `vector tap` could print the events without having to include a new sink 👍

**Comment by bachrilq** [comment]
Wow great! , nice feature, I just know that feature, thank you for your suggestion @spencergilbert 👍
