### ISSUE TITLE
Remove requirement of setting AWS env vars for integration tests

### ISSUE THREAD

**Issue by lukesteensen** [vectordotdev/vector#1390]
New contributors run into this because it isn't documented anywhere, but we should be able to remove the requirement completely.

**Comment by LucioFranco** [comment]
Yeah, I have this issue a lot, I'm not sure exactly how we may want to go about it but one idea would be to actually have our own implementation of a rusoto provider. Internally, it would wrap DefaultCredentialsProvider but during `cfg(test)` would swap it out for fake credentials?

**Comment by jszwedko** [comment]
These don't appear to be required anymore.
