### ISSUE TITLE
[new_relic sink] send distributions to New Relic

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#13904]

**Comment by asllop** [comment]
Distribution metrics are not actually supported by the New Relic Metric API. Internally, New Relic can handle this type of metrics (https://docs.newrelic.com/docs/data-apis/understand-data/metric-data/metric-data-type/), but the API only allows injecting gauge, count and summary metrics (https://docs.newrelic.com/docs/data-apis/ingest-apis/metric-api/report-metrics-metric-api/#send-metric-data).

**Comment by jszwedko** [comment]
Aha, you are right @asllop . I'll mark this as closed then.

**Comment by asllop** [comment]
@jszwedko I think this issue should be closed for the reasons exposed in my previous comment.
