### ISSUE TITLE
[new_relic sink] actually set the metric type in the metrics API model object

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#13903]

**Comment by asllop** [comment]
The models for count metrics are different in New Relic and Vector. While New Relic expects it to contain an `interval.ms` field, that is, the time during which the metric has been counted, there is no such field in Vector. Looks like for Vector, a count metric represents a single point in time, an event that makes a counter increment or reset. For New Relic, a count metric represents an accumulation of increments that happened during a time interval, and always resets to zero automatically after it is sent. The concepts are different, and thus, I don't think we can directly translate Vector count metrics to New Relic.

For more info on New Relic metric model:

https://docs.newrelic.com/docs/data-apis/understand-data/metric-data/metric-data-type/

**Comment by asllop** [comment]
@jszwedko please correct me if I'm wrong regarding how Vector count metrics work.

**Comment by jszwedko** [comment]
Thanks @asllop ! I'm actually curious what @bruceg or @tobz thinks here since they are more familiar with our metrics data model.

**Comment by bruceg** [comment]
We do have a metric normalizer layer for all metrics sinks that can convert any absolute metrics (including counters) into incremental values. We can easily setup this layer to convert counters to incremental values. For the interval, It sounds like storing the previous request time and emitting the difference between that and now may be sufficient, as that would be interval over which the counter has accumulated.

**Comment by asllop** [comment]
@bruceg does Vector provide types for this specific task? Any usage example I can see in other components? Or is it something I have to implement in my side?
