### ISSUE TITLE
Advanced replace with regex and encryption

### ISSUE THREAD

**Issue by ccamachofg** [vectordotdev/vector#13916]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When using the replace function with regex and capture groups plus applying encryption/encoding to one of the capture groups, the output is not the expected one.

**Note:** I am not sure if calling a function from within a function is a supported feature of VRL of if my behavior is the expected one.

## Example
I try to put just a simple event of what I am trying to accomplish

**Event**:
`2022-08-10 08:05:26.092 [INFO][8] felixnodeprocessor.go 215: Old CIDRS: []`

I want to capture the text `felixnodeprocessor`, keep the prefix `felix` and the suffix `processor`, and encrypt the text `node`. To do so I am using the following remap transform:

```
key = "12345678901234567890123456789012"
iv = "1234567890123456"
.message = replace!(.message, r'(?P<x>felix)(?P<y>node)(?P<z>processor)', "$$x" + encode_base64(encrypt!("$$y", "AES-256-CBC-PKCS7", key, iv: iv)) + "$$z")
```
**Output:**
`2022-08-10 08:19:29.813 [INFO][8] +NWARaHXzOn+w==processor.go 215: Old CIDRS: []`
**Expected Output:**
`2022-08-10 08:19:29.813 [INFO][8] felix+NWARaHXzOn+w==processor.go 215: Old CIDRS: []`

### Configuration

```text
sources:
  in_datadog_agent:
  type: datadog_agent
  address: "0.0.0.0:8080"

transforms:
  pdp:
    type: remap
    inputs:
      - in_datadog_agent
    source: |
      .ddtags = string!(.ddtags) + ",sender:vector"
      key = "12345678901234567890123456789012"
      iv = "1234567890123456"
      .message = replace!(.message, r'(?P<x>felix)(?P<y>node)(?P<z>processor)', "$$x" + encode_base64(encrypt!("$$y", "AES-256-CBC-PKCS7", key, iv: iv)) + "$$z")     

sinks:
  out_datadog:
    type: datadog_logs
    inputs:
      - pdp
    default_api_key: "${DD_API_KEY}"
    compression: gzip
    encoding:
      codec: json
```

### Version

vector 0.22.2 (x86_64-unknown-linux-gnu 0024c92 2022-06-15)

### Example Data

2022-08-10 08:05:26.092 [INFO][8] felixnodeprocessor.go 215: Old CIDRS: []

### Additional Context

Vector is running as a statefulset inside k8s, but no special configuration.

**Comment by tobz** [comment]
@ccamachofg

Firstly, regarding your experience with the replacement value not looking as you expect, this is related to a lack of escaping the capture group references.

The regular expression is getting confused when it tries to render your replacement string -- `"$$x+NWARaHXzOn+w==$$z"` -- as it thinks two capture capture group references exist: `x+NWARaHXzOn+w==` and `z`. This can be solved simply by escaping the references with curly braces, like so: `"$${x}" + encode_base64(encrypt!("$$y", "AES-256-CBC-PKCS7", key, iv: iv)) + "$${z}"`. Doing so will get you something closer to the expected output: `felixmxV7GWK9+5nanosLFCzGwg==processor.go`.

I've opened https://github.com/vectordotdev/vector/issues/13949 to make sure we update the documentation/examples to show and explain this better.

Secondly, I understand your desire to use a VRL function to feed the replacement value. Unfortunately, this is not currently possible and it's not clear how easily we could implement such a feature.

I can think of a few ways to achieve this today using slightly suboptimal VRL, but it would depend on the nature of your input:

- are you matching multiple lines at a time?
- does a line only ever have one of these identifiers that you need to match?
- is the `node` part actually static or will you end up wanting to do something like `felix(?P<id>[a-z]+)processor`?

If you can provide me a bit more of that information, I can try and help craft an example for you.

**Comment by ccamachofg** [comment]
Hello @tobz,

Thanks a lot for your response, it makes it way clearer. I was able to use the matching groups with the scape characters and I am getting a better result.

When using `.message = replace!(.message, r'(?P<x>felix)(?P<y>node)(?P<z>processor)', "$${x}" + encode_base64(encrypt!("$${y}", "AES-256-CBC-PKCS7", key, iv: iv)) + "$${z}" )` I get: `felixgkm5lJ5HPIWOhtSewl9YMQ==processor.go`. Which looks better, since I get my prefix and suffix correctly, however the encrypted/encoded value ends up being `${y}` and not the actual captured word: `node`. 

I was not able to get the expected output `felixmxV7GWK9+5nanosLFCzGwg==processor.go`. Not sure if you were able to make it work, but I guess this is because of what you mentioned: _"I understand your desire to use a VRL function to feed the replacement value. Unfortunately, this is not currently possible and it's not clear how easily we could implement such a feature."_

To answer your questions:
- Yes, we have events that can have multiple lines.
- Normally each line has one identifier, but other lines can match another identifier
- It would definitely not be static, our actual regexes will have more than one dynamic capture group. They look more like this `(12[0-9]{2})([0-9]{12})([0-9]{2}[Ff0-9]{0,2})`

For now what I have somewhat working is the following:

This is of course not good enough since I am only replacing one match, I suppose my first replace is only assigning the last match to `test`
```
test = replace!(.message, r'.*(?P<x>felix)(?P<y>node)(?P<z>processor).*', "$${x}," + "$${y}," + "$${z}")
pd = split(test, ",")
pd_clear = join!(pd)
pd[1] = encode_base64(encrypt!(pd[1], "AES-256-CBC-PKCS7", key, iv: iv))
.message = replace!(.message, pd_clear, join!(pd, separator: "|"))
```

I really appreciate if you are able to come back with another example on how to achieve this

**Comment by tobz** [comment]
Right, so capture group references can only be resolved in the overall string passed as the replacement value, so `encrypt!` will never get `node`, only `$${y}`.

I do have some thoughts on how to achieve this with VRL as-is. Using your example regex pattern, and with a warning that I actually haven't fully tested this VRL:

```
iv = "..."
key = "..."

# First, find all instances of a match in our message. This gives us a array of objects,
# where the object contains all of the capture groups for the individual match:
eligible_matches = parse_regex_all!(.message, r'12[0-9]{2}(?P<encrypt>[0-9]{12})[0-9]{2}[Ff0-9]{0,2}')

# Next, we replace all of the matches we found with the encrypted version:
for_each(eligible_matches) -> |_index, captures| {
  # `needle` is the original string, which in the case of our regular expression,
  # would be something like "123411122233344411F4", and the part we want to
  # encrypt -- "111222333444" -- is in the named capture group `encrypt`.
  needle = captures.0

  # Now we generate a replacement for `needle`, which in this case, simply involves
  # encrypting the match in the named capture group `encrypt`, but this would be
  # where you generate whatever the original `needle` should be replaced with.
  encrypted_needle = replace(needle, captures.encrypt, encode_base64(encrypt!(captures.encrypt, "AES-256-CBC-PKCS7", key, iv: iv)))

  # Now we simply replace `needle` with `encrypted_needle` in our original message:
  .message = replace(.message, needle, encrypted_needle)
}
```

It was only as I was writing this example that I realized my original thought of how complicated this would be was not the only way to solve it, and that it could be done in this much simpler way. It's also fairly portable: you just need a capture group(s) around the individual parts that need to be encrypted/modified via VRL.

**Comment by ccamachofg** [comment]
Hello @tobz,

Thanks a lot for your response!

I had to do some syntax fixes, but your code pretty much worked, here is the code that worked:

```
# Added `numeric_groups: true` so the function returns the `0` capture group
eligible_matches = parse_regex_all!(.message, r'12[0-9]{2}(?P<encrypt>[0-9]{12})[0-9]{2}[Ff0-9]{0,2}', numeric_groups: true)

for_each(eligible_matches) -> |_index, captures| {
  needle = captures."0"  # Need to use quotes to be able to access capture group `0`
  
  # For the next 2 assignments I had to use `!`, otherwise I get `this expression is fallible` errors
  encrypted_needle = replace!(needle, captures.encrypt, encode_base64(encrypt!(captures.encrypt, "AES-256-CBC-PKCS7", key, iv: iv)))  
  .message = replace!(.message, needle, encrypted_needle)
}
```

I will have to do some performance tests to validate if this will be good enough for our use case, but I think for now this is good enough for me.

I really appreciate the time you took to help me troubleshoot and the proposed solution

**Comment by tobz** [comment]
@ccamachofg Nice, glad you were able to get to a workable solution. :)
