### ISSUE TITLE
file source does not enforce `include` field

### ISSUE THREAD

**Issue by tshepang** [vectordotdev/vector#13943]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I missed adding `include` field and did not get a warning/error, even though [it's marked as required](https://vector.dev/docs/reference/configuration/sources/file/#include).

### Configuration

```text
data_dir = "/tmp"

[sources.in]
 type = "file"

[sinks.out]
 inputs = ["in"]
 type = "console"
 encoding.codec = "text"
```

### Version

vector 0.23.3 (x86_64-unknown-linux-gnu af8c9e1 2022-08-10)

**Comment by spencergilbert** [comment]
cc @neuronull, who identified this during component auditing but I don't believe had opened an issue.

**Comment by neuronull** [comment]
> cc @neuronull, who identified this during component auditing but I don't believe had opened an issue.

Thanks for the tag- correct I did not open an issue, but plan to address this as part of the file source audit. Assigned to myself.
