### ISSUE TITLE
there is no coercer transform

### ISSUE THREAD

**Issue by tshepang** [vectordotdev/vector#13941]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

https://vector.dev/docs/about/under-the-hood/architecture/data-model/log/#timestamp-coercion talks about a coercer transform. I suspect this is now `to_timestamp`?

**Comment by jszwedko** [comment]
Good catch, thanks @tshepang . We missed updating that doc when the transform was removed. `parse_timestamp` is its replacement.
