### ISSUE TITLE
Kafka consumer group lag internal metric

### ISSUE THREAD

**Issue by rsilvasu** [vectordotdev/vector#13987]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Currently Vector is getting the Statistics from librdkafka: https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md as internal_events: https://github.com/vectordotdev/vector/blob/ba1e1c404f1278316cc55931cf4d3d620f5a536c/src/internal_events/kafka.rs#L112-L151

One of the key metrics of a kafka consumer is the lag, which is not included on the internal_events but is currently available with the current implementation.

As discussed via discord with @JeanMertz , is needed to:

- need to iterate over the provided topic metrics: https://docs.rs/rdkafka/0.28.0/rdkafka/statistics/struct.Statistics.html#structfield.topics

- Then iterate over the partitions of each topic: https://docs.rs/rdkafka/0.28.0/rdkafka/statistics/struct.Topic.html#structfield.partitions

- And then finally, for each partition, expose the consumer_lag metric: https://docs.rs/rdkafka/0.28.0/rdkafka/statistics/struct.Partition.html#structfield.consumer_lag

### Version

0.23

**Comment by fpytloun** [comment]
Would be great. Now it requires some other service to be able to have lag metrics, eg. kafka-lag-exporter. 
BTW this issue si probably duplicate or related: https://github.com/vectordotdev/vector/issues/12182

**Comment by zamazan4ik** [comment]
@fpytloun Am I right, that the required in the issue metric is named `kafka_consumergroup_group_lag ` in kafka-lag-exporter?

**Comment by fpytloun** [comment]
@zamazan4ik I think there are two metrics, one is lag in number of messages and second is time.

**Comment by zamazan4ik** [comment]
@fpytloun you are right. As a part of the corresponding PR I've implemented only the metric regarding lag in number of messages. Are you interested in the lag in seconds too? If yes, I guess I could easily add it in another PR.

**Comment by fpytloun** [comment]
@zamazan4ik Yes, I think that metric is also very interesting 🤔
