### ISSUE TITLE
Elasticsearch Sink Issue

### ISSUE THREAD

**Issue by ztroop** [vectordotdev/vector#14025]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I'm seeing an error `Action/metadata line [1] contains unknown parameter [_type]` while trying to use the `elasticsearch` sink after upgrading our ELK stack to `8.2.2`. Looks like `_type` was deprecated and ultimately removed. I tried removing `mode = "bulk"` but I still get the same issue. 

See configuration for the sink configuration and debug for the full error message.

### Configuration

```text
[sinks.out]
type = "elasticsearch"
inputs = ["in"]
endpoint = "localhost:9200"
mode "bulk"
compression = "none"
```

### Version

vector 0.21.0 (x86_64-unknown-linux-gnu c1edb89 2022-04-14)

### Debug Output

```text
ERROR sink{component_kind="sink", component_type=elasticsearch, component_name=out}:request{request_id=0}: vector::internal_events::elasticsearch: Reponse failed. error_code=http_response_400 error_type="request_failed" stage="sending" response=Response { status: 400, version: HTTP/1.1, headers: {"x-elastic-product": "Elasticsearch", "content-type": "application/json;charset=utf-8", "content-length": "261"}, body: b"{\"error\":{\"root_case\":[{\"type\":\"illegal_argument_exception\",\"reason\":\"Action/metadata line [1] contains unknown parameter [_type]\"}]
```

**Comment by spencergilbert** [comment]
👋, 
[suppress_type_name](https://vector.dev/docs/reference/configuration/sinks/elasticsearch/#suppress_type_name) should be used after ES 7/8 to remove this field, we'll eventually default to this but have kep it in for backwards compatibility.
