### ISSUE TITLE
(master branch)Grok without GREEDYDATA will caught: unable to parse grok: value does not match any rule

### ISSUE THREAD

**Issue by honganan** [vectordotdev/vector#14060]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I built a new package from master(commit id:8e2201bcfd7b7ec460d783ed8b8489cafef55902) and found I have to add `%{GREEDYDATA}` after my grok pattern or the `parse_grok` will run fails with: `unable to parse grok: value does not match any rule`. 

This only happens on my built from master, and it works fine on release `0.23.3`. I think there may be some behavior changes in `parse_grok` and we may need to mention it in next versions document.

> PS: My old grok pattern did not match all parts of provided string

My pattern before:
```
.parsed,err = parse_grok(
    .message,
    "%{TIMESTAMP_ISO8601:time} %{WORD:level} \\[?(?<infoType>\\w+)\\]? (?<requestId>\\S+) (?<appId>\\S+) %{IP:remoteIp} %{WORD:method} %{NUMBER:statuCode} %{HOSTNAME:remoteHost} (?<remotePath>\\/\\S*)
)
```

The message field is:
```
2022-08-23T03:07:17.012 INFO request xxxxxxxxxx xx.common 115.201.168.122 GET 200 xx.xx.com /global/api/xxx xx.common 33 243535 {} {"host":"xx.xx-prod-base.svc","appID":"xx.common"}
```

After I Added `%{GREEDYDATA}` it works ok:
```
. |= parse_grok!(
    .message,
    "%{TIMESTAMP_ISO8601:time} %{WORD:level} \\[?(?<infoType>\\w+)\\]? (?<requestId>\\S+) (?<appId>\\S+) %{IP:remoteIp} %{WORD:method} %{NUMBER:statuCode} %{HOSTNAME:remoteHost} (?<remotePath>\\/\\S*) %{GREEDYDATA}"
)
```

Both of the patterns have been tested successfully at:https://grokdebug.herokuapp.com/

### Version

Self built from master source (commit id:8e2201bcfd7b7ec460d783ed8b8489cafef55902)

**Comment by honganan** [comment]
Seems grok matching becomes from greedy to non-greedy.

**Comment by honganan** [comment]
@spencergilbert Does it have relationship with [13008](https://github.com/vectordotdev/vector/pull/13008) ?

**Comment by fuchsnj** [comment]
This is the commit that introduced the regression: https://github.com/vectordotdev/vector/commit/97ccda4bebd75e2a9b567071a1eb77c537b0a6b9

**Comment by honganan** [comment]
I'm not very clear to understand your statement, means code version before the commit should works?

**Comment by honganan** [comment]
> This is the commit that introduced the regression: [97ccda4](https://github.com/vectordotdev/vector/commit/97ccda4bebd75e2a9b567071a1eb77c537b0a6b9)

I'm not very clear to understand your statement, means code version before the commit should works?

**Comment by jszwedko** [comment]
> > This is the commit that introduced the regression: [97ccda4](https://github.com/vectordotdev/vector/commit/97ccda4bebd75e2a9b567071a1eb77c537b0a6b9)
> 
> I'm not very clear to understand your statement, means code version before this commit should works?

That's correct. We are looking into resolving this issue for v0.24.0. Thanks for reporting it!
