### ISSUE TITLE
Verify `prometheus_exporter` sink

### ISSUE THREAD

**Issue by prognant** [vectordotdev/vector#14077]
- [x] Verify internal event processing metrics are tested via `assert_X_compliance` test helpers
- [ ] Update `component_discarded_events_total` to match the new [instrumentation spec](https://github.com/vectordotdev/vector/blob/master/docs/specs/instrumentation.md#eventsdropped) by adding `reason` to the emitted logs, and `intentional` to emitted logs and metrics
- [ ] Verify that the component correctly emits the correct error events per the [component spec](https://github.com/vectordotdev/vector/blob/master/docs/specs/instrumentation.md#events)

**Comment by prognant** [comment]
`component_discarded_events_total` does not apply for this kind of sink that should be pulled by an external consumer.

**Comment by jszwedko** [comment]
@prognant I think this sink can actually discard events if the incoming metric cannot be normalized:

https://github.com/vectordotdev/vector/blob/553763f6ed37f1bfda7655f9aa6679e2423d27f9/src/sinks/prometheus/exporter.rs#L557-L578 (note there is no `None` arm)

I'll reopen this, but let me know if I'm wrong.

**Comment by jszwedko** [comment]
👍 makes sense. Maybe it still make sense to guard against it in the future in case we start returning `None` there and forget to cover it?

**Comment by neuronull** [comment]
I gave this a look over. It seems like with 14227 merged in, that this can be closed now.
