### ISSUE TITLE
Verify `pulsar` sink

### ISSUE THREAD

**Issue by prognant** [vectordotdev/vector#14096]
- [x] Verify internal event processing metrics are tested via `assert_X_compliance` test helpers
- [x] Update `component_discarded_events_total` to match the new [instrumentation spec](https://github.com/vectordotdev/vector/blob/master/docs/specs/instrumentation.md#eventsdropped) by adding `reason` to the emitted logs, and `intentional` to emitted logs and metrics
- [ ] Verify that the component correctly emits the correct error events per the [component spec](https://github.com/vectordotdev/vector/blob/master/docs/specs/instrumentation.md#events)

**Comment by prognant** [comment]
Encoding failure are the only non-recoverable, thus `component_discarded_events_total` matches the new instrumentation spec thanks to #14021.

**Comment by jszwedko** [comment]
@prognant I think the `pulsar` sink is not emitting an error whenever the send fails?

https://github.com/vectordotdev/vector/blob/553763f6ed37f1bfda7655f9aa6679e2423d27f9/src/sinks/pulsar.rs#L359-L363

I'll reopen, but let me know if I'm wrong.
