### ISSUE TITLE
Support multiple `access_key` tokens in `aws_kinesis_firehose` source

### ISSUE THREAD

**Issue by tim-klarna** [vectordotdev/vector#14106]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

There are two security based use-cases for this:

1. Password Rotation (new access_key's must be added without invalidating the old ones, until no old ones are in use anymore)
2. No Shared Secrets (Support authorization from multiple different sources without having to share secrets between these. E.g. think of different customers each configuring a Firehose to send data to a provider's vector cluster. The current approach requires giving all customers the same access_key.)

### Proposal

Implement support for multiple tokens, inline with https://vector.dev/docs/reference/configuration/sources/splunk_hec/, which also does this.

**Comment by dizlv** [comment]
Hey @jszwedko I've drafted [PR](https://github.com/vectordotdev/vector/pull/15828) for this feature, can you take a quick look if I'm moving to the right direction? Thank you! 👀

**Comment by spencergilbert** [comment]
Closed as of #15828 - thanks again @dizlv!
