### ISSUE TITLE
Verify `sematext_logs` sink

### ISSUE THREAD

**Issue by prognant** [vectordotdev/vector#14142]
- [x] Verify internal event processing metrics are tested via `assert_X_compliance` test helpers
- [x] Update `component_discarded_events_total` to match the new [instrumentation spec](https://github.com/vectordotdev/vector/blob/master/docs/specs/instrumentation.md#eventsdropped) by adding `reason` to the emitted logs, and `intentional` to emitted logs and metrics
- [x] Verify that the component correctly emits the correct error events per the [component spec](https://github.com/vectordotdev/vector/blob/master/docs/specs/instrumentation.md#events)

**Comment by neuronull** [comment]
This sink is a wrapper on the elastic search sink which is already covered in the audit list.

It's unit tests are already using the compliance helpers.

I see no additional error / events dropped areas.
