### ISSUE TITLE
Add support for transforming traces into metrics

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#14154]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Proposal

The `log_to_metric` takes a stream of log events and drives metrics from those events. No such functionality exists for trace events. However, since trace events are currently effectively equivalent to log events, it should be trivial to provide the same functionality, either in a new transform or by updating (and renaming) `log_to_metric` to accept traces as well.

### References

[Request on Discord](https://discord.com/channels/742820443487993987/746070604192415834/1013870497001390120):
> Hey team! Any plans to create a trace_to_metric transform plug? We'd like to generate some metrics from traces. Any way we can do this?

**Comment by yocca** [comment]
Related to #12710

**Comment by bruceg** [comment]
Believe it or not, I searched for that before typing up this issue, but didn't find it. As that is a much more comprehensive discussion of this issue, I'll close this in favor of continuing there.
