### ISSUE TITLE
expire_metrics is expected as struct Duration, not integer

### ISSUE THREAD

**Issue by tuananhnguyen-ct** [vectordotdev/vector#14188]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The [documentation](https://vector.dev/docs/reference/configuration/global-options/#expire_metrics) states that in the config, expire_metrics is uint

When specifying expire_metrics as integer (60), vector validation failed with error 
```
invalid type: integer `60`, expected struct Duration
```

Setting expire_metrics to `{ secs: 3600, nanos: 0 }` works.

Either the documentation should specify the data type correctly, or expire_metrics should be accept as integer.

### Version

0.24

**Comment by jszwedko** [comment]
Thanks for this report @tuananhnguyen-ct ! It's definitely the intention that it is a number of seconds.
