### ISSUE TITLE
Verify `aws_kinesis_firehose` source

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#14194]
- [x] Verify internal event processing metrics are tested via `assert_X_compliance` test helpers
- [x] Update `component_discarded_events_total` to match the new [instrumentation spec](https://github.com/vectordotdev/vector/blob/master/docs/specs/instrumentation.md#eventsdropped) by adding `reason` to the emitted logs, and `intentional` to emitted logs and metrics
- [x] Verify that the component correctly emits the correct error events per the [component spec](https://github.com/vectordotdev/vector/blob/master/docs/specs/instrumentation.md#events)

**Comment by spencergilbert** [comment]
Source appears to only drop events when failing a send, otherwise we don't receive events at all.

**Comment by jszwedko** [comment]
@spencergilbert did you verify the error events too? That is, the ones that emit `component_errors_total` (or if any are missing).

**Comment by spencergilbert** [comment]
> @spencergilbert did you verify the error events too? That is, the ones that emit `component_errors_total` (or if any are missing).

Yep, the two "custom" internal events that emit errors have all the properties from the spec 👍
