### ISSUE TITLE
Invalid custom_tags metrics from sinks datadog_metric

### ISSUE THREAD

**Issue by bachrilq** [vectordotdev/vector#14239]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

So I compare the resulting metric between Datadog Agent and Datadog Agent through Vector. The details are like this:
1. Metrics > Datadog Agent > Datadog Server
2 Metrics > Datadog Agent > Vector > Datadog Server

and I found a difference in datadog custom_tags between the two methods: 
1. the first difference is when sent custom_tags without a key, the vector automatically adds `:` at the end of `custom_tags`, for example when not using vector the custom_tags is `valid_error` but when using vector the custom tag changes into `valid_error:`

- not using vector
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/40727644/187859528-e0921a17-3b22-4fda-b16b-e79bac25b323.png">

- using vector
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/40727644/187860107-f18ab846-81e2-4850-b3da-cd19d0df7c3d.png">

- not using `from`
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/40727644/187859906-5e3e0f04-2bf7-40ce-a34e-b22c91a45928.png">

2. the second issue is when using vector somehow there are one custom_tags that is highest than the other, and it seems the vector overwrites other custom_tags. for example we have metric `gql_per_service_call_rate` and have custom_tag with the key is `service`  and have 184 value. like `service:A-1-service`, `service:B-2-service` until `service:B-184-service`, but when using vector there is one custom_tags got the highest than other, and It makes seems the another `custom_tags` service is like going down because there are no metrics for that service. 

- as you can see in this picture when using the vector,  custom_tags `service:ta` is going the highest, but after disabling the vector, the metric goes normal again, we already double the check service that is going down or not when we use the vector, and it turns out the service is fine, but the metrics are wrong
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/40727644/187877600-684b3ac2-6c5d-4d33-a82f-f42d7d38ad89.png">

### Configuration

```text
## vector.toml
# vector source
[sources.datadog_agent_forwarder]
type = "datadog_agent"
address = "127.0.0.1:8128"

[transforms.transform_whitelist_metric]
type = "remap"
inputs = [ "datadog_agent_forwarder" ]
file = "/etc/vector/program.vrl"

# Print parsed logs to
[sinks.datadog_metric]
type = "datadog_metrics"
inputs = ["transform_whitelist_metric"]
api_key = "###############"
request.concurrency = "adaptive"
buffer.type = "memory"
buffer.max_events = 100000

[api]
enabled = true
address = "127.0.0.1:8686"


## program.vrl
list_whitelist_metric=[
"vector_testing.gauge.0testing",
"gql_per_service_call_rate"]

full_metric_name,err = join([.namespace, .name], ".")
if !includes(list_whitelist_metric, full_metric_name){
abort
}
```

### Version

`vector 0.24.0 (x86_64-unknown-linux-gnu 43267b9 2022-08-30)`  and `vector 0.24.0 (x86_64-unknown-linux-gnu 4611307 2022-08-08)`

**Comment by bachrilq** [comment]
dfd

**Comment by jszwedko** [comment]
Rolling this into https://github.com/vectordotdev/vector/issues/14742
