### ISSUE TITLE
Lack of resilience for Kafka sink ?

### ISSUE THREAD

**Issue by Momotoculteur** [vectordotdev/vector#14259]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hello guys !

I'm using Vector with Kafka sink, and try to simulate loss of connectivity. I use the disk buffer, and have data written in perfectly. When i re-up my connectivity, i expect to get all my previous data in output of my kafka sink. The problem is regardless of the time i cut the connectivity, i have only the latest logs of the last ~5 minutes. So if my connectivity is down for less than 5min i have all my logs. Up than 5 minutes, i have nothing since my disconnection.

My disk buffer is large enougth for this amount of logs.

Feel free if you want more details about my configuration.

Have a great day,
Bastien.

### Configuration

```text
sources:
    vector_source:
      type: vector
      address: 0.0.0.0:9000
      version: "1"

  sinks:
    eventhub_sink:
      type: kafka
      buffer:
        type: "disk"
        max_size: 1073741824
      inputs:
        - vector_source
      encoding: json
      bootstrap_servers: <my_server>
      topic: <my_topic>
      sasl:
        enabled: true
        mechanism: "PLAIN"
        username: <my_username>
        password: <my_password>
      healthcheck: true
      compression: none
      librdkafka_options:
        "security.protocol": sasl_ssl
```

### Version

0.23.0-distroless-static

**Comment by jszwedko** [comment]
Hi @Momotoculteur !

Thanks for this report. Sorry for the delay in response. A few things:

* Could you share the Vector log output too?
* Could you try monitoring the internal buffer metrics to see if the buffer is filling up more quickly than you expect? You con use the `internal_metrics` source and pipe the output to a `console` sink or to a `promotheus_exporter` sink and configure a local Prometheus to collect it for graphing
* I noticed your data source is a `vector` source. I assume there is another Vector instance sending data to it? Could you provide the config for it as well? I'm wondering if it is the upstream Vector instance that is dropping data.
* I noticed you are using version `1` of the `vector` source. Could you try version `2`? Version `1` is a simple TCP socket that doesn't provide any feedback to clients.

**Comment by jszwedko** [comment]
Closing due to lack of response, but please feel free to reopen this if you are still encountering this issue. Or if anyone else is, please leave a comment.
