### ISSUE TITLE
Create a wrapper type for sensitive string data.

### ISSUE THREAD

**Issue by tobz** [vectordotdev/vector#14260]
## Context

As part of the ongoing configuration schema work, we've identified a common pattern of having configuration fields that carry sensitive data -- passwords, API tokens, and so on -- but have no easy way to identify themselves as being sensitive information.

This can be a problem for a few reasons:

- the configuration schema won't expose this, which makes using it to generate context-aware warning labels, or hiding of values in UIs/forms based on the schema, a manual process, which is prone to error
- we may unintentionally emit these strings into logging since they are generally using `String` which will show up in both `Display` and `Debug`-based usages

## Solution

We should introduce a newtype wrapper, tentatively called `SensitiveString`, which wraps a `String` internally and has the following characteristics:

- (de)serializes as a `String` (drop-in compatible with `String` for `serde` purposes)
- sets `configurable`-based metadata to indicate that it is a "sensitive" string
- `Display` and `Debug` implementations that emit `**REDACTED**`, or some sentinel value like that
- no implicit `Deref` implementations, to avoid unwittingly exposing the value
- dedicated accessors to pair with the above, such that users has to consciously make an effort to get the value out, forcing them to deal with the value in a way that makes it more obvious why the type is being used

**Comment by jszwedko** [comment]
Closed as this was implemented by the introduction of `SensitiveString`.
