### ISSUE TITLE
unable to load lua dependancy

### ISSUE THREAD

**Issue by khaskelbergTAU** [vectordotdev/vector#14271]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

im trying to load the luaredis dependancy to the lua transform.
its crashing in runtime when trying to import luasocket, with the error:

runtime error: error loading module 'socket.core' from file '/usr/local/lib/lua/5.4/socket/core.so':
        /usr/local/lib/lua/5.4/socket/core.so: undefined symbol: luaL_setfuncs

(full error in debug output)

### Configuration

```text
[sources.generate_syslog]
type = "demo_logs"
format = "syslog"

[transforms.lua_stuff]
inputs = [ "generate_syslog"]
type = "lua"
version = "2"
source = """
redis = require 'redis'
client = redis.connect('127.0.0.1', 6379)
function process(event, emit)
    event.log.field = client:ping()
    emit(event)
end
"""

    [transforms.remap_lua_stuff.hooks]
    process = "process"
    

[sinks.emit_syslog]
inputs = ["lua_stuff"]
type = "console"
encoding.codec = "json"
```

### Version

vector 0.24.0 (x86_64-unknown-linux-gnu 43267b9 2022-08-30)

### Debug Output

```text
2022-09-02T21:49:50.543814Z  INFO vector::app: Log level is enabled. level="vector=trace,codec=trace,vrl=trace,file_source=trace,tower_limit=trace,rdkafka=trace,buffers=trace,kube=trace"
2022-09-02T21:49:50.543952Z  INFO vector::config::watcher: Creating configuration file watcher.
2022-09-02T21:49:50.544604Z  INFO vector::config::watcher: Watching configuration files.
2022-09-02T21:49:50.544870Z  INFO vector::app: Loading configs. paths=["/etc/vector/vector.toml"]
2022-09-02T21:49:50.545645Z DEBUG vector::config::loading: No secret placeholder found, skipping secret resolution.
2022-09-02T21:49:50.547948Z DEBUG vector::topology::builder: Building new source. component=generate_syslog
2022-09-02T21:49:50.548496Z DEBUG vector::topology::builder: Building new transform. component=remap_syslog
2022-09-02T21:49:50.550363Z DEBUG vector::topology::builder: Building new sink component=emit_syslog
2022-09-02T21:49:50.550476Z ERROR vector::topology: Configuration error. error=Transform "remap_syslog": Cannot evaluate Lua code in "source": runtime error: error loading module 'socket.core' from file '/usr/local/lib/lua/5.4/socket/core.so':
        /usr/local/lib/lua/5.4/socket/core.so: undefined symbol: luaL_setfuncs
stack traceback:
        [C]: in ?
        [C]: in ?
        [C]: in function 'require'
        /usr/local/share/lua/5.4/socket.lua:12: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.4/redis.lua:844: in upvalue 'create_connection'
        /usr/local/share/lua/5.4/redis.lua:889: in function 'redis.connect'
        [string "/cargo/registry/src/github.com-1ecc6299db9ec8..."]:2: in main chunk
```

### Additional Context

im running in a docker container. 

luarocks version is 3.8.0

luarocks installed packages are luaredis and luasocket.

**Comment by khaskelbergTAU** [comment]
update: this issues was introduced in vector version 0.23.0 

there was a switch from mlua version 0.7.4 to 0.8.0

compiling vector version 0.24.0 from source with mlua dep backrolled to 0.7.4 creates a similar yet different error - now the undefined symbol is lua_gettop.

**Comment by bruceg** [comment]
I can confirm this issue with both the version 0.24.0 download and current `master` branch on Ubuntu 22.04. The default paths don't match where Ubuntu installs Lua libraries, so I needed to use the following to run it: 
```
env LUA_PATH='/usr/share/lua/5.4/?.lua' LUA_CPATH='/usr/lib/x86_64-linux-gnu/lua/5.4/?.so' vector --config CONFIG.toml
```

**Comment by khvzak** [comment]
Unfortunately this is because linker removes unused Lua symbols from binary, and mlua does not use `luaL_setfuncs`.
As workaround I have a list of symbols to keep and seems `luaL_setfuncs` was forgotten.
The fix: https://github.com/khvzak/mlua/commit/050ac4f5ad05072faeda9708e82c10156447c629

I'll release a new version soon

**Comment by khaskelberg** [comment]
Also, re-adding this code to `.cargo/config.toml` seems to fix the issue, at least in our testing
```
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-rdynamic"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-rdynamic"]
```
Previously, this was included in config, but https://github.com/vectordotdev/vector/pull/13074/commits/1aa1e42f517e025d58d71123fad5b61d514ab821 deleted this lines

**Comment by khvzak** [comment]
Ok, seems the problem was not with `luaL_setfuncs`.
The `rustflags = ["-C", "link-args=-rdynamic"]` is required to get Lua symbols properly exported.

**Comment by bruceg** [comment]
I can confirm re-adding those lines resolves the problem. I will work up a patch to that effect.
