### ISSUE TITLE
Support templated values for Clickhouse sink

### ISSUE THREAD

**Issue by frantsao** [vectordotdev/vector#14283]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

We are using vector as agent and aggregator to store logs from different sources in Clickhouse databases. But, at this moment, we don't have an scalable mode to route the logs at the aggregators to the right table at the CH servers. 

### Attempted Solutions

As workaround, we introduce in the aggregator configuration several sink blocks (one per table) and some logic to skip or accept sinking the incoming data. But we have to modify the aggregators configuration each time we have a new table at the clickhouse database.

### Proposal

It would be wonderful allowing templates at least in the database, table, and host parameters.

### Version

0.24.0

**Comment by mr-karan** [comment]
Definitely interested in this, at least the `table` field to begin with :+1:

**Comment by dsmith3197** [comment]
The `database` and `table` fields are template-able now thanks to https://github.com/vectordotdev/vector/pull/18005

**Comment by frantsao** [comment]
Thanks a lot @dsmith3197 :-)
