### ISSUE TITLE
Syslog source docs describe changed decoding behavior

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#14309]
Our docs for the syslog source says:
> If parsing fails, Vector includes the entire Syslog line in the `message` key.

However, the code was changed in #11244 to error if the syslog decoder doesn't parse successfully. A note was added in that PR to the highlights, but the documentation was left unchanged. The reference should be changed to reflect the current behavior.

**Comment by dsmith3197** [comment]
This was done in https://github.com/vectordotdev/vector/pull/14605
