### ISSUE TITLE
demo_logs: provide an ability to generate reproducible logs

### ISSUE THREAD

**Issue by zamazan4ik** [vectordotdev/vector#14370]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

During the development or demonstration it is useful to have an ability to get reproducible logs between runs. It allows to compare results between run. E.g. in my case during development compression level support for File sink, I wanted to compare compression ratio between different compression levels. Firstly, I tried to use `demo_logs` since it allows to generate sample logs. 

But quickly I've noticed it generate different logs between runs! So I just switched to `file` source with the predefined bunch of Lorem Ipsum text and performed required testing on it. This way has own drawbacks - there is no ability to generate infinite sample text stream.

### Proposal

There are several ways, how it can be resolved. But I think intrdocuing a `seed` settings to `demo_logs` source is the best. It allows to get a equal logs between runs since the random will be initiated with the same `seed` from the config file.

However, there is one problem: at least timestamp between runs will not be equal.

**Comment by jszwedko** [comment]
Thanks for this request @zamazan4ik ! You can configure a static set of lines to send via the `lines` parameter when `mode = "shuffle"` (see: https://vector.dev/docs/reference/configuration/sources/demo_logs/#lines ). Would this suffice for you?

**Comment by zamazan4ik** [comment]
@jszwedko as far as I see, `shuffle` mode choose lines from the `lines` parameter in a **random** way. So I will get the same set of lines but in a different order. I want preserve lines order between runs.

**Comment by jszwedko** [comment]
Ah, you are right, I neglected that the shuffling was random. 👍 We also have some upcoming work to make it possible for all sources to emit demo data (https://github.com/vectordotdev/vector/issues/11563). This might end up being covered by that.

**Comment by zamazan4ik** [comment]
Yeah, fine. Please just add to #11563 use case from this issue. With an explicit note about it will be a higher chance to be implemented and not forgotten somewhere in the issue tracker :)

**Comment by jszwedko** [comment]
:) Added it to the use-cases over there. I'll close this issue out.
