### ISSUE TITLE
`internal_metrics` source: metrics not being expired despite `expire_metrics_secs`

### ISSUE THREAD

**Issue by hhromic** [vectordotdev/vector#14394]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

While experimenting with the new `expire_metrics_secs` option, we noticed that it is not behaving as expected for the `file` source (we haven't examined other sources for the same problem). I'm not sure if this is a bug or it "works as intended".

In the `file` source, we currently have a tag cardinality explosion issue due to the `file` tag and filenames with timestamps on them, e.g. `datafile-20220101-100000.txt`, `datafile-20220101-110000.txt`, `datafile-20220101-120000.txt`, etc. These files are created by an external system and then they are eventually deleted.

Before the introduction of the `expire_metrics_secs` option, Vector would keep all metrics for all the `file` tag values seen since start, thus leading to the cardinality explosion due to the infinite nature of the timestamping in the names. However, when setting `expire_metrics_secs` to a value of, for example, `30` (seconds), we expected that Vector metrics forget the `file` tag for a file that is no longer being watched. But this is not the case. The metrics are still there forever.

While investigating, we think that the problem is that the metrics from the `file` source are always updated, even when files disappear. Therefore, the expire metrics option cannot kick-in because they are still being _seen_.

Consider this very simple Vector configuration that demonstrates the issue:
```yaml
data_dir: vector/
expire_metrics_secs: 10

sources:
  file:
    type: file
    include: ["data/*.txt"]
  metrics:
    type: internal_metrics

sinks:
  blackhole:
    type: blackhole
    inputs: ["file"]
  prometheus:
    type: prometheus_exporter
    inputs: ["metrics"]
```

When we run the above configuration with a sample data file:
```
$ ls -la data/sample.txt
-rw-r--r-- 1 hromic hromic 55 Sep 13 11:50 data/sample.txt
$ cat data/sample.txt
this is some data
to feed to vector
hopefully it works

$ vector -c vector.yaml
2022-09-13T13:54:21.850393Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info,kube=info"
2022-09-13T13:54:21.850475Z  INFO vector::app: Loading configs. paths=["vector.yaml"]
2022-09-13T13:54:21.852263Z  INFO vector::topology::running: Running healthchecks.
2022-09-13T13:54:21.852424Z  INFO vector: Vector has started. debug="false" version="0.24.1" arch="x86_64" build_id="8935681 2022-09-12"
2022-09-13T13:54:21.852478Z  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.
2022-09-13T13:54:21.854547Z  INFO source{component_kind="source" component_id=file component_type=file component_name=file}: vector::sources::file: Starting file server. include=["data/*.txt"] exclude=[]
2022-09-13T13:54:21.854547Z  INFO vector::sinks::blackhole::sink: Total events collected events=0 raw_bytes_collected=0
2022-09-13T13:54:21.856535Z  INFO vector::topology::builder: Healthcheck: Passed.
2022-09-13T13:54:21.856580Z  INFO vector::topology::builder: Healthcheck: Passed.
2022-09-13T13:54:21.865202Z  INFO source{component_kind="source" component_id=file component_type=file component_name=file}:file_server: file_source::checkpointer: Attempting to read legacy checkpoint files.
2022-09-13T13:54:21.880651Z  INFO source{component_kind="source" component_id=file component_type=file component_name=file}:file_server: vector::internal_events::file::source: Found new file to watch. file=data/sample.txt
2022-09-13T13:54:22.853949Z  INFO vector::sinks::blackhole::sink: Total events collected events=3 raw_bytes_collected=1764
...

# in another console
$ curl -sS http://localhost:9598/metrics | grep -v ^# | grep -F sample.txt
vector_component_received_bytes_total{component_id="file",component_kind="source",component_name="file",component_type="file",file="data/sample.txt",protocol="file"} 52 1663077355855
vector_component_received_event_bytes_total{component_id="file",component_kind="source",component_name="file",component_type="file",file="data/sample.txt"} 52 1663077355855
vector_component_received_events_total{component_id="file",component_kind="source",component_name="file",component_type="file",file="data/sample.txt"} 3 1663077355855
vector_events_in_total{component_id="file",component_kind="source",component_name="file",component_type="file",file="data/sample.txt"} 3 1663077355855
vector_files_added_total{component_id="file",component_kind="source",component_name="file",component_type="file",file="data/sample.txt"} 1 1663077355855
vector_processed_bytes_total{component_id="file",component_kind="source",component_name="file",component_type="file",file="data/sample.txt",protocol="file"} 52 1663077355855

# now we move away the sample file so Vector stop watching it
$ mv data/sample.txt data/sample.old

# back to the original console, Vector correctly reported that the file is no longer there
2022-09-13T13:56:53.633348Z  INFO source{component_kind="source" component_id=file component_type=file component_name=file}:file_server: vector::internal_events::file::source: Stopped watching file. file=data/sample.txt

# now, after waiting more than 10 seconds (the expire_metrics_secs option value), the metrics are still there
$ curl -sS http://localhost:9598/metrics | grep -v ^# | grep -F sample.txt
vector_component_received_bytes_total{component_id="file",component_kind="source",component_name="file",component_type="file",file="data/sample.txt",protocol="file"} 52 1663077471857
vector_component_received_event_bytes_total{component_id="file",component_kind="source",component_name="file",component_type="file",file="data/sample.txt"} 52 1663077471857
vector_component_received_events_total{component_id="file",component_kind="source",component_name="file",component_type="file",file="data/sample.txt"} 3 1663077471857
vector_events_in_total{component_id="file",component_kind="source",component_name="file",component_type="file",file="data/sample.txt"} 3 1663077471857
vector_files_added_total{component_id="file",component_kind="source",component_name="file",component_type="file",file="data/sample.txt"} 1 1663077471857
vector_files_unwatched_total{component_id="file",component_kind="source",component_name="file",component_type="file",file="data/sample.txt"} 1 1663077471857
vector_processed_bytes_total{component_id="file",component_kind="source",component_name="file",component_type="file",file="data/sample.txt",protocol="file"} 52 1663077471857

# if we wait a bit more and query metrics again, we see that the timestamp is being increased
$ curl -sS http://localhost:9598/metrics | grep -v ^# | grep -F sample.txt
vector_component_received_bytes_total{component_id="file",component_kind="source",component_name="file",component_type="file",file="data/sample.txt",protocol="file"} 52 1663077503856
vector_component_received_event_bytes_total{component_id="file",component_kind="source",component_name="file",component_type="file",file="data/sample.txt"} 52 1663077503856
vector_component_received_events_total{component_id="file",component_kind="source",component_name="file",component_type="file",file="data/sample.txt"} 3 1663077503856
vector_events_in_total{component_id="file",component_kind="source",component_name="file",component_type="file",file="data/sample.txt"} 3 1663077503856
vector_files_added_total{component_id="file",component_kind="source",component_name="file",component_type="file",file="data/sample.txt"} 1 1663077503856
vector_files_unwatched_total{component_id="file",component_kind="source",component_name="file",component_type="file",file="data/sample.txt"} 1 1663077503856
vector_processed_bytes_total{component_id="file",component_kind="source",component_name="file",component_type="file",file="data/sample.txt",protocol="file"} 52 1663077503856
```

The increase in metrics timestamp above let us think that the file source is still updating the metrics, despite the file being removed from the watch list and thus they never expire.

EDIT: I just tried setting the `remove_after_secs` option, so Vector itself deletes the file:
```
2022-09-13T14:01:00.183607Z  INFO source{component_kind="source" component_id=file component_type=file component_name=file}:file_server: vector::internal_events::file::source: File deleted. file=data/sample.txt
2022-09-13T14:01:00.183668Z  INFO source{component_kind="source" component_id=file component_type=file component_name=file}:file_server: vector::internal_events::file::source: Stopped watching file. file=data/sample.txt
```
However, the metrics are still being updated (increasing timestamp), so the same issue persists.

### Version

vector 0.24.1 (x86_64-unknown-linux-gnu 8935681 2022-09-12)

**Comment by bruceg** [comment]
I have reproduced this issue and can confirm the behavior, but it is not limited to the `file` source. I am still tracking down the problem, but I can trigger it with just the `internal_metrics` source and `console` sink.

**Comment by hhromic** [comment]
Hi @bruceg, I tested now your PR using the latest nightly Docker image.

While the PR seems to fix the issue of metrics being properly expired in the `internal_metrics` source, it seems that the `promethus_exporter` still does not want to forget them. Therefore, the MRE I provided in this issue is still not resolved unfortunately.

The only difference I can see now with the PR is that the timestamps in the exported metrics are not increasing anymore, indicating that `internal_metrics` indeed stopped reporting them. However, the "stale" metrics are still being exported by `prometheus_exporter`.

One can argue that Prometheus will drop stale metrics with old-enough timestamps thus avoiding the explosion after scraping, however the prometheus exporter in Vector will still be producing a big amount (and growing) of stale metrics on every request. I can presume this will also consume unbounded amounts of memory in Vector itself.

Moreover, if the new [`suppress_timestamp`](https://vector.dev/docs/reference/configuration/sinks/prometheus_exporter/#suppress_timestamp) option is set to `true` in the `prometheus_exporter` sink, then Prometheus will not discard them anymore because metrics without timestamps are considered with a timestamp of _now_.

I think your PR only solved one part of the issue, the other part now remaining in the prometheus exporter sink now.

I also noticed another problem in the `file` source itself. The metrics are expired with `expire_metrics_secs`, however for files that are slowly updated but NOT deleted/closed, i.e. for longer than the expiration timer, their corresponding metrics that are expired will have their counter values reset to 0 whenever the next write/update occurs. In other words, the `file` source should make sure that metrics for a file are considered "still seen" as long as files are still open and being read.

Given all the above, should we re-open this issue or open new separate issues from what I described?

**Comment by jszwedko** [comment]
Thanks for trying this out @hhromic . @bruceg has been looking at this today. Though it is a separate issue that appears to be specific to the `prometheus_exporter` sink, I think since the original MRE is still, in fact, not working correctly we can re-open this issue to track.

**Comment by hhromic** [comment]
@jszwedko thanks for following up with this issue, much appreciated!
I re-titled the issue now according to the current state of the situation.

Regarding this part I mentioned:

> I also noticed another problem in the `file` source itself. The metrics are expired with `expire_metrics_secs`, however for files that are slowly updated but NOT deleted/closed, i.e. for longer than the expiration timer, their corresponding metrics that are expired will have their counter values reset to 0 whenever the next write/update occurs. In other words, the `file` source should make sure that metrics for a file are considered "still seen" as long as files are still open and being read.

Do you want me to open a separate issue to track that?
I don't believe it is strictly related to the `internal_metrics` source nor the `prometheus_exporter` sink.

**Comment by bruceg** [comment]
How long did you wait for metrics to be expired from the `prometheus_exporter` sink? By default, it will wait 60 seconds before flushing them, [as configured by `flush_period_secs`](https://vector.dev/docs/reference/configuration/sinks/prometheus_exporter/#flush_period_secs).

I think it would be good to have a separate issue for the `file` source issue, yes.

**Comment by hhromic** [comment]
How embarrasing, clearly not enough 🙈.
I just checked again, waiting the whole minute and indeed the `prometheus_exporter` sink flushed the expired metrics.
So this issue is actually fixed for good then. Very sorry for overlooking that sink option!
The behaviour I was expecting is simply obtained when `flush_period_secs = expire_metrics_sec`. Good to know!

I will close this issue now and will open another one for the `file` source tomorrow. Thanks again for the help and fix!
