### ISSUE TITLE
enterprise: Consider re-using `enterprise.site` instead of default value for Datadog sinks

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#14392]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

When setting the `enterprise.site` configuration option, it could easily be assumed that it would affect the `site` value that the Datadog sinks contain. Today it doesn't and only impacts Vector's "self-reporting" for Observability Pipelines.

It's likely the common use-case to be sending events to the same site you're monitoring Observability Pipelines and we could simplify that, reducing user configuration.

### Attempted Solutions

This isn't blocking today, as a user just needs to set the `site` option on every Datadog component.

### Proposal

If the `enterprise.site` option is set, rather than use the default value in other Datadog components - defer to the user's explicitly set `enterprise.site`. They can of course be specified in the other components if the user has an particular need, but it doesn't seem like a natural default to assume.

### Version

0.24.1

**Comment by jszwedko** [comment]
Closing since this block is being removed. cc/ @001wwang @leebenson for visibility.
