### ISSUE TITLE
How to set some macros variables to vector

### ISSUE THREAD

**Issue by sundy-li** [vectordotdev/vector#1440]
Did vector provide some macros like `current_time`, `today` or something else. 
```
[transforms.aa]
  type = "add_fields"
  inputs = ["log"]

  [transforms.aa.fields]
    "job" = "myjob"
    "timestamp" : "${current_time} "  ## I want current timestamp in seconds

```

**Comment by a-rodin** [comment]
Hey @sundy-li, most of the sources automatically add `timestamp` field, which contains the ingestion timestamp. Could it by chance used instead?

**Comment by sundy-li** [comment]
Yes, It could be. But we maybe need something else more. So I suggest there will be more internal macros(timestamp, today, current_line,  current_file) or some other commons.
 
Now there are `timestamp`,  `host`  which will be injected to the logs by default. Why not let users choose their labels on their own?  Perhaps I don't want the name `host`, I'd love the name `instance`(as Prometheus style). Then I can use transforms.add_fields to add `instance` fields.

Now, I use ClickHouse sinke, I must use SQL to transform the timestamp to DateTime, I think it will be better to make it done in Vector.

```
CREATE TABLE default.common_log
(
    `timestamp` String,
    `job` LowCardinality(String),
    `host` String,
    `file` String,
    `message` String,
    `time` DateTime DEFAULT toDateTime(substring(timestamp, 1, 19)),
    `day` Date DEFAULT toDate(time)
)
```

**Comment by a-rodin** [comment]
It is possible to insert the current Unix timestamp using Lua transform. With it your example changes to

```toml
[transforms.aa]
  type = "lua"
  inputs = ["log"]
  source = """
    event["job"] = "myjob"
    event["timestamp"] = os.time()
  """
```

See [`lua` date functions docs](https://www.lua.org/pil/22.1.html) for details about other date-related functions, such as date, which would allow to insert date instead. Note that currently all values inserted through Lua transform are converted to strings, so you might want to add `coercer` transform after:

```toml
[transforms.bb]
  type = "coercer"
  inputs = ["aa"]
  [transforms.bb.types]
    timestamp = "int"
```

However, as a warning, using Lua might not be as fast as native transforms, so make sure that it is fast enough for your needs if you are going to use it.

> Yes, It could be. But we maybe need something else more. So I suggest there will be more internal macros(timestamp, today, current_line, current_file) or some other commons.

The idea with macros is interesting. As it is something related to the config, I'm curious what @Jeffail thinks about it.

> Now, I use ClickHouse sink, I must use SQL to transform the timestamp to DateTime, I think it will be better to make it done in Vector

Note that Vector's timestamps have nanosecond precision, while ClickHouse's `DateTime` has only second precision. This means that automatic conversion would result in losing precision. However, as it is something which still can be very useful, even with lost precision, I've created https://github.com/timberio/vector/issues/1443 to discuss it there.

**Comment by sundy-li** [comment]
We want both fast and features. Rust macros support is better than remote language call function.

**Comment by jszwedko** [comment]
Closing this since VRL has a `now()` function now for fetching the current time.
