### ISSUE TITLE
parse_key_value creates invalid field names

### ISSUE THREAD

**Issue by bruberg** [vectordotdev/vector#14413]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

If a key/value pair has e.g. a dash in the key name, an unmodifiable field name is created.

```
$ parse_key_value!(s'Queue-ID: DA7F562F94, Message-ID: <hash@example.com>, mail_id: z_e2VMsaJP1T, Hits: -2.35, size: 45728, queued_as: EB95062F90', field_delimiter: ",", key_value_delimiter: ":")
{ "Hits": "-2.35", "Message-ID": "<hash@example.com>", "Queue-ID": "DA7F562F94", "mail_id": "z_e2VMsaJP1T", "queued_as": "EB95062F90", "size": "45728" }
```

This creates problems later on:

```
vector[3468]: 123 │     .postfix.queue_id = del(parsed_amavis_log._csv_params.Queue-ID)
vector[3468]:     │                                                                 ^^
vector[3468]:     │                                                                 │
vector[3468]:     │                                                                 undefined variable
vector[3468]:     │                                                                 did you mean "err"?
```

Logstash' kv filter allows for modifying key names during parsing (https://www.elastic.co/guide/en/logstash/current/plugins-filters-kv.html#plugins-filters-kv-trim_key), perhaps something like that could be used to avoid invalid characters.

### Version

vector 0.24.1 (x86_64-unknown-linux-gnu 8935681 2022-09-12)

**Comment by spencergilbert** [comment]
👋,

Hey @bruberg - these are actually valid paths, but are improperly called in your script. The proper way is: `parsed_amavis_log._csv_params."Queue-ID"`.

You can see an [example](https://vector.dev/docs/reference/vrl/expressions/#path-example-quoted-path) in the [docs](https://vector.dev/docs/reference/vrl/expressions/#path).
