### ISSUE TITLE
`gcp_cloud_storage` sink ignoring batch.max_bytes

### ISSUE THREAD

**Issue by suvl** [vectordotdev/vector#14426]
This is the same problem as #3263

Both in version 0.20.0 and 0.24.1 I'm noticing that the file uploaded to GCP is capped at about 15 megabyes.

The relevant part of the config is:

```
      batch.max_bytes = 52428800
      batch.timeout_secs = 360
      batch.max_events = 900000
```

Number of events is not that consistent, but is around 32k-33k. But as of the file sizes, it's like this:
<img width="519" alt="image" src="https://user-images.githubusercontent.com/6018083/190279978-a2273d7e-ca47-45d8-a18a-03baeffbb837.png">

Notice: I have no idea in what back version this worked. I've just noticed the problem 'cause my BigQuery Data Transfer broke due to excessive number of files.

**Comment by jszwedko** [comment]
Thanks for opening this @suvl . Looking at it, I think it might be the same issue as https://github.com/vectordotdev/vector/issues/10020 which is that the batch sizes are calculated based on the in-memory size of the events rather than the serialized size. To validate, could you try bumping it and see if it generates larger files or if it is actually capped at 15 MB for some other reason?

**Comment by suvl** [comment]
Hey @jszwedko. Mine is currently at 

```
      # Buffering
      buffer.type = "memory"
      buffer.max_events = 950000
```

Tried getting it down to 50000 and then back to 1950000 and the results were the same 15MB files.

**Comment by jszwedko** [comment]
Hi @suvl !

Those are actually the buffer settings, rather than the batch settings. Could you try setting the batch settings higher?

For example:

```
      batch.max_bytes = 104857600 # 2x the value you have right now
```

To make sure the max batch size is being applied and not one of the other settings (max_events or timeout_secs) I'd suggest removing those settings.

**Comment by suvl** [comment]
Hey @jszwedko !

Trying it like this:

```
      # Buffering
      buffer.type = "memory"
      buffer.max_events = 950000

      # Storage settings
      storage_class = "STANDARD"
      batch.max_bytes = 104857600
      #batch.timeout_secs = 360
      #batch.max_events = 900000
```

Started creating 28.6MB files, and that makes no sense!

<img width="528" alt="image" src="https://user-images.githubusercontent.com/6018083/190282840-22b7b951-450e-4ad0-adf4-c20b88c7e65c.png">

Downloading one of these files I get 64665 events in it.

**Comment by suvl** [comment]
Moving it to `314572800` gets the output files to 85.6MB so it seems that there's some evidence here for #10020

**Comment by jszwedko** [comment]
Thanks @suvl ! I'm fairly confident this is #10020 then. I'll close this to merge it into that issue. This is something that is on our radar and I hope we can fix before too long.
