### ISSUE TITLE
`downcase` is documented as infallible but is fallible

### ISSUE THREAD

**Issue by kevinpark1217** [vectordotdev/vector#14436]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

In the [downcase](https://vector.dev/docs/reference/vrl/functions/#downcase) documentation, the function is marked `infallible`. However, the execution says otherwise.

```
  error[E103]: unhandled fallible assignment
    ┌─ :7:30
    │
  7 │         .splunk_sourcetype = downcase(type)
    │         -------------------- ^^^^^^^^^^^^^^
    │         │                    │
    │         │                    this expression is fallible
    │         │                    update the expression to be infallible
    │         or change this to an infallible assignment:
    │         .splunk_sourcetype, err = downcase(type)
    │
    = see documentation about error handling at https://errors.vrl.dev/#handling
    = learn more about error code 103 at https://errors.vrl.dev/103
    = see language documentation at https://vrl.dev
    = try your code in the VRL REPL, learn more at https://vrl.dev/examples
```

### Version

vector 0.24.1 (x86_64-apple-darwin 8935681 2022-09-12)

**Comment by spencergilbert** [comment]
👋 
Hi @kevinpark1217, infallible functions are infallible when the input types are guaranteed. [`downcase`](https://vector.dev/docs/reference/vrl/functions/#downcase) requires a String as input, and it doesn't look like that value is known to be a string.

The following should work, or some additional type assertion before the `downcase` call.

```coffee
.splunk_sourcetype = downcase(string!(type))
```

**Comment by jszwedko** [comment]
This behavior around (in)fallibility with type definitions is mentioned here: https://vector.dev/docs/reference/vrl/expressions/#function-call-characteristics
