### ISSUE TITLE
Comparing Telegraf

### ISSUE THREAD

**Issue by Hipska** [vectordotdev/vector#14475]
Hi all, I'm new at Vector and come from using Telegraf. I would love to see how Vector compares against Telegraf in the different performance tests and features table.

I opened corresponding issue on the harness repo: https://github.com/vectordotdev/vector-test-harness/issues/100

I can help by adding the Features table for Telegraf if I would know when exactly a tool gets a ✔️.

**Comment by Hipska** [comment]
Great, can you let me know when a tool gets a tick for an item?

**Comment by Hipska** [comment]
There are no linked test cases in the [Features](https://github.com/vectordotdev/vector#features) table..

**Comment by jszwedko** [comment]
Previously it used the test cases in https://github.com/vectordotdev/vector-test-harness/tree/master/cases

**Comment by Hipska** [comment]
I think you are still confusing the [Features](https://github.com/vectordotdev/vector#features) table with the [Performance](https://github.com/vectordotdev/vector#performance) and [Correctness](https://github.com/vectordotdev/vector#correctness) table. For the latter two, it is clear when a tick is set, but it is unclear for the Features table.

**Comment by jszwedko** [comment]
> I think you are still confusing the [Features](https://github.com/vectordotdev/vector#features) table with the [Performance](https://github.com/vectordotdev/vector#performance) and [Correctness](https://github.com/vectordotdev/vector#correctness) table. For the latter two, it is clear when a tick is set, but it is unclear for the Features table.

Ah, doh, you are right. I was confusing correctness. I think the features table was just manually created.

**Comment by Hipska** [comment]
Thanks, I added a PR to add Telegraf in that table. I'm open to comments.

**Comment by Hipska** [comment]
> Hey! We've actually discontinued use of that `vector-test-harness` repository. We will be working on a new comparison suite though and hope to publish it in the future.

Hi @jszwedko, any update on this?

**Comment by jszwedko** [comment]
> > Hey! We've actually discontinued use of that `vector-test-harness` repository. We will be working on a new comparison suite though and hope to publish it in the future.
> 
> Hi @jszwedko, any update on this?

Unfortunately nothing yet.

**Comment by Hipska** [comment]
@jszwedko and now?

**Comment by pront** [comment]
Hi @Hipska, unfortunately we don't have the capacity to revive that repository. Also, performance and regression detection has been migrated to use an internal Datadog tool.
