### ISSUE TITLE
vector validate with stdin source blocks until stdin data is sent

### ISSUE THREAD

**Issue by jorgebay** [vectordotdev/vector#14512]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Running `vector validate` using the following configuration will cause the process to not exit until a new line is sent to the stdin of the vector process.

This does not occur on `0.22` branch.

### Configuration

```text
data_dir = "/tmp"

[sources.in]
type = "stdin"

[sinks.out]
inputs = ["in"]
type = "console"

[sinks.out.encoding]
codec = "text"
```

### Version

0.24.1

**Comment by jszwedko** [comment]
Thanks for this report @jorgebay . I bisected this down to https://github.com/vectordotdev/vector/pull/13389.  We'll take a closer look.
