### ISSUE TITLE
Rename `http` => `http_server` and `http_scrape` => `http_client`

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#14522]
# Context

Historically the `http` source has been a _source_ of confusion due to both it's ambiguous name as well as somewhat unclear description:

```markdown
Collect logs emitted by an `HTTP` server
```

The `http` source is, in fact, a server that runs as part of Vector which receives requests from external HTTP clients, converting the request body into events.

We've recently added a `http_scrape` source which makes requests to an external HTTP server, a generalized form of the `prometheus_scrape` source.

As the `http_scrape` source has yet to make its stable appearance, we have the opportunity to rename it as a non-breaking change. I propose renaming these two sources along the well known client/server divide, this will be a more obvious naming strategy for these components and ideally cause less user confusion.

# Implementation

- Rename `http` source to `http_server`
- Rename `http_scrape` source to `http_client`
- Rename `Util::Http` to `Util::HttpServer`
  - This code is shared by some, but not all, HTTP server based sources
- Rename `Util::HttpScrape` to `Util::HttpClient` 
  - This code is shared by the `prometheus_scrape` source

# Out-of-Scope

- Renaming the `prometheus_scrape` source
- Renaming the `prometheus_exporter` sink
- Renaming the `http` sink

The Prometheus ecosystem commonly uses both scrape (`scrape_interval`, `scrape_configs`, etc.) and exporter ([exporters](https://prometheus.io/docs/instrumenting/exporters/)), leading to a less confusing UX. The `http` sink (currently) has no analogous component, and we could consider renaming it when implemented or as part of another issue that enforces general naming standardization.

**Comment by fuchsnj** [comment]
We should potentially also consider the `socket` source, which has a similar naming issue. Maybe rename it to `socket_server` (or consider it out of scope for this change)

**Comment by spencergilbert** [comment]
> We should potentially also consider the `socket` source, which has a similar naming issue. Maybe rename it to `socket_server` (or consider it out of scope for this change)

I'd put it in the same category of `http` sink, out of scope _here_ unless...

> Maybe simply being consistent within Vector will help with this though (e.g. also renaming socket to socket_server as @fuchsnj suggests).

We want to have a wider discussion of how things are generally named, enforce it, and make the changes.

**Comment by randomchance** [comment]
I would have interpreted the first suggestion correctly, but I can see how it could be misconstrued.  
I **do** think that even if you did initially misinterpret the names it would still be clear that there is another source with mirrored functionality. That way ~~I don't~~ users don't just write off the idea of receiving `http` entirely. 

I personally think sticking with the standard `client|server` verbs is best, however I can see using `http_listener` instead of `http_server` if that would be more clear.

**Comment by zamazan4ik** [comment]
I also support the renaming. I have no preffered variants anyway :) I at least agree, that the current `http` is kinda confusing (`http_scrape` is fine to me though).

My main consideration is if we want to rename the sources name, would be good to provide an auto conversion for the config file during the upgrade process. It will make the life much easier. If we have no such mechanism right now, maybe it will be a good time to at least think about it :) E.g. at the beginning only one-way conversion (old config -> new config) could be supported.

**Comment by jszwedko** [comment]
Just circling back to this. I still think the naming is a bit ambiguous, but also that it's an improvement over the current state of things so I'm ok with this change and then we can revisit in the future.

**Comment by spencergilbert** [comment]
Would we be ok getting this merged in for `0.25`?

**Comment by JeanMertz** [comment]
I can see Jesse's concerns, but I agree that it's an improvement 👍

**Comment by jszwedko** [comment]
> Would we be ok getting this merged in for `0.25`?

👍  if you feel like you can take it on this week we can squeeze it into 0.25.
