### ISSUE TITLE
Documentation for host_metrics load1 / load5 / load15 has incorrect time interval

### ISSUE THREAD

**Issue by mdesson** [vectordotdev/vector#14521]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The documentation for the host metrics `load1`, `load5`, and `load15` states that it covers the last 1/5/15 seconds. However, after browsing the source it seems that it is over the course of _minutes_, a very different time interval.

https://vector.dev/docs/reference/configuration/sources/host_metrics/#load1

<img width="764" alt="image" src="https://user-images.githubusercontent.com/25888319/191782533-7fb92991-2d4d-447a-a7b6-d7f0af84aa95.png">

From the source:

1. The metrics are defined [here](https://github.com/vectordotdev/vector/blob/248583fe27dfb3c1393c80580af5c3340a89cd3f/src/sources/host_metrics/mod.rs#L246):

```rust
            Ok(loadavg) => {
                output.gauge("load1", loadavg.0.get::<ratio>() as f64, BTreeMap::new());
                output.gauge("load5", loadavg.1.get::<ratio>() as f64, BTreeMap::new());
                output.gauge("load15", loadavg.2.get::<ratio>() as f64, BTreeMap::new());
            }
```

2. They're of LoadAvg type, which is defined [here](https://github.com/vectordotdev/vector/blob/248583fe27dfb3c1393c80580af5c3340a89cd3f/src/sources/eventstoredb_metrics/types.rs#L181):

```rust
pub struct LoadAvg {
    #[serde(rename = "1m")]
    pub one_m: f64,
    #[serde(rename = "5m")]
    pub five_m: f64,
    #[serde(rename = "15m")]
    pub fifteen_m: f64,
}
```

### Version

0.24.1

**Comment by bruceg** [comment]
Thanks for pointing this out, @mdesson. I have opened #14527 to fix this.
