### ISSUE TITLE
Vector won't read contents of old log files even if read_from = "beginning" and ignore_older_secs = 0 is set

### ISSUE THREAD

**Issue by davidlukac** [vectordotdev/vector#14552]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

[`vector 0.24.1 (x86_64-unknown-linux-gnu 8935681 2022-09-12)`](https://vector.dev)

I have bunch of old log files sitting on the server:

```
$ ls -al /var/opt/app/logs/httpd/access*
-rw-rw---- 1 app app  98836 May 24  2021 /var/opt/app/logs/httpd/access.log.2021-05-24
-rw-rw---- 1 app app 101632 May 25  2021 /var/opt/app/logs/httpd/access.log.2021-05-25
-rw-rw---- 1 app app  97910 Jun  1  2021 /var/opt/app/logs/httpd/access.log.2021-06-01
...
-rw-rw---- 1 app app    732 Sep 19 01:10 /var/opt/app/logs/httpd/access.log.2022-09-19
-rw-rw---- 1 app app    732 Sep 20 01:10 /var/opt/app/logs/httpd/access.log.2022-09-20
-rw-rw---- 1 app app    732 Sep 21 01:10 /var/opt/app/logs/httpd/access.log.2022-09-21
```

My source config is:
```
[sources.log_files]
type = "file"
include = [ "/var/opt/app/logs/httpd/access.log.*" ]
read_from = "beginning"
ignore_older_secs = 0
```

What `vector` does, is to pick up the latest file from the pattern `.../access.log.*` and collects only what's appended to the file, even though `read_from = "beginning"` is present.

I can't make it to read all the historical files from the beginning, so I can clean them up. The only way I made `vector` to really read a file from beginning was to insert a line at the beginning of a file.

Is this a bug or I'm doing something wrong?

_Also published as a [question on DevOps Stack Exchange](https://devops.stackexchange.com/questions/16635/how-can-i-make-vector-collect-old-log-files)._

### Configuration

```text
[sources.log_files]
type = "file"
include = [ "/var/opt/app/logs/httpd/access.log.*" ]
read_from = "beginning"
ignore_older_secs = 0
```

### Version

vector 0.24.1 (x86_64-unknown-linux-gnu 8935681 2022-09-12

**Comment by ethack** [comment]
I could be wrong, but I wonder if `ignore_checkpoints = true` would help you. The docs for `read_from` say "In the absence of a checkpoint...". If you've run vector on these files ever before there are likely checkpoints written and it's trying to start where it left off.

**Comment by davidlukac** [comment]
@ethack good tip, I'll `ignore_checkpoints` as well and report back. I did try deleting the checkpoints manually, which didn't change the behaviour.

**Comment by jszwedko** [comment]
This does seem like an issue with checkpoints, that Vector already read those files and thus won't re-read them. I'll close this, but please reopen if you find this is still an issue after either ignoring the checkpoints with `ignore_checkpoints` or when clearing out the existing checkpoints by removing them from `/var/lib/vector` (or whatever the configured `data_dir` is).
