### ISSUE TITLE
New `prometheus_push_gateway` sink

### ISSUE THREAD

**Issue by Jeffail** [vectordotdev/vector#1461]
More info here: https://prometheus.io/docs/practices/pushing/

The push gateway allows you to use a push model for Prometheus metrics. This is mostly intended for short lived jobs and has a few issues when used with long running services, but for Vector it'd be another tool on the belt.

**Comment by a-rodin** [comment]
It looks like Vector's buffers actually relieves the first drawback in the list mentioned in the docs:

> When monitoring multiple instances through a single Pushgateway, the Pushgateway becomes both a single point of failure and a potential bottleneck.

With on-disk buffers a temporarily downtime of Prometheus would be not an issue, as Vector would re-batch them when Prometheus becomes healthy again.

**Comment by omegarus** [comment]
Is it possible to use HTTP sink may be to push metrics to pushgateway ?

**Comment by marcusteixeira** [comment]
Ref: https://github.com/vectordotdev/vector/blob/v0.36/src/sources/prometheus/pushgateway.rs#L8-L12

Prometheus push_gateway is available on release 0.36.0 of vector(https://vector.dev/releases/0.36.0/)

**Comment by jszwedko** [comment]
Oh yes, thanks for the bump @marcusteixeira . I'll close this issue.
