### ISSUE TITLE
keepalive.time_secs option does not validate for Vector sinks

### ISSUE THREAD

**Issue by jayhardee9** [vectordotdev/vector#14618]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I cannot get the below configuration to validate with the `keepalive.time_secs` option specified in my Vector config [following this in the docs](https://vector.dev/docs/reference/configuration/sinks/vector/#keepalive). If I remove it, it will validate. For what it's worth, I'm running Vector with the `timberio/vector:latest-alpine` image.

### Configuration

```text
[sources.my_source_id]
type = "file"
ignore_older_secs = 600
include = [ "/var/log/**/*.log" ]
read_from = "beginning"

[sinks.my_sink_id]
type = "vector"
inputs = [ "my_source_id" ]
address = "92.12.333.224:6000"
version = "2"

[sinks.my_sink_id.keepalive]
time_secs = 30
```

### Version

vector 0.24.1 (aarch64-unknown-linux-musl 8935681 2022-09-12)

### Debug Output

```text
Failed to load ["/etc/vector/vector.toml"]
------------------------------------------
x data did not match any variant of untagged enum VectorConfig for key `sinks.my_sink_id`
```

### Additional Context

I'm running Vector with the `timberio/vector:latest-alpine` image.

**Comment by spencergilbert** [comment]
It looks like there were a couple options that were intended for the now removed `v1` version of the sink. I've opened https://github.com/vectordotdev/vector/pull/14619 to remove those options.
