### ISSUE TITLE
parse_syslog - thread 'vector-worker' panicked at

### ISSUE THREAD

**Issue by Klar** [vectordotdev/vector#14651]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

log message with date "Feb 29 14:07:19" crashes vector as Feb 29 does not exist.

### Configuration

```text
# .message = "<134> Feb 28 14:07:19 myhostname sshd - - - this is my message"   <-- working
.message = "<134> Feb 29 14:07:19 myhostname sshd - - - this is my message"     <-- vector panick crash
  parsed_syslog, err = parse_syslog(.message)

  if err != null {
    ...
```

### Version

vector 0.24.1 (x86_64-unknown-linux-gnu 8935681 2022-09-12)

### Debug Output

```text
2022-09-30T11:07:42.593671Z DEBUG transform{component_kind="transform" component_id=transform_final component_type=remap component_name=transform_final}: vector::utilization: utilization=0.00007978729074498148
thread 'vector-worker' panicked at 'No such local time', /cargo/git/checkouts/chrono-ea2147b7778d4084/b7abfc3/src/offset/mod.rs:173:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'vector-worker' panicked at 'internal error: entered unreachable code: join error or bad poll', src/topology/builder.rs:679:30

2022-09-30T11:07:42.594318Z ERROR transform{component_kind="transform" component_id=transform_final component_type=remap component_name=transform_final}: vector::topology: An error occurred that Vector couldn't handle.

2022-09-30T11:07:42.594402Z  INFO vector: Vector has stopped.
```

### Example Data

see configuration.

.message ==> "<134> Feb 29 14:07:19 myhostname sshd - - - this is my message"

**Comment by jszwedko** [comment]
@StephenWakely do you mind taking a peek at this one? I was able to reproduce locally with `vector vrl`.
