### ISSUE TITLE
Display VRL diagnostic messages in web UI

### ISSUE THREAD

**Issue by JeanMertz** [vectordotdev/vector#14659]
Once we have a simple web UI (#14657), we need one more addition to this UI to make it useful as a first version to users. It needs to be able to display errors returned by the VRL compiler when compilation of a VRL program fails.

To accomplish this, we'll use the existing third `textbox` element normally used to display the resulting log event after processing the event, and instead show one or more diagnostic messages as returned by the compiler.

While this is fairly simple at first, we can expand on this later, to move it to a different location on the page, and add more styling to the diagnostic to make it more readable to the user.

**Comment by jonathanpv** [comment]
To display the diagnostic methods we will require another method of printing out the errors, currently text areas and monaco editor do not offer a rich printing of terminal codes. We can utilize xterm.js which is also used by visual studio code to print out the error messages in a nice readable manner. A coming pr will implement this but for now there is a demo I have spun up here: 

https://codepen.io/jonpad/pen/jOxpEKj

**Comment by JeanMertz** [comment]
> We can utilize xterm.js which is also used by visual studio code to print out the error messages in a nice readable manner.

This seems like a good first step 👍 

In the future, I expect our diagnostics to be switched over to an actual type that you can query for specific information. For example, given this error:

```

error[E110]: invalid argument type
  ┌─ :1:8
  │
1 │ upcase(.foo)
  │        ^^^^
  │        │
  │        this expression resolves to any
  │        but the parameter "value" expects the exact type string
  │
  = try: ensuring an appropriate type at runtime
  =
  =     .foo = string!(.foo)
  =     upcase(.foo)
  =
  = try: coercing to an appropriate type and specifying a default value as a fallback in case coercion fails
  =
  =     .foo = to_string(.foo) ?? "default"
  =     upcase(.foo)
  =
  = see documentation about error handling at https://errors.vrl.dev/#handling
  = learn more about error code 110 at https://errors.vrl.dev/110
  = see language documentation at https://vrl.dev
```

You'll be able to query the following information:

- error code
- error title
- error span
- list of "primary message" spans and titles (in this case "this expression resolves to any")
- list of "secondary message" spans and titles (in this case "but the parameter "value" expects the exact type string")
- list of "try" messages with "title" and "suggestion"
- list of "other notes"

This will be used (at some point) within the Datadog UI to show VRL diagnostics, and can also be used by the Playground to style the diagnostics outside the code editor, without the need to parse terminal character sequences.

**Comment by jonathanpv** [comment]
> In the future, I expect our diagnostics to be switched over to an actual type that you can query for specific information. For example, given this error:

Sweet this will offer users a lot more features and I can definitely see how it won't need to parse terminal character sequences within the web playground after this is implemented.
