### ISSUE TITLE
kubernetes_logs documentation missing log output fields

### ISSUE THREAD

**Issue by mjperrone** [vectordotdev/vector#14669]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

[In the code](https://github.com/vectordotdev/vector/blob/cd5b2adae1cd29af5f3a27ec8b75c9b586b67d73/src/sources/kubernetes_logs/pod_metadata_annotator.rs#L62-L73) I see 12 kubernetes fields that are populated by the `kubernetes_logs` source.  In [the documentation](https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/#output-logs) I see 11 kubernetes fields.

`container_id` and `pod_owner` are missing. Running vector I _do_ see `kubernetes.container_id` and `kubernetes.pod_owner` appear.

### Configuration

```text
[sources.kubernetes_logs]
  type = "kubernetes_logs"
```
```


### Version

latest

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

**Comment by spencergilbert** [comment]
Looks like both were missing from the `output` section of the CUE file, and `container_id` was also missing from the configuration section.
