### ISSUE TITLE
Loki sink: Labels with "-" in them seemingly ignored.

### ISSUE THREAD

**Issue by jaqb76** [vectordotdev/vector#14763]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

It looks like labels with dash "-" in them are ignored by the loki sink. e.g.

application = '{{ kubernetes.pod_labels.app-name }}'

does not create the application label.

### Actual Behavior
label.application  is missing.

### Expected Behavior
application = '{{ kubernetes.pod_labels.app-name }}'

### Configuration

```text
loki_sink:
        compression: gzip
        remove_label_fields: true
        encoding:
          codec: json
        endpoint: https://loki-xxxx
        inputs:
        - kubernetes_logs
        labels:
          clustername: test_cluster
          container: '{{ kubernetes.container_name }}'
          forwarder: vector
          host: '{{ kubernetes.pod_node_name }}'
          namespace: '{{ kubernetes.pod_namespace }}'
          pod: '{{ kubernetes.pod_name }}'
          app: '{{ kubernetes.pod_labels.app }}'
          application: '{{ kubernetes.pod_labels.app-name }}'
          release: '{{ kubernetes.pod_labels.release }}'
          pod_uid: '{{ kubernetes.pod_uid }}'
          region: us-east-2
          pod_labels: '{{kubernetes.pod_labels}}'
        type: loki
```

### Version

INFO vector: Vector has started. debug="false" version="0.24.0" arch="x86_64" build_id="43267b9 2022-08-30"

### Example Data

![Screenshot from 2022-10-07 12-37-09](https://user-images.githubusercontent.com/40625220/194534819-21c189d4-4f8f-45c6-ac2f-eed2a59e7593.png)

**Comment by spencergilbert** [comment]
👋 

Hi there, try this template syntax instead:

```diff
- application = '{{ kubernetes.pod_labels.app-name }}'
+ application = '{{ kubernetes.pod_labels."app-name" }}
```

We've been updating how Vector looks up paths to be aligned with VRL, unfortunately it looks like the docs around template syntax and field path notation weren't updated at the time of the change. I'm writing a pull request to address that now, but it should be replaced by [path expressions](https://vector.dev/docs/reference/vrl/expressions/#path). 

Additionally the compile time checking of these paths is incomplete and is tracked by https://github.com/vectordotdev/vector/issues/13033 which we are hoping to tackle this quarter.

Let me know if this doesn't solve the problem and I'll reopen the issue!
