### ISSUE TITLE
Add debug logging to the `cloudwatch_logs` sink for rejected events

### ISSUE THREAD

**Issue by LucioFranco** [vectordotdev/vector#1481]
We should add a debug log https://github.com/timberio/vector/blob/master/src/sinks/aws_cloudwatch_logs/request.rs#L144 that will log when there are rejected logs from the `PutLogEvents` endpoint. This should be rate limited similar to our other sources/transforms/sinks.

https://docs.rs/rusoto_logs/0.42.0/rusoto_logs/struct.PutLogEventsResponse.html

**Comment by jszwedko** [comment]
Closing since we have a new [component spec](https://github.com/vectordotdev/vector/blob/master/docs/specs/component.md) that guides these log messages.
