### ISSUE TITLE
sink failure dependency

### ISSUE THREAD

**Issue by omriKaltura** [vectordotdev/vector#14828]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When using 2 or more sinks, we found that the status of a specific sink can affect the delivery of events to other sinks.
in this case we have 2 sinks:
`elasticsearch` and  `s3`
all sources are transformed and sent to both sinks in parallel.

we noticed that when our elastic cluster became unavailable (red) and stopped receiving events, the events stopped arriving to the s3 sink as well at the same time. 

upon restarting the agent the events where sent again to the S3 sink for a few minutes and then stopped again

### Configuration

```text
[sinks.s3]
  type = "aws_s3"
  inputs = ["s3-logs"]
  bucket = "xxxxx"
  encoding.codec = "text"
  key_prefix = "xxxxx"
  compression = "gzip"
  healthcheck = true
  region = "xxxxx"
  auth.assume_role = "xxxxx"
  batch.timeout_secs = 300
  batch.max_bytes = 10000000
  buffer.type = "disk"
  buffer.max_size = 400000000
[sinks.elasticsearch]
  type = "elasticsearch"
  inputs = ["jsonparser"]
  host = "xxxxx"
  bulk.index = "{{ kubernetes.pod_namespace }}-%Y.%m.%d"
  auth.strategy = "aws"
  aws.region = "xxxx"
  batch.max_bytes = 10490000
  batch.max_events = 1000
  batch.timeout_secs = 5
  buffer.max_events = 200
  buffer.type = "memory"
  buffer.when_full = "block"
  tls.verify_certificate = false
  tls.verify_hostname = false
```

### Version

0.18.1

**Comment by jszwedko** [comment]
Hi @omriKaltura ! This is expected behavior when fanning out. If one sink is slow or stops, it will cause backpressure that affects other sinks connected to the same inputs. You can avoid this be configuring the problematic sink, here `elasticsearch`, to drop data rather than applying backpressure by setting `buffer.when_full = "drop_newest"`. This is discussed here: https://vector.dev/docs/about/concepts/#backpressure . Let me know if that helps!

**Comment by jszwedko** [comment]
Closing as resolved but please leave a comment if you have any additional questions!
