### ISSUE TITLE
parse_timestamp: input is not enough for unique date and time

### ISSUE THREAD

**Issue by skitsanos** [vectordotdev/vector#14841]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I have a strange problem with parsing timestamp, it throws me an error on parsing date like this: `Oct  5 14:43:03 2023 GMT` with format set to `%h  %-d %H:%M:%S %Y %Z`

If I use the very same date and format in pure Rust, it works just fine:

```rust
extern crate chrono;
use chrono::prelude::*;

fn main() {
    let date_str = "Oct  5 14:43:03 2023 GMT";

    let date = Utc.datetime_from_str(&date_str, "%h  %-d %H:%M:%S %Y %Z");

    match date {
        Ok(v) => println!("{:?}", v),
        Err(e) => println!("{:?}", e)
    }
}
```

But in VRL the following fails:

```
ts = parse_timestamp!("Oct  5 14:43:03 2023 GMT", format: "%h %-d %H:%M:%S %Y %Z")
```

Am I missing something, or is there an issue in the `parse_timestamp` function?

### Version

vector 0.24.1 (x86_64-apple-darwin 8935681 2022-09-12)

### Debug Output

```text
2022-10-14T11:00:05.191630Z ERROR transform{component_kind="transform" component_id=parse_log component_type=remap component_name=parse_log}: vector::internal_events::remap: Mapping failed with event. error="function call error for \"parse_timestamp\" at (169:246): Invalid timestamp \"Oct  5 14:43:03 2023 GMT\": input is not enough for unique date and time" error_type="conversion_failed" stage="processing" internal_log_rate_secs=10
```

### Example Data

```
Oct  5 14:43:03 2023 GMT
```

**Comment by StephenWakely** [comment]
The conversion routine we use is `DateTime::parse_from_str`. This requires the timezone to be specified - unlike with `UTC::datetime_from_str`.

Unfortunately `%Z` doesn't actually work as a timezone specifier. See this [footnote](https://docs.rs/chrono/latest/chrono/format/strftime/index.html#fn6).

It works if you specify an offset:

```coffee
$ parse_timestamp!("Oct  5 14:43:03 2023 +0100", format: "%h %-d %H:%M:%S %Y %z")
t'2023-10-05T13:43:03Z'
```

`Utc.datetime_from_str` just ignores the timezone. You will get the same result if you specify `GMT` or `BST`.

I don't think there is a fix for this.
