### ISSUE TITLE
Support Logstash HTTP input as a sink

### ISSUE THREAD

**Issue by davidjericho** [vectordotdev/vector#14854]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Vector is a useful source solution to feed to a Logstash environment, being far more efficient than a single instance of Logstash, and easy to deploy. We can't avoid using Logstash pipelines on the backend at the moment, but we can scale them horizontally, allowing us to increase throughput.

Vector doesn't support the ndjson format in the HTTP sink that Logstash is expecting, and while we could recursively process the ndjson in the Logstash environment, this isn't how we'd deploy it in production nor is it useful for benchmarking a Logstash pipeline. 

Vector is transmitting the HTTP format in an a JSON array. Logstash's HTTP input expects it to be a slightly awkward ndjson, and it ends each line with a comma and then a \n.

Additional use cases would be simply naive Vector collectors passing to a Logstash HTTP receiver. As noted in https://www.elastic.co/guide/en/logstash/current/ls-to-ls.html the advice is stick with HTTP to HTTP if reliability can be answered. This is particularly relevant in the MSP style situation where we don't have full control of the logging endpoint, and some transform of data is required before loading into a data lake.

### Attempted Solutions

Setting the batch.max_events to 1 resulted in a sink output that Logstash would accept with minimal post-processing, but an extra step in the Logstash pipeline was required to handle this, and there are obvious efficiency implications. Peak performance we saw in that scenario was an order of magnitude lower than a batched transfer.

We tried various codecs and mime type applications in Logstash, but none worked to unwrap the log data properly.

I did look at the source to see if I could implement a PR for this, but my knowledge of Rust is minimal and while I could follow the code I didn't think I could rapidly solve the problem.

StephenW on Discord responded to my query and suggested I write up a feature request.

### Proposal

Extend Vector's http sink to support both ndjson and Logstash ndjson as an encoding method.

### References

These look similar, but not directly related.

* [#1174](https://github.com/vectordotdev/vector/pull/1174)
* [#1209](https://github.com/vectordotdev/vector/issues/1209)

### Version

vector 0.24.2 (x86_64-unknown-linux-musl 5e47b89 2022-10-13)

**Comment by jszwedko** [comment]
Hi @davidjericho !

Do you know what format the `http` input for Logstash expects for batches of events? https://www.elastic.co/guide/en/logstash/current/plugins-inputs-http.html doesn't seem to provide much detail other than it accepts "multiline events". That might help us give advice on the appropriate Vector configuration to use.

For sending individual events to logstash something like:

```
```

**Comment by davidjericho** [comment]
Hi @jszwedko,

I spent some time working with a colleague to get the reverse working, with logstash as a source writing to vector. Your comment and this work in the other direction clued me onto what was mismatched. 

The final answer was:

vector.toml:
```
[sinks.logstash]
type = "http"
inputs = [ "*" ]
uri = "http://...."
encoding.codec = "json"
framing.method = "newline_delimited"
```

logstash input configuration:
```
input {
  http {
    port => <port number>
    additional_codecs => { "application/x-ndjson" => "json_lines" }
  }
}
```

I'm not sure why I never clued onto the mime-type originally however the configuration above is working fine.

Thank you for the pointer, no need for this particular feature request.

**Comment by jszwedko** [comment]
Perfect, thanks for following up @davidjericho ! Hopefully your notes here help others that may run into this.
