### ISSUE TITLE
Only flush relevant kafka source acknowledgements during rebalance

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#14865]
In the recent change to flush commits on Kafka rebalance events (#10434), the process used flushes _all_ outstanding finalizers from the outstanding set. This may cause a failure to commit outstanding events from topics that were not rebalanced away from this consumer, leading to duplicated messages on restart.

We should add the necessary hooks to the `OrderedFinalizer` to allow it to selectively flush only certain elements from its set on rebalance.

Ref https://github.com/vectordotdev/vector/pull/10434#discussion_r784931021

**Comment by dsmith3197** [comment]
This was fixed in https://github.com/vectordotdev/vector/pull/17497
