### ISSUE TITLE
Pre-compile templates

### ISSUE THREAD

**Issue by fuchsnj** [vectordotdev/vector#14864]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Currently templates that include fields are parsed with a regex, and then every field is parsed every time a template is rendered. These values do not change and can be pre-compiled to speed up template rendering.

### Version

0.24

**Comment by jszwedko** [comment]
User investigation with some more details: https://github.com/vectordotdev/vector/issues/14898
