### ISSUE TITLE
Splunk HEC Sink: Automation of the indexed field extractions

### ISSUE THREAD

**Issue by marckhair** [vectordotdev/vector#14867]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The automation of the indexed field extractions when sending json logs to Splunk HEC as a sink in vector does not work. The logs ingested in splunk end up being ingested as raw logs.

The same source transform was sent using an HTTP post sink to the Splunk collector endpoint of my Splunk service, and the fields were automatically indexed.

Reference: https://docs.splunk.com/Documentation/Splunk/8.0.0/Data/IFXandHEC

### Configuration

```text
Config Number 1 (not indexed properly) 
  my_splunk_http_event_collector:
     type: splunk_hec_logs
     inputs:
       - my_extract_splunk
     endpoint: http://splunk:8088
     encoding:
       codec: json
     default_token: "${SPLUNK_HEC_TOKEN}"
     source: "kafka-vector"
     endpoint_target: event

Config Number 2 (indexed properly)
  my_splunk_http:
    type: http
    method: post
    inputs:
      - my_extract_splunk
    uri: http://splunk:8088/services/collector/event
    request:
      headers:
        Authorization: "Splunk abcd1234"
    encoding:
      codec: json
```

### Version

$ docker exec -it vector vector --version vector 0.25.0

**Comment by jszwedko** [comment]
Hi @marckhair ,

Could you provide a reproducible example that we can run locally? Using the `stdin` source and some sample data is common for this. I think there is likely to be a few moving parts here (the source of the data, any transformations) so having a complete example we can run would be helpful.

A difference between those two sinks is that the `splunk_hec_logs` one will send the data as structured HEC data while the `http` sink will just send it as raw JSON.

You could also try pointing both of those sinks at a requestbin service or local proxy to examine the differences in the requests.

**Comment by jszwedko** [comment]
Closing this as stale but please reopen if you are able to circle back around to this to provide a runnable example.
