### ISSUE TITLE
Build in docker cause `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by honganan** [vectordotdev/vector#14873]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I am trying to build from source on a x86_64 machine. Following [installation](https://vector.dev/docs/setup/installation/manual/from-source/#next-steps), I have successfully build `make package-x86_64-unknown-linux-musl-all`. And When I run `make package-aarch64-unknown-linux-musl-all` I caught this:
```
Compiling proc-macro2 v1.0.43
   Compiling libc v0.2.131
   Compiling serde v1.0.143
   Compiling log v0.4.17
   Compiling memchr v2.5.0
   Compiling futures-core v0.3.21
error: failed to run custom build command for `proc-macro2 v1.0.43`

Caused by:
  process didn't exit successfully: `/target/release/build/proc-macro2-013962dc82d9974e/build-script-build` (exit status: 1)
  --- stderr
  /target/release/build/proc-macro2-013962dc82d9974e/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /target/release/build/proc-macro2-013962dc82d9974e/build-script-build)
  /target/release/build/proc-macro2-013962dc82d9974e/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /target/release/build/proc-macro2-013962dc82d9974e/build-script-build)
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `log v0.4.17`

Caused by:
  process didn't exit successfully: `/target/release/build/log-cae7d2923ea5e2fd/build-script-build` (exit status: 1)
  --- stderr
  /target/release/build/log-cae7d2923ea5e2fd/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /target/release/build/log-cae7d2923ea5e2fd/build-script-build)
error: failed to run custom build command for `libc v0.2.131`

Caused by:
  process didn't exit successfully: `/target/release/build/libc-735be3a2f25e9ac6/build-script-build` (exit status: 1)
  --- stderr
  /target/release/build/libc-735be3a2f25e9ac6/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /target/release/build/libc-735be3a2f25e9ac6/build-script-build)
  /target/release/build/libc-735be3a2f25e9ac6/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /target/release/build/libc-735be3a2f25e9ac6/build-script-build)
error: failed to run custom build command for `memchr v2.5.0`

Caused by:
  process didn't exit successfully: `/target/release/build/memchr-6fc9dd5047220f50/build-script-build` (exit status: 1)
  --- stderr
  /target/release/build/memchr-6fc9dd5047220f50/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /target/release/build/memchr-6fc9dd5047220f50/build-script-build)
...more
```

As my understanding, it's build in a docker image, anything should be boxed. How could this happened? Any help will be appreciate, Thanks!

### Version

source tag v0.24.2

### Additional Context

machine info:
$ uname -a
Linux xxx 4.14.246-187.474.amzn2.x86_64 #1 SMP Tue Sep 7 21:48:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jszwedko** [comment]
Hi @honganan ,

I think you might need to run `cargo clean` before running `make package-aarch64-unknown-linux-musl-all`. The `target/` directory is mounted into the container so running the builds in sequence can pollute each other by sharing cached artifacts. This raises the question of if we should be mounting the `target/` directory for those builds 🤔

**Comment by honganan** [comment]
> I think you might need to run `cargo clean` before running `make package-aarch64-unknown-linux-musl-all`. The `target/` directory is mounted into the container so running the builds in sequence can pollute each other by sharing cached artifacts. This raises the question of if we should be mounting the `target/` directory for those builds

Wow! that resolved my problem, Thanks! That's professional

**Comment by honganan** [comment]
Record another same problem caused by `target` directory mounting: Sometimes build will caught `tar：xxx achive not found.`
**Cause**
 There are command like `tar -xvf vector-0*-"$(cat /etc/apk/arch)"-unknown-linux-musl*.tar.gz --strip-components=2` in build script. If there are many tar files in `target/artifact` directory the `*` in command will match multiple files and append all of them behind the `tar` command, yet `tar` do not support multiple files, like `tar -xvf file1.tar.gz file2.tar.gz` will fail.
**Resolve**
Delete unnecessary tar file under `target/artifact/`

**Comment by jszwedko** [comment]
Closing as resolved.
