### ISSUE TITLE
sinks.clickhouse.acknowledgements.enabled不支持

### ISSUE THREAD

**Issue by hjun881** [vectordotdev/vector#14919]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

* 我的配置如下:
```yml
[sinks.sinks_ck_nginx_log_v2_v1]
type = "clickhouse"
inputs = ["transforms_remap_nginx_log_v2"]
host = "http://127.0.0.1:80"
batch.max_events = 10000
batch.timeout_secs = 2 
database = "ops_logs"
table = "nginx_local" 
auth.strategy = "basic"
auth.user = "log_clickhouse"
auth.password = "log_clickhouse"
healthcheck.enabled = false
acknowledgements.enabled = true
encoding.only_fields = ["timestamp","server_name","ip_address","log_type","cluster","host","remote_addr","request_length","request_time","time_local","uri","status","body_byte
s_sent","args","request_method","request_body","http_referer","http_user_agent","upstream_response_time","upstream_addr","upstream_status","monitor","business"]
compression = "none"
```

* 报错如下:
```
x unknown field `acknowledgements`, expected one of `endpoint`, `table`, `database`, `skip_unknown_fields`, `compression`, `encoding`, `batch`, `auth`, `request`, `tls` for key `sinks.sinks_ck_nginx_log_v2_v1` at line 100 column 1
```

* > [参考的官方文档](https://vector.dev/docs/reference/configuration/sinks/clickhouse/)

### Version

vector 0.20.1 (x86_64-unknown-linux-gnu 38b806e 2022-04-07)

**Comment by jszwedko** [comment]
Hi @hjun881 . I think that configuration option is not available on the version of Vector you are running. Can you please try again with the latest version, v0.24.2? I'll close this, but please leave a comment if it still isn't working for you.
