### ISSUE TITLE
chore(config, docs): handle initial integration of newly auto-generated source documentation into existing Cue

### ISSUE THREAD

**Issue by tobz** [vectordotdev/vector#14998]
Once #14814 is completed and we have a way to generate (near-)equivalent Cue documentation from the configuration schema itself, we need to tweak the existing Cue documentation to utilize it.

## Main Outcomes

- We should have a repeatable way to build the auto-generated documentation and then merge it into the "existing" Cue documentation, specifically for sources.
- We should maintain all of the other "custom" attributes and data currently present: we only want to use the auto-generated data for field-related documentation, not things like status badges, or "How It Works", etc.

## List of sources to convert

- [x] Convert the `amqp` source to use auto-generated docs @StephenWakely 
- [x] #15837
- [x] #15669
- [x] #15670
- [x] #15671
- [x] #15672
- [x] #16050
- [x] #15825
- [x] #15830
- [x] #15673
- [x] #15838
- [x] #15839
- [x] #15840
- [x] #15674
- [x] #16058
- [x] #15902
- [x] #15675
- [x] #15841
- [x] #16053
- [x] #16037
- [x] #15894
- [x] #16002
- [x] #15676
- [x] #15842
- [x] #15677
- [x] #16055
- [x] #15843
- [x] #15980
- [x] #15844
- [x] #15668
- [x] #15845
- [x] #15984
- [x] #16015
- [x] #16075
- [x] #16001
- [x] #16078
- [x] #15888
- [x] #15846
- [x] #16097
- [x] #15661

(This is naturally a follow-on of #14815)

**Comment by tobz** [comment]
# Conversion guide!

The process of "converting" a component to use the machine-generated Cue documentation essentially boils down to removing the configuration data in the "existing" Cue file, and replacing it with a link to merge in the machine-generate "base" Cue file. There's some additional, context-specific changes you'll likely have to make to bring the machine-generated Cue documentation up to parity with what already exists.

We'll run through pretending we're going to convert the `file` source.

## Ensuring the machine-generated Cue documentation is up-to-date

Before starting, and after _every change to the Rust source_, you'll need to run `make generate-component-docs`. This will re-compile Vector, use the resulting debug binary to generate the configuration schema output (which gets written to `/tmp/vector-config-schema.json`), and then run `scripts/generate-components-docs.rb` against that generated configuration schema. All of the machine-generated Cue files will be regenerated, and you should see changes to a given component reflected in the corresponding Cue file.

## Finding the relevant files

All of the Cue files for the user-facing documentation live under `website/cue/reference`. For components specifically, they're nested one level down, in `website/cue/reference/components`. You'll want to start by opening both the "existing" and the "base" Cue files. The "existing" Cue file is the one currently powering the user-facing documentation, and the "base" one is the one that's machine-generated and _only_ deals with configuration fields, and none of the other stuff: status labels, "How It Works", etc.

For the `file` source, the existing file is `website/cue/reference/components/sources/file.cue` and base file is `website/cue/reference/components/sources/base/file.cue`. This pattern holds true for all components, if you substitute `source` for whatever the component type is: `source`, `transform`, or `sink`.

I find opening the files up side-by-side works well for cross-referencing between the two, but it's up to you, obviously.

## Truing up the machine-generated output

Before we actually do the conversion to merge in the base Cue file, we'll want to "true up" the machine-generated output itself. With the files open side-by-side, you'll find the `configuration` section of the Cue data, and you should see similar (identical, if you're lucky!) fields listed out. What we want to do here is get these as close as we reasonably can, unless the machine-generated output is actually superior.

Let's walk through some examples below.

## Common discrepancies and how to approach them

### Field titles/description with different formatting

This one is pretty straightforward. During the original work to add the configuration schema support to the source code, much of the existing Cue documentation was ported, in terms of field titles/descriptions, back into the source. For example, the `file` source has a field called `data_dir` which in the current documentation reads as:

> The directory used to persist file checkpoint positions. By default, the global `data_dir` option is used. Please make sure the Vector project has write permissions to this dir.

In the machine-generated documentation for the same field, we have:

> The directory used to persist file checkpoint positions.
>
> By default, the global `data_dir` option is used. Please make sure the user Vector is running as has write permissions to this directory.

This is identical except for the formatting/line breaks. In general, we should **prefer** to break up field titles/descriptions. It makes reading things easier. That's why it's this way in the doc comments in the source code.

If you see any existing doc comments in the source that are more like the first example, don't be afraid to break them up a little. There's usually some intuitive rhyme and reason to how/when to split, such as if there's a sentence about what the default value/behavior is, or what happens if a field is enabled/disabled, etc.

Also don't forget that all doc comments must have the triple forward slash (`///`) in order to be picked up for/inserted into the configuration schema. That also means that if you see TODOs or developer-only notes in the doc comments, you should change them to use the double forward slash syntax (`//`) instead, which will exclude them from being added to the configuration schema.

### Field titles/descriptions with wildly different content

Like the above example, some license was taken when porting over the existing Cue documentation in order to clarify wording and present a more consistent "voice" throughout the documentation. This also included leaning on the ability to "derive" a field's title/description from the underlying field type.

For example, the `acknowledgements` derives its title/description from the implementation of `SourceAcknowledgementsConfig` itself. This is so that common types, such as `SourceAcknowledgementsConfigi` or the various encoding/decoding types, TLS, and so on, can specify a single, vetted title/description that all components are able to benefit from. However, not all of these derived types have a suitable title/description.

In some cases, the doc comments may have been written with more of a developer mindset, providing details and terminology that will never be relevant to users, and even if it's technically accurate, we might end up wanting to massage the wording to better suit the user-facing documentation.

In these scenarios, you generally have two options:

- adjust the doc comments directly
- override the doc comments by using `#[configurable(title = "...")]` or `#[configurable(description = "...")]`

In some cases, the way we would word the user-facing documentation for a particular type may fit well with the developer-facing doc comments, and so writing those doc comments is an acceptable approach to take. In other cases, such as `SourceAcknowledgementsConfig`, the developer-facing and user-facing documentation has good reason to be meaningfully different: the type exists to paper over us deprecating setting acknowledgement behavior on sources themselves. We want the developer-facing documentation to acknowledge this, so that developers understand why it exists (even though it looks like a redundant version of `AcknowledgementsConfig` that should be refactored/deduplicated away). We also want the user-facing documentation to explain the intended behavior, as well as carry a message that setting acknowledgement behavior on sources is deprecated.

In order to do this, we use the aforementioned helper macros to override what the configuration schema uses for the title/description, which lets us leave the developer-facing documentation as-is. That looks roughly like this:

```rust
/// Source-specific end-to-end acknowledgements configuration.
///
/// This type exists solely to provide a source-specific description of the `acknowledgements`
/// setting, as it is deprecated, and we still need to maintain a way to expose it in the
/// documentation before it's removed while also making sure people know it shouldn't be used.
#[configurable_component]
#[configurable(title = "Controls how acknowledgements are handled by this source.")]
#[configurable(
    description = "This setting is **deprecated** in favor of enabling `acknowledgements` at the [global][global_acks] or sink level. \
Enabling or disabling acknowledgements at the source level has **no effect** on acknowledgement behavior.

See [End-to-end Acknowledgements][e2e_acks] for more information on how Vector handles event acknowledgement.

[global_acks]: https://vector.dev/docs/reference/configuration/global-options/#acknowledgements
[e2e_acks]: https://vector.dev/docs/about/under-the-hood/architecture/end-to-end-acknowledgements/"
)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct SourceAcknowledgementsConfig {
    /// Whether or not end-to-end acknowledgements are enabled for this source.
    enabled: Option<bool>,
}
```

It's not the prettiest thing, but you'll note how we override both the title and description, and go as far as using normal Markdown syntax to provide links and emphasis when mentioning that the setting is deprecated.

**Comment by neuronull** [comment]
Linking to the bootstrap PR that converted a couple sources, for reference: 

https://github.com/vectordotdev/vector/pull/15502

**Comment by spencergilbert** [comment]
An additional note, some of the links from the old cue files may not work when directly ported to the rust comments. [Example](https://github.com/vectordotdev/vector/pull/15699/files#diff-e959c06a6a6149821d524d5830dab8ee16c668643bda0d973ca591238b07682cL42-L43)

**Comment by spencergilbert** [comment]
I believe this can be closed @tobz @jszwedko? The conversion guide is a nice piece of documentation if we wanted to move it somewhere more permanent.

**Comment by jszwedko** [comment]
Agreed, thanks for flagging! This looks like it is complete.
