### ISSUE TITLE
Stuck file descriptors for rotated files

### ISSUE THREAD

**Issue by akunafin** [vectordotdev/vector#15067]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

vector agent is accumulating file descriptors for the rotated log files:
```
1	/usr/local/bin/vector	/var/log/clusterlogs/phoenix/kphoenix-7fbd46f4f4-znc5l-phoenix-debug.log (deleted)
1	/usr/local/bin/vector	/var/log/clusterlogs/phoenix/kphoenix-7fbd46f4f4-znc5l-phoenix-debug.log (deleted)
1	/usr/local/bin/vector	/var/log/clusterlogs/phoenix/kphoenix-7fbd46f4f4-9rcjl-phoenix-debug.log (deleted)
1	/usr/local/bin/vector	/var/log/clusterlogs/phoenix/kphoenix-7fbd46f4f4-znc5l-phoenix-debug.log (deleted)
1	/usr/local/bin/vector	/var/log/clusterlogs/phoenix/kphoenix-7fbd46f4f4-g5p8x-phoenix-debug.log (deleted)
1	/usr/local/bin/vector	/var/log/clusterlogs/phoenix/kphoenix-7fbd46f4f4-znc5l-phoenix-debug.log (deleted)
1	/usr/local/bin/vector	/var/log/clusterlogs/phoenix/kphoenix-7fbd46f4f4-g5p8x-phoenix-debug.log (deleted)
```
This seems to be the same issue described there:
https://github.com/vectordotdev/vector/issues/3440

### Configuration

vector source config:
```
[sources.phoenix_source_debug]
  include = ["/var/log/clusterlogs/phoenix/*debug*.log"]
  type = "file"
  ignore_older = 10800
  [sources.phoenix_source_debug.multiline]
      start_pattern = '(INFO|DEBUG|WARN|ERROR|TRACE)'
      mode = "halt_before"
      condition_pattern = '(INFO|DEBUG|WARN|ERROR|TRACE)'
      timeout_ms = 1000
```

### Version

0.21.1

### Additional Context

In the agent logs I'm constantly getting the WARN messages like this:
```
Internal log [Found line that exceeds max_line_bytes; discarding.] has been rate limited 2 times.
Found line that exceeds max_line_bytes; discarding. internal_log_rate_secs=30
```
However, I don't think it is related to that problem.

### References

#3440

**Comment by bruceg** [comment]
I think this is the same issue as #11742. Closing in favor of that issue. Please re-open if you have different context to add.
