### ISSUE TITLE
The global `timezone` option can't be set when using multiple files

### ISSUE THREAD

**Issue by rbarrois** [vectordotdev/vector#15071]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When using at least two files for vector configuration, it is impossible to set the [`timezone = ` global option](https://vector.dev/docs/reference/configuration/global-options/#timezone); vector fails with `x conflicting values for 'timezone' found`

This seems to relate to commit 9cf1ea9b08ed745e3872c1cc81757f6078c82419; I guess that, in https://github.com/vectordotdev/vector/blob/master/lib/vector-core/src/config/global_options.rs#L196-L198, one of the values is either empty, or the default value.

### Configuration

```text
==> example/source.toml <==
[sources.source0]
format = "json"
interval = 1.0
type = "demo_logs"

[sinks.sink0]
inputs = ["source0"]
target = "stdout"
type = "console"
encoding.codec = "json"

==> example/vector.toml <==
timezone = "UTC"
```

### Version

vector 0.25.0 (x86_64-unknown-linux-gnu b573b51 2022-11-01)

### Debug Output

```text
2022-11-02T14:25:59.546767Z  INFO vector::app: Internal log rate limit configured. internal_log_rate_secs=10
Failed to load ["example/source.toml", "example/vector.toml"]
-------------------------------------------------------------
x conflicting values for 'timezone' found
```
```


### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

**Comment by bruceg** [comment]
Your analysis is exactly correct, and I have a unit test reproducing this. A fix will be coming shortly.

**Comment by bruceg** [comment]
As a workaround until the fix is released, you can put the same `timezone` setting in all of the configuration files. Since all the timezones are identical, there are no conflicting values.

**Comment by rbarrois** [comment]
Thanks for the incredibly quick resolution! :)
