### ISSUE TITLE
Vector decrypt kafka message

### ISSUE THREAD

**Issue by trustnote-wang** [vectordotdev/vector#15099]
Hello everyone!

I use vector get messages from kafka cluster, those messages are encrypted, how to use vector decrypt those messages?

example:

{"message":"2022-11-03T18:45:15\tv2.3\tf42997478041195387f2fcca56c4d87d\t1\t0.1100849137\t105\tCOMPILER_TYPE_UNK\tPACKER_TYPE_UNK\tSFX_NO_SFX\t\t20221102120345\tV2.3\teAEd1H1MVXUcx/Ff5xn1VTneGU/jfLd5dF0bSqPOif1k/UzZJ1Rn3eXIO9DjboalR75o/bm7Sc+kNJ+Bz8ISI/3NIllqTSVylcG/pKw1Cmoy1O+/xagq9cqxRHkPfgA/hB/Bj+Eh+InSPAyPwE/RP8MOwS9gHyvoG+zvsPuxj8Lv4QD8EQ6ykn7CPg5PKu0hGGGF/B37D6X5F+sMnUYZhufgiNI8j30B+yL2Jex/sEfZOPcYymWUq/BfVtA19HGU6/AGygT2JCvoJoqIUmdpSlvHjsaegu1ghZyGfRucrrRnoN+OfQecDe9GvwfOgU70BLVpIlqdlRyj/ld5Meo+e+FJ2DeFjfClQ717qpCr3Got/dq9Fp1H2pg/XYj200bV3G1Dag/BnlP8B/jv+NQ==\t0.9300000072\t30\t\tRELOCATABLE\tx86_64\tkamala\tqdev2\tv1.0\t2653788242175861718\t3\t131075\t2851\t305\t\t\teAFrYeNjFGaM+5/wv5yxmhEAHQgEXg==\t3312294\t101200\t\t2.0.0.26\t\tELF_FILE\tL2RhdGEva2FtYcWRlMg==","timestamp":"2022-11-03T10:45:15.586Z"}

**Comment by jszwedko** [comment]
Hi @trustnote-wang ! Have you seen the [decrypt VRL function](https://vector.dev/docs/reference/vrl/functions/#decrypt)?

**Comment by zamazan4ik** [comment]
@jszwedko is this related? https://github.com/vectordotdev/vector/issues/9924

**Comment by trustnote-wang** [comment]
Thank you @jszwedko, I know how to do it！
