### ISSUE TITLE
Compressed Vector configuration file

### ISSUE THREAD

**Issue by zvlb** [vectordotdev/vector#15100]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Kubernetes resources (configmap and secret) have a limit for data - 3Mb.
If I try to start a Vector in Kubernetes with a configuration file larger than 3 MB, I get a Kubernetes error.

### Attempted Solutions

For [Vector Operator](https://github.com/kaasops/vector-operator) I can use my [Config Reloader](https://github.com/zvlb/config-reloader), like I do [this for Logging Operator](https://github.com/banzaicloud/logging-operator/pull/1108), but it's not a "clear" solution.

I think the best solution - add a feature to Vector so that it can start with the compressed config file.

**Comment by zamazan4ik** [comment]
Could you please share, what is your use case for such huge config file? I guess such config file size is... unusual. Really interesting to hear about the real-life use-case for that.

**Comment by zamazan4ik** [comment]
Just an idea (possibly you've already tried that) - you can try to split your large config file to a bunch of smaller config files. Vector supports running with multiple provided config files.

**Comment by zvlb** [comment]
> Could you please share, what is your use case for such huge config file? I guess such config file size is... unusual. Really interesting to hear about the real-life use-case for that.

I use [Vector Operator](https://github.com/kaasops/vector-operator) in a big bare-metal Kubernetes cluster, where works many teams, and deployed many applications.
Developers deploy many CRs VectorPipeline (CR for configuring sinks/transforms/sources), and Vector Configuration file can be more, than 3Mb.
(This is a very rare case, but I came across this)



> Just an idea (possibly you've already tried that) - you can try to split your large config file to a bunch of smaller config files. Vector supports running with multiple provided config files.

I can split (1 CR VectorPipeline = 1 Kubernetes secret with configuration), but if in K8s cluster deployed 1000 CR, Operator creates 1000 secrets. It looks not very good.

I can add the feature for analyzing Vector Configuration file and splitting him if he is more than 3 Mb, but I think solutions with [Config Reloader](https://github.com/zvlb/config-reloader) look better

**Comment by zamazan4ik** [comment]
Thanks for sharing the scenario!

(spoiler: I am not a k8s expert) I still think splitting configuration into several secrets should be fine in this case. You can split it not by "1 CR = 1 k8s secret" but as "N CR = 1 k8s secret" and calculate this N dynamically (N CRs should result in the total config size strictly less than 3 Mib). I understand that it will require additional work outside, possible some N recalculations if one CR in a "shard" will grow significantly for some reason, etc.

And, honestly, introducing config compression support does not solve problem completely - it just enlarges the actual limit. We will get the same problem, when the compressed secret will grow more than the max secret size.

P.S. According to the [k8s docs](https://kubernetes.io/docs/concepts/configuration/secret/#restriction-data-size) the size limit is 1 Mib. Could you please explain a little bit more, why are you think that the actual size limit is 3 Mib?

**Comment by zvlb** [comment]
> why are you think that the actual size limit is 3 Mib

Sorry. It's my mistake. Actual limit - 1 Mb (I got [this](https://github.com/kubernetes/kubernetes/blob/master/test/integration/controlplane/synthetic_controlplane_test.go#L338) error, and think 3Mb - it's limit)


> You can split it not by "1 CR = 1 k8s secret" but as "N CR = 1 k8s secret" and calculate this N dynamically
Ok. I will add this function in Vector Operator in subsequent releases. I think it's better, then starting Vector from the compressed config.

Thanks!
