### ISSUE TITLE
Add feature to construct key-value from custom fields in `parse_cef` VRL function

### ISSUE THREAD

**Issue by ktff** [vectordotdev/vector#15154]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

It's common for CEF messages to contain pairs of custom fields such as `c6a1Label` and `c6a1` whose values are key and it's value respectively. So an example of 
```
{
   "c6a1Label":  "Device IPv6 Address", 
   "c6a1":  "2345:0425:2CA1:0000:0000:0567:5673:23b5"
}
```
actually means
```
{
   "Device IPv6 Address": "2345:0425:2CA1:0000:0000:0567:5673:23b5"
}
```

### Proposal

Add optional boolean argument `translate_custom_fields` to `parse_cef` VRL function. If set to `true` it would do translate pairs of custom fields to key value pairs. By default this would be turned off.

Custom fields mentioned in [Extension Dictionary](https://www.microfocus.com/documentation/arcsight/arcsight-smartconnectors-8.3/pdfdoc/cef-implementation-standard/cef-implementation-standard.pdf#%5B%7B%22num%22%3A219%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C72.75%2C723.75%2C0%5D) would be translated.

There is also the question of what to do with duplicates. The specification is silent on this but there were mentions that they can happen in practice as a way to transport arrays https://github.com/vectordotdev/vector/pull/14382#issuecomment-1248734812. There are two approaches:
1. Discard such log as invalid.
2. Collect duplicates into arrays.
     * This would change `parse_cef` signature from `string` to `string | array` when translation is on.

### References

CEF version 26 https://www.microfocus.com/documentation/arcsight/arcsight-smartconnectors-8.3/pdfdoc/cef-implementation-standard/cef-implementation-standard.pdf

Follow-up to discussion in #14382

@sim0nx @hhromic @fuchsnj @spencergilbert 

### Version

vector 0.26.0

**Comment by sim0nx** [comment]
On the question about duplicates. I must admit that I have never seen those over various different CEF type logs.
I would highly suggest to go for 1) as noted in https://github.com/vectordotdev/vector/pull/14382#issuecomment-1249628346 this would not be the first time this is done.

Also using *reroute_dropped* these events are not entirely dropped if so wanted and can be processed in a different way.

**Comment by hhromic** [comment]
Despite me advocating before on returning arrays for duplicate keys, after thinking this more I fully agree with @sim0nx that nowadays Vector allows for easily re-routing discarded data and thus can be handled (either reporting or routing somewhere).

So I would also go for option (1) indeed because bad data can be cleanly captured 👍.

**Comment by r4zr1** [comment]
It doesn't work with this log https://docs.imperva.com/bundle/cloud-application-security/page/more/log-file-structure.htm

Maybe because the use more than 5 cs fields

**Comment by ktff** [comment]
> Maybe because the use more than 5 cs fields

@r4zr1 that's probably the cause. It only recognizes fields from [Extension Dictionary](https://www.microfocus.com/documentation/arcsight/arcsight-smartconnectors-8.3/pdfdoc/cef-implementation-standard/cef-implementation-standard.pdf#%5B%7B%22num%22%3A219%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C72.75%2C723.75%2C0%5D).
