### ISSUE TITLE
Azure Blob sink cannot be configured with connection_string

### ISSUE THREAD

**Issue by dekelpilli** [vectordotdev/vector#15214]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

`connection_string` in the `azure_blob` sink is parsed as `**REDACTED**` instead of as the actual string value. An instance with an Azure Blob sink configured with a connection string will fail to start up.

### Configuration

```text
"my-sink": {
      "encoding": {
        "codec": "json"
      },
      "connection_string": "DefaultEndpointsProtocol=https;AccountName=accountNameHere;AccountKey=accountKeyHere;EndpointSuffix=core.windows.net",
      "request": {
        "retry_attempts": 1
      },
      "framing": {
        "method": "newline_delimited"
      },
      "type": "azure_blob",
      "compression": "none",
      "batch": {
        "max_bytes": 16777216,
        "timeout_secs": 1
      },
      "container_name": "private",
      "inputs": ["my-xform"],
      "blob_prefix": "blob/%F/"
    },
```

### Version

0.25.1

### Debug Output

```text
Sink "my-sink": no key/value found in connection string: **REDACTED**
```

### Additional Context

This bug was not present in 0.24.2. I believe this problem is cause by [this line of code](https://github.com/vectordotdev/vector/blob/05f57e49e95bf1be6e5c2ade21633bdbe5464898/src/sinks/azure_blob/config.rs#L139), which should instead be

```rs
self.connection_string.map(|v| String::from(v))
```

Alternatively, `SensitiveString` could be modified to be converted correctly when called with `.to_string()`

### References

- https://github.com/vectordotdev/vector/discussions/15170

**Comment by ctorrisi** [comment]
Some additional information:

This bug seems to be the cause of the error raised in a recent Discussion #15170.

A similar issue was raised in Pull Request #13453 referenced by this [comment](https://github.com/vectordotdev/vector/pull/13453#issuecomment-1259640088) comment regarding the `storage_account` configuration but was mitigated by reverting `storage_account`'s type to `Option<String>`.
