### ISSUE TITLE
Put `parses_sink_full_es_aws` test behind a feature flag or use `localstack`

### ISSUE THREAD

**Issue by a-rodin** [vectordotdev/vector#1527]
Currently running `cargo test` on a machine which doesn't have AWS credentials yields the following error:

```
---- parses_sink_full_es_aws stdout ----
thread 'parses_sink_full_es_aws' panicked at 'called `Result::unwrap()` on an
`Err` value: ["Sink \"out\": Could not generate AWS credentials:
CredentialsError { message: \"Couldn\\\'t find AWS credentials in environment,
credentials file , or IAM role.\" }"]', tests/config.rs:599:5
```

I think we should allow the tests running by default by `cargo test` pass locally without requiring AWS credentials to be present. For example, this test had to be [disabled for `nix`](https://github.com/timberio/vector/blob/560644d4f27c4b8bb245eb0fc9f0b4a88a24fd48/distribution/nix/default.nix.erb#L58), which made the `nix` expression know some of details of Vector's internals, so that renaming this test would break the `nix` expression.

I think we could do one of the following:

* put this test behind a separate `aws` feature flag;
* put it behind `docker` feature flag and use `localstack`;
* change the implementation, so that no AWS credentials needed at all.

@LucioFranco what do you think?

**Comment by LucioFranco** [comment]
@a-rodin we should implement a custom provider that wraps the `DefaultCredentialsProvider` that in `cfg(test)` will mock out credentials.

**Comment by LucioFranco** [comment]
A work around on machines I've been doing is adding fake creds to my env which works but isn't ideal.

**Comment by lukesteensen** [comment]
Whether or not we decide to write a custom provider in the future, it's nice not to leave things like this lying around. I've opened #1595 to do the easy cleanup for now.

**Comment by jszwedko** [comment]
This no longer seems to be the case. It doesn't try to connect when running this test.
