### ISSUE TITLE
Improve `aggregate` transform performance with concurrency

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#15298]
The `aggregate` transform runs as a task transform, which reduces it to running as a single task. In the presence of large numbers of metrics, this can cause it to become a bottleneck. We should investigate sharding the data across a set of threads which would do the aggregation separately.

One suggested scheme would be to hash the series name (includes namespace, name, and tags), and use that value to determine the thread to pass off too. If this hash is passed along with the metric, we may be able to reuse it to determine the hash table entry, avoiding hashing twice.

**Comment by jszwedko** [comment]
Closing this in-lieu of https://github.com/vectordotdev/vector/issues/11857 but the notes here are good.
