### ISSUE TITLE
Allow using VRL for test inputs

### ISSUE THREAD

**Issue by mikelorant** [vectordotdev/vector#15304]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Test inputs feel very difficult to use when wanting to build more functional tests. Dotted fields require quoting, top level arrays for multiple events are not possible, empty objects cannot be set and there are many more limitations.

Testing something like `throttle` just seems awkward with the current implementation (using multiple inputs unfortunately doesn't even work).

It seems like as more capabilities are added to Vector, this input method is going to become a design limitation.

### Attempted Solutions

There are many workarounds for the existing challenges. Workarounds should not need to exist. We need something that fits in with the Vector design.

### Proposal

Rather than trying to handle these limitations, why not embrace VRL as the solution?

The transforms are most often a remap which are written in VRL. The outputs are checked as VRL. It seems logical that the input be a VRL as well.

This would solve most use cases because there is no event that cannot be generated by this. Taking a use case of multiple events which require top levels arrays would become a simple task of just assigning `.` to an array containing events.

Nested events would be much clearer as these can be handled by the standard object syntax. This removes the use of flattened keys.

The most important part of this is that tests would be consistent. It would make it far easier when new transforms are introduced as it is likely the existing functions would be enough to generate the event to test the transform. The cognitive load of trying to remember the quirky test input workarounds would also be gone as now just implement it the same as elsewhere.

An example of 2 tests which demonstrate a nested event and multiple events:
```
tests:
  - name: nested event
    inputs:
      - insert_at: my transform
        type: vrl
        source: |
          some_variable = "my value"
          . = {
            "field1": "a value",
            "field2": some_variable,
            "field3": {
              "subfield": "some value"
            }
          }
    outputs:
      ...

  - name: multiple events
    inputs:
      - insert_at: my transform
        type: vrl
        source: |
          . = [
            {
              "message": "first event"
            },
            {
              "message": "second event"
            }
          ]
    outputs:
      ...
```

I think this type of solution would greatly improve the ease of testing and solve testing more unusual components such as throttle.

By leveraging the existing input type there would be no breaking change. Without knowing the details of Vector internals. this might also be even be easier to implement as it can use much of the same code used by testing outputs.

**Comment by jszwedko** [comment]
Related: https://github.com/vectordotdev/vector/issues/12886

**Comment by mjperrone** [comment]
From a random user's perspective, I like the proposal and see how it would help me with [my issues testing](https://github.com/vectordotdev/vector/issues/14853)

**Comment by MichaHoffmann** [comment]
Hey, i gave this a stab and it kinda worked well! Here is my hacky PR: https://github.com/vectordotdev/vector/pull/19107
