### ISSUE TITLE
Data gets truncated when working with HTTP source

### ISSUE THREAD

**Issue by hannan-khan-intelops** [vectordotdev/vector#15310]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Using an HTTP source, I am getting OpenTelemetry data from an OpenTelemetry Collector. The data is being received by Vector, however it is being truncated. I am currently using the `file` sink, as well as the `console` sink. The data in the file is the same as the data in the console, truncated.

### Configuration

```text
Here is the `customConfig` parameter of my values file:
customConfig:
  api:
    enabled: true
    address: 127.0.0.1:8686
    playground: true
  sources:
    otlp-http:
      type: http
      address: 0.0.0.0:80
      path: /v1/metrics
      encoding: text
  sinks:
    my_sink_id:
      type: file
      inputs:
        - otlp-http
      compression: none
      encoding:
        codec: json
      path: /tmp/vector.log
    stdout:
      encoding:
        codec: json
      inputs:
        - otlp-http
      target: stdout
      type: console
```

### Version

vector 0.25.1 (x86_64-unknown-linux-gnu 9125a99 2022-11-07)

### Example Data

Below is an example of the expected data from the OpenTelemetry Collector:
```
Metric #7
Descriptor:
     -> Name: network_stats.rx_drops
     -> Description: Number of network receive drops by the pod
     -> Unit:
     -> DataType: Gauge
NumberDataPoints #0
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-11-19 20:21:26.297145747 +0000 UTC
Value: 0
```
And here is the truncated data that is showing up in the both the `console` and `file` sinks:
```
{"message":"\u0016network_stats.rx_drops\u0012+Number of network receive drops by the pod*\u0014","path":"/v1/metrics","source_type":"http","timestamp":"2022-11-19T20:19:47.568181914Z"}
```
As you can see, it is only providing the metadata, and the actual 'Value' parameter is not being printed to console/stored in file.

**Comment by bruceg** [comment]
Do you have a sample of the input data this was fetching? Note that with the `text` encoding, each line of the input will be decoded into a separate event [as described here](https://vector.dev/docs/reference/configuration/sources/http_server/#encoding).

**Comment by hannan-khan-intelops** [comment]
@bruceg, [here](https://gist.github.com/hannan-khan-intelops/0a00c9a4563e96abc098a52ceb98fdbb) is some sample input data that is outputted by the OpenTelemetry Collector.  
I have considered that each line is decoded into a separate event, as each data point takes up two events in Vector (take a look at my [comment](https://gist.github.com/hannan-khan-intelops/0a00c9a4563e96abc098a52ceb98fdbb?permalink_comment_id=4377162#gistcomment-4377162) on the sample input data). When I view the second line however, it is filled with mainly unicode sequences, which mean nothing when converted back into text.  
Perhaps this could be an issue with how the OpenTelemetry Collector is sending the data?

**Comment by bruceg** [comment]
The Unicode sequences in the text appear to be ASCII control characters (values less than `\0020`). I suspect that what the collector is sending to Vector is different than that sample data. Is that sample data actual output from the collector that would be received by Vector, or some sample from another source? You could send the data to something like netcat (`nc -l 0 80 > filename`) to capture the actual data.

It also seems likely that this will need a [`reduce` transform](https://vector.dev/docs/reference/configuration/transforms/reduce/) to merge the multiple lines shown above into a single event.

**Comment by hannan-khan-intelops** [comment]
@bruceg, Thank you for your help so far. I've ran the `nc -l 0 80` command, and gotten the following output:
<img width="642" alt="image" src="https://user-images.githubusercontent.com/114026668/203185400-0d3c7d94-3cdb-455d-bae8-32dbb2fd4785.png">
It seems that the OpenTelemetry Collector is compressing the data using gzip. I was able to get rid of this compression, and the data is being translated much better now, however, the Unicode sequences are still present:
```
network_stats.tx_errors\u0012,Number of network transmit errors by the pod*\u0014\n\u0012\u0019�|�\u0002\u0017�)\u00171\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0012[\n\u0016network_stats.tx_drops\u0012+Number of network transmit drops by the pod*\u0014\n\u0012\u0019�|�\u0002\u0017�)\u00171\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0012Z\n\u0016
```
Is there any sort of Vector transforms for textual data? I would like to parse through the Unicode sequences in the Vector aggregator itself. I'm assuming the `Lua` transform is the only one that comes close.

**Comment by bruceg** [comment]
You might be able to do something with VRL string handling functions, but otherwise yes the `lua` transform would be your go-to for that.

**Comment by hannan-khan-intelops** [comment]
@bruceg, I'll look into VRL as well, thank you for your help.

**Comment by jszwedko** [comment]
We also plan to expand the `opentelemetry` source to accept metrics. I'll close this in-lieu of that and given the above discussion.
