### ISSUE TITLE
Multiple configuration files in the CLI, with glob pattern works only with one config under glob matching path.

### ISSUE THREAD

**Issue by zenradtski** [vectordotdev/vector#15319]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Assume we have following configuration files:
```
/etc/vector/vector.toml
/etc/vector/staging/custom_config1.toml
/etc/vector/staging/custom_config2.toml
```

and we start vector with specifying the configs from CLI:
```
/usr/local/vector/bin/vector --config /etc/vector/staging/*.toml --config /etc/vector/vector.toml
```

The start will fail with:
```
error: The subcommand '/etc/vector/staging/custom_config2.toml' wasn't recognized

Usage: vector [OPTIONS] [COMMAND]

For more information try '--help'
```

I expect to have all the files loaded

### Version

0.25.1

### Additional Context

If there is only one ```--config``` glob  parameter, all the config files matching glob pattern are properly loaded.
If there is only one file matching glob pattern and there are few other explicit paths specified with multiple ```--config``` switches, then all the configs loads properly as well. 
The issue happens when we mix multiple glob matching configuration files with explicitly given paths supplied with another ```--config``` switches.

### References

[#1445](https://github.com/vectordotdev/vector/issues/1445)

**Comment by spencergilbert** [comment]
I expect you need to quote the paths so shell expansion works properly?

```
vector --config "/etc/vector/staging/*.toml" --config "/etc/vector/vector.toml"
```

Example:

```shell
☸ minikube (default) in vector on  master is 📦 v0.26.0 via 🦀 v1.64.0
❯ vector --config "config/examples/namespacing/sources/*.toml" --config "config/examples/namespacing/transforms/*.toml" --config config/examples/namespacing/sinks/*.toml --config config/examples/namespacing/vector.toml
error: The subcommand 'config/examples/namespacing/sinks/s3_archives.toml' wasn't recognized

  Did you mean 'config'?

If you believe you received this message in error, try re-running with 'vector -- config/examples/namespacing/sinks/s3_archives.toml'

Usage: vector [OPTIONS] [COMMAND]

For more information try '--help'

☸ minikube (default) in vector on  master is 📦 v0.26.0 via 🦀 v1.64.0
❯ vector --config "config/examples/namespacing/sources/*.toml" --config "config/examples/namespacing/transforms/*.toml" --config "config/examples/namespacing/sinks/*.toml" --config config/examples/namespacing/vector.toml
2022-11-22T13:56:51.249109Z  INFO vector::app: Internal log rate limit configured. internal_log_rate_secs=10
2022-11-22T13:56:51.249249Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info,lapin=info,kube=info"
2022-11-22T13:56:51.249519Z  INFO vector::app: Loading configs. paths=["config/examples/namespacing/sinks/es_cluster.toml", "config/examples/namespacing/sinks/s3_archives.toml", "config/examples/namespacing/sources/apache_logs.toml", "config/examples/namespacing/transforms/apache_parser.toml", "config/examples/namespacing/transforms/apache_sample.toml", "config/examples/namespacing/vector.toml"]
# ...
```

Please let us know if this doesn't resolve your issue!
