### ISSUE TITLE
f64 in ValueKind

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#1532]
Here's a current definition of a `ValueKind`:

https://github.com/timberio/vector/blob/f11fedd726b4da2f20e834e24d33e084fd00e7e5/src/event/mod.rs#L203-L210

There's a `Float(f64)` variant. Having `f64` prevents us from deriving `Eq` and `Hash` for `ValueKind`, and rust is that way for [good reasons](https://internals.rust-lang.org/t/f32-f64-should-implement-hash/5436/32). For this use case, however, we probably don't want to actually have a raw `f64` here, and have a safer newtype around it, and here's why:

- `f64` can represent `NaN`s and infinities, and also +0/-0.
  We're working with serializable types here, and neither `NaN`, nor infinities make sense for the serialization, because JSON is a de-facto standard here, and it doesn't allow those.

- Having `Eq` and `Hash` is useful for a thing like [this](https://github.com/timberio/vector/blob/408c1ee28bcae56829cbc2df701e87c8f2ec0a05/src/event/discriminant.rs).

I propose replacing `f64` with a `NormalF64` newtype, that would guard the values with `val.is_normal() == true` invariant.
It would have `impl TryFrom<f64> for NormalF64` and `impl From<NormalF64> for f64`. It will also normalize the sign of 0 to always be positive.

**Comment by MOZGIII** [comment]
We can use (ordered-float])[https://crates.io/crates/ordered-float] instead of a custom newtype.

**Comment by a-rodin** [comment]
That's an interesting problem, taking into account the limitations of JSON. However, just to note, `i64` has a somewhat related problem, as some programming languages consuming JSON implicitly convert them to floats and keep only 53 bits of integer precision, so it is [considered to be a good practice to serialize large 64-bit numbers as strings](https://developer.twitter.com/en/docs/basics/twitter-ids).

> Having `f64` prevents us from deriving `Eq` and `Hash` for `ValueKind`, and rust is that way for [good reasons](https://internals.rust-lang.org/t/f32-f64-should-implement-hash/5436/32).

Why would we need to have `Eq` and `Hash` for `ValueKind` in the first place?

**Comment by MOZGIII** [comment]
In the context of this issue, encoding `f64` and `i64` as strings is also a solution. In general, I personally like this approach. It guarantees that we never have issues with precision if we don't do any transformation of the values. For simple cases (like read JSON from source and write JSON to sink) that's a truly lossless format.
Currently, I guess we'll get a parsing issue if a numeric value can't be represented as a corresponding 64 bit type, and the message will get discarded. If we make a couple newtypes to wrap float and numeric types that are capable of representing the underlying value either natively (as a corresponding 64 bit type), or as a string (if the value doesn't fit in 64 bit type) - we'll get the best of both worlds. Although, if we'll be doing transformations over the values they'll be more complicated, cause we'd have to handle this new case of when numeric values are string and e can't do arithmetic on them easily.

**Comment by binarylogic** [comment]
I'm all for precision and absolute correctness, but not when it creates an unjustified amount of work and surprising edge cases.

> If we make a couple newtypes to wrap float and numeric types that are capable of representing the underlying value either natively (as a corresponding 64 bit type), or as a string (if the value doesn't fit in 64 bit type) - we'll get the best of both worlds. Although, if we'll be doing transformations over the values they'll be more complicated, cause we'd have to handle this new case of when numeric values are string and e can't do arithmetic on them easily.

Exactly. This is _not_ worth the effort. I cannot think of an observability use case that requires this level of accuracy. 53 bits of integer precision is plenty. :)

**Comment by MOZGIII** [comment]
I agree, I mostly mentioned it for completeness, rather than as a to-go option.

**Comment by jszwedko** [comment]
Closing this since we use `NotNan<f64>` now.
