### ISSUE TITLE
Vector 0.25.2 not available from https://packages.timber.io/vector/0.25.2

### ISSUE THREAD

**Issue by archoversight** [vectordotdev/vector#15392]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

https://packages.timber.io/vector/0.25.2/

returns an empty listing and no packages/rpm's/zip files are available, yet https://vector.dev/releases/0.25.2/ says it has been released

### Version

0.25.2

**Comment by jszwedko** [comment]
Thanks @archoversight . The workflow publishing the packages is still running: https://github.com/vectordotdev/vector/actions/runs/3576657138 . We mistakenly published the website first, but usually do it second. I'll close this once they are uploaded.

**Comment by archoversight** [comment]
\o/ thank you @jszwedko
