### ISSUE TITLE
How to convert journald output to json before sending to es cluster

### ISSUE THREAD

**Issue by petermp79** [vectordotdev/vector#15417]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I am trying to export journald output to ES cluster. I tried it export to console, it seems working fine. However, when I replace the sinks with ES cluster, this sink does not allow the data to be encapsulated in JSON format. In another word, encoding.codec = "json"  is not a valid setting in Elastic search cluster. 

In this case, how can I convert transform output to json before sending it to ES index?

Please advise.

### Configuration

```text
[sources.log_file]
type = "journald"
#
# Parse Syslog logs
# See the Vector Remap Language reference for more info: https://vrl.dev        
#
[transforms.parse_logs]
type = "remap"
inputs = ["log_file"]
source = '''
. = parse_syslog!(string!(.message))
'''

## Print parsed logs to stdout
#
# This works
#
#[sinks.print]
#type = "console"
#inputs = ["parse_logs"]
#encoding.codec = "json"

[sinks.es_cluster]
type   = "elasticsearch"
inputs = ["parse_logs"]
mode = "bulk"
bulk.action = "index"
bulk.index = "dmn0"
compression = "none"
#
# This setting is not accepted in this sink
#
#encoding.codec = "json"
tls.ca_file = "/etc/elasticsearch/certs/http_ca.crt"
endpoints = [ "https://elastic:ClX9b*W07OSQ0JuRlf9R@REDACTED:9200" ] # es cluster
```

### Version

vector 0.25.1 (x86_64-unknown-linux-gnu 9125a99 2022-11-07)

### Debug Output

```text
RUST_BACKTRACE=full sudo vector -vvv --config ./vector.toml

RUST_BACKTRACE=full sudo vector -vvv --config ./vector.toml
2022-12-01T17:52:05.270140Z  INFO vector::app: Internal log rate limit configured. internal_log_rate_secs=10
2022-12-01T17:52:05.270284Z  INFO vector::app: Log level is enabled. level="vector=trace,codec=trace,vrl=trace,file_source=trace,tower_limit=trace,rdkafka=trace,buffers=trace,lapin=trace,kube=trace"
2022-12-01T17:52:05.271041Z  INFO vector::app: Loading configs. paths=["vector.toml"]
2022-12-01T17:52:05.272341Z ERROR vector::cli: Configuration error. error=unknown field `codec`, expected one of `only_fields`, `except_fields`, `timestamp_format` for key `sinks.es_cluster`
```

**Comment by jszwedko** [comment]
Hi @petermp79 !

I'm a little bit confused about what you are trying to achieve. The `elasticsearch` sink doesn't have encoding options because it has a well-defined JSON API for incoming events so the events will be sent to Elasticsearch using that API. Do you mean you want to encode the message as JSON and insert it into Elasticsearch as a raw string, instead?

**Comment by petermp79** [comment]
Hi Jesse,

Thanks for quick response. Appreciated!

So, for ES sink, vector will use ES API that encapsulates events in JSON before sending to ES cluster. The input data can be raw string data, correct? As you can see from the toml file, I tried to send journald log data to an index (dmn0) on Es for viewing. For each line of log, I use parse_syslog for transforming it into kv pairs before injecting into ES sink. That's what I am trying to do.

**Comment by jszwedko** [comment]
Hey! Yeah, that looks right, it should result in structured data ending up in ES.

**Comment by petermp79** [comment]
Thanks, Jesse for confirmation. Issue closed.
