### ISSUE TITLE
Secrets don't work when used in HTTP Sink uri

### ISSUE THREAD

**Issue by WilliamApted** [vectordotdev/vector#15414]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Limits to where secrets can be used in configuration. 

### Context:
With environment variables in vector configuration, they can be used anywhere, as long as the format `${Environment_Variable_Name:?Error if not supplied}` is followed. 

### Problem:
From the Vector documentation, my understanding would this be more or less the same when using secrets, so long as the format `SECRET[secret_backend.secretKey]` is used. 
Attempting to set the HTTP Sink Uri using a secret, as in the provided example configuration, I found this isn't the case and the secret isn't resolved. 

________________________________________

If this is intended behavior and not a bug - documentation should probably be updated to reflect the limitation of secrets. 

### Configuration

```text
secret:
  example:
    type: exec
    command: # command loading secrets here

# Sources/tramsforms ommitted for clarity

transforms:
  check_secrets:
    type: remap
    inputs:
      - example
    source: |
      .category = %category
      .testSecret = "SECRET[example.secret1]"

sinks:
  httpSink:
    type: http
    inputs:
      - check_secrets
    encoding:
      codec: json
    uri: "SECRET[example.httpsinkuri]"
```

### Version

vector 0.25.2 (x86_64-unknown-linux-gnu d690c44 2022-11-29)

### Debug Output

```text
2022-12-01T11:21:17.000094Z  INFO vector::app: Internal log rate limit configured. internal_log_rate_secs=10
2022-12-01T11:21:17.014738Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info,lapin=info,kube=info"
2022-12-01T11:21:17.029389Z  INFO vector::app: Loading configs. paths=["metadata-secrets-test.yaml"]
thread 'main' panicked at 'invalid authority: InvalidDomainCharacter', src/sinks/util/uri.rs:122:69
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5
   3: <vector::sinks::util::uri::UriSerde as core::convert::From<http::uri::Uri>>::from
   4: <vector::sinks::util::uri::UriSerde as core::convert::TryFrom<alloc::string::String>>::try_from
   5: vector::sinks::util::uri::_::<impl serde::de::Deserialize for vector::sinks::util::uri::UriSerde>::deserialize
   6: vector::sinks::http::_::<impl serde::de::Deserialize for vector::sinks::http::HttpSinkConfig>::deserialize
   7: vector::sinks::_::<impl serde::de::Deserialize for vector::sinks::Sinks>::deserialize
   8: indexmap::serde::<impl serde::de::Deserialize for indexmap::map::IndexMap<K,V,S>>::deserialize
   9: <vector::config::builder::_::<impl serde::de::Deserialize for vector::config::builder::ConfigBuilder>::deserialize::__Visitor as serde::de::Visitor>::visit_map
  10: <vector::config::loading::config_builder::ConfigBuilderLoader as vector::config::loading::loader::process::Process>::merge
  11: vector::config::loading::loader_from_paths
  12: vector::config::init_log_schema
  13: vector::app::Application::prepare_from_opts::{{closure}}
  14: vector::app::Application::prepare_from_opts
  15: vector::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by djrodgerspryor** [comment]
I'm encountering a similar problem when trying to use secret interpolation to extract some config from the environment to find the correct firehose delivery stream name.

Vector.toml
```toml
# We use vectors 'secret' config feature to get the delivery stream name dynamically
# from a script, even though it's not actually secret
[secret]

[secret.firehose]
type = "exec"
command = ["/etc/vector/get_delivery_stream_name.rb"]

...

[sinks.firehose_logs]
type = "aws_kinesis_firehose"
inputs = ["tagged_*"]
stream_name = "SECRET[firehose.name]"
encoding.codec = "json"
```

Vector is then blowing up with:
```
Jan 31 12:47:01 ip-172-31-43-188.ap-southeast-2.compute.internal vector[6459]: x Health check for "firehose_logs" failed: DescribeDeliveryStream failed: Error { code: "AccessDeniedException", message: "User: arn:aws:sts::761665997146:assumed-role/drp-test-hax/i-066ca5f9d7b2d2fbd is not authorized to perform: firehose:DescribeDeliveryStream on resource: arn:aws:firehose:ap-southeast-2:761665997146:deliverystream/SECRET[firehose.name] because no identity-based policy allows the firehose:DescribeDeliveryStream action", request_id: "fcf21b13-cfdb-44dd-a0a1-0b168fcee20d" }
```

Using:
```
vector 0.27.0 (x86_64-unknown-linux-gnu 5623d1e 2023-01-18)
```

**Comment by StephenWakely** [comment]
Yup, can confirm during the load process Vector is deserializing the config once before it replaces the secrets and deserializes again. Since it attempts to deserialize into UriSerde, it fails because the uri contains invalid character.

I'm not really sure why it does this initial deserialization.

**Comment by bruceg** [comment]
I have confirmed this happens as late as version 0.28.2, however the latest release 0.29.0 no longer exhibits the same problem.

I tracked this down to the commit f2479de665fb0e605c58decb56a28a352a0183dd which was simplifying some internals of schema handling, but also changed the ordering of deserialization of some config loading steps.
