### ISSUE TITLE
APT mirror down: "402 payment required"

### ISSUE THREAD

**Issue by lifeofguenter** [vectordotdev/vector#15445]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Seems like the APT repository is offline

```
$ curl -I https://repositories.timber.io/public/vector/cfg/setup/bash.deb.sh
HTTP/2 402 
```

```
curl -I https://repositories.timber.io/public/vector/deb/debian
HTTP/2 402 
```

Guessing this is just a payment issue with AWS and not a sign vector will not be opensource anymore? :)

### Version

n/a

**Comment by atibdialpad** [comment]
this seems to have been fixed yesterday. More details in discord.

**Comment by jszwedko** [comment]
Indeed, this should be fixed now. I'm following up to see what happened here. Thanks for the report @lifeofguenter .
