### ISSUE TITLE
`axiom` enhanced tag support

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#15523]
Note, shares underlying code with `elasticsearch`

**Comment by spencergilbert** [comment]
Blocked by https://github.com/vectordotdev/vector/issues/15425

**Comment by spencergilbert** [comment]
I don't think `axiom` actually accepts metrics, just the log-ified metrics as we do for ES. We could expose the MetricToLog config to allow users to opt-in empty and repeated tags for the final logs that get sent.

That should be supported by Axiom, but I don't know what may happen if that's changed while "live". Elasticsearch would require an index rollover due to mapping constraints, but I didn't see any details for Axiom.

Could try and reach out to them or leave it until requested? cc @jszwedko

**Comment by bruceg** [comment]
I think at this point I would leave it until requested.
