### ISSUE TITLE
Allow multiple LokiRecords with different sets of labels to be included in a single batch

### ISSUE THREAD

**Issue by atodekangae** [vectordotdev/vector#15630]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Currently, when using the Loki sink, a batch can only contain `LokiRecord`s with the same set of labels.  This means that if two records have different sets of labels, they must be placed in separate batches. However, under circumstances where records typically have different sets of labels, the current implementation results in each record requiring a separate HTTP / ProtoBuf request, leading to inefficient use of resources.

However, this restriction is not imposed by the Loki specification, but rather is a result of the current implementation. Therefore, it would be technically feasible to lift this limitation and decrease the number of HTTP requests made by allowing multiple LokiRecords with different sets of labels to be included in a single batch. 

### Proposal

The proposal can be realized by following changes:

1. Make `PartitionKey` to include only the tenant id (https://github.com/vectordotdev/vector/blob/98d687dc3828da5e15a79f2a097fd8cd80b7bf63/src/sinks/loki/event.rs#L173)
2. Change the definition of `LokiBatch` (https://github.com/vectordotdev/vector/blob/98d687dc3828da5e15a79f2a097fd8cd80b7bf63/src/sinks/loki/event.rs#L57) as follows:

```
#[derive(Debug, Default, Serialize)]
pub struct LokiBatch {
    streams_by_labels: HashMap<String, LokiStream>,   // the String key is a string representation of a set labels
    #[serde(skip)]
    finalizers: EventFinalizers,
}

#[derive(Debug, Default, Serialize)]
pub struct LokiStream {
    stream: HashMap<String, String>,
    values: Vec<LokiEvent>,
}
```

3. Change the implementation of `From<Vec<LokiRecord>> for LokiBatch` accordingly https://github.com/vectordotdev/vector/blob/98d687dc3828da5e15a79f2a097fd8cd80b7bf63/src/sinks/loki/event.rs#L65
4. Change the implementation of `Encoder<Vec<LokiRecord>> for LokiBatchEncoder` (https://github.com/vectordotdev/vector/blob/98d687dc3828da5e15a79f2a097fd8cd80b7bf63/src/sinks/loki/event.rs#L24)

I have prepared a patch that implements the changes described above, and if the maintainers find this feature enhancement to be useful, I would be happy to submit a pull request for review.

### Version

0.26.0

**Comment by spencergilbert** [comment]
Hi @atodekangae - let me take a look at this, it's been a little bit since I looked at the Loki side of things. Surface value it sounds like a good change and I'd be happy to look at your PR, but I want to double check that I'm not forgetting anything!

**Comment by atodekangae** [comment]
Thank you for your response. I have now sent a pull request for the proposed enhancement. I hope it meets your standards and I am open to any feedback or modifications that you may have. Please let me know if there are any changes that need to be made.

**Comment by spencergilbert** [comment]
Awesome, I'll take a look and hopefully we get get it merged quickly!
