### ISSUE TITLE
Gauges appear to randomly jump around in Datadog and Prometheus

### ISSUE THREAD

**Issue by derekhuizhang** [vectordotdev/vector#15683]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Gauges appear to randomly jump around in Datadog and Prometheus.

Steps to reduce:
1. Download and build (./build.sh): https://github.com/derekhuizhang/statsd-firehose
2. Run a Vector instance listening on 8125
3. Run the firehose for gauges with the **random flag enabled**, I've tried this with 10, 100, or 1000 gauges per second:
```
./statsd-firehose -countcount 0 -distcount 0 -histcount 0 -gaugecount 1 -gaugefreq 10 -random
```
```
./statsd-firehose -countcount 0 -distcount 0 -histcount 0 -gaugecount 1 -gaugefreq 100 -random
```
```
./statsd-firehose -countcount 0 -distcount 0 -histcount 0 -gaugecount 1 -gaugefreq 1000 -random
```
Result in Datadog:
<img width="821" alt="Screen Shot 2022-12-21 at 1 28 13 PM" src="https://user-images.githubusercontent.com/25254181/208977524-47da5e6b-7902-4c94-8dc2-04019ce8edfd.png">

Result in Grafana Prometheus:
<img width="1673" alt="Screen Shot 2022-12-21 at 1 33 24 PM" src="https://user-images.githubusercontent.com/25254181/208978437-4afca268-3a7b-42e7-bf3b-a3d7411dfaff.png">

However, if you check in the **console**, you will notice that the actual values are usually between -5 and 5. They never go below -20. Thus, these values should never be sent to Prometheus or Datadog.

I've also confirmed that I don't see the same behavior with datadog-agent. 

### Configuration

```text
data_dir = "/var/lib/vector"

[api]
enabled = true

[sources.statsd_metrics]
type = "statsd"
mode = "udp"
address = "127.0.0.1:8125"

[transforms.aggregate_metrics]
type = "aggregate"
inputs = ["statsd_metrics"]
interval_ms = 10000

[sinks.datadog]
type = "datadog_metrics"
default_api_key = <redacted>
inputs = [ "aggregate_metrics" ]

[sinks.prometheus]
type = "prometheus_remote_write"
endpoint = <redacted>
inputs = [ "aggregate_metrics" ]

<redacted TLS info>

[sinks.console]
type = "console"
target = "stdout"
inputs = [ "aggregate_metrics" ]

[sinks.console.encoding]
codec = "json"
```

### Version

0.26.0

**Comment by derekhuizhang** [comment]
Hm, so I think this may be related to the way negative gauges are considered deltas, rather than as independent values?  It appears what is happening is that positive values are being reported fine, and then negative values are being added as deltas on top of the last negative value.

Not sure why Vector sends the gauge as a delta of the last negative value tho, does this have to do with aggregation? Then it's a bit weird to me why the console values look fine.

Is this just the default behavior of the Datadog/Prometheus API to just add negatives to the delta of the last submitted negative gauge value if a negative gauge value is submitted? If so, that's very weird and doesn't seem to be documented anywhere

https://github.com/statsd/statsd/blob/master/docs/metric_types.md#gauges

**Comment by derekhuizhang** [comment]
Gotcha, I think the confusion came because my statsd firehose is sending in **dogstatsd**, which supports negative gauges, whereas statsd parses the negative sign before the gauges differently.
1. Is there any plan to support dogstatsd as a source, or a configuration option with statsd?
2. If not, is there a workaround I can use to get the negative gauges to appear in DD or Prometheus?

I want to say I can use the lua transform, but I'm not sure if this would work if the statsd transformation (eg. the conversion to a delta) happens at the sink sending level or the source level, given that we are supposed to be sending dogstatsd to Datadog. Are there any other alternatives or ideas you can think of?

**Comment by derekhuizhang** [comment]
I managed to figure it out in the Lua transform, but would still appreciate if we could get dogstatsd as an option!

**Comment by jszwedko** [comment]
Glad you got it working @derekhuizhang ! I opened https://github.com/vectordotdev/vector/issues/15741 to track dogstatsd support.
