### ISSUE TITLE
Possible incorrect fingerprint calculation in `file` source

### ISSUE THREAD

**Issue by Ilmarii** [vectordotdev/vector#15700]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hello!
I think we found an interesting thing.
According to the docs, only the first line should be used when calculating a fingerprint of a file in `file source`.
However, now the CRC is calculated over the first line padded with zeros to the length of `max_line_bytes`.
https://github.com/vectordotdev/vector/blob/45403e64018c02b353b49b86cf2be4863b2a64dc/lib/file-source/src/fingerprinter.rs#L96-L100
This looks like a bug to me, because changing `max_line_bytes` will change all fingerprints of existing files.
And I assume checksum should only be calculated on the data read.

It also causes a lot of performance damage, especially if you increase max_line_bytes (as we did).
In our deployment with max_line_bytes increased to 1 MB, profiling shows that CRC checksum calculation takes ~30% of the time.
![checksum](https://user-images.githubusercontent.com/86586309/209203349-e6b09f72-c539-4e8b-90c9-97328152ea5e.png)

Also it affects `kubernetes_log` source since it uses `FileServer` from `file source` internally. 
(@spencergilbert sorry, i tag you because of k8s)

My guess is that the fix will require more than just the correct length for the checksum calculation, but also adding a new variant to `FingerprintStrategy` and to the [maybe_upgrade](https://github.com/vectordotdev/vector/blob/45403e64018c02b353b49b86cf2be4863b2a64dc/lib/file-source/src/checkpointer.rs#L164) function, otherwise existing log files will be marked as new when updating to version with fix.

Please tell me if my reasoning is correct and I'll be happy to make a pull request.

### Configuration

```text
[sources.kubernetes_logs]
      type = "kubernetes_logs"
      max_line_bytes = 1048576
```

### Version

0.25.2

**Comment by zamazan4ik** [comment]
Disclaimer: I am not a Vector developer.

I agree with you that it looks like a bug. IMO `max_line_bytes` shouldn't affect the checksum.

Regarding strategy, how it could be fixed... Well, seems like your suggestion with `FingerprintStrategy` is the only way to preserve the backward compatibility in some way if we care about it. The only con is that it will increase a little bit maintenance burden. Later, we will be able to deprecate the old (current) strategy as buggy, and users will have enough time to migrate their configs to the new strategy.

Another option is just changing the existing sources and writing about it a warning in the release.

**Comment by jszwedko** [comment]
Thanks for this report @Ilmarii !

I think the issue here is just with the 0-padding. I think users would expect [max_line_bytes](https://vector.dev/docs/reference/configuration/sources/file/#max_line_bytes) to apply to fingerprinting too as the intention of this option is to protect against malformed files that don't have newlines, which matters during fingerprinting too.

I can see how the 0-padding changing would affect the checksums too, though, even if the actual bytes in the file didn't change.

**Comment by zamazan4ik** [comment]
Agree. I think we need here just eliminate zero-padding with the option.

**Comment by Ilmarii** [comment]
Agree with both of you. I tried to add a smooth auto-upgrade to the new version with the correct checksum calculation without zero-padding.
