### ISSUE TITLE
Ensure all sinks have a *good* default log level

### ISSUE THREAD

**Issue by LucioFranco** [vectordotdev/vector#1570]
We should setup all the sinks and run them to ensure that all the log levels make sense. I would suggest this is done by someone that didn't originally add the initial logs so that we can get a different opinion.

Reference https://github.com/timberio/vector/pull/1564#pullrequestreview-346639409

**Comment by jszwedko** [comment]
Closing this as stale. We can let new issues pop up for any odd logging.
