### ISSUE TITLE
Add ignore_older for kubernetes_logs

### ISSUE THREAD

**Issue by iishabakaev** [vectordotdev/vector#15738]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

A simple example: if I switch from fluent-bit to vector, I have a situation where the vector reads all the logs from the very beginning, which causes big problems for kafka \ ELK with existing logs.

### Proposal

Need functionality like in file sources 
https://vector.dev/docs/reference/configuration/sources/file/#ignore_older_secs

As I see it, this functionality has already been pre-prepared, but is not active.
https://github.com/vectordotdev/vector/blob/master/src/sources/kubernetes_logs/mod.rs#L646

**Comment by zamazan4ik** [comment]
@iishabakaev I think in your case you will need also this option: https://github.com/vectordotdev/vector/blob/master/src/sources/kubernetes_logs/mod.rs#L640

I suppose we could add both options to the Kubernetes source: `ignore_older` and `read_from` - both of them are useful.  `ignore_older` allows us to process only the latest N logs with a new Vector instance (according to the case from @iishabakaev ), `read_from` allows us completely remove logs duplication in the target system. `read_from` will work in the absence of checkpoint (as it done in `file` source). When the checkpoint will be created, Vector continues reading from the latest checkpoint position regardless `read_from` property.
