### ISSUE TITLE
HMAC sha256

### ISSUE THREAD

**Issue by sidenkoaleksandr** [vectordotdev/vector#15758]
Hello, Please add HMAC sha256

**Comment by jszwedko** [comment]
Hi @sidenkoaleksandr !

I think this issue is lacking enough detail about what you want to be added to Vector. Can you please open a new request using the [feature request template](https://github.com/vectordotdev/vector/issues/new?assignees=&labels=type%3A+feature&template=feature.yml)? Thanks!
