### ISSUE TITLE
Add agent info to the sink 

### ISSUE THREAD

**Issue by suikast42** [vectordotdev/vector#15767]
### A note for the community

I am using filebeat from elasticsearch with the elastic common schema. 
I try to addopt vector as the new logshipper.  

vectroy allready adds some metada to the sink logs like hostmeta data. 

is there a easy setup for add some meta data about the agent itself. For example 

```proto
message Agent {
  message Build {
    string original = 1;
  }

  Build build = 1;
  string ephemeral_id = 2;
  string id = 3;
  string name = 4;
  string type = 5;
  string version = 6;
}
```

**Comment by jszwedko** [comment]
Hi @suikast42 !

Do you mean you want to annotate each log flowing through Vector with this information?

**Comment by suikast42** [comment]
Exactly that.
Wit a lot of agents in the landscape that can help to observe which versrions are runing oh which nodes.

**Comment by jszwedko** [comment]
Gotcha, thanks for confirming! In that case, I think this issue is covered by https://github.com/vectordotdev/vector/issues/5860 . Please feel free to leave any additional thoughts there!

**Comment by suikast42** [comment]
> Gotcha, thanks for confirming! In that case, I think this issue is covered by #5860 . Please feel free to leave any additional thoughts there!

Great thanks and a happy new year.
