### ISSUE TITLE
Bump version after releasing to avoid failed CI checks

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#1578]
We should bump the version as part of the release process to avoid:

https://circleci.com/gh/timberio/vector/78546

**Comment by a-rodin** [comment]
Could we use GH Actions to create PRs bumping the version?

**Comment by binarylogic** [comment]
Yep, that works for me. We should use the semantic commit information to determine which version to bump to.

**Comment by jszwedko** [comment]
Closing since this is part of the release process, albeit a manual step.
