### ISSUE TITLE
Multiline parsing of events resulting in multiple events being merged

### ISSUE THREAD

**Issue by chidambaranathan-karthikeyan** [vectordotdev/vector#15852]
We have multiline events and this events extend up-to 350 lines (upto 50000 characters). 

During our peak load, logging increases. When the logging increases, we see large number of cases where events are merged. This is not a merge where one event has two requests  one after another. In this case, the events are interlaced (i.e say lines 1-10 of first event followed by 20-30 lines of second event, then some lines of first event and then some lines of second). This pattern of interlacing is random and there is no specific pattern.

Multi line parsing regex is correct. Since the same regex works when the volume of logging is low. 

Vector version - 0.22.3 (cannot update to latest version, since we run CentOS 7 and future versions require CentOS).

Vector sink configuration 

[sinks.XXXX]
 type = "elasticsearch"
 inputs = ["add_fields"]
 doc_type = "_doc"
 healthcheck = true
 endpoint = "XXXXXX"
 id_key = "id"
 bulk.index = "XXXXX"
 bulk.action = "create"
 compression = "gzip"
 auth.strategy = "basic"
 auth.password = "XXXXX"
 auth.user = "XXXXX"

# Batch
 batch.max_size = 10490000
 batch.timeout_secs = 1

 # Buffer
 buffer.type = "memory"
 buffer.max_events = 100
 buffer.when_full = "drop_newest"

 # Request
 request.rate_limit_duration_secs = 1
 request.rate_limit_num = 5
 request.retry_attempts = 3
 request.retry_initial_backoff_secs = 1
 request.retry_max_duration_secs = 10
 request.timeout_secs = 60

 # TLS
 tls.verify_certificate = false
 tls.verify_hostname = false

**Comment by spencergilbert** [comment]
Hi @chidambaranathan-karthikeyan - can you share your complete config, redacting anything sensitive?

**Comment by jszwedko** [comment]
Closing due to lack of response, but feel free to reopen if you are still experiencing this. We would need all of the usual data we collect for bug reports: https://github.com/vectordotdev/vector/issues/new?assignees=&labels=type%3A+bug&template=bug.yml

Re:

> Vector version - 0.22.3 (cannot update to latest version, since we run CentOS 7 and future versions require CentOS).

You should actually be able to upgrade now. The latest release of Vector should work on CentOS 7 (for x86_64 at least).
