### ISSUE TITLE
Datadog Source should have check_run and intake endpoints

### ISSUE THREAD

**Issue by datsabk** [vectordotdev/vector#15897]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

When sending data from Datadog agent to Vector, the requests to endpoints - `/api/v1/check_run` and `/intake` - This leads to a lot of content in the logs and potentially an issue in some internal Datadog agent working. 

### Proposal

We should proxy such endpoints from Datadog source directly out to Datadog in order to be able to support Datadog Agent -> Vector connection effectively. 

This will allow us a lot of granular control on what system metrics get sent out to Datadog and thereby control the amount of active series alongside. 

### Version

0.25.2

**Comment by jszwedko** [comment]
Hi @datsabk !

Thanks for this request. I just wanted to clarify what you are looking for. Is the issue that you have configured your Datadog Agent to forward to Vector ([via the `vector` options](https://vector.dev/docs/reference/configuration/sources/datadog_agent/#configuring-the-datadog-agent)) and it is also trying to hit those routes? Or is it that you would _like_ to forward the data sent to those routes through Vector, but cannot currently do so. Could you share your Datadog Agent configuration? That might help clear things up.

**Comment by datsabk** [comment]
Ah - I was trying to simply update the Datadog url to point to vector. Using vector options makes sense. Let me try that and get back. 

In case you are aware of it, if I configure the vector options , does it skip the check run and intake endpoints or keeps sending those requests to Datadog directly?

**Comment by jszwedko** [comment]
> In case you are aware of it, if I configure the vector options , does it skip the check run and intake endpoints or keeps sending those requests to Datadog directly?

Yeah, that's right, it will only forward the configured data types to Vector. The other routes will continue going directly to Datadog.

**Comment by datsabk** [comment]
Awesome. Closing this in that case. Will try that out and report back if things don't work

**Comment by datsabk** [comment]
@jszwedko - The option you mentioned mandates the use of Observability pipelines. What if I wish to directly forward data from Datadog agent (running in k8s cluster) to Vector ? The [only option](https://github.com/DataDog/helm-charts/blob/02c78a0993d7b9e3bea3170d7abacbdba2879003/charts/datadog/values.yaml#L118) is dd_url attribute in the helm chart. 

This is why we need these endpoints to be proxied. 

Our aim here is to be able to selectively control the system metrics being sent to Datadog without having to disable a certain AWS integration entirely.

**Comment by datsabk** [comment]
@jszwedko looks like they changed that documentation entirely to inject their own OP worker instead. 
Gonna try if vector options still work. If not, the vector documentation might need changes

**Comment by datsabk** [comment]
Okay need to reopen this. What is happening on configuring `vector.enabled:true` is that it sends metrics to Datadog + Vector. We don't want that. We wish to route the complete metrics through Vector alone. And for that we need to change `dd_url` to vector and modify

**Comment by jszwedko** [comment]
> Okay need to reopen this. What is happening on configuring `vector.enabled:true` is that it sends metrics to Datadog + Vector. We don't want that. We wish to route the complete metrics through Vector alone. And for that we need to change `dd_url` to vector and modify metric tags

Hmm, that's definitely unexpected! Would it be possible to provide a full bug report for that: https://github.com/vectordotdev/vector/issues/new?assignees=&labels=type%3A+bug&template=bug.yml ? This is the first time we've heard of this issue so there may be something specific to your configuration that is causing it that we'll need in order to reproduce. You shouldn't need to set `dd_url`.

We can leave this issue open to track adding support for the additional endpoints, but it shouldn't be required for publishing metrics from the Datadog Agent to Vector.
