### ISSUE TITLE
Add check-spelling

### ISSUE THREAD

**Issue by jsoref** [vectordotdev/vector#15997]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Typos happen, both in PR descriptions and in docs/code. They can result in various problems.

Recognizing typos before they're merged should improve code quality and users' experience of the product.

### Attempted Solutions

@spencergilbert apparently looked into using https://github.com/crate-ci/typos but it "need[ed] more configuration up front than I could afford"

### Proposal

Deploy https://github.com/check-spelling/check-spelling (based on https://github.com/check-spelling/spell-check-this, tuned based on a discussion w/ vector.dev team).

It'll be something similar to https://github.com/jsoref/vector/commit/e8475d01f8880d34b896a24379bab309fc091d7f (but probably w/  only `jobs.spelling` and not the other jobs...)

### References

https://github.com/vectordotdev/vector/pull/15970#issuecomment-1396053282

### Version

2a7be394b4c447e048a5b415ff36f7ebf4d03934

**Comment by spencergilbert** [comment]
Thanks for opening this @jsoref - I'll note that some of the configuration with `typos` may be part of the changes you linked (https://github.com/jsoref/vector/commit/e8475d01f8880d34b896a24379bab309fc091d7f)

Based on my "informal" chats around introducing spell checking into CI we support it - with the biggest concerns/unknown of managing the tool over time. Maintaining and updating the configuration files, how often that may happen and how "tedious" it'll be.

I'll get this issue in front of the wider team and at least get a concrete set of questions and concerns we may have - or just excited approval 😄

**Comment by jsoref** [comment]
### Suggested Configuration

So, here are the changes I'd suggest atm to enable check-spelling:
https://github.com/vectordotdev/vector/compare/master...jsoref:vector:spell-check?expand=1

### Getting There

<details><summary>The 6 pushes I took to reach the above series</summary>

For reference, here's the flow of [steps](https://github.com/check-spelling/vector/actions/workflows/spelling.yml) I took to reach that branch:

1. Rebased the [spell-check commit](https://github.com/check-spelling/vector/commit/9a50eca9be81a7109fd832a142ed13833bb5330e) onto [master](https://github.com/check-spelling/vector/commit/b0d9c3f96cdeccf5cde4a5d9f5d63a95be796353) (omitting the other event handlers and jobs which I'm not recommending for a public repository at this time) as https://github.com/check-spelling/vector/commit/9a50eca9be81a7109fd832a142ed13833bb5330e
   - I missed a configuration knob (which I in removed in step 5)
   - The [job summary](https://github.com/check-spelling/vector/actions/runs/3954367775) showed:
     * Unrecognized words (3)
        * databend
        * responess
        * retured
      * Errors (1)
        [❌ forbidden-pattern](https://github.com/check-spelling/check-spelling/wiki/Event-descriptions#forbidden-pattern) 3
   - The forbidden-pattern was for ` opt in `, but while developing the spelling PR, I dropped that change as the cases used in this repository are verb phrases and not a noun. (More on this later)
2. Introduced two fixes (https://github.com/check-spelling/vector/commit/c1bfef8eb7bce2f80af38e8436a480b419669753 and https://github.com/check-spelling/vector/commit/77bd46e5a3634d6d5a45da70795d8564114f08fc), [and commented out the `opt in` pattern](https://github.com/check-spelling/vector/compare/9a50eca9be81a7109fd832a142ed13833bb5330e..88dd78e5964705f827553eb2971986fffe354611)
   - The [job summary](https://github.com/check-spelling/vector/actions/runs/3954529980) showed:
     * Unrecognized words (1)
        * databend
     * To accept ✔️ these unrecognized words as correct, run the following commands
3. I ran the command to [update the expect file](https://github.com/check-spelling/vector/commit/414351436bae3f48089270c865e9e48134b22189)
    - The file can be updated by hand (removing items that are stale and adding items that are listed in **Unrecognized words**), but I've found it's helpful to offer a command to run instead.
    - The [job summary](https://github.com/check-spelling/vector/actions/runs/3954762363) reported one other thing about an `s'zork` -- for English (the initial target of check-spelling) such items were generally not words, so they aren't treated as fatal (they're an odd ghost).
4. I added a pattern to cover [`s'zork`](https://github.com/check-spelling/vector/compare/414351436bae3f48089270c865e9e48134b22189..95f158d18fe5f2bd769eedce34c0b6dcaa4358f4)
   - The [job summary](https://github.com/check-spelling/vector/actions/runs/3954875981) showed a clean bill of health
5. I [removed a stray configuration entry](https://github.com/jsoref/vector/compare/95f158d18fe5f2bd769eedce34c0b6dcaa4358f4..7a421f5e3d3eda93b0608872b82149d63b53f7e4)
6. I'm [tuning `sarif`](https://github.com/jsoref/vector/compare/7a421f5e3d3eda93b0608872b82149d63b53f7e4..74b932a9e4042e3805195fd945a2bbe723a6d3ce)

Note that I could have easily performed all of these steps together, but I performed them separately to show their effect / be able to describe them individually (the need for step 5 was a pure oversight, I'm human).
</details>

### User Flow

Generally users will be either fixing spelling (as in step 2) or accepting words into `expect.txt` (as in step 3); occasionally adding `patterns.txt` (as in step 4) or altering the `excludes.txt` file (as noted in the commit message for https://github.com/check-spelling/vector/commit/95f158d18fe5f2bd769eedce34c0b6dcaa4358f4).

#### Hints to users

Part of the report message can be specified as part of the configuration:
https://github.com/jsoref/vector/blob/spell-check/.github/actions/spelling/advice.md -- you can put whatever advice you'd like into it (I've incrementally adjusted my default messaging over time).

### Sarif Reports

<details><summary>GitHub supports fancy `sarif` reports...</summary>

The configuration as provided here includes `sarif` reports which are a somewhat new GitHub feature for pushes and PRs w/in a single repository (but not across forks). Unfortunately they're mostly designed for security reports which means that the reports are generally only available to repository owners.

Sarif reports are nice because they provide very pretty reports:
<img width="943" alt="image" src="https://user-images.githubusercontent.com/2119212/213351774-eece84c9-19b5-4a2d-b92d-d5182e6bed8c.png">
And their data can be imported into IDEs, e.g. VSCode.

If a user forks a repository and enables workflows, they'll be able to see the reports in their fork before they make a PR to the upstream repository. As you've probably noticed, most contributors don't enable actions. 

Unfortunately, permissions aren't a dynamic part of the workflow. If `security-events: write` is a concern, the relevant configuration lines can be removed (it would be possible to create a pair of jobs one w/ and one w/o and have them use `if:` conditions based on _is fork_, but then the rest of the configuration would have to be duplicated -- this doesn't seem worthwhile).
</details>

---

Before turning it on, I'd encourage a couple of people to try playing with it, either in their own forks, or if they like they can create PRs into https://github.com/check-spelling/vector/

**Comment by spencergilbert** [comment]
Sorry for taking so long on this @jsoref - we'd be happy to approve a PR introducing this into our CI workflow. Did you want to use the existing branch you've made?

**Comment by jsoref** [comment]
Sure... lemme rebase...
