### ISSUE TITLE
`extra_field_selector` in `kubernetes_logs` does not work with annotations

### ISSUE THREAD

**Issue by igor-nikiforov** [vectordotdev/vector#15991]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We want to select pods with specific annotation `my.annotation.com/vector-agent=true` an trying using [extra_field_selector](https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/#extra_field_selector) for them.

But we getting following error:

`WARN vector::kubernetes::reflector: Watcher Stream received an error. Retrying. error=InitialListFailed(Api(ErrorResponse { status: "Failure", message: "field label not supported: \"metadata.annotations", reason: "BadRequest", code: 400 }))`

It was expected that in `extra_field_selector` we could use any field for selection on Pod metadata level. But seems it does not work like this.

### Configuration

```text
sources:
  passthrough_source:
    extra_field_selector: '"metadata.annotations=my.annotation.com/vector-agent\=true"'
```
```


### Version

0.25.1

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

**Comment by spencergilbert** [comment]
Hey @igor-nikiforov - this is actually a limitation of Kubernetes.

Field selectors have a limited set of supported fields, as noted [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/#supported-fields). `metadata.name` and `metadata.namespace` are always supported, and then support varies depending on the Resource being queried.

Sadly this support isn't documented (or I couldn't find it), but [this blog](https://hoelz.ro/blog/which-fields-can-you-use-with-kubernetes-field-selectors) listed the support as of Kubernetes `v1.20` and the fields Pod's support can be found in the code [here](https://github.com/kubernetes/kubernetes/blob/cc68c06f9cb6c70cbb840a8d7b9ca49eb223cb3f/pkg/registry/core/pod/strategy.go#L307-L328).
