### ISSUE TITLE
Error when defining request.headers for http sink

### ISSUE THREAD

**Issue by mans2singh** [vectordotdev/vector#16036]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I am trying to run a simple vector job with syslog source and http sink. I am adding request.headers as specified in the docs https://vector.dev/docs/reference/configuration/sinks/http/#request.headers.  

`{
  "Authorization": "${HTTP_TOKEN}",
  "X-Powered-By": "Vector"
}`

However, I get an error:

`2023-01-19T22:20:25.374547Z ERROR vector::cli: Configuration error. error=expected a table key, found a newline at line 24 column 21`

I have tried placing the headers in a single line (as shown below) but still get the same error.

Is this a bug or did I miss anything in the docs ? 

Thanks

Here is the complete toml:

`
[sources.dummy_logs]
type = "demo_logs"
format = "syslog"
interval = 1

[transforms.parse_logs]
type = "remap"
inputs = ["dummy_logs"]
source = '''
. = parse_syslog!(string!(.message))
'''

[sinks.logs_sink]
type = "http"
inputs = [ "parse_logs" ]
uri = "http://my-test-server.com"
method = "post"
#request.headers = { "Authorization": "MyAuthToken", "X-Powered-By": "Vector" }

request.headers = { 
  "Authorization": "MyAuthToken", 
  "X-Powered-By": "Vector" 
}

  [sinks.logs_sink.encoding]
  codec = "json"

[api]
enabled = true
address = "127.0.0.1:8686"`

### Configuration

```text
[sources.dummy_logs]
type = "demo_logs"
format = "syslog"
interval = 1

[transforms.parse_logs]
type = "remap"
inputs = ["dummy_logs"]
source = '''
. = parse_syslog!(string!(.message))
'''

[sinks.logs_sink]
type = "http"
inputs = [ "parse_logs" ]
uri = "http://my-test-server.com"
method = "post"
#request.headers = { "Authorization": "MyAuthToken", "X-Powered-By": "Vector" }

request.headers = { 
  "Authorization": "MyAuthToken", 
  "X-Powered-By": "Vector" 
}

  [sinks.logs_sink.encoding]
  codec = "json"

[api]
enabled = true
address = "127.0.0.1:8686"`
```

### Version

vector 0.25.1 (x86_64-apple-darwin 9125a99 2022-11-07)

**Comment by jszwedko** [comment]
Hi @mans2singh !

The issue seems to be with TOML syntax. A table like this works:

```
[request.headers]
"Authorization" = "MyAuthToken"
"X-Powered-By" = "Vector"
```

I think the inline table you have needs to use `=`s instead of `:` but I also couldn't get that validating using https://www.toml-lint.com/ . The example in the docs there is definitely misleading since it only shows the JSON definition.

**Comment by mans2singh** [comment]
Thanks @jszwedko for your advice.
