### ISSUE TITLE
Add ability to do one off release builds for testing

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#16104]
We've had a number of instances where it we wanted to provide custom builds to a user for deployment or testing including:

- https://github.com/vectordotdev/vector/issues/15292
- https://github.com/vectordotdev/vector/pull/16079

The only way to do that right now is executing multiple error-prone steps locally. Ideally I think we could just use CI to do this to run the same workflow that publishes our nightly and release images. This could be done as an on demand workflow that takes a git ref to build. Later we could think about also having labels we could apply to pull requests to run the workflow.

I think this would involve:

- Creating a new workflow file like [the nightly one](https://github.com/vectordotdev/vector/blob/master/.github/workflows/nightly.yml) that kicks off the [publish workflow](https://github.com/vectordotdev/vector/blob/master/.github/workflows/publish.yml)
- Updating the publish workflow to know how to deal with a new release "channel". I think we could call it "test".

**Comment by neuronull** [comment]
This was addressed by https://github.com/vectordotdev/vector/pull/17024
