### ISSUE TITLE
Regularize `vdev` integration test arguments to `cargo`

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#16147]
In the `test.yaml` file for the integration tests, every copy has an `args` list containing the same pattern:
* `--features FLAGS`
* Either `--lib` or `--test NAME`
* A test name filter (ex `::elasticsearch::`)

These should get refactored out into custom fields instead of a generic `args` block:
* A list of features
* An optional test name, if not present runs the lib tests
* A test filter string

These would be turned into the same parameters to the `cargo` command line, but under program control.

**Comment by jonathanpv** [comment]
So the direction recommended by Bruce

Figure out the representation types for the three additional fields
Put them in the integration config struct in place of the args, which is a vec of string 

Then convert one of the configs to match that data type, and it will be better to send on Slack. The yaml will be expected to look like this:

```
features: "sources-aws"
test: "shutdown"
test_filter: "::aws::"
```

The test field there should be optional, when it is not present will assume the lib part of things.
Converting one of the configs will allow me to test

Redis, and shutdown are a few that use test naming setups. So those are two to target.

Then would need to change the source file, I will need to hook into `testing/integration.rs` and `testing/runner.rs`
So in `integration.rs` `let mut args ... configure....` around there is where we will add three fields to replace the vector.

Features would be a string, test would be an optional string, test filter will be a string required.

Question:
Where does the YAML come into picture:
looking at structure derive and deserialize
`testing/config.rs`

Test will be an optional string, that will be a logic, --lib option if it is some then add --test into the name of the test

cargo vdev integration shutdown --  
cargo vdev integration redis -- 


use cargo test -- help to find out what these flags.
