### ISSUE TITLE
Vector service does not start properly

### ISSUE THREAD

**Issue by yellow1912** [vectordotdev/vector#16177]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When I tried to install vector via the installer script, the bin file was not linked to /usr/bin/vector properly, and service was not setup. 

After I have done those tasks manually, when I tried to start the service, there is no error but when I check the status it is inactive:

service vector start
service vector status
● vector.service - Vector
     Loaded: loaded (/etc/systemd/system/vector.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Sat 2023-01-28 22:35:21 +07; 2s ago
       Docs: https://vector.dev
    Process: 1519449 ExecStartPre=/usr/bin/vector validate (code=exited, status=0/SUCCESS)
    Process: 1519472 ExecStart=/usr/bin/vector (code=exited, status=0/SUCCESS)
   Main PID: 1519472 (code=exited, status=0/SUCCESS)

Jan 28 22:35:21 lead vector[1519472]: 2023-01-28T15:35:21.020581Z  INFO vector::app: Log level is enabled.>
Jan 28 22:35:21 lead vector[1519472]: 2023-01-28T15:35:21.020636Z  INFO vector::app: Loading configs. path>
Jan 28 22:35:21 lead vector[1519472]: 2023-01-28T15:35:21.021955Z  INFO vector::topology::running: Running>
Jan 28 22:35:21 lead vector[1519472]: 2023-01-28T15:35:21.022089Z  INFO vector: Vector has started. debug=>
Jan 28 22:35:21 lead vector[1519472]: 2023-01-28T15:35:21.022106Z  INFO vector::app: API is disabled, enab>
Jan 28 22:35:21 lead vector[1519472]: 2023-01-28T15:35:21.022296Z  INFO vector::topology::builder: Healthc>
Jan 28 22:35:21 lead vector[1519472]: 2023-01-28T15:35:21.022374Z  INFO vector::sources::file_descriptors:>
Jan 28 22:35:21 lead vector[1519472]: 2023-01-28T15:35:21.022456Z  INFO vector::app: All sources have fini>
Jan 28 22:35:21 lead vector[1519472]: 2023-01-28T15:35:21.022534Z  INFO vector: Vector has stopped.
Jan 28 22:35:21 lead systemd[1]: vector.service: Succeeded.

Calling vector cli manually seems to work fine though. Not sure why the service cannot run properly.

### Version

0.27.0

**Comment by jszwedko** [comment]
Hi @yellow1912 !

Thanks for this report. A few questions / comments:

* Can you share the full log output from journald? The output above seems truncated.
* Can you share the configuration you are providing to Vector? By default the service looks for it in `/etc/vector/vector.toml`.
* The installer script is only meant for user-local installs as it just downloads the tarball and puts it at `~/.vector`. I can see the documentation doesn't really make that clear though. We can adjust that. To install Vector on a "production system" I'd recommend using one of the [package manager installation options](https://vector.dev/docs/setup/installation/operating-systems/)

**Comment by yellow1912** [comment]
@jszwedko Thank you for your quick response. 

1. The output is below:

> Jan 28 23:12:35 lead systemd[1]: Starting Vector...
> Jan 28 23:12:35 lead vector[1522449]: √ Loaded ["/etc/vector/vector.toml"]
> Jan 28 23:12:35 lead vector[1522449]: √ Component configuration
> Jan 28 23:12:35 lead vector[1522449]: √ Health check "out"
> Jan 28 23:12:35 lead vector[1522449]: ------------------------------------
> Jan 28 23:12:35 lead vector[1522449]:                            Validated
> Jan 28 23:12:35 lead systemd[1]: Started Vector.
> Jan 28 23:12:35 lead vector[1522469]: 2023-01-28T16:12:35.609272Z  INFO vector::app: Internal log rate lim>
> Jan 28 23:12:35 lead vector[1522469]: 2023-01-28T16:12:35.609430Z  INFO vector::app: Log level is enabled.>
> Jan 28 23:12:35 lead vector[1522469]: 2023-01-28T16:12:35.609487Z  INFO vector::app: Loading configs. path>
> Jan 28 23:12:35 lead vector[1522469]: 2023-01-28T16:12:35.610760Z  INFO vector::topology::running: Running>
> Jan 28 23:12:35 lead vector[1522469]: 2023-01-28T16:12:35.610867Z  INFO vector: Vector has started. debug=>
> Jan 28 23:12:35 lead vector[1522469]: 2023-01-28T16:12:35.610878Z  INFO vector::app: API is disabled, enab>
> Jan 28 23:12:35 lead vector[1522469]: 2023-01-28T16:12:35.611217Z  INFO vector::sources::file_descriptors:>
> Jan 28 23:12:35 lead vector[1522469]: 2023-01-28T16:12:35.611280Z  INFO vector::topology::builder: Healthc>
> Jan 28 23:12:35 lead vector[1522469]: 2023-01-28T16:12:35.611326Z  INFO vector::app: All sources have fini>
> Jan 28 23:12:35 lead vector[1522469]: 2023-01-28T16:12:35.611331Z  INFO vector: Vector has stopped.
> Jan 28 23:12:35 lead systemd[1]: vector.service: Succeeded.

2. My configuration is below:
```
data_dir = "/var/lib/vector"

# Input data. Change me to a valid input source.
[sources.in]
  type = "stdin"

# Output data
[sinks.out]
  inputs   = ["in"]
  type     = "console"
  encoding.codec = "text"

```

3. In addition, I was upgrading from an older version (0.10.x). In the conf.d I have some additional files as well. Perhaps this is where the issue comes from?

4. If I try to run vector --config-dir /etc/vector/conf.d/ I get the following issue:

> ERROR vector::cli: Configuration error. error=unknown variant `json_parser`, expected one of `aggregate`, `aws_ec2_metadata`, `dedupe`, `filter`, `log_to_metric`, `lua`, `metric_to_log`, `reduce`, `remap`, `route`, `sample`, `tag_cardinality_limit`, `throttle` for key `transforms.app_logs_parsed`

The config that causes the error is:

```
[transforms.app_logs_parsed]
  type         = "json_parser"
  inputs       = ["app_logs"]

```

After some digging, it seems like now I have to use https://vector.dev/docs/reference/vrl/ ?
I could not find any upgrade guide, this is my attempt:

```
[transforms.app_logs_parsed]
  type         = "remap"
  inputs       = ["app_logs"]
  source = '''
      # Parse Syslog input. The "!" means that the script should abort on error.
      . = parse_json!(string!(.message))

There is also an add_fields transform that I'm not sure how I should update, should I use lua?
```

[transforms.app_logs_parsed_fields]
  type         = "add_fields"
  inputs       = ["app_logs_parsed"]
  overwrite    = false
  fields.type  = "myapp"
  fields.host  = "${HOSTNAME}"
```
  '''
```

**Comment by jszwedko** [comment]
> @jszwedko Thank you for your quick response.
> 
> 1. The output is below:
> 
> > Jan 28 23:12:35 lead systemd[1]: Starting Vector...
> > Jan 28 23:12:35 lead vector[1522449]: √ Loaded ["/etc/vector/vector.toml"]
> > Jan 28 23:12:35 lead vector[1522449]: √ Component configuration
> > Jan 28 23:12:35 lead vector[1522449]: √ Health check "out"
> > Jan 28 23:12:35 lead vector[1522449]: ------------------------------------
> > Jan 28 23:12:35 lead vector[1522449]:                            Validated
> > Jan 28 23:12:35 lead systemd[1]: Started Vector.
> > Jan 28 23:12:35 lead vector[1522469]: 2023-01-28T16:12:35.609272Z  INFO vector::app: Internal log rate lim>
> > Jan 28 23:12:35 lead vector[1522469]: 2023-01-28T16:12:35.609430Z  INFO vector::app: Log level is enabled.>
> > Jan 28 23:12:35 lead vector[1522469]: 2023-01-28T16:12:35.609487Z  INFO vector::app: Loading configs. path>
> > Jan 28 23:12:35 lead vector[1522469]: 2023-01-28T16:12:35.610760Z  INFO vector::topology:🏃 Running>
> > Jan 28 23:12:35 lead vector[1522469]: 2023-01-28T16:12:35.610867Z  INFO vector: Vector has started. debug=>
> > Jan 28 23:12:35 lead vector[1522469]: 2023-01-28T16:12:35.610878Z  INFO vector::app: API is disabled, enab>
> > Jan 28 23:12:35 lead vector[1522469]: 2023-01-28T16:12:35.611217Z  INFO vector::sources::file_descriptors:>
> > Jan 28 23:12:35 lead vector[1522469]: 2023-01-28T16:12:35.611280Z  INFO vector::topology::builder: Healthc>
> > Jan 28 23:12:35 lead vector[1522469]: 2023-01-28T16:12:35.611326Z  INFO vector::app: All sources have fini>
> > Jan 28 23:12:35 lead vector[1522469]: 2023-01-28T16:12:35.611331Z  INFO vector: Vector has stopped.
> > Jan 28 23:12:35 lead systemd[1]: vector.service: Succeeded.

This output is still truncated horizontally 😄 You can see that it cuts off each line after a certain number of characters.

> 2. My configuration is below:
> 
> ```
> data_dir = "/var/lib/vector"
> 
> # Input data. Change me to a valid input source.
> [sources.in]
>   type = "stdin"
> 
> # Output data
> [sinks.out]
>   inputs   = ["in"]
>   type     = "console"
>   encoding.codec = "text"
> ```

Gotcha, I see. If running this config via the SystemD service, Vector will just start up and then shutdown immediately because there is no input on stdin. I'm fairly sure that is what is happening here. You could try swapping out the `stdin` source for another one to verify.

> 3. In addition, I was upgrading from an older version (0.10.x). In the conf.d I have some additional files as well. Perhaps this is where the issue comes from?
> 4. If I try to run vector --config-dir /etc/vector/conf.d/ I get the following issue:
> 
> > ERROR vector::cli: Configuration error. error=unknown variant `json_parser`, expected one of `aggregate`, `aws_ec2_metadata`, `dedupe`, `filter`, `log_to_metric`, `lua`, `metric_to_log`, `reduce`, `remap`, `route`, `sample`, `tag_cardinality_limit`, `throttle` for key `transforms.app_logs_parsed`
> 
> The config that causes the error is:
> 
> ```
> [transforms.app_logs_parsed]
>   type         = "json_parser"
>   inputs       = ["app_logs"]
> ```
> 
> After some digging, it seems like now I have to use https://vector.dev/docs/reference/vrl/ ? I could not find any upgrade guide, this is my attempt:
> 
> ```
> [transforms.app_logs_parsed]
>   type         = "remap"
>   inputs       = ["app_logs"]
>   source = '''
>       # Parse json input. The "!" means that the script should abort on error.
>       . = parse_json!(string!(.message))
>       '''
> ```
> 
> There is also an add_fields transform that I'm not sure how I should update, should I use lua?
> 
> ```
> [transforms.app_logs_parsed_fields]
>   type         = "add_fields"
>   inputs       = ["app_logs_parsed"]
>   overwrite    = false
>   fields.type  = "myapp"
>   fields.host  = "${HOSTNAME}"
> ```

When upgrading from an older version of Vector, I'd recommend stepping through each minor releases' upgrade guide. In this case, you are hitting some of the removals in [v0.24.0](https://vector.dev/highlights/2022-08-16-0-24-0-upgrade-guide/#deprecated-transforms). The migration instructions are in the [v0.22.0 upgrade guide](https://vector.dev/highlights/2022-05-03-0-22-0-upgrade-guide/#deprecated-transforms) when their deprecation was announced.

Hope this helps!

**Comment by yellow1912** [comment]
Thank you very much, it seems to clear up everything now. 

I have one last question if I may. VRL is a bit confusing for me right now, I'm trying to port my code to use remap and it looks like this:

OLD:

```
[transforms.nginx_error_logs_parsed]
  type         = "grok_parser"
  inputs       = ["nginx_error_logs"]
  pattern      = '(?<timestamp>%{YEAR}[./]%{MONTHNUM}[./]%{MONTHDAY} %{TIME}) \[%{LOGLEVEL:level}\] %{POSINT:pid}#%{NUMBER:threadid}\: \*%{NUMBER:connectionid} %{GREEDYDATA:message}, client: %{IP:client}, server: %{GREEDYDATA:server}, request: "(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion}))"(, upstream: "%{GREEDYDATA:upstream}")?, host: "%{DATA:host}"(, referrer: "%{GREEDYDATA:referrer}")?'
  types.timestamp = "timestamp|%s" # timestamp conversion
```

NEW:

```
[transforms.nginx_error_logs_parsed]
  type         = "remap"
  inputs       = ["nginx_error_logs"]
  drop_on_error = false
  source = '''
  . |= parse_grok!(.message, "(?<timestamp>%{YEAR}[./]%{MONTHNUM}[./]%{MONTHDAY} %{TIME}) \[%{LOGLEVEL:level}\] %{POSINT:pid}#%{NUMBER:threadid}\: \*%{NUMBER:connectionid} %{GREEDYDATA:message}, client: %{IP:client}, server: %{GREEDYDATA:server}, request: "(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion}))"(, upstream: "%{GREEDYDATA:upstream}")?, host: "%{DATA:host}"(, referrer: "%{GREEDYDATA:referrer}")?")
  .timestamp = parse_timestamp!(.timestamp , format: "%s")
  '''
```

This gives the error:

error[E202]: syntax error
  ┌─ :1:1
  │
1 │ ╭   . |= parse_grok!(.message, "(?<timestamp>%{YEAR}[./]%{MONTHNUM}[./]%{MONTHDAY} %{TIME}) \[%{LOGLEVEL:level}\] %{POSINT:pid}#%{NUMBER:threadid}\: \*%{NUMBER:connectionid} %{GREEDYDATA:message}, client: %{IP:client}, server: %{GREEDYDATA:server}, request: "(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion}))"(, upstream: "%{GREEDYDATA:upstream}")?, host: "%{DATA:host}"(, referrer: "%{GREEDYDATA:referrer}")?")
2 │ │   .timestamp = parse_timestamp!(.timestamp , format: "%s")
3 │ │
  │ ╰──^ unexpected error: invalid escape character: \[

Is there something that I missed here?

**Comment by yellow1912** [comment]
I think I fixed it:

```
[transforms.nginx_error_logs_parsed]
  type         = "remap"
  inputs       = ["nginx_error_logs"]
  drop_on_error = false
  source = '''
  . |= parse_grok!(.message, "(?<timestamp>%{YEAR}[./]%{MONTHNUM}[./]%{MONTHDAY} %{TIME}) [%{LOGLEVEL:level}] %{POSINT:pid}#%{NUMBER:threadid}: *%{NUMBER:connectionid} %{GREEDYDATA:message}, client: %{IP:client}, server: %{GREEDYDATA:server}, request: \"(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion}))\"(, upstream: \"%{GREEDYDATA:upstream}\")?, host: \"%{DATA:host}\"(, referrer: \"%{GREEDYDATA:referrer}\")?")
  .timestamp = parse_timestamp!(.timestamp , format: "%s")
  '''
```

BTW, parse_grok does not seem to run here:

https://playground.vrl.dev/

I get:

> error[E105]: call to undefined function
>   ┌─ :1:6
>   │
> 1 │ . |= parse_grok!(.message, "(?<timestamp>%{YEAR}[./]%{MONTHNUM}[./]%{MONTHDAY} %{TIME}) [%{LOGLEVEL:level}] %{POSINT:pid}#%{NUMBER:threadid}: *%{NUMBER:connectionid} %{GREEDYDATA:message}, client: %{IP:client}, server: %{GREEDYDATA:server}, request: \"(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion}))\"(, upstream: \"%{GREEDYDATA:upstream}\")?, host: \"%{DATA:host}\"(, referrer: \"%{GREEDYDATA:referrer}\")?")
>   │      ^^^^^^^^^^
>   │      │
>   │      undefined function
>   │      did you mean "parse_glog"?
>   │
>   = learn more about error code 105 at https://errors.vrl.dev/105
>   = see language documentation at https://vrl.dev
>   = try your code in the VRL REPL, learn more at https://vrl.dev/examples
>

**Comment by jszwedko** [comment]
Great! Yeah, `parse_grok` doesn't run in the playground since it doesn't easily compile to WASM. We want to improve the error messages there to make that clearer.

It seems like everything has been resolved here so I'll close this issue, but let me know if you have any other questions!

**Comment by dss010101** [comment]
So is this now a requirement..to use VRL with latest versions?

**Comment by dss010101** [comment]
> @dss010101 `grok_parser` was deprecated in `0.22` and removed soon after. Please see [the upgrade guide](https://vector.dev/highlights/2022-05-03-0-22-0-upgrade-guide/#grok_parser) for more information.

ok thank you. i've converted my toml to the following, but have a question. In the below i have several parsing patterns.
if the 'msg' field i parse out may contain a pattern like 'app_id=app_1234', can i post parse and add 'app_id' as a field, rather than include another parser pattern for it as i do below?  It seems it would be cleaner to post parse and add optional fields that may or may not be in the msg. Are there any examples of doing this?
```
source = '''
    . |= parse_groks!(
            .message, 
            patterns:[
                "\\[%{TIMESTAMP_ISO8601:log_time}\\]\\[%{INT:process}:%{INT:thread}\\]\\[%{WORD:severity}\\]\\[%{WORD:module}.%{WORD:func}\\] app_id:%{NOTSPACE:app_id} %{GREEDYDATA:msg}",
                "\\[%{TIMESTAMP_ISO8601:log_time}\\]\\[%{INT:process}:%{INT:thread}\\]\\[%{WORD:severity}\\]\\[%{WORD:module}.%{WORD:func}\\] %{GREEDYDATA:msg}",
                "\\[%{TIMESTAMP_ISO8601:log_time}\\]\\[%{INT:process}:%{INT:thread}\\]%{WORD:severity}:%{WORD:module}:%{GREEDYDATA:msg}"
            ]
    )

'''
```
example logs with/and without app_id:
```
[2023-05-15 11:52:29,401][2555:140431094425152][INFO][default.run] initalizing application
[2023-05-15 11:52:29,401][2555:140431094425152][INFO][default.run] app_id:my_app_12345 initialized.
```

**Comment by spencergilbert** [comment]
@dss010101 please open a new GitHub discussion since this is unrelated to the original issue, thanks!

**Comment by dss010101** [comment]
done:.  glad there is a more 'discussion/support' area in this repo as opposed to solely 'issue/bugs'....

https://github.com/vectordotdev/vector/discussions/17397
