### ISSUE TITLE
Global timezone is not in effect

### ISSUE THREAD

**Issue by FengZh61** [vectordotdev/vector#16206]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I added the global timezone to the configuration file, but it didn't work!

### Configuration

```text
data_dir = "/opt/vector"
timezone = "Asia/Shanghai"
[sources.mydev]
type = "file"
ignore_older_secs = 600
include = [ "/var/log/messages" ]
read_from = "end"

[sinks.print]
type = "console"
inputs = ["mydev"]
encoding.codec = "json"
```

### Version

0.27.0

### Additional Context

{"file":"/var/log/messages","host":"mydev","message":"Jan 31 12:39:13 mydev systemd: Started Session 888 of user root.","source_type":"file","timestamp":"2023-01-31T04:39:13.366589879Z"}
{"file":"/var/log/messages","host":"mydev","message":"Jan 31 12:39:13 mydev systemd-logind: New session 888 of user root.","source_type":"file","timestamp":"2023-01-31T04:39:13.366605776Z"}
{"file":"/var/log/messages","host":"mydev","message":"Jan 31 12:39:13 mydev dbus[1181]: [system] Activating service name='org.freedesktop.problems' (using servicehelper)","source_type":"file","timestamp":"2023-01-31T04:39:13.366609303Z"}
{"file":"/var/log/messages","host":"mydev","message":"Jan 31 12:39:13 mydev dbus-daemon: dbus[1181]: [system] Activating service name='org.freedesktop.problems' (using servicehelper)","source_type":"file","timestamp":"2023-01-31T04:39:13.366612536Z"}
{"file":"/var/log/messages","host":"mydev","message":"Jan 31 12:39:13 mydev dbus[1181]: [system] Successfully activated service 'org.freedesktop.problems'","source_type":"file","timestamp":"2023-01-31T04:39:13.366617066Z"}
{"file":"/var/log/messages","host":"mydev","message":"Jan 31 12:39:13 mydev dbus-daemon: dbus[1181]: [system] Successfully activated service 'org.freedesktop.problems'","source_type":"file","timestamp":"2023-01-31T04:39:13.366620362Z"}
{"file":"/var/log/messages","host":"mydev","message":"Jan 31 12:40:01 mydev systemd: Started Session 889 of user root.","source_type":"file","timestamp":"2023-01-31T04:40:02.578485972Z"}

localtime is 2023-01-31 12:40:02

**Comment by davidhuie-dd** [comment]
According to the docs, the `timezone` configuration option is:
> The name of the time zone to apply to timestamp conversions that do not contain an explicit time zone.
Source: https://vector.dev/docs/reference/configuration/global-options/

That config value would only apply if you attempted to parse a timestamp without a timezone. Only then would the provided timezone would be used as the timestamp's timezone. However, it would just be how we represent the timestamp *internally*; Vector always outputs timestamps in UTC. 

Please feel free to make a feature request if you would like to customize the output timestamp timezones. Thanks!

**Comment by FengZh61** [comment]
> According to the docs, the `timezone` configuration option is:
> 
> > The name of the time zone to apply to timestamp conversions that do not contain an explicit time zone.
> > Source: https://vector.dev/docs/reference/configuration/global-options/
> 
> That config value would only apply if you attempted to parse a timestamp without a timezone. Only then would the provided timezone would be used as the timestamp's timezone. However, it would just be how we represent the timestamp _internally_; Vector always outputs timestamps in UTC.
> 
> Please feel free to make a feature request if you would like to customize the output timestamp timezones. Thanks!

Thanks for the answer, UTC time parsing is not convenient, I am converting the time to unix timestamp, but the unix timestamp only supports to seconds, is it considered to support to milliseconds and microseconds?

**Comment by jszwedko** [comment]
Hi @FengZh61 !

I don't think I completely understand the question. Vector's internal timestamps are not unix timestamps, they are structured types that store up to nanosecond resolution.

**Comment by FengZh61** [comment]
> Hi @FengZh61 !
> 
> I don't think I completely understand the question. Vector's internal timestamps are not unix timestamps, they are structured types that store up to nanosecond resolution.

My idea is unix timestamps store up to nanosecond resolution.But now only to seconds.

**Comment by jszwedko** [comment]
> > Hi @FengZh61 !
> > I don't think I completely understand the question. Vector's internal timestamps are not unix timestamps, they are structured types that store up to nanosecond resolution.
> 
> My idea is unix timestamps store up to nanosecond resolution.But now only to seconds.

Vector's internal timestamps can store up to nanosecond resolution. I feel like I'm missing part of the question here 😅

**Comment by FengZh61** [comment]
> > > Hi @FengZh61 !
> > > I don't think I completely understand the question. Vector's internal timestamps are not unix timestamps, they are structured types that store up to nanosecond resolution.
> > 
> > 
> > My idea is unix timestamps store up to nanosecond resolution.But now only to seconds.
> 
> Vector's internal timestamps can store up to nanosecond resolution. I feel like I'm missing part of the question here 😅

tks， I understand what you mean!

**Comment by FengZh61** [comment]
> > > Hi @FengZh61 !
> > > I don't think I completely understand the question. Vector's internal timestamps are not unix timestamps, they are structured types that store up to nanosecond resolution.
> > 
> > 
> > My idea is unix timestamps store up to nanosecond resolution.But now only to seconds.
> 
> Vector's internal timestamps can store up to nanosecond resolution. I feel like I'm missing part of the question here 😅

Hi @jszwedko new discovery!
.timestamp, err = to_float(.timestamp) can store up to nanosecond resolution!
encoding.timestamp_format="unix"   store up to second resolution!
But I need to use remap for that!

**Comment by FengZh61** [comment]
> > timestamp_format
> 
> Ah, yeah, I see. You can use `timestamp_format` with a string format to encode higher precision. If you want an option for encoding timestamps as unix timestamps with enhanced precision would you mind opening a feature request?

I will open a feature request~
