### ISSUE TITLE
Questions: count journald SYSLOG_FACILITY/PRIORITY as metrics

### ISSUE THREAD

**Issue by mhf-ir** [vectordotdev/vector#1622]
How to add prometheus counter by journald.
In need add **Log to Metric Transform** counting number of journald base on **SYSLOG_FACILITY** or **PRIORITY**

**Comment by mhf-ir** [comment]
Also may some documentation about real world use cases will be help.

**Comment by binarylogic** [comment]
@mhf-ir thanks. We're discussing and will provide help/example in a follow up comment. Regarding the docs, we're about to launch a new "Guides" section on the website that will cover more real-world examples. Additionally, we have an "automatic events to metrics" project [on the roadmap](https://github.com/timberio/vector/issues/1538) where we're going to try and make this process as easy as possible. And, of course, we're open to any feedback you have.

**Comment by jszwedko** [comment]
Closing this as stale. It is possible via the `log_to_metrics` transform.
