### ISSUE TITLE
Buffer became broken after network errors and restart

### ISSUE THREAD

**Issue by kandeshvari** [vectordotdev/vector#16231]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

k8s node was live-migrated, and network errors have appeared. vector pod was restarted, and I see the error in the log:

```
2023-02-01T12:16:20.672747Z ERROR vector_buffers::variants::disk_v2::writer: Last record written to data file is behind expected position. Events have likely been lost. ledger_next=387356 last_record_id=385378 record_events=40
```
it stuck on this line, and HTTP server didn't start. 

I looked into buffer directory, there was a file ~100M in size. As I understand, they are unsent messages. I deleted position (?) file and restarted the pod. It started fine.

Q: How to deal with the buffer in such situations? How to fix the buffer and sent collected messages?

### Version

0.27.0

**Comment by jszwedko** [comment]
This is believed to be fixed by https://github.com/vectordotdev/vector/pull/17099
