### ISSUE TITLE
[axiom sink] Integration test is nonfunctional and has been disabled

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#16261]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

This actually happened back in November 2022 as part of #15053 and hasn't been addressed.

@bahlo this seems like it fell through the cracks, do you know what needs to happen here to fix the tests?

### Version

n/a

**Comment by spencergilbert** [comment]
Bump @bahlo any updates or news on this? We don't have the bandwidth to appropriately support this sink as-is.

**Comment by bahlo** [comment]
Hi @spencergilbert, terribly sorry about the delay. We experienced some sickness in the team and I‘m on parental leave right now, will make sure this is tackled asap.

**Comment by spencergilbert** [comment]
Thanks @bahlo and @schehata! Understand that life happens ❤️  - it'd be great to set up a better line of communication for this integration.

I noticed (what I think to be) a bug in the original implementation and made a fix accordingly [here](https://github.com/vectordotdev/vector/pull/16536). Though having an "official" contact point or email/etc to loop y'all in would be great, what do you think?

**Comment by schehata** [comment]
thanks @spencergilbert for the quick response, I will drop you an email in a moment, for better communication, and we can take it from there.

I am checking your fix as well, but from first glance, the fix makes sense 👍
