### ISSUE TITLE
AWS `region` and `endpoint` config may be handled better as an `enum`

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#1628]
In `src/region.rs`, `RegionOrEndpoint` is a structure with two optional components. Where this setting is present, exactly one must be defined, which is more suitable to an enum. This moves the handling of the exclusions into the serde parsing.

FWIW I did similar with the new GCP stackdriver logging sink, which has four mutually exclusive log name prefixes: https://github.com/timberio/vector/blob/dac0d1100cf1c0947736ed74f63f2fb81b50df17/src/sinks/gcp/stackdriver_logging.rs#L43

**Comment by lukesteensen** [comment]
We actually went through this process and ended up not choosing an enum due to the inability to control the serde error messages (see #251). We can definitely revisit that decision, but I figured the context would be helpful :smile:

**Comment by bruceg** [comment]
I guess then it's worth asking if I should also do the same for the GCP stackdriver logging sink.

**Comment by lukesteensen** [comment]
Yeah, good question! We have a [test](https://github.com/timberio/vector/blob/b51b1735c4cf348f5e33e2764d1e5b099561ab67/tests/config.rs#L327) covering the error output for S3, so maybe it's worth adding one to stackdriver.

**Comment by binarylogic** [comment]
@bruceg I'd have this issue represent the work @lukesteensen mentioned.

**Comment by Hoverbear** [comment]
@bruceg Would this prevent folks from using things like `ams3` as a region if they're using something like DigitalOcean's s3 buckets?

**Comment by bruceg** [comment]
If it is a known region identifier (ie the `rusoto` crate knows about it), then you can configure it using the `region` setting. Otherwise you would need to use the `endpoint` setting. In any case, this issue is not describing a change in behavior. The handling in `src/region.rs` already enforces the enum behavior instead of letting serde handle it, so Vector can control the error message.

**Comment by jszwedko** [comment]
Closing this since we ended up allowing both region and endpoint to be specified in https://github.com/vectordotdev/vector/pull/11578
