### ISSUE TITLE
Add fuzzing tests to Vector

### ISSUE THREAD

**Issue by a-rodin** [vectordotdev/vector#1630]
In order to improve Vector's security and stability, we can add fuzzing tests to Vector.

As @lukesteensen [mentioned](https://github.com/timberio/vector/issues/843#issuecomment-532408827), fuzzing was already used to harden individual components of Vector, such as the `tokenizer` transform. However, it might be interesting to invest more in this. For example we can start from defining our general approach to fuzzing which can then be applied to different components.

Such approach is to be specified and details can change, but I have in mind something like this:

* Agree which fuzzer(s) to use and how to call them (on entire Vector binary or on individual functions).
* Define inputs which are to be fuzzed for different components. These definitions can be stored either in TOML files or as Rust code.
* Create a Dockerfile which would setup everything necessary for reproducible running the fuzzying process. Also, having either a service in the `docker-compose` file (see https://github.com/timberio/vector/issues/1613#issuecomment-579268809 for details) or a wrapping shell script in `scripts` could help with reproducible runs of the fuzzing tests.

Some notes: I think it might be worth to focus on making it easy to maintain these tests and add fuzzing definitions for new components. If it comes come at cost of having not the most computationally efficient fuzzing process, it could be fine as long as we are not going to run these tests in CI.

**Comment by binarylogic** [comment]
@MOZGIII unless you think this is a very valuable and high priority feature I'd like to take it out of this project.

**Comment by MOZGIII** [comment]
I think we do need this, but I'd say this should be added after 1.0 when we have less turbulence. I agree this is a nice-to-have thing, and not of high priority.

**Comment by jszwedko** [comment]
Closing this since he have add fuzz tests to some areas of Vector and will continue to expand usage of this approach.
