### ISSUE TITLE
`datadog_agent` source missing `component_events_in_total` `component_events_out_total`

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#16309]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The `datadog_agent` source doesn't appear to be publishing in/out event metrics.

![image](https://user-images.githubusercontent.com/316880/217029977-414f7aed-6636-4dce-b14a-fdc810b911d3.png)

### Configuration

```text
enterprise:
  api_key: <api key>
  configuration_key: <conf key>
  site: "datadoghq.com"
​
api:
  enabled: true
​
sources:
  datadog_agent:
    type: datadog_agent
    address: 0.0.0.0:8226
    multiple_outputs: true
    store_api_key: false
    # Configure to enable SSL on incoming connections
    # https://vector.dev/docs/reference/configuration/sources/datadog_agent/#tls
    tls: null
​
sinks:
  datadog_metrics:
    type: datadog_metrics
    inputs:
      - datadog_agent.metrics
    default_api_key: <api key>
    acknowledgements:
      enabled: true
  datadog_logs:
    type: datadog_logs
    inputs:
      - datadog_agent.logs
    default_api_key: <api key>
    compression: gzip
    acknowledgements:
      enabled: true
  # Development status: BETA
  datadog_traces:
    type: datadog_traces
    inputs:
      - datadog_agent.traces
    default_api_key: <api key>
    compression: gzip
    acknowledgements:
      enabled: true
```

### Version

vector 0.27.0

**Comment by zamazan4ik** [comment]
Just to friendly remind you: https://github.com/vectordotdev/vector/issues/14464 :)

Maybe we need an epic about the outdated docs metric or some code-generation-based approach. Because that is not the first time when we get a similar problem.

**Comment by jszwedko** [comment]
Bisected this down the lack of "events in" down to ab173ff72cbe1978f25c3b10f867e24e6f5e60fa . I think the lack of "events out" regressed in a different commit so I'll bisect that down as well.

**Comment by jszwedko** [comment]
Looks like the lack of "events out" was regressed in 272a238b74d90f623f635fa52cdeb490b362749c. I'm guessing both of these are due to the lack of attaching component labels.

**Comment by jszwedko** [comment]
This seems to also affect the `splunk_hec` source.
