### ISSUE TITLE
aws_s3 sink should use "AWS_ROLE_ARN" environment variable

### ISSUE THREAD

**Issue by zzzz465** [vectordotdev/vector#16321]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

I'm trying to run vector in kubernetes, and our cluster's pod gets its token via IRSA (pod identity).
(it's more secure than injecting the user ACCESS/SECRET key)

aws-eks-identity-webhook pod injects appropriate environment variables when pod is up, checking annotation on service account.
some environments that being set is: `AWS_ROLE_ARN`, `AWS_WEB_IDENTITY_TOKEN_FILE`

it would be nice if vector selects `RoleAuthentication` mode if `AWS_ROLE_ARN` environment variable is defined.

### Attempted Solutions

I checked that with using aws cli, it automatically detects those environment variables I mentioned above.
so I assume this is related to how vector determines which credential resolver to use.

https://github.com/vectordotdev/vector/blob/81b82856a8ef9bd37018a4faa19db6eb323abe86/src/aws/auth.rs#L55-L125

### Proposal

in aws_s3 sink, option `auth.assume_role` also accepts `AWS_ROLE_ARN` environment variable.

### Version

vector 0.27.0 (x86_64-unknown-linux-gnu 5623d1e 2023-01-18)

**Comment by alexey-ban** [comment]
Work for me in version="0.29.1" arch="x86_64" revision="74ae15e 2023-04-20 14:50:42.739094536"
