### ISSUE TITLE
Re-enable aws_kinesis streams test

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#16376]
https://github.com/vectordotdev/vector/blob/d98ed324d110991afb8bdc39b9d8d0166c9b8221/src/sinks/aws_kinesis/streams/integration_tests.rs#L26

Disabled in https://github.com/vectordotdev/vector/pull/16372, might be a challenge to reproduce locally as both it and `kinesis_put_records_without_partition_key` consistently fail locally on my Mac.

**Comment by spencergilbert** [comment]
Hey @zamazan4ik, it looks like we failed to run the integration tests and one of the new ones you'd just added is failing. @neuronull was able to reproduce this locally, do you mind taking a look?

**Comment by zamazan4ik** [comment]
I definitely can, if the integration test will work fine on my local machine :)
