### ISSUE TITLE
Add Beats protocol (Logstash) output

### ISSUE THREAD

**Issue by piotrp** [vectordotdev/vector#16397]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Vector already accepts Beats inputs, but it's missing the ability to output data in this format. That would allow for:
* reliable data delivery to secured Elasticsearch clusters that use Logstash input as a security layer
* easier migration path from Beats + Logstash to Vector, as only one of components would need to be replaced at a time

### Proposal

Add a Beats (Logstaqsh) output, supporting
* TLS
* compression
* multiple target addresses with load-balancing
* acknowledgements

**Comment by mheiniger** [comment]
I think its the same as this: #533, right?

**Comment by jszwedko** [comment]
Thanks @mheiniger . Agreed that it is a duplicate and that this one has a more thorough description. I"ll close the other one.

**Comment by krikkiteer** [comment]
the reactions given for #553 shouldnt be disregarded though in weighing the interest in the feature.

**Comment by jszwedko** [comment]
> the reactions given for #553 shouldnt be disregarded though in weighing the interest in the feature.

Yeah, that's a good point. It'll be hard to maintain tracking of the interest across the duplicate. Given the other issue has a lot of interest already recorded I think what I'll do is reopen it, close this one, but migrate the description.

**Comment by jszwedko** [comment]
Duplicate of https://github.com/vectordotdev/vector/issues/533
