### ISSUE TITLE
Source : file progress tracking 

### ISSUE THREAD

**Issue by hdost** [vectordotdev/vector#16393]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

- Ensure that all of file is read and forwarded
- Be able to continue reading a file after a restart

### Attempted Solutions

The file source doesn’t have any tracking currently. 

### Proposal

Provide a number of options on the file source to track the progress of reading a file. 
Allow for files read to be forwarded in full.

**Comment by jszwedko** [comment]
Hi @hdost !

The `file` source actually already supports tracking progress through [checkpointing](https://vector.dev/docs/reference/configuration/sources/file/#checkpointing) to ensure that Vector picks up at the right spot when restarted. Does this cover your use case? Or is there is something else you are looking for?

**Comment by hdost** [comment]
🤦🏼‍♂️ indeed.  however i think what threw me off was the "stateless" i guess it's optionally stateless sorry for the noise.
