### ISSUE TITLE
Vector -> Vector -> Datadog not handling rate metric correctly

### ISSUE THREAD

**Issue by datsabk** [vectordotdev/vector#16412]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We had a [problem](https://github.com/vectordotdev/vector/issues/14857) in the past which was fixed in 0.24.2 version wherein Datadog was mistakenly sending rate metrics as counter. 

Now we are trying a configuration where vector in our app cluster sends data to vector in a central processing cluster. This vector in turn sends data to Datadog. Seems like the `rate` metric is again being treated as `count` when sends via the vector sink and ends up causing problems when sent to Datadog. 

The version in use is v0.25.0

### Configuration

```text
data_dir: /data/vector
          api:
            enabled: true
            address: 0.0.0.0:8686
            playground: false
          sources:
            vector_metrics:
              type: internal_metrics
              scrape_interval_secs: 60
            datadog_agent:
              address: 0.0.0.0:8282
              type: datadog_agent
              disable_logs: true
              disable_traces: true
              multiple_outputs: false
          transforms:
            rename_metrics:
              type: remap
              inputs:
                - datadog_agent
              source: |-
                .name, err = replace(.name, r'[^A-Za-z0-9_]', "_")
                .namespace, err = replace(.namespace, r'[^A-Za-z0-9_]', "_")
                if .counter !=null {
                  .kind = "absolute"
                }
                if .gauge !=null {
                  .kind = "absolute"
                }
                del(.tags."k2.version")
                del(.tags."k2.skip_checks")
                new_tags, parseErr = object(.tags)
                if parseErr != null {
                  log("Error parsing as object", level: "error", rate_limit_secs: 0)
                }
                for_each(new_tags) -> |key, value| {
                  .tags, err = remove(value: object!(.tags), path: [key])
                  if err != null {
                    log(err, level: "error")
                  }
                }
                for_each(new_tags) -> |key, value| {
                  .tags, err2 = set(value: .tags, path: [replace(key, r'[^A-Za-z0-9_]', "_")], data: value)
                  if err2 != null {
                    log(err2, level: "error")
                  }
                }
            modify_tags_for_vector_metrics:
              type: remap
              inputs:
                - vector_metrics
              source: |-
                del(.tags.host)
                .tags.node = get_env_var!("VECTOR_SELF_NODE_NAME")
                .tags.cluster_name = {{ .Values.global.clusterName | quote }}
            filter_for_vector_sink:
              type: filter
              inputs:
                - datadog_agent
              condition: "true"
            filter_for_prometheus:
              type: filter
              inputs:
                - rename_metrics
                - modify_tags_for_vector_metrics
              condition: {{ .Values.ampWrite.enabled | quote }}
          sinks:
            vector_monitoring_sink:
              type: vector
              inputs:
                - filter_for_vector_sink
              address: metrics-ingest.segment.local:9000
            prom_remote_write:
              type: prometheus_remote_write
              inputs:
                - filter_for_prometheus
              endpoint: "http://localhost:8080/workspaces/ampWorkspaceId/api/v1/remote_write"
```

### Version

0.25.0

**Comment by datsabk** [comment]
@jszwedko - Can we get some initial analysis done on this. Some hint on where to begin would be great to have. I could get someone from my team to work on the fix.

**Comment by jszwedko** [comment]
Hey @datsabk ! Apologies, we are a little behind in triage of new issues but hope to get to this soon. One thing you could do to help narrow it down is use the `console` sink to log the metric (use the `native_json` `encoding.codec`) in the first Vector as well as the second Vector and compare to see if it is lacking the `interval` field (which indicates that it is a rate and not a counter).

**Comment by datsabk** [comment]
Hey @jszwedko - There is an `interval_ms` field. Is that the one you are talking about? 

It exists on both sides of our pipeline. 
The one that receives Datadog metrics, forwards using Vector sink 
and the other that receives using Vector source and forwards using Datadog sink 

So now the question is why would this still be treated as rate? Is it the translation from Vector to Datadog sink that's broken ?

**Comment by jszwedko** [comment]
> Hey @jszwedko - There is an `interval_ms` field. Is that the one you are talking about?
> 
> It exists on both sides of our pipeline. The one that receives Datadog metrics, forwards using Vector sink and the other that receives using Vector source and forwards using Datadog sink
> 
> So now the question is why would this still be treated as rate? Is it the translation from Vector to Datadog sink that's broken ?

The `interval_ms` field having a value is what tells the `datadog_metrics` sink to encode the counter as a rate metric when sending to Datadog. If that field is not set (`None`) then the counter is passed to Datadog a counter. It sounds like that field is set all the way through your pipeline, though, so the `datadog_metrics` sink should be sending the metric as a rate to Datadog.

**Comment by datsabk** [comment]
Closing this issue - It was the aggregator that was a pain for this. One of our environments was pushing the same metric with 10s interval while our aggregator in a different environment was configured for 30s interval
