### ISSUE TITLE
High CPU load when redis connection fails

### ISSUE THREAD

**Issue by idenkov** [vectordotdev/vector#16492]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When I run Vector on a single core instance with Redis cluster, Vector fails to connect to it and load average goes to 1.5. 
![Screenshot from 2023-02-17 13-45-38](https://user-images.githubusercontent.com/8784288/219649316-7b7ba67c-4f20-42d2-9d62-36a17c2c19f1.png)

### Configuration

```text
[sources.redis_metrics]
type = "redis"
url = "redis://:password@127.0.0.1:6379/0"
key = "vector"
```

### Version

0.25.0

### Debug Output

```text
Feb 17 11:40:15 rediscluster-005 vector[15148]: {"error":"An error was signalled by the server: 12785 10.177.14.192:6379","error_code":"MOVED","error_type":"reader_failed","host":"rediscluster-005","internal_log_rate_limit":true,"message":"Failed to read message.","metadata":{"kind":"event","level":"ERROR","module_path":"vector::internal_events::redis","target":"vector::internal_events::redis"},"pid":15148,"source_type":"internal_logs","stage":"sending","timestamp":"2023-02-17T11:40:15.597331686Z","vector":{"component_id":"redis_metrics","component_kind":"source","component_name":"redis_metrics","component_type":"redis"}}
```

### References

https://github.com/vectordotdev/vector/issues/16490

**Comment by StephenWakely** [comment]
This was fixed by #16518.
