### ISSUE TITLE
Send a complete file to a destination

### ISSUE THREAD

**Issue by petermp79** [vectordotdev/vector#16524]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

I have a need to send a file, e.g. a json config (text) file or coredump (binary) file, to be stored on, e.g. elastic search.
However, after digging into the documentation and hacking multiline log file read feature. I am unable to do it. 

### Attempted Solutions

I tried multiline options. However, the last line (set as condition_marker marker) is not picked up to complete the file content, neither with halt_with or halt_before option.

I am not sure if vector has any existing methods for my use case. Yet, I think there may be some people who wish to do the same thing I do from time to time.

### Proposal

I quick resolution to this problem is to provide an option to include the marker in the event data group or better yet allow 
EOF as a condition marker.

### Version

vector 0.25.1 (x86_64-unknown-linux-gnu 9125a99 2022-11-07)

**Comment by zamazan4ik** [comment]
Vector is not supposed for binary files. For usual files, feel free to use `file` source with any supported sink.

**Comment by StephenWakely** [comment]
You could have a go at using the [exec source](https://vector.dev/docs/reference/configuration/sources/exec/) and `cat` the file.

But, this isn't really within the scope of Vector. Vector focuses on observability  data. So I will be closing this.
