### ISSUE TITLE
Throttling causes startup healthcheck failure with AWS Kinesis Firehose

### ISSUE THREAD

**Issue by djrodgerspryor** [vectordotdev/vector#16578]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

AWS Kinesis Firehose can throttle any request if it decides that it's temporarily overloaded; clients should back off and retry when they recieve these errors.

Vector tries to health check all of its sources and syncs when starting up, but if Firehose throttles the initial healthcheck request, then vector won't start, even if everything is set up correctly. If vector could start up properly, then it would buffer up log messages and retry until its requests were successful.

Proposed fix: During the healthcheck, Vector should treat 429 and 503 responses from Firehose (throttling or service unavailable) as successes. A 429 or 503 response means that everything is set up correctly on Vector's end (the caller has the right permissions, they have network access etc.) but the firehose API is busy which isn't actually relevant for the healthcheck.

### Configuration
N/A (any firehose config can have this error, it just requires that the AWS account it's used in is generating enough traffic to hit the firehose throughput limits).

### Version

```vector 0.27.0 (x86_64-unknown-linux-gnu 5623d1e 2023-01-18)```

### Debug Output

Example failure:

```text
Redirecting to /bin/systemctl restart vector.service
Job for vector.service failed because the control process exited with error code. See "systemctl status vector.service" and "journalctl -xe" for details.
Redirecting to /bin/systemctl status  -l vector.service
● vector.service - Vector
   Loaded: loaded (/usr/lib/systemd/system/vector.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2023-02-22 00:37:59 UTC; 27ms ago
     Docs: https://vector.dev/
  Process: 4375 ExecStartPre=/usr/bin/vector validate (code=exited, status=78)

Feb 22 00:37:59 client-event-i-0e82bac5ba02b5b21.au.s522.net vector[4375]: 2023-02-22T00:37:59.258424Z  WARN vector::config: Source has acknowledgements enabled by a sink, but acknowledgements are not supported by this source. Silent data loss could occur. source="host_metrics" sink="prometheus_export"
Feb 22 00:37:59 client-event-i-0e82bac5ba02b5b21.au.s522.net vector[4375]: √ Loaded ["/etc/vector/vector.toml"]
Feb 22 00:37:59 client-event-i-0e82bac5ba02b5b21.au.s522.net vector[4375]: √ Component configuration
Feb 22 00:37:59 client-event-i-0e82bac5ba02b5b21.au.s522.net vector[4375]: √ Health check "prometheus_export"
Feb 22 00:37:59 client-event-i-0e82bac5ba02b5b21.au.s522.net vector[4375]: 2023-02-22T00:37:59.780172Z ERROR vector::topology::builder: msg="Healthcheck failed." error=DescribeDeliveryStream failed: Error { code: "ThrottlingException", message: "Rate exceeded", request_id: "d83c486b-298f-ad44-8453-2e4c7595df8e" } component_kind="sink" component_type="aws_kinesis_firehose" component_id=firehose_logs component_name=firehose_logs
Feb 22 00:37:59 client-event-i-0e82bac5ba02b5b21.au.s522.net vector[4375]: x Health check for "firehose_logs" failed: DescribeDeliveryStream failed: Error { code: "ThrottlingException", message: "Rate exceeded", request_id: "d83c486b-298f-ad44-8453-2e4c7595df8e" }
Feb 22 00:37:59 client-event-i-0e82bac5ba02b5b21.au.s522.net systemd[1]: vector.service: control process exited, code=exited status=78
Feb 22 00:37:59 client-event-i-0e82bac5ba02b5b21.au.s522.net systemd[1]: Failed to start Vector.
Feb 22 00:37:59 client-event-i-0e82bac5ba02b5b21.au.s522.net systemd[1]: Unit vector.service entered failed state.
Feb 22 00:37:59 client-event-i-0e82bac5ba02b5b21.au.s522.net systemd[1]: vector.service failed.
```

### References

Possibly related to this ticket about retry behaviour for the firehose SDK: https://github.com/vectordotdev/vector/issues/12835

**Comment by zamazan4ik** [comment]
While I agree regarding 429 HTTP code, that it could be "ignored" in this case, I think 503 HTTP code cannot be ignored since it does not mean that the request is throttled. It also could mean that Firehose just does not work - and the healthcheck must fail in this case.

@jszwedko what do you think?

**Comment by jszwedko** [comment]
> While I agree regarding 429 HTTP code, that it could be "ignored" in this case, I think 503 HTTP code cannot be ignored since it does not mean that the request is throttled. It also could mean that Firehose just does not work - and the healthcheck must fail in this case.
> 
> @jszwedko what do you think?

I agree, a 503 means that Vector couldn't validate that the request was successful and so I think it makes sense to have the healthcheck fail or retry.

**Comment by zamazan4ik** [comment]
I think we have no consistent way here - hugely depends on the implementation of every healthcheck... Agree, that being more consistent here would be a good thing.

**Comment by spencergilbert** [comment]
Yeah - I think just doing a basic "retry X times with backoff before exiting" could cover 70% of issues and avoid a bunch of per sink code.

**Comment by jszwedko** [comment]
Could start with just applying the `request` options to health checks as well.

**Comment by jszwedko** [comment]
I made a more generic issue to resolve this for all sinks. I'll close this one since it is covered by that one, but thank you for getting this conversation started! Feel free to follow the other issue or leave any additional comments there.
