### ISSUE TITLE
Cannot start vector. no 'max_length' configured anywhere - Using `max_length` is deprecated error nonetheless

### ISSUE THREAD

**Issue by ccmsi** [vectordotdev/vector#16630]
Greetings.
I have an annoying issue that i seem to be unable to escape.
Trying to start vector in a setup that used to work i cannot start vector anymore after an update.
There is an error message that seems to call for a simple action..
*Using `max_length` is deprecated*
giving direction where such is supposedly misconfigured.
However, no such configuration item has been defined...   anywhere.
I checked the docs at (its in a socket source) according to vectordev and the proposed new version of max_length "framing.newline_delimited.max_length" is in place. However, vector cannot be started up. If *all* framing items are commented out, the service can be started.
Thanks for any hint on how to escape this.

**Comment by StephenWakely** [comment]
A recent change added in a default value for this `max_length` field (https://github.com/vectordotdev/vector/blob/master/src/sources/socket/tcp.rs#L43) resulting in this field always being set and leading to this error.

This default needs to be removed.

**Comment by ccmsi** [comment]
Incredibly quick ...
I'm using
repositories.timber.io/public/vector/deb/ubuntu
for retrieving vector. In this case, in what timeframe would that change reasonably appear in a package ?

**Comment by StephenWakely** [comment]
It should be in the latest nightly release. <https://packages.timber.io/vector/nightly/latest/>

**Comment by ccmsi** [comment]
can confirm its fixed in 0.28.1

**Comment by neuronull** [comment]
This was introduced by https://github.com/vectordotdev/vector/pull/16027
