### ISSUE TITLE
Sink to AWS Kinesis data stream not work

### ISSUE THREAD

**Issue by amliuyong** [vectordotdev/vector#16679]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Sink to AWS Kinesis data stream not work

### Configuration

```text
[sinks.kinesis_sink]
type = "aws_kinesis_streams"
inputs =  ["json_parser"]   
partition_key_field = "timestamp"
compression = "none"
region = "us-east-1"
stream_name = "....."

acknowledgements.enabled = true
  [sinks.kinesis_sink.encoding]
  codec = "json"
```

### Version

0.28.0

### Debug Output

```text
3/3/2023, 1:49:07 PM	2023-03-03T05:49:07.718428Z ERROR vector::topology::builder: msg="Healthcheck failed." error=DescribeStream failed: service error component_kind="sink" component_type="aws_kinesis_streams" component_id=kinesis_sink component_name=kinesis_sink	worker
3/3/2023, 1:49:07 PM	x Health check for "kinesis_sink" failed: DescribeStream failed: service error	worker
3/3/2023, 1:49:07 PM	√ Component configuration	worker
3/3/2023, 1:49:07 PM	√ Loaded ["/etc/vector/vector-global.toml", "/etc/vector/vector-kinesis-ack.toml", "/etc/vector/vector.toml"]	worker
3/3/2023, 1:49:07 PM	vector validate /etc/vector/vector-global.toml /etc/vector/vector.toml /etc/vector/vector-kinesis-ack.toml	worker
3/3/2023, 1:49:07 PM	AWS_REGION: us-east-1	worker
3/3/2023, 1:49:07 PM	AWS_KINESIS_STREAM_NAME: igs-kinesis-t1-kinesisDataStreamToS3OnDemandNestedStackkinesisDataStreamToS3OnDemandN-kinesisStreamOnDemand49471253-Kc66BECUjmO1	worker
3/3/2023, 1:49:07 PM	STREAM_ACK_ENABLE: true	worker
3/3/2023, 1:49:07 PM	VECTOR_REQUIRE_HEALTHY: false	worker
3/3/2023, 1:49:07 PM	WORKER_THREADS_NUM: 6
```

### Additional Context

I run vector in AWS ECS task and sink data to AWS kinesis using below version of vector

```dockerfile
FROM  timberio/vector:0.28.0-debian

```

when I upgraded the base image from `timberio/vector:0.27.1-debian` to `0.28.0`, the Health check for "kinesis_sink" failed

It works well in version `timberio/vector:0.27.1-debian`

**Comment by jszwedko** [comment]
Hi @amliuyong ! This is a known issue with 0.28.0 that is mentioned on https://vector.dev/releases/0.28.0/. It is fixed in `master` and will be released with 0.28.1.
