### ISSUE TITLE
vector pod restart every 2 hours

### ISSUE THREAD

**Issue by yankunsam** [vectordotdev/vector#16674]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

vector pod restart every 2 hours
![ffd32094-b21e-4803-83ff-99ac2da82df6](https://user-images.githubusercontent.com/16130147/222622430-bfbb37e4-15a4-4669-a7c6-c627762935d8.jpeg)
 
And the logs before restart,
```
thread 'main' panicked at 'failed to register allocation group token', src/internal_telemetry/allocations/mod.rs:195:9
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
   2: core::panicking::panic_display
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:139:5
   3: core::panicking::panic_str
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:123:5
   4: core::option::expect_failed
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/option.rs:1879:5
   5: vector::internal_telemetry::allocations::acquire_allocation_group_id
   6: vector::topology::running::RunningTopology::spawn_sink
   7: vector::topology::running::RunningTopology::spawn_diff
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: vector::app::Application::run::{{closure}}
  10: vector::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Version

0.27

**Comment by spencergilbert** [comment]
👋 it looks live you've run into this already resolved bug - https://github.com/vectordotdev/vector/pull/16201

You can either update to `0.28.0` (note the regression in AWS sinks described on the release notes), or disable allocation tracking.

**Comment by yankunsam** [comment]
@spencergilbert how to disable alloction tracking?

**Comment by jszwedko** [comment]
> @spencergilbert how to disable alloction tracking?

Unfortunately you'll need to update to 0.28.0. Allocation tracking is disabled by default, but there is still some code that runs even when it is disabled that is causing this issue.

**Comment by yankunsam** [comment]
@jszwedko thanks. I will have a try.
