### ISSUE TITLE
[Dedupe transformation] Add an option to flush the cache every X seconds / milliseconds and to count deduped logs

### ISSUE THREAD

**Issue by nicolasmf** [vectordotdev/vector#16681]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Let's say you receive a lot of logs from firewalls, but a lot of them are not useful, so you write a configuration to aggregate logs by devname, srcip, dstip and dstport fields.

Example log :
Feb 1 13:12:34 <Redacted_IP> <180>date=2023-01-23 time=13:57:22 devname="SOME_DEVICE_NAME" devid="..." logid="..." type="..." subtype="..." level="..." vd="..." eventtime=... tz="..." srcip=1.2.3.4 srcport=1234 srcintf="..." srcintfrole="..." dstip=1.2.3.4 dstport=1234 dstintf="..." dstintfrole="..." sessionid=... proto=... action="..." policyid=... policytype="..." poluuid="..." service="..." dstcountry="..." srccountry="..." trandisp="..." duration=... sentbyte=... rcvdbyte=... sentpkt=... rcvdpkt=... appcat="..." sentdelta=... rcvddelta=...

If, in a 10 seconds interval, 8 logs have the same devname, srcip, dstip and dstport, this would be outputed :

Feb 1 13:12:34 <Redacted_IP> <180>date=2023-01-23 time=13:57:22 devname="SOME_DEVICE_NAME" devid="..." logid="..." type="..." subtype="..." level="..." vd="..." eventtime=... tz="..." srcip=1.2.3.4 srcport=1234 srcintf="..." srcintfrole="..." dstip=1.2.3.4 dstport=1234 dstintf="..." dstintfrole="..." sessionid=... proto=... action="..." policyid=... policytype="..." poluuid="..." service="..." dstcountry="..." srccountry="..." trandisp="..." duration=... sentbyte=... rcvdbyte=... sentpkt=... rcvdpkt=... appcat="..." sentdelta=... rcvddelta=... **log_count=8** <=

And if a log is never deduped (and stays in the cache), it should also be outputed 

### Attempted Solutions

The problem with the dedupe transformation is that there is no way to flush the cache, so if I receive a log one day, it will always be comparing with the others incoming logs. Also, if a log is different from the others, it will take space on the stack forever.

### Version

0.28.0-1

**Comment by fuchsnj** [comment]
Hey @nicolasmf, it seems like what you are trying to accomplish should be possible by switching to a `reduce` transform instead of `dedupe`. `reduce` gives you more control and allows you to set a time limit. In addition you could use a `remap` transform to add a `log_count=1` counter before the `reduce` transform, and then use a `merge_strategies.sum` on that field to get a count of aggregated logs.

**Comment by nicolasmf** [comment]
Hey @fuchsnj, thank you for your response ! I had a problem with the reduce transform : 

Let's say I give 3 X logs and 2 Y logs, I'll only get in the output 1 X log, and no Y log. Is there something I'm doing wrong ?

Here's my config : 

[sources.in]
type = "stdin"

[transforms.aggregation]
type = "reduce"
inputs = ["in"]
flush_period_ms = 10_000
group_by = [    "devname",
                "srcip",
                "dstip",
                "dstport",
]

[sinks.out]
inputs = ["aggregation"]
type = "console"
encoding.codec = "json"

**Comment by fuchsnj** [comment]
The `group_by` config for `reduce` looks at fields on an event, but your `stdin` source is only receiving raw strings (`decoding.codec` defaults to `bytes`). It isn't parsing the message to get fields, so the `group_by` isn't matching anything, meaning all of your events are being reduced into a single one.

You can simply add `decoding.codec = "json"` to your `stdin` source, which will parse the input as json and give you actual fields to work with.

I used your test config with the following 5 inputs:
```json
{"devname": "a", "msg": "test 1"}
{"devname": "a", "msg": "test 2"}
{"devname": "a", "msg": "test 3"}
{"devname": "b", "msg": "test 4"}
{"devname": "b", "msg": "test 5"}
```

and it gave me the expected result of 2 messages (after 10 seconds)
```json
{"devname":"a","host":"nathan-fox-Thinkpad","msg":"test 1","source_type":"stdin","timestamp":"2023-03-09T20:29:39.188757105Z","timestamp_end":"2023-03-09T20:29:45.148866920Z"}
{"devname":"b","host":"nathan-fox-Thinkpad","msg":"test 4","source_type":"stdin","timestamp":"2023-03-09T20:29:47.764798838Z","timestamp_end":"2023-03-09T20:29:50.884285818Z"}

```

**Comment by nicolasmf** [comment]
Thank you ! 

Is there a way to combine the elements every 10 seconds, without waiting after the last event is received ?

As we receive a lot of events in an uninterrupted way, I cannot afford to use the `expire_after_ms` field.

**Comment by nicolasmf** [comment]
Hello,

Do you think there will be a future enhancement regarding what I'm looking for ? 

Thank you,

**Comment by fuchsnj** [comment]
@nicolasmf I believe you are now running into the issue that was fixed recently in https://github.com/vectordotdev/vector/pull/16146

Feel free to try out a nightly build of Vector to see if that works better for you, or wait until the next version is released.

**Comment by nicolasmf** [comment]
Okay, thank you for your time.

**Comment by jszwedko** [comment]
Rolling this issue into https://github.com/vectordotdev/vector/issues/16695
