### ISSUE TITLE
AWS Kinesis data stream partition_key_field not work as expected

### ISSUE THREAD

**Issue by amliuyong** [vectordotdev/vector#16680]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

set `partition_key_field = "timestamp"`  in  sink `aws_kinesis_streams`

in vector version 0.27.1, the `Partition key` in kinesis data stream can not be read as text. It seems that it is binary data.

but in version 0.25.1,  the `Partition key`  worked as expected. it is text data from timestamp field of the input json.

### Configuration

```text
[sinks.kinesis_sink]
type = "aws_kinesis_streams"
inputs =  ["json_parser"]   
partition_key_field = "timestamp"
compression = "none"
region = "us-east-1"
stream_name = "..."

acknowledgements.enabled = true
  [sinks.kinesis_sink.encoding]
  codec = "json"
```

### Version

0.27.1

### Additional Context

Run vector in AWS ECS task with below docker base image.

```text
FROM timberio/vector:0.27.1-debian
```

**Comment by spencergilbert** [comment]
👋 sorry about that @amliuyong, this appears to be a [duplicate](https://github.com/vectordotdev/vector/issues/16263) and [already resolved](https://github.com/vectordotdev/vector/commit/31a82a5c3892da8bdcbffe76761da81094a1568e).

It's technically resolved in `0.28.0`, however an AWS SDK upgrade regressed other functionality. We'll be cutting a `0.28.1` release Monday that will contain both fixes.
