### ISSUE TITLE
Add support for metrics to the aws_s3 sink and source

### ISSUE THREAD

**Issue by Shadow6363** [vectordotdev/vector#16718]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

We send our hosts' Datadog observability data to an `aws_s3` sink, which is then read from by another set of Vector services that perform any transformations before emitting the data to Datadog.
This has worked well for our logs; however, when we attempted to send metrics to the `aws_s3` sink, it fails.

Vector support recommended we use a metric to log transformation, but that transforms the data into a format that can no longer be sent to Datadog as a metric.
They pointed out a Lua transformation that properly transforms the data back into the metric format, but given our volume and the performance hit when using Lua transforms, that's not likely to be a scalable solution.

It was mentioned that the `aws_s3` sink should theoretically be able to support ingesting metrics now and that we should create a feature request asking to add such support. Consequently, to read that data, the `aws_s3` source would also need to support emitting metrics.

**Comment by jszwedko** [comment]
Thanks for opening this @Shadow6363 !

I split it into two issues: https://github.com/vectordotdev/vector/issues/16824 and https://github.com/vectordotdev/vector/issues/16825 since they can be resolved independently. I'll close this one, but feel free to follow the others! I also put pointers on the other issues for interested contributors.

**Comment by Shadow6363** [comment]
Thank you @jszwedko ! 🙇🏼
