### ISSUE TITLE
Default HTTP sink method changed

### ISSUE THREAD

**Issue by joscha-alisch** [vectordotdev/vector#16740]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

In this commit, the default http method used in the http sink changed from "POST" to "GET": https://github.com/vectordotdev/vector/commit/6617316533ca73529b253483a66150a3a07df845

Given that the `http_server` source still has the default method `POST`, this is a breaking change when connecting two vector instances via http. If this was intentional, I couldn't find anything in the release notes. 

### Version

0.28.1

**Comment by jszwedko** [comment]
Thanks for the catch @joscha-alisch . You do appear to be correct. I'm guessing the PR author was confused by a code comment that said `GET` was the default when it was, in fact, `POST`. We'll get this resolved and included in 0.28.2.
