### ISSUE TITLE
Upgrade to rust 1.69

### ISSUE THREAD

**Issue by fuchsnj** [vectordotdev/vector#16744]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jszwedko** [comment]
I assume you've seen this, but https://github.com/vectordotdev/vector/pull/16212 was the start of the upgrade to 1.67.1 that got blocked in case you want to pull in any of those changes here.

**Comment by jszwedko** [comment]
Reopening since technically this issue hasn't been closed.

**Comment by fuchsnj** [comment]
Renaming to 1.69, since 1.68 gets an ICE with Vector. See https://github.com/vectordotdev/vector/pull/16745#issuecomment-1464068196 for details.
