### ISSUE TITLE
Require release artifacts to be signed by GPG keys of multiple core team members

### ISSUE THREAD

**Issue by a-rodin** [vectordotdev/vector#1675]
https://github.com/timberio/vector/issues/1674 proposed a way for the users to verify authenticity of Vector binaries by recompiling them and then comparing results of the compilation with what we provide.

However, some users might want a simpler way to do this which doesn't involve compiling Vector. One solution might be to provide gurantees from multiple core team members that they did this check manually (on machines which they control) and it passed for them. These guarantees can be materialized as detached GPG signatures.

The general idea is the following:

* after the release artifacts are published, at least two or three (or maybe  more) members of the core team try to run the reproducible builds locally and then compare the resulting artifacts with the ones published;
* if these artifacts match byte-by-byte for the given core team member, this core team member signs all of these artifacts by a detached GPG signature;
* then all these signatures are [combined](https://superuser.com/questions/802262/how-to-merge-several-detached-signatures-from-different-people-into-one) and published on the Vector's website alongside the release artifacts;
* then the user who wants to verify the authenticity of release artifacts can import public GPG keys of these core team members from GitHub and verify these signatures, all of the have to be valid.

If we decide to proceed with this, we would need to develop a well-specified process for this, where all things which can be automated are automated.

**Comment by a-rodin** [comment]
Actually, it is even better to require to have these detached signatures produced before actual release artifacts are produced by the CI system. It would:

* ensure that no one just signed the published artifacts instead of producing their own;
* would allow to verify that all signatures match for artifacts produced in CI before they are actually published.

**Comment by Hoverbear** [comment]
Should the CI bot also sign?

**Comment by a-rodin** [comment]
@Hoverbear It can sign too, although it is not clear to me that it would provide more guarantees than just having an additional signature (using a different private key) from a core team member, in addition to the "personalized" signature of the same person. That's because at least one core team member would have full access to the CI infrastructure and thus be able to read to the private key of the CI bot.

It could have been considered a kind of automation, where the CI bot "represents" at least one core team member, allowing this person to avoid manual signing. However, it seems to me less reliable than manual signing because it means putting trust in the CI infrastructure, while the initial idea allows to avoid doing so.

**Comment by binarylogic** [comment]
@jszwedko this is related to https://github.com/vectordotdev/vector/issues/8842, keep it open or close?

**Comment by jszwedko** [comment]
I think we can close this in-lieu of #8842
