### ISSUE TITLE
Vector making api requests to Kubernetes API server without using resource_version

### ISSUE THREAD

**Issue by jeremy-mi-rh** [vectordotdev/vector#16753]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Context

We use vector to deliver `kubernetes_logs` to our kafka cluster which will be later processed and ingested into Humio. Vector is deployed as a daemon set in our kubernetes clusteres (each with >1000 nodes running). 

We recently had an outage in one of our kubernetes clusters (with ~1100 nodes running). There was a failure in ETCD leader node, which resulted in a cascaded failure where pods making 1000x API calls to our API server which eventually brought the kubernetes control plane down entirely. 

In the process of remediation, we identified vector as one of the candidate that was hammering the API server. Shutting down vector along with a few other daemon sets eventually reduced the traffic on Control Plane components, which allows ETCD nodes to recover. 

## Investigation

We did some analysis and investigation after the outage is recovered, and there are 2 issues we want to bring to vector community.

### resource_version not set when making API requests to Kube API server

Based on this issue: https://github.com/vectordotdev/vector/issues/7943, resource_version was set to 0 in vector 0.18 - 0.20. PR [#11714](https://github.com/vectordotdev/vector/pull/11714) adopted kube-rs and dropped the change in [#9974](https://github.com/vectordotdev/vector/pull/9974). When looking at the Audit logs from kube-api-server, we don't see the resource_version set in the request URL, which makes us wonder if this was an regression

Sample request in audit logs:

```json
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Request","auditID":"xxx","stage":"ResponseComplete","requestURI":"/api/v1/nodes?\u0026fieldSelector=metadata.name%3Dip-10-x-x-x.ec2.internal","verb":"list","user":{"username":"system:serviceaccount:vector:vector-agent","uid":"xxx","groups":["system:serviceaccounts","system:serviceaccounts:vector","system:authenticated"]},"sourceIPs":["10.x.x.x"],"objectRef":{"resource":"nodes","name":"ip-10-x-x-x.ec2.internal","apiVersion":"v1"},"responseStatus":{"metadata":{},"code":200},"requestReceivedTimestamp":"2023-03-08T02:29:15.992746Z","stageTimestamp":"2023-03-08T02:29:16.534351Z","annotations":{"authentication.k8s.io/legacy-token":"system:serviceaccount:vector:vector-agent","authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"default-reader-role-binding\" of ClusterRole \"cluster-read-all\" to Group \"system:authenticated\""}}
```

### Need a more aggressive backoff strategy? 

Another issue we found, is that vector was making lot more requests when it was seeing non successful responses from Kube API server. Making more requests is expected, as it needs to retry. However we are seeing 1000x times more requests in some cases. 

<img width="1049" alt="Screen Shot 2023-03-09 at 2 47 47 PM" src="https://user-images.githubusercontent.com/97993061/224177783-c7624988-215d-461c-9c46-1a2eec0a838b.png">

Before 17:45, the traffic was pretty steady. It makes 1 - 300 requests at a per minute basis. And when etcd server starts to have issues, it starts to make very aggressive requests which results in as many as 200,000 requests per minute. Is there a way we can configure the backoff strategy in this case? Or should it be less aggressive on retrying by default?

Also attached the graph that filtered on 429 response code:

<img width="1033" alt="Screen Shot 2023-03-09 at 2 54 27 PM" src="https://user-images.githubusercontent.com/97993061/224179012-609007c9-9e8c-4b72-b5c6-e1d6c0063374.png">

### Version

vector 0.27.0 (x86_64-unknown-linux-gnu 5623d1e 2023-01-18)

### References

#7943

**Comment by fuchsnj** [comment]
Hey @jeremy-mi-rh, thanks for the issue.

It seems like this is for 2 separate issues, `resource_version`, and backoff. Do you mind splitting this into 2 issues to make it easier for us to track / prioritize?

**Comment by jeremy-mi-rh** [comment]
Sure! Let me create separate ones and close this one.

**Comment by jeremy-mi-rh** [comment]
* resource_version not set to 0: https://github.com/vectordotdev/vector/issues/16797
* vector back off strategy to K8s API server: https://github.com/vectordotdev/vector/issues/16798
