### ISSUE TITLE
Kafka source overrides existing timestamp field in unix format

### ISSUE THREAD

**Issue by clamoris** [vectordotdev/vector#16760]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Kafka source overrides existing timestamp field in message.

We have a service sending messages to Kafka with existing `timestamp` field in unix format. Vector is reading messages using Kafka source and passing it to other sinks. 

Expected: `timestamp` field to be passed to sinks without change.
Actual: `timestamp` is replaced with current timestamp in different format (rfc3339 ?)

### Configuration

```text
[sources.testVectorTimestamp]
type = "kafka"
bootstrap_servers = "<removed>"
group_id = "testVectorCG"
topics = [ "testVectorTimestamp" ]
sasl.enabled = true
sasl.mechanism = "SCRAM-SHA-512"
sasl.password = "<removed>"
sasl.username = "<removed>"
librdkafka_options."security.protocol" = "sasl_ssl"
decoding.codec = "json"

[sinks.out]
inputs = ["testVectorTimestamp"]
type = "console"
encoding.codec = "json"
```

### Version

vector 0.28.0 (x86_64-unknown-linux-gnu 971c594 2023-02-27)

### Debug Output

```text
2023-03-10T12:20:03.251581Z  INFO vector::app: Internal log rate limit configured. internal_log_rate_secs=10
2023-03-10T12:20:03.251717Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info,lapin=info,kube=info"
2023-03-10T12:20:03.251790Z  INFO vector::app: Loading configs. paths=["test.toml"]
2023-03-10T12:20:03.258167Z  INFO vector::topology::running: Running healthchecks.
2023-03-10T12:20:03.258267Z  INFO vector::topology::builder: Healthcheck passed.
2023-03-10T12:20:03.258333Z  INFO vector: Vector has started. debug="false" version="0.28.0" arch="x86_64" revision="971c594 2023-02-27"
2023-03-10T12:20:03.258345Z  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.
{"headers":{},"message_key":null,"offset":1,"partition":0,"source_type":"kafka","timestamp":"2023-03-10T12:20:24.672Z","timestamp_copy":1678450299,"topic":"testVectorTimestamp"}
{"headers":{},"message_key":null,"offset":1,"partition":1,"source_type":"kafka","timestamp":"2023-03-10T12:20:26.173Z","timestamp_copy":1678450299,"topic":"testVectorTimestamp"}
```

### Example Data

{"timestamp": 1678450299, "timestamp_copy": 1678450299}
{"timestamp": 1678450299, "timestamp_copy": 1678450299}

**Comment by clamoris** [comment]
Looks like an oversight in https://github.com/vectordotdev/vector/issues/2700

**Comment by fuchsnj** [comment]
The timestamp key is being overwritten here:
https://github.com/vectordotdev/vector/blob/261bdba020c1fab5a24d118e90fb640b596fafea/src/sources/kafka.rs#L610

Note that with the (not yet publicly release released) `log_namespace` feature enabled, this will not be a problem. However, I'm not aware of any reasonable workarounds until then.

**Comment by pjarmalavicius** [comment]
Is there a plan to fix this?

**Comment by jszwedko** [comment]
> Is there a plan to fix this?

We plan to address this as part of a new feature we are working on to move "metadata" like the Kafka payload timestamp out of the event itself.

**Comment by WoWsj** [comment]
> We plan to address this as part of a new feature we are working on to move "metadata" like the Kafka payload timestamp out of the event itself.

@jszwedko Hello, is there any GitHub issue ticket for this?

**Comment by jszwedko** [comment]
This was actually implemented as an opt-in beta feature that we are referring to as "log namespacing". You can see https://vector.dev/blog/log-namespacing/ for details.

If enabled on the `kafka` source, the timestamp from the kafka message will be added as metadata accessible via `%kafka.timestamp`, rather than directly in the event itself and so won't override any decoded fields.

We have yet to fully document this feature (e.g. updating the `Output Data` sections), but we'll do that before stabilizing the feature.

Given the log namespacing feature was released, I'll close this out.
