### ISSUE TITLE
Acquire CII Badge(s)

### ISSUE THREAD

**Issue by Hoverbear** [vectordotdev/vector#1680]
The CII from LF has a "Badge Program" that allows us to qualify for and display nice infrastructure standards qualifications. I think we can achieve passing quite easily. Silver/gold may require quite some work!

https://www.coreinfrastructure.org/programs/badge-program/

cc @binarylogic

**Comment by jszwedko** [comment]
Duplicate of https://github.com/vectordotdev/vector/issues/322
