### ISSUE TITLE
Modify `capture_output()` method to propagate errors and exit status 

### ISSUE THREAD

**Issue by jonathanpv** [vectordotdev/vector#16807]
The `capture_output()` function should be able to propagate errors and exit status, it's not decided yet how to implement this since some cases exist where we want to see the stdout and stderr others where we don't care about the stdout. 

We previously discussed modifying the `capture_output()` function, but for now, I've implemented a new wrapper function called `run_command_check_status()`. This function runs the command, checks its exit status for success, returns an error if either the spawning of the command fails or if the command's exit code indicates a failure. This does so without caring about the output.

I also mentioned previously that I will track that issue separately, which I will create now.

Relevant pending PRs:
https://github.com/vectordotdev/vector/pull/16748/files#diff-3aa0b9b03ec0a4a4861c47ab7de668a62095b8669d0fd592df5cb84c7521a05eR142-R159

https://github.com/vectordotdev/vector/pull/16772/files#diff-0ff86c240a1da53c0fa4f6a7a1177c0e1b9cdddb9114e681f1b4939e076ce2afR116-R130

**Comment by jonathanpv** [comment]
Insert the checkrun in between the capture_output() between the stdout, and output()

The second thing: don't think we would want to throw away stderr but that will be tracked in a second issue.

**Comment by bruceg** [comment]
I think what we want for this is to avoid using `Command::output` entirely, and instead:
1. Set up the command with `self.stdout(Stdio::PIPE)`, leaving stdin and stderr untouched.
2. Spawn the process,
3. Read the output from `child.stdout` into a buffer.
4. Catch the exit code, and return `Err(something)` if it is non-zero.
5. Else return `Some(buffer)` converted to a `String` for convenience.
