### ISSUE TITLE
syslog source_ip changed to source_id, while the doc still references source_ip

### ISSUE THREAD

**Issue by sim0nx** [vectordotdev/vector#16818]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hi,

I am using the syslog source (https://vector.dev/docs/reference/configuration/sources/syslog/) and require usage of the *source_ip* field.
After having upgraded from v0.26.0 -> 0.28.1 I noticed that some rules which depend on *source_ip* no longer worked, as well as a new field having popped up in the logs **source_id**.

This change seems to be related to the following PR https://github.com/vectordotdev/vector/pull/15386 .

Note that the documentation still mentions **source_ip** and not **source_id**.

### Configuration

```text
[sources.syslog_514_tcp]
type = "syslog"
address = "0.0.0.0:514"
mode = "tcp"

[sinks.print]
type = "console"
inputs = ["syslog_514_tcp"]
encoding.codec = "json"
```

### Version

vector 0.28.1 (x86_64-unknown-linux-gnu ff15924 2023-03-06)

### Example Data

```json
{
  "appname": "rsyslogd",
  "facility": "syslog",
  "host": "xxxxxx",
  "hostname": "xxxxxx",
  "message": "...",
  "severity": "err",
  "source_id": "xxx.xxx.xxx.xxx",
  "source_type": "syslog",
  "timestamp": "2023-03-16T15:02:03Z"
}
```

note the **source_id**

**Comment by zamazan4ik** [comment]
More precisely, the related change is here: https://github.com/vectordotdev/vector/pull/15386/files#diff-0bcf766b37b7e9aadb9613a926fc90ed7fc296d85c543a9f79f97a7f183bdc2aR381

**Comment by spencergilbert** [comment]
Definitely a typo, we'll get this fixed ASAP.
