### ISSUE TITLE
Kinesis Data Stream - gzipped partition_key when using compression

### ISSUE THREAD

**Issue by zpriddy** [vectordotdev/vector#16823]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The issue seems to be that the `partition_key` gets compressed when compression is turned on... This works as expected with compression turned off. This is what the data in the shard was looking like 

![Kinesis_bad_partition_key](https://user-images.githubusercontent.com/1858679/225717980-d582bd27-e94b-4cb8-a7f9-5f90c43f4184.png)

### Configuration

```text
type = "aws_kinesis_streams"
inputs = [ "event_router.*" ]
stream_name = "${VECTOR_SPLUNK_LOGS_KINESIS_STREAM_NAME:?AWS Firehose stream name not set}"
compression = "gzip"
region = "${VECTOR_SPLUNK_LOGS_KINESIS_REGION:?AWS Firehose region not set}"
partition_key_field = "index"

  [encoding]
  codec = "json"
  only_fields = ["event", "fields", "host", "index", "source", "sourcetype", "time"]
  timestamp = "unix"

  [request]
  concurrency = "adaptive"
```

### Version

0.28.1

**Comment by fuchsnj** [comment]
I've played around with this sink a bit, and I'm not seeing anything that could cause this.

Could you share any more of your config / setup, specifically around the source of your events? I'm wondering if you have something _before_ the `aws_kinesis_streams` that could potentially be compressing the `index` field? Could you try adding a `console` sink with `encoding.codec = json` with `nputs = [ "event_router.*" ]` without changing anything else in your config to see what the input events look like?

**Comment by zpriddy** [comment]
Everything looks right for data coming - that was the first debug step I took. When i commented out `compression = "gzip"` Everything was working as expected. I will do another test of adding this back in. When this happened it drained about 1TB of events into Kinesis where they were dropped for invalid partition key

**Comment by zpriddy** [comment]
So I ran a partial deployment with compression enabled, and it is looking as expected with the shard name in plain text and the data gzipped encoded. What I am thinking is these were events that were sent with the `partition_key  = ".index"` instead of  `partition_key  = "index"`  (Sometimes its not clear if its field name or path syntax) 

With all of this said I do think that the documentation should say that setting the `partition_key` is recommended. I was struggling to get over 5 MB/s to Kinesis.. Out of desperation I scaled our Aggregator cluster from 6 to 15 and got up to 10 MB/s ... As soon as I deployed the change with the `partition_key` set.. I saw it hit 94 MB/s... 

I was trying to figure out if it was the compression being disabled or the partition key being set that improved the performance of the sink.. Im still playing with that now... 

However I am seeing high count of `Write throughput exceeded` counts and the `PutRecords successful records average` has been between 40%-50% and this is with the adaptive concurrency enabled.. even with that the `PutRecords failed records` is at 0%...  Is there any suggestions besides the adaptive concurrency to not have 40%-90% of the requests be throttled @fuchsnj ? 

![Screenshot 2023-03-16 at 3 30 35 PM](https://user-images.githubusercontent.com/1858679/225767466-5f0b1c51-7867-48c4-9628-0328f429b091.png)
