### ISSUE TITLE
Unable to parse timestamp without timezone

### ISSUE THREAD

**Issue by spraot** [vectordotdev/vector#16870]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I'm attempting to parse a timestamp without no timezone. I expect Vector to assume my local timezone, which is set in my config as `timezone = "Europe/Copenhagen"`. Instead I see this error:

`$ dt, err = parse_timestamp("Mar 20 15:29:13", format: "%b %e %H:%M:%S")
"function call error for \"parse_timestamp\" at (10:70): Invalid timestamp \"Mar 20 15:29:13\": input is not enough for unique date and time"`

This example is from repl, but I see the same error running as a service.

I attempted to work around this by appending `format_timestamp(now(), format: "%z")`, but `now()` is only available in UTC, so this didn't work. How else can I solve this?

### Version

vector 0.28.0 (x86_64-unknown-linux-gnu 971c594 2023-02-27)

**Comment by fuchsnj** [comment]
I don't think this issue is related to timezones, you have not provided a year in your timestamp.

This example seems to work fine.
```coffee
parse_timestamp!("Mar 20 2023 15:29:13", format: "%b %e %Y %H:%M:%S")
t'2023-03-20T19:29:13Z'
```

**Comment by spraot** [comment]
Oh thanks that makes sense. I did a similar trick using now() to get the year, but is there any way to do that without it being wrong around year end?
