### ISSUE TITLE
Old internal metrics for files are not being deleted

### ISSUE THREAD

**Issue by kandeshvari** [vectordotdev/vector#17005]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

During the time of usage length of the `/metrics` constantly grows up. After a small investigation, I discovered that metrics with labels for old files weren't deleted and kept being sent to Prometheus. Is there an option to remove such metrics? As a workaround, I can restart the vector daily, but it seems like a dumb solution.

### Configuration

```text
sources:
  internal_metrics:
    type: internal_metrics
    scrape_interval_secs: 15

sinks:
  prom_exporter:
    type: prometheus_exporter
    inputs:
      - internal_metrics
    address: 0.0.0.0:9090
```
```


### Version

0.28.1

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

**Comment by jszwedko** [comment]
Hi @kandeshvari !

There is an option you can use to expire the metrics after a period: https://vector.dev/docs/reference/configuration/global-options/#expire_metrics_secs . Would you want to try that?

**Comment by kandeshvari** [comment]
Thank you for your reply, @jszwedko! I'll try it.

But I have a question - documentation said: `If set, Vector will configure the internal metrics system ...`. Why is it a `global` option (not a part of `internal_metrics`), and why is there no mention of such an important option in the `internal_metrics` or `prometheus_exporter` documentation?

**Comment by jszwedko** [comment]
> Thank you for your reply, @jszwedko! I'll try it.
> 
> But I have a question - documentation said: `If set, Vector will configure the internal metrics system ...`. Why is it a `global` option (not a part of `internal_metrics`), and why is there no mention of such an important option in the `internal_metrics` or `prometheus_exporter` documentation?

Ah, this is because the internal metrics registry is independent of the `internal_metrics` source. It also drives other functionality in Vector like `vector top`. So, even if you aren't using the `internal_metrics` source, metrics are still recorded internally.

**Comment by jszwedko** [comment]
Closing since https://github.com/vectordotdev/vector/issues/17005#issuecomment-1490253803 should be accurate.
