### ISSUE TITLE
Acknowledgements not working with Amazon Opensearch

### ISSUE THREAD

**Issue by oleksiiprokhorenko** [vectordotdev/vector#17061]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We are using Vector in K8s with the following architecture:

Agents put data into S3
S3 emits an SQS message
Vector Aggregator picks up the SQS message, processes the S3 object and put data into Amazon OpenSearch indexes

The main reason why we are using Vector is its feature "acknowledgements" that prevent losing data even OpenSearch server is not reachable for some reasons.

The feature worked fine with version vector:0.25.2-distroless-libc (helm vector-aggregator-0.17.1), but not working with the next version vector:0.26.0-distroless-libc (helm vector-aggregator-0.18.0) and later. The newer versions got data from SQS and S3 object, but doesn't receive the acknowledgement from OpenSearch and as a result no new data received in Opensearch. When I disable "acknowledgements" option on the latest versions, everything works fine but we definitely need this option working.

During update from 0.25.2 to 0.26.0 I replaced deprecated option "suppress_type_name: true" with "api_version:" - that's the only one change I did.

Do I need to add some extra options to make "acknowledgements" working again on the latest version?
Thank you!

### Configuration

```text
customConfig:
  data_dir: /vector-data-dir

  api:
    enabled: true
    address: 127.0.0.1:8686
    playground: false

  sources:
    s3_k8s_logs:
      type: aws_s3
      compression: gzip
      region: ${region}
      strategy: sqs
      sqs:
        delete_message: true
        poll_secs: 15
        queue_url: "${queue_url}"
        visibility_timeout_secs: 300

  transforms:
    initial_transform:
      type: remap
      inputs:
        - s3_k8s_logs
      source: |
        . = parse_json!(.message)

    de_dots:
      type: remap
      inputs:
        - initial_transform
      source: |
        . = map_keys(., recursive: true) -> |key| { replace(key, ".", "_") }

    route_k8s_logs:
      type: route
      inputs:
        - de_dots
      route:
        kube: .kubernetes.container.name == "kube-proxy" || .kubernetes.container_name == "kube-proxy"

    remap_kube:
      type: remap
      inputs:
        - route_k8s_logs.kube
      source: |
        .index_name = "kube"
        ."@timestamp" = del(.timestamp)

  sinks:
    opensearch:
      api_version: v8
      type: elasticsearch
      #suppress_type_name: true
      inputs:
        - remap_kube
        - remap_unmatched
      endpoints:
        - ${endpoint}
      auth:
        user: "${user}"
        password: "${password}"
        strategy: "basic"
      compression: gzip
      batch:
        max_bytes: 200000
      distribution:
        retry_max_duration_secs: 300
      mode: "bulk"
      bulk:
        action: "create"
        index: |-
          {{ print "vector-{{ .index_name }}-dev-%Y.%m.%d" }}
      healthcheck: false
      tls:
        verify_hostname: true
      acknowledgements:
        enabled: true
```

### Version

vector:0.26.0-distroless-libc and later

### Additional Context

no logs from the pod vector-aggregator-0 at all

**Comment by neuronull** [comment]
Hello,

Would you be able to provide debug logs for this scenario?

**Comment by oleksiiprokhorenko** [comment]
The latest helm chart works fine with acknowledgements, most likely due to this fix:

The aws_s3 source no longer deadlocks under low client_concurrency when acknowledgements are enabled. Thanks to [mdeltito](https://github.com/mdeltito) for contributing this change!
