### ISSUE TITLE
[UX] Config settings around `endpoint`/`url`/`address`/`uri` should be more consistent

### ISSUE THREAD

**Issue by neuronull** [vectordotdev/vector#17074]
For both sources and sinks, we use these names in configuration settings without great consistency.

We should center on which one(s) to use for what data direction/application, update the component configuration settings, and document the reasoning at a central location to be referenced.

**Comment by jszwedko** [comment]
Duplicate of https://github.com/vectordotdev/vector/issues/17074

**Comment by neuronull** [comment]
> Duplicate of #17074

👀  was this comment meant for a different issue? Or is the issue # link meant to point to a different one?

**Comment by neuronull** [comment]
I bet https://github.com/vectordotdev/vector/issues/8877

**Comment by jszwedko** [comment]
Doh, yep :) Meant to link to https://github.com/vectordotdev/vector/issues/8877
