### ISSUE TITLE
Memory usage metrics

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#1708]
It'd be great to have a per-source/transform/sink memory usage metrics.
This should give the users the power to troubleshoot issues like #1496 with very little effort in most cases.

The proposed approach to achieve this is to add explicit logic for computing an estimate of the consumed memory to every relevant location (i.e. source, transform, sink, etc) and make that data available to our internal metric gathering system (i.e. prometheus export and/or our internal metrics source).

**Comment by binarylogic** [comment]
This might be a silly question, but I'm curious how you would track real-time memory usage on a per-component basis? Does Rust provide mechanisms for achieving this?

**Comment by MOZGIII** [comment]
> explicit logic for computing an estimate of the consumed memory
I'm thinking about the simplest thing possible, that's also very trivial, however it's not generic - that is to manually account for how much memory we use at a given moment, where possible.
For instance, with `merge` transform I was working on, we store a partial event merge state, that's pretty much an event internally. For each event, we can compute the amount of memory it takes by simply summing up the byte sizes of each of the fields, and the size of the event we keep as a partial event merge state is what we would call the amount of memory that `merge` transform uses.

Of course, this estimate won't be accurate, but at least it'll give the user the opportunity to know, if things go south, where the memory is in the system.

I'm not sure if it'd work for all the cases, but this approach looks interesting to me, because even with something like `lua` transform we can potentially come up with a pretty good estimate of how much memory the VM takes at a certain point of time.

P.S. I'm also considering ways of doing something more elegant, like compile-time allocation coloring by owner for grouping/accounting them at runtime, but that's non-trivial, and I'm at the very early stages of the research process on this idea. Compared to that, manual estimates are a lower hanging fruit.

**Comment by LucioFranco** [comment]
We use a lot of reference counting so we would need to track that, which I think would be pretty hard.

For lua, if we could extract how much memory the vm is using I think that could be _very_ useful.

**Comment by MOZGIII** [comment]
It's pretty easy: https://docs.rs/rlua/0.17.0/rlua/struct.Lua.html#method.used_memory

**Comment by MOZGIII** [comment]
Regarding the reference counting - what would be an example of that? Most of the transforms should have pretty much no internal state, and for sinks and sources - I guess it would not be too difficult to do some rough accounting - just enough to indicate when things grow way out of proportion.

With this initiative, there's also a design problem of figuring out a sensible way to add metrics - in such a way that'd be easily usable by the end users. I think we have to provide a sort a common pattern that all sources/transforms/sinks should try to report - while not prohibiting the additional metrics where fit.

**Comment by LucioFranco** [comment]
Almost all of our events are backed by references counted immutable bytes, so it may be hard to track down that.

**Comment by MOZGIII** [comment]
Oh, you mean if we track the allocations? I agree, that's very hard.
On the other hard, it's really easy to write the code to inc the memory counter when you produce an event, and dec it when an event is released. Again, it might not be accurate, but would still help imo.

**Comment by lukesteensen** [comment]
Noting that we should include the new `reduce` transform in this, as well as any others that intentionally aggregate state in memory (e.g. batching, `dedupe` transform, etc).

**Comment by MOZGIII** [comment]
We can also expose the stats for the buffers between transforms. Given that transforms typically either have an explicit state of some kind that we should be able to track, or operate on a single event at a time - in general, this can be as lower effort / bigger value thing.

**Comment by jszwedko** [comment]
Some efforts have been started around this in https://github.com/vectordotdev/vector/pull/11109

**Comment by jszwedko** [comment]
Closing as completed by https://github.com/vectordotdev/vector/pull/11109 and follow-on PRs.
