### ISSUE TITLE
when using kinesis data stream or other AWS corresponding service, if use credentials file to authorize it failed.

### ISSUE THREAD

**Issue by Jake0109** [vectordotdev/vector#17107]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

```
Running tests
2023-04-11T08:35:32.360772Z ERROR vector::unit_test: Failed to execute tests:
data did not match any variant of untagged enum AwsAuthentication
in `sinks.kinesis_syslog`
```
after running `vector test myconfig` this error occurred. I think credentials files should be one of the way to authorize, but I just wonder if vector can do the same way.
the doc also recommend to not use static accessKey and accessId, so how to authorize? Is role the only way?

### Configuration

```text
data_dir = "~/vector/data/"

# Ingest
[sources.syslog]
type = "file"
include = ["/var/log/messages"]
start_at_beginning = true

# Structure and parse the data
[transforms.remap]
inputs = ["syslog"]
type = "remap"
drop_on_error = false
source = '''
. |= parse_apache_log!(string!(.message), "common")
'''

# Output data
#[sinks.console_logs]
#inputs = ["remap"]
#type = "console"
#encoding.codec = "json"

[sinks.kinesis_syslog]
type = "aws_kinesis_streams"
inputs = ["remap"]
auth.credentials_file = "~/.aws/credentials"
auth.profile = "my_profile"
auth.region = "ap-northeast-1"
compression = "none"
stream_name = "my_stream"
encoding.codec = "json"
```

### Version

0.28.1

**Comment by Jake0109** [comment]
thanks for your response, but after I changed auth.region to region, this error message displayed:
"ERROR vector::topology: Configuration error. error=Sink "kinesis_syslog": Overriding the credentials file is not supported.".
In this way I supposed that it has set credentials file as the way to authorize, but after all the message "did not match" mekes me confused.

**Comment by neuronull** [comment]
Oh it looks like you have encountered this issue: https://github.com/vectordotdev/vector/issues/16632

, which was fixed in `v0.29.0` by: https://github.com/vectordotdev/vector/pull/16633

**Comment by Jake0109** [comment]
thank you very much.
after updated to v0.29.0 it does not occurred again.

**Comment by Jake0109** [comment]
unfortunately it happened again, it turns out that I changed default AWS credential files to make vector use default profile to authorize, but after I delete the default profile it failed again.
```
Running tests
2023-04-17T07:27:16.150657Z ERROR vector::unit_test: Failed to execute tests:
data did not match any variant of untagged enum AwsAuthentication
in `sinks.kinesis_syslog`
.
```
this is my configure file
```
data_dir = "/data/vector/data/"
log_schema.host_key = "hostname"

# Ingest
[sources.syslog]
type = "file"
include = ["/var/log/messages"]
start_at_beginning = true

# Structure and parse the data
#[transforms.remap]
#inputs = ["syslog"]
#type = "remap"
#drop_on_error = false
#source = '''
#. |= parse_apache_log!(string!(.message), "common")
#'''

# Output data
[sinks.console_logs]
inputs = ["syslog"]
type = "console"
encoding.codec = "json"

[sinks.kinesis_syslog]
type = "aws_kinesis_streams"
inputs = [ "syslog" ]
auth.credentials_file = "/home/xxx/.aws/credentials"
auth.profile = "xxx"
auth.regoin = "ap-northeast-1"
compression = "none"
stream_name = "xxx"
encoding.codec = "json"
buffer.max_events = 300
```
besides the configuration `log_schema.host_key` does not work.

And I also have a look at the merge request of https://github.com/vectordotdev/vector/pull/16633
I don't know why but it use `default` profile only, and if `default` profile is not set, vector cannot work with `auth.credentials_file` configuration.

**Comment by bruceg** [comment]
The configuration of the AWS authentication currently requires both `credentials_file` and `profile`, and only those two, to be set in order to use credentials stored in a file. By also setting `regoin` (a typo?), the configuration parser is confused which type of authentication is being requested, as the `region` field belongs to a different type. I think the particular error you are seeing can be cleared up by removing the region setting.

**Comment by jszwedko** [comment]
Closing since https://github.com/vectordotdev/vector/issues/17107#issuecomment-1518428978 seems to be accurate.
