### ISSUE TITLE
`appsignal` sink should apply user-defined TLS settings

### ISSUE THREAD

**Issue by neuronull** [vectordotdev/vector#17112]
As observed in https://github.com/vectordotdev/vector/issues/17110 , the sink is currently not allowing user defined TLS settings (https://cs.github.com/vectordotdev/vector/blob/a791595b0cfcae36d0c46708a91d5e2813ed38eb/src/sinks/appsignal/mod.rs#L117).

The can be adressed by adding the `TlsSettings` to the config struct for the sink and applying them instead of `&None`.

**Comment by tombruijn** [comment]
I've created a PR with a fix: https://github.com/vectordotdev/vector/pull/17122
