### ISSUE TITLE
Field Issues with 0.29.0

### ISSUE THREAD

**Issue by zpriddy** [vectordotdev/vector#17115]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem
*** EDIT 
It seems like some field checking was introduced in 0.29.0 and is causing Vector to crash with working configs in 0.28.2. I am not sure what they changes are that would cause this to happen.. So I am hoping we can get some documentation on what fields these changes effect.. We have a very large and diverse deployment that we manage and dont even know where to begin on tracing this issue. 

### Original Problem
I have a file: `../transforms/router.toml` as shown below... If I have a route with the route id: `category_logs` it will cause Vector to panic. If I change it to `categoryLogs` or `event_logs` or basically anything else... it does not panic..

I think it has to do with the `category_`

### Configuration

```text
type = "route"
inputs = ["my-inpit"]

    [route]
    netflow = '''ends_with(to_string!(.topic), "-netflow")'''
    category_logs = '''exists(.message.category)'''
```

### Version

0.29.0

### Debug Output

```text
Apr 11 22:36:33 vector-aggregator vector[3245603]: thread 'main' panicked at 'Setting a field on a value that cannot be an object', lib/vector-core/src/schema/definition.rs:279:13
Apr 11 22:36:33 vector-aggregator vector[3245603]: stack backtrace:
Apr 11 22:36:33 vector-aggregator vector[3245603]:    0: rust_begin_unwind
Apr 11 22:36:33 vector-aggregator vector[3245603]:              at ./rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
Apr 11 22:36:33 vector-aggregator vector[3245603]:    1: core::panicking::panic_fmt
Apr 11 22:36:33 vector-aggregator vector[3245603]:              at ./rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
Apr 11 22:36:33 vector-aggregator vector[3245603]:    2: vector_core::schema::definition::Definition::with_event_field
Apr 11 22:36:33 vector-aggregator vector[3245603]:    3: <vector::transforms::remap::RemapConfig as vector::config::transform::TransformConfig>::outputs
Apr 11 22:36:33 vector-aggregator vector[3245603]:    4: vector::topology::schema::possible_definitions
Apr 11 22:36:33 vector-aggregator vector[3245603]:    5: vector::topology::schema::possible_definitions
Apr 11 22:36:33 vector-aggregator vector[3245603]:    6: vector::topology::schema::possible_definitions
Apr 11 22:36:33 vector-aggregator vector[3245603]:    7: vector::config::validation::warnings
Apr 11 22:36:33 vector-aggregator vector[3245603]:    8: vector::config::compiler::compile
Apr 11 22:36:33 vector-aggregator vector[3245603]:    9: vector::cli::SubCommand::execute::{{closure}}
Apr 11 22:36:33 vector-aggregator vector[3245603]:   10: vector::app::Application::prepare_from_opts
Apr 11 22:36:33 vector-aggregator vector[3245603]:   11: vector::main
Apr 11 22:36:33 vector-aggregator vector[3245603]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Apr 11 22:36:33 vector-aggregator systemd[1]: vector.service: Control process exited, code=exited status=101
Apr 11 22:36:33 vector-aggregator systemd[1]: vector.service: Failed with result 'exit-code'.
```

**Comment by zpriddy** [comment]
This looks like it might actually be due to an unnest call before the router

**Comment by jszwedko** [comment]
Hi @zpriddy ,

Thanks for this report! I'm having a hard time reproducing this with the config snippet you provided. Could you provide a full set of configuration along with some sample input that triggers it?

**Comment by zpriddy** [comment]
@jszwedko - Our deployment is very large.. It is going to take some time to debug what is causing this to happen.. I am going to try to do a config one file at a time until it crashes.. With that said.. It does not even finish the startup process before it crashes, so there will be no input provided to trigger it.

**Comment by jszwedko** [comment]
> @jszwedko - Our deployment is very large.. It is going to take some time to debug what is causing this to happen.. I am going to try to do a config one file at a time until it crashes.. With that said.. It does not even finish the startup process before it crashes, so there will be no input provided to trigger it.
> 
> It does seem to be the same as #17083

Ah, gotcha, thanks. Knowing that it happens at start-up is helpful. It does look like we'll need more of your config to reproduce it as so far we've been unsuccessful. Let us know!

**Comment by zpriddy** [comment]
I almost wonder if it has to do with this: 

```
[log_schema]
metadata_key = "vector.metadata"
source_type_key = "vector.source_type"
```

**Comment by dariosusman** [comment]
I'm attaching the configuration file I'm using, since it has no credentials or anything sensitive.
[vector.toml.txt](https://github.com/vectordotdev/vector/files/11214211/vector.toml.txt)

Indeed, this only happens at start-up and also shows in a `vector validate`.

Best regards,
Dario Susman

**Comment by neuronull** [comment]
Would you be able to provide the output of `vector --version`? Thanks!

Also, where are you sourcing the build from? (build from source, github, docker etc.)

**Comment by dariosusman** [comment]
I had to revert/downgrade back, of course.

That was after updating the APT/DEB package on Debian, which got me to version 0.29.0.

Best regards,
Dario Susman

**Comment by neuronull** [comment]
Thanks for that extra context.

So far I have not been able to reproduce this with the provided configuration file.

I tried both the [vector_0.29.0-1_amd64.deb](https://github.com/vectordotdev/vector/releases/download/v0.29.0/vector_0.29.0-1_amd64.deb) from the GH releases, and also from the [apt package manager](https://vector.dev/docs/setup/installation/package-managers/apt/)

The result I get is:

```
➜  ~ which vector
/usr/bin/vector
➜  ~ vector --version
vector 0.29.0 (x86_64-unknown-linux-gnu 33b3868 2023-04-11 22:19:54.512366263)
➜  ~ vector validate /etc/vector/vector.toml
Loaded with warnings ["/etc/vector/vector.toml"]
------------------------------------------------
~ Transform "routev2v._unmatched" has no consumers

√ Component configuration
√ Health check "winlogout"
√ Health check "out"
√ Health check "syslogout"
√ Health check "albout"
√ Health check "fileout"
--------------------------------------------------
                                         Validated
➜  ~
```


🤔  Does the error occur for you, if you remove the enrichment table parts of the config?

**Comment by dariosusman** [comment]
That would mean that the remap for the alb will not have the GeoIP data. I can comment it out. I'll give it a test.

**Comment by dariosusman** [comment]
I'm sorry. My mistake. I've sent the wrong configuration file, from the wrong server.

The attached configuration file has been edited to remove sensitive data and replaced with content with `<>`, e.g. `<AWS S3 BUCKET>`.

[vector.toml.txt](https://github.com/vectordotdev/vector/files/11216299/vector.toml.txt)


```
# vector --version
vector 0.29.0 (x86_64-unknown-linux-gnu 33b3868 2023-04-11 22:19:54.512366263)
# 
```
```
# RUST_BACKTRACE=full vector validate
thread 'main' panicked at 'Setting a field on a value that cannot be an object', lib/vector-core/src/schema/definition.rs:279:13
stack backtrace:
   0:     0x560eb644712e - std::backtrace_rs::backtrace::libunwind::trace::h1d00f3fcf4cb5ac4
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x560eb644712e - std::backtrace_rs::backtrace::trace_unsynchronized::h920a6ff332484ee2
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x560eb644712e - std::sys_common::backtrace::_print_fmt::hd7323920c925af6d
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x560eb644712e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3155a8c966b4beb5
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x560eb5a7886e - core::fmt::write::h062c617411b691df
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/fmt/mod.rs:1209:17
   5:     0x560eb6412f94 - std::io::Write::write_fmt::hb61fdf1275c61e1c
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/io/mod.rs:1682:15
   6:     0x560eb644847f - std::sys_common::backtrace::_print::hd1b4d9664ab500e0
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x560eb644847f - std::sys_common::backtrace::print::hca896ae22beb06cb
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x560eb6447f7d - std::panicking::default_hook::{{closure}}::h0b5eeed5cf36ab5f
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:267:22
   9:     0x560eb64491d6 - std::panicking::default_hook::h8932b573145a321b
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:286:9
  10:     0x560eb64491d6 - std::panicking::rust_panic_with_hook::h4b1447a24e3e94f8
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:688:13
  11:     0x560eb6448b33 - std::panicking::begin_panic_handler::{{closure}}::h8701da9995a3820c
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:577:13
  12:     0x560eb6448acc - std::sys_common::backtrace::__rust_end_short_backtrace::hb696c5ed02a01598
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x560eb6448aa1 - rust_begin_unwind
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
  14:     0x560eb54837b2 - core::panicking::panic_fmt::h8aa706a976963c88
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
  15:     0x560eb8d2b2b0 - vector_core::schema::definition::Definition::with_event_field::hef94215cd1ec0ff1
  16:     0x560eb7887360 - <vector::transforms::remap::RemapConfig as vector::config::transform::TransformConfig>::outputs::h7f592ae22d7c18f2
  17:     0x560eb78ee8da - vector::config::validation::warnings::hd8f7629136e46024
  18:     0x560eb78e161c - vector::config::compiler::compile::h1136b8b6500876b6
  19:     0x560eb8aecc29 - vector::cli::SubCommand::execute::{{closure}}::h71314069c549eb90
  20:     0x560eb8adc5b8 - vector::app::Application::prepare_from_opts::hd4e16660ae41aeda
  21:     0x560eb554f4ab - vector::main::h99d4ac2f55549f3f
  22:     0x560eb554d7b3 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha35ff0081048d02c
  23:     0x560eb5552669 - main
  24:     0x7f77e197fd0a - __libc_start_main
  25:     0x560eb554d6ba - <unknown>
  26:                0x0 - <unknown>
```

I've now reverted back to vector 0.28.2-1

```
# vector --version
vector 0.28.2 (x86_64-unknown-linux-gnu 986dd37 2023-04-10)
```

**Comment by neuronull** [comment]
Thanks for providing the updated config. I was able to reproduce the error with that config, and trim that down to something smaller (see below).

This must be something related to the fact that there are two transforms, because if the second transform "bar" is commented out, then the error does not occur.

This further makes me suspect the issue is related to this commit https://github.com/vectordotdev/vector/commit/e19f4fca320d817fd58ce2bdf429ec3384a3eacb, since the assertion is coming from the log namespacing module, and this commit has much overlap with these bits.

I rolled back to the commit prior to that one, and the error does not occur (was not able to revert that commit without conflicts).

We will need to fix this in the next patch.

```
[sources.in]
type = "stdin"

[transforms.foo]
type="remap"
inputs=["in"]
source='''
result, e = get_enrichment_table_record("geoip", {"ip":.source_ip})
if e == null {
.geoip = result
}
'''

[transforms.bar]
type = "remap"
inputs = ["foo"]
source = '''
'''

[sinks.blackhole]
type = "blackhole"
inputs = [ "bar" ]
```

**Comment by neuronull** [comment]
Further notes: the assert comes from the `with_event_field()` function, and occurs when it thinks the event kind being operated on is not an object.
Suspect that something may have gone awry in the logic for the remap transform's outputs, when there are multiple input schema definitions.

**Comment by StephenWakely** [comment]
This panic is occurring for me because we have two remap transforms in the topology.  The transform `vpn_session_geoip` is raising an error because the `geoip` enrichment table doesn't exist. (This doesn't exist because I don't have the database at that location on my machine.) 

When the remap compiler raises an error it produces a schema definition of:

```rust
                    Definition::new_with_default_metadata(
                        // The program failed to compile, so it can "never" return a value
                        Kind::never(),
                        input_definition.log_namespaces().clone(),
                    )
```

This definition is then being passed to the next remap transform which then tries to set a number of different fields on the definition, but because that definition has been specified as `Kind::never()` it produces that panic.

I think it is a bit extreme to panic in this situation. I would like to change that to produce a warning instead. This then allows us to collect all the errors produced whilst building up the topology and report them correctly. Also potentially a Remap transform should check if the incoming definition is `Kind::never()` and if it is it would know that nothing will ever be sent to it, so it doesn't need to compile anything.

This doesn't completely answer all the questions though. If you are able to run Vector fine on an older version then that means all the transforms are compiling successfully, which would not cause this error. So I think it is possible that there is a further problem going on, but we won't know what that is until we can get Vector reporting the errors correctly.

**Comment by sbalmos** [comment]
Chiming in here, as this regression affects my usage also. At least in my case, it is definitely from a transform running `. = unnest!(.message)`, causing multiple events to be emitted to the rest of the pipeline.

**Comment by neuronull** [comment]
> Chiming in here, as this regression affects my usage also. At least in my case, it is definitely from a transform running `. = unnest!(.message)`, causing multiple events to be emitted to the rest of the pipeline.

Hi @sbalmos, thanks for raising your impact as well. Would you be able to share your transform configs?
