### ISSUE TITLE
Vector doesn't support special characters in proxy credentials

### ISSUE THREAD

**Issue by konstantin-kornienko** [vectordotdev/vector#17125]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When HTTP proxy's credentials contain special characters (like !@#$% etc) they should be url-encoded in `http_proxy` or `https_proxy` env vars, like
```
export https_proxy=http://user:P%40ssw0rd@myproxy:3128
```

Vector incorrectly parses this, so http sink fails to authenticate in proxy.

Suggested test:
```
let config = ProxyConfig {
    http: Some("http://user:P%40ssw0rd@1.2.3.4:5678".into()),
    https: Some("https://user:P%40ssw0rd@2.3.4.5:9876".into()),
    ..Default::default()
};
let first = config
    .http_proxy()
    .expect("should not be an error")
    .expect("should not be None");
let encoded_header = format!("Basic {}", BASE64_STANDARD.encode("user:P@ssw0rd"));
let expected_header_value = HeaderValue::from_str(encoded_header.as_str());

assert_eq!(
    first.headers().get("authorization"),
    expected_header_value.as_ref().ok()
);
```

### Version

0.28.1

**Comment by neuronull** [comment]
Thanks for the report.
Reproduced with that unit test.

**Comment by kkornienko-aparavi** [comment]
Thanks @neuronull , the problem is that proxy passwords _highly likely_ contain special characters in the wild )
Hope it can be fixed.

**Comment by konstantin-kornienko** [comment]
Thanks @neuronull , the problem is that proxy passwords highly likely contain special characters in the wild )
Hope it can be fixed.
