### ISSUE TITLE
Limit memory usage for sources - Make vector 'resource aware'

### ISSUE THREAD

**Issue by timfehr** [vectordotdev/vector#17123]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

There is already a [backpressure mechanism](https://vector.dev/docs/about/concepts/#backpressure) where sinks or transforms provide backpressure which will propagate back to the source, but there is no mechanism to limit the source if the source is the bottleneck or vector has to less resources that the source can handle the incoming messages.

### Attempted Solutions

Limit the overall resources for the vector instance via kubernetes resulted in a `OOMKilled` crash loop when the source tried to read more messages than given resources allowed.

```
[sources.kafka]
type = "kafka"
bootstrap_servers = "${KAFKA_IN_BOOTSTRAP_SERVERS:?Missing kafka in bootstrap servers}"
group_id = "${KAFKA_CONSUMER_GROUP_ID:?Missing kafka group id}"
auto_offset_reset = "${KAFKA_NEW_CONSUMER_OFFSET:-latest}
decoding.codec = "${KAFKA_IN_CODEC:-bytes}"
topics = ["${KAFKA_IN_TOPIC:?Missing kafka input topic}"]
metrics.topic_lag_metric = true

[sinks.bh]
type = "blackhole"
inputs = [ "kafka" ]
```

### Proposal

One solution could be that vector becomes aware of its resources and do not exceed them.

Another, perhaps easier to implement, solution could be to have a configuration setting for sources or any transform to set a memory usage limit or smth.

A combination of both could also be possible, that the maximum/default config setting is the maximum available resources that vector is aware of, but the user can also set the allowed limit per source/component to ensure that the memory is distributed evenly or especially give the component which needs more resources the amount it needs.

### References

[Discord support thread](https://discord.com/channels/742820443487993987/1095358286984925294)

### Version

vector 0.28.1 (x86_64-unknown-linux-gnu ff15924 2023-03-06)

**Comment by jszwedko** [comment]
I think this is the same as https://github.com/vectordotdev/vector/issues/11942 so I'll combine it.
