### ISSUE TITLE
[bug] Vector binary crashes with `exec format error` on ARM64 / aarch64 (`0.29.0-alpine`)

### ISSUE THREAD

**Issue by pascaliske** [vectordotdev/vector#17157]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When upgrading my installation from `0.28.2-alpine` to `0.29.0-alpine` I get the following error and the binary inside the container completely crashes on my ARM64 / aarch64 system:

```sh
exec /usr/local/bin/vector: exec format error
```

The binary of `0.28.2-alpine` works fine on my ARM64 / aarch64 system.

### Configuration

```text
Nothing relevant here. Problem arises during binary execution.
```

### Version

vector 0.29.0 (aarch64-unknown-linux-musl)

**Comment by zamazan4ik** [comment]
According to the Dockerhub, 0.29.0-alpine has no ARM version but 0.28.2 - has. @jszwedko do you know what is the reason for that?

0.29.0-alpine:
<img width="461" alt="image" src="https://user-images.githubusercontent.com/7355383/232210895-8c30ae36-e036-4903-b76d-35b148ca7f7f.png">

0.28.2-alpine:
<img width="475" alt="image" src="https://user-images.githubusercontent.com/7355383/232211018-0734a86e-50b9-4ff2-9f2d-ab72ad0ab759.png">

Before the fix, I could suggest build your own Docker image for ARM :) Or just wait for the fix.

**Comment by pascaliske** [comment]
Yeah, you're right. I didn't had a closer look at the available architectures because I were on mobile device. 😁

I'm fine with waiting on version `0.28.2` until the official fix is released. 👍🏻

**Comment by bruceg** [comment]
I can confirm this is an issue. There were some issues during the 0.29.0 release that ended up with us doing a manual upload of the artifacts. Evidently, those images were missed in the process. We will make sure to cover that in [the 0.29.1 release](https://github.com/vectordotdev/vector/issues/17164), which is already in process.

**Comment by pascaliske** [comment]
Yes, I can confirm, that it’s fixed on my side! Thanks.
