### ISSUE TITLE
matching "\0" in message is invalid

### ISSUE THREAD

**Issue by scMarkus** [vectordotdev/vector#17158]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I am trying to reroute some docker logs if the message contains a null character like so:
`contains(string(.message) ?? "", "\0")`
This does produce the following vector error on startup
```
│ vector-logs 1 │ ╭ contains(string(.message) ?? "", "\t") ||                                                                          │
│ vector-logs 2 │ │ contains(string(.message) ?? "", "\0")                                                                             │
│ vector-logs 3 │ │                                                                                                                    │
│ vector-logs   │ ╰^ unexpected error: invalid escape character: \0                                                                    │
```
The `\t` in that output shall illustrate that it seams to pass vectors validation but not the `\0`. Since the error code lines are looking as intended I am assuming there is no issue with me writing yaml config here. Am I misreading the [documentation](https://vector.dev/docs/reference/vrl/expressions/#string-characteristics) on how to use `\0`? 

### Configuration

```text
data_dir: /opt/vector/data/
sources:
  docker:
    type: docker_logs
    multiline:
      mode: continue_through
      start_pattern: "^[^\\s]"
      condition_pattern: "^[\\s]+"
      timeout_ms: 2000
transforms:
  route:
    type: route
    inputs: [docker]
    route:
      debug: contains(string(.message) ?? "", "\0")
sinks:
  my_sink_id:
    type: console
    inputs: [route.debug]
    encoding:
      codec: json
```

### Version

vector 0.29.0 (x86_64-unknown-linux-gnu 33b3868 2023-04-11 22:19:54.512366263)

**Comment by bruceg** [comment]
This is a known limitation in the VRL compiler at this point. See [this issue in the VRL repository](https://github.com/vectordotdev/vrl/issues/148) for more details.
