### ISSUE TITLE
vector cant start up

### ISSUE THREAD

**Issue by lupanagora** [vectordotdev/vector#17167]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

when i use image vector:0.17.3-alpine deploy to k8s , pod get errors below:
Apr 18 07:37:35.619  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info"
Apr 18 07:37:35.619  INFO vector::config::watcher: Creating configuration file watcher.
Apr 18 07:37:35.619 ERROR vector::app: Unable to start config watcher. error=uncategorized error

### Configuration

```text
containers:
  - args:
    - --watch-config
    - /etc/vector/*.toml
    - --config
    - /etc/vector/*.toml
    image: vector:0.17.3-alpine
    imagePullPolicy: IfNotPresent
    name: vector
    resources:
      limits:
        cpu: 400m
        ephemeral-storage: 50Mi
        memory: 400Mi
      requests:
        cpu: 400m
        ephemeral-storage: 50Mi
        memory: 400Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data/logs
      name: log
    - mountPath: /etc/vector
      name: vector-config
      readOnly: true


...
volumes:
  - configMap:
      defaultMode: 420
      name: vector-config
    name: vector-config
  - hostPath:
      path: /data/log
      type: DirectoryOrCreate
    name: log


....

apiVersion: v1
data:
  default.toml: |-
    [sources.log]
    type = "file"
    ignore_older = 600
    include = ["/data/logs/*.log"]

    [transforms.remapper]
    type = "remap"
    inputs = ["log"]
    source ='''
      message_parts, err = split(.message, " ", limit: 8)
      .log= "log"
      .log_date = message_parts[0]
      .log_time = message_parts[1]
      .level = message_parts[2]
      .hostName = message_parts[3]
      .workerId = message_parts[4]
      .pid = message_parts[5]
      .line = message_parts[6]
      .msg = message_parts[7]
      del(.message)
    '''

    [sinks.xxx]
     # some detail configs
kind: ConfigMap
```

### Version

vector 0.17.3 (x86_64-unknown-linux-musl d72c6e7 2021-10-21)

**Comment by jszwedko** [comment]
Closing due to lack of response.
