### ISSUE TITLE
Support AMQP properties

### ISSUE THREAD

**Issue by arouene** [vectordotdev/vector#17173]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Hello,

The AMQP protocol support properties, which includes:

- Content type
- Content encoding
- Routing key
- Delivery mode (persistent or not)
- Message priority
- Message publishing timestamp
- Expiration period
- Publisher application id

I needed to have a support for the **content-type** property as the client I'm using (and others I suppose) needs a content-type to know how to deserialize, and Vector at the moment, does not set content-type.

### Attempted Solutions

No actual support for properties currently, I tried to use a field for the content-type, but it does not work the way intended.

### Proposal

The change I propose, is to make a configuration for **properties.content_type** on the **AMQP sink**. If it's not set, the older behavior apply (using `BasicProperties::default()`).

I have work on a branch, here https://github.com/arouene/vector/tree/amqp_sink_support_content_type in my repo, would you be interested to have it as a PR ?

I currently only support **content_type** and **content_encoding**, I can implement other properties if needed.

### Version

vector 0.28.1 (x86_64-unknown-linux-gnu ff15924 2023-03-06)

**Comment by bruceg** [comment]
Yes, we would definitely be interested in this as a PR. I did a quick once-over of your branch, and the only suggestion I would have is to include the properties config in `config.rs`. Otherwise, it looks pretty clean.

**Comment by arouene** [comment]
All right, I will do that, thanks for your suggestion !

**Comment by arouene** [comment]
Hello @bruceg, I moved the content of `properties.rs` into `config.rs`. When you will have time, can you check the PR please ?
