### ISSUE TITLE
Add support for dynamic `valid_tokens` to the Splunk HEC source

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#17172]
### Discussed in https://github.com/vectordotdev/vector/discussions/17168

There is no good way to communicate a list of valid tokens to the `splunk_hec` source other than by [hard-coding them in the configuration file](https://vector.dev/docs/reference/configuration/sources/splunk_hec/#valid_tokens). It would be useful for systems like this to be able to dynamically add entries to or remove entries from this list at run time. One possibility would be to name a file containing tokens, or possibly to name a command to execute to either list and/or validate tokens.

**Comment by bruceg** [comment]
> Would an acceptable solution be to have the `splunk_hec` source iterate the given tokens, and any that contains a comma would be split and merged back into the list?

The proposal doesn't really help with the dynamic list issue described above. It does help where the tokens are stored in an environment variable, but there is still no way to communicate a new value for that variable to Vector outside of a full restart, sinc reload wouldn't provide Vector with a new environment.

**Comment by jszwedko** [comment]
Rolling this issue into a more generic one about secrets supporting values that are an array: https://github.com/vectordotdev/vector/issues/17213
