### ISSUE TITLE
aws_ec2_metadata transform assumes event is an object, even in Vector namespace

### ISSUE THREAD

**Issue by StephenWakely** [vectordotdev/vector#17193]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The `aws_ec2_metadata` transform assumes the incoming object is an Object. This is fine for the Legacy namespace (currently in use everywhere), but in the Vector namespace this is not always the case.

Currently Vector will panic (once the transform definitions work goes in) on load if the incoming event definition is not an object.

### Configuration

```text
schema:
  enabled: true

sources:
  in:
    type: syslog
    address: 0.0.0.0:9000
    mode: tcp
    log_namespace: true

transforms:
  thing:
    type: aws_ec2_metadata
    inputs:
      - in
      
sinks:
  console:
    type: console
    inputs:
      - thing
    encoding:
      codec: json
    target: stdout
```

### Version

v0.30

**Comment by fuchsnj** [comment]
Long term this transform should probably be deprecated. It doesn't provide enough flexibility to decide how to enrich an event with the new data. A better alternative is to allow this enrichment in VRL with something like https://github.com/vectordotdev/vector/issues/15110
