### ISSUE TITLE
Resumable transform

### ISSUE THREAD

**Issue by peterwa88** [vectordotdev/vector#17197]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

HI, there. I need a data dog agent has a function that it saves data to a local temperary place when network has problem and resend data when the network recovered. Does Vector offer this kind of function?

**Comment by zamazan4ik** [comment]
Yes, it has. It's called buffering: https://vector.dev/docs/about/under-the-hood/architecture/buffering-model/

**Comment by bruceg** [comment]
As @zamazan4ik has indicated, all vector sinks integrate a standard buffer mechanism. For example, [here is the configuration section for the `datadog_logs` sink](https://vector.dev/docs/reference/configuration/sinks/datadog_logs/#buffer). By default, it is only configured to buffer 500 events to memory, but a disk buffer is also available that can hold much more. When the sink is unable to send, it will buffer events up to the maximum configured size, at which point it will either stop accepting new events or drop them from the buffer, depending on the configuration. When the sink is able to send again, it will first pull events from the buffer to fill its outbound requests.

**Comment by peterwa88** [comment]
Thank you!
