### ISSUE TITLE
Datadog sink does not support histogram aggregations & sketches

### ISSUE THREAD

**Issue by datsabk** [vectordotdev/vector#17220]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Datadog exporter in the Open Telemetry Collector today supports [Histogram Aggregations and Sketches for summary](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/144b3428eed16e8b82bf0696cba31f56cde15342/exporter/datadogexporter/config.go#L108) but Vector Datadog sink does not seem to have the capability to do so. 

Look for someone to help in enabling this functionality - Need aggregations as well as percentile capabilities to be introduced. 

### Configuration

```text
sinks:
  datadog_metrics:
    type: datadog_metrics
    inputs:
     - filter_for_datadog_sink
    histograms: 
      send_aggregation_metrics: true
      percentiles: 
        enabled: true
        percentile:
        - 0.95
        - 0.90
    default_api_key: ${DD_API_KEY}
```

### Version

0.25.0

**Comment by jszwedko** [comment]
Hey @datsabk !

We had some discussion on Discord, but for posterity:

> I believe that translation should happen. Histograms are decoded here: https://github.com/vectordotdev/vector/blob/7570bb31e2f471e3ff8bc818c24e9bde3090818c/src/sources/prometheus/parser.rs#L64-L99 into a AggregatedHistogram internally. This is encoded as a sketch here: https://github.com/vectordotdev/vector/blob/7570bb31e2f471e3ff8bc818c24e9bde3090818c/src/sinks/datadog/metrics/normalizer.rs#L26-L29

> datsabk
> OP
>  — 05/02/2023 6:17 AM
> So will percentiles be generated as separate metrics? Or just the aggregations (Sum, max, min)
> jszwedko — 05/02/2023 1:39 PM
> The data will actually just be sent as a distribution (sketch) to Datadog rather than pre-aggregating the statistics. Then in Datadog you can query arbitrary percentiles, sum, min, max, etc. https://docs.datadoghq.com/metrics/distributions/ has some more details

Given that histograms are encoded as sketches, I believe this support exists. I'll close this issue but feel free to reopen if you are still seeing gaps.
