### ISSUE TITLE
VRL cannot reference json paths with "$" in them

### ISSUE THREAD

**Issue by frankh** [vectordotdev/vector#17237]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The following remap doesn't work

```
[transforms.session_recordings_parsed2]
type = "remap"
inputs = [ "session_recordings_parsed" ]
source = '''
  . = parse_json!(.data)
  .session_id = .properties.$$session_id
'''
```

And there doesn't seem to be any way of escaping it so that it does work.

The format of the json object is `{"properties": {"$session_id": "blah"}}`

### Version

0.29.1

**Comment by jszwedko** [comment]
Hi @frankh !

I think there are a couple of things at play here:

`$` is used to indicate environment variable interpolation in Vector config files and so must be escaped with a second `$`, as you are doing.

But then also paths cannot start with special characters and so have to be quoted. That is, I think you want: `.properties."$$session_id"`.

**Comment by jszwedko** [comment]
Closing this since I'm pretty confident in my answer in https://github.com/vectordotdev/vector/issues/17237#issuecomment-1525976286 but please feel free to re-open if you cannot get that working!

**Comment by lennysec** [comment]
Hi @jszwedko !
I've tested this case on VRL Playground, but it didn't work:
https://playground.vrl.dev/
Vector Version:	[3378adad](https://github.com/vectordotdev/vector/tree/3378adad7b5b1819ffd52cf9563f519bb13ebdad)
VRL Version:	[0.13.0](https://crates.io/crates/vrl/0.13.0)

The result of `.properties."$$session_id"` is null

**Comment by lennysec** [comment]
FYI: 
`.properties."$session_id"` can get the value correctly, but it will cause an error when using it in vector config：
`ERROR vector::cli: Configuration error. error=Missing environment variable in config.`

vector version: 0.37.0

Add a `--strict-env-vars=false` is a workaround, but I think that's not the right way to solve this problem

**Comment by lennysec** [comment]
@jszwedko Thanks for your reminding. Problem solved.
