### ISSUE TITLE
Add support for templates to vector sink address

### ISSUE THREAD

**Issue by amanmahajan26** [vectordotdev/vector#17239]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I am trying to access a pipeline variable `.address` in vector sink but unable to do so. I get the following error:

`2023-04-27T16:22:34.829020Z ERROR vector::topology: Configuration error. error=Sink "vector_aggregator": invalid uri character`

Not able to figure out what am I doing wrong.

### Configuration

```text
[sources.log_files]
type = "file"
include = [
  "/var/log/rabbitmq/rabbit.log",
]

[transforms.enrich]
type = "remap"
inputs = ["log_files"]
source = """
if contains("${ENVIRONMENT}", "production") {
  .address = "http://<PRODUCTION_ENDPOINT>:<PORT>"
} else {
  .address = "http://<STAGING_ENDPOINT>:<PORT>"
}
"""

[sinks.vector_aggregator]
type = "vector"
inputs = [ "enrich" ]
address = "{{ address }}"
version = "2"
```

### Version

0.24.2

### Debug Output

```text
2023-04-27T16:22:34.829020Z ERROR vector::topology: Configuration error. error=Sink "vector_aggregator": invalid uri character
```

**Comment by bruceg** [comment]
At this point, it is not possible to use a template in the `vector` sink address field. To achieve what you are trying to do in the above, you would need to also set an environment variable containing the endpoint address before running Vector.

**Comment by dsmith3197** [comment]
We discussed as a team and our recommended solution is to use the route transform and two sinks for this use case. We are wary about making the host itself templateable due to the implications throughout the sink.
