### ISSUE TITLE
DataDog Metrics Sink issue with aggregated histogram

### ISSUE THREAD

**Issue by mfamahran** [vectordotdev/vector#17241]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Currently I'm testing a specific setup with vector which ends up passing an event to datadog_metrics_sink.

Testing with a gauge metric type was successful, however when testing an aggregated_histogram metric type the sink seems to fail in outputting the events to DD, I'm clearly able to see that the sink receives the event but there are no signs of errors nor events out of the sink to DD.

DD Metrics sink doesn't seem to be delivering the acknowledgements to the source for the first time it's receiving the data, the source is just stuck waiting for it, once the source is restarted all requests would successful but with the same behaviour of not outputting metrics to DD

Included in the debug output the console output of the same event.

### Configuration

```text
datadog_metrics_sink:
    type: datadog_metrics
    inputs:
      - transform_meta
    acknowledgements:
      enabled: true
    default_api_key:
    site: "datadoghq.com"
```

### Version

0.30.0

### Debug Output

```text
vector-vector-1  | 2023-04-27T21:14:32.785274Z TRACE sink{component_kind="sink" component_id=datadog_metrics_sink component_type=datadog_metrics component_name=datadog_metrics_sink}: vector_common::internal_event::events_received: Events received. count=1 byte_size=509
vector-vector-1  | 2023-04-27T21:14:32.785295Z TRACE sink{component_kind="sink" component_id=test_out component_type=console component_name=test_out}: vector_common::internal_event::events_received: Events received. count=1 byte_size=509
vector-vector-1  | 2023-04-27T21:14:32.791608Z TRACE sink{component_kind="sink" component_id=test_out component_type=console component_name=test_out}: vector_common::internal_event::events_sent: Events sent. count=1 byte_size=507
vector-vector-1  | {"name":"test.histogram2","namespace":"","tags":{"tag1":"test"},"timestamp":"2023-04-27T21:14:32.781562380Z","kind":"absolute","aggregated_histogram":{"buckets":[{"upper_limit":1.0,"count":1},{"upper_limit":2.0,"count":2},{"upper_limit":5.0,"count":1},{"upper_limit":10.0,"count":1}],"count":5,"sum":30.0}}
vector-vector-1  | 2023-04-27T21:14:32.792080Z TRACE sink{component_kind="sink" component_id=test_out component_type=console component_name=test_out}: vector_common::internal_event::bytes_sent: Bytes sent. byte_size=319 protocol=console
```

### Example Data

{"name":"test.histogram2","namespace":"","tags":{"tag1":"test"},"timestamp":"2023-04-27T21:14:32.781562380Z","kind":"absolute","aggregated_histogram":{"buckets":[{"upper_limit":1.0,"count":1},{"upper_limit":2.0,"count":2},{"upper_limit":5.0,"count":1},{"upper_limit":10.0,"count":1}],"count":5,"sum":30.0}}

**Comment by bruceg** [comment]
This appears to be working as intended. The `datadog_metrics` sink converts aggregate histograms into incremental sketches and submits them to the Datadog sketch API. Since they are incremental and the above histogram is absolute, it would need a second histogram to compute the differential between them before submitting.

**Comment by mfamahran** [comment]
That solves the problem, thanks for taking the time to check this out.
