### ISSUE TITLE
add batching to kafka source with file sink

### ISSUE THREAD

**Issue by krikkiteer** [vectordotdev/vector#17242]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

We wanted to stream kafka-messages to another server and store the messages as files for longterm-backup.
However performance is rather slow and can't keep up with the amount of messages, leading to an ever increasing lag in messages, eventually leading to dataloss (on 64 cores, 512G, 30 threads).

### Attempted Solutions

- increasing threads
- deactivating compression for filestorage
- deactivating acknowledgements in file-sink
- switching to unencrypted transmission
- switching to encrypted wireguard tunnel

### Proposal

I assume that the behaviour has its cause in each message getting fetched one by one, rather than batched, which would reduce unnecessary communication with kafka a lot and in turn increase throughput considerably.. 

this was already proposed in #7794 but rejected at the time due to no apparent need at the time, until such time, that the need arose... -> here we are ;-)

### References

#7794 

### Version

0.29.1-1

**Comment by bruceg** [comment]
Just to completely eliminate the sink side of things, could you replace the sink with a `blackhole` sink to see if that changes the rate at which the messages are handled? I would not expect a significant change given the current speed of the file sink. Also, what is the CPU utilization of the system when the lag is increasing?

The messages are actually not likely fetched individually from kafka, but those details are hidden by the `librdkafka` interface. Vector does handle them individually internally, which is likely a serious performance pessimization.

**Comment by krikkiteer** [comment]
wow - nice quick response.. 

- cpu utilization was nearly not existent during drops.

- great hint with the blackhole-sink (didnt know that one before) and it apparently was a problem with the sink after all.. 
the sink configuration had buffer.when_full = block and thats what it apparently did.. after increasing the memory-buffer to 500k events everything works smoothly now even _with_ compression enabled.

also, your hint about librdkafka-internals brought the thought of the docs up again.. and actually passing
  [sources.broker_logs.librdkafka_options]
  "fetch.min.bytes" = "1000000"

feels - at least subjectively - like a throughput improvement.

thank you very much for the quick push in the right direction! for now at least the current implementation seems to work well enough.. its night though, so i'll observe and report back if anything reaches limits with high event-volume.

:)

**Comment by bruceg** [comment]
Excellent. I'm glad to hear this helped you out. Since you have a solution to your issue, I'll close this for now. Feel free to reopen this or a new issue if the kafka source becomes a bottleneck.

**Comment by krikkiteer** [comment]
@bruceg i sadly have to reopen this again... after several days of testing it seems that the kafka-batching needs some improvement.. i moved the setup in the meantime to a server with faster disks and bandwidth, so i can eliminate all outside error-sources..  we have 200gbit interconnection between kafka and the server, only ssd's in use.. cpu/load is negligible - but the messages just cant be fetched and processed fast enough from the source-server when full-load is happening.

i also tried it agian with a blackhole sink to eliminate the sink-side of things.. kafka message lag just keeps increasing..
is there anything else you can think of, that we might try to improve performance ?

thanks!

**Comment by jszwedko** [comment]
Hi @krikkiteer !

We discussed this one a bit more today and came to the conclusion that we don't plan to add batching on top of what is done at the Kafka protocol level and is configurable via the [librdkafka options](https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md). I'd suggest playing around with those options some more to see if you can improve throughput.

Separately you could try increasing the thread count via `VECTOR_THREADS` and see if that has an impact.
