### ISSUE TITLE
Splunk HEC source adds input to root instead of message field if given nested objects

### ISSUE THREAD

**Issue by MadsRC** [vectordotdev/vector#17243]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

[The documentation indicates](https://vector.dev/docs/reference/configuration/sources/splunk_hec/#event-fields) that the Splunk HEC input will store the "raw line, unparsed" in the `message` field at the root.

However, if the input is provided with a JSON object in which the value of the `event` field is an object, as opposed to a string, then no `message` field is produced, and the value of the `event` field is placed at the root.

Given that the documentation mentions "raw line" and "unparsed", one could argue that the `message` field should, in this case, contain an escaped JSON string. Better yet, it could contain the parsed object.

The reason this is an issue is that it is impossible to distinguish values provided to the source from the fields that are generated automatically by Vector. What happens if the `event` field contains an object that has a field called `timestamp`? At best, the Vector generated `timestamp` field would be overwritten. At worst, the `timestamp` field provided to the source would be overwritten.

I tested it by sending the following 2 curl commands, and observing the following output:

```
curl -v "http://localhost:9000/services/collector" \
    -H "Authorization: Splunk abc" \
    -d '{"event": "Hello, world!", "sourcetype": "manual"}'

curl -v "http://localhost:9000/services/collector" \
    -H "Authorization: Splunk abc" \
    -d '{"event": {"data": "Hello, world!"}, "sourcetype": "manual"}' 
```

```
 {"message":"Hello, world!","source_type":"splunk_hec","splunk_sourcetype":"manual","timestamp":"2023-04-27T21:49:46.265118506Z"}
{"data":"Hello, world!","source_type":"splunk_hec","splunk_sourcetype":"manual","timestamp":"2023-04-27T21:50:45.651037756Z"}
```

### Configuration

```text
[sources.in]
type = "splunk_hec"
address = "0.0.0.0:9000"

[sinks.console]
type = "console"
inputs = ["in"]
[sinks.console.encoding]
codec = "json"
```

### Version

0.29.1

**Comment by jszwedko** [comment]
Hi @MadsRC ,

Thanks for this report. This behavior is admittedly confusing. We are in the process of implementing a new feature, which we are calling ["log namespacing"](https://github.com/vectordotdev/vector/blob/master/rfcs/2022-04-20-12187-log-namespacing.md), that will resolve the issue with colliding fields. Once that is in place, all Vector metadata fields (like `timestamp`) will end up in a separate "namespace", all Splunk metadata fields (like "sourcetype") will end up in their own namespace, and `.` will be set to whatever `event` is (which could be a string or an object). I think that will resolve the problem you are having.

Until that feature is complete I think we just need to update the docs to make the current behavior clearer.

**Comment by neuronull** [comment]
Hi @MadsRC ,

The log namespacing feature is available now, you can read some more about it here: https://vector.dev/blog/log-namespacing/

I will close this issue since we are handling the fields such as sourcttype, index, source. channel in the log namespacing logic for this component.
