### ISSUE TITLE
Make CSV encoder configurable

### ISSUE THREAD

**Issue by scMarkus** [vectordotdev/vector#17261]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Currently the CSV encoder used in multiple places like the S3 sink is using a standard configuration in terms of column separator (`,`) and quotation escaping (`"`). This conforms to [rfc 4180](https://www.rfc-editor.org/rfc/rfc4180). Anyway we are currently using a setup where we are using a tab delimited (TSV: `\t`) variant of it. Furthermore the respective data is read via Apache Spark which uses `\` as quotation escape character as its [default](https://spark.apache.org/docs/latest/sql-data-sources-csv.html). We would like to transparently move the logging pipeline towards vector without disrupting the downstream processes which would make said configuration options mandatory to us when writing the data.

### Attempted Solutions

As far as I can see there is no documented configuration option to change the described behavior. Looking into the vector source it seams to me as the relevant part is: 
https://github.com/vectordotdev/vector/blob/4b80c714b68bb9acc2869c48b71848d11954c6aa/lib/codecs/src/encoding/format/csv.rs#L80
This is using [from_writer](https://docs.rs/csv/latest/csv/struct.Writer.html#method.from_writer) of the respective CSV library which sets default values. Alternatively a [WriterBuilder](https://docs.rs/csv/latest/csv/struct.WriterBuilder.html) of the same library could be used which has option to set a [delimiter](https://docs.rs/csv/latest/csv/struct.WriterBuilder.html#method.delimiter) and [quotation escape char](https://docs.rs/csv/latest/csv/struct.WriterBuilder.html#method.escape) as well as some other configs.

### Proposal

What indeed does exists in the documentation already is the required `encoding.csv.fields` option. In my mind it would be a nice fit to extend `encoding.csv` by `encoding.csv.delimiter` and `encoding.csv.quotation_escape` and use those to configure the `csv::WriterBuilder`.

### References

 feat(codec): Add csv encoding for sinks #16603 

### Version

vector 0.29.0 (x86_64-unknown-linux-gnu 33b3868 2023-04-11 22:19:54.512366263)

**Comment by scMarkus** [comment]
Would the proposed approach be reasonable? I may find some time trying to implement this. If so would one be so kind and hint me at how to implement new config options?

**Comment by spencergilbert** [comment]
I'll see if I can get @vectordotdev/ux-team to respond by the end of the week - we have started adding some options on codecs like `decoding.<codec>.<option>` ([ref](https://master.vector.dev/docs/reference/configuration/sources/socket/#decoding.gelf.lossy)).

So I could see the `encoding.csv.<options>` fitting in with that pattern.

**Comment by jszwedko** [comment]
Agreed, the options can be nested as suggested like:

```
encoding.csv.delimiter = ...
encoding.csv.quotes = ...
```

We'd be happy to see a PR for this if you feel motivated @scMarkus. The options would be added here: https://github.com/vectordotdev/vector/blob/c21f892e574579e323742da009f15a39c43555af/lib/codecs/src/encoding/format/csv.rs#L51-L60
