### ISSUE TITLE
Elastic version auto-detection needs to happen when connection to Elastic is established.

### ISSUE THREAD

**Issue by syedriko** [vectordotdev/vector#17279]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

This is a sequel to https://github.com/vectordotdev/vector/issues/17226.

At the moment, version auto-detection of Elasticsearch server happens at config parsing time and if the Elastic server is not available, we're going to hit https://github.com/vectordotdev/vector/blob/1e432089f4a3375b2a6dfefb1de3197af5f2313d/src/sinks/elasticsearch/common.rs#L151, which is going to assume a version that can end up being incorrect. It appears that version auto-detection needs to happen not at config parsing time but right after we've established a connection with Elastic.
A case can likely be made for re-detecting Elastic version every time the connection is re-established.

### Version

vector 0.30.0-custom-752d4245c (x86_64-unknown-linux-gnu debug=full)

**Comment by spencergilbert** [comment]
Thanks! This is currently happening [here](https://github.com/vectordotdev/vector/blob/4335b0a34a44af82bb63739e8e9b3ffc72ecf3f7/src/sinks/elasticsearch/config.rs#L471) in the `build` function. I don't think there's anything stopping us from moving the version detection into runtime, given (IIRC) it only affects how we're encoding payloads.

The startup problem could also be solved with https://github.com/vectordotdev/vector/issues/16810

**Comment by dsmith3197** [comment]
After discussing with the team, we have determined that auto-detection is complicated and doesn't always work properly (e.g., opensearch). We'd prefer to deprecate support for auto-detection and rather default to v8.
