### ISSUE TITLE
Source File: issue with file rotation which not using logrotate

### ISSUE THREAD

**Issue by inatale** [vectordotdev/vector#17305]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We use vector to get and parse FreeIPA logs (/var/log/dirsrv/<name>/access*. But vector stops receiving logs after log rotation happened (even after service restart). We think it somehow related to how vector works with file rotation. Usually if rotation is configured using logrotate (like apache logs for example) everything is ok but it seems that FreeIPA works with rotation in different way (https://fossies.org/linux/389-ds-base/ldap/servers/slapd/log.c) and not using logrotate. 

### Configuration

```text
[api]
enabled = true

[sources.freeipa_additional_logs]
type = "file"
include = [ "/var/log/apache2/*.log", "/var/log/ipa/*.log", "var/log/pki/pki-ca-spawn.*.log", "/var/log/pki/pki-kra-spawn.*.log", "/var/log/dirsrv/*/audit", "/var/log/dirsrv/*/errors", "/var/log/sssd/*.log" ]

[sources.freeipa_access_log]
type = "file"
include = [ "/var/log/dirsrv/<--name-->/access*"]

[sources.freeipa_logs]
type = "file"
# include = [ "/var/log/apache2/error.log", "/var/log/auth.log", "/var/log/dirsrv/<--name-->/access" ]
include = [ "/var/log/auth.log" ]


[sinks.vector_cached]
type = "vector"
# inputs = [ "freeipa_logs" ]
inputs = [ "freeipa_auth", "freeipa_additional_logs", "freeipa_access" ]
address = "<--ip-address--and--port-->"

[transforms.freeipa_auth]
type = "remap"
inputs = [ "freeipa_logs" ]
drop_on_abort = true
# some transformation

[transforms.freeipa_access]
type = "remap"
inputs = [ "freeipa_access_log" ]
drop_on_abort = true
# some transformation
"""
```

### Version

0.28.2

**Comment by inatale** [comment]
@spencergilbert , thank you a lot. Now it works. We had to look through documentation more carefully :)

**Comment by spencergilbert** [comment]
Nice! I'm glad that solved it for you.
