### ISSUE TITLE
enable zstd compression for aws-s3 sink

### ISSUE THREAD

**Issue by vbmithr** [vectordotdev/vector#17324]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Decompression is supported in aws-s3 source, the sink should match it.

**Comment by akoshchiy** [comment]
@spencergilbert Hi! Can I try to pick it up? It seems pretty easy - just to extend behavior in Compressor api.

**Comment by ziz** [comment]
> I swear there was already an open issue for this, but I'm not finding it.

#2302 looks to be the higher-level "add zstd to sinks" feature request, but that's a broader thing than specifically adding it to aws_s3.

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/17371
