### ISSUE TITLE
File handle hoarding

### ISSUE THREAD

**Issue by djrodgerspryor** [vectordotdev/vector#17349]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We generate new log files periodically and listen to them with a vector file source. We set `remove_after_secs = 300` so that vector will clean up these files once it's done with them.

What we see though, is that vector doesn't delete many of these files, and even if we delete old files externally, vector holds open file handles to them so that their disk space isn't deallocated, leading to an out of disk space error once we collect many GB of logs.

Note that each of the below files has it's creation time in it's name, and some of them are many hours old (and thus definitely not still being written-to), yet are still being held open:
```
[ec2-user@rds-log-shipper-i-061242cc1da41d3dd.au.s522.net ~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        7.7G     0  7.7G   0% /dev
tmpfs           7.7G     0  7.7G   0% /dev/shm
tmpfs           7.7G  792K  7.7G   1% /run
tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup
/dev/nvme0n1p1  8.0G  2.8G  5.2G  35% /
/dev/nvme1n1     30G  2.6G   28G   9% /var/lib/docker
/dev/nvme2n1    148G  136G  4.5G  97% /rds_log_shipper
tmpfs           1.6G     0  1.6G   0% /run/user/1000
[ec2-user@rds-log-shipper-i-061242cc1da41d3dd.au.s522.net ~]$ sudo lsof -nP | rg '(deleted)'
vector    26165                 root   11r      REG              259,0 335266114    6815962 /rds_log_shipper/data/logs/live-db-v13/audit/server_audit.log.2023-05-09T01:28:11.998545051+00:00 (deleted)
vector    26165                 root   12r      REG              259,0 267655118    6815820 /rds_log_shipper/data/logs/live-db-v13/audit/server_audit.log.2023-05-08T23:41:13.305416353+00:00 (deleted)
vector    26165                 root   13r      REG              259,0 291473967    6816075 /rds_log_shipper/data/logs/live-db-v13/audit/server_audit.log.2023-05-09T03:01:53.465262084+00:00 (deleted)
vector    26165                 root   14r      REG              259,0 297600347    6815838 /rds_log_shipper/data/logs/live-db-v13/audit/server_audit.log.2023-05-08T23:51:35.614919697+00:00 (deleted)
vector    26165                 root   15r      REG              259,0 303493865    6815758 /rds_log_shipper/data/logs/live-db-v13/audit/server_audit.log.2023-05-08T23:24:19.434446653+00:00 (deleted)
vector    26165                 root   16r      REG              259,0 269020864    6815768 /rds_log_shipper/data/logs/live-db-v13/audit/server_audit.log.2023-05-08T23:25:07.309375460+00:00 (deleted)
vector    26165                 root   17r      REG              259,0 279826602    6816188 /rds_log_shipper/data/logs/live-db-v13/audit/server_audit.log.2023-05-09T04:36:23.888551025+00:00 (deleted)
vector    26165                 root   18r      REG              259,0 300086066    6815762 /rds_log_shipper/data/logs/live-db-v13/audit/server_audit.log.2023-05-09T01:23:12.129845036+00:00 (deleted)
...
```

This vector instance processes seveal hundred GB of logs per day, and it takes a day or two for the 150GB disk to fill up, so it's only a portion of files which are being held open. We do also see logs from vector indicating that files are being deleted, eg:

```
2023-05-09T08:58:34.107949Z  INFO source{component_kind="source" component_id=rds_logfiles_default component_type=file component_name=rds_logfiles_default}:file_server: vector::internal_events::file::source: Stopped watching file. file=/rds_log_shipper/data/logs/live-db-v13/slowquery/mysql-slowquery.log.2023-05-09.0.2023-05-09T08:53:24.222731666+00:00
2023-05-09T08:58:34.107960Z  INFO source{component_kind="source" component_id=rds_logfiles_default component_type=file component_name=rds_logfiles_default}:file_server: vector::internal_events::file::source: Stopped watching file. file=/rds_log_shipper/data/logs/named-locks-db-prod-default-ap-southeast-2/error/mysql-error-running.log.2023-05-03.4.2023-05-09T08:53:24.233075858+00:00
```

We do have acknowledgements enabled globally, I wonder if some events are somehow stuck and that's preventing their source files from being closed? All of these logs are directed to another vector instance as the final sink.

### Configuration

```text
acknowledgements.enabled = true

[sources.rds_logfiles_default]
type = "file"
include = [
	"${LOG_DESTINATION_PATH:?LOG_DESTINATION_PATH must be specified for vector to run!}*/**/*"
]
# These need special handling
exclude = ["**/PrePatchCompatibility.log*"]
file_key = "logfile_path"
read_from = "beginning"
# The log shipper won't move or recreate any files, so this is the safest deduplication method
fingerprint.strategy = "device_and_inode"
# Vector will remove log files after they've been read, if no new data has been
# written in the last 5 minutes. This is safe because the log shipper will just
# re-create the file and put any new data in it if data is written after that point.
# This stops us from running out of disk space.
remove_after_secs = 300

[sources.rds_logfiles_pre_patch_compatibility]
type = "file"
include = [
	"${LOG_DESTINATION_PATH:?LOG_DESTINATION_PATH must be specified for vector to run!}**/PrePatchCompatibility.log*"
]

# Really dumb multi-line handling to just suck the whole file into a single log
multiline.condition_pattern = ".*"
multiline.mode = "continue_through"
multiline.start_pattern = "^Executing Compatibility Checks"
multiline.timeout_ms = 180000 # Wait 3 mins for new lines before ingesting

# Same config as rds_logfiles_default
file_key = "logfile_path"
read_from = "beginning"
fingerprint.strategy = "device_and_inode"
remove_after_secs = 300

...
```

### Version

vector 0.29.1 (x86_64-unknown-linux-gnu 74ae15e 2023-04-20 14:50:42.739094536)

### Additional Context

This instance of vector is running in a docker container with a volume mount to the watched volume on the host.

**Comment by spencergilbert** [comment]
👋 

> We do also see logs from vector indicating that files are being deleted...

Do the files referenced in these logs continue to be held, or are they properly removed once deleted?

Vector _could_ be holding handles if it hasn't confirmed it's finished reading the entire file and if it's falling behind far enough that could explain the behavior.

**Comment by djrodgerspryor** [comment]
> Do the files referenced in these logs continue to be held, or are they properly removed once deleted?

I spot checked a few and they seem to actually be deleted. I'll keep an eye on it over the next day or so as the load varies and see if that changes under stress.

Taking a look at the `open_files` metric over the last day, it looks like it suddenly starts growing at a certain point (possibly triggered by load):

<img width="1504" alt="Screenshot 2023-05-10 at 7 55 46 am" src="https://github.com/vectordotdev/vector/assets/3197007/46108643-3a67-4e4f-be1b-706552ac777c">

**Comment by djrodgerspryor** [comment]
As a workaround, we've taught our service to truncate old logfiles before deleting them (so that we can reclaim the disk space even if vector keeps the file handle open), but interestingly, vector now seems to be closing the file handles properly:

<img width="1505" alt="Screenshot 2023-05-10 at 11 40 27 am" src="https://github.com/vectordotdev/vector/assets/3197007/e8454041-4f0e-4bf4-8f53-27458b45ea3f">

Today (with file truncation), even under high load, the number of open file handles has stabilised and `lsof ` shows no deleted files held open.

I guess that suggests that something about the file contents was causing vector to keep them around.

**Comment by djrodgerspryor** [comment]
Is there any particular metric I should be looking at to check if vector is falling behind? The buffer size metrics look pretty steady and `buffer_discarded_events_total` only shows dropped metrics, not any logs.

**Comment by jszwedko** [comment]
@djrodgerspryor you could look at the utilization metric for components processing logs. If any are `1` or close to `1` that could indicate a bottleneck downstream of the `file` source, that is causing back-pressure.

Separately it could be the `file` source itself that isn't keeping up. You could try tweaking `max_read_bytes`. We've seen people get better performance by tweaking that value so that Vector reads more from each file before switching to the next file to be read.

Even if files are deleted, Vector will continue trying to hold them open and read them until it has finished reading. Once it gets to the end of a deleted file, it should drop the handle.

**Comment by djrodgerspryor** [comment]
It looks like our highest utlitisation is the firehose sink, which is pretty consistently at ~50%.

<img width="1511" alt="Screenshot 2023-05-12 at 9 15 18 pm" src="https://github.com/vectordotdev/vector/assets/3197007/bec916d1-5d53-4a81-b1a9-1474a1a14cda">


I'll try bumping `max_read_bytes` and report back.

**Comment by djrodgerspryor** [comment]
No change after increasing `max_read_bytes` unfortunately.

<img width="3192" alt="Screenshot 2023-05-16 at 1 34 02 pm" src="https://github.com/vectordotdev/vector/assets/3197007/e98d7dc8-f63c-40c7-9267-b7d08e7acc91">

Any other ideas for where the bottleneck could be (or how to find it)?

**Comment by jszwedko** [comment]
Hrm, yeah, could you share your full config? The fact that none of the components seem saturated makes it sound like it's `file` source not reading fast enough.

**Comment by jszwedko** [comment]
Closing as stale. It seems likely that the `file` source just couldn't keep up here.
