### ISSUE TITLE
Vector_build_info metric is not exporting to Prometheus

### ISSUE THREAD

**Issue by seanocca** [vectordotdev/vector#17345]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I have exposed metrics to our Prometheus scraper and all other metrics are flowing to our data source on Grafana except `vector_build_info`. This is important for us to see for our alerts and keeping up to date with the latest version.

### Configuration

```text
customConfig:
    data_dir: "/vector-data-dir"

    api:
      enabled: true
      address: 0.0.0.0:8686

    sources:
      kubernetes_logs:
        type: kubernetes_logs

      internal_metrics:
        type: internal_metrics

    transforms:
      filter_out_pods:
        type: filter
        inputs: ["kubernetes_logs"]
        condition: |
          .kubernetes.container_name != "api-gateway"

      add_brand:
        type: remap
        inputs: ["filter_out_pods"]
        source: |-
          .brand = "NOT_SET"

      normalised_logs:
        type: remap
        inputs: ["add_brand"]
        source: |-
          .host = "${KUBERNETES_NODE_NAME}"

      pod_log_count:
        type: log_to_metric
        inputs: ["normalised_logs"]
        metrics:
          - type: "counter"
            field: "kubernetes.pod_name"
            name: "vector_agent_pod_log_count"
            tags:
              pod: "{{`{{kubernetes.pod_name}}`}}"
              node: "{{`{{kubernetes.pod_node_name}}`}}"
              namespace: "{{`{{kubernetes.pod_namespace}}`}}"

    sinks:
      blackhole:
        type: blackhole
        inputs: ["normalised_logs"]

      prometheus:
        type: prometheus_exporter
        inputs: ["internal_metrics", "pod_log_count"]
        address: "0.0.0.0:80"
```

### Version

0.24.0

### Additional Context

We have Vector running in Kubernetes in both agent and stateless-aggregator modes for different deployments. Neither of them report vector_build_info. We scrape prometheus metrics through an endpoint on port 80 with url /metrics. The configuration provided is from our agent deployment.

**Comment by spencergilbert** [comment]
👋 the version you're running is out of date and doesn't contain that metric. [It was added in `0.25.0`](https://vector.dev/releases/0.25.0/#changelog), please upgrade your Vector version.
