### ISSUE TITLE
Vector shouldn't use the `test` VRL feature

### ISSUE THREAD

**Issue by fuchsnj** [vectordotdev/vector#17377]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Previously the `vrl` crate had an internal `test` feature that was un-intentionally enabled. This was caught and fixed in recent VRL refactoring. (VRL `0.4.0`).

Vector was relying on this in a few places where is shouldn't be (all related to converting an `f64` into a `Value`. That implementation is normally only available for tests, since the `f64` needs to be checked for `NaN` first).
As a quick fix, to keep existing behavior, the `test` feature was explicitly enabled for VRL. This should be fixed and removed.

### Version

0.29

**Comment by dsmith3197** [comment]
@pront please confirm that this is fixed.

**Comment by pront** [comment]
Vector still enables the `test` VRL feature. +1 on removing this.
