### ISSUE TITLE
Pagination in vector top output

### ISSUE THREAD

**Issue by D13410N3** [vectordotdev/vector#17392]
### A note for the community

Hello

When there are a lot of components in Vector there is no way to see actual `vector top` info for every component - it is just showing info that can be adjusted on screen
Example:
![image](https://github.com/vectordotdev/vector/assets/5101042/ad9a6b05-e974-4f86-a862-102775e81b48)
There a lot of components that can't be seen - there are two way to watch them - use bigger screen or scale to 50%

Maybe, there's an ability to add pagination?

### Version

0.28.1

**Comment by jszwedko** [comment]
Thanks @D13410N3 ! I think this is similar enough to https://github.com/vectordotdev/vector/issues/5883 that I'll just fold it into that issue. We could do either pagination or scrolling to solve this need.
