### ISSUE TITLE
Vector cannot handle the throttle exception from Kinesis data stream

### ISSUE THREAD

**Issue by dengmingtong** [vectordotdev/vector#17424]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I use vector to sink the data to Kinesis data stream, some requests are throttled, but vector cannot catch these exception and still return successful response to front-end.

Is it vector issue or any config I can set to handle these exception?

Thanks,
Mingtong

### Configuration

```text
[sinks.kinesis_sink]
type = "aws_kinesis_streams"
inputs =  ["json_parser"]   
partition_key_field = "timestamp"
compression = "none"
region = "%%AWS_REGION%%"
stream_name = "%%AWS_KINESIS_STREAM_NAME%%"

acknowledgements.enabled = true
  [sinks.kinesis_sink.encoding]
  codec = "json"
```

### Version

0.25.1-debian

**Comment by dengmingtong** [comment]
Thank you very much for your response.
Actually, I have another question, if the request to Kinesis data stream is throttled, I think vector should return an error code to front-end, but currently, vector still return successful response to front-end.
Is it an issue or how should I config vector .toml?

Thanks,
Mingtong

**Comment by jszwedko** [comment]
> Thank you very much for your response. Actually, I have another question, if the request to Kinesis data stream is throttled, I think vector should return an error code to front-end, but currently, vector still return successful response to front-end. Is it an issue or how should I config vector .toml?
> 
> Thanks, Mingtong

The expected behavior is that Vector retries these requests so it would wait to respond to the front-end until they were successful. This isn't implemented yet though (see https://github.com/vectordotdev/vector/issues/12835).

**Comment by dengmingtong** [comment]
T

> 

So suppose kinesis has some problem, the request can never be delivered to kinesis, vector is able to return error response to front-end?

**Comment by dengmingtong** [comment]
I already set acknowledgements.enabled = true, but when request is throttled by kinesis, vector still return successful response to front-end. it is an known issue or any other config I need to set?

**Comment by jszwedko** [comment]
> I already set acknowledgements.enabled = true, but when request is throttled by kinesis, vector still return successful response to front-end. it is an known issue or any other config I need to set?

Ah, yeah, that sounds the same as https://github.com/vectordotdev/vector/issues/12835 but for `aws_kinesis_streams` instead. I confused your initial issue for `aws_kinesis_firehose`. I'll re-open for tracking.

**Comment by dengmingtong** [comment]
It seems a bit confusing, let me summarize my two questions:

1. Currently, when vector sends requests to **Kinesis Data Stream**, some messages are being throttled, but there are no retries.

1. If a request is throttled, and I have set **acknowledgements.enabled = true**, Vector still returns success response to the frontend.

Could you help to confirm whether these two issues are problems with Vector.
Is there any plan to fix them? 
Especially the second question is particularly important for us.

Thanks,
Mingtong

**Comment by dengmingtong** [comment]
Is there any estimation for these issues can be fixed?

**Comment by dengmingtong** [comment]
Hello, @jszwedko  because we are using vector to sink data to KDS, this issue caused we lose some data.
I have verify the PR https://github.com/vectordotdev/vector/pull/16771/files, it works for our case, May I copy this PR change and submit another PR for change?

**Comment by jszwedko** [comment]
> Hello, @jszwedko because we are using vector to sink data to KDS, this issue caused we lose some data. I have verify the PR https://github.com/vectordotdev/vector/pull/16771/files, it works for our case, May I copy this PR change and submit another PR for change?

That would be great! I think there were just a few comments on that PR that needed to be followed up on.

**Comment by neuronull** [comment]
👋  hello, does https://github.com/vectordotdev/vector/pull/17535 , close this issue?

**Comment by dengmingtong** [comment]
Yes, it is #17535 PR.

**Comment by dengmingtong** [comment]
Is there any progress? Seem the PR is still blocking there.

**Comment by jszwedko** [comment]
> Hello, @jszwedko, Is there any progress? Seem the PR is still blocking there.

Thanks for opening the new PR! Did you make the changes requested on the original PR? If so, we can give it a review.

**Comment by dengmingtong** [comment]
@jszwedko  Yes, I merge the commits from original PR and change code to fix some action checking.
Please help to review it. We need this fixing for our solution. :)

**Comment by jszwedko** [comment]
Thanks @dengmingtong ! We'll get this reviewed again then.

**Comment by spencergilbert** [comment]
> @jszwedko The PR is still not reviewed, we really need this change. Could you please help to speed up it. :)

Apologies @dengmingtong - It's been assigned to me, but I've been stuck on some other work and traveling. I'll be reviewing it later this afternoon, the earliest this would be released (out side of `nightly`) would be around July 5.

**Comment by dengmingtong** [comment]
@spencergilbert spencergilbert
Thanks for your review, I have rebase and refactored the code, could you please help to review it again. 
:)

**Comment by dengmingtong** [comment]
@spencergilbert spencergilbert
Got your comments yesterday, I have rebase and refactored the code, could you please help to review it again.
:)

**Comment by dengmingtong** [comment]
@jszwedko The PR is still open status and wait for another reviewer to approve.
Could you help to reminder the reviewer to go next step?
We really need this fixing.

**Comment by spencergilbert** [comment]
@dengmingtong apologies - the second reviewer has been out on PTO, they should be back today and I'll have them take a look.

**Comment by dengmingtong** [comment]
@spencergilbert  I have updated the PR again, and could you please to review it and also reminder second reviewer to go next step?
We really need this fixing. Because of jet lag, if there is small change comments, could you help to refactor the code and make this PR merged as soon as possible. :)

**Comment by dengmingtong** [comment]
@spencergilbert  I saw the PR has been removed from merge queue due to test-integration failed. I do not have this experience, could you help to solve this test-integration failure? 
Thank you so much. :)

**Comment by dengmingtong** [comment]
Thank you very much to merge the PR, but I have to open the issue again.
Just want to know is there any plan to release new version to include this change?
Is it possible to release next week?
