### ISSUE TITLE
installation for raspberry pi is failing

### ISSUE THREAD

**Issue by gowthamgts** [vectordotdev/vector#17450]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Looks like the installation script is not working for raspberry pi. I followed the docs - https://vector.dev/docs/setup/installation/manual/vector-installer/

```shell
$ uname -a
Linux pi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.vector.dev | bash

                                   __   __  __
                                   \ \ / / / /
                                    \ V / / /
                                     \_/  \/

                                   V E C T O R
                                    Installer


--------------------------------------------------------------------------------
Website: https://vector.dev
Docs: https://vector.dev/docs/
Community: https://vector.dev/community/
--------------------------------------------------------------------------------

>>> We'll be installing Vector via a pre-built archive at https://packages.timber.io/vector/0.29.1/
>>> Ready to proceed? (y/n)

>>> Please enter y or n.
>>> y

--------------------------------------------------------------------------------

vector: unsupported arch: armv7-unknown-linux-gnueabihf
```

I can see the same issue has been raised by others as well in the past: #2301 #4669

### Version

NA

**Comment by jszwedko** [comment]
Thanks for opening this @gowthamgts . I think https://github.com/vectordotdev/vector/pull/17484 should fix it.
