### ISSUE TITLE
Order by / sort by for reduce

### ISSUE THREAD

**Issue by alippai** [vectordotdev/vector#17523]
When processing out of order messages (eg UDP source) there is no way to add seq_num field. A complete implementation would also have a “total messages” in the first message and raising error if messages are missing after the configured buffer time.

I can imagine fragmentation and reassembly of larger UDP messages can be a common pattern.

**Comment by tobz** [comment]
Well, there's a few things going on, some of which you could handle today and some of which can't/won't be handled by Vector at all.

At a high level, UDP packets have no concept of a sequence number like TCP packets do. IP itself has a concept of fragmentation, and bakes in the fragment offset and has flags for whether or not more fragments should be expected.. but we don't have access to that with the networking primitives we use in Vector, and trying to surface that is out of the question given the complexity-to-value ratio.

With that said, any sequence numbers would have to be added by the upstream sender, which would mean manually fragmenting those UDP datagrams. If you could manually fragment them and add such a field, one trick would be to use the `array` merge strategy for `reduce`, for both the sequence number field and then whatever field you want to reduce, like a log message fragment, and so on.

With that reduced event structure, you could use `remap` to both iterate over said reduced fields and rebuild the original, unfragmented message, as well as detect if there's a gap in the sequence numbers present in the reduced event and emit an error.

Overall, while UDP fragmentation and out-of-order receiving may be a real-world concern, Vector is not in a position to solve it, and other protocol should be used instead if ordering is a hard requirement.
