### ISSUE TITLE
Vector instances with a sink to a central vector instance only validate TLS on initial handshake. Feature or bug?

### ISSUE THREAD

**Issue by rcousens** [vectordotdev/vector#17631]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I'm not sure this is a bug or a design flaw, or even maybe a feature. Recently we replaced our vector "sink" instances (a central aggregator) and in doing so all the vector source instances had to renegotiate the TLS handshake and we found out our TLS cert had expired on the central aggregator the day before but log volume was unaffected as it seems the connections are quite long-lived and the expiry date is only validated on the initial handshake. 

Should Vector be evaluating the health of the TLS connection more periodically? Should it allow sending to a sink with an expired TLS cert when the expiry happens in the middle of a period of stable operation once a connection to a vector sink has already been opened?

I expected the behaviour to be more along the lines of refusing to continue the connection once the expiry had lapsed but perhaps I'm misguided and this is too much to ask of it during an existing connection.

### Configuration

```text
N/A
```

### Version

0.29.0

**Comment by jszwedko** [comment]
Hi @rcousens !

This is an interesting issue. Vector should validate the certificate on each handshake but you are correct that I don't think the certificate is considered after the connection has been established. Are you aware of other programs, especially similar ones to Vector like FluentD, Logstash, etc., that close connections after establishing if the certificate used in the handshake is later expired? I haven't previously heard of that sort of behavior of TLS connections, but I also never thought about it much before 😄 That would help inform how "expected" this behavior is.

We have had requests to limit connection lifetimes. That seems like that would at least help mitigate the issue for you if it, say, only had connections that lasted 60 seconds. Would it be sufficient? Or do you really need the connection to terminate if the certificate it used during the handshake later expires?

**Comment by rcousens** [comment]
Hi @jszwedko, thanks for the considered reply. After some considered thought I think I have come to the conclusion that Vector's current behaviour is correct. 

I think in the instance that there was a scenario where mTLS was being used for both authentication and authorization then I'd consider the behaviour inappropriate for the use case. But in the instance that the TLS connection is long-lived, and the SSL handshake was successful at a point in the past, then it's reasonable to assume it's connected to the same "thing" so the certificate is valid for its purposes still. Reconnecting and failing to negotiate TLS should be expected in this case and is.

I'll close this ticket, but thanks for listening and considering it! I think an option to limit connection lifetimes could indeed mitigate this issue. Cheers!
