### ISSUE TITLE
Specifying a merge_strategy has no effect on nested fields.

### ISSUE THREAD

**Issue by jsbali** [vectordotdev/vector#17637]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Specifying a merge_strategy for a nested field has no effect and it uses DiscardMerger for the top-level field.

Going through the code at [reduce/mod.rs](https://github.com/vectordotdev/vector/blob/c7e0b2ca94ffdeabfbdbae0c4a3a845c3752026b/src/transforms/reduce/mod.rs#LL242C35-L242C35) 
We basically look at top-level fields only even though the correct Strategy exists for the nested field.

Can we please check this one.

### Configuration

```text
[sinks.Out]
type = "console"
inputs = [ "Reducer" ]
encoding.codec = "json"

[sources.In]
type = "stdin"
decoding.codec = "json"

[transforms.Reducer]
group_by = [ "k" ]
inputs = [ "In" ]
type = "reduce"
merge_strategies."log.msg" = "concat_newline"
```

### Version

vector 0.31.0 (aarch64-apple-darwin)

### Example Data

{"k":"1", "log":{"msg":"first"}}
{"k":"1", "log":{"msg":"second"}}

### Additional Context

Expected the output to be 
`{"k":"1", "log":{"msg":"first\\nsecond"}}`

**Comment by KJTsanaktsidis** [comment]
Or perhaps the real solution here is https://github.com/vectordotdev/vector/issues/18324
