### ISSUE TITLE
Unexpected concurrency behavior

### ISSUE THREAD

**Issue by vimmerru** [vectordotdev/vector#17639]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hello,

I am trying to get maximum throughput of my pipeline and noticed that performance of sink is always limited despite the amount of streams it joins and can't utilized all resources. Just a trivial example 

if i have 2x `demo_logs` routed to one `http` sink (i use http_test_server) it gives ~250k eps. 

```
[sources.demo_logs]
type = "demo_logs"
format = "json"
interval = 0.0

[sources.demo_logs2]
type = "demo_logs"
format = "json"
interval = 0.0

[sinks.http]
type = "http"
inputs = [ "demo_logs", "demo_logs2"]
uri = "http://localhost:8080"
encoding.codec = "native"
request.concurrency = "adaptive"
```

if i route each `demo_logs` to it's own `http` sink performance increases near twice (to ~480k eps)

```
[sources.demo_logs]
type = "demo_logs"
format = "json"
interval = 0.0

[sources.demo_logs2]
type = "demo_logs"
format = "json"
interval = 0.0

[sinks.http]
type = "http"
inputs = [ "demo_logs" ]
uri = "http://localhost:8080"
encoding.codec = "native"
request.concurrency = "adaptive"

[sinks.http2]
type = "http"
inputs = [ "demo_logs2" ]
uri = "http://localhost:8080"
encoding.codec = "native"
request.concurrency = "adaptive"
```

I tried different request concurrency settings and real streams instead of demo_logs, but behavior is quite similar. 

Does this behavior expected and documented somehow or it is a bug?

### Version

vector 0.30.0 (x86_64-apple-darwin 38c3f0b 2023-05-22 17:38:48.655488673)

**Comment by neuronull** [comment]
noting that this was also discussed a bit on discord:

https://discord.com/channels/742820443487993987/1116351958140338256

This seems to be a limitation of the `http` sink.

**Comment by neuronull** [comment]
I attempted to repro this and suspect I'm running into limitations with environment. I am topping out at 57k eps (in the case of one http sink).

**Comment by vimmerru** [comment]
@neuronull Have you consumed all resources? If you have 57k, but cpu's are still available it means you reproduced the case.

**Comment by vimmerru** [comment]
I can also suggest setup 2 vectors

- first: demo_log -> http
- second: http->blackhole

It allows easy setup performant pipelines that can show concurrency issue on usual developer pc.

**Comment by pront** [comment]
Hi @vimmerru, did you confirm this behavior with configs for [this scenario](https://github.com/vectordotdev/vector/issues/17639#issuecomment-1655330797) as well?

I did the following quick experiment on my M1 Max.

## Single sink

### config
```
[api]
enabled = true

[sources.demo_logs]
type = "demo_logs"
format = "json"
interval = 0.0

[sources.demo_logs2]
type = "demo_logs"
format = "json"
interval = 0.0

[sinks.http]
type = "http"
inputs = [ "demo_logs", "demo_logs2"]
uri = "http://localhost:8000"
encoding.codec = "native"
request.concurrency = "adaptive"
```

### Vector top
<img width="1423" alt="~CLionProjectsvectortargetdebugvector top 2023-08-16 at 5 11 58 PM" src="https://github.com/vectordotdev/vector/assets/1138161/47c51344-7fd2-4bfb-8a77-ab01a19e6dab">


## Different sinks

### config
```
[api]
enabled = true

[sources.demo_logs]
type = "demo_logs"
format = "json"
interval = 0.0

[sources.demo_logs2]
type = "demo_logs"
format = "json"
interval = 0.0

[sinks.http]
type = "http"
inputs = [ "demo_logs" ]
uri = "http://localhost:8000"
encoding.codec = "native"
request.concurrency = "adaptive"

[sinks.http2]
type = "http"
inputs = [ "demo_logs2" ]
uri = "http://localhost:8000"
encoding.codec = "native"
request.concurrency = "adaptive"
```

### Vector top
<img width="1403" alt="~CLionProjectsvectortargetdebugvector top 2023-08-16 at 5 17 14 PM" src="https://github.com/vectordotdev/vector/assets/1138161/d4cf921b-ca94-4ac8-b149-2378431665a5">

**Comment by vimmerru** [comment]
I unable reproduce the behaviour with high performant http-server now. Both configs give similar performance (~400k eps). Maybe something changed in 31-32 releases. Will continue the experiments tomorrow with real sink.

**Comment by pront** [comment]
Thank you @vimmerru for your investigation. Let us know if you have new findings.

**Comment by jszwedko** [comment]
One observation made recently is that the adaptive concurrency algorithm (`request.concurrency = "adaptive"`) has a cap of 200 concurrent requests. You should be able to look at the https://vector.dev/docs/reference/configuration/sources/internal_metrics/#adaptive_concurrency_limit metric to see if you are bumping into this limit.

Limit in the code: https://github.com/vectordotdev/vector/blob/40f525cae3eb7c6867afeeed4b2bd82cf85f5a65/src/sinks/util/adaptive_concurrency/mod.rs#L14

**Comment by jszwedko** [comment]
Closing since this seems to be resolved after upgrading, but please leave a comment with any new findings.
