### ISSUE TITLE
source type 'syslog' do not support rfc3164

### ISSUE THREAD

**Issue by Lempossible** [vectordotdev/vector#17654]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I want to take nginx access_log in syslog format as vector's source。But vector parse syslog failed. It seems that vector do not support  syslog in rfc3164 format.

### Configuration

```text
[sources.nginx_syslog]
type = "syslog"
address = "127.0.0.1:9000"
mode = "udp"

[transforms.parse_logs]
type = "remap"
inputs = ["nginx_syslog"]
source = '''
. = parse_syslog!(.message)
'''

[sinks.print]
type = "http"
inputs = ["parse_logs"]
uri = "http://127.0.0.1:28080/"
encoding.codec = "json"
```

### Version

master branch

**Comment by StephenWakely** [comment]
Looking at your configuration you are using the `syslog` source which is going to parse the incoming data as a syslog message. You are then piping this data to `remap` and then further parsing the already parsed message as another syslog message.

If you remove the remap transform this should work fine. 

I'll close this issue, but feel free to reopen and add more details if you continue to have problems.

**Comment by StephenWakely** [comment]
> You mean there is no need to call parse_syslog!(.message)? I want to use syslog as source and transform it into serval opentelemetry span. What should I do?

Correct. The `syslog` source already does the parsing for you. What results are you getting when you remove that transform?

We don't explicitly support opentelemetry spans, so you would need to transform the event to get it into a state that you need.
