### ISSUE TITLE
specail process after parse syslog in remap, before sinks

### ISSUE THREAD

**Issue by Lempossible** [vectordotdev/vector#17665]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

I want to do some special process to logs after parsing syslog(in remap). But as far as I know，lua is only for events，not for logs.  Is there a way to add a phase after remap where I can process parsed syslog in lua?

### Version

master branch

**Comment by StephenWakely** [comment]
In this case an "event" is the collective term for logs, metrics and traces. The `lua` transform is perfectly capable of working with Log events. Access the log fields under the `event.log` variable. See the example [here](https://vector.dev/docs/reference/configuration/transforms/lua/#examples-add-rename-and-remove-log-fields) for details.

**Comment by Lempossible** [comment]
How lua transfrom parses syslog from source ?

**Comment by StephenWakely** [comment]
> How lua transfrom parses syslog from source ?

I don't understand the question. Can you detail what you are trying to achieve?

**Comment by Lempossible** [comment]
I have learned how to use lua to transform.  I guess vector must have parsed syslog before transform. What I need to do is just implement hook.process in configuration or in an independent Lua file.
Thanks a lot anyway.
