### ISSUE TITLE
Request a new release for full retry of partial failures in kinesis streams

### ISSUE THREAD

**Issue by dengmingtong** [vectordotdev/vector#17706]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The [PR](https://github.com/vectordotdev/vector/pull/17535) has been merged for fix the issue of full retry of partial failures in kinesis streams.

May I know when the new version of vector will be released to include this change?
If it is possible, could you have a new release next week?

Thanks,
Mingtong

### Version

0.30.0

**Comment by jszwedko** [comment]
Hi @dengmingtong !

Thanks again for your contribution! You can find our release documentation here: https://github.com/vectordotdev/vector/blob/master/RELEASES.md . We release a new minor version every 6 weeks and the next one is scheduled for the week of July 4th; this change will be included there. Until then have a couple of options:

* Run the latest nightly build, which will also have these changes
* Build Vector yourself, with the changes, based on the 0.30.0 release. This would be slightly more "stable" than the nightly build

I'll close this out, but let us know if you have any other questions!
