### ISSUE TITLE
Collect additional network metrics that available in Prometheus Node Exporter

### ISSUE THREAD

**Issue by sirantd** [vectordotdev/vector#17734]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Virtual machines have network throughput limitations, so collecting such metrics as `node_ethtool_bw_in_allowance_exceeded`, 
`node_ethtool_bw_out_allowance_exceeded`,
`node_ethtool_pps_allowance_exceeded`,
`node_ethtool_conntrack_allowance_exceeded`,
`node_ethtool_linklocal_allowance_exceeded`

is very beneficial. I can't completely drop prometheus_node_exporter from the clusters and replace it with a vector agent without the ability to collect these additional metrics.

### Proposal

Add support for collecting additional metrics if ethtool is installed on the node

### References

Here you can find more details about this feature https://github.com/prometheus/node_exporter/issues/1908

**Comment by jszwedko** [comment]
Thanks @sirantd ! I think this is covered by https://github.com/vectordotdev/vector/issues/17247
