### ISSUE TITLE
Throttle config option to disable "key" label in events_discarded_total metric

### ISSUE THREAD

**Issue by Hexta** [vectordotdev/vector#17778]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Currently, throttle exposes every bucket as a `key` label in `events_discarded_total` metric:
```plain
events_discarded_total{key="value1"} 
events_discarded_total{key="value2"} 
...
events_discarded_total{key="valueN"} 
```
Using `key_field` with an unrestricted range of values (-Inf, +Inf) leads in cardinality explosion.

### Attempted Solutions

`filter` and `tag_cardinality_limity` transforms could help reduce cardinality at the output.
However, utilisation of these transforms will continue to increase proportionately to internal metrics cardinality.

### Proposal

Implement a configuration option for `throttle` transform to disable `key` label in the metrics.

### Version

0.30.0

**Comment by dsmith3197** [comment]
Note that there have been prior discussions on whether or not to drop the `key` label altogether [here](https://github.com/vectordotdev/vector/pull/17542).
