### ISSUE TITLE
encode_logfmt mishandles "="

### ISSUE THREAD

**Issue by grinapo** [vectordotdev/vector#17855]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I'm not sure whether there is a specification for _logfmt_, but clearly vector and loki have different mental images about equal signs. [This page](https://pkg.go.dev/github.com/kr/logfmt) seems to be a fair representation of both what I'd accept and what's possibly used by loki.

Problem:
```
$ encode_logfmt({"a":"= ", "b":"="})
"a=\"= \" b=="
```
(a) contains a space, so it gets properly escaped.
(b) contains an equal sign and it __should__ be escaped.

But maybe I'm wrong, and the quoted page overspecifies the format. Still, it _feels_ wrong not to quote '=' sign, and it indeed _looks_ wrong.

### Version

vector 0.30.0 (x86_64-unknown-linux-gnu 38c3f0b 2023-05-22 17:38:48.655488673)

**Comment by dsmith3197** [comment]
Hi @grinapo,

Thanks for providing all the necessary context. I went ahead an created a fix PR as it was a quick one.
