### ISSUE TITLE
Load balancing for splunk_hec sink

### ISSUE THREAD

**Issue by lukesteensen** [vectordotdev/vector#1786]
Users should be able to provide a list of endpoints to the `splunk_hec` sink. The implementation should then round-robin requests between these endpoints, temporarily removing any from the pool that return errors.

There are a few things to consider here:

* The sink healthcheck should check all provided endpoints
* When an error occurs, the request should be retried on a different endpoint
* If a request fails on one endpoint and succeeds on another, that should count against the health of that endpoint
* When an endpoint is sufficiently unhealthy (e.g. 2 errors in a row where the same request succeeded on another endpoint), that endpoint should be removed from the active set
* Endpoints outside of the active set should be periodically healthchecked to see if they should be brought back in to the active set
* We need to handle cases where the healthcheck of an endpoint works, but the actual requests do not. This should not result in the endpoint flapping in and out of the active set.
* We need to handle cases where all endpoints are failing, and continue to retry against all endpoints regardless of their health

**Comment by a-rodin** [comment]
I think this is related to https://github.com/timberio/vector/issues/762 and ideally should be done for all HTTP-based sinks in a uniform manner.

**Comment by jamtur01** [comment]
See also #3649.

**Comment by jszwedko** [comment]
Closing in-lieu of https://github.com/vectordotdev/vector/issues/2032
