### ISSUE TITLE
Support for ES datastream with empty namespace or dataset

### ISSUE THREAD

**Issue by Hexta** [vectordotdev/vector#17883]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

There is already existing ES index named `logs-frontend`.

We need to configure Vector  to send logs to this index.

### Attempted Solutions

Configuring `data_stream.namespace = ""` leads in ES index name `logs-frontend-` instead of `logs-frontend`

### Proposal

Replace fixed index name format `type-dataset-namespace` with:

- namespace is empty: `type-dataset`
- dataset is empty `type`

Check invariants:

- non-empty `namespace` requires non-empty `type` and `dataset`
- non-empty `dataset` requires non-empty `type`

### Version

0.30.0

**Comment by dsmith3197** [comment]
@Hexta, 

Thanks for pointing this out. This should be a relatively straightforward fix.

https://github.com/vectordotdev/vector/blob/e9f21a98b9f17035fb971f3f95476ec37d9bbe56/src/sinks/elasticsearch/config.rs#L464
