### ISSUE TITLE
vector takes up very high cpu and no longer processes data

### ISSUE THREAD

**Issue by z2665** [vectordotdev/vector#17916]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

In our k8s cluster, the vector was working fine, but it seems that after a program on the node printed some special logs (we don't know the details yet), the vector had a cpu full (we set a 1 core cpu limit) and was unable to write to the loki

You can see that the cpu used by the vector rises sharply after the problem occurs and reaches its limit
![image](https://github.com/vectordotdev/vector/assets/11162926/cf66d65b-ad6e-48f9-bf21-1f07d9affe80)

sum(increase(vector_component_sent_events_total{component_type="loki"}[5m])) The event sent by loki drops sharply, but not to 0, even though the back-end loki can no longer find the log
![image](https://github.com/vectordotdev/vector/assets/11162926/803a5b8f-0544-4546-9105-0841ea020b81)

I have two questions:
1. what log makes the vector behave this way
2. why does vector_component_sent_events_total not drop to 0

Tanks very much

### Version

0.23

**Comment by zamazan4ik** [comment]
> Version: 0.23

I highly recommend you update to the latest Vector versions and your test case once again. So old Vector versions are not actually supported.

**Comment by z2665** [comment]
Thanks, I will upgrade the vector to the latest version and keep an eye on it
