### ISSUE TITLE
Allow global schemas to be propagated as build args

### ISSUE THREAD

**Issue by Jeffail** [vectordotdev/vector#1792]
We currently use a global struct for storing schema paths which is wrapped within a `OnceCell`. This makes it easy to reference the schema paths from any component. However, this is also brittle and will potentially limit us in future. For example, when running the unit tests of multiple configuration files it's impossible to support per-config schemas. It's not likely for a user to hit this, and there's a work around (executing them as separate commands), but it's confusing and odd behavior that a user shouldn't really be exposed to.

The solution is to pass these fields from configuration all the way down to the component level. This is already being done with things like `SinkContext`. The next time someone needs to touch the build signature for a component they ought to consider tackling this at the same time.

**Comment by Hoverbear** [comment]
Yup this is a good way forward for this. :)

**Comment by binarylogic** [comment]
Noting, this is likely a moot issue since we will be ripping out the current support for schemas for a better alternative.

**Comment by jszwedko** [comment]
Closing since we are pursing removing these global schema options with https://github.com/vectordotdev/vector/issues/12187
