### ISSUE TITLE
Building `vdev` in CI during integration test suite workflow consumes unnecessary time

### ISSUE THREAD

**Issue by neuronull** [vectordotdev/vector#17946]
When https://github.com/vectordotdev/vector/pull/17725 was completed, this introduced additional CI time to compile `vdev` in order to run the file detection command.

This takes at least 9 minutes to complete (currently).

It could probably be addressed by caching in that workflow job, since `vdev` doesn't change all that often (respectively compared to vector).

**Comment by jszwedko** [comment]
Rolling into https://github.com/vectordotdev/vector/issues/18013 to track ideas for improving Vector's CI time in one place.
