### ISSUE TITLE
Compilation failure with Rust 1.71

### ISSUE THREAD

**Issue by tjni** [vectordotdev/vector#17978]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When compiling using Rust 1.71, the compiler reports a new warning:
```
   Compiling vector-buffers v0.1.0 (/private/tmp/nix-build-vector-0.31.0.drv-0/source/lib/vector-buffers)
error: variable does not need to be mutable
   --> lib/vector-core/src/tls/incoming.rs:266:13
    |
266 |         let mut this = self.get_mut();
    |             ----^^^^
    |             |
    |             help: remove this `mut`
    |
note: the lint level is defined here
   --> lib/vector-core/src/lib.rs:11:9
    |
11  | #![deny(warnings)]
    |         ^^^^^^^^
    = note: `#[deny(unused_mut)]` implied by `#[deny(warnings)]`

error: variable does not need to be mutable
   --> lib/vector-core/src/tls/incoming.rs:310:13
    |
310 |         let mut this = self.get_mut();
    |             ----^^^^
    |             |
    |             help: remove this `mut`

error: could not compile `vector-core` (lib) due to 2 previous errors
```

### Version

0.31.0

**Comment by jszwedko** [comment]
Hi @tjni !

You can see the current version of Rust we use with Vector in the `.rust-toolchain` file. We haven't updated to 1.71.0 yet.

I'll close this out, but I imagine we'll also update shortly.

**Comment by tjni** [comment]
Thank you!
