### ISSUE TITLE
Set Rust flag `codegen-units` to 1 for release Vector builds

### ISSUE THREAD

**Issue by a-rodin** [vectordotdev/vector#1798]
The results of tests performed by @bruceg in https://github.com/timberio/vector/issues/309#issuecomment-586505606 show that `codegen-units=1` Rust flag can reduce Vector binary size by 13%.

I think it is worth to add support for setting it to `scripts/build-archive.sh` script and enable it by default for release archives.

**Comment by tobz** [comment]
This is already happening, both for CI runs ([defined here](https://github.com/vectordotdev/vector/blob/master/scripts/environment/release-flags.sh), [called here](https://github.com/vectordotdev/vector/blob/05a318729cbcd3733957da7c3f6cf1d9bf70283b/scripts/environment/prepare.sh#L32)) and published artifacts ([configured here](https://github.com/vectordotdev/vector/blob/master/.github/workflows/publish.yml#L21)).
