### ISSUE TITLE
Missing First Trade in Backtesting Results

### ISSUE THREAD

**Issue by vishalsahicoin** [vectordotdev/vector#18023]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hello,

I've been using vectorbt for backtesting, and I've encountered an issue where the first trade is missing from my results.

Here are the long signal timestamps and the corresponding prices:

`Open time                    TS_Long_Signals   Price
2020-12-20 00:00:00+00:00    True             23792.27
2021-05-17 00:00:00+00:00    False            46506.00
2021-08-06 00:00:00+00:00    True             40872.89
2021-10-01 00:00:00+00:00    False            43825.73
2021-10-05 00:00:00+00:00    True             49222.65
2021-12-06 00:00:00+00:00    False            49435.25
2022-03-28 00:00:00+00:00    True             46796.36
2022-04-16 00:00:00+00:00    False            40563.62
2023-01-15 00:00:00+00:00    True             20967.61
2023-05-28 00:00:00+00:00    False            26864.35
2023-06-23 00:00:00+00:00    True             29884.01
`

However, when I extract the trades from the backtest results, it seems like the first trade (starting on 2020-12-20) is missing:

`Exit Trade Id    Column    Size    Entry Timestamp           Avg Entry Price    Entry Fees    Exit Timestamp           Avg Exit Price    Exit Fees    PnL         Return      Direction    Status    Position Id
0                0         0       2021-08-06 00:00:00+00:00 40872.89            0.099900      2021-10-01 00:00:00+00:00 43825.73           0.107117     7.010212     0.070172     Long        Closed     0
1                1         0       2021-10-05 00:00:00+00:00 49222.65            0.106903      2021-12-06 00:00:00+00:00 49435.25           0.107365     0.247463     0.002315     Long        Closed     1
2                2         0       2022-03-28 00:00:00+00:00 46796.36            0.107151      2022-04-16 00:00:00+00:00 40563.62           0.092879     -14.471254   -0.135055    Long        Closed     2
3                3         0       2023-01-15 00:00:00+00:00 20967.61            0.092694      2023-05-28 00:00:00+00:00 26864.35           0.118762     25.856885    0.278950     Long        Closed     3
4                4         0       2023-06-23 00:00:00+00:00 29884.01            0.118525      2023-06-23 00:00:00+00:00 29884.01           0.000000     -0.118525    -0.001000    Long        Open       4
`

Could you `please` help me understand why the first trade is missing from the backtesting results? Is there a specific parameter I need to adjust, or is this a potential bug in the software?

Thank you for your assistance.

### Version

0.24.3

**Comment by spencergilbert** [comment]
👋 I think you may have meant to open this issue [here](https://github.com/polakowo/vectorbt)
