### ISSUE TITLE
Unix socket source - Error handle

### ISSUE THREAD

**Issue by pmzara** [vectordotdev/vector#18036]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I'm using Socket source to collect logs from all my apps.
Everything was running without any problem until a couple of days the socket connection stopped working with the following message error:
2023-07-12T22:04:08.083015Z ERROR source{component_kind="source" component_id=socket component_type=socket component_name=socket}: vector::topology: An error occurred that Vector couldn't handle: receiver disconnected.
Before this error message, I saw this one:
thread 'vector-worker' panicked at 'internal error: entered unreachable code: join error or bad poll', src/topology/builder.rs:797:30
The only way to return to work was to restart the servers.

### Configuration

```text
Host running Linux: 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:21:56 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
Vector version: 0.28.1-x86_64
Vector running inside docker container: 
Client:
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.1
 Git commit:        20.10.21-0ubuntu1~22.04.3
 Built:             Thu Apr 27 05:58:37 2023
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.1
  Git commit:       20.10.21-0ubuntu1~22.04.3
  Built:            Thu Apr 27 05:37:25 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.12-0ubuntu1~22.04.1
  GitCommit:
 runc:
  Version:          1.1.4-0ubuntu1~22.04.3
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### Version

0.28.1-x86_64

**Comment by jszwedko** [comment]
Thanks for opening this report @pmzara . Do confirm, did Vector exit when that happened? Or did you have to intervene to kill the process?

**Comment by pmzara** [comment]
@jszwedko Vector exited when that happened.

**Comment by neuronull** [comment]
Hi @pmzara, thanks for providing the versioning. Would you also be able to provide a minimum vector config that produced this error?

**Comment by pmzara** [comment]
@neuronull How we are using Vector:
- EC2 instance running golang API service;
- Logs are sent to this API service;
- API service sends logs to Vector using socket (HERE is the problem)
- Vector is running inside a container with MAC (AppArmor profile). This is the command that runs Vector:
```
	cmd := exec.Command("/usr/local/vector/bin/vector", "-q", "--config-dir", "/vector-config")
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	err = cmd.Start()
	if err != nil {
		log.Fatal(err)
	}
```
- Counter metrics are sent to Telegraf using socket (no problem here)
- Distribution metrics are sent to HTTP server and forward to Datadog using HTTP Proxy (security requirements)

**Comment by jszwedko** [comment]
> @neuronull @jszwedko This problem only happens in AWS Graviton architecture.

That's pretty strange 🤔 

Just out of curiosity, have you tried the newest version of Vector (0.31.0)? I'm not aware of any recent changes that we made that would affect this, but we have upgrade dependencies, which could have an impact here.

Are you easily able to reproduce this locally? If so, could you add reproduction instructions? Or do you just see it happen in deployed environments?

**Comment by pmzara** [comment]
@jszwedko Yes. I tried version 0.31.0 and the problem persisted. Is there any debug option that I can enable to collect more information about the error?

**Comment by jszwedko** [comment]
> @jszwedko Yes. I tried version 0.31.0 and the problem persisted. Is there any debug option that I can enable to collect more information about the error?

You could try enabling debug logs (`VECTOR_LOG=debug`).

I'm still curious about

> Are you easily able to reproduce this locally? If so, could you add reproduction instructions? Or do you just see it happen in deployed environments?

too. Are you able to reproduce this behavior in a consistent way?

**Comment by pmzara** [comment]
@jszwedko I'm able to reproduce this behavior. I will enable debug logs and check the messages. I will start my tests and update this issue when I have more information. Thanks.

**Comment by pmzara** [comment]
@jszwedko I enabled the debug option to Vector (-v flag). I can see a lot of the INFO and DEBUG messages but I don't see any error message. As you can see in the attached picture everything was working without any problem.
![Screenshot 2023-08-02 at 15 39 11](https://github.com/vectordotdev/vector/assets/6985754/bd09a880-85f5-4a88-a229-3473a4c70c6b)
This is the only message before the error:
2023-08-02T18:28:19.115120Z INFO source{component_kind="source" component_id=socket component_type=socket component_name=socket}:connection: vector::sources::util::unix_stream: Finished sending.
Error message:
![Screenshot 2023-08-02 at 15 43 04](https://github.com/vectordotdev/vector/assets/6985754/e251be5d-22e3-4014-9ea2-3a4e8375fef0)

**Comment by jszwedko** [comment]
Gotcha. Are you able to reproduce it easily locally? If we are able to reproduce it on our side we can probably track it down. ` Finished sending` would indicate the source is shutting down. Is there anything that might be issuing a SIGTERM to Vector to cause it to shutdown?

**Comment by pmzara** [comment]
I think that the problem is related to memory capacity. These are all the error messages before the first error message (get dst failed)
![Screenshot 2023-08-02 at 17 01 26](https://github.com/vectordotdev/vector/assets/6985754/3fed707c-9812-4e0c-9bd8-3fce07ed8507)

**Comment by jszwedko** [comment]
@pmzara do you mean that Vector was OOM-killed?

**Comment by pmzara** [comment]
Because Vector is running inside a container maybe the container has a memory restriction.

**Comment by jszwedko** [comment]
Closing as stale since it seems like this is an OOM kill to me, but feel free to leave a comment if you pick this investigation back up.
