### ISSUE TITLE
Consider support /quitquitquit api on vector

### ISSUE THREAD

**Issue by ZhiHanZ** [vectordotdev/vector#18034]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

I have been using Vector in a Kubernetes environment, specifically employing it as a sidecar container to capture logs from Kubernetes jobs. In this context, I've noticed that the process to terminate the Vector service can become quite complex and potentially insecure when using Signals. Implementing a straightforward API endpoint to terminate the service could significantly streamline this process and improve security.

One solution I would propose is the introduction of a /quitquitquit API, similar to what several other projects have already implemented. This would provide a simple, secure way to terminate the Vector service, reducing the risk of introducing bugs or security breaches.

Examples of projects that have adopted this approach include:

Dapr: https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-job/
Envoy: https://www.envoyproxy.io/docs/envoy/latest/operations/admin#post--quitquitquit

**Comment by jszwedko** [comment]
Makes sense. Thanks for the request @ZhiHanZ !

**Comment by jszwedko** [comment]
Hi @ZhiHanZ !

We discussed this a bit more and realized we don't completely understand the use-case. Could you describe your use-case a bit more? Why do you need an API to shutdown Vector rather than having K8s send signals?

**Comment by ZhiHanZ** [comment]
Sure @jszwedko ,

For use case part,  the obvious use case is that by default, vector is a long running log collection container using [distroless image](https://vector.dev/docs/setup/installation/platforms/kubernetes/#agent) which means that it does not contain package manager and shell, this practice is great for security consideration as it minimize the attack surface.

However when come to kubernetes job use case, the main process such as a spark job exit, it is hard to send signal to the distroless image as it contains no shell, user needs to use the debian vector distro and setup a lot of scripts to make the process work correctly, for example, the [CloudSQL case](https://cotton-ori.medium.com/how-to-terminate-a-side-car-container-in-kubernetes-job-2468f435ca99).

If vector could support a http api for shudown, above case could be resolved in a pretty clean way, people could just call the shutdown api on their preStop hook or send a shutdown request once the main process return, no need to choose debian distribution with complex scripts.

**Comment by jszwedko** [comment]
Ah, I see, thanks for providing more context @ZhiHanZ . I see this is a gap in Kubernetes lifecycle management: https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/753-sidecar-containers/README.md#problems-jobs-with-sidecar-containers

https://suraj.io/post/how-to-gracefully-kill-kubernetes-jobs-with-a-sidecar/ seems to describe an approach of sharing the process namespace to be able to send a signal from the main container to the sidecar. Would that work for you as a workaround that doesn't involve additional scripts in the sidecar?

**Comment by jszwedko** [comment]
Closing this since it seems like the work-around of sharing a process space is sufficient and Kubernetes is thinking about better solutions in this space. If you have a use-case not supported by this workaround, feel free to leave a comment!

**Comment by mkudukin** [comment]
Hi, @jszwedko. One use case is Windows version of Vector. Windows doesn't have signals, and looks like there is no way to gracefully stop Vector, except if you started it in terminal and could press Ctrl+C. What do you think?

**Comment by jszwedko** [comment]
Good point, Vector doesn't handle signals on Windows other than ctrl-c at the moment. It seems like there might be a crate we could leverage that has better Windows signal handling support though: https://docs.rs/signal-hook/latest/signal_hook/. I think I'd prefer to try that before adding an API endpoint since it is simpler and closer to the existing behavior.
