### ISSUE TITLE
Passing different values of source and destination GCP projects for metrics, in GCP cloud monitoring (gcp stackdriver metrics) config gives invalid argument error

### ISSUE THREAD

**Issue by rk3094** [vectordotdev/vector#18035]
### A note for the community 
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Environment:
Using the GCP Cloud Monitoring sync, with vector running in a Pod in GKE. Using GCP workload identity (GCP service account linked to GKE service account) to authenticate to GCP. 

Problem: 
We are trying to get merics from a source GCP project say, Project_A and then publishing these metrics to another  GCP project say Project_B. In the VRL configuration below, we defined the gcp sink type as "gcp_stackdriver_metrics" which requires us to fill **project_id** to which to publish metrics: https://vector.dev/docs/reference/configuration/sinks/gcp_stackdriver_metrics/#project_id . Here we are passing the destination project i.e. Project_B

Then we are using the gcp sink resource of "[generic_task](https://cloud.google.com/monitoring/api/resources#tag_generic_task)" which also required to define a **project_id** which is the GCP project associated with this resource. Here we are passing this source GCP project ID i.e. Project_A

Now, the problem is when the source and destination project ID values are same, then only vector configuration works fine, otherwise vector complains with below error:

> 2023-07-17T09:44:15.153648Z ERROR sink{component_kind="sink" component_id=gcp component_type=gcp_stackdriver_metrics component_name=gcp}:request{request_id=27}: vector::sinks::util::retries: Internal log [Not retriable; dropping the request.] has been suppressed 26 times.2023-07-17T09:44:15.153673Z ERROR sink{component_kind="sink" component_id=gcp component_type=gcp_stackdriver_metrics component_name=gcp}:request{request_id=27}: vector::sinks::util::retries: Not retriable; dropping the request. reason="response status: 400 Bad Request" internal_log_rate_limit=true2023-07-17T09:44:15.153698Z ERROR sink{component_kind="sink" component_id=gcp component_type=gcp_stackdriver_metrics component_name=gcp}:request{request_id=27}: vector::sinks::util::sink: Response failed. response=Response { status: 400, version: HTTP/1.1, headers: {"vary": "Origin", "vary": "X-Origin", "vary": "Referer", "content-type": "application/json; charset=UTF-8", "transfer-encoding": "chunked", "date": "Mon, 17 Jul 2023 09:44:15 GMT", "server": "ESF", "cache-control": "private", "x-xss-protection": "0", "x-frame-options": "SAMEORIGIN", "x-content-type-options": "nosniff"}, body: b"{\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"Field timeSeries[0].resource.labels.project_id had an invalid value of \\\"**<Project_A>**\\\": if present, must be the project number or ID in the request name.\",\n    \"status\": \"INVALID_ARGUMENT\"\n  }\n}\n" } 
 

Also, If we skip defining _project_id_ field in under [sinks.gcp.resource], then _poject_id_ value from [sinks.gcp] is inherited.

In our use case, since both the project_id values are different, this is not working. As a workaround, we tried to introduce a new custom value in metrics called source_project and we are passing the source GCP project value in there.``

### Configuration

```text
Vector config for sink: 

[sinks.gcp]
    type = "gcp_stackdriver_metrics"
    inputs = [ "my_metric1" ]
    project_id = "${DESTINATION_GCP_PROJECT_ID:?destnation_gcp_project_id where to publish metrics must be supplied}"
    
    [sinks.gcp.resource]
    type = "generic_task"
    project_id = "${SOURCE_GCP_PROJECT_ID:?source_gcp_project_id must be supplied where metrics are originated}"
    location = "${GCP_LOCATION:?gcp_location must be supplied}"
    namespace = "${SERVICE_NAMESPACE:?service_namespace must be supplied}"
    job = "${JOB_NAME}:?job_name must be supplied"
    task_id = "${TASK_ID:?task_id must be supplied}"
```

### Version

vector 0.31.0 (x86_64-unknown-linux-musl 0f13b22 2023-07-06 13:52:34.591204470)

### Debug Output

```text
2023-07-17T09:44:15.153648Z ERROR sink{component_kind="sink" component_id=gcp component_type=gcp_stackdriver_metrics component_name=gcp}:request{request_id=27}: vector::sinks::util::retries: Internal log [Not retriable; dropping the request.] has been suppressed 26 times.2023-07-17T09:44:15.153673Z ERROR sink{component_kind="sink" component_id=gcp component_type=gcp_stackdriver_metrics component_name=gcp}:request{request_id=27}: vector::sinks::util::retries: Not retriable; dropping the request. reason="response status: 400 Bad Request" internal_log_rate_limit=true2023-07-17T09:44:15.153698Z ERROR sink{component_kind="sink" component_id=gcp component_type=gcp_stackdriver_metrics component_name=gcp}:request{request_id=27}: vector::sinks::util::sink: Response failed. response=Response { status: 400, version: HTTP/1.1, headers: {"vary": "Origin", "vary": "X-Origin", "vary": "Referer", "content-type": "application/json; charset=UTF-8", "transfer-encoding": "chunked", "date": "Mon, 17 Jul 2023 09:44:15 GMT", "server": "ESF", "cache-control": "private", "x-xss-protection": "0", "x-frame-options": "SAMEORIGIN", "x-content-type-options": "nosniff"}, body: b"{\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"Field timeSeries[0].resource.labels.project_id had an invalid value of \\\"<Project_A>\\\": if present, must be the project number or ID in the request name.\",\n    \"status\": \"INVALID_ARGUMENT\"\n  }\n}\n" }
```

**Comment by neuronull** [comment]
Hello,

Hmm, this error:

```
"code": 400,\n  "message": "Field timeSeries[0].resource.labels.project_id had an invalid value of \"<Project_A>\": if present, must be the project number or ID in the request name.",\n "status": "INVALID_ARGUMENT"
```

Appears to be coming from the downstream 🤔  Naively, it would seem that is a requirement enforced by the GCP API.

**Comment by rk3094** [comment]
@neuronull Could you please confirm that? If it is GCP issue, what's the next step, will you be opening a ticket there?

**Comment by jszwedko** [comment]
Closing as stale since this seems to be a misconfiguration issue. You are passing `<Project_A>` as the project ID but this is not a valid project ID. Please leave a comment if I am misunderstanding!
