### ISSUE TITLE
New `azure_monitor_logs` sink

### ISSUE THREAD

**Issue by nazar554** [vectordotdev/vector#1808]
I'd really like to have support for Azure Log Analytics.
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/data-collector-api

**Comment by binarylogic** [comment]
Thanks @nazar554, Azure Monitor looks powerful. We're hoping to wrap up support for the core GCP services and will likely start on Azure next. We'd love help from anyone willing to build this as well.

**Comment by zoni** [comment]
I'd be very interested in support for this in vector as well. I'm currently picking up Rust, but don't feel proficient enough yet to offer implementation work on this.

That being said, if work on this was done, I'd be perfectly happy to test out any PRs and report issues on that and/or help out with documentation work if that is helpful.

**Comment by Hoverbear** [comment]
@zoni Thanks! If you feel up for a project before we get to this, let me know, we can always offer some mentoring. :)

**Comment by nazar554** [comment]
I have a working setup based on stdout & my forwarder, but I am not sure how to port the request batching logic to vector. I am supposed to use `HttpSink`?

Anyway, here is the [repo](https://gitlab.com/nazarmx/log_analytics/-/blob/master/src/main.rs).

**Comment by Hoverbear** [comment]
@LucioFranco  think this is a good job for good old HttpSink?

**Comment by LucioFranco** [comment]
So I'll preface this with I don't know much about `azure_monitor_logs` but if its like a lot of other logging services. It looks like you need first someway to encode events into some sort of message encoding then a way to build requests. This is basically what `HttpSink` exposes without the user needing to deal with any async code. So I think from what I can tell the answer is yes.

**Comment by lukasmrtvy** [comment]
Any progress on this ?

**Comment by bigredmachine** [comment]
I'm interested in this Azure Monitor Logs sink, as well as the Azure Event Hubs sink (https://github.com/timberio/vector/issues/2434). And think there is some overlap in functionality from my intended use case, so sharing my thoughts.

I'm looking to scrape an applications prometheus metrics endpoint, convert it into Application Insights JSON metrics format (something like this http://apmtips.com/blog/2017/10/27/send-metric-to-application-insights/), and then send them in compressed batches to an Azure Event hub (preferred, or to Log Analytics direct as per this Sink).
After it gets into Azure Event hub, then ends up in Log Analytics via another service, along with any other desired destinations.

Either way the metrics need to be converted to the same Application Insights JSON metrics format. So suggesting if that part could be re-usable/separate, it would help with my desired use case.

Let me know if I can help, e.g. QA this out.
Or help out with the metrics format conversion? Where would that live? I've not used vector or rust before. But looks promising that can achieve what I need if this conversion and sinks can be added.

**Comment by nazar554** [comment]
Should this be closed, or #4464 needs to be done first?

**Comment by jamtur01** [comment]
This can be closed! Thanks.
