### ISSUE TITLE
format_timestamp timezone timestamp breaking the basic functionality of s3 sink

### ISSUE THREAD

**Issue by ghost** [vectordotdev/vector#18081]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I am using s3 sink for uploading the data for every 5 mins with buffer configuration.  Since vector **TIMEZONE** configuration is default to UTC.  

`Issue 1:` using format_timezone  converted the UTC to SGT Timezone and this resulted every min to push the data instead of every 5 mins.

`Issue 2:` under key_prefix date=%Y%m%d still uses UTC and resulting in the data upload to wrong folder

<img width="982" alt="Screenshot 2023-07-26 at 12 19 33 AM" src="https://github.com/vectordotdev/vector/assets/83200227/9995a75b-277d-46e9-9582-aee665c091f5">

### Configuration

```text
data_dir = "/var/lib/vector"
timezone = "Asia/Singapore"


[api]
  enabled = true

[sources.forward_proxy]
    type = "file"
    include = ["/var/log/squid/access.log"]
    #ignore_older = 3600 # Ignore events older than 1 hour
    read_from = "end"

[transforms.remap_forward_proxy]
    type = "remap"
    inputs = [ "forward_proxy" ]
    source = """
      .message = parse_json!(.message)
      .custom_timestamp = format_timestamp!(now(), format: "%H_%M", timezone: "Asia/Singapore")
    """

[sinks.s3_forward_proxy]
    type = "aws_s3"
    inputs = ["remap_forward_proxy"]
    acl = "bucket-owner-full-control"
    bucket = "xxxxxxx-xxxxxxxxx-xxxxxxx-xxxxxxxx"
    content_encoding = "none"
    content_type = "application/x-gzip"
    filename_time_format = ""
    filename_append_uuid  = false
    filename_extension = "gz"
    key_prefix = "production/forward-proxy_squid.access.log-vector-1/date=%Y%m%d/{{ .custom_timestamp }}_forward-proxy_ap-southeast-1_${HOSTNAME}"
    compression = "gzip"
    region = "ap-southeast-1"


    [sinks.s3_forward_proxy.buffer]
        type = "disk"
        when_full = "block"
        max_size =  5368709760

    [sinks.s3_forward_proxy.batch]
        timeout_secs = 300
        max_bytes = 250000000 #250 mb

   [sinks.s3_forward_proxy.framing]
        method = "newline_delimited"

    [sinks.s3_forward_proxy.encoding]
        codec = "json"
        except_fields = ["custom_timestamp"]
```

### Version

vector 0.31.0 (x86_64-unknown-linux-gnu 0f13b22 2023-07-06 13:52:34.591204470)

### References

https://github.com/vectordotdev/vrl/pull/247
https://github.com/vectordotdev/vector/issues/14160
https://github.com/vectordotdev/vector/pull/17004

**Comment by madan-wego** [comment]
Buffer getting flushed properly only If set as below config in s3 sink 

`filename_time_format = "%H_%M_forward-proxy_ap-southeast-1_${HOSTNAME}"`

But this is defaulting to UTC because of the below code

https://github.com/vectordotdev/vector/blob/421b421bb988335316417c80129014ff80179246/src/sinks/aws_s3/sink.rs#L79C55-L79C75

**Comment by neuronull** [comment]
Hello, regarding

> Issue 2: under key_prefix date=%Y%m%d still uses UTC and resulting in the data upload to wrong folder

Could that not be solved by using the time zone specifier in the [strftime-specifier](https://vector.dev/docs/reference/configuration/template-syntax/#strftime-specifiers) (https://docs.rs/chrono/0.4.19/chrono/format/strftime/index.html#specifiers) ?

**Comment by madan-wego** [comment]
[strftime-specifier](https://vector.dev/docs/reference/configuration/template-syntax/#strftime-specifiers) This will not solve the issue, since it uses the timestamp (which is also in UTC) schema.

**Comment by neuronull** [comment]
> Buffer getting flushed properly only If set as below config in s3 sink

> filename_time_format = "%H_%M_forward-proxy_ap-southeast-1_${HOSTNAME}"

Just to clarify- so with that config setting added ,issue # 1 goes away (as a workaround), but you are still faced with issue # 2 , correct?

**Comment by madan-wego** [comment]
> 

Buffer is working only if I set `filename_time_format`.  By setting this Timestamp going into UTC. I need the timestamp as SGT. 

When I check the code. filename_time_format defaults to UTC. can you make option to use the any Timezone ? If Timezone was not defined, then it can use UTC.

**Comment by neuronull** [comment]
I'll admit, I'm a bit puzzled trying to sort out how the `filename_time_format` , or even just the `format_timestamp!()` , is impacting the batch flushing timeout- That is operating on it's own internal timer, not checking timestamps on the events 🤔

**Comment by madan-wego** [comment]
@neuronull Did you find anything related to this issue ?

**Comment by ahsandar** [comment]
can see the  buffer doesn't respect flushing time and flushes multiple times 

```
[transforms.remap_timestamped_dns_stream]
  type = "remap"
  inputs = [ "condition.dns-stream" ]
  source = '''
    .storage_timestamp = format_timestamp!(now(), "%H_%M_%s", "Etc/GMT")
    .storage_date = format_timestamp!(now(), "%Y%d%m", "Etc/GMT")
 '''

```

```
[sinks.r2_dns_stream]
  type = "aws_s3"
  inputs = [ "remap_timestamped_dns_stream" ]
  bucket = "kakashi-dns-stream"
  endpoint = "${R2_ENDPOINT}"
  region = "us-east-1"
  acl = "private"
  filename_append_uuid = true
  filename_extension = "log.gz"
  # filename_time_format = "%H_%M_%s"
  key_prefix = "date={{ .storage_date }}/{{ .storage_timestamp }}_"
  compression = "gzip"
[sinks.r2_dns_stream.auth]
  access_key_id = "${R2_ACCESS_KEY}"
  secret_access_key = "${R2_SECRET_KEY}"
[sinks.r2_dns_stream.buffer]
  type = "disk"
  when_full = "block"
  max_size = 268435488
[sinks.r2_dns_stream.encoding]
  codec = "json"
  except_fields = ["storage_timestamp", "storage_date"]
[sinks.r2_dns_stream.framing]
  method = "newline_delimited"
```
![image](https://github.com/vectordotdev/vector/assets/2472371/dc087531-c098-4d56-aa31-e9ce9b046007)

**Comment by ahsandar** [comment]
If i remove the %s from the formatted timestamp it pushes data every minute. So seems the key_prefix is some how influencing the flushing behaviour 
![image](https://github.com/vectordotdev/vector/assets/2472371/dd7a958a-c10d-4f1f-859d-7877c4d93500)

**Comment by ahsandar** [comment]
even addin batch.timeout_secs makes no impact
```
[sinks.r2_dns_stream.batch]
  timeout_secs = 300  
```
![image](https://github.com/vectordotdev/vector/assets/2472371/dc817777-4e80-4071-93ab-3ddbb69b2ab3)

**Comment by neuronull** [comment]
Thanks for those extra details. Let me take another pass at this and see if I can sort out how the key prefix might influence flushing.

**Comment by neuronull** [comment]
OK on a closer look, it seems the `key_prefix` becomes an element of the batch setting's `Partitioner`. This particular sink uses a batcher that also has a partitioner. I'm still reading up on this area of the code but from what I can tell, because the key prefix being used here has a timestamp in it, if you add the seconds to the timestamp, then only events that came in with that same second will be included in that batch. Similarly if you remove the seconds from the timestamp formatter, you get it in minutes.

**Comment by neuronull** [comment]
Here are a couple suggestions that should get past the issues you are facing:

In the transform, note we leave off seconds and minutes, in order for the partitioner to not take priority on that.

```
      .custom_timestamp = format_timestamp!(now(), format: "%Y%m%d/%H", timezone: "Asia/Singapore")
 ```
 
 In the sink:
 ```
     filename_time_format = ""
    key_prefix = "production/forward-proxy_squid.access.log-vector-1/date={{ .custom_timestamp }}_forward-proxy_ap-southeast-1_${HOSTNAME}"
```

One thing to be aware of though- if you set `filename_appen_uuid` to false, that might result in batch filename conflicts.

You could try moving the `"_%M"` format for minutes, to the `filename_time_format`.

**Comment by madan-wego** [comment]
Tried this solution @neuronull if I move `"_%M"` format to  `filename_time_format` it is defaulting to UTC. 

Example: 22:19 IST will result in `filename_time_format` to set Min as 22_49 instead of 22_19 . 

[transforms.step1]
  type = "remap"
  inputs = ["input_with_log_namespace"]
  source = '''
    .custom_timestamp = format_timestamp!(now(), format: "%Y%m%d/%H", timezone: "Asia/Kolkata")
  '''
  
  [sinks.s3_forward_proxy]
  type = "aws_s3"
  inputs = ["step1"]
  acl = "bucket-owner-full-control"
  bucket = "XXXXXX-XXXXXXXX-XXXXXXXX"
  content_encoding = "none"
  content_type = "application/x-gzip"
  filename_time_format = "%M_forward-proxy_ap-southeast-1_${HOSTNAME}"
  filename_append_uuid  = false
  filename_extension = "gz"
  # Vector 0.24.1 doest not support local timezone for file creation.
  key_prefix = "production/forward-proxy_squid.access.log-vector-1/{{ .custom_timestamp }}_"
  compression = "gzip"
  region = "ap-southeast-1"
  
  
![Screenshot 2023-08-03 at 11 41 23 PM](https://github.com/vectordotdev/vector/assets/83200227/0ae00303-550c-4c2e-bc8b-a99c9ddeab5c)

**Comment by madan-wego** [comment]
@neuronull Only easy solution which I can think off is don't hardcode the UTC inside in the `filename_time_format` function of s3 sink. So we can pass the timestamp as we wanted. 

I can see a PR which is best solution for the current issue. please take a look. that might solve. 

https://github.com/vectordotdev/vector/pull/17004/files

**Comment by neuronull** [comment]
> Tried this solution @neuronull if I move "_%M" format to filename_time_format it is defaulting to UTC.
> 22:19 IST will result in filename_time_format to set Min as 22_49 instead of 22_19 .

Ah yes, sorry for that oversight. That would only work in timezones aligned on the hour.

> We need to upload the files every 5 mins or 15 mins

I believe if you use 

```
 .custom_timestamp = format_timestamp!(now(), format: "%Y%m%d/%H", timezone: "Asia/Singapore")

filename_time_format = "%s" // or don't set this at all because that is the default
key_prefix = "production/forward-proxy_squid.access.log-vector-1/date={{ .custom_timestamp }}_forward-proxy_ap-southeast-1_${HOSTNAME}"
```

, then your batch timeout setting will be respected (so you can configure 5, 15 mins etc) , and the file names will be unique due to the `%s` appending the unix epoch in seconds granularity (as long as you don't have more than one batch per second).

**Comment by ahsandar** [comment]
> > Tried this solution @neuronull if I move "_%M" format to filename_time_format it is defaulting to UTC.
> > 22:19 IST will result in filename_time_format to set Min as 22_49 instead of 22_19 .
> 
> Ah yes, sorry for that oversight. That would only work in timezones aligned on the hour.
> 
> > We need to upload the files every 5 mins or 15 mins
> 
> I believe if you use
> 
> ```
>  .custom_timestamp = format_timestamp!(now(), format: "%Y%m%d/%H", timezone: "Asia/Singapore")
> 
> filename_time_format = "%s" // or don't set this at all because that is the default
> key_prefix = "production/forward-proxy_squid.access.log-vector-1/date={{ .custom_timestamp }}_forward-proxy_ap-southeast-1_${HOSTNAME}"
> ```
> 
> , then your batch timeout setting will be respected (so you can configure 5, 15 mins etc) , and the file names will be unique due to the `%s` appending the unix epoch in seconds granularity (as long as you don't have more than one batch per second).

it doesn't solves the problem. It sticks to flushing every minute
```
[sinks.r2_dns_stream]
  type = "aws_s3"
  inputs = [ "remap_timestamped_dns_stream" ]
  bucket = "kakashi-dns-stream"
  endpoint = "${R2_ENDPOINT}"
  region = "us-east-1"
  acl = "private"
  filename_append_uuid = true
  filename_extension = "log.gz"
  filename_time_format = "_%s"
  # key_prefix = "date=%Y%m%d/"
  key_prefix = "date={{ .storage_date }}/{{ .storage_timestamp }}_"
  compression = "gzip"
[sinks.r2_dns_stream.auth]
  access_key_id = "${R2_ACCESS_KEY}"
  secret_access_key = "${R2_SECRET_KEY}"
[sinks.r2_dns_stream.buffer]
  type = "disk"
  when_full = "block"
  max_size = 268435488
[sinks.r2_dns_stream.batch]
  timeout_secs = 300  
[sinks.r2_dns_stream.encoding]
  codec = "json"
  except_fields = ["storage_timestamp", "storage_date"]
[sinks.r2_dns_stream.framing]
  method = "newline_delimited"

```
![image](https://github.com/vectordotdev/vector/assets/2472371/abc7fad5-13c4-49c5-afd3-5a25c22ff011)

**Comment by ahsandar** [comment]
```
[transforms.remap_timestamped_dns_stream]
  type = "remap"
  inputs = [ "condition.dns-stream" ]
  source = '''
    .storage_timestamp = format_timestamp!(now(), "%H_%M", "Etc/GMT")
    .storage_date = format_timestamp!(now(), "%Y%m%d", "Etc/GMT")
 '''
```

`This flushes every 5 min as expected but in UTC`
```
  filename_time_format = "%H_%M_%s"
  key_prefix = "date=%Y%m%d/"
``` 

`This flushes every minute based on calculated timestamp value`
```
 filename_time_format = "_%s"
 key_prefix = "date={{ .storage_date }}/{{ .storage_timestamp }}_"
```

In the screenshot the files flushed at 5 mins are based on the config where `storage_timestamp` is not used. For the one in the below half you can see the values are flushed every minute when using `storage_timestamp`. 

Another issue with not putting `%M` is I can't have folder created at 5 minute interval if I need for e.g

```
date=20230804/01/05/file.log.gz
date=20230804/01/10/file.log.gz
date=20230804/01/15/file.log.gz
date=20230804/01/20/file.log.gz
....
.....
......

````

All of this would probably work with UTC when not using formatted timestamp but causes problem when doing so. In case we use `%M` in `file_time_format` it will not cover all timezone as it can be 55 in UTC but 25 somewhere else.

**Comment by jszwedko** [comment]
Thanks @ahsandar .

I definitely agree this would be simpler if there was better timezone support in Vector. I'm just trying to help you get a workaround for now 🙂 

As you note, `filename_time_format` is always in UTC so you'll not want to put any timestamp specifiers in there (except perhaps `%s` which would be the unix timestamp). I'd suggest something like:

```
[transforms.remap_timestamped_dns_stream]
  type = "remap"
  inputs = [ "condition.dns-stream" ]
  source = '''
    .storage_timestamp = format_timestamp!(now(), "%Y%m%d"/%H", "Asia/Singapore")
 '''
```

and

```
  filename_time_format = "%s"
  key_prefix = "date={{ .storage_timestamp }}"
```

This will result in objects partitioned by the hour. You will not end up with the minute anywhere in the filename. To be able to do that I think the `aws_s3` sink would need to be timezone aware. One simple way to change this in Vector would be to have:

https://github.com/vectordotdev/vector/blob/b2d23a838e7b5409273d82afa647b960b24499d3/src/sinks/aws_s3/sink.rs#L79

use the timezone configured in Vector (via https://vector.dev/docs/reference/configuration/global-options/#timezone; falling back to the system timezone).

**Comment by ahsandar** [comment]
Thanks @jszwedko but having minute is a must have requirement for now to migrate fully out of fluentd and move to vector as of now. 

I believe fluentd has an elegant way of handling this https://docs.fluentd.org/configuration/format-section. 

The sinks should have a timezone option which can be default  set to global timezone option but can take any TZ value instead of relying solely on the global option as one could be uploading to different regions and would like to push data in that TZ. .That would make the config something like 

```
[sinks.r2_dns_stream]
  type = "aws_s3"
  timezone = "Asia/Singapore" # timezone field default global timezone option
  inputs = [ "remap_timestamped_dns_stream" ]
  bucket = "kakashi-dns-stream"
  endpoint = "${R2_ENDPOINT}"
  region = "us-east-1"
  acl = "private"
  filename_append_uuid = true
  filename_extension = "log.gz"
  filename_time_format = "%H_%M_%s"
  key_prefix = "date=%Y%m%d/"
  compression = "gzip"
[sinks.r2_dns_stream.auth]
  access_key_id = "${R2_ACCESS_KEY}"
  secret_access_key = "${R2_SECRET_KEY}"
[sinks.r2_dns_stream.buffer]
  type = "disk"
  when_full = "block"
  max_size = 268435488
[sinks.r2_dns_stream.batch]
  timeout_secs = 300  
[sinks.r2_dns_stream.encoding]
  codec = "json"
  except_fields = ["storage_timestamp", "storage_date"]
[sinks.r2_dns_stream.framing]
  method = "newline_delimited"
```

**Comment by jszwedko** [comment]
Gotcha, yeah, I agree that sinks could take a `timezone` option that defaults to the globally configured `timezone`. There is precedent for that sort of override with other options like `proxy`.

I created two issues to track each of these changes independently:

- https://github.com/vectordotdev/vector/issues/18158
- https://github.com/vectordotdev/vector/issues/18159

I think those two issues cover this report so I'll close it, but let me know if you disagree. You can subscribe to the other issues for updates. We'd also be happy to see PRs addressing either of them 🙂
