### ISSUE TITLE
Configurable response code for HTTP Server source

### ISSUE THREAD

**Issue by kunalmohan** [vectordotdev/vector#18096]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Event generators, which send events to vector for processing and ingestion, depend on datadog HTTP API which returns 202 in case of success. It isn't possible to update event generator code immediately if they reside in environments outside our control (Eg: mobile and IoT devices). For switching over to vector, we need to support the older API as well, until the update is rolled out to all event generators. This requires vector to return 202 in case of successful event ingestion.

### Proposal

Make HTTP response code configurable in case of successful event ingestion.

### Version

vector 0.31.0

**Comment by jszwedko** [comment]
A rather extreme workaround here would be to write a custom HTTP server that accepts the data, forwards it to Vector, and forwards the response back, but sends a different status code. It seems like a sensible configuration option to be added though.
