### ISSUE TITLE
Hexadecimal Value to ASCII text

### ISSUE THREAD

**Issue by artemNN** [vectordotdev/vector#18100]
need a function to convert a Hexadecimal Value to ASCII text (String).

example:
input: "746869732069732074657874"
output: "this is text"

**Comment by neuronull** [comment]
Hello, would you be able to provide more details about the use case you need to cover?

**Comment by artemNN** [comment]
in my case, I process the auditd log. Some fields are in HEX format. these fields are written by the linux kernel.

**Comment by artemNN** [comment]
it seems there is already a decode_base16 function
