### ISSUE TITLE
Healthchecks don't load external secrets

### ISSUE THREAD

**Issue by mmelvin0** [vectordotdev/vector#18121]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Using externally loaded secrets with health checks enabled, it seems the secrets don't get substituted at health check time. The sinks work if health checks are disabled but with them enabled Vector refuses to start even if `require_healthy = false`.

The error I'm getting from ClickHouse is as follows, which should make it clear what's happening based on the provided example config below:

```
<Error> Access(user directories): from: 127.0.0.1, user: SECRET[vector.clickhouse_user]: Authentication failed: Code: 192. DB::Exception: There is no user `SECRET[vector.clickhouse_user]` in ldap. (UNKNOWN_USER)
```

In my case, the user name should be `vector`, not `SECRET[vector.clickhouse_user]`. This is what Vector thinks about the situation:

```
ERROR vector::topology::builder: msg="Healthcheck failed." error=Unexpected status: 403 Forbidden component_kind="sink" component_type="clickhouse" component_id=clickhouse_journal component_name=clickhouse_journal
x Health check for "clickhouse_journal" failed: Unexpected status: 403 Forbidden
```

Strangely, even with `require_healthy = false` this causes Vector to exit with status 78.

If I disable health checks, Vector starts up and authenticates with my ClickHouse setup just fine (e.g. my secrets script is returning the JSON Vector expects and everything is being substituted correctly at run time.)

I doubt this has anything to do with ClickHouse or its sink; I suspect this should be reproducible with any config that uses external secrets.

### Configuration

```text
[healthchecks]
enabled = true
require_healthy = false

[secret.vector]
command = ['/usr/local/bin/vector-secrets']
type = 'exec'

[sources.journal]
type = 'journald'

[sinks.clickhouse_journal]
type = 'clickhouse'
inputs = ['journal']
endpoint = 'http://127.0.0.1:8123'
date_time_best_effort = true
table = 'journal'
auth.strategy = 'basic'
auth.user = 'SECRET[vector.clickhouse_user]'
auth.password = 'SECRET[vector.clickhouse_password]'
```

### Version

vector 0.31.0 (x86_64-unknown-linux-gnu)

**Comment by neuronull** [comment]
Hello,

Hmm interesting. I attempted to repro this with just the `socket` source, using the secret value for the address to connect to. It didn't reproduce for me. If I enable the healthcheck, it appropriately detects if that port is available or not.

```toml
[healthchecks]
enabled = true

[api]
enabled = true

[secret.foo]
type = "exec"
command = ["./secret.sh"]

[sources.in]
type = "stdin"
decoding.codec = "bytes"

[sinks.socket]
type = "socket"
inputs = [ "in" ]
encoding.codec = "json"
mode = "tcp"
address = "SECRET[foo.fooSecret]"
```

```bash
#!/bin/bash

echo '{"fooSecret": {"value": "localhost:1234", "error": null}}'
```

So far I haven't found anything in the code that would indicate why there would be a difference here. The secrets should being interpreted and retrieved at config load, then when the sink runs, the interpreted values for the sink config are there for the healthcheck to run.

To clarify on this part

> If I disable health checks, Vector starts up and authenticates with my ClickHouse setup just fine (e.g. my secrets script is returning the JSON Vector expects and everything is being substituted correctly at run time.)

Does this mean you confirmed that data flows through and is received in ClickHouse?

**Comment by mmelvin0** [comment]
Pretty weird, and thank you for checking so quickly. Yes, my data is definitely flowing through and being stored in ClickHouse once healthchecks are disabled.

Are you 100% that it _actually_ established a connection to `localhost:1234` you don't have a new Unix socket that just appeared on your machine somewhere named `SECRET[foo.fooSecret]`?

I had just finished rigorously testing my config to make sure everything was perfect before turning on healthchecks as the last step, it failed in the above manner and then I turned them off and it was pumping all my metrics and logs through again, so I'm fairly confident.

I'll test more extensively soonish. Some notes-to-self-out-loud on that:
1. Try TCP socket sink with `nc` on the other side.
2. Try HTTP sink with basic auth.
3. Verify exactly when and how my secrets script is called when it doesn't work.
4. I'm using ClickHouse LDAP for user directory. Check to see what credentials are actually being sent to the LDAP server.
5. Try double quotes in my TOML instead of single (doubtful.)

**Comment by neuronull** [comment]
Yeah I tested with netcat and sent an event through.

It is weird yeah. I'll dig a little more into the code path for the secrets and this sink in particular to double check if there is any reason this might be happening.

**Comment by neuronull** [comment]
The only thing that jumps out to me as potentially relevant is that the `auth` is an enum. I would expect this not to matter with the interpolation of the secret. Nonetheless, I'm interested to hear your findings on your notes to self, as those data points could steer the investigation.

**Comment by jszwedko** [comment]
Closing as stale, but if you do come back to this, please leave a comment! Secrets loading actually happens before config parsing (via pattern matching) so it's unclear to me why only some parts of the config structure wouldn't support it.

**Comment by usa4ev** [comment]
Hi! I'm having the exact same issue. Clickhouse sink healthcheck fails with 403 error. After disabeling sinks healthcheck everything works just fine. I tried, just in case, to define [secret.clickhouse] in a separate file, but doesn't change a thing.
I use vector 0.33.1 (x86_64-unknown-linux-gnu 3cc27b9 2023-10-30 16:50:49.747931844)
