### ISSUE TITLE
Memcache Source and Sink Support

### ISSUE THREAD

**Issue by amojisys** [vectordotdev/vector#18181]
### A note for the community

We need to be able to read from and write to Memcache for Caching. Is the feature already available or whether Vector.dev development team are planning to develop this feature?

**Comment by jszwedko** [comment]
Hi @amojisys !

Can you share a bit more about your use case? Is it that you want to store log and metric events in memcache and have Vector read them from there?

**Comment by amojisys** [comment]
> Hi @amojisys !
> 
> Can you share a bit more about your use case? Is it that you want to store log and metric events in memcache and have Vector read them from there?

Hi @jszwedko

Yeah you know like Redis that we have both source and sink and we are able to write to and read from it. I am looking for the same features for Memcache.

Thanks

**Comment by jszwedko** [comment]
Closing this since it still isn't clear to me how this would work. If people do have thoughts on what this would look like, please share them here!
