### ISSUE TITLE
prometheus_remote_write: very high memory usage

### ISSUE THREAD

**Issue by pierlucg1047** [vectordotdev/vector#18199]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Sendings datadog agent metrics to a victoriametrics sink using prometheus_remote_write quickly fills up the entire memory (and thus gets OOMKilled).

Changing the sink to a `influxdb_metrics`, with the same metrics and the same victoriametrics instances, does not reproduce the issue (but for some reason the histogram timeseries are seperated instead of having the `le` label).

Adding a disk buffer does not help. The debug logs show nothing abnormal.

### Configuration

```text
api:
  address: "[::]:8686"
  enabled: true
  playground: true
data_dir: /vector-data-dir
sinks:
  victoriametrics:
    inputs:
      - internal_metrics
      - route_metrics.datadog
    endpoint: http://grafana-mgmt-vm-vminsert.grafana:8480/insert/0/prometheus
    type: prometheus_remote_write
    request:
      concurrency: adaptive
  blackhole:
    type: blackhole
    inputs:
      - route_metrics._unmatched
sources:
  datadog_agent:
    address: "[::]:80"
    multiple_outputs: true
    type: datadog_agent
  internal_metrics:
    scrape_interval_secs: 5
    type: internal_metrics
transforms:
  route_metrics:
    inputs:
    - datadog_agent.metrics
    type: route
    route:
      datadog: "true"
```

### Version

vector 0.31.0 (aarch64-unknown-linux-musl 0f13b22 2023-07-06 13:52:34.591204470)

**Comment by pront** [comment]
Hi @pierlucg1047, can you share some internal metrics entries? I want to understand the load a bit better. Also, is there anything special about your `endpoint`, is it a victoria metrics cluster?

**Comment by pierlucg1047** [comment]
Hey @pront, I can definitely share internal metrics. If there are some particular metrics you're interested in, let me know.

There is nothing special about the endpoint, yes it is a victoria metrics cluster :)

By using `vector_component_received_event_bytes_total_value` and `vector_component_received_events_total_value`, I see that the average event size is around 4KiB, which seems like a lot.

We ingest about 7k metrics/s, with peaks around 40k metrics/s. 

We currently have 3 vector instances, with 4 vCPUs and 8GiB memory limits each (each on a different node).
