### ISSUE TITLE
Support SVCB and HTTPS records in dnstap source

### ISSUE THREAD

**Issue by icb-** [vectordotdev/vector#18228]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Please add support for [SVCB and HTTPS](https://datatracker.ietf.org/doc/draft-ietf-dnsop-svcb-https/) records in the dnstap source. These newer records comprise a significant percentage of DNS queries. My logs are filled with messages about unsupported rdata types from these queries being processed, and they represent a hole in query visibility.

### Proposal

Add parsing of SVCB and HTTPS records from the dnstap source.

### Version

vector 0.31.0 (x86_64-unknown-linux-gnu 0f13b22 2023-07-06 13:52:34.591204470)

**Comment by jszwedko** [comment]
@j-bai is this something you'd be interested in adding to the `dnstap` source?

**Comment by mattb-nn** [comment]
I'd very much appreciate this being added, please!
