### ISSUE TITLE
`host_metrics` doesn't collect ext4 filesystems other than `/dev/sda1` even if others exist

### ISSUE THREAD

**Issue by genki** [vectordotdev/vector#18231]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I am using the vector for collecting `host_metrics` in a docker container that has mounted host's `/sys` and `/proc`.
However, it collected data from only `/dev/sda1` even if the host filesystem has several ext4 entries like this:
```
# ls /mnt/host/proc/fs/ext4
sda1  sdb   sdc
```

And the env variables as follows:
```
# env
HOSTNAME=m2
SHLVL=1
HOME=/root
SYSFS_ROOT=/mnt/host/sys
PROCFS_ROOT=/mnt/host/proc
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
````

I have read the document that says `SYSFS_ROOT` env var is suite for using with container, but it seemed not working as mentioned.

### Configuration

```text
[api]
enabled = true

[sources.host_metrics]
type = "host_metrics"
collectors = [
  "cpu", "disk", "load", "memory", "network", "cgroups", "filesystem", "host"
]

[transforms.remap_host]
type = "remap"
inputs = ["host_metrics"]
source = '''
.tags.host = get_env_var!("HOSTNAME")
'''

[sinks.prometheus]
type = "prometheus_exporter"
inputs = ["remap_host"]
address = "0.0.0.0:9598"
```

### Version

vector 0.31.0 (x86_64-unknown-linux-musl 0f13b22 2023-07-06 13:52:34.591204470)

### Debug Output

Here is an example result for the promql `host_filesystem_free_bytes{host="m2",filesystem="ext4"}`:

```
host_filesystem_free_bytes{collector="filesystem",device="/dev/sda1",filesystem="ext4",host="m2",instance="10.0.0.175:9598",job="vector",mountpoint="/etc/hostname"} | 65897684992
host_filesystem_free_bytes{collector="filesystem",device="/dev/sda1",filesystem="ext4",host="m2",instance="10.0.0.175:9598",job="vector",mountpoint="/etc/resolv.conf"} | 65897684992
host_filesystem_free_bytes{collector="filesystem",device="/dev/sda1",filesystem="ext4",host="m2",instance="10.0.0.175:9598",job="vector",mountpoint="/etc/hosts"} | 65897684992
```

**Comment by genki** [comment]
I have investigated behaviour of the helm, it try to see the mount record at `/proc/mounts` that is symlinked to 
 `/proc/self/mounts`, it is not of the host but of the container itself. 
To achieve to collect the data from host filesystem, we need to see the `/proc/1/mounts` file instead of `/proc/mounts` in a docker container.
How about to add a configuration option to the filesystem collector in order to to specify the exact path to the mounts file?

**Comment by Voldemat** [comment]
Issue is still present and the main problem is heim itself does not provide a way to configure path to mounts file, it is hardcoded right now to "$PROCFS_ROOT / mounts". The workaround is just mounting another drives subfolder somewhere in container, then it will be mentioned in /proc/mounts and heim will pick it up and pass to vector
