### ISSUE TITLE
Handle empty string value of pipeline name in ES sink as not configured

### ISSUE THREAD

**Issue by Hexta** [vectordotdev/vector#18246]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

I need to configure ingest pipeline name for ES sink by an environment variable.
At the same time I need to disable using pipelines in some cases.

### Attempted Solutions

```yaml
pipeline: ${ENV_VAR:-}
```

- `ENV_VAR` is not set. Config validation failed with `pipeline: invalid type: unit value, expected any valid TOML value`
- `ENV_VAR=""`. ES sink tries to use `""` as an ingest pipeline name which leads in failed requests.

### Proposal

Handle empty string `pipeline` value as not configured.

### Version

0.31.0

**Comment by hhromic** [comment]
@jszwedko for what is worth, this issue is very related to this feature request I opened some time ago: https://github.com/vectordotdev/vector/issues/12832

Specially to support the case you mentioned: `pipeline: ${ENV_VAR:-null}`

**Comment by Hexta** [comment]
@jszwedko Thx for the reply. I forgot to add that I tried all the options from the top  of my head )

* ${ENV_VAR:-null}. `invalid type: unit value, expected any valid TOML value`
* ${ENV_VAR:-~}. `invalid type: unit value, expected any valid TOML value`
