### ISSUE TITLE
install script incorrectly append PATH if it contains spaces

### ISSUE THREAD

**Issue by ezimore** [vectordotdev/vector#18291]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Vector installation removes the apostrophe ('mydir with spaces') and escape characters (mydir\ with\ spaces) from the PATH variable which makes existing configured commands and vector command not found.

### Version

vector 0.31.0 (x86_64-unknown-linux-gnu 0f13b22 2023-07-06 13:52:34.591204470)

### Example Data

Prerequisites: 
- vector not installed
- PATH variable contains spaces e.g. PATH=/home/myuser/mydir\ with\ spaces:'/home/myuser/2nddir with spaces'

After vector installation, the PATH variable looks like:
`PATH=/home/myuser/mydir with spaces:/home/myuser/2nddir with spaces:/home/myuser/.vector/bin`

PATH variable is corrupted. Vector command is not available, even more other commands on the directories added earlier into PATH are not available as well.

the correct behaviour would be keeping the original PATH string as it is and appending only the vector path at the end
`PATH=/home/myuser/mydir\ with\ spaces:'/home/myuser/2nddir with spaces':/home/myuser/.vector/bin`

**Comment by jszwedko** [comment]
Thanks for this report @ezimore . I opened https://github.com/vectordotdev/vector/pull/18294 to resolve it.
