### ISSUE TITLE
Test `kafka` source against AWS' MSK service

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#1833]
In our community chat we had a user report an error using Amazon's MSK service with the `kafka` source:

> Hi, I was giving Vector a whirl today.
> I was trying to read from from a Kafka source, after sending nginx logs with the Kafka sink... I get the following error, tried it in RUST_BACKTRACE=full mode but didn't add any additional context... I get this:
> > Feb 15 00:54:42.530 ERROR source{name=kafka type=kafka}: vector::sources::kafka: Kafka returned error error=KafkaError (Message consumption error: NotImplemented (Local: Not implemented))
>
> ```
> [sources.kafka]
> # REQUIRED
> type = "kafka" # must be: "kafka"
> bootstrap_servers = "broker1:9092,broker2:9092,broker3:9092"
> group_id = "consumer-group" # example
> topics = ["test-logs"] # example
> ```
>
> this is an MSK cluster running 2.2

Noting, the `kafka` source worked fine with the non-AWS kafka service as well as kafkacat.

It would be worth testing our `kafka` source against AWS MSK and it might be worth doing this with https://github.com/timberio/vector/issues/1516.

**Comment by a-rodin** [comment]
I tested `kafka` source and sink with AWS MSK 2.2.1 and it worked fine in plain text mode. I think we need more details about configuration of the MSK cluster they had problems with.

I agree that it is worth to implement #1516 and also probably #1853.

**Comment by binarylogic** [comment]
Hey @schofield, any chance you could provide your Vector config for your MSK tests? Thanks!

**Comment by a-rodin** [comment]
I think it is the same error as

**Comment by binarylogic** [comment]
@a-rodin I'm unassigning you from this since you have other more important work going on. You, or someone else, can test this at a later date.

**Comment by kitos9112** [comment]
Hi,

Felt slightly reluctant about opening a new GH Issue so I'll give it a go here.

Now that AWS MSK supports IAM integration for Client authentication against the broker nodes. Are there plans to amend the existing Kafka authentication implementation?

> All clients need to be configured with the Apache 2.0 licensed aws-msk-iam-auth library which infers and sends IAM credentials securely to MSK using SigV4 request signing. 

https://aws.amazon.com/about-aws/whats-new/2021/05/introducing-iam-access-control-amazon-msk/
https://github.com/aws/aws-msk-iam-auth

**Comment by smlgbl** [comment]
@binarylogic @jszwedko Any plans on integrating #1833? This would really increase the possible uses for vector...

**Comment by jszwedko** [comment]
Thanks @smlgbl . This should be folded into #1516. I'll close this one. This is still on our radar (as is adding support for AWS authentication for AWS's prometheus service), but nothing scheduled yet.

**Comment by shivmohith** [comment]
> I tested `kafka` source and sink with AWS MSK 2.2.1 manually and it worked fine in plain text mode. I think we need more details about configuration of the MSK cluster they had problems with.
> 
> I agree that it is worth to implement #1516 and also probably #1853.

Hi, can you share the Vector configurations that worked with MSK? I am trying to setup the same but unable to.
