### ISSUE TITLE
macOS system page is missing Homebrew method

### ISSUE THREAD

**Issue by hongbo-miao** [vectordotdev/vector#18352]
Just a small doc issue. ☺️

https://vector.dev/docs/setup/installation/operating-systems/macos/
![image](https://github.com/vectordotdev/vector/assets/3375461/84007236-b6fa-4e12-87e2-01ee13fc5f56)

macOS system is missing Homebrew method at https://vector.dev/docs/setup/installation/package-managers/homebrew/

**Comment by jszwedko** [comment]
Thanks for pointing this out @hongbo-miao ! I opened https://github.com/vectordotdev/vector/pull/18364 to resolve it.
