### ISSUE TITLE
Sources output data fields value dismatch

### ISSUE THREAD

**Issue by x2x4com** [vectordotdev/vector#18371]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Follow the doc, both sources syslog and file have same output data filed 'host' that equivalent to gethostname command,
But on my system, syslog source output host output this value like 'hostname -s' do, file source work expected
Here is my debug
```
# hostname
ip-10-0-1-12.cn-north-1.compute.internal
# echo $HOSTNAME
ip-10-0-1-12.cn-north-1.compute.internal
```
file source collected console output 

```
{"file":"/var/log/last.log","host":"ip-10-0-1-12.cn-north-1.compute.internal","message":"reboot   system boot  3.10.0-1127.13.1 Thu Aug 24 13:58 - 14:35  (00:36)    ","source_type":"file","timestamp":"2023-08-24T06:35:01.913864313Z"}
```

syslog source collected console output

```
{"appname":"CROND","facility":"cron","host":"ip-10-0-1-12","hostname":"ip-10-0-1-12","message":"(root) CMD (last > /var/log/last.log)","procid":5358,"severity":"info","source_ip":"127.0.0.1","source_type":"syslog","timestamp":"2023-08-24T06:40:01Z"}
```

check the result what i provided, syslog and file output value 'host' dismatched

Source: syslog, output data filed  

### Configuration

```text
[sources.vector_syslog]
type = "syslog"
address = "127.0.0.1:514"
mode = "udp"
path = "/var/run/vector-syslog"

[sources.generate_syslog]
type = "demo_logs"
format = "syslog"
count = 100

[sources.last_log]
type = "file"
include = [ "/var/log/last/*.log" ]


[sinks.emit_syslog]
inputs = ["vector_syslog", "last_log"]
type = "console"
encoding.codec = "json"
#encoding.codec = "text"

[sinks.syslog_to_s3]
inputs = ["vector_syslog"]
type = "aws_s3"
encoding.codec = "json"
bucket = "cfd-audit-log"
key_prefix = "dev/{{ host }}/{{ facility }}/"
auth.access_key_id = "aaa"
auth.secret_access_key = "bbb"
auth.region = "ccc"
healthcheck.enabled = false
```

### Version

vector 0.32.0 (x86_64-unknown-linux-gnu 1b403e1 2023-08-15 14:56:36.089460954)

### Debug Output

```text
https://gist.github.com/x2x4com/1385d9f836d158b7e06ef5956a6772d2
```

### Example Data

1
```
Aug 24 14:40:01 ip-10-0-1-12 CROND[5358]: (root) CMD (last > /var/log/last.log)
```

2
```
reboot   system boot  3.10.0-1127.13.1 Thu Aug 24 13:58 - 15:07  (01:08)
```

**Comment by jszwedko** [comment]
Hi @x2x4com !

I think the doc for the `syslog` source is incorrect: the `host` there should be the host that comes from the syslog message rather than `gethostname`. If you need the hostname of the underlying host, you could add a `remap` transform that calls https://vector.dev/docs/reference/vrl/functions/#get_hostname to get the underlying host name and add it as a field.

I'll open a PR to update the docs.
