### ISSUE TITLE
Add Vector version information to the VRL playground

### ISSUE THREAD

**Issue by zamazan4ik** [vectordotdev/vector#18403]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Vector has a playground to test VRL programs - https://playground.vrl.dev/ . But right now it's not clear - which Vector version is used during the VRL program evaluation. Since Vector users can have different Vector versions, and between Vector versions can be differences in the available VRL functionality - it's important to understand the currently deployed Vector version on the playground. In the local Vector chat we already have at least one person, who in the past saw the difference between the playground and the local Vector version and spent some time debugging it.

### Attempted Solutions

I see no solutions from the user side except using a self-hosted Vector where a user can track the Vector version.

### Proposal

Add the currently deployed Vector version to https://playground.vrl.dev/ , maybe as a text field or something like that. Ideally, with a precision to commit.

Another idea - host simultaneously multiple Vector versions, and add an option for a user to choose a target Vector (since Vector users don't always live on the latest Vector version and still need to evaluate their VRL programs). It could be done something like godbolt.org already does. But this way will be more difficult to implement.

**Comment by jszwedko** [comment]
Thanks @zamazan4ik ! I agree we should have the version number on there. We have also discussed the idea of having a version switcher.

In case people stumble upon this issue trying to figure out the version that the playground is using, it is currently deployed from the `HEAD` of `master`.

**Comment by zamazan4ik** [comment]
@pront Could we please add the currently deployed commit to the playground? Because right now it's not clear, what is the deployment lag between the master branch and the deployed VRL playground.

**Comment by jszwedko** [comment]
> @pront Could we please add the currently deployed commit to the playground? Because right now it's not clear, what is the deployment lag between the master branch and the deployed VRL playground.

It should be pretty instantaneous, but I agree with putting the SHA with the version number.
