### ISSUE TITLE
Journald source cannot process journal collected from multiple remotes

### ISSUE THREAD

**Issue by a-bali** [vectordotdev/vector#18430]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I'm collecting journals from multiple machines by running `systemd-journal-remote` on the server and `systemd-journal-upload`on the clients. The server collects the journal from remotes to` /var/log/journal/remote`.

I created a Vector journald source pointing to that directory which should contain the journal for all remote clients, but only logs from the first client are collected by Vector (first meaning the first to send an entry after Vector is launched). This is regardless whether the journal is split per host or combined (as per `systemd-journal-remote's` configuration).

The issue seems to be that `journalctl` would require the `--merge` flag to properly parse all entries from all remotes (if this is not passed, I see '`--Reboot--`' messages in journalctl's output between entries from different remotes, however it is not possible to pass it on to `journalctl` by Vector due to lack of configuration options.

A potential solution would be to add a configuration flag to the journald source whether to merge entries or not and pass on the `--merge/-m` flag to the `journalctl` subprocess.

### Configuration

```text
[sources.remote_journald]
type = "journald"
since_now = true
journal_directory = "/var/log/journal/remote"
```

### Version

0.32.1

### Additional Context

systemd v245

**Comment by StephenWakely** [comment]
I wonder if rather than adding a configuration option for just the `merge` option, it might be an idea to add an option for `extra_journalctl_params` which could be used to add any extra parameters that the user may need.

**Comment by a-bali** [comment]
Sounds to me a good solution, being even more universal then the one I suggested originally.

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/18568
