### ISSUE TITLE
deb packaging: Two trailing \n in DEBIAN/conffiles prevent Uyuni/SUSE Manager from importing Vector deb repo

### ISSUE THREAD

**Issue by senecops** [vectordotdev/vector#18439]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We noticed that deb packages generated by cloudsmith cannot be imported into Uyuni/SUSE Manager due to an empty newline in `conffiles`. Steps to check:

```
wget https://repositories.timber.io/public/vector/deb/any-distro/pool/any-version/main/v/ve/vector_0.31.0-1/vector_0.31.0-1_amd64.deb
dpkg-deb -e vector_0.31.0-1_amd64.deb
hd DEBIAN/conffiles
```

I also reproduced this with https://packages.timber.io/vector/nightly/latest/vector_nightly-1_amd64.deb as of 2023-08-31.

Outputs:

```
--2023-08-09 16:26:13--  https://repositories.timber.io/public/vector/deb/any-distro/pool/any-version/main/v/ve/vector_0.31.0-1/vector_0.31.0-1_amd64.deb
Resolving repositories.timber.io (repositories.timber.io)... 2600:9000:21c7:2200:7:d499:1ac0:93a1, 2600:9000:21c7:d000:7:d499:1ac0:93a1, 2600:9000:21c7:4c00:7:d499:1ac0:93a1, ...
Connecting to repositories.timber.io (repositories.timber.io)|2600:9000:21c7:2200:7:d499:1ac0:93a1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27588296 (26M) [application/vnd.debian.binary-package]
Saving to: ‘vector_0.31.0-1_amd64.deb’

vector_0.31.0-1_amd64.deb                       100%[=====================================================================================================>]  26.31M  22.1MB/s    in 1.2s    

2023-08-09 16:26:14 (22.1 MB/s) - ‘vector_0.31.0-1_amd64.deb’ saved [27588296/27588296]

00000000  2f 65 74 63 2f 76 65 63  74 6f 72 2f 76 65 63 74  |/etc/vector/vect|
00000010  6f 72 2e 74 6f 6d 6c 0a  2f 65 74 63 2f 64 65 66  |or.toml./etc/def|
00000020  61 75 6c 74 2f 76 65 63  74 6f 72 0a 0a           |ault/vector..|
0000002d
```

Note the two `0a`. One newline is completely fine and expected. Two are not. The source definition does nothing wrong I would say, ref: https://github.com/vectordotdev/vector/blob/4cc9cdf04cbd2e25426ca3283b76c5b3eee93565/Cargo.toml#L51

### Version

vector 0.31.0 (x86_64-unknown-linux-gnu 0f13b22 2023-07-06 13:52:34.591204470)

### Additional Context

I reported this on 2023-08-09 to support@cloudsmith.io. They say the problem is caused by how Vector creates the package. I was able to confirm that by searching for another project and checking if their conffile also has double newline. https://cloudsmith.io/~isc/repos/stork/packages/detail/deb/isc-stork-server/1.12.0.230802125039/a=amd64;d=any-distro%252Fany-version;t=binary/ has a single new line.

### References

* https://github.com/uyuni-project/uyuni/issues/5212
* https://www.picotech.com/support/topic40901.html
* https://git.dpkg.org/cgit/dpkg/dpkg.git/commit/?id=15416a18f7645dbb9a36edb1e52f30a9e83c6627

**Comment by jszwedko** [comment]
Thanks for reporting this @senecops ! It seems to be an issue with the tool we use to build the debian packages. I opened an issue upstream: https://github.com/kornelski/cargo-deb/issues/110

I noticed the only conffiles we have are in `/etc` though so I think we could actually drop that directive since `dh_installdeb` automatically flags files under `/etc` as conffiles. I'll open a PR to do that.
