### ISSUE TITLE
ARMv6 build

### ISSUE THREAD

**Issue by a-bali** [vectordotdev/vector#18445]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Can we get an ARMv5/v6 build for older Raspberry Pis?

**Comment by jszwedko** [comment]
Just a note that I started looking at this by copy/paste/modifying the armv7 builds, but ran into issues with `protoc` not being found in the path, which was strange. I haven't been able to look into it more than that. This seems like a good contributor issue if anyone is interested. See https://github.com/vectordotdev/vector/pull/18514 for a start.
