### ISSUE TITLE
`aws_kinesis_firehose` source fails to respond to GET requests

### ISSUE THREAD

**Issue by amanmahajan26** [vectordotdev/vector#18486]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I am trying to send CloudWatch logs to Vector via Kinesis firehose. In vector configuration, I have added the `aws_kinesis_firehose` source and deployed vector over a publicly exposed endpoint. With this configuration, logs are being received in vector. Only problem is that the healthcheck that we need to configure for this listener in vector ALB's target group is failing with `MethodNotAllowed` error:

Error log:
`2023-09-05T14:16:05.658920Z ERROR source{component_kind="source" component_id=firehose component_type=aws_kinesis_firehose component_name=firehose}: vector::internal_events::aws_kinesis_firehose: Error occurred while handling request. error="Rejection(MethodNotAllowed)" stage="receiving" error_type="request_failed" error_code=http_response_500 internal_log_rate_secs=10 request_id=`

### Configuration

```text
[api]
      enabled = true
    
[sources.firehose]
type = "aws_kinesis_firehose"
address = "0.0.0.0:443" 
access_key = <ACCESS_KEY>
[sources.firehose.healthcheck]
enabled = true

[transforms.parse_firehose_events]
type = "remap"
inputs = ["firehose"]
drop_on_error = false
source = '''
  parsed = parse_aws_cloudwatch_log_subscription_message!(.message)
  . = unnest(parsed.log_events)
  . = map_values(.) -> |value| {
    event = del(value.log_events)
    value |= event
    
  }
'''

[sinks.firehose_sink]
type = "file"
inputs = [ "parse_firehose_events" ]
path = "/tmp/firehose.log"
  [sinks.firehose_sink.encoding]
  codec = "json"
```

### Version

0.24.2

### Debug Output

```text
2023-09-05T14:16:05.658920Z ERROR source{component_kind="source" component_id=firehose component_type=aws_kinesis_firehose component_name=firehose}: vector::internal_events::aws_kinesis_firehose: Error occurred while handling request. error="Rejection(MethodNotAllowed)" stage="receiving" error_type="request_failed" error_code=http_response_500 internal_log_rate_secs=10 request_id=
```

### References

#8109

**Comment by StephenWakely** [comment]
The `firehose` endpoint is just for sending events to. 

To ascertains Vector's health you can use the `/health` endpoint in the Vector [api](https://vector.dev/docs/reference/api/#endpoints). Would that work for you?

**Comment by amanmahajan26** [comment]
Ok, I see. Yes, that would be fine.
