### ISSUE TITLE
Source aws_s3 using sqs queue raises error

### ISSUE THREAD

**Issue by nellynp** [vectordotdev/vector#18617]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The following ERROR appears when running the vector configuration:

ERROR source{component_kind="source" component_id=s3_bucket component_type=aws_s3 component_name=s3_bucket}: vector::internal_events::aws_sqs: Failed to fetch SQS events. error=service error error_code="failed_fetching_sqs_events" error_type="request_failed" stage="receiving" internal_log_rate_limit=true

ERROR source{component_kind="source" component_id=s3_bucket component_type=aws_s3 component_name=s3_bucket}: vector::internal_events::aws_sqs: Internal log [Failed to fetch SQS events.] is being suppressed to avoid flooding.

ERROR source{component_kind="source" component_id=s3_bucket component_type=aws_s3 component_name=s3_bucket}: vector::internal_events::aws_sqs: Internal log [Failed to fetch SQS events.] has been suppressed 817 times.

Also, index does not appear in kibana after running vector.

### Configuration

```text
sources:
  s3_bucket:
    type: aws_s3
    compression: auto
    endpoint: https://endpoint.s3.some-region.amazonaws.com
    region: some-region
    sqs:
      queue_url: https://sqs.some-region.amazonaws.com/...

sinks:
  elasticsearch:
    type: elasticsearch
    inputs:
      -   s3_bucket
    endpoints:
      - "https://es01:9200"
    bulk:
      index: "awss3"
    compression: "none"
    tls:
      ca_file: "ca.crt"
    api_version: "v8"
    auth:
      strategy: "basic"
      user: "${ELASTIC_USER}"
      password: "${ELASTIC_PASSWORD}"
```

### Version

0.32.1

### Debug Output

 DEBUG source{component_kind="source" component_id=s3_bucket component_type=aws_s3 component_name=s3_bucket}:send_operation{operation="ReceiveMessage" service="sqs"}:async_map_request{name="retrieve_credentials"}: aws_credential_types::cache::lazy_caching: loaded credentials from cache

DEBUG source{component_kind="source" component_id=s3_bucket component_type=aws_s3 component_name=s3_bucket}:send_operation{operation="ReceiveMessage" service="sqs"}:dispatch: hyper::client::pool: reuse idle connection for ("https", endpoint.s3.some-region.amazonaws.com)

DEBUG hyper::proto::h1::io: flushed 1723 bytes

DEBUG hyper::proto::h1::io: parsed 6 headers

DEBUG hyper::proto::h1::conn: incoming body is chunked encoding

DEBUG hyper::proto::h1::decode: incoming chunked header: 0x189 (393 bytes)

DEBUG hyper::proto::h1::conn: incoming body completed

DEBUG hyper::client::pool: pooling idle connection for ("https", endpoint.s3.some-region.amazonaws.com)

### Additional Context

I am running vector with docker compose:
 vector:
  image: timberio/vector:latest-alpine
  volumes:
    - ./vector.yml:/etc/vector/vector.yml:ro
    - certs:/usr/share/vector/config/certs
  environment:
     - ELASTIC_USER=elastic
     - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}

     - http_proxy=http://some-ip-and-port
     - https_proxy=http://some-ip-and-port

     - no_proxy=localhost,10.0.0.0/8,es01

**Comment by jszwedko** [comment]
Hi @nellynp ,

I'd suggest trying to set `VECTOR_LOG=aws_smithy_http=trace`. That should give you some more debug logs that'll help illuminate the error.

**Comment by nellynp** [comment]
Hi @jszwedko,

This is what I get when using `VECTOR_LOG=aws_smithy_http=trace`:

`TRACE dispatch: aws_smithy_http_tower::dispatch: dispatching request request=Request { method: POST, uri: https://endpoint.s3.some-region.amazonaws.com/, version: HTTP/1.1, headers: {"content-type": "application/x-www-form-urlencoded", "content-length": "194", "user-agent": "aws-sdk-rust/0.54.1 os/linux lang/rust/1.71.1", "x-amz-user-agent": "aws-sdk-rust/0.54.1 api/sqs/0.24.0 os/linux lang/rust/1.71.1", "x-amz-date": "20230922T073230Z", "authorization": Sensitive, "x-amz-security-token": "redacted"}, body: SdkBody { inner: Once(Some(b"Action=ReceiveMessage&Version=2012-11-05&QueueUrl=https%3A%2F%2Fsqs.some-region.amazonaws.com%2F428062847257%2Fredacted&MaxNumberOfMessages=10&VisibilityTimeout=300&WaitTimeSeconds=15")), retryable: true } }`

`TRACE load_response: aws_smithy_http::middleware: read HTTP response body http_response=Response { status: 412, version: HTTP/1.1, headers: 
{"x-amz-request-id": "redacted", "x-amz-id-2": "redacted", "content-type": "application/xml", "transfer-encoding": "chunked", "date": "Fri, 22 Sep 2023 07:32:29 GMT", "server": "AmazonS3"}, body: b"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>PreconditionFailed</Code><Message>At least one of the pre-conditions you specified did not hold</Message><Condition>Bucket POST must be of the enclosure-type multipart/form-data</Condition><RequestId>redacted</RequestId>redacted</HostId></Error>" }`

**Comment by jszwedko** [comment]
Ah, I think I see the issue here. You are specifying `endpoint` which is also used for the SQS API requests which is causing the API requests to be sent to the virtual S3 bucket endpoint rather than the SQS API. Do you need to be specifying `endpoint`? Could you try removing that and see what happens?

**Comment by nellynp** [comment]
That worked! Thanks! The documentation wasn't clear on how to set it.
