### ISSUE TITLE
Use Exponential Backoff to handle AWS S3 Rate Limiting for better flow control

### ISSUE THREAD

**Issue by wmyre** [vectordotdev/vector#18708]
As an engineer I'd like Vector to have exponential backoff in place for rate-limited requests. 
When a request is rate limited, it can retry again in the current step, but if the 2nd retry returns a rate-limit error, then push to a method which performs asynchronous exponential backoff's . Ideally we also build telemetry metrics around this so users' can measure the current delay of the backoff. 

This would have high levels of re-usability across other outputs using rate-limiting responses as well. 

Something like: https://docs.rs/backoff/latest/backoff/
https://github.com/vectordotdev/vector/blob/18f07a00efc6843ccabb74153291d25573e39293/src/aws/mod.rs#L56

**Comment by jszwedko** [comment]
Hi @wmyre!

I'm not 100% sure what is being asked for here because Vector already does exponential back-offs for requests. This is implemented here: https://github.com/vectordotdev/vector/blob/master/src/sinks/util/retries.rs. Can you confirm what behavior it is that you are looking for?

**Comment by wmyre** [comment]
> Hi @wmyre!
> 
> I'm not 100% sure what is being asked for here because Vector already does exponential back-offs for requests. This is implemented here: https://github.com/vectordotdev/vector/blob/master/src/sinks/util/retries.rs. Can you confirm what behavior it is that you are looking for?

Ah, thank you for the reference! That is what I was looking for, and I see now that you pass in configurable retry args for the sink. I was mainly looking for areas that could present reliability issues for a sudden, high-load, of errored requests.

**Comment by jszwedko** [comment]
Gotcha 👍 I'll close this out since this specific request is already satisfied, but if you additional use-cases that aren't satisfied, feel free to open a new issue.
