### ISSUE TITLE
Invalid field path when referencing namespaced field key

### ISSUE THREAD

**Issue by sbalmos** [vectordotdev/vector#18867]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I'm performing initial testing of using the new namespaced log format. However I receive an fatal configuration error of Invalid field path whenever I am using a namespaced key name in a `*_key` configuration. In this particular small case, I am changing the `timestamp_key` field of my Splunk HEC sink to use the new `%vector.ingest_timestamp` timestamp, rather than the default `.timestamp` field of the event message.

### Configuration

```text
data_dir: /tmp
api:
  enabled: true
  address: 127.0.0.1:8686
  playground: false
schema:
  log_namespace: true
sources:
  console_in:
    type: stdin
transforms:
  rebuild_msg:
    type: remap
    inputs:
      - console_in
    source: |-
      msg, err = parse_json(.)
      if msg != null { . = msg }
sinks:
  console_out:
    type: console
    target: stdout
    inputs:
      - rebuild_msg
    encoding:
      codec: json
  splunk_hec:
    type: splunk_hec_logs
    inputs:
      - rebuild_msg
    default_token: abc123
    endpoint: http://127.0.0.1:12345
    timestamp_key: "%vector.ingest_timestamp"
    encoding:
      codec: json
    healthcheck:
      enabled: false
```

### Version

vector 0.34.0-custom-11bc5d98b (x86_64-unknown-linux-gnu debug=full)

### Debug Output

```text
2023-10-17T19:09:41.629797Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=info,rdkafka=info,buffers=info,lapin=info,kube=info"
2023-10-17T19:09:41.664380Z  INFO vector::app: Loading configs. paths=["test_namespace.yaml"]
2023-10-17T19:09:41.769183Z ERROR vector::cli: Configuration error. error=Invalid field path "%vector.ingest_timestamp"


in `sinks.splunk_hec`
```

**Comment by neuronull** [comment]
Hello and thanks for the bug report.

Checking with others in the team it sounds like the error message isn't super clear here, it could stand to be improved. Currently the Splunk HEC sink only allows that config setting to point to event fields, so the "%" isn't allowed in the path.

The fix likely involves changing the config setting's type from `ConfigValuePath` to `ConfigTargetPath`.
