### ISSUE TITLE
Bump to Rust 1.73.0

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#18870]
https://blog.rust-lang.org/2023/10/05/Rust-1.73.0.html

**Comment by StephenWakely** [comment]
> any and all help is greatly appreciated 🙇‍♂️

That is technically just a warning telling us that the call to `clone` the `entry_path` is unnecessary. It looks like the rust compiler got a little smarter and can now detect this. 

This can be fixed by just removing the  `.clone()` call.

```diff
                let last_component = entry_path
                    .file_name()
                    .unwrap_or_else(|| panic!("Failed to get file_name for {entry_path:?}"));
-                   .clone();
```

**Comment by dsmith3197** [comment]
https://github.com/vectordotdev/vector/pull/19518
