### ISSUE TITLE
Optionally emit __CURSOR for journald source

### ISSUE THREAD

**Issue by sproberts92** [vectordotdev/vector#18881]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Some platforms with older versions of systemd do not have `__SEQNUM` or `__SEQNUM_ID`, and so events do not contain sufficient uniqueness to derive an id for indexing (without resorting to hashing the message or similar, which doesn't let you work backwards to locate the original event at the source).

### Proposal

The `__CURSOR` field does actually contain the `__SEQNUM` and `__SEQNUM_ID`, even on systems that don't have those fields, so it would be good to be able to optionally emit the cursor with the event.

So I propose that we add a boolean option `emit_cursor` to enable sending `__CURSOR` with the event for use on older platforms, instead of stripping it out as currently occurs.

**Comment by tobz** [comment]
@sproberts92 Are you able to link to anything that shows the chronology of `__SEQNUM`, `__SEQNUM_ID`, and `__CURSOR`? Doing a cursory search didn't really turn anything up, and it would lend weight towards the idea of making a change for compatibility purposes if we could demonstrate for a fact it would increase compatibility.

**Comment by sproberts92** [comment]
Chronology as in when were `__SEQNUM` and `__SEQNUM_ID` introduced? They were only added to the json journal output (which Vector consumes) in [February this year](https://github.com/systemd/systemd/commit/2bc70e2e9db13cfbc74e4bf1fd28ecbfef1466c9), which made it into systemd v254.

Really only Arch has v254 at the moment, so this change is making deriving a unique index possible on almost all platforms where it wasn't before. And even on v254 it's still useful, from [sd_journal_get_cursor](https://www.freedesktop.org/software/systemd/man/latest/sd_journal_get_cursor.html):
 
>  The string only contains printable characters and can be passed around in text form. The cursor identifies a journal entry globally and in a stable way

Probably nicer to use that instead of needing to construct your own id from `_SEQNUM` + `_BOOT_ID` + etc.

**Comment by dsmith3197** [comment]
This work was completed in https://github.com/vectordotdev/vector/pull/18882
