### ISSUE TITLE
Add IMDSv1 support for the `aws_ec2_metadata` transform

### ISSUE THREAD

**Issue by LucioFranco** [vectordotdev/vector#1890]
We should consider adding `IMDSv1` support via an optional flag. This would by-pass our current usage of `IMDSv2` which is the new metadata API. 

A couple issues we are seeing with the `IMDSv2` API is when the HTTP request has to hop through multiple "networks" an example of this is running vector withing a docker container which means that all http requests must make at least 2 network hops. By default EC2 sets this value to 1 and thus by default with `IMDSv2` vector will not work out of the box. 

The solution here is to run this command:
`aws ec2 modify-instance-metadata-options --instance-id <ID> --http-endpoint enabled --http-put-response-hop-limit 2`

Another potential solution would be to implement `IMDSv1` and tell users to use that if they are having issues while running vector within a docker container.

Some further things that we should consider is that 1) `IMDSv1` may get deprecated by AWS soon since its pretty insecure 2) EC2 in the future may consider bumping the default to 2 instead of 1 hop.

**Comment by jszwedko** [comment]
Closing this since we are only supporting IMDSv2 now.
