### ISSUE TITLE
sh.vector.dev is down

### ISSUE THREAD

**Issue by fuadsaud** [vectordotdev/vector#18997]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Not sure if this is the correct place to report the problem.

I noticed one of our setup scripts that installed vector via the installation script started failing around 15h36 UTC today:

```sh
❯❯❯ curl --proto '=https' --tlsv1.2 -sSf https://sh.vector.dev
curl: (35) LibreSSL/3.3.6: error:1404B42E:SSL routines:ST_CONNECT:tlsv1 alert protocol version
```

### Version

N/A

**Comment by jszwedko** [comment]
Apologies @fuadsaud ! This is due to an issue with a hosting cutover. We are resolving it now.

**Comment by fuadsaud** [comment]
@jszwedko thanks for your response!

I was able to fix the problem temporarily by pointing the script to download the installation script from GitHub.

**Comment by jszwedko** [comment]
This should be back up. Note that you'll need to add `-L` to the `curl` to follow redirects now. https://github.com/vectordotdev/vector/pull/19000 updates the documentation to include this.
