### ISSUE TITLE
Vector returning 500 when hit non-existing endpoint

### ISSUE THREAD

**Issue by saban90** [vectordotdev/vector#19098]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hi,

We are running vector agent on our instances in AWS and we noticed that we are getting Applicationelb target 5XX when users try to hit non existing endpoint. After research our conclusion is that vector agent is return 500 status if endpoint doesn't exist, which sounds like wrong, because we would expect some 4XX code for this.

for example request to the following endpoints:
https://someurl.elb.amazonaws.com:443/somethingrandom.conf   produces target 500.
https://someurl.elb.amazonaws.com:443    gives 2XX or 4XX

Thank you.

### Version

0.26.0

**Comment by jszwedko** [comment]
Hi @saban90 !

Could you please edit this issue to provide the configuration and debug output?

**Comment by jszwedko** [comment]
Closing due to lack of response.
