### ISSUE TITLE
Updated docker but now only looking for yaml

### ISSUE THREAD

**Issue by tknx** [vectordotdev/vector#19096]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I recently updated the docker to timberio/vector:latest-alpine at 2023-11-08-1600PST and now it won't start.

Logs show the following:
`2023-11-09T00:08:10.559346Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=info,rdkafka=info,buffers=info,lapin=info,kube=info"
2023-11-09T00:08:10.560253Z ERROR vector::config::loading: Config file not found in path. path="/etc/vector/vector.yaml"
2023-11-09T00:08:47.485678Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=info,rdkafka=info,buffers=info,lapin=info,kube=info"
2023-11-09T00:08:47.486591Z ERROR vector::config::loading: Config file not found in path. path="/etc/vector/vector.yaml"`

### Configuration

```text
[sources.docker_logs]
type = "docker_logs"

[sources.unraid_logs]
type = "file"
include = ["/var/log/syslog"]

[sinks.zinc]
type = "http"
inputs = ["docker_logs", "unraid_logs"]
uri = "https://api.zinc.dev/api/tarun_organization_966/default/_json"
method = "post"
auth.strategy = "basic"
auth.user = "redacted"
auth.password = "redacted"
compression = "gzip"
encoding.codec = "json"
encoding.timestamp_format = "rfc3339"
healthcheck.enabled = false
```

### Version

latest:alpine

### Debug Output

```text
Can't create since docker won't launch
```

**Comment by John-Dai** [comment]
I think the latest release 0.34 performed the following deprecation, but it wasn't documented.
```DEPRECATED Using the deprecated "/etc/vector/vector.toml" config path as the default config location. Vector is migrating to YAML as the default config format. Future Vector versions will use "/etc/vector/vector.yaml" as the default config location.```

Try passing in the toml file via the `-c` flag or via the `VECTOR_CONFIG_TOML` environment variable.

**Comment by hhromic** [comment]
> (...), but it wasn't documented.

This was changed in release v0.33.0 actually and it was documented: <https://vector.dev/releases/0.33.0/>

Furthermore, from the highlight: <https://vector.dev/highlights/2023-08-30-yaml-default-format/>
> If you are relying on Vector auto-loading /etc/vector/vector.toml, this will still work in 0.33.0 but it is now deprecated. The aforementioned location will no longer be considered in 0.34.0.

**Comment by jszwedko** [comment]
Hi @tknx !

Apologies, As @hhromic noted this deprecation was noted in v0.33.0, but it does look like we forgot to include a note in v0.34.0 about the breaking change. I opened https://github.com/vectordotdev/vector/pull/19120 to fix that.
