### ISSUE TITLE
Splunk HEC timestamp field removal and unnecessary warnings

### ISSUE THREAD

**Issue by tbenade** [vectordotdev/vector#19133]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hi, trying to understand why our `timestamp` field is being removed by the Splunk HEC Sink when we are posting to the `event` endpoint_target with `auto_extract_timestamp` set to true.

Example the additional `timestamp` field we added gets removed by the sink `.timestamp = parse_timestamp!(.datetime, "%d/%b/%Y:%H:%M:%S")`

In addition we don't understand the point of the supplied warning given the current configuration requesting we want to send to the Splunk HEC and want Splunk to auto extract the timestamp.

```{"host":"ip-eee-ap-southeast-2.compute.internal","internal_log_rate_limit":true,"message":"Timestamp was not found. Deferring to Splunk to set the timestamp.","metadata":{"kind":"event","level":"WARN","module_path":"vector::internal_events::splunk_hec::sink","target":"vector::internal_events::splunk_hec::sink"},"pid":9744,"source_type":"internal_logs","vector":{"component_id":"splunk_sink","component_kind":"sink","component_type":"splunk_hec_logs"}}```

### Configuration

```text
sources:
  demo_logs:
    type: demo_logs
    format: json
    interval: 10
transforms:
  demo_logs_parser:
    inputs:
      - "demo_logs"
    type: "remap"
    source: |
      . = parse_json!(.message)
      .datetime = parse_timestamp!(.datetime, "%d/%b/%Y:%H:%M:%S")
      .timestamp = parse_timestamp!(.datetime, "%d/%b/%Y:%H:%M:%S")
sinks:
  splunk_sink:
    type: splunk_hec_logs
    inputs:
      - splk_*
    compression: gzip
    endpoint: "https://http-inputs-acme.splunkcloud.com"
    endpoint_target: event
    index: "test_sink"
    source: "splunk_sink_event"
    auto_extract_timestamp: true
    sourcetype: "_json"
    default_token: "SECRET[backend_aws_secrets_manager.never_you_mind]"
    encoding:
      codec: json
```

### Version

0.34

### Example Data

```
{"bytes":3638,"datetime":"13/Nov/2023:10:42:18","host":"147.154.143.110","method":"OPTION","protocol":"HTTP/2.0","referer":"https://some.netbank/wp-admin","request":"/apps/deploy","status":"403","user-identifier":"KarimMove"}
```

**Comment by bruceg** [comment]
I am a little confused by the planned usage. The configuration for `auto_extract_timestamp` is intended to parse a timestamp out of the message field. In the case of the configuration above, it is manually parsing out a timestamp from another field. Vector is pulling that timestamp out of the event data and sending it along to Humio in the HEC request data. Please clarify how you would like the timestamp to be handled.

**Comment by tbenade** [comment]
Hi, 

My configuration is just an arbitrary example to demonstrate that Vector is removing my timestamp field. `auto_extract_timestamp` is a query parameter that is sent to Splunk that tells Splunk that no specific timestamp has been sent along with the event and Splunk should use its own configuration to decide the correct value for the correct time of the posted event. In this case Vector should not be touching the data and passing it on to Splunk as the user intended, which appears to not be the case. The `datetime` field gets to Splunk in the event payload just fine but `timestamp` is stripped from the payload.

Not sure why you are talking about Humio there was no mention of Humio in the issue context.

**Comment by bruceg** [comment]
My apologies for the confusion. I had been looking at a couple of sources and mixed the terms up.

Thank you for the clarification. From what I am seeing in the code, this issue is caused by the `splunk_hec_logs` sink always removing the `timestamp` field even if `auto_extract_timestamp` is set to true. For now, I believe you can work around this by setting `timestamp_key` in the config to some unused field name. This will still produce the nuisance warning, but it should not remove the timestamp field. I will discuss with the rest of the team whether we want to change the default behavior of `auto_extract_timestamp` to improve this.

**Comment by tbenade** [comment]
Thanks, I can concur the workaround has worked. Look forward to the outcome from the team.

**Comment by bruceg** [comment]
We have some confusion about the intended use case for what is described above. From our understanding, Splunk will always use the `timestamp` field in the header, even when `auto_extract_timestamp` is set. So, if we were not to remove the timestamp, Splunk would not attempt to parse the timestamp from the message, which is what `auto_extract_timestamp` is telling it to do. Could you clarify what you are trying to accomplish with the above original config?

**Comment by tbenade** [comment]
Apologies for the delayed response my Github notifications are broken.

I think at its most simplest Vector should not be touching the contents of the log message. The user should be able to post to and configure the sink as they see fit and Vector should just fulfil the request. Its a confusing and undocumented diagnostic path if Vector starts making assumptions about what the user is trying to do. Add to that we end up in this situation where the user could change their data or vector configuration to get the solution working, but instead now need lobby for a code change in the underlying solution.

The Splunk documentations states.
> [services/collector/event](http://docs.splunk.com/Documentation/Splunk/9.2.0/RESTREF/RESTinput#services.2Fcollector.2Fevent)
> Sends timestamped events to the HTTP Event Collector using the Splunk platform JSON event protocol when you set the auto_extract_timestamp argument to true in the /event URL.
> An example of a timestamp is 2017-01-02 00:00:00
> - If there's a timestamp in the event's JSON envelope, Splunk honors that timestamp first.
> - If there's no timestamp in the event's JSON envelope, the merging pipeline extracts the timestamp from the event.
> - If time=xxx is used in the /event URL, then auto_extract_timestamp is disabled.

The sink ideally should work exactly as is stated by the Splunk documentation. We are currently working with migrating workloads off fluentbit forwarders to Vector and they work as expected and without any `timestamp` handling specific configuration. Events are posted to Splunk HEC and indexed timestamps for the events are garnered from their payloads. Cant immediately think of a reason Vector shouldn't behave the same.

**Comment by jszwedko** [comment]
My take is that setting `auto_extract_timestamp` to `true` on the `splunk_hec_logs` sink should disable removal of the `timestamp` field. Otherwise it should map the `timestamp` field to `time` per https://docs.splunk.com/Documentation/Splunk/latest/Data/FormateventsforHTTPEventCollector#Event_metadata so that it is picked up correctly by Splunk when `auto_extract_timestamp` is set to `false`.

**Comment by jszwedko** [comment]
Ah, sorry, I mean:

When `auto_extract_timestamp` is set to `true`, I think Vector should leave the `timestamp` field on the event when sending it to Splunk as Splunk will do the extraction.

When `auto_extract_timestamp` is set to `false`, I think Vector should set the `time` field on the HEC payload to whatever the `timestamp` field on the event is and remove the `timestamp` field from the event.

**Comment by tbenade** [comment]
Thanks @jszwedko for coming back as always, much appreciated. While I don't agree the field should be deleted I can confirm it works well as mentioned. 

If I may, my rationale for the for not removing the field is that users use the splunk UI differently and many are not even aware of internal event time functions/capability/fields etc like `_time`. They just look at their logs and want to see a field with the time in it as that is what they sent to Splunk. Quick and easy no Splunk experience required. I also believe by removing the field we are only taking something away from the customer, I don't see how we are adding value by removing the data. Maybe one day the removal of the timestamp field could be configurable rather than having that opinion imposed on the sink user.
