### ISSUE TITLE
In `prometheus_scrape` the options `endpoint_tag` & `instance_tag` seem to do the same thing

### ISSUE THREAD

**Issue by james-stevens** [vectordotdev/vector#19146]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

In `prometheus_scrape` the options `endpoint_tag` & `instance_tag` seem to do the same thing - i.e. they add a prometheus tag (with a name of your choice) with the value of the scrape source. But there's no option to set the value they add as the scrape source - they *ALWAYS* use the scrape source you have specified. My problem is my scrape source is `127.0.0.1` :)

So two options that do the same thing, but no option for what I want to do :)

I'm running `vector` on the same box as a number of services that output prometheus metrics. To make the system more secure I have made all the prometheus emitters LISTEN on `127.0.0.1` and have a locally running `vector` collect from there. Then I want to use `vector` to push all the metrics to a central `vector` as this means I can add TLS using authenticate using a private CA. We need the local `vector` anyway for other purposes.

The problem is, I have lots of servers set up like this, & `vector` is labelling all the `instance_tag`s with `127.0.0.1` which is less than useful when all aggregated together.

What I would like to be able to do is have `vector` add an instance tag, but then also be able to specify the instance tag's value.

It would also be nice to be able to set an `instance` tag & value for `internal_metrics`

Basically, because I want to use `vector` as a wide-area prometheus aggregator, I *need* the `instance` tag to have been set correctly BEFORE the metrics leave each individual server.

I could use prometheus to collect from the `vector` on each server (there by adding the `instance` tag), then get `vector` to re-collect from prometheus & push the data up, but that's messy. Or I could also use prometheus to collect from the `vector` on each server, then use another prometheus to collect from the first prometheus, but we're planning on running `vector` anyway and fixing this issue would save us running one extra prometheus ... and `vector` is *SO* close to being able to do what we want!!!!!

Being able to use `vector` as a scalable & secure prometheus aggregator would be nice.

### Configuration

```text
node_metrics:
    type: prometheus_scrape
    scrape_interval_secs: 15
    scrape_timeout_secs: 2
    endpoints:
      - "http://127.0.0.1:9100/metrics"
```

### Version

vector 0.34.0 (x86_64-unknown-linux-gnu c909b66 2023-11-07 15:07:26.748571656)

**Comment by bruceg** [comment]
Setting `instance_tag` should be including the port number, according to both the documentation and my reading of the source code, which would make the tag unique for each port being listened to on localhost. Is that not the case, or is that insufficient? VRL also includes facilities for remapping those tag values, could that be used to map the port value to a unique tag?

**Comment by james-stevens** [comment]
> Setting `instance_tag` should be including the port number, according to both the documentation and my reading of the source code, which would make the tag unique for each port being listened to on localhost. Is that not the case, or is that insufficient? VRL also includes facilities for remapping those tag values, could that be used to map the port value to a unique tag?

I think you've missed the point - I have 25 hosts & `vector` is collecting from `127.0.0.1:9100` on all of them - its not the port that's the problem but the IP Address. When all the data is collated in one place, all the metrics say `instance="127.0.0.1:9100"`

As you suggest, I could prob remap the `instance` value in VRL, or simply not use the `instance_tag` option at all, but add the `instance` tag & value in VRL - but seems to me a pretty trivial thing to just allow me to set the instance tag **value** as well as the instance tag **name**.

Another work-around might be to use `/etc/hosts` to alias the host name (or any unique name) to the IP `127.0.0.1`, then configure `vector` to collect from the name I've put in `/etc/hosts`, which `vector` will then use as the instance tag value - but I will also then need to get `vector` to collect its own `internal_metrics` from itself in order to have an `instance` tag added ... so just adding an instance tag & value of my choice in VRL is probably the cleanest way to solve this for now.

Just seems odd to have two options to set a name, but no corresponding option to set the value.

**Comment by bruceg** [comment]
You are correct I misread the description. Do I hear right, then, that you have individual Vector instances on each host, and then a central aggregator collecting from all of these which, as described, all show the same instance tag in the metrics? I can see from that how the `instance_tag` as currently defined is not useful for you.

In general, a `remap` transform using VRL is our recommended solution for data modifications like this. An alternative approach would be to have some kind of enrichment transform that adds the current host name similar to what `aws_ec2_metadata` transform does, but such a transform does not currently exist.

**Comment by james-stevens** [comment]
> Do I hear right, then, that you have individual Vector instances on each host, and then a central aggregator collecting from all of these which, as described, all show the same instance tag in the metrics?

yes - we have the vector there for other reasons - but using it to aggregate the metrics makes the server more secure. Instead of having to expose all the metrics publishers to a wider audience they only have to listen on `127.0.0.1`. It also means we can push the metrics instead of pulling them, so there's no outbound listener for metrics - which is def nice, IMHO - and we can add TLS & authentication with a private CA.

I could use a `remap` to change the value of the `instance`, for collected metrics, but for the `internal_metrics`, I would still need to add a tag, so I'll have to use an enrichment anyway. Seeing as I will need an "enrichment" to add `instance` to the `internal_metrics`, I may as well use the same `enrichment` to add the `instance` tag to all metrics, and disregard both the `intance_tag` & `endpoint_tag` options.

Like I said, it seems a shame to have two options, that basically do the exact same thing, but neither do what I need, so I'm going to have to add my own code.

So near and yet so far ... :)

**Comment by bruceg** [comment]
Thank you for the clarifications, @james-stevens. Your description of your intended architecture makes sense to me, as does the desire to not have to have listening ports open on the boxes.

As previously indicated, this kind of use case is a good example of why we developed remap in the first place. As such, we are unlikely to add a tagging options like that to `internal_metrics` without also adding it to all of the metric sources. We have discussed some possible options for making it simpler to attach a remap to components, which would greatly simplify use cases like this — almost as simple as configuring an instance tag as you describe — however that far from a definite plan at this point.

**Comment by james-stevens** [comment]
Sure, thanks - I totally understand - just seems a shame to have two options that do the same thing, but don't quite do what I want. Doing it in VRL looks reasonably easy ... time will tell ;)

You may as well close this `issue` then - unless you want to dedup those two options !!


FYI: its not actually the first-stage aggregation on-box that's the issue, in fact - cos, if we collect the (first stage) aggregated metrics from each (of 25) boxes using prometheus itself, then it will add a correct `instance` tag.

Its only when we go the the second level aggregation, pushing from on-box vector to a remote vector, for the full & final aggregation, is when we see the problem. But (for me), having only a single client/outgoing TLS+Private CA connection (from the entire site) containing all the metrics, is worth the small pain of getting it working just right !!

Its also nice that using vector means there's (normally) no local storage requirement (unless it buffers), where as if we used prometheus federation for aggregation, it would do that using local storage, both/either on box & per-site.


great product, BTW ... and I've had some really great support raising a couple of other bugs - so thanks to everybody on the team!

**Comment by Salathaniel** [comment]
https://gptzero.me/?via=salathaniel
