### ISSUE TITLE
Add namespace to chronicle sink 

### ISSUE THREAD

**Issue by JennaBlack** [vectordotdev/vector#19183]
add support for a new Sink level field named `namespace`

https://cloud.google.com/chronicle/docs/reference/ingestion-api#unstructuredlogentries 

> namespace | string
> User-configured environment namespace to identify the data domain the logs originated from. Use namespace as a tag to identify the appropriate data domain for indexing and enrichment functionality.

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/19398
