### ISSUE TITLE
Vector Kafka Configure headers_key maybe not effective in the Sink 

### ISSUE THREAD

**Issue by csh0101** [vectordotdev/vector#19209]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I just to test the kafka headers_key configure for vector.
I excepted  
when I exec Command `echo '{"headers": {"data-parse-format": "json"}} ' | vector -c local_vector.toml -v ` , this message should be deliver to kafka broker, and the kafka sink will extract this kv pair in to Kafka Headers.. But it's not real in the truth. 
I find it not work.  
and I discover the event have some metadata, like source_type,host. I just want to know , if the  sink to extract headers from log event by specify headers_key on configuration file. it will at the root directory, if there a json,in the above command,
echo echo '{"headers": {"data-parse-format": "json"}} , this output maybe is include something like this { source_type: xxx, myoutput$: {echo_ouput},} and at this situation, the sink is find at root dir, but not echo_output which is my real log,not vector log. If my guess is right,I think there maybe have a gap or bug when I to use the headers_key..
@fuchsnj  
so i saw this pr is contributed by  you ! my homie!  can you have time to express my confuse ....
very thanks! 

### Configuration

```text
#local_vector
data_dir = "/tmp/vector"
[api]
enabled = true
[sources.log]
type = "stdin"
# ignore_older = 600
# include = ["/tmp/log_test.log"] #你的日志文件

[sinks.aliyun_sls]
type = "kafka"
inputs = ["log"]                                                         #如果添加自行添加一些transform，做相应修改
bootstrap_servers = "test-vector-log.cn-hangzhou.log.aliyuncs.com:10012"
compression = "gzip"
healthcheck = true
topic = "test"                                                           # 对应申请的日志库名称
headers_key = "headers"
# acknowledgements.enabled = true
encoding.codec = "json"
sasl.enabled = true
sasl.mechanism = "PLAIN"
```

### Version

vector 0.35.0 (aarch64-apple-darwin)

### Example Data

Key: None, Value: b'{"host":"juanxincaideMacBook-Pro.local","message":"{\\"headers\\": {\\"data-parse-format\\": \\"json\\"}} ","source_type":"stdin","timestamp":"2023-11-21T06:48:42.813462Z"}', Headers: None
this is by a simple python client

**Comment by bruceg** [comment]
This looks like the source (a `stdin` source, I presume) is interpreting the input data as bytes and not as JSON. Could we see the configuration of the source as well to verify?

**Comment by csh0101** [comment]
> This looks like the source (a `stdin` source, I presume) is interpreting the input data as bytes and not as JSON. Could we see the configuration of the source as well to verify?这看起来像源（我认为是 `stdin` 源）将输入数据解释为字节而不是 JSON。我们是否也可以查看源的配置来进行验证？

very think to your reply! I was confused. I have no extra configuration for the source named `log`. And I understand that you mean, just maybe I should add the  codec  the source `stdin` ?

**Comment by csh0101** [comment]
I will show you my source config @bruceg 
``` toml
[sources.log]
type = "stdin"
```

**Comment by csh0101** [comment]
> I will show you my source config 我将向您展示我的源配置@bruceg
> 
> ```toml
> [sources.log]
> type = "stdin"
> ```

it's everything!

**Comment by csh0101** [comment]
@bruceg  
maybe I misunderstand your meaning. But I should report to your about my experiment. And I just want say 
I change my source to type `file`, but it's also failed.. 
``` toml 
[sources.log]
type = "file"
ignore_older = 600
include = ["/tmp/log_test.log"]
[sinks.aliyun_sls]
type = "kafka"
inputs = ["log"]                      #如果添加自行添加一些transform，做相应修改
bootstrap_servers = "127.0.0.1:10012"
healthcheck = true
topic = "test"                        # 对应申请的日志库名称
headers_key = "headers"
encoding.codec = "json"
```
``` test_log.log 
{"message":"This is an information log message.","context":{},"level":200,"level_name":"INFO","channel":"my_logger","datetime":"2023-11-20T15:51:45.359632+08:00","extra":{},"headers":{"data-parse-format":"json"}}
```

**Comment by csh0101** [comment]
> @bruceg maybe I misunderstand your meaning. But I should report to your about my experiment. And I just want say也许我误解了你的意思。但我应该向你报告我的实验。我只想说 I change my source to type `file`, but it's also failed..我将源更改为 `file` 类型，但它也失败了。
> 
> ```toml
> [sources.log]
> type = "file"
> ignore_older = 600
> include = ["/tmp/log_test.log"]
> [sinks.aliyun_sls]
> type = "kafka"
> inputs = ["log"]                      #如果添加自行添加一些transform，做相应修改
> bootstrap_servers = "127.0.0.1:10012"
> healthcheck = true
> topic = "test"                        # 对应申请的日志库名称
> headers_key = "headers"
> encoding.codec = "json"
> ```
> 
> ```
> {"message":"This is an information log message.","context":{},"level":200,"level_name":"INFO","channel":"my_logger","datetime":"2023-11-20T15:51:45.359632+08:00","extra":{},"headers":{"data-parse-format":"json"}}
> ```

what I expect ? I think maybe the headers is extracted by sink component because of the specify headers_key :"headers"

**Comment by bruceg** [comment]
Okay, I think I see what is going on. The `log` source is handling the whole line as a block of text. As such, it does not do any JSON interpretation of that text. Notice in the output text, the data inside `message` is quoted:
```json
"message":"{\"headers\": {\"data-parse-format\": \"json\"}}"
```
To do this translation, you will need to add a `remap` transform:
```toml
[transforms.parse_message]
type = "remap"
inputs = ["log"]
source = ". |= parse_json!(.message)"
```
Then set up the input of `aliyun_sls` to come from `parse_message`.

**Comment by csh0101** [comment]
> Okay, I think I see what is going on. The `log` source is handling the whole line as a block of text. As such, it does not do any JSON interpretation of that text. Notice in the output text, the data inside `message` is quoted:
> 
> ```json
> "message":"{\"headers\": {\"data-parse-format\": \"json\"}}"
> ```
> 
> To do this translation, you will need to add a `remap` transform:
> 
> ```toml
> [transforms.parse_message]
> type = "remap"
> inputs = ["log"]
> source = ". |= parse_json!(.message)"
> ```
> 
> Then set up the input of `aliyun_sls` to come from `parse_message`.

OK. Last Night I saw the vrl remap for learning and I just want to know more about vector. And the morning , I aware what you means. Because I saw the first example of the vrl. so at this situation, the message is raw string but not json string ...

**Comment by csh0101** [comment]
Let me just 

> Okay, I think I see what is going on. The `log` source is handling the whole line as a block of text. As such, it does not do any JSON interpretation of that text. Notice in the output text, the data inside `message` is quoted:
> 
> ```json
> "message":"{\"headers\": {\"data-parse-format\": \"json\"}}"
> ```
> 
> To do this translation, you will need to add a `remap` transform:
> 
> ```toml
> [transforms.parse_message]
> type = "remap"
> inputs = ["log"]
> source = ". |= parse_json!(.message)"
> ```
> 
> Then set up the input of `aliyun_sls` to come from `parse_message`.

Let me try it ....
