### ISSUE TITLE
Vector Slowness When Building a Number of Varied VRL Programs

### ISSUE THREAD

**Issue by wmyre** [vectordotdev/vector#19222]
### Discussed in https://github.com/vectordotdev/vector/discussions/19221

<div type='discussions-op-text'>

<sup>Originally posted by **wmyre** November 22, 2023</sup>
How does Vector's compiler of VRL scripts function entirely? For example, does Vector perform some kind of caching of compiled scripts in its data directory for quicker reloads, and is this sort of compiler functionality documented anywhere? I do understand that vector builds its topology based on the entirety of the configuration, but it seems like the builders performance diminishes severely when it has to compile VRL scripts. </div>

Vector does not appear to have any capability of holding stateful information of previously compiled VRL scripts which get used in transforms. This makes Vector extremely slow in building its topology when running in complex, full-ETL environments where custom VRL scripts are in place for over 100 different transformations. This is an extremely limiting feature of Vector unless I am missing something that will drastically improve the speed of Vector during hot-reloads of complex transformation configurations. It takes at least an hour for vector to finish building the topology with custom VRL transformation's in a Docker container for ~100 VRL scripts in v0.31.x-v0.34.x. 

It'd be nice to pre-compile VRL scripts or something to eliminate this burden.

**Comment by bruceg** [comment]
The VRL "compiler" transforms the VRL programs into parse trees, which it then verifies semantically and later executes by walking the trees. No pre-compilation or caching of the parsed programs are done.

In our experience, this process happens very quickly for the types of programs we have been developing with, even for relatively long ones. The fact that you are seeing it take over 30 seconds to parse each script suggests something else is going on here. How long are the scripts you are working with?

**Comment by wmyre** [comment]
> The VRL "compiler" transforms the VRL programs into parse trees, which it then verifies semantically and later executes by walking the trees. No pre-compilation or caching of the parsed programs are done.
> 
> In our experience, this process happens very quickly for the types of programs we have been developing with, even for relatively long ones. The fact that you are seeing it take over 30 seconds to parse each script suggests something else is going on here. How long are the scripts you are working with?

Thank you for the response. The length of scripts vary between a few lines of code to > 1,500 lines of code. Now that you brought it up, it does appear code length has a significant impact on build performance. 

One of the scripts, which is 1,378 lines of code, took 7 minutes 15 seconds to build, based on timestamps between builds.
```
2023-11-27T14:53:44.456184Z DEBUG vector::topology::builder: Building new transform. component=omitted
2023-11-27T15:00:59.699916Z DEBUG vector::topology::builder: Building new transform. component=omitted_two
```

Additionally, we noticed the topology doesn't begin building for over 20 minutes after the following (secret placeholder) log is emitted (is this when it begins building everything into parse trees, perhaps?): 

```
2023-11-27T14:16:43.748007Z DEBUG vector::config::loading: No secret placeholder found, skipping secret resolution.
2023-11-27T14:40:34.739105Z DEBUG vector::topology::builder: Building new source. component=metrics
```

**Comment by bruceg** [comment]
> One of the scripts, which is 1,378 lines of code, took 7 minutes 15 seconds to build, based on timestamps between builds.

This is an excellent data point, thank you for the clarification. It is still puzzling to us, though. That would imply that the VRL took over 300ms to parse each line of code, which is pretty difficult to swallow and again definitely does not correlate with our experience. Do these scripts contain large numbers of complex regex patterns, by any chance? That is one explanation that is being floated, as that library can potentially take a long time to compile complex patterns.

We are also considering the possibility that there is a non-linear factor involved in parsing. If you, say, drop or add a dozen lines from the largest script, does its parse time change significantly?

As to your original question, since the current internal format is effectively just a parse tree, it does not lend itself to saving to disk in a format that would be significantly more optimal than just parsing the text again… assuming there are no issues as described above.

**Comment by wmyre** [comment]
> > One of the scripts, which is 1,378 lines of code, took 7 minutes 15 seconds to build, based on timestamps between builds.
> 
> This is an excellent data point, thank you for the clarification. It is still puzzling to us, though. That would imply that the VRL took over 300ms to parse each line of code, which is pretty difficult to swallow and again definitely does not correlate with our experience. Do these scripts contain large numbers of complex regex patterns, by any chance? That is one explanation that is being floated, as that library can potentially take a long time to compile complex patterns.
> 
> We are also considering the possibility that there is a non-linear factor involved in parsing. If you, say, drop or add a dozen lines from the largest script, does its parse time change significantly?
> 
> As to your original question, since the current internal format is effectively just a parse tree, it does not lend itself to saving to disk in a format that would be significantly more optimal than just parsing the text again… assuming there are no issues as described above.

We will continue using the script that has 1,378 lines of code to figure this out. In that script, there are no complex regex expressions. There's a number of O(1) statements as well as a number of for_each statements. Additionally there's a number of usages for the `parse_timestamp()` function and `format_timestamp()` function. Which the format_timestamp to me could be a potential culprit of slowness, but it is the only thing I can tell that could logically be resource consuming.

Additionally we did try something out on another script which is 844 lines of code that took 40-50 seconds to parse. We removed a nested for_each loop which consisted of lines 258-842 and that dropped the parsing time to 2-3 seconds, quite a difference! 

This is a bit of a head scratcher for all of us, yay! I did spin up my own vector dev environment last night and stepped through the code to try and identify what method the slowness begins at to help figure out the performance problem here, but the source code is of course very complex and I'm still a bit of a noob with Vector's architecture. I did identify that the ConfigBuilderLoader is potentially being instantiated twice, which may be contributing to the slowness, as in app.rs, `config::init_log_schema` and  `config::load_from_paths_with_provider_and_secrets` both get called and both of them call the loader method `load_builder_from_paths()`, thus potentially doubling the parsing time, however I could be totally wrong here, but wanted to point it out... 

If you could provide me some good debugging break points to monitor slowness at, or a good way of debugging these vrl's parsing, I can certainly assist better in figuring this potential performance problem out that we are running in to.

**Comment by bruceg** [comment]
For digging into the speed of parsing VRL, you would need to work within the [vrl repository](https://github.com/vectordotdev/vrl). I would start with cloning that repository, extracting one of the scripts to a file, and run `cargo run --package vrl-cli -- --program FILENAME < /dev/null`. This will build and run the script and then exit. I would start by stepping through `fn parse` in `src/parser/mod.rs`.

If you can post one of the expensive scripts somewhere, we could take a look to see if anything stands out to us as well.

**Comment by jszwedko** [comment]
> In this case, the parent component seems to be rebuilt for each child component.

This would be interesting. What leads you to believe this is the case?

**Comment by jszwedko** [comment]
Gotcha, yeah, I think I see it. For a component with `remap` inputs it ends up compiling the VRL for all input components to make sure the output schema matches the input schema of the component: https://github.com/vectordotdev/vector/blob/5a6b670ce05cc7c34b0af0cf2a58810d47b2f71c/src/transforms/remap.rs#L221-L329

I think a change here _might_ be to have Vector build the components in graph order so that `first` would be built earlier and then it the call to `outputs` wouldn't need to be recompile it.

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/20555
