### ISSUE TITLE
Dual shipping with datadog agent

### ISSUE THREAD

**Issue by lkoniecz** [vectordotdev/vector#19233]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Datadog agent supports [dual shipping](https://docs.datadoghq.com/agent/configuration/dual-shipping/).
This is supported by [victoria-metrics](https://docs.victoriametrics.com/#sending-metrics-to-datadog-and-victoriametrics) for instance, however vector does not seem to be compliant with DD ingest API

```
2023-11-24 06:12:24 UTC | CORE | ERROR | (comp/forwarder/defaultforwarder/worker.go:194 in process) | Too many errors for endpoint 'http://vector-metrics:8282/api/v1/check_run': retrying later
2023-11-24 06:12:24 UTC | CORE | ERROR | (comp/forwarder/defaultforwarder/worker.go:194 in process) | Too many errors for endpoint 'http://vector-metrics:8282/api/v2/series': retrying later
2023-11-24 06:12:39 UTC | CORE | ERROR | (comp/forwarder/defaultforwarder/worker.go:194 in process) | Too many errors for endpoint 'http://vector-metrics:8282/api/v1/check_run': retrying later
2023-11-24 06:12:39 UTC | CORE | ERROR | (comp/forwarder/defaultforwarder/worker.go:194 in process) | Too many errors for endpoint 'http://vector-metrics:8282/api/v2/series': retrying later
```

Is there a plan for supporting that?

I know I can push the metrics from datadog to vector thru a https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml#L588 but this would redirect sending all metrics.

### Configuration

following property set in datadog agent configuration
```text
`DD_ADDITIONAL_ENDPOINTS` set to http://me-vector-hostname:8282
```

### Version

vector 0.34.1 (x86_64-apple-darwin 86f1c22 2023-11-16 14:59:10.486846964)

### Example Data

N/A

### Additional Context

N/A

**Comment by bruceg** [comment]
I'm not entirely clear what it is you are trying to accomplish, as there appear to be multiple difficulties here. Please clarify what the desired usage of Vector would be.

While the sinks themselves will only send the events to a single destination, Vector does support shipping any stream of events to any number of destinations. Simply add another sink consuming the same inputs and it will clone the events as needed.

If Vector is unable to send metrics to the Datadog metrics endpoint of Victoria metrics, I would expect there to be some subtle difference between the protocol expected by that and the live Datadog metrics endpoint that is causing problems there.

**Comment by jszwedko** [comment]
Just to clarify, Vector doesn't work with the `additional_endpoints` Agent configuration. Instead, you can see https://vector.dev/docs/reference/configuration/sources/datadog_agent/#configuring-the-datadog-agent for how to configure the Agent to forward to Vector.

I'll close this out, but let us know if you have any troubles with that.
