### ISSUE TITLE
Systemd Unit File gets overwritten upon package upgrade

### ISSUE THREAD

**Issue by dariosusman** [vectordotdev/vector#19251]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We're using the TOML configuration file syntax yet with vector. For that, I've reconfigured the systemd unit file to take this configuration. However, when the package is updated/upgraded, the systemd unit file gets replaced by the default from the package. If I set it to immutable, the package upgrade process fails (which makes total sense).

However, if either the systemd file unit or a configuration file (in /etc/vector/*) is different to what the package expects, these shouldn't be overwritten. Specially since in your documentation you recommend to reconfigure the start-up scripts to accomodate to a desired effect.

Thank you.

Best regards,
Dario Susman

### Version

0.34.1

### Example Data

This is the modified systemd unit file:

```[Unit]
Description=Vector
Documentation=https://vector.dev
After=network-online.target
Requires=network-online.target

[Service]
User=vector
Group=vector
ExecStartPre=/usr/bin/vector validate --config-toml /etc/vector/vector.toml
ExecStart=/usr/bin/vector --config /etc/vector/vector.toml
ExecReload=/usr/bin/vector validate --config-toml /etc/vector/vector.toml
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
AmbientCapabilities=CAP_NET_BIND_SERVICE
EnvironmentFile=-/etc/default/vector
# Since systemd 229, should be in [Unit] but in order to support systemd <229,
# it is also supported to have it here.
StartLimitInterval=10
StartLimitBurst=5
[Install]
WantedBy=multi-user.target```

### Additional Context

Running on Debian Bookworm

### References

_No response_

**Comment by bruceg** [comment]
The [standard pattern](https://askubuntu.com/questions/659267/how-do-i-override-or-configure-systemd-services) for systemd unit files is to install the stock unit file in a location that may be read-only, and then administrators can copy that into `/etc` to make changes to it. I recommend you do so to keep your changes persistent across upgrades.

If our documentation says that you should modify the script in-place, then I agree that point could use clarification. I am not, however, finding the reference you would be looking at for that. Could you provide a link to where you found instructions like that?

**Comment by bruceg** [comment]
Thanks for the follow up, @dariosusman. I'm glad you got it working. The `systemctl edit` function is new to me too, and is very handy for just this purpose.
