### ISSUE TITLE
Automatically post a picture with plotted benchmarking results by `/bench` command in PR discussion

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#1927]
I thought it would be cool to have this, in addition to test harness. Benches should be more accurate for measuring performance optimizations. We should provide an easy way to pull the results and integrate them into our PR review loop.

**Comment by Hoverbear** [comment]
Criterion supports this! https://bheisler.github.io/criterion.rs/book/user_guide/plots_and_graphs.html

**Comment by jszwedko** [comment]
Closing as out-of-date. The soak framework does post comments on each PR and there are plots available as assets on each CI run.
