### ISSUE TITLE
how to add increment count by VRL 

### ISSUE THREAD

**Issue by lhgwoo2** [vectordotdev/vector#19341]
Hi.
We want to publish auto increment number in the log.
Using lua transform, we were able to publish increasing number fields by log.
but such functions are not identified in remap transform.

Ask how to implement that logic using remap.

example.

hooks.init = "function (emit)\ncount=0\nend"
hooks.process = "function (event, emit)\ncount = count+1\nevent.log.sequenceno = count\n\temit(event)\nend"

**Comment by zamazan4ik** [comment]
I guess this feature request is blocked by https://github.com/vectordotdev/vector/issues/19246

**Comment by jszwedko** [comment]
Agreed, this feature request is blocked by https://github.com/vectordotdev/vector/issues/19246.
