### ISSUE TITLE
k8s vector Unable to collect journald logs

### ISSUE THREAD

**Issue by junlintianxiazhifulinzhongguo** [vectordotdev/vector#19382]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

**Vector deployment method: Agent**

**In k8s, system service logs were collected through Journald. The vector container did not output any output, nor did it create a corresponding topic in my Kafka. There was no problem with the Kafka service, and it was determined that the vector did not read the relevant Journald system service logs. The image version is: Timberio/Vector: Nightly Debian**

**In k8s, system service logs were collected through Journald without any output or creation of corresponding topics in my Kafka. The Kafka service was fine and it was determined that the vector did not read the relevant Journald system service logs，Regardless of whether pods are added or removed at relevant nodes**

**The initial version used was this one: timberio/vector:0.34.1-distroless-libc, but this version has many issues, requiring additional files to be mounted and missing corresponding commands and library files. Therefore, the latest version of the image used for this test is： timberio/vector:nightly-debian**

### Configuration

```text
data_dir: /vector-data-dir
api:
  enabled: true
  address: 127.0.0.1:8686
  playground: false
sources:
  journald_source:
    type: journald
    batch_size: 16
    current_boot_only: true
    include_matches:
      _SYSTEMD_UNIT:
        - kubelet.service
        - containerd.service
sinks:
  kafka_kubernetes_logs_node_journald:
    type: kafka
    inputs: [journald_source]
    bootstrap_servers: maize95-broker-headless.kafka.svc.cluster.local:9092
    compression: none
    headers_key: headers
    key_field: user_id
    librdkafka_options:
      client.id: rdkafka
      socket.send.buffer.bytes: "100"
    message_timeout_ms: 300000
    socket_timeout_ms: 60000
    topic: vector-k8s-log-node-journald
    encoding:
      codec: json
```

### Version

timberio/vector:nightly-debian

### Debug Output

```text
2023-12-14T15:15:22.468871026+08:00 2023-12-14T07:15:22.468665Z  INFO vector::app: Log level is enabled. level="info"

2023-12-14T15:15:22.471197805+08:00 2023-12-14T07:15:22.471012Z  INFO vector::app: Loading configs. paths=["/etc/vector"]

2023-12-14T15:15:22.528377181+08:00 2023-12-14T07:15:22.527904Z  INFO vector::topology::running: Running healthchecks.

2023-12-14T15:15:22.532216782+08:00 2023-12-14T07:15:22.532107Z  INFO vector: Vector has started. debug="false" version="0.35.0" arch="x86_64" revision="07cdf75 2023-12-14 04:03:13.923883865"

2023-12-14T15:15:22.544851656+08:00 2023-12-14T07:15:22.544657Z  INFO vector::internal_events::api: API server running. address=127.0.0.1:8686 playground=off

2023-12-14T15:15:22.557181323+08:00 2023-12-14T07:15:22.556924Z  INFO source{component_kind="source" component_id=journald_source component_type=journald}: vector::sources::journald: Starting journalctl.

2023-12-14T15:15:22.594789074+08:00 2023-12-14T07:15:22.594499Z  INFO vector::topology::builder: Healthcheck passed.
```

### Additional Context

k8s: v1.26.5
vector chart: 0.29.0
containerd: v1.7.3
linux:  Anolis OS 8.8
kernel:  4.19.91-27.an8.x86_64

**Comment by jszwedko** [comment]
Hi @junlintianxiazhifulinzhongguo ,

When running the journald source within a container to consume logs on the host, you need to mount in the journald journal files. This is touched on in this issue: https://github.com/vectordotdev/vector/issues/5225. The need for this is what prompted the addition of the [journal_directory](https://vector.dev/docs/reference/configuration/sources/journald/#journal_directory) option to configure where to find the journald files.

Without mounting it'll try to consume the journald files from within the container, of which there probably won't be any.

**Comment by junlintianxiazhifulinzhongguo** [comment]
@jszwedko Thank you，issue resolved。
The complete configuration is as follows：
```
data_dir: /vector-data-dir
api:
  enabled: true
  address: 127.0.0.1:8686
  playground: false
sources:
  journald_source:
    type: journald
    batch_size: 16
    current_boot_only: true
    journal_directory: /var/log/journal
    include_matches:
      _SYSTEMD_UNIT:
        - kubelet.service
        - containerd.service
      _TRANSPORT:
        - kernel
```
