### ISSUE TITLE
thread 'vector-worker' panic at failing parse_grok function

### ISSUE THREAD

**Issue by henrywiechert** [vectordotdev/vector#19384]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Error message:
`thread 'vector-worker' panicked at 'internal error: entered unreachable code: join error or bad poll', src/topology/builder.rs:901:30`

With a non-standard log input like this (stdin):

  `"/volume/LongFileNameLongFileName.hpp:42 Some Text:[0,0]"`

which is parsed by this remap VRL function (which was intended to match "/path/file.cpp[42] ..."):

  `data, error = parse_grok!(.message, "%{PATH:srcfile}\\[%{NUMBER:srcline}\\] %{GREEDYDATA:specific_msg}")`

The VRL function should fail, but not panic.

### Configuration

```text
[sources.in]
type = "stdin"

[transforms.vector_bug1]
inputs = ["in"]
type = "remap"
source = '''
    data = parse_grok!(.message, "%{PATH:srcfile}\\[%{NUMBER:srcline}\\] %{GREEDYDATA:specific_msg}")
    . = merge(., {
        "srcfile": data.srcfile,
        "srcline": data.srcline,
        "specific_msg": data.specific_msg,
    })
'''

[sinks.json_output]
inputs = ["vector_bug1"]
encoding.codec = "json"
type = "console"
```

### Version

vector 0.34.0

### Debug Output

```text
https://gist.github.com/henrywiechert/62cc6f1baa86a58c1159b18cf681bbf4
```

### Example Data

Stripped down input data, that still generates the panic is shown below. Seems two aspects are relevant.
- the length of the path/file name (issue not happen with shorter path/file names)
- having the square brackets at the "unexpected" position

Input data:
`/volume/LongFileNameLongFileName.hpp:42 Some Text:[0,0]`

**Comment by jszwedko** [comment]
Hi @henrywiechert ! I think this is the same issue as https://github.com/vectordotdev/vector/issues/15199. I'll close it as a duplicate. It shouldn't panic, and instead return an error, but unfortunately the panic is within a library we use. You can see https://github.com/kkos/oniguruma/issues/143 for what this error indicates (basically it had to retry matching too many times).
