### ISSUE TITLE
CLI help message doesn't match argument order requirements for `validate`

### ISSUE THREAD

**Issue by jmagnuson** [vectordotdev/vector#19401]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I am in the process of migrating vector `0.31.0` to `0.34.1`, and currently use a systemd service file based on the [one](https://github.com/vectordotdev/vector/blob/master/distribution/systemd/vector.service) in tree. Since I want to continue using the existing `/etc/vector/vector.toml` config, I attempted to include the explicit argument `--config-toml` to the service invocations. Based on usage:

```
# /usr/bin/vector -h
Usage: vector [OPTIONS] [COMMAND]
```

I would have expected this to work:

```
# /usr/bin/vector --config-toml /etc/vector/vector.toml validate
2023-12-16T17:13:56.620987Z ERROR vector::config::loading: Config file not found in path. path="/etc/vector/vector.yaml"
```

However, I ended up guessing that the sub-command and argument order mattered, and attempted the reverse with success:

```
# /usr/bin/vector validate --config-toml /etc/vector/vector.toml
√ Loaded ["/etc/vector/vector.toml"]
√ Component configuration
√ Health check "devnull"
------------------------------------
                           Validated
```

It seems that either the help message should be reworded to reflect the order requirements, or if possible the CLI parser should just become agnostic to order. I haven't dug deep enough to know if there are sub-command specific options, which may complicate this.

### Version

vector 0.34.1-custom-86f1c22d7f (aarch64-unknown-linux-gnu debug=full)

### Additional Context

cargo build options (in yocto recipe):
```
CARGO_BUILD_FLAGS:append = "--no-default-features \
    --features='sources-journald,\
    sources-host_metrics,\
    transforms-dedupe,\
    transforms-remap,\
    transforms-filter,\
    transforms-throttle,\
    sinks-elasticsearch,\
    sinks-influxdb,\
    sinks-loki,\
    sinks-aws_s3,\
    sinks-http,\
    sinks-file,\
    sinks-console,\
    sinks-vector,\
    sinks-redis,\
    sinks-blackhole,\
    api,\
    api-client'\
"
```

**Comment by jszwedko** [comment]
This trips me up too. Some options are "global" options while others are options for the subcommand. We have https://github.com/vectordotdev/vector/issues/12242 open to audit this and make it more consistent so I think we can loop this issue into that one. Thanks for raising @jmagnuson !
