### ISSUE TITLE
Vector VRL Playground broken

### ISSUE THREAD

**Issue by nielslammers** [vectordotdev/vector#19442]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

https://playground.vrl.dev/ is broken since a few days.
When clicking 'Run program' web development console shows:

```
Uncaught RuntimeError: unreachable executed
    run_vrl https://playground.vrl.dev/pkg/vector_vrl_web_playground.js:131
    handleRunCode https://playground.vrl.dev/index.js:213
    onclick https://playground.vrl.dev/:1
[vector_vrl_web_playground_bg.wasm:3894496:1](https://playground.vrl.dev/pkg/vector_vrl_web_playground_bg.wasm)
    <anonymous> https://playground.vrl.dev/pkg/vector_vrl_web_playground_bg.wasm:3894496
    <anonymous> https://playground.vrl.dev/pkg/vector_vrl_web_playground_bg.wasm:4053299
    <anonymous> https://playground.vrl.dev/pkg/vector_vrl_web_playground_bg.wasm:3826283
    <anonymous> https://playground.vrl.dev/pkg/vector_vrl_web_playground_bg.wasm:4005015
    <anonymous> https://playground.vrl.dev/pkg/vector_vrl_web_playground_bg.wasm:2859481
    <anonymous> https://playground.vrl.dev/pkg/vector_vrl_web_playground_bg.wasm:2590359
    <anonymous> https://playground.vrl.dev/pkg/vector_vrl_web_playground_bg.wasm:2586694
    <anonymous> https://playground.vrl.dev/pkg/vector_vrl_web_playground_bg.wasm:3277361
    <anonymous> https://playground.vrl.dev/pkg/vector_vrl_web_playground_bg.wasm:959482
    run_vrl https://playground.vrl.dev/pkg/vector_vrl_web_playground.js:131
    handleRunCode https://playground.vrl.dev/index.js:213
```

Checked on Chrome and Firefox, using different internet connections as well.

### Version

https://github.com/vectordotdev/vector/tree/5ef73ee665a395af23deb93a8138038745038c92

**Comment by dsmith3197** [comment]
The error is specifically related to the following line.
```
.timestamp = now()
```

Note that the playground works for programs that do not include the `now()` function, which we will look in to. Please let us know if there are other programs for which the playground errors.

**Comment by jszwedko** [comment]
I narrowed it down to this VRL commit: https://github.com/vectordotdev/vrl/commit/797e4e765c9cda88a6396d98d373388b5c45a51e . It looks like the `wasm-bindgen` and `js-sys` chrono features were accidentally dropped since we were including them transitively through the syslog_loose crate rather than explicitly specifying them in VRL's Cargo.toml.

**Comment by jszwedko** [comment]
Opened https://github.com/vectordotdev/vrl/pull/605 to fix.
