### ISSUE TITLE
Expose prometheus exporter, remote_write related configs

### ISSUE THREAD

**Issue by suikammd** [vectordotdev/vector#19517]
Hi, I write a control service to auto generate Vector config toml. But some prometheus related config not exposed.

I want know if it ok to expose those configs? If ok, I will submit a pr to do so.

**Comment by StephenWakely** [comment]
Can you expound a bit more about which config options you need?

**Comment by suikammd** [comment]
> Can you expound a bit more about which config options you need?

PrometheusExporterConfig for now

**Comment by suikammd** [comment]
@StephenWakely hi, do your team think it's ok to expose this config PrometheusExporterConfig?

**Comment by StephenWakely** [comment]
What do you mean by "expose"? It's not quite clear to me what your use case is. Are you importing Vector as a library into another project?

**Comment by suikammd** [comment]
Yes, I import vector as a library.

**Comment by suikammd** [comment]
> Yes, I import vector as a library.

https://github.com/vectordotdev/vector/blob/aa6fd40ae9fda3279cbfd4f4ec3bdbb7debde691/src/sinks/prometheus/mod.rs#L6
change from `pub(crate)` to `pub`

**Comment by StephenWakely** [comment]
Yes, this would be fine. Would you like to submit a PR?

**Comment by suikammd** [comment]
I submit the PR and I also pub remote_write. You may check the PR. thx! @StephenWakely
