### ISSUE TITLE
kubernetes_logs source randomly dropping some logs (~ 50% drop in number of events) 

### ISSUE THREAD

**Issue by umakarnati** [vectordotdev/vector#19547]
### Problem

kubernetes_logs source randomly dropping some logs (almost 50% in number of event)    This problem seems happening  especially in  pods( these are backend java services)  where we see very high log volume  for other pods it works fine.  Could you please suggest  any solution to fix this issue.

Here is agent config and we are using vector version 0.33.0-alpine and we dont see any errors in vector logs.

##Configuration:
apiVersion: v1
data:
  vector.yaml: |-
    data_dir: "/vector-data-dir"
    sources:
      k8slogs:
        type: kubernetes_logs

Before migrating to vector  we were using datadog-agent to collect the logs.  Here is the chart that shows  number of logs events that beings sent to data dog before and after vector migration .. after deploying vector on Dec 12  there is clear drop in number of log events.

Data dog ingestion rate:

<img width="1194" alt="Screenshot 2024-01-08 at 9 45 31 AM" src="https://github.com/vectordotdev/vector/assets/88678165/471bc0ad-5898-407a-8691-f08004a9c273">

k8s source rate : 

<img width="1548" alt="Screenshot 2024-01-08 at 10 17 26 AM" src="https://github.com/vectordotdev/vector/assets/88678165/bdf61567-97d2-4658-aea6-dcdbf7320c3b">

### Version

0.33.0-alpine

**Comment by umakarnati** [comment]
using glob_minimum_cooldown_ms: 500 from default 1000 .helped to fix the issue.

    sources:
      k8slogs:
        type: kubernetes_logs
        glob_minimum_cooldown_ms: 500

**Comment by jszwedko** [comment]
Gotcha, it seems likely that files were being rotated before Vector could start tailing them then. I'll close this out since the behavior is "expected" albeit could be improved. I think using inotify is probably the simplest way to improve the tailing behavior. https://github.com/vectordotdev/vector/issues/5089 is tracking that.

**Comment by stickyb1t** [comment]
I encountered the same problem. I solved this problem by increasing max_read_bytes in kubernetes source to 32768 bytes.
