### ISSUE TITLE
Sources need a context parameter, similar to sinks and transforms

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#1954]
Similar to #1839, sinks also need to be passed a context object that contains the custom DNS resolver, global options, and new context items coming down the pipe (#1917 shutdown triggers).

The updated trait should look like:
```rust
trait SourceConfig: core::fmt::Debug {
    fn build(&self, cx: SourceContext) -> crate::Result<sources::Source>;
        name: &str,
        globals: &GlobalOptions,
        out: mpsc::Sender<Event>,
    ) -> crate::Result<sources::Source>;

    fn output_type(&self) -> DataType;

    fn source_type(&self) -> &'static str;
}
```

The new `SourceContext` struct should wrap all the old parameters, and add a `resolver` function like `SinkContext` does.

Also ref #1307 #827

**Comment by Hoverbear** [comment]
This is related to #1769 as well since this configuration would be in them!

**Comment by Hoverbear** [comment]
I'd be happy to pick this up if noone else wants. It's lots of tedious finnicky details. :)

**Comment by binarylogic** [comment]
Go for it. @bruceg does that work or were you planning to do this? Is your work blocked otherwise?

**Comment by bruceg** [comment]
I stumbled over it while trying to use our existing HTTPS client support (in the sinks) in the GCP pubsub source. I can work around it, but the result will need to be fixed up for this at some point.

**Comment by Hoverbear** [comment]
I worked on this a bit and have a clear picture how to do it. If anyone wants to take this on instead, just let me know. :)

**Comment by MOZGIII** [comment]
I took care of it cause I needed it for my k8s work: #2557.

**Comment by jszwedko** [comment]
This does exist now.
