### ISSUE TITLE
`all_metrics` field not recognized in `log_to_metric` transform

### ISSUE THREAD

**Issue by johnguirgis** [vectordotdev/vector#19625]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Vector does not seem to be recognizing the `all_metrics` field in the `log_to_metric` transform and gives an error upon its inclusion. 

### Configuration

```text
transforms:
  log_2_met:
    inputs:
      - kafka
    type: log_to_metric
    metrics: ignored
    all_metrics: true
```

### Version

vector 0.34.2 (x86_64-unknown-linux-gnu d685a16 2024-01-02 14:59:54.890517436)

### Debug Output

```text
2024-01-15T20:39:11.651266Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=info,rdkafka=info,buffers=info,lapin=info,kube=info"
2024-01-15T20:39:11.663282Z  INFO vector::app: Loading configs. paths=["kafka.yaml"]
2024-01-15T20:39:11.667084Z ERROR vector::cli: Configuration error. error=unknown field `all_metrics`, expected `metrics`
```

**Comment by a-patos** [comment]
+1

**Comment by jszwedko** [comment]
Hi @johnguirgis ! This was added in Vector v0.35.0. Do you mind trying that version instead? I'll close this out, but feel free to reopen if you hit the same error.

**Comment by a-patos** [comment]
i m in Vector v0.35.0. and i got same issues
