### ISSUE TITLE
Regex Capture named groups should be null

### ISSUE THREAD

**Issue by splitice** [vectordotdev/vector#19703]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Currently with `parse_regex` (and probably `parse_regexes`) an unmatched group matches as an empty string.

This is wasteful and creates problems should there be the need to match an empty capture vs not present capture (null)

### Configuration

```text
in VRL:
. = `parse_regex(.message, "^(abc: (?P<abc>[a-zA-Z]+))?")`
```

`.abc` will be `""` on an empty or non matching `.message`

### Version

0.26

### Debug Output

```text
-
```

### Example Data

-

### Additional Context

-

### References

-

**Comment by jszwedko** [comment]
Hi @splitice ,

This doesn't seem to be the case in the latest version of Vector, I see:

```

$ .message = "no match"
"no match"

$ . = parse_regex!(.message, r'^(abc: (?P<abc>[a-zA-Z]+))?')
{ "abc": null }
```

Can you try upgrading and seeing if it resolves the issue for you?

**Comment by splitice** [comment]
@jszwedko You might be right, we are a bit behind. Thank you for your response, hopefully I didnt waste your time. I'll confirm with latest in the coming days.

I recall we had some performance regressions but I can't recall the specifics (probably metrics). I think thats why we never moved to 0.27.x (performance regression).

I'll certainly give a newer version a try and test again.

**Comment by jszwedko** [comment]
👍 sounds good. I'll close this out but feel free to reopen if it doesn't resolve the issue for you.
