### ISSUE TITLE
VRL function to retrieve vector's configured/current IANA timezone name

### ISSUE THREAD

**Issue by klondikedragon** [vectordotdev/vector#19716]
As discussed in https://github.com/vectordotdev/vector/discussions/19685, it can be helpful in some situations for a (remote) sink to know the IANA timezone zone (e.g., `America/Chicago`) of the vector agent that is sending the data.

As one example use case, consider an http sink that receives data from vector that does work to parse/analyze unstructured text in the submitted data, and needs to disambiguate textual timestamps that do not have an explicit timezone.

While several approaches were discussed in https://github.com/vectordotdev/vector/discussions/19685, the simplest/cleanest short-term suggested approach is to add a new VRL function (e.g., `get_vector_timezone()`), so that this information could be added to the event data, and then recognized by the sink as needed.

If vector's [global timezone property](https://vector.dev/docs/reference/configuration/global-options/#timezone) is configured to be `local` (the default), then ideally this VRL function would retrieve the proper IANA timezone name from the host OS, or if that information isn't available, to return the offset of the local timezone encoded as a string instead (e.g., `-05:00`).

I'm opening this issue based on the contributing guidelines to discuss the enhancement, and if approved, will craft a PR for it.

**Comment by jszwedko** [comment]
Thanks for opening this to discuss further @klondikedragon ! We are in agreement that adding this function to VRL makes sense as an approach and so would be happy to see a PR for it.
