### ISSUE TITLE
Vector acks messages sent by S3 source even when delivery failed

### ISSUE THREAD

**Issue by tanushri-sundar** [vectordotdev/vector#19711]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I am sending messages from S3 to GCP PubSub using Vector. 

I have observed that messages rejected by the PubSub sink for non-retryable errors (ex: 400, 403) are dropped.

```
2024-01-18T21:35:42.649078Z ERROR vector_common::internal_event::component_events_dropped: Internal log [Events dropped] is being suppressed to avoid flooding.
```

The dropped messages are deleted from SQS, even with a DLQ configured on my SQS. 

I would expect that the SQS message not be deleted per Vector’s end-to-end-acknowledgement guarantee. 

----
**Expected behavior**:  Vector should delete messages in S3 only if delivery to the sink is successful. I have traced this issue back to the [S3 source code here](https://github.com/vectordotdev/vector/blob/53f97c1c61ca176ba20852d0cfc1e45e44cf2235/src/sources/aws_s3/sqs.rs#L611):

```
match result {
    BatchStatus::Delivered => Ok(()),
    BatchStatus::Errored => Err(ProcessingError::ErrorAcknowledgement),
    BatchStatus::Rejected => {
        // Sinks are responsible for emitting ComponentEventsDropped.
        // Failed events cannot be retried, so continue to delete the SQS source message.
        Ok(())
    }
```

The `BatchStatus::Rejected` case should call `Err(ProcessingError::ErrorAcknowledgement)`. 

This would allow failed messages to be DLQed, as the user can configure a DLQ on their SQS and set custom values for maximum retries and visibility timeout.

This fix could potentially be a configuration based approach, with a parameter such as `strict_ack = true` preventing Vector's overeager deletion.

### Version

0.33.0

### References

#14899 
#14708 
#10870

**Comment by jszwedko** [comment]
This is one of the issues intended to be addressed by https://github.com/vectordotdev/vector/pull/14708.

**Comment by tanushri-sundar** [comment]
@jszwedko I agree, this could definitely be solved by the RFC [#14708](https://github.com/vectordotdev/vector/pull/14708). A smaller scope fix for this particular source would be very helpful, and it could potentially be a low-touch code change. Since there isn't a timeline for implementing the RFC, perhaps starting with this fix can help unblock some users more quickly.

**Comment by jszwedko** [comment]
Yeah, after reflecting a bit I agree that this seems like a safe incremental change to make even in the context of that RFC. I'd be happy to see a PR for it if you like.

**Comment by tanushri-sundar** [comment]
@jszwedko That sounds great! I've opened PR #19748
