### ISSUE TITLE
Vector OS repositories at `repositories.timber.io` were decommissioned on February 28th

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#19713]
These repositories were deprecated during the v0.34.0 release of Vector and replaced with repositories at `apt.vector.dev` and `yum.vector.dev`. v0.35.0 was only published to the new repositories.

Please see https://vector.dev/highlights/2023-11-07-new-linux-repos/ for details and leave a comment here if you have any issues migrating.

**Comment by pavel-elkin-klarna** [comment]
Hey everyone! It looks like the rpm repo has a wrong redirect without a trailing slash `https://yum.vector.dev/stable/vector-0`, when this `https://yum.vector.dev/stable/vector-0/` works correctly. 

In the sense that if you choose a basearch, the former linkr redirects to `https://yum.vector.dev/stable/x86_64/`, and the latter - to `https://yum.vector.dev/stable/vector-0/x86_64/`

**Comment by jszwedko** [comment]
Hi @pavel-elkin-klarna !

Thanks for the comment! I'm not able to reproduce this though. The yum config seems to work with and without a trailing `/`. For example, this works:

```
[vector]
name = Vector
baseurl = https://yum.vector.dev/stable/vector-0/$basearch
enabled=1
gpgcheck=1
repo_gpgcheck=1
priority=1
gpgkey=https://keys.datadoghq.com/DATADOG_RPM_KEY_CURRENT.public
       https://keys.datadoghq.com/DATADOG_RPM_KEY_B01082D3.public
       https://keys.datadoghq.com/DATADOG_RPM_KEY_FD4BF915.public
```

Does that not work for you?

**Comment by pavel-elkin-klarna** [comment]
Hi @jszwedko! Yes, this way it indeed works. The way we stumbled upon it is maybe a weird use case - we added this repo to artifactory to cache the packages. I added the url without the basearch: ""https://yum.vector.dev/stable/vector-0" so the users of this artifactory repo can use any architecture. I tried this url with and without trailing slash and artifactory in both cases doesn't see vector packages. And I see the same behaviour just opening this url in the browser.

**Comment by jszwedko** [comment]
@pavel-elkin-klarna Sorry, I think I'm still missing something 😓 What do you expect https://yum.vector.dev/stable/vector-0 to redirect to?

**Comment by pavel-elkin-klarna** [comment]
That's a fair question, I'll try to find which url artifactory requests. I suspect it's repository metadata. For what it's worth, the old artifactory url worked without basearch like this: "https://repositories.timber.io/public/vector/rpm/amzn/2"

**Comment by jszwedko** [comment]
Hmm, that link is giving me a 404 (the old repositories are still active at the moment). Maybe Artifactory is appending to it?

**Comment by pavel-elkin-klarna** [comment]
It most probably does, the way clients use it is `<artifactory url>/$basearch`. And with the timberio repo artifactory finds the right `repomd` folder with all vector packages and with the new one somehow it doesn't. I'll add the request it makes when I find it..

**Comment by pavel-elkin-klarna** [comment]
I believe it's this feature we're using https://jfrog.com/help/r/jfrog-artifactory-documentation/set-up-remote-rpm-repositories

**Comment by pavel-elkin-klarna** [comment]
Not an artifactory expert, so sorry for being vague.

**Comment by jszwedko** [comment]
Thanks! And no worries. I'm also not very familiar with Artifactory so we may have to wait for someone with more knowledge to describe what the upstream repository needs to do to be compatible. Thanks for noting it though!

**Comment by pavel-elkin-klarna** [comment]
We deleted artifactory metadata and now everything works! I guess it was trying to query the new repo with the old metadata.

**Comment by rnhurt** [comment]
I'm getting a 404 when trying to install Vector on an fresh new AWS Amazon Linux 2023 EC2 instance.  However, I can pull that URL using `curl` and it works just fine.

```
repo: downloading from remote: vector
error: Status code: 404 for https://yum.vector.dev/stable/vector-0/\x86_64/repodata/repomd.xml (IP: 13.32.208.8) (https://yum.vector.dev/stable/vector-0/\x86_64/repodata/repomd.xml).:-- ETA
error: Status code: 404 for https://yum.vector.dev/stable/vector-0/\x86_64/repodata/repomd.xml (IP: 13.32.208.8) (https://yum.vector.dev/stable/vector-0/\x86_64/repodata/repomd.xml).
error: Status code: 404 for https://yum.vector.dev/stable/vector-0/\x86_64/repodata/repomd.xml (IP: 13.32.208.8) (https://yum.vector.dev/stable/vector-0/\x86_64/repodata/repomd.xml).
error: Status code: 404 for https://yum.vector.dev/stable/vector-0/\x86_64/repodata/repomd.xml (IP: 13.32.208.8) (https://yum.vector.dev/stable/vector-0/\x86_64/repodata/repomd.xml).
Vector                                                                                                                                                        3.1 kB/s | 313  B     00:00
Errors during downloading metadata for repository 'vector':
  - Status code: 404 for https://yum.vector.dev/stable/vector-0/\x86_64/repodata/repomd.xml (IP: 13.32.208.8)
Error: Failed to download metadata for repo 'vector': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

**Comment by jszwedko** [comment]
Hi @rnhurt!

It looks like there may be an extra `\` in there:

```
https://yum.vector.dev/stable/vector-0/\x86_64/repodata/repomd.xml
```

should be

```
https://yum.vector.dev/stable/vector-0/x86_64/repodata/repomd.xml
```

Could you share the yum configuration? Did you use `CSM_MIGRATE=true bash -c "$(curl -L https://setup.vector.dev)"` to create it? Or did you manually edit the files?

**Comment by rnhurt** [comment]
> Hi @rnhurt!
> 
> It looks like there may be an extra `\` in there:
> 
> ```
> https://yum.vector.dev/stable/vector-0/\x86_64/repodata/repomd.xml
> ```
> 
> should be
> 
> ```
> https://yum.vector.dev/stable/vector-0/x86_64/repodata/repomd.xml
> ```

OMG! You are correct.  I am using Ansible for my server configuration and I just copied the `baseurl` straight out of the Vector migration page.  Of course, that section of the page with the `baseurl` is a HEREDOC and you have to escape the "$".  🤦

**Comment by jszwedko** [comment]
Closing this since the repos have been decommissioned for about a month at this point.
