### ISSUE TITLE
A case for runtime configuration: runtime adjustable log filtering

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#1973]
I've been thinking about I've been using logging systems in the past, and I realized I'd find a lot of use for something I've never see anywhere before: runtime configuration.

So, first, the context. Apps generate logs, and, in the usual case, the volume of those varies based on the "log level". I.e. there are very few logs at the `error` or `fatal` level, and there are very much logs at the `debug` and `trace` levels.
It's not uncommon to do the following: when doing troubleshooting, to turn on the `debug` log levels, while usually to just use `debug`. Typically we just change those settings at the app configuration.

Now, here's the problem. A change like this - a config change - is relatively expensive and difficult to do. It automatically means a container recreation in a container-based environment, and even in non-container based environments apps typically have to restart to apply new configs, as it usually makes very little sense to implement reloading them in runtime. Plus it's slow.

The alternative is set apps to always print all the logs (i.e. at a `debug` level) and filter them at the log aggregation agent or at the receiving end (i.e. at graylog or elasticsearch instance). The benefit of doing it on the receiving end is that there are usually really easy ways of configuring the filtering at runtime - a few clicks in the GUI you're already at. The downside is all the logs are transferred to the receiving end, and this yields high costs. Filtering at the log aggregation agent (that's us!) is better in that sense because logs can be filtered relatively cheaply before they get on the wire - thus saving costs. However, there's no way to easily alter vector settings at runtime currently.

It would be great if we could make vector poll settings from a central server instead of using the local ones, so that we one could build a nice GUI to change the settings (like switching the minimal log level to filter out, or change the glob for app module path filter).

Here's a couple of ways we could implement this at the configuration perspective:

1. Allow reloading the whole configuration from the remote end. The remote will then provide us with the whole config file or an equivalent to the whole config file.

2. Implement string substitution in the config values: for instance, local config file would have something like this:

   ```toml
   [transforms.my_transform_id]
     type = "drop_events"
     inputs = ["my-source-id"]
   [[transforms.my_transform_id.where_fields]]
     log_level = "{{remote.log_level_regexp}}"
   ```

   And the remote end would only have to output the kv pairs: `{"log_level_regexp": "(ERROR|INFO|WARN)"}`.

Both (1) and (2) have some downsides, but they're just to demonstrate some concrete ideas on what this would mean for us in practice.

On the remote end, we should allow everyone to implement the server vector that would be polling from. We could implement a plugin for Kibana to do provide users with an easy to use way of managing this when they already have an ELK stack, and even offer our own cloud service for those who don't, or want something more advanced!

P.S. This is probably a good candidate for an RFC.

**Comment by binarylogic** [comment]
Yes, I'd like to point out that this overlaps heavily with a future feature we've discussed, which is live interaction with Vector instances. It's more likely we'll lump this in with that.

General comments around app debug logs: I agree, and for traditional web server applications IO should be fine. But for other apps, this could severely affect performance.

**Comment by jszwedko** [comment]
Closing this in-lieu of a more focused issue: https://github.com/vectordotdev/vector/issues/17704
