### ISSUE TITLE
VRL early returns

### ISSUE THREAD

**Issue by mladedav** [vectordotdev/vector#19766]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

I would like to simplify my VRL transforms by returning early in case a fallible step ends.

### Attempted Solutions

It is possible to instead keep nesting `if` blocks but that is harder to read. One can also route events based on whether they can be parsed and then remap them in subsequent transforms. This can however duplicate expensive operations such as json parsing.

Something like this:
```
message, err = string(message)

if err != null {
  .parse_error = "Log line missing message"
  return
}
parsed, err = parse_json(message)
if err {
  .json_parse_error = err
  return
else {
  . = parsed
}

// continue processing logline
```

instead of

```
message, err = string(message)

if err != null {
  .parse_error = "Log line missing message"
} else {
  parsed, err = parse_json(message)
  if err {
    .json_parse_error = err
  else {
    . = parsed
    // continue processing logline
  }
}
```

### Proposal

Formally adding the `return` keyword. It is already reserved so I don't think this should break any code.

It can be a simple expression without any parameters which just returns `.`

In practice it would work the same way as `abort` except that instead of returning the original event, it would return the current value of `.` so I wouldn't expect the implementation to be complex either.

### Version

0.35.0

**Comment by jszwedko** [comment]
Thanks @mladedav . I think the use-case described here is the same as the one outlined in https://github.com/vectordotdev/vector/issues/7496 . Would you agree? Would https://github.com/vectordotdev/vector/issues/7496 cover your request as well?

**Comment by mladedav** [comment]
Yes, it does cover this. Sorry, I could not find that issue.

What can be done to drive this forward? I assume all changes to VRL need an RFC so that would be the next step?

Or is this something that probably wouldn't land anyway since the issue generated so little traction in three years?

**Comment by jszwedko** [comment]
I think the next step, as you noted, would be an RFC to think through the changes more. We are open to this change, just haven't had the motivation to do it ourselves yet. We'd be happy to help a contributor through the process though.

Given the other issue seems to cover this one too, I'll close this one. Let us know if you are interested in taking this forward!

**Comment by jszwedko** [comment]
(RFCs follow this format: https://github.com/vectordotdev/vector/blob/master/rfcs/README.md)
