### ISSUE TITLE
Vector is not able to discover EC2 nodes provisioned by Karpenter

### ISSUE THREAD

**Issue by marcustut** [vectordotdev/vector#19798]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I have an EKS cluster and initially the nodes are created with eksctl, but since there are scaling needs, I installed karpenter so it can spawn EC2 instances as nodes on demand.

However, the issue is that vector will not collect logs from these new nodes created by karpenter, it does still work for those previous initial nodes created by eksctl.

Any idea on this? So far I can’t seem to find the reason why

### Version

0.35.0

**Comment by joelp172** [comment]
Hi, did you find a resolution to this issue. I am facing the same problem.
