### ISSUE TITLE
Sandbox for VRL

### ISSUE THREAD

**Issue by KVahlin** [vectordotdev/vector#19824]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Introduction with VRL is too hard. It syntax is not obviously. 

### Attempted Solutions

Introduction with VRL is too hard. It syntax is not obviously. Sandbox with samples will be great. Because i have to modify transform section in docker-compose.yaml and restart containers -> update results in console. It is too hard and so long.

### Proposal

Simple sandbox with source field, field for modification with VRL code and auto updated result field. Perhaps, suggestions with errors or tips

**Comment by jszwedko** [comment]
Hey! There is actually a sandbox at `playground.vrl.dev`. Is that along the lines of what you are looking for?
