### ISSUE TITLE
Integration tests for `kafka` sink hang for Kafka 0.11.0.0

### ISSUE THREAD

**Issue by a-rodin** [vectordotdev/vector#1984]
We use the [latest](https://github.com/timberio/vector/blob/b22e4d39a60b3e35e605d1f3997c32e14886853d/docker-compose.yml#L495) version of [wurstmeister/kafka](https://hub.docker.com/r/wurstmeister/kafka) Docker image for the integration tests. Currently it corresponds to Kafka 2.12.

However, it turns out that the integration tests pass only for Kafka 2.x. Setting the version tag in `docker-compose.yml` to any version earlier than 2.x makes the integration tests hang.

Because Vector claims to support all versions of Kafka since 0.9, we need to fix this and potentially add integration tests using earlier versions of Kafka to CI.

**Comment by binarylogic** [comment]
I'd say this is high priority. To add to this, we should be erroring when an unsupported version is detected. I'm curious about general strategies around this. Ex: doing the same with Elasticsearch and so on.
