### ISSUE TITLE
Incorrect documentation for drop_on_abort default

### ISSUE THREAD

**Issue by kutzi** [vectordotdev/vector#19916]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The documentation for drop_on_abort suggests that the aborted event is send downstream per default.
However, in my experience drop_on_abort: true is already set per default
https://vector.dev/docs/reference/configuration/transforms/remap/#drop_on_abort
```
Drops any event that is manually aborted during processing.

Normally, if a VRL program is manually aborted (using [abort](https://vector.dev/docs/reference/vrl/expressions/#abort)) when processing an event, the original, unmodified event is sent downstream. In some cases, you may not wish to send the event any further, such as if certain transformation or enrichment is strictly required. Setting drop_on_abort to true allows you to ensure these events do not get processed any further.
```

### Configuration

```text
We're using this configuration. Leaving out drop_on_abort or specifying it as true, doesn't make any difference. Only if I specify false, aborted events are send downstream 
   drop_docker_service:
      type: "remap"
      drop_on_abort: true 
      inputs:
        - "journald"
      source: |
        if (exists(._SYSTEMD_UNIT) && ._SYSTEMD_UNIT == "docker.service") {
          abort
        }
```

### Version

Vector has started. debug="false" version="0.35.0" arch="x86_64" revision="e57c0c0 2024-01-08 14:42:10.103908779"

**Comment by jszwedko** [comment]
Thanks @kutzi . I opened https://github.com/vectordotdev/vector/pull/19918 to fix the docs.
