### ISSUE TITLE
Perfomance degradation in elasticsearch sink when using compression (gzip or zlib) after v0.34.0

### ISSUE THREAD

**Issue by ojh3636** [vectordotdev/vector#19981]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

[Tl;DR]
After vector version  0.33.1 (since 0.34.0), the elastic search sink performance is very poor when using compression option. (50% degraded of throughput and cpu & memory usage is very high)

Recently I upgraded vector from 0.27 to 0.36, then I can observe the performance degrade.
So I do regression test to point out which version is the problem. I can find that after 0.34.0 the elasticsearch sink performance is very poor.

<img width="1890" alt="image" src="https://github.com/vectordotdev/vector/assets/15365028/e34a5b4f-4b63-4143-936b-cbb67c1f9062">
<img width="970" alt="image" src="https://github.com/vectordotdev/vector/assets/15365028/58a0095e-26a5-4ca1-94c7-7b37456d0d38">

After observe the performance degrade, I do perf profiling v0.33.1 vs v0.34.0, then I can find difference between two version's flame graph

[Version v0.33.1]
![perf-0 33 1](https://github.com/vectordotdev/vector/assets/15365028/a0d00468-ab8f-41f3-a808-3aa3912b56fa)

[Version v0.34.0]
![perf-34](https://github.com/vectordotdev/vector/assets/15365028/f47b8bac-1dc8-4942-ab03-8aea0f9d712a)

After version v0.34.0, the memory set system call count is very high when to do GzEncoder (I also confirm that this call stack occur when I using the zlib compression rather than gzip) 

After these debugging, I turn off the compression and then I can observe the performance is almost same with previous version.
<img width="953" alt="image" src="https://github.com/vectordotdev/vector/assets/15365028/da009624-1520-493d-9a6b-39572e231e19">

But of course, the memory usage is high because the compression is disabled
<img width="942" alt="image" src="https://github.com/vectordotdev/vector/assets/15365028/29d46bf7-a474-4c9d-b30f-0ad55c4abbdd">

I think this problem is related to https://github.com/vectordotdev/vector/pull/18850 and https://github.com/rust-lang/flate2-rs/issues/395

Thank you.

### Configuration

```text
[api]
      enabled = true
      address = "0.0.0.0:9600"
    [log_schema]
      host_key = "_vector_host"
      metadata_key = "_vector_metadata"
      source_type_key = "_vector_source"
      message_key = "_vector_message"
      timestamp_key = "_vector_timestamp"
    [sources.kafka]
      type = "kafka"
      bootstrap_servers = "***"
      topics = ["***"]
      group_id = "***"
      decoding.codec = "json"
      auto_offset_reset = "latest"
      fetch_wait_max_ms = 10000
      session_timeout_ms = 10000
      headers_key = "\"@metadata\".kafka.headers"
      key_field =  "\"@metadata\".kafka.key"
      offset_key =  "\"@metadata\".kafka.offset"
      partition_key = "\"@metadata\".kafka.partition"
      topic_key =  "\"@metadata\".kafka.topic"
      [sources.kafka.librdkafka_options]
        "client.id" = "***"
        "max.poll.interval.ms" = "300000"
        "heartbeat.interval.ms" = "5000"
        "fetch.min.bytes" = "102400"
        "socket.receive.buffer.bytes" = "4096000"
    [sinks.to_es]
      type = "elasticsearch"
      inputs = ["kafka"]
      endpoint = "***"
      encoding.except_fields = ["_vector_source", "_vector_timestamp", "@metadata"]
      mode = "bulk"
      bulk.action = "index"
      bulk.index = "***"
      id_key = "\"@metadata\".documentId"
      bulk.max_bytes = 7680000
      compression = "gzip"
      request.timeout_secs = 7200
      request.rate_limit_duration_secs = 1
      request.rate_limit_num = 15
      buffer.max_events = 5000
      request_retry_partial = true


    [sources.internal_metrics]
      type = "internal_metrics"
      scrape_interval_secs = 15
      namespace = "vector"

    [sinks.internal_metrics_to_prometheus]
      inputs = ["internal_metrics"]
      type = "prometheus_exporter"
      address = "0.0.0.0:9601"
      default_namespace = "default"
```

### Version

v0.34.0

**Comment by ojh3636** [comment]
![perf-34](https://github.com/vectordotdev/vector/assets/15365028/747ceede-dd5f-4dcf-9d16-9603fee5f9e2)
![perf-0 33 1](https://github.com/vectordotdev/vector/assets/15365028/3050bde4-dff2-4117-8549-68b81252c8da)

Upload the 0.34.0 and 0.33.1 flamegraph svg for additional information

**Comment by jszwedko** [comment]
Thanks for the detailed analysis. It'll help narrow down where the issue may be. I'm not seeing anything obvious in the changelog so it might be an otherwise innocuous seeming change like a dependency update.

**Comment by Hexta** [comment]
Hey,
Maybe, it's worth adding a buffered writer for *Encoder writers?
I've tried to use 10KB buffer and performance improved a lot, similar to v0.33.0.

**Vector at revision b3889bcea**
![flamegraph-orig](https://github.com/vectordotdev/vector/assets/3001133/e766e716-c7a8-43f2-adb2-f19df4368b9b)

**Vector at revision b3889bcea with buffered writer**
![flamegraph-optimized](https://github.com/vectordotdev/vector/assets/3001133/e02d6533-712d-473b-a1d9-df8eadf71eab)

**Comment by Byron** [comment]
Thanks @Hexta for sharing!

Could you also share the patch here that leads to the flamgraph with improved performance? I was trying to understand better how this regression can be explained. For context, here is my [related comment](https://github.com/rust-lang/flate2-rs/issues/395#issuecomment-1975088152) over at `flate2`.

Thank you.

**Comment by Hexta** [comment]
@Byron This is just a draft version of the patch to verify the idea.
It should be moved to [Compressor](https://github.com/vectordotdev/vector/blob/b3889bcea835a00395928e0743a3c14582dc426d/src/sinks/util/compressor.rs).

```patch
diff --git a/src/sinks/elasticsearch/encoder.rs b/src/sinks/elasticsearch/encoder.rs
index cdee78120..9fb299d66 100644
--- a/src/sinks/elasticsearch/encoder.rs
+++ b/src/sinks/elasticsearch/encoder.rs
@@ -1,4 +1,5 @@
 use std::{io, io::Write};
+use std::io::BufWriter;
 
 use serde::Serialize;
 use vector_buffers::EventCount;
@@ -72,6 +73,7 @@ impl Encoder<Vec<ProcessedEvent>> for ElasticsearchEncoder {
     ) -> std::io::Result<(usize, GroupedCountByteSize)> {
         let mut written_bytes = 0;
         let mut byte_size = telemetry().create_request_count_byte_size();
+        let mut buffered_writer = BufWriter::with_capacity(10_240, writer);
         for event in input {
             let log = {
                 let mut event = Event::from(event.log);
@@ -81,7 +83,7 @@ impl Encoder<Vec<ProcessedEvent>> for ElasticsearchEncoder {
                 event.into_log()
             };
             written_bytes += write_bulk_action(
-                writer,
+                &mut buffered_writer,
                 event.bulk_action.as_str(),
                 &event.index,
                 &self.doc_type,
@@ -89,14 +91,15 @@ impl Encoder<Vec<ProcessedEvent>> for ElasticsearchEncoder {
                 &event.id,
             )?;
             written_bytes +=
-                as_tracked_write::<_, _, io::Error>(writer, &log, |mut writer, log| {
-                    writer.write_all(&[b'\n'])?;
-                    serde_json::to_writer(&mut writer, log)?;
-                    writer.write_all(&[b'\n'])?;
+                as_tracked_write::<_, _, io::Error>(&mut buffered_writer, &log, |mut buffered_writer, log| {
+                    buffered_writer.write_all(&[b'\n'])?;
+                    serde_json::to_writer(&mut buffered_writer, log)?;
+                    buffered_writer.write_all(&[b'\n'])?;
                     Ok(())
                 })?;
         }
 
+        buffered_writer.flush()?;
         Ok((written_bytes, byte_size))
     }
 }
```

**Comment by Byron** [comment]
Thanks for sharing! It's still unclear to me exactly how it happens that `flate2` is running into this kind of Vec-trashing that seems to be causing the issues here, when a buffered writer is not used, even after looking at the `Compressor` code. Maybe the answer is in `flate2` more than here, after all it's really just used as [`std::io::Write` implementation](https://github.com/vectordotdev/vector/blob/b3889bcea835a00395928e0743a3c14582dc426d/src/sinks/util/compressor.rs#L32C54-L32C65).

**Comment by Hexta** [comment]
Without buffer writer Vector is calling encoder `writer::write` for every small amount of data (10 bytes on average).
With 32KB inner buffer in flate2 it causes resizing with memset for each `write` call.

**Comment by ojh3636** [comment]
@Hexta Thanks for digging this issue! I've just apply the suggested buffered writer patch and do test(only for es sink encoder)
Confirm that the performance issue is solved. And even less use the cpu than v0.33.1!
 
![perf-34-buf](https://github.com/vectordotdev/vector/assets/15365028/fbbf3612-32f5-4fde-b67d-d73286b2e5b3)

<img width="595" alt="image" src="https://github.com/vectordotdev/vector/assets/15365028/a7294db1-5b44-4003-898c-feac8dc2baba">
<img width="1905" alt="image" src="https://github.com/vectordotdev/vector/assets/15365028/8d95d011-5ce2-4d71-adca-02c58e3b29a7">

**Comment by Byron** [comment]
> Without buffer writer Vector is calling encoder `writer::write` for every small amount of data (10 bytes on average). With 32KB inner buffer in flate2 it causes resizing with memset for each `write` call.

Thanks for the hint!
I think I put the pieces together now. The problem is that the internal buffer is [created with 32kb capacity](https://github.com/rust-lang/flate2-rs/blob/76327b14b08ecb616b023d6a6713cc37e9004f99/src/zio.rs#L164). However, with each small write it's [memset to its full capacity](https://github.com/rust-lang/flate2-rs/blob/69972b8262fbe03c28450c4c18961b41ad92af6a/src/mem.rs#L576), just to be [truncated to what's actually written right after](https://github.com/rust-lang/flate2-rs/blob/69972b8262fbe03c28450c4c18961b41ad92af6a/src/mem.rs#L580).

I will report this over at `flate2` in the hopes that this is fixable, even though in a way the issue that it uncovered along with a fix that further *improves* performance compared to the previous version seems like a net-positive.

**Comment by Hexta** [comment]
I'd like to prepare a PR.
@jszwedko do you have any objections for the proposed solution if it'll be implemented inside Compressor?

**Comment by jszwedko** [comment]
> I'd like to prepare a PR. @jszwedko do you have any objections to the proposed solution if it'll be implemented inside Compressor?

Thanks for the thorough investigation @Hexta and @Byron ! Let me flag this to some team members to weigh in.

**Comment by bruceg** [comment]
Agreed, thanks for this great investigation, @Hexta and @Byron. I agree in general with the patch and would support a PR in this direction, preferably with a big comment about why the buffer is necessary in the first place. I'm just curious about the buffer size constant. Is there anything magic about the 10kiB buffer size? Why not 32kiB like the underlying `flate2` buffer, to be able to flush it all in one go? If it's just to amortize the writes, would 8kiB or even 4kiB be enough, making it page-sized and more likely to be page-aligned?

Putting it into `Compressor` makes a lot of sense if this is a general issue for other sinks. We're investigating that a bit further.

**Comment by Hexta** [comment]
I think a 4KB buffer would be big enough and page-aligned, thanks for comment.
If the solution makes sense, I'll check performance with a 4KB buffer for different compression types.

**Comment by jszwedko** [comment]
I think the solution make sense though, as you suggest, it should be implemented in the [Compressor](https://github.com/vectordotdev/vector/blob/b3889bcea835a00395928e0743a3c14582dc426d/src/sinks/util/compressor.rs) so that all sinks can benefit.

**Comment by leandrojmp** [comment]
Just for curiosity, this issue affected compression on other sinks?

I have a data pipeline where a python script downloads files from cloudtrail and I use vector to open the files, unnest the main json object, send to a kafka sink using gzip compression and remove the files.

I was having an issue for a couple of weeks that was pretty hard to troubleshoot the root cause, from time to time the server just uses all the memory and the VM _freezes_, requiring a restart, which impacts the data ingest.

Last night while trying to fix this I found this issue and decided to upgrade from `0.35` to `0.36.1` and until now it seems that the issue is solved and another memory leak issue I had (which require a cronjob to restar vector every couple of hours) seems to be gone as well.

**Comment by jszwedko** [comment]
> Just for curiosity, this issue affected compression on other sinks?
> 
> I have a data pipeline where a python script downloads files from cloudtrail and I use vector to open the files, unnest the main json object, send to a kafka sink using gzip compression and remove the files.
> 
> I was having an issue for a couple of weeks that was pretty hard to troubleshoot the root cause, from time to time the server just uses all the memory and the VM _freezes_, requiring a restart, which impacts the data ingest.
> 
> Last night while trying to fix this I found this issue and decided to upgrade from `0.35` to `0.36.1` and until now it seems that the issue is solved and another memory leak issue I had (which require a cronjob to restart vector every couple of hours) seems to be gone as well.

Hey! Yeah, it affected all sinks using `flate2` for compression and the fix fixed it in a shared layer. I'm glad to hear it helped your situation as well!
