### ISSUE TITLE
ERROR vector::cli: Configuration error. error=Input "t1" for sink "211" doesn't match any components.

### ISSUE THREAD

**Issue by zhaohuaxi-Shi** [vectordotdev/vector#20014]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

This error occurred using the following configuration,  I don't know where the problem lies.

ERROR vector::cli: Configuration error. error=Input "t1" for sink "211" doesn't match any components.

### Configuration

```text
data_dir='/var/lib/vector'
[api]
enabled = false
[sources.209]
type='kafka'
bootstrap_servers='192.168.5.83:19092'
group_id='tag-cardinality-limit'
topics=['vm-service-log']


[transforms.t1]
type='route'
inputs=['209']
    [transforms.t1.route]
    debug = '.level == "debug"'


[sinks.211]
type='kafka'
inputs=['t1']
encoding.codec='json'
bootstrap_servers='192.168.5.83:19092'
topic='route-sink-test'
```

### Version

0.34.1

**Comment by jszwedko** [comment]
Hi @zhaohuaxi-Shi !

You'll want to use `inputs=['t1.debug']`. The `route` transform has one "output" for every defined route. In this case you defined a `debug` route and so need to use that in the input name. This is mentioned here: https://vector.dev/docs/reference/configuration/transforms/route/#route_id
