### ISSUE TITLE
Statsd timing metrics incorrectly parsed

### ISSUE THREAD

**Issue by paymog** [vectordotdev/vector#20019]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I think that vector is not parsing [statsd timing metrics](https://github.com/statsd/statsd/blob/master/docs/metric_types.md#timing) correctly. I'm using the [hotshots nodejs library](https://github.com/brightcove/hot-shots/) to emit a timing metric like so

```
            this.statsdClient.timing(
              options.name,
              123456,
              makeLabelValuesStrings(labels)
            );
```

When I send this to https://github.com/dasch/statsd-debug I see the following output

```
Timer `graphql_request_gauge' 123456.0 projectId:project_clt31u75a0014ijp23yimhhzf, subgraphName:ethblocks, versionLabel:main
```

When I send this to vector with the config shown below I see the following output (note how the value is `123.456` and not `123456`)

```
vector-1  | {"name":"graphql_request_gauge","tags":{"projectId":"project_clt31u75a0014ijp23yimhhzf","subgraphName":"ethblocks","versionLabel":"main"},"kind":"incremental","distribution":{"samples":[{"value":123.456,"rate":1}],"statistic":"histogram"}}
vector-1  | {"distribution":{"samples":[{"rate":1,"value":123.456}],"statistic":"histogram"},"kind":"incremental","name":"graphql_request_gauge","tags":{"projectId":"project_clt31u75a0014ijp23yimhhzf","subgraphName":"ethblocks","versionLabel":"main"},"timestamp":"2024-03-06T15:41:56.281634337Z"}
```

Additionally, sending a manual timing request with `echo -n "example.metric:123456|ms" | nc -u -w0 127.0.0.1 9831` (I'm running vector on port 9831) results in the following output

```
vector-1  | {"name":"example.metric","kind":"incremental","distribution":{"samples":[{"value":123.456,"rate":1}],"statistic":"histogram"}}
vector-1  | {"distribution":{"samples":[{"rate":1,"value":123.456}],"statistic":"histogram"},"kind":"incremental","name":"example.metric","timestamp":"2024-03-06T15:47:20.784253065Z"}
```

### Configuration

```text
[sources.statsd-metrics]
type = "statsd"
address = "0.0.0.0:9831"
mode = "udp"

[transforms.statsd_to_log]
inputs = ["statsd-metrics"]
type = "metric_to_log"

[sinks.latency_stdout]
inputs = ["statsd_to_log", "statsd-metrics"]
type = "console"
encoding.codec = "json"
target = "stdout"
```

### Version

0.36.0

### Additional Context

I'm running this in dodcker compose for local testing and kubernetes for staging and production. The above debugging was done with docker compose.

**Comment by jszwedko** [comment]
Hi @paymog !

For ingestion of statsd timing metrics, they are normalized to seconds which is why you see 123.456 in Vector for an input of 123456 ms.

I'll close this out, but let me know if you have any other questions!

**Comment by paymog** [comment]
Ah gotcha, yeah I guess you're right that the spec doesn't mention how these should be handled. Kinda odd that the unit is sent as `ms` but then it's internally converted to `s` - doesn't seem very intuitive to me. That being said, I understand that things like this happen! Thanks for digging in and writing docs 🙂
