### ISSUE TITLE
fingerprint.ignored_header_bytes is optional but Vector errors when starting with configuration error

### ISSUE THREAD

**Issue by markotitel** [vectordotdev/vector#20072]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When using file source and configuring fingerprint options Vector errors on startup with error:

`Configuration error. error=missing field ignored_header_bytes`

### Configuration

```text
nomad_logs:
       type: "file"
       fingerprint:
         strategy: "checksum"
         lines: 15
```

### Version

0.36.0

**Comment by jszwedko** [comment]
Thanks for reporting this @markotitel . I opened https://github.com/vectordotdev/vector/pull/20076 to fix it.
