### ISSUE TITLE
Support Embedded Metric Format in CloudWatch Logs sink

### ISSUE THREAD

**Issue by dastbe** [vectordotdev/vector#2009]
CloudWatch now allows you to [embed metrics directly into structures logs](https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-cloudwatch-launches-embedded-metric-format/), which they will extract and use to populate the time series data serverside. This has some obvious benefits, such as

* Avoiding redundant requests/network IO if you're persisting metrics in both logs and as metrics
* Ability to interleave application logs and metrics into a single stream 

In order to support this rusoto will need to support [injecting a custom header into a request](https://github.com/rusoto/rusoto/issues/1707).

**Comment by jszwedko** [comment]
This is available now as-of https://github.com/vectordotdev/vector/pull/12866
