### ISSUE TITLE
Repeated data when restart vector with/without disk buffer file

### ISSUE THREAD

**Issue by oulinbao** [vectordotdev/vector#20118]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I used vector transfer json data from kafka to minio. In order to preventing lost data, I used disk buffer and e2e ack for data persistence. And I found it will send repeated data whether I keep or remove the disk buffer file. At least, if I delete the disk buffer file, I think vector can know the last ack of kafka and continue to consume it, it should have no repeated records.

### Configuration

```text
api:
  enabled: true
  address: 127.0.0.1:8686
data_dir: /opt/vector
acknowledgements:
  enabled: true
sources:
  kafka:
    type: kafka
    bootstrap_servers: "localhost:9093"
    group_id: "t55"
    topics:
      - "dns"
    commit_interval_ms: 1000
    auto_offset_reset: earliest
    librdkafka_options:
      'enable.auto.commit': 'true'
transforms:
  parse_json:
    type: remap
    inputs:
      - kafka
    source: |-
      . = parse_json!(.message)
      . = parse_json!(.message)
sinks:
  minio:
    type: aws_s3
    inputs:
      - parse_json
    bucket: dns
    auth:
      access_key_id: xxxx
      secret_access_key: xxxxx
    compression: gzip
    encoding:
      codec: json
    endpoint: http://localhost:6000
    filename_extension: gz
    region: us-east-1
    batch:
      max_bytes: 50000000
      timeout_secs: 30
    buffer:
      type: disk
      max_size: 10000000000
    key_prefix: "%Y-%m-%d_"
    filename_append_uuid: false
```

### Version

vector 0.36.0 (x86_64-apple-darwin a5e48bb 2024-02-13 14:43:11.911392615)

**Comment by jszwedko** [comment]
Do you see any errors publishing to minio? The `aws_s3` sink is "at least once" and so you may see duplicates but it should be uncommon unless there are a lot of errors publishing.

**Comment by oulinbao** [comment]
No errors published. Yes, I am simulating vector crashing :)
