### ISSUE TITLE
Vector supports multiple config files

### ISSUE THREAD

**Issue by Joshualy94** [vectordotdev/vector#20122]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Hi, I wonder if I understand it correctly, but I am using vector with all components in one config file (vector.yaml at /etc/vector), which makes it too large to handle a large system. Is there a way we can store the structure in several config files and make the structure more clear?

Thanks!

**Comment by andjhop** [comment]
Yes: https://vector.dev/docs/reference/configuration/#multiple-files.
