### ISSUE TITLE
Please reconsider or refine VRL content filtering

### ISSUE THREAD

**Issue by eliebleton-manomano** [vectordotdev/vector#20124]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

I wish for a productive VRL development experience by having VRL errors be actionable and useful.

### Proposal

Please make the code source behavior [introduced here](https://github.com/vectordotdev/vector/commit/2ad7097b10112f1bd086d6a58c3bce47eb5652ae) either opt-in or opt-out. In present shape, error originating from any attached VRL file are quite hard to use - especially if the line numbers don't exactly match for a reason or another.

I believe that this feature should be opt-in : Our VRL files do not contain sensitive values and we intend to keep them that way. I suspect the same is true for most users, as we have tools to keep them out, namely environment variables and reference tables.

### References

https://github.com/vectordotdev/vector/pull/19356

### Version

vector 0.36.0 (x86_64-unknown-linux-gnu)

**Comment by jszwedko** [comment]
Thanks for the prompt @eliebleton-manomano ! After discussing it some more we agree and decided to revert it for now in https://github.com/vectordotdev/vector/pull/20125

**Comment by eliebleton-manomano** [comment]
Thank you for this extremely prompt resolution.
