### ISSUE TITLE
Datadog Sink Buffer Issues

### ISSUE THREAD

**Issue by wnhtr** [vectordotdev/vector#20135]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I am using the datadog_metrics sink to send metrics to Datadog, and that is working great.  However, sink buffer always increases until it hits the limit and starts blocking everything.  I can verify that my metrics are making it to Datadog just fine (without delay), but for some reason the vector buffer for this sink never gets purged.

### Configuration

```text
sinks:
  datadog_metrics:
    type: datadog_metrics
    inputs: 
      - agg_metrics
      - agg_vector_metrics
    default_api_key: "${DD_API_KEY}"
    site: "${DD_SITE}"
    buffer:
      type: disk
      max_size: 300000000
```

### Version

0.36.1-1

**Comment by jszwedko** [comment]
I'd suggest looking at a couple of things:

- Are you sure that the sink is keeping up with the buffer? I'd compare the internal metrics `buffer_events_received_total` with `component_sent_events_total` to see if more events are flowing into the buffer than out of the sink
- If the sink is applying backpressure, I'd fiddle with the `request.concurrency` setting to see if increasing the concurrency relieves the backpressure

**Comment by wnhtr** [comment]
I have resolved this issue by removing the buffer config from the sink.  The new, working sink config looks like this:

sinks:
  datadog_metrics:
    type: datadog_metrics
    inputs: 
      - agg_metrics
      - agg_vector_metrics
    default_api_key: "${DD_API_KEY}"
    site: "${DD_SITE}"

**Comment by jszwedko** [comment]
Great, thanks @wnhtr ! I'll close this out then since you seem to have found a config that works for you. Feel free to reopen if you want to dig into the disk buffer issues further.
