### ISSUE TITLE
Make `aws_s3` allow for configuration of the `max_number_of_messages` value

### ISSUE THREAD

**Issue by fdamstra** [vectordotdev/vector#20172]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

The `aws_s3` source is hardcoded to grab 10 SQS messages at a time. When working with large files in S3, this means the visibility_timeout must be set exceptionally high in order to handle processing _10_ very large files.

### Proposal

Make a configuraiton setting for `max_number_of_messages` in the aws_s3 source. This setting is currently hardcoded to `10`, which is the maximum. The default setting in the SDK is `1`, which is our desired setting and makes the most sense for large file ingestions. The setting of 10 is only appropriate for small files.

### References

The fix for very large files that exceed the visibility timeout is #4910 , but that fix should be combined with smaller batch sizes for the best use of resources.

### Version

vector 0.36.1 (x86_64-unknown-linux-gnu 2857180 2024-03-11 14:32:52.417737479)

**Comment by jszwedko** [comment]
Makes sense! We'd be happy to see a PR for this if you (or someone else) feels motivated.

**Comment by fdamstra** [comment]
This was merged and released in april.
