### ISSUE TITLE
Incorrect metrics for kafka source

### ISSUE THREAD

**Issue by jlazic** [vectordotdev/vector#20224]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Starting with vector 0.34.2 there is discrepancy between Events In and Events Out for Kafka sources shown in API and `vector top`

This is snapshot of vector top output after a few moments of running, as you can see Kafka source claims it's taking 7.98k/s In and outputting almost 8x out.

| ID    | Kind | Type | Events In | Bytes In | Events Out | Bytes Out | Errors
| --- | --- | --- | --- | --- |--- | --- | --- | 
| kafka-in | source | kafka | 1.45M (7.98k/s) | 1.81GiB (9.99MiB/s) | 11.76M (64.68k/s) | N/A | -- |
| blackhoule-out | sink | blackhole | 11.76M (64.68k/s) | N/A | 11.76M (64.68k/s) | 16.38M (92.35MiB/s) | -- |

This started happening with 0.34 and same behavior is exhibited upto latest 0.37.0
Version 0.33.1 works as expected.

### Configuration

```text
[sources.kafka-in]
    type = "kafka"
    bootstrap_servers = "..."
    auto_offset_reset = "earliest"
    group_id = "vector-test-64"
    key_field = "message_key"
    topics = ["vector-test-64"]
    metrics.topic_lag_metric = true

[sinks.blackhole-out]
    type = "blackhole"
    inputs = [ "kafka-in" ]
```

### Version

0.37.0

**Comment by jszwedko** [comment]
Thanks for this report! I appreciate you including all of the relevant details. I was able to use that to bisect down to f2efb1ac53f45621fff3f2ea7628cc1082040b5e which seems to have introduced this regression.

Unfortunately nothing jumps out to me just yet. The implementation _appears_ to be correct. @jches , as the author of that diff, I'm curious if anything jumps out to you as a potential cause. To summarize: it looks like the `kafka` source is severely undercounting `component_events_in_total` after that change.

**Comment by jches** [comment]
Ah yeah thanks for reporting this! Looks it's probably related to the `emit!` calls not mapping to the correct span to associate with the source.
