### ISSUE TITLE
Vector unable to publish to AWS SNS sink when running as systemctl service

### ISSUE THREAD

**Issue by ankur143r** [vectordotdev/vector#20243]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We are using vector to publish to sns sink. However we have observed that when vector runs as a systemctl service, it is unable to publish any message to aws sns sink. However if we run it through a command for e.g. vector -c /etc/vector/vector.toml - It is able to publish to sns sink successfully.

Sample config is added

### Configuration

```text
[sources.cyber]
type = "socket"
address = "0.0.0.0:514"
mode = "tcp"



[sinks.syslog_to_sns]
type = "aws_sns"
inputs = [ "cyber" ]
region = "ap-southeast-2"
healthcheck.enabled = false
encoding.codec = "json"
topic_arn = "arn:aws:sns:ap-southeast:1234567:foo_xyz_abc_defghi_18"
```

### Version

vector-0.36.0-1.x86_64

### Additional Context

Vector is running on AWS EC2 instance (AWS Linux 2)

**Comment by jszwedko** [comment]
Hi @ankur143r ! Can you share the log output from Vector when running under SystemD? My guess is that it is trying to load the default configuration file `/etc/vector/vector.yaml` and not finding it. If you want to use `/etc/vector/vector.toml` you can set `VECTOR_CONFIG=/etc/vector/vector.toml` in `/etc/default/vector`.

**Comment by jszwedko** [comment]
Closing due to lack of response.
