### ISSUE TITLE
Add labels to chronicle sink

### ISSUE THREAD

**Issue by bwerthmann** [vectordotdev/vector#20281]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Make use of `optional` Google Chronicle's `labels[]` which is...
> Array of objects containing the key-value pairs for labels to be applied to the logs.

https://cloud.google.com/chronicle/docs/reference/ingestion-api#body_parameters_2

### Attempted Solutions

Not supported currently.

### Proposal

add support for a new Sink level field named `labels`.

**Comment by bwerthmann** [comment]
I am interested in working on this issue.

**Comment by jszwedko** [comment]
Great, thanks @bwerthmann ! Just let us know if you need any guidance. The DEVELOPMENT.md and CONTRIBUTING.md docs are a good place to start.

**Comment by bwerthmann** [comment]
Already reading both docs. :)
