### ISSUE TITLE
Prometheus sync - improved histogram support

### ISSUE THREAD

**Issue by afoninsky** [vectordotdev/vector#2033]
Following histogram provides additional features (less cardinality, more accuracy), but it can be handled only in VictoriaMetrics TSDB (https://victoriametrics.com/):

https://medium.com/@valyala/improving-histogram-usability-for-prometheus-and-grafana-bc7e5df0e350

Placing this issue as a point for discussion if it's useful to implement such histograms or not.

**Comment by binarylogic** [comment]
Thanks @afoninsky, we'll take a look.

**Comment by jszwedko** [comment]
Closing this in favor of https://github.com/vectordotdev/vector/issues/16333
