### ISSUE TITLE
s3 log source from mutiple s3 buckets 

### ISSUE THREAD

**Issue by neeltom92** [vectordotdev/vector#20348]
### Problem

using S3 as a log source and I need to retrieve objects from multiple S3 buckets in different AWS accounts to a deployment running in EKS in another account. 

To achieve this, I must create IAM roles for cross account IRSA in the account where each bucket is residing and annotate the service account attached the deployment with the role ARN's,
however, afaik I can only annotate the SA with an ARN once and annotation " eks.amazonaws.com/role-arn" accepts string values and not arrays, so cannot annotate with more than 1 arn's
so how to solve this?

### Version

vector 0.36.1

**Comment by jszwedko** [comment]
Hi @neeltom92 ,

This sounds a little like a general AWS issue than something about Vector specifically. I think you could create the role in the account Vector is running in and give it access in the target accounts. See

- https://docs.aws.amazon.com/AmazonS3/latest/userguide/example-walkthroughs-managing-access-example2.html
- https://docs.aws.amazon.com/lambda/latest/dg/with-sqs-cross-account-example.html

For an example of this.

I'll close this out, but let me know if you have any questions.
