### ISSUE TITLE
Add a pretty json encoding for better testing / configuring experience

### ISSUE THREAD

**Issue by lsampras** [vectordotdev/vector#20380]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

A better UX when users are trying to build/configure their pipeline, the primary usage would be with the console sink.

Pretty-json is much more friendlier to infer the structure of your data.

### Attempted Solutions

I've attempted this on [my fork](https://github.com/lsampras/vector/tree/add_pretty_json) and seems to work pretty well, although I might be missing edge cases or making invalid assumptions...

### Proposal

Adding a simple encoding would work here based on underlying [serde_json::to_writer_pretty](https://docs.rs/serde_json/latest/serde_json/fn.to_writer_pretty.html) implementation.

### Version

0.37.1

**Comment by jszwedko** [comment]
Thanks @lsampras ! I took a quick look at your branch and I think this is something we'd accept as a contribution if you feel inclined to open a pull request.

**Comment by lsampras** [comment]
@jszwedko I've opened #20384 for adding this, Can you take a look at that once?
