### ISSUE TITLE
Possible Memory Leak with Kafka source 

### ISSUE THREAD

**Issue by biuboombiuboom** [vectordotdev/vector#20403]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We have a configuration with a kafka source and an clickhouse sink. 
The memory often overflow。

### Configuration

```text
[sources.in]
session_timeout_ms = 180000
type = "kafka"
bootstrap_servers = "bootstrap.brokers.kafka:9092"
group_id = "kafka-consume-group"
topics = ["my-topic"]
librdkafka_options = { "auto.offset.reset" = "latest", "fetch.min.bytes" = "10240" }

[transforms.balance]
type = "remap"
inputs = ["in"]
drop_on_error = true
source = '.route_id=random_int(0,4)'

[transforms.route]
type = "route"
inputs = ["balance"]
reroute_unmatched = false
route.first = '.route_id==0'
route.second = '.route_id==1'
route.third = '.route_id==2'
route.fouth = '.route_id==3'


[sinks.out-clickhouse-1]
type = "clickhouse"
inputs = ["route.first"]
compression = "none"
endpoint = "http://localhost:8125"
database = "mytable"

batch.max_events = 800000
batch.max_bytes = 2147483648
batch.timeout_secs = 120

request.timeout_secs = 120
request.adaptive_concurrency.initial_concurrency=4
# request.adaptive_concurrency.max_concurrency_limit=4

buffer.type = "memory"
buffer.max_events = 400000
buffer.when_full = "block"

[sinks.out-clickhouse-2]
type = "clickhouse"
inputs = ["route.second"]
compression = "none"
endpoint = "http://localhost:8125"
database = "apmmytable

batch.max_events = 800000
batch.max_bytes = 2147483648
batch.timeout_secs = 120

request.timeout_secs = 120
request.adaptive_concurrency.initial_concurrency=4
# request.adaptive_concurrency.max_concurrency_limit=4

buffer.type = "memory"
buffer.max_events = 400000
buffer.when_full = "block"

[sinks.out-clickhouse-3]
type = "clickhouse"
inputs = ["route.third"]
compression = "none"
endpoint = "http://localhost:8125"
database = "mytable"

batch.max_events = 800000
batch.max_bytes = 2147483648
batch.timeout_secs = 120

request.timeout_secs = 120
request.adaptive_concurrency.initial_concurrency=4
# request.adaptive_concurrency.max_concurrency_limit=4

buffer.type = "memory"
buffer.max_events = 400000
buffer.when_full = "block"

[sinks.out-clickhouse-4]
type = "clickhouse"
inputs = ["route.fouth"]
compression = "none"
endpoint = "http://localhost:8125"
database = "mytable"

batch.max_events = 800000
batch.max_bytes = 2147483648
batch.timeout_secs = 120

request.timeout_secs = 120
request.adaptive_concurrency.initial_concurrency=4
# request.adaptive_concurrency.max_concurrency_limit=4

buffer.type = "memory"
buffer.max_events = 400000
buffer.when_full = "block"



[sources.vector_logs]
type = "internal_logs"

[sinks.log2file]
type = "file"
inputs = ["vector_logs"]
path = "/data/logs/vector-%Y-%m-%d.log"
encoding.codec = "logfmt"

[sources.vector_metrics]
type = "internal_metrics"

[sinks.prometheus_exporter]
inputs = ["vector_metrics"]
type = "prometheus_exporter"
```

### Version

0.37.1

**Comment by jszwedko** [comment]
Hi @biuboombiuboom ,

There's not a lot of detail here. What leads you to believe there is a memory leak? If you are feeling motivated you could try running Vector under `valgrind` and providing the profile here.

**Comment by nsweeting** [comment]
We're actually seeing a similar issue running the latest version. With a kafka source and a clickhouse sink. A sustained flow of messages seems to inevitably result in OOM. You can see the behaviour in these charts. We have very bursty workloads. Each workload burst results in sustained CPU use (makes sense) as well as continued memory growth. If the work stops - the memory goes back down. But if the work continues... it will OOM.

<img width="1598" alt="Screenshot 2024-05-02 at 11 21 34 AM" src="https://github.com/vectordotdev/vector/assets/3457648/8374889c-7b8b-4604-8a5f-77c9f10ad932">

**Comment by biuboombiuboom** [comment]
> We're actually seeing a similar issue running the latest version. With a kafka source and a clickhouse sink. A sustained flow of messages seems to inevitably result in OOM. You can see the behaviour in these charts. We have very bursty workloads. Each workload burst results in sustained CPU use (makes sense) as well as continued memory growth. If the work stops - the memory goes back down. But if the work continues... it will OOM.
> 
> <img alt="Screenshot 2024-05-02 at 11 21 34 AM" width="1598" src="https://private-user-images.githubusercontent.com/3457648/327487212-8374889c-7b8b-4604-8a5f-77c9f10ad932.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NjUxNTksIm5iZiI6MTcxNDk2NDg1OSwicGF0aCI6Ii8zNDU3NjQ4LzMyNzQ4NzIxMi04Mzc0ODg5Yy03YjhiLTQ2MDQtOGE1Zi03N2M5ZjEwYWQ5MzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDZUMDMwNzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjIwNjJmNTVhYmFmOWNkMDE4MmM1NGMyOGFkYzFmYzFmNzgyOTRlZTBmNTEyMmJmYTgyNzc3OGY5NTNiNmU4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JIVCSKXQxR8eznA8f5gkr286nU3-ZAMpnaQMYf_3jco">

Look the same

**Comment by biuboombiuboom** [comment]
![image](https://github.com/vectordotdev/vector/assets/7258606/58c9306c-64c1-4c5a-b1b3-e28d8008d08c)

![image](https://github.com/vectordotdev/vector/assets/7258606/97fff8ff-25a6-4ba3-aa17-6fa3e54c64bc)

`ack_stream` has too many `FinalizerEntry` not consumed.

Try sync store offsets,and disable BatchNotifier.

Or move `ack_stream.next()` before `messages.next()`  & with `biased`.

**Comment by bruceg** [comment]
I'm not clear what you mean by the following:

> Try sync store offsets,and disable BatchNotifier.

The second suggestion is spot on and definitely worth a try. The `ack_stream` should always be checked before consuming new events, because eventually it will run dry to allow progress for new data.

**Comment by biuboombiuboom** [comment]
> I'm not clear what you mean by the following:
> 
> > Try sync store offsets,and disable BatchNotifier.
> 
> The second suggestion is spot on and definitely worth a try. The `ack_stream` should always be checked before consuming new events, because eventually it will run dry to allow progress for new data.

Sorry ,I didn't express it clearly, please disregard the first suggestion

**Comment by bruceg** [comment]
I have pushed up a possible fix for this issue. If you are able to build Vector from source, check out PR #20467 and try the resulting binary.

**Comment by bruceg** [comment]
The proposed fix is now in the `master` branch. Please confirm if this resolves the memory leak for you.

**Comment by biuboombiuboom** [comment]
> The proposed fix is now merged into the `master` branch. Please confirm if this resolves the memory leak for you.

Yes, It is effective

**Comment by jszwedko** [comment]
Thanks for confirming! And for suggesting the original fix. I'll close this issue out.
