### ISSUE TITLE
Change Loki OutOfOrderAction default

### ISSUE THREAD

**Issue by jpds** [vectordotdev/vector#20466]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Proposal

Loki 2.4.0 is three years old now - should the default at https://github.com/vectordotdev/vector/blob/e1d1e851e71bd8c20f9c53a8340f0cdc3d0e7c12/src/sinks/loki/config.rs#L145-L159 be changed to accept?

**Comment by jszwedko** [comment]
Thanks @jpds . I agree at this point a better default would be `Accept`. Feel free to open a PR if you like.
