### ISSUE TITLE
vector-agent sources  kubernetes_logs timezone  invalid

### ISSUE THREAD

**Issue by huisebug** [vectordotdev/vector#20507]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I hope the time zone can be Asia/Shanghai, but the logs printed from the vector aggregator console and the data stored in the clickhouse are still in UTC world standard time. I tried the American/New York time zone but it still hasn't changed

### Configuration

```text
sources:
      kubernetes_logs:
        extra_namespace_label_selector: huisebug.io/logging-system=enabled
        timezone: Asia/Shanghai
        namespace_annotation_fields:
          namespace_labels: ""
        node_annotation_fields:
          node_labels: ""
        pod_annotation_fields:
          container_id: ""
          container_image: ""
          container_image_id: ""
          container_name: container_name
          pod_annotations: ""
          pod_ip: ""
          pod_ips: ""
          pod_labels: ""
          pod_name: pod_name
          pod_namespace: pod_namespace
          pod_node_name: ""
          pod_owner: ""
          pod_uid: ""
        type: kubernetes_logs
      vector_metrics:
        type: internal_metrics
```

### Version

timberio/vector:0.38.0-distroless-libc

### Debug Output

```text
{"container_name":"nginx","file":"/var/log/pods/default_nginx-564d4f7d84-xp8cw_8ca2bfea-5915-4f95-be20-a5ee813314df/nginx/1.log","message":"10.10.1.0 - - [17/May/2024:10:56:34 +0800] \"GET / HTTP/1.1\" 304 0 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36\" \"192.168.137.1\"","pod_name":"nginx-564d4f7d84-xp8cw","pod_namespace":"default","source_type":"kubernetes_logs","stream":"stdout","timestamp":"2024-05-17T02:56:34.364711461Z"}
```

### Additional Context

使用vectoragent--》vector-aggregator--》clickhouse

**Comment by jszwedko** [comment]
@huisebug The `timezone` config on sources just configures how Vector reads timestamps that are missing a timezone. Internally in Vector, all timestamps are recorded as UTC. I think what you want is to be able to configure the timezone that Vector writes the timestamps using. This is an outstanding feature request: https://github.com/vectordotdev/vector/issues/18158. I'll close this one in-lieu of the feature request. Feel free to follow along there are add additional thoughts.
