### ISSUE TITLE
Vector fails to start with opentelemetry source configured

### ISSUE THREAD

**Issue by tronboto** [vectordotdev/vector#20548]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Vector raises a configuration error when configured with a minimal opentelemetry pipeline

### Configuration

```text
sources:
  my_source_id:
    type: opentelemetry
    grpc:
      address: 0.0.0.0:4317
    http:
      address: 0.0.0.0:4318

sinks:
  my_sink_id:
    type: console
    inputs:
      - my_source_id
    encoding:
      codec: json
```
```


### Version

0.38.0

### Debug Output

vector  | 2024-05-22T15:03:10.984088Z DEBUG vector::app: Internal log rate limit configured. internal_log_rate_secs=10
vector  | 2024-05-22T15:03:10.984193Z  INFO vector::app: Log level is enabled. level="trace"
vector  | 2024-05-22T15:03:10.984369Z DEBUG vector::app: messaged="Building runtime." worker_threads=4
vector  | 2024-05-22T15:03:10.984500Z TRACE mio::poll: registering event source with poller: token=Token(1), interests=READABLE
vector  | 2024-05-22T15:03:10.985639Z  INFO vector::app: Loading configs. paths=["/etc/vector/vector.yaml"]
vector  | 2024-05-22T15:03:10.987705Z DEBUG vector::config::loading: No secret placeholder found, skipping secret resolution.
vector  | 2024-05-22T15:03:10.988500Z ERROR vector::cli: Configuration error. error=Input "my_source_id" for sink "my_sink_id" doesn't match any components.
vector exited with code 78
```

**Comment by jszwedko** [comment]
Hi @tronboto ! You need to use `my_source_id.logs` as the input (that source uses "named outputs" to allow for metrics and traces to be added later as event types to that source).

**Comment by tronboto** [comment]
Thanks, @jszwedko . Just saw this: https://vector.dev/docs/reference/configuration/sources/opentelemetry/#outputs

None of the other sources we use require this so it didn't cross my mind that this one would be different. It makes sense though given the upcoming support for metrics and traces.
