### ISSUE TITLE
vector oom

### ISSUE THREAD

**Issue by chixianliangGithub** [vectordotdev/vector#20553]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Issue Description:
After starting, memory usage keeps increasing until it eventually results in an out-of-memory (OOM) condition.
I noticed that the memory usage keeps increasing and is not being released.
<img width="532" alt="c4d3503a23e2ee84f701cf35858005e" src="https://github.com/vectordotdev/vector/assets/11659305/67efb42c-eeee-4af3-92a3-329ff4bc0db4">
<img width="535" alt="c2c15daf4e41f25549d5abdd7db022f" src="https://github.com/vectordotdev/vector/assets/11659305/fa77c18e-a945-4182-80af-04bab07867cc">
<img width="505" alt="001cad94ebc1039ef2627f1e9d6417b" src="https://github.com/vectordotdev/vector/assets/11659305/1341f5f1-7934-4ba4-b2aa-a753315c47e6">
<img width="495" alt="8ec050ff5382c7bedc2c9a7b058e93f" src="https://github.com/vectordotdev/vector/assets/11659305/337fe24f-744e-4362-8d73-b79d473ec7d3">

### Configuration

```text
[sources.kafka_app_log]
  type = "kafka"
  bootstrap_servers = "xxx:9092,xxx:9092,xx:9092"
  group_id = "vector-log"
  topics = ["xxx"]

[transforms.process_app]
  type = "remap"
  inputs = ["kafka_app_log"]
  source = '''
    if !exists(.message) {
      log("Missing message field", level: "warn")
    } else {
      parts, err = split(.message, "|service_platform_name=")
      if err == null {
        content = parts[0]
        platform = parts[1]
        additional_info, err = split(platform, ",")
        if (err == null) {
          log_type = additional_info[0]
          if log_type == "log" {
            result, err = split(content, "|")
            if err == null {
              happen_time = slice!(result[0], 0, 19)
              .log_time = happen_time
              .thread = result[1]
              .request_origin = result[2]
              .level = result[3]
              .logger = result[4]
              .log_format_version = result[5]
              traces, err = split(result[6], ":")
              .trace_id = traces[1]
              .trace_info = result[7]
              .trace_group = result[8]
              .log_message = result[9]
              .platform_name = additional_info[1]
              .service_name = additional_info[2]
              .ip = additional_info[3]
            }
          }
        }
      }
    }
    del(.message)
    del(.headers)
  '''

[sinks.clickhouse_app]
  type = "clickhouse"
  inputs = ["process_app"]
  endpoint = "http://xxx:8123"
  database = "xxx"
  table = "xxx"
  date_time_best_effort = true
  # compression = "gzip"
  skip_unknown_fields = true
  request.timeout_secs = 30
  auth.strategy = "basic"
  auth.user = "default"
  auth.password = "xxx"
```

### Version

vector 0.38.0 (x86_64-unknown-linux-gnu ea0ec6f 2024-05-07 14:34:39.794027186)

**Comment by chixianliangGithub** [comment]
> I think this might be fixed by #20467 which will be included in the next release. Could you try the latest nightly release and see if that works for you? You can find those here:
> 
> * https://hub.docker.com/r/timberio/vector/tags?page=&page_size=&ordering=&name=nightly for docker
> * https://packages.timber.io/vector/nightly/2024-05-23/ for other assets
After changing to the new version, it seems that the memory has stabilized after increasing to 5.3g.

**Comment by jszwedko** [comment]
Thanks for checking! I'll close this out but let us know if you have further questions.

**Comment by vosmax** [comment]
After update to 0.39.0 Im still experiencing OOMs, when consumer has a huge lag

**Comment by bobelev** [comment]
Same here. Patch helped a lot with an up-to-date consumer. But when topic is read from the begging, vector uses a lot of memory despite of acknowledgements or low `queued.min.messages`.

**Comment by vosmax** [comment]
@jszwedko, greetings! 
Looks this issue has to be reopened.

**Comment by jszwedko** [comment]
HI @vosmax and @bobelev ! Thanks for flagging. Do one of you mind opening a new issue with all of the relevant details? It seems likely to be a different issue than the one reported here since this one was resolved.

**Comment by bobelev** [comment]
@jszwedko Is there some sort of guide on how to report memory problems for vector? I'd be happy to provide config/logs/graphs.

**Comment by jszwedko** [comment]
> @jszwedko Is there some sort of guide on how to report memory problems for vector? I'd be happy to provide config/logs/graphs.

The _most_ helpful thing to do would be to capture a memory profile using `valgrind` and to provide that 🙏
