### ISSUE TITLE
Validate command tries to bind to port when using splunk_hec source

### ISSUE THREAD

**Issue by Aeternax** [vectordotdev/vector#20589]
### Problem

We are using the splunk_hec source and want to verify that our config is always in a good state.
That was never a problem until using this source.

Running a `vector validate` we get the following error:

`Component errors:
x Source "source_hec": TCP bind failed: Address already in use (os error 98)
`

And this is due to it trying to bind to the port, which is already taken by the running vector instance.

### Configuration

```text
---
data_dir: /tmp
sources:
  src_hec:
    type: splunk_hec
    address: 0.0.0.0:8000
sinks:
  void:
    inputs: [src_hec]
    type: blackhole
```

### Version

vector 0.37.1 (x86_64-unknown-linux-gnu cb6635a 2024-04-09 13:45:06.561412437)
vector 0.38.0 (x86_64-apple-darwin ea0ec6f 2024-05-07 14:34:39.794027186)

### Debug Output

```text
RUST_BACKTRACE=FULL
vector  validate
√ Loaded ["/etc/vector/vector.yaml"]

Component errors
----------------
x Source "src_hec": TCP bind failed: Address already in use (os error 98)
```

**Comment by jszwedko** [comment]
This is expected, but can be avoided by passing `--no-environment` which should skip binding to the port.

**Comment by Aeternax** [comment]
@jszwedko, it seems strange that for this source the expected behavior is different than with other ones.

Is there a reason why that is so?

**Comment by jszwedko** [comment]
> @jszwedko, it seems strange that for this source the expected behavior is different than with other ones.
> 
> Is there a reason why that is so?

It shouldn't differ. I believe any sources that bind to a port should be attempting to bind without `--no-environment`. I believe the intent of `vector validate` (without `--no-environment`) is to check for resource availability (like ports).

**Comment by Aeternax** [comment]
> > @jszwedko, it seems strange that for this source the expected behavior is different than with other ones.
> > Is there a reason why that is so?
> 
> It shouldn't differ. I believe any sources that bind to a port should be attempting to bind without `--no-environment`. I believe the intent of `vector validate` (without `--no-environment`) is to check for resource availability (like ports).

We only recently started using vector, but have only found this trying to bind behavior with the `splunk_hec` source.

So far we've used at least `vector` and `socket` sources otherwise which both bind to a port and validate works without a problem.

So I'd say this is not entirely expected behavior for all sources.

**Comment by jszwedko** [comment]
> > > @jszwedko, it seems strange that for this source the expected behavior is different than with other ones.
> > > Is there a reason why that is so?
> > 
> > 
> > It shouldn't differ. I believe any sources that bind to a port should be attempting to bind without `--no-environment`. I believe the intent of `vector validate` (without `--no-environment`) is to check for resource availability (like ports).
> 
> We only recently started using vector, but have only found this trying to bind behavior with the `splunk_hec` source.
> 
> So far we've used at least `vector` and `socket` sources otherwise which both bind to a port and validate works without a problem.
> 
> So I'd say this is not entirely expected behavior for all sources.

Ah, interesting, I think this may be a bug in the `vector` and `socket` sources then based on my understanding of the intended behavior of `vector validate` without the `--no-environment` flag 🤔 The inconsistency is definitely undesirable.
