### ISSUE TITLE
parse_aws_alb_log Failing due to new log format

### ISSUE THREAD

**Issue by misterek** [vectordotdev/vector#20591]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

AWS is introducing a traceabilty ID to the end of AWS ALB Logs.  Current behavior is function call error for \"parse_aws_alb_log\" at (54:82): Log should be fully consumed: \" TID_<theid>\""

### Version

0.38

### References

https://github.com/vectordotdev/vrl/pull/862

**Comment by jszwedko** [comment]
Thanks for this report @misterek ! I think it is the same as https://github.com/vectordotdev/vrl/issues/852 so I'll close this one as a duplicate (there is also a workaround in that issue). I recognize that this is a severe issue though so we'll try to address it next week.
