### ISSUE TITLE
Documentation missing for decrypt VRL function reference

### ISSUE THREAD

**Issue by alisa101rs** [vectordotdev/vector#20648]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I am sorry if I file this issue in the wrong repository.

I think that both encrypt and decrypt vrl functions support the same list of algorithms [(see implementation)](https://github.com/vectordotdev/vrl/blob/main/src/stdlib/decrypt.rs#L68). But algorithm list for [decrypt](https://vector.dev/docs/reference/vrl/functions/#decrypt) vrl function is different from list for [encrypt](https://vector.dev/docs/reference/vrl/functions/#encrypt) in official reference documentation. 

This https://github.com/vectordotdev/vector/blob/f6527ec5869b4502ea1dbb68e85634a331d2eb3d/website/cue/reference/remap/functions/decrypt.cue#L3-L31
should be the same as this
https://github.com/vectordotdev/vector/blob/f6527ec5869b4502ea1dbb68e85634a331d2eb3d/website/cue/reference/remap/functions/encrypt.cue#L3-L40

### Version

https://vector.dev

**Comment by jszwedko** [comment]
Thanks for the report! Opened https://github.com/vectordotdev/vector/pull/20658 to correct.
