### ISSUE TITLE
Autotagging issues and PRs

### ISSUE THREAD

**Issue by Hoverbear** [vectordotdev/vector#2071]
I'd like to set up a GA script to automatically tag our issues based on semantics.

**Comment by binarylogic** [comment]
Go for it. I tried one that used "AI" and it was pretty bad. If we do this it should probably be based on rules.

**Comment by Hoverbear** [comment]
What about this one that uses file patterns? https://github.com/banyan/auto-label

**Comment by binarylogic** [comment]
I'm happy with anything that doesn't produce false positives. I don't want to be removing invalid labels.

**Comment by Hoverbear** [comment]
Do you consider a PR that touches the file source, but is not directly regarding the file source, as a PR that should be labelled with the file source tag?

**Comment by jszwedko** [comment]
Closing since we do have some basic auto-labeling now.
