### ISSUE TITLE
Path exists in the event, but VRL doesn't see it

### ISSUE THREAD

**Issue by vosmax** [vectordotdev/vector#20724]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I've faced with the issue when VRL doesn't see the path, but it is presented in the event. 
You may see it in the output. I add a condition with a function `exists` with 2 outputs. 
1 - shows the full event -> field presented
2 - shows value of the path `kubernetes.namespace_name ` -> null
Logs: 
```
2024-06-24T18:54:03.471165Z  INFO vector::topology::builder: Healthcheck passed.
2024-06-24T18:54:06.116504Z ERROR transform{component_kind="transform" component_id=app-logs-transforms component_type=remap}: vrl::stdlib::log: {"@timestamp": "2024-06-24T18:54:00.259096Z","_p": "F","kubernetes.container_image": "quay.io/strimzi/kafka:0.39.0-kafka-3.6.1","kubernetes.container_name": "cruise-control","kubernetes.host": "ip-XX-XXX-XX-XXX.XXX.compute.internal","kubernetes.labels.app_kubernetes_io/instance": "kafka-1","kubernetes.labels.app_kubernetes_io/managed-by": "strimzi-cluster-operator","kubernetes.labels.app_kubernetes_io/name": "cruise-control","kubernetes.labels.app_kubernetes_io/part-of": "strimzi-kafka-1","kubernetes.labels.env": "stable","kubernetes.labels.release": "kafka-1","kubernetes.labels.strimzi_io/cluster": "kafka-1","kubernetes.labels.strimzi_io/component-type": "cruise-control","kubernetes.labels.strimzi_io/kind": "Kafka","kubernetes.labels.strimzi_io/name": "kafka-1-cruise-control","kubernetes.namespace_name": "kafka","kubernetes.pod_name": "kafka-1-cruise-control-6d76c9759-r4ndt","kubernetes_cluster": "dev","kubernetes_node": "ip-XX-XXX-XX-XXX.XXX.compute.internal","log": "2024-06-24 18:54:00 INFO  AbstractAsyncRequest:49 - Processing async request CruiseControlStateRequest.","log_topic": "eks-logging","logging_topic": "eks-logging","source_type": "kafka","stream": "stdout","time": "2024-06-24T18:54:00.259096875Z"} internal_log_rate_secs=60 vrl_position=1427
2024-06-24T18:54:06.116529Z ERROR transform{component_kind="transform" component_id=app-logs-transforms component_type=remap}: vrl::stdlib::log: <null> internal_log_rate_secs=60 vrl_position=1473
2024-06-24T18:54:06.150178Z ERROR sink{component_kind="sink" component_id=app-logs-output component_type=elasticsearch}: vector::internal_events::template: Failed to render template for "data_stream.namespace". error=Missing fields on event: ["kubernetes.namespace_name"] error_type="template_failed" stage="processing" internal_log_rate_limit=true
```

### Configuration

```text
api:
  enabled: false
data_dir: /var/lib/vector
sinks:
  app-logs-output:
    auth:
      password: ${ES_PASSWORD}
      strategy: basic
      user: ${ES_USER}
    compression: gzip
    data_stream:
      dataset: '{{ kubernetes_cluster }}'
      namespace: '{{ kubernetes.namespace_name }}'
      type: eks
    endpoints:
    - ${ES_HOST}
    inputs:
    - app-logs-transforms
    mode: data_stream
    tls:
      verify_certificate: false
    type: elasticsearch
sources:
  app-logs-input:
    auto_offset_reset: earliest
    bootstrap_servers: ${KAFKA_BOOTSTRAP_SERVER}
    decoding:
      codec: json
    group_id: eks-logs
    tls:
      ca_file: /secrets/ca.pem
      crt_file: /secrets/cert.pem
      enabled: true
      key_file: /secrets/key.pem
    topic_key: log_topic
    topics:
    - ^app-logs.+$
    type: kafka
  app-logs-input-2:
    auto_offset_reset: earliest
    bootstrap_servers: ${KAFKA_BOOTSTRAP_SERVER}
    decoding:
      codec: json
    group_id: eks-logs
    tls:
      ca_file: /secrets/ca.pem
      crt_file: /secrets/cert.pem
      enabled: true
      key_file: /secrets/key.pem
    topic_key: log_topic
    topics:
    - ^app-logs2.+$
    type: kafka
transforms:
  app-logs-transforms:
    inputs:
    - app-logs-input
    - app-logs-input-2
    source: |-
      value_len_limit = 32000
      exclude_keys = [
          "container_hash",
          "docker_id",
          "pod_id",
          "pod-template-hash"
      ]
        
      if !exists(.kubernetes.namespace_name) {
        .kubernetes.namespace_name = "nonamespace"
      }
        
      # Modify keys with dots in name
      . = map_keys(., recursive: true) -> |key| {
          if starts_with(key, "kubernetes") {
              key
          } else {
              replace(key, ".", "_")
          }
      }
          
      . = flatten(object(.))
          
      # map to store the transformed results
      transformed_map = {}
          
      for_each(.) -> |key, value| {
          # Mask sensitive keys
          if contains(key, "password", case_sensitive: false) || contains(key, "token", case_sensitive: false) {
              transformed_map = set!(transformed_map, [key], "[REDACTED]")
          } else {
              transformed_map = set!(transformed_map, [key], value)
          }
          # Remove keys from excluded list
          for_each(exclude_keys) -> |_index, value| {
             if contains(key, value, case_sensitive: false) {
               transformed_map = remove!(transformed_map, [key])
             }
          }
      }
          
      # Output the new map
      . = transformed_map
          
      # Mask Bearer in log message
      . = map_values(.) -> |value| {
          if is_string(value) {
              value = redact(string(value),filters: [r'Bearer\s+[a-zA-Z0-9_=.-]+'])
              truncate(value, limit: value_len_limit, suffix: "...")
          }
      }
          
      . = compact(.)
          
      if !exists(.kubernetes.namespace_name) {
        log(., level: "error", rate_limit_secs: 60)
        log(.kubernetes.namespace_name, level: "error", rate_limit_secs: 60)
      }
    type: remap
```

### Version

0.39.0

### Example Data

```json
{
  "@timestamp": "2024-06-24T18:54:00.259096Z",
  "_p": "F",
  "kubernetes.container_image": "quay.io/strimzi/kafka:0.39.0-kafka-3.6.1",
  "kubernetes.container_name": "cruise-control",
  "kubernetes.host": "ip-XX-XXX-XX-XXX.XXX.compute.internal",
  "kubernetes.labels.app_kubernetes_io/instance": "kafka-1",
  "kubernetes.labels.app_kubernetes_io/managed-by": "strimzi-cluster-operator",
  "kubernetes.labels.app_kubernetes_io/name": "cruise-control",
  "kubernetes.labels.app_kubernetes_io/part-of": "strimzi-kafka-1",
  "kubernetes.labels.env": "stable",
  "kubernetes.labels.release": "kafka-1",
  "kubernetes.labels.strimzi_io/cluster": "kafka-1",
  "kubernetes.labels.strimzi_io/component-type": "cruise-control",
  "kubernetes.labels.strimzi_io/kind": "Kafka",
  "kubernetes.labels.strimzi_io/name": "kafka-1-cruise-control",
  "kubernetes.namespace_name": "kafka",
  "kubernetes.pod_name": "kafka-1-cruise-control-6d76c9759-r4ndt",
  "kubernetes_cluster": "dev",
  "kubernetes_node": "ip-XX-XXX-XX-XXX.XXX.compute.internal",
  "log": "2024-06-24 18:54:00 INFO  AbstractAsyncRequest:49 - Processing async request CruiseControlStateRequest.",
  "log_topic": "eks-logging",
  "logging_topic": "eks-logging",
  "source_type": "kafka",
  "stream": "stdout",
  "time": "2024-06-24T18:54:00.259096875Z"
}
```

### Additional Context

Vector is running as Stateless-Aggregator, deployed by Helm from official Helm Chart
[Playground shows result](https://playground.vrl.dev/?state=eyJwcm9ncmFtIjoiICAgICAgdmFsdWVfbGVuX2xpbWl0ID0gMzIwMDBcbiAgICAgIGV4Y2x1ZGVfa2V5cyA9IFtcbiAgICAgICAgICBcImNvbnRhaW5lcl9oYXNoXCIsXG4gICAgICAgICAgXCJkb2NrZXJfaWRcIixcbiAgICAgICAgICBcInBvZF9pZFwiLFxuICAgICAgICAgIFwicG9kLXRlbXBsYXRlLWhhc2hcIlxuICAgICAgXVxuICAgICAgICBcbiAgICAgIGlmICFleGlzdHMoLmt1YmVybmV0ZXMubmFtZXNwYWNlX25hbWUpIHtcbiAgICAgICAgLmt1YmVybmV0ZXMubmFtZXNwYWNlX25hbWUgPSBcIm5vbmFtZXNwYWNlXCJcbiAgICAgIH1cbiAgICAgICAgXG4gICAgICAjIE1vZGlmeSBrZXlzIHdpdGggZG90cyBpbiBuYW1lXG4gICAgICAuID0gbWFwX2tleXMoLiwgcmVjdXJzaXZlOiB0cnVlKSAtPiB8a2V5fCB7XG4gICAgICAgICAgaWYgc3RhcnRzX3dpdGgoa2V5LCBcImt1YmVybmV0ZXNcIikge1xuICAgICAgICAgICAgICBrZXlcbiAgICAgICAgICB9IGVsc2Uge1xuICAgICAgICAgICAgICByZXBsYWNlKGtleSwgXCIuXCIsIFwiX1wiKVxuICAgICAgICAgIH1cbiAgICAgIH1cbiAgICAgICAgICBcbiAgICAgIC4gPSBmbGF0dGVuKG9iamVjdCguKSlcbiAgICAgICAgICBcbiAgICAgICMgbWFwIHRvIHN0b3JlIHRoZSB0cmFuc2Zvcm1lZCByZXN1bHRzXG4gICAgICB0cmFuc2Zvcm1lZF9tYXAgPSB7fVxuICAgICAgICAgIFxuICAgICAgZm9yX2VhY2goLikgLT4gfGtleSwgdmFsdWV8IHtcbiAgICAgICAgICAjIE1hc2sgc2Vuc2l0aXZlIGtleXNcbiAgICAgICAgICBpZiBjb250YWlucyhrZXksIFwicGFzc3dvcmRcIiwgY2FzZV9zZW5zaXRpdmU6IGZhbHNlKSB8fCBjb250YWlucyhrZXksIFwidG9rZW5cIiwgY2FzZV9zZW5zaXRpdmU6IGZhbHNlKSB7XG4gICAgICAgICAgICAgIHRyYW5zZm9ybWVkX21hcCA9IHNldCEodHJhbnNmb3JtZWRfbWFwLCBba2V5XSwgXCJbUkVEQUNURURdXCIpXG4gICAgICAgICAgfSBlbHNlIHtcbiAgICAgICAgICAgICAgdHJhbnNmb3JtZWRfbWFwID0gc2V0ISh0cmFuc2Zvcm1lZF9tYXAsIFtrZXldLCB2YWx1ZSlcbiAgICAgICAgICB9XG4gICAgICAgICAgIyBSZW1vdmUga2V5cyBmcm9tIGV4Y2x1ZGVkIGxpc3RcbiAgICAgICAgICBmb3JfZWFjaChleGNsdWRlX2tleXMpIC0%2BIHxfaW5kZXgsIHZhbHVlfCB7XG4gICAgICAgICAgICAgaWYgY29udGFpbnMoa2V5LCB2YWx1ZSwgY2FzZV9zZW5zaXRpdmU6IGZhbHNlKSB7XG4gICAgICAgICAgICAgICB0cmFuc2Zvcm1lZF9tYXAgPSByZW1vdmUhKHRyYW5zZm9ybWVkX21hcCwgW2tleV0pXG4gICAgICAgICAgICAgfVxuICAgICAgICAgIH1cbiAgICAgIH1cbiAgICAgICAgICBcbiAgICAgICMgT3V0cHV0IHRoZSBuZXcgbWFwXG4gICAgICAuID0gdHJhbnNmb3JtZWRfbWFwXG4gICAgICAgICAgXG4gICAgICAjIE1hc2sgQmVhcmVyIGluIGxvZyBtZXNzYWdlXG4gICAgICAuID0gbWFwX3ZhbHVlcyguKSAtPiB8dmFsdWV8IHtcbiAgICAgICAgICBpZiBpc19zdHJpbmcodmFsdWUpIHtcbiAgICAgICAgICAgICAgdmFsdWUgPSByZWRhY3Qoc3RyaW5nKHZhbHVlKSxmaWx0ZXJzOiBbcidCZWFyZXJcXHMrW2EtekEtWjAtOV89Li1dKyddKVxuICAgICAgICAgICAgICB0cnVuY2F0ZSh2YWx1ZSwgbGltaXQ6IHZhbHVlX2xlbl9saW1pdCwgc3VmZml4OiBcIi4uLlwiKVxuICAgICAgICAgIH1cbiAgICAgIH1cbiAgICAgICAgICBcbiAgICAgIC4gPSBjb21wYWN0KC4pXG4iLCJldmVudCI6eyJAdGltZXN0YW1wIjoiMjAyNC0wNi0yNFQxODo1NDowMC4yNTkwOTZaIiwiX3AiOiJGIiwia3ViZXJuZXRlcy5jb250YWluZXJfaW1hZ2UiOiJxdWF5LmlvL3N0cmltemkva2Fma2E6MC4zOS4wLWthZmthLTMuNi4xIiwia3ViZXJuZXRlcy5jb250YWluZXJfbmFtZSI6ImNydWlzZS1jb250cm9sIiwia3ViZXJuZXRlcy5ob3N0IjoiaXAtWFgtWFhYLVhYLVhYWC5YWFguY29tcHV0ZS5pbnRlcm5hbCIsImt1YmVybmV0ZXMubGFiZWxzLmFwcF9rdWJlcm5ldGVzX2lvL2luc3RhbmNlIjoia2Fma2EtMSIsImt1YmVybmV0ZXMubGFiZWxzLmFwcF9rdWJlcm5ldGVzX2lvL21hbmFnZWQtYnkiOiJzdHJpbXppLWNsdXN0ZXItb3BlcmF0b3IiLCJrdWJlcm5ldGVzLmxhYmVscy5hcHBfa3ViZXJuZXRlc19pby9uYW1lIjoiY3J1aXNlLWNvbnRyb2wiLCJrdWJlcm5ldGVzLmxhYmVscy5hcHBfa3ViZXJuZXRlc19pby9wYXJ0LW9mIjoic3RyaW16aS1rYWZrYS0xIiwia3ViZXJuZXRlcy5sYWJlbHMuZW52Ijoic3RhYmxlIiwia3ViZXJuZXRlcy5sYWJlbHMucmVsZWFzZSI6ImthZmthLTEiLCJrdWJlcm5ldGVzLmxhYmVscy5zdHJpbXppLmlvL2NsdXN0ZXIiOiJrYWZrYS0xIiwia3ViZXJuZXRlcy5sYWJlbHMuc3RyaW16aS5pby9jb21wb25lbnQtdHlwZSI6ImNydWlzZS1jb250cm9sIiwia3ViZXJuZXRlcy5sYWJlbHMuc3RyaW16aS5pby9raW5kIjoiS2Fma2EiLCJrdWJlcm5ldGVzLmxhYmVscy5zdHJpbXppLmlvL25hbWUiOiJrYWZrYS0xLWNydWlzZS1jb250cm9sIiwia3ViZXJuZXRlcy5uYW1lc3BhY2VfbmFtZSI6ImthZmthIiwia3ViZXJuZXRlcy5wb2RfbmFtZSI6ImthZmthLTEtY3J1aXNlLWNvbnRyb2wtNmQ3NmM5NzU5LXI0bmR0Iiwia3ViZXJuZXRlc19jbHVzdGVyIjoiZGV2Iiwia3ViZXJuZXRlc19ub2RlIjoiaXAtWFgtWFhYLVhYLVhYWC5YWFguY29tcHV0ZS5pbnRlcm5hbCIsImxvZyI6IjIwMjQtMDYtMjQgMTg6NTQ6MDAgSU5GTyAgQWJzdHJhY3RBc3luY1JlcXVlc3Q6NDkgLSBQcm9jZXNzaW5nIGFzeW5jIHJlcXVlc3QgQ3J1aXNlQ29udHJvbFN0YXRlUmVxdWVzdC4iLCJsb2dfdG9waWMiOiJla3MtbG9nZ2luZyIsImxvZ2dpbmdfdG9waWMiOiJla3MtbG9nZ2luZyIsInNvdXJjZV90eXBlIjoia2Fma2EiLCJzdHJlYW0iOiJzdGRvdXQiLCJ0aW1lIjoiMjAyNC0wNi0yNFQxODo1NDowMC4yNTkwOTY4NzVaIn0sImlzX2pzb25sIjpmYWxzZSwiZXJyb3IiOm51bGx9) without any problem

**Comment by vosmax** [comment]
Hey @jszwedko! Thank you for your reply! 
Is flattening also related to sink template resolving? 
```
2024-06-24T18:54:06.150178Z ERROR sink{component_kind="sink" component_id=app-logs-output component_type=elasticsearch}: vector::internal_events::template: Failed to render template for "data_stream.namespace". error=Missing fields on event: ["kubernetes.namespace_name"] error_type="template_failed" stage="processing" internal_log_rate_limit=true
```

**Comment by jszwedko** [comment]
> Hey @jszwedko! Thank you for your reply! Is flattening also related to sink template resolving?
> 
> ```
> 2024-06-24T18:54:06.150178Z ERROR sink{component_kind="sink" component_id=app-logs-output component_type=elasticsearch}: vector::internal_events::template: Failed to render template for "data_stream.namespace". error=Missing fields on event: ["kubernetes.namespace_name"] error_type="template_failed" stage="processing" internal_log_rate_limit=true
> ```

Ah, yes, the issue there is likely to be the same. You'll want to use `{{ ."data_stream.namespace" }}`

**Comment by jszwedko** [comment]
I'll close this out since it seems to have been resolved but feel free to leave any additional questions.
