### ISSUE TITLE
Support reading auth token from file

### ISSUE THREAD

**Issue by nfs950512** [vectordotdev/vector#20747]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

I am deploying vector in k8s and I am trying to scrape metrics from cadvisor. For that vector would need to be configured to using the content in mounted serviceaccount token file `/var/run/secrets/kubernetes.io/serviceaccount/token`

equivalent curl command:
`curl -k -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes.default.svc/api/v1/nodes/ns1/proxy/metrics/cadvisor`

Vector only supports specifying the token value under auth.token

### Proposal

Proposing vector to add an option to read auth.token from a file.

**Comment by jszwedko** [comment]
Thanks @nfs950512 ! There is a PR that started implementing this feature, https://github.com/vectordotdev/vector/pull/20138, with some discussion there.

**Comment by nfs950512** [comment]
Appreciated!

**Comment by jszwedko** [comment]
I think we can leave this request open until it is implemented for others to find it.
