### ISSUE TITLE
Chunked GELF Decoding

### ISSUE THREAD

**Issue by jorgehermo9** [vectordotdev/vector#20769]
Relates to #13292.

As stated in [this comment](https://github.com/vectordotdev/vector/issues/13292#issuecomment-1333968625) we should start the chunked gelf support with the decoding part. The implementation should be based on [graylog's docs](https://go2docs.graylog.org/5-0/getting_in_log_data/gelf.html).

I'm currently woking on this and I have an initial implementation. Will submit a PR addressing this.

**Comment by jszwedko** [comment]
Thanks for the PR for this @jorgehermo9 !
