### ISSUE TITLE
Documentation bug leading to 404 for unit tests

### ISSUE THREAD

**Issue by s01ipsist** [vectordotdev/vector#20802]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

https://vector.dev/docs/reference/vrl/
has a malformed hyperlink in the text
```
When writing [unit tests](https://vector.dev/docs/reference/configuration//unit-tests)
```
due to a double slash in the path which causes a 404 when following the link.

The source link in https://github.com/vectordotdev/vector/blob/master/website/cue/reference/remap/concepts/assertions.cue#L13
uses the lookup from
https://github.com/vectordotdev/vector/blob/master/website/cue/reference/urls.cue#L631

`vector_configuration` ends in a `/` but `vector_unit_tests` also uses a slash to separate the components of `"\(vector_configuration)/unit-tests"`

There are many values in this file which use the `/docs/reference/configuration` path, but only `vector_unit_tests` tries to use the `vector_configuration` reference. Suggest that this is standardised to
```
vector_unit_tests:                          "/docs/reference/configuration/unit-tests"
```
for consistency and to fix the 404

### Version

0.39.0

**Comment by jszwedko** [comment]
Thanks! I opened https://github.com/vectordotdev/vector/pull/20819 to fix this.
