### ISSUE TITLE
Update URL path joining to use common method

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#20817]
A number of our components use ad hoc methods to join two URL component paths together. As seen in #20810, this can result in errors in remote services, particularly destinations of sinks, where the joining results in doubled slashes. We should sweep all components for such usages and fix them with a common function like the `merge_url_and_key` introduced in the above PR.

I've labelled this as "tech debt", but technically it s a bug-in-waiting, as it can potentially be triggered by a typo in configuration depending on the components.

**Comment by jszwedko** [comment]
This is a good idea, but I think it's an example of an issue we'd never pick up on its own merits. Given that, the pattern we've used for this sort of thing is just to add a `TODO` to the code that could be picked up when someone is in the area implementing some other change.

**Comment by jszwedko** [comment]
I would support bug reports for specific options that don't handle this correctly though.
