### ISSUE TITLE
Some log lines may randomly lack initial symbols

### ISSUE THREAD

**Issue by crt0r** [vectordotdev/vector#20914]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hello, Vector community!

## Context

We use Vector to collect NGINX logs from a reverse proxy for over a dozen of websites.
The logs are written in the default *combined* NGINX format.

Data is ingested into ClickHouse for further analysis via Grafana. 
In addition to parsed data split into different fields, we also collect the original *message* field.

## The Problem

Recently, I noticed that some of the ingested access log messages lack several bytes at the start, even though they are totally OK in the log files.
This is the case for several dozens of records out of over 173 million.

---

I've attached a couple of screenshots redacted for privacy as well as a [CSV containing an export from ClickHouse](https://github.com/user-attachments/files/16350531/malformed_client_ips_export.csv).

Please, let me know if you want me to provide more debugging information!

Thank you in advance!

![Example record with a malformed message inside of ClickHouse](https://github.com/user-attachments/assets/97a9a18a-4218-4332-b866-f0e1a168a815)

![Example valid log messages in the log file](https://github.com/user-attachments/assets/f998daa4-881b-4358-9de5-2dc6f8bc4f82)

### Configuration

```text
sources:
  access:
    type: file
    include:
    - /var/log/nginx/access.log
    - /var/log/nginx/*/*access.log

  error:
    type: file
    include:
    - /var/log/nginx/error.log
    - /var/log/nginx/*/*error.log

transforms:
  nginx-access-parsed:
    type: remap
    inputs:
    - access
    source: |
      ._type = "access"
      ._message = .message

      parsed_data, err = parse_nginx_log(.message, "combined")

      if err == null {
        . |= parsed_data

        site_name, regex_err = parse_regex(.file, r'(?<value>[A-Za-z0-9:\.-]+)-(access|error)\.log$')

        if regex_err == null {
            .site_name = site_name.value
        } else {
            .site_name = "-"
        }

      } else {
        log(err, "error")
        ._message = string!(err) + ". Original message: \"" + string!(._message) + "\""
      }

      .timestamp = to_int(to_unix_timestamp(parse_timestamp!(.timestamp, "%d/%b/%Y:%T %z")))

      del(.source_type)
      del(.message)

  nginx-error-parsed:
    type: remap
    inputs:
    - error
    source: |
      ._type = "error"
      ._message = .message
      .timestamp = to_int(to_unix_timestamp(parse_timestamp!(.timestamp, "%Y/%m/%d %H:%M:%S")))

      site_name, regex_err = parse_regex(.file, r'(?<value>[A-Za-z0-9:\.-]+)-(access|error)\.log$')

      if regex_err == null {
          .site_name = site_name.value
      } else {
          .site_name = "-"
      }

      del(.message)
      del(.source_type)

sinks:
  clickhouse:
    inputs:
    - nginx-access-parsed
    - nginx-error-parsed
    type: clickhouse
    database: nginx
    table: '{{ ._type }}'
    endpoint: '${CLICKHOUSE_ENDPOINT}'
    batch:
      timeout_secs: 5
    auth:
      strategy: basic
      user: '${CLICKHOUSE_USER}'
      password: '${CLICKHOUSE_PASSWORD}'
```

### Version

vector 0.39.0 (x86_64-unknown-linux-gnu 73da9bb 2024-06-17 16:00:23.791735272)

## Table Schemas for NGINX Logs in ClickHouse

```sql
CREATE TABLE nginx.access
(
    `timestamp`   DateTime,
    `_message`    String DEFAULT '',
    `file`        String DEFAULT '',
    `host`        String DEFAULT '',
    `agent`       String DEFAULT '',
    `client`      String DEFAULT '',
    `compression` String DEFAULT '',
    `referer`     String DEFAULT '',
    `request`     String DEFAULT '',
    `size`        Nullable(UInt64) DEFAULT NULL,
    `status`      Nullable(UInt16) DEFAULT NULL,
    `user`        String DEFAULT '',
    `site_name`   String DEFAULT '-',
    `_id`         FixedString(26) DEFAULT generateULID()
)
ENGINE = MergeTree
ORDER BY timestamp
TTL timestamp + toIntervalDay(15);

CREATE TABLE nginx.error
(
    `timestamp`  DateTime,
    `_message`   String DEFAULT '',
    `file`       String DEFAULT '',
    `host`       String DEFAULT '',
    `site_name`  String DEFAULT '-'
)
ENGINE = MergeTree
ORDER BY timestamp
TTL timestamp + toIntervalDay(15);
```

**Comment by jszwedko** [comment]
Thanks for this report @crt0r . I think it is the same as https://github.com/vectordotdev/vector/issues/10025 so I'll close this one as a duplicate, but let me know if you think this is a different issue. I appreciate the additional context you added here.

**Comment by crt0r** [comment]
Thanks! Yes, this is the exact problem I have.

I tried to search for a duplicate before posting, but that was unsuccessful. Sorry for that 😅.

**Comment by crt0r** [comment]
Maybe this would be helpful, there's one important detail.

We rotate NGINX logs using *logrotate* every one hour.
