### ISSUE TITLE
HTTP Source returns 200 for errored events

### ISSUE THREAD

**Issue by frankh** [vectordotdev/vector#20990]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

 any events sent to an http server that fail will not be written to the sink. Despite this, all requests return 200 responses, which the client will take to mean the event has been persisted to the sink     

see the example configuration
      

### Configuration

```text
sources:
  capture_server:
    type: http_server
    address: 0.0.0.0:8000
    strict_path: false
    query_parameters:
      - _
    host_key: ip
    decoding:
      codec: vrl
      vrl:
        source: |
          . = parse_json!(.message)

transforms:
  event_error:
    type: remap
    inputs:
      - capture_server
    drop_on_abort: false
    drop_on_error: false
    source: |
      assert!(false, "oh my gahd")

sinks:
  quota_limited:
    type: file
    path: file.db
    encoding:
      codec: json
    acknowledgements:
      enabled: true
    inputs:
      - event_error
 ```
```


### Version

0.40

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

**Comment by jszwedko** [comment]
Hi @frankh ,

By default, the `http_server` source will return 200 as soon as it has ingested the events into Vector. If you want it to wait until the sink has processed the events successfully please take a look at https://vector.dev/docs/about/under-the-hood/architecture/end-to-end-acknowledgements/

I'll close this since the behavior is intended, but let me know if you have any additional questions!

**Comment by jszwedko** [comment]
Mmm, I thought that page linked to configuration examples, but it doesn't. See it for an explanation of how the feature works, but https://vector.dev/docs/reference/configuration/sinks/file/#acknowledgements.enabled is the configuration option you want.

**Comment by frankh** [comment]
i included 

```
    acknowledgements:
      enabled: true
```

in the sink (and also globally in my config), but it's still returning 200 immediately

**Comment by jszwedko** [comment]
Doh, sorry, I missed that you did have it configured in the sink already. I'll reopen this to be investigated.

**Comment by frankh** [comment]
Looks like it's the same as this: https://github.com/vectordotdev/vector/issues/12217

**Comment by jszwedko** [comment]
Good catch, this does look to be the same as https://github.com/vectordotdev/vector/issues/12217. I'll close this one in-lieu of that one.
