### ISSUE TITLE
Measure console sink performance after `FramedWrite` removal

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#2099]
As part of the console sink hotfix #2096 we've removed `FramedWrite` from the implementation.

https://github.com/timberio/vector/pull/2096#issuecomment-601402243
> `FramedWrite` gave us some buffering on the output. Did we lose that here? Might be worth checking if throughput changed at all.

We should measure if there's an effect on performance.

**Comment by jszwedko** [comment]
We plan to let profiling lead us to additional performance changes.
