### ISSUE TITLE
Internal metrics to get the response time (RTT) of an http sink

### ISSUE THREAD

**Issue by mattzech** [vectordotdev/vector#20992]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

In our grafana dashboard, we had the following metric to show the response time of our sinks to the logging endpoint (Scalyr in this case):
```
sum(increase(vector_http_client_response_rtt_seconds_bucket{component_name="scalyr", cluster="$cluster"}[$__interval])) by (le)
```
The above query works great for Splunk, but according to [docs](https://vector.dev/docs/reference/configuration/sinks/http/#telemetry-metrics) this is not available for HTTP Sinks.

I was wondering if you had any suggestions for an alternative metric to use here?

### Configuration

```text
scalyr:
        type: http
        inputs:
        - scalyr_reducer
        buffer:
          type: disk
          # 100GB
          max_size: 107374182400
          when_full: block
        batch:
          max_events: 1
          max_bytes: 107170620
        compression: gzip
        method: "post"
        request:
          headers:
            content-type: "application/json;charset=UTF-8"
        framing:
          method: newline_delimited
        encoding:
          timestamp_format: unix
          codec: json
          only_fields:
          - token
          - session
          - sessionInfo
          - events
          - threads
        uri: https://app.scalyr.com/api/addEvents
```

### Version

0.39.0

**Comment by jszwedko** [comment]
I'm guessing it is just undocumented. @mattzech could you confirm that you don't see the metric for the `http` sink?

**Comment by mattzech** [comment]
Hey @jszwedko 
I played around with it some more. Turns out the `cluster` parameter was the problem. Switched it to `agent_tag_cluster="$cluster"` and the metrics came up again. Thanks for the help
