### ISSUE TITLE
Honeycomb sink is hardcoded to US endpoint, causing errors for customers in the EU

### ISSUE THREAD

**Issue by huntipl** [vectordotdev/vector#20994]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Currently the honeycomb sink is hardcoded to use US endpoint `api.honeycomb.io:443` and explicitly does not allow changing it, there is now an EU endpoint `api.eu1.honeycomb.io:443` and not being able to set it causes errors 

> (unknown API key - check your credentials, region, and API URL) 

sending telemetry to the EU account.

### Version

v0.40.0

**Comment by jszwedko** [comment]
Thanks for this report @huntipl ! It does appear to be hardcoded. ➕ to adding a configurable option.

**Comment by award28** [comment]
Looks like this was resolved in #21147

**Comment by jszwedko** [comment]
Indeed, thanks @award28 . Closed by https://github.com/vectordotdev/vector/pull/21147
