### ISSUE TITLE
Reimplement `crate::event::util::log::remove::remove` function without recursion

### ISSUE THREAD

**Issue by a-rodin** [vectordotdev/vector#2104]
Currently [`crate::event::util::log::remove::remove`](https://github.com/timberio/vector/blob/c8b47b3230a4b790d8cda0e47265771666581f98/src/event/util/log/remove.rs#L4-L23) function is implemented using recursion. However, it can in principle be reimplemented without recursion using `O(1)` memory and without function call overhead.

If we proceed with doing this, there should be two steps:
* [ ] Add a new implementation without recursion.
* [ ] Add benchmarks for it to `benches` and measure the peformance improvements.

**Comment by jszwedko** [comment]
Closing to let profiling guide this sort of enhancement.
