### ISSUE TITLE
Vector is broken in Nixpkgs

### ISSUE THREAD

**Issue by Scandiravian** [vectordotdev/vector#21127]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Rust 1.80 unfortunately broke a lot of packages, including Vector. Currently it's not possible to build Vector on NixOS due to this; the issue for packages broken by Rust 1.80 is tracked here: https://github.com/NixOS/nixpkgs/issues/332957.

I can see that PR #20949 to update Vector to Rust 1.80 is underway, but I couldn't find any issues mentioning, that the Nixpkgs build is currently broken, so I wanted to make sure that you were aware of the issue downstream since your docs has a section on installing Vector on NixOS, which currently doesn't work.

### Version

0.40

**Comment by jszwedko** [comment]
Thanks for this note @Scandiravian . The nixos packages are actually maintained by the community. cc/ @jpds for awareness since you've been doing the most work on that lately :) It sounds like the path forward is just to finish the upgrade to Rust 1.80?

**Comment by Scandiravian** [comment]
> Thanks for this note @Scandiravian . The nixos packages are actually maintained by the community. cc/ @jpds for awareness since you've been doing the most work on that lately :) It sounds like the path forward is just to finish the upgrade to Rust 1.80?

Thanks for your reply; sorry if I didn't make it clear, that I was aware of the nixpkg being community maintained. Since a config for NixOS is in the docs for Vector, I thought it would be important for you to know that the downstream build that the docs depend on is broken. Hope that clears things up a bit :blush: 

I appreciate that you're prioritizing the update to 1.80, since it's difficult to fix the build downstream. Thanks again for taking the time to reply to the ticket :+1:

**Comment by jpds** [comment]
Fixed in https://github.com/NixOS/nixpkgs/commit/7d9c3fd5ccff13a2799e5679df50e87939318cb9 and also https://github.com/NixOS/nixpkgs/pull/337564

**Comment by jszwedko** [comment]
Thanks @jpds !

I'll close this out, but we are still working on upgrading the version of Rust used to 1.80 too.
