### ISSUE TITLE
Inaccurate documentation of framing.character_delimited.delimiter

### ISSUE THREAD

**Issue by andrewthad** [vectordotdev/vector#21121]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Vector's published documentation describes the type of `framing.character_delimited.delimiter` as `uint`. However, when I try to supply 10 (the codepoint for a newline), I get this error:

    Configuration error. error=invalid type: integer `10`, expected a character

I suspect this just an oversight involving the metadata used to generate the docs.

### Version

0.41.0

**Comment by jszwedko** [comment]
Thanks for reporting this. I think the same change that was made in https://github.com/vectordotdev/vector/commit/5a10aa2b0556563d11244b04829a72d86a8e338b for the CSV decoder delimiter needs to be made for the framing delimiter.
