### ISSUE TITLE
GELF codec should support compression

### ISSUE THREAD

**Issue by flyingflo** [vectordotdev/vector#21153]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Currently, the GELF codec fails to decode compressed messages received via UDP. 

[GELF](https://go2docs.graylog.org/current/getting_in_log_data/gelf.html) supports compression:

> When using UDP as transport layer, GELF messages can be sent uncompressed or compressed with either GZIP or ZLIB.
> Graylog nodes automatically detect the compression type in the GELF magic byte header.
> Decide if you want to trade a bit more CPU load for saving network bandwidth. GZIP is the protocol default.

### Attempted Solutions

If I understand that correctly, decompression is just not  yet implemented.

### Proposal

The[ Graylog GELF decoder](https://github.com/Graylog2/graylog2-server/blob/6dab8975f5d80c90e6346f1fcab30af11bcadf19/graylog2-server/src/main/java/org/graylog2/inputs/codecs/gelf/GELFMessage.java#L108) decides whether it is gzip, zlib, or uncompressed by looking a the magic numbers in the first bytes, then decompress accordingly. It also detects Chunking (#13292) this way.

### References

#13292
#4868

**Comment by flyingflo** [comment]
Another example in [Go from grafana](https://github.com/grafana/go-gelf/blob/1cbd6368efe24cfa12574d988b4f0653ed5123e2/gelf/reader.go#L90).

I should learn Rust  :thinking:

**Comment by jorgehermo9** [comment]
I was planning to implement this once my PR #20859 is merged.

Actually, I have it kind of working, but wanted to wait until that is merged that PR is not bloated with a lot of changes.

I'll appreciate if you could wait until that #20859 is merged and I submit the decompression PR

@flyingflo

**Comment by jorgehermo9** [comment]
Hi @flyingflo. My PR https://github.com/vectordotdev/vector/pull/20859 just got merged. I'll start working into the decompression part asap.

**Comment by jorgehermo9** [comment]
Hi @flyingflo . Opened #21816 for addressing this. You can track this implementation there.

Feel free to build it from that branch and test if it works for your usecase
