### ISSUE TITLE
Add support to enrich OTLP data with kubernetes metadata

### ISSUE THREAD

**Issue by Sh4d1** [vectordotdev/vector#21239]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Some applications in kubernetes, might send out logs & traces to an otlp endpoint. Usually it's done with a "proxy" like otelcollector, or grafana alloy (which uses otelcollector IIRC). They both allow to add kubernetes metadata on the incoming traces or logs, based on source IP, or others. 

### Attempted Solutions

Currently, Vector can only attach kubernetes metadata to logs taken directly from the pods (which is a valid, and I guess the majority's case), but leave no other options to do what I describe above. 

### Proposal

I haven't looked that much at the kubernetes' logs source, but I think some code could be re-used to create a `kubernetes_pod` transform or something like that. 

### Version

0.40.1

**Comment by jszwedko** [comment]
Hi @Sh4d1 !

Thanks for opening this. I think it is a special case of the more general feature request to have a transform for k8s metadata enrichment: https://github.com/vectordotdev/vector/issues/5077. I'll close this one in-lieu of that one, but let me know if you disagree.

**Comment by Sh4d1** [comment]
Perfect thanks I missed it, my bad!
