### ISSUE TITLE
Add nested field does not work in Lua transform

### ISSUE THREAD

**Issue by alexeynl** [vectordotdev/vector#21240]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Can't add nested field to my log as states in documentation:

![image](https://github.com/user-attachments/assets/7b1a0d51-f6f4-4b08-aefe-def6fe42565e)

https://vector.dev/docs/reference/configuration/transforms/lua/#examples

If event.log.nested field in the example below does not exist i get the error:

024-09-09T14:58:59.322460Z ERROR transform{component_kind="transform" component_id=test_parser component_type=lua}: vector::internal_events::lua: Error in building lua script. error=RuntimeErrorHooksProcess { source: RuntimeError("[string \"src/transforms/lua/v2/mod.rs:231:9\"]:3: attempt to index a nil value (field 'nested')\nstack traceback:\n\t[C]: in metamethod 'newindex'\n\t[string \"src/transforms/lua/v2/mod.rs:231:9\"]:3: in function <[string \"src/transforms/lua/v2/mod.rs:231:9\"]:1>") } error_type="script_failed" error_code="runtime_error_hook_process" stage="processing" internal_log_rate_limit=true

### Configuration

```text
test_parser:
    inputs:
      - parse_xml
    type: lua
    version: "2"
    hooks:
      process: |-
        function (event, emit)
          event.log.nested.test = "test"
          emit(event)
        end
```

### Version

0.40.0

**Comment by jszwedko** [comment]
I think you need to do:

```
event.log.nested = {}
event.log.nested.field = "nested field"
```

Lua doesn't allow indexing into fields that aren't set. I see the example needs to be updated. Let me do that.

**Comment by alexeynl** [comment]
Yes, i'am aware about this workaround, but 

1. Why the documentation states it is possible? It is is not possible to create nested field this way i think documentation require to be change.
2.

**Comment by jszwedko** [comment]
> 2\. This is not a good option:
> 
> ```
> event.log.nested = {}
> event.log.nested.field = "nested field"
> ```
> 
> Because in this case if event.log.nested is exist it will be rewrited. So i need check is event.log.nested is exist every time i assing it to blank object (`event.log.nested = {}`).
> 
> Moreover if i need create more nested field like this: `event.log.nested.nested.field = "test"` i need to
> 
> 1. check event.log.nested is not exist.
> 2. check event.log.nested.log.nested is not exist.
> 3. create event.log.nested: `event.log.nested = {}`
> 4. create event.log.nested.nested: `event.log.nested.nested{}`
>    And so on. The code become too complex for more level nests.

That's correct, but unfortunately that is a limitation of Lua and so not something that we can change.

**Comment by alexeynl** [comment]
> unfortunately that is a limitation of Lua and so not something that we can change.
Ok i understand...
Thank you for clarification and fixing docs.
