### ISSUE TITLE
Vector source: Invalid source_event_id in metadata

### ISSUE THREAD

**Issue by MiniPierre** [vectordotdev/vector#21252]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

After upgrading to Vector 0.41.0, this error occurred for every incoming message: `ERROR source{component_kind="source" component_id=source_vector component_type=vector}:grpc-request{grpc_service="vector.Vector" grpc_method="PushEvents"}: vector_core::event::proto: Invalid source_event_id in metadata`

Every incoming message comes from a Vector agent 0.40.0 using the vector sink
After rolling back the Vector server to 0.40.0, everything came back to normal

### Configuration

```text
---
# Agent configuration
sources:
  source1:
    type: "file"
    include:
      - "xxx"

transforms:
  filter1:
    type: "filter"
    inputs:
      - "source1"
    condition:
      type: "vrl"
      source: |-
        true

  filter2:
    type: "remap"
    inputs:
      - "filter1"
    source: |-
      .vector_environment = ["xxx"]
      .type = "xxx"

sinks:
  sink1:
    type: "vector"
    inputs:
      - "vector_*"
    address: "xxx"
    tls:
      enabled: true
    acknowledgements:
      enabled: true
    compression: true

---
# Server configuration
sources:
  source_vector:
    type: "vector"
    address: "[::]:6000"
```

### Version

0.41.0

**Comment by jszwedko** [comment]
Thanks for this report @MiniPierre ! It sounds like a regression. We are looking into it now.

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/21257. We'll release this tomorrow.
