### ISSUE TITLE
Malformed notice in VRL function documentation

### ISSUE THREAD

**Issue by jorgehermo9** [vectordotdev/vector#21251]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

In the newly introduced `parse_influxdb` vrl function, it seems that the notice section of the documentation is malformed for the first item 
<img width="1106" alt="image" src="https://github.com/user-attachments/assets/bb58c62b-6f69-4554-866e-40fa79a1dad2">

It looks like it is wrapped around backticks and seems like a markdown code box.

Is this intended or a bug?

https://vector.dev/docs/reference/vrl/functions/#parse_influxdb-notices

I see nothing weird here https://github.com/vectordotdev/vector/blob/da264a8139543309b5329a2c0db8a588b34233d9/website/cue/reference/remap/functions/parse_influxdb.cue#L11

### Version

0.41.0

**Comment by jszwedko** [comment]
I think this is just a whitespace formatting issue. I opened https://github.com/vectordotdev/vector/pull/21273 to fix it. Thanks for the report!
