### ISSUE TITLE
`vector` sink proxy disabling

### ISSUE THREAD

**Issue by jpds** [vectordotdev/vector#21315]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The `vector` sink appears to automagically enable HTTP proxy support (with no way of turning it off).

This caused me some issues where I was trying to send data from a locked down network, where on one hand I had a series of targets leveraging the automatic HTTP support (through environment variables), whilst wanting to send to another Vector instance without the HTTP proxy (and down a VPN tunnel instead).

### Version

0.41.0

**Comment by jszwedko** [comment]
What do you mean by "automagically"? Vector does support the normal `http(s)_proxy` environment variables. If those are set, the values will be respected. Is that what you mean?

**Comment by jpds** [comment]
@jszwedko Yes, indeed. In this case, those are useful for the sources I have configured, but I want to disable it just for this one sink.

**Comment by jszwedko** [comment]
Ah I see. I assume you tried setting: `proxy: { enabled: false }` on the sink you want to disable it on?

**Comment by pront** [comment]
Hmm, this sink is not checking the `enabled` field: 
https://github.com/vectordotdev/vector/blob/59b7c9ad55dff61ecc34be71f438e4a7f9826eb8/src/sinks/vector/config.rs#L213

We could also update `build_proxy_connector` to return an error when the `enabled == false` to avoid masking this issue.

**Comment by pront** [comment]
Disregard my previous comment, the [proxy](https://github.com/vectordotdev/vector/blob/master/lib/vector-core/src/config/proxy.rs#L196) implementation handle this correctly and doesn't add any proxies if it's disabled. However, `enabled` is `true` by default so you will have to manually disable in the global options:
```
proxy:
  enabled: false
```
