### ISSUE TITLE
vector_component_errors_total metric is empty even when there's an error on cloudwatch sink

### ISSUE THREAD

**Issue by rfum** [vectordotdev/vector#21339]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hello, 
I had a problem regarding to logs which I found out it wasn't directly related to vector. But when I'm trying to debug the issue even when there's no log flow from vector daemonset to cloudwatch sink, vector_component_errors_total metric was empty. It took me some time to find out root cause of the problem. 
vector instances with problem was printing the following warn log:

```
WARN sink{component_kind="sink" component_id=cloud_watch component_type=aws_cloudwatch_logs}:request{request_id=1}: vector::sinks::util::retries: Retrying after error. error=CloudwatchError::DescribeLogStreams: dispatch failure internal_log_rate_limit=true
```
Is this an expected behaviour or a bug? Could it be related to log level of the error message? 

### Configuration

```text
sinks:
      cloud_watch:
        auth:
          assume_role: arn:aws:iam::111111111111:role/foo
        group_name: foo-group
        inputs:
        - kubernetes_logs
        - internal_logs
        region: eu-central-1
        stream_name: bar-stream
        type: aws_cloudwatch_logs
      internal_metrics_sink:
        address: 0.0.0.0:9100
        inputs:
        - internal_metrics
        type: prometheus_exporter
    sources:
      internal_logs:
        type: internal_logs
      internal_metrics:
        type: internal_metrics
      kubernetes_logs:
        extra_namespace_label_selector: kubernetes.io/metadata.name!=kube-system
        type: kubernetes_logs
```

### Version

0.40.0

**Comment by jpds** [comment]
Same as #20515 .

**Comment by jszwedko** [comment]
Yeah, the issue here is that it is a warning rather than an error which is why `component_errors_total` isn't incremented. Retried errors generally are logged as warnings. I could see it being useful to have a separate `component_warnings_total` metric though if someone wanted to open a request for that.

**Comment by rfum** [comment]
@jszwedko I cannot understand the point of categorizing a connection error as WARN, that blocks whole data flow into a sink. This error blocked my deployment for a few days until I find the root cause. Wouldn't it be better to categorize this error as ERR instead of WARN, instead of creating a new metric for WARN ? I can understand it might be retried but I think after consuming an error budget it'd be better to mark it as an error instead of a warning.

**Comment by jszwedko** [comment]
> @jszwedko I cannot understand the point of categorizing a connection error as WARN, that blocks whole data flow into a sink. This error blocked my deployment for a few days until I find the root cause. Wouldn't it be better to categorize this error as ERR instead of WARN, instead of creating a new metric for WARN ? I can understand it might be retried but I think after consuming an error budget it'd be better to mark it as an error instead of a warning.

That's an interesting thought: that things consuming the "error budget" should be emitted as errors. Currently the definition of errors in Vector is those that cannot be recovered or retried and can possibly drop data. Warnings are used for operations that failed but will be retried.

I'm open to the thought that these guidelines for errors vs warnings should be rethought, but it'd be a fairly wide change to make. If someone is interested in proposing that change, I think an [RFC](https://github.com/vectordotdev/vector/blob/master/rfcs/README.md) would be the first step given the scope and impact.
