### ISSUE TITLE
HTTP Sink: Adaptive concurrency logic has deadlock when decrease_ratio < 0.5 

### ISSUE THREAD

**Issue by holdno** [vectordotdev/vector#21340]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

adaptive_concurrency: Controller.semaphore will deadlock when decrease_ratio < 0.5 and init_limit set like 10

codes: 
https://github.com/vectordotdev/vector/blob/f99e052b54fc9c32731694f258b30360e28b68ac/src/sinks/util/adaptive_concurrency/controller.rs#L229-L250

when decrease_ratio set to 0.3 and init_limit downgrade to 2
``` rust
to_forget  = 2 - (2 * 0.3) as usize;

(2 * 0.3) as usize = 0

to_forget = 2 - 0 = 2

self.semaphore.forget_permits(2);
```

semaphore will be zero if current requesting always get bad response

### Configuration

```text
request:
  adaptive_concurrency:
    decrease_ratio: 0.3
    ewma_alpha: 0.4
    initial_concurrency: 10
    max_concurrency_limit: 200
    rtt_deviation_scale: 2.5
```

### Version

vector 0.41.0

**Comment by bruceg** [comment]
Thanks for pointing this out @holdno. I have put up a quick fix in #21344.
