### ISSUE TITLE
Missing documentation for adaptive_concurrency metrics

### ISSUE THREAD

**Issue by tronboto** [vectordotdev/vector#21408]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

There is no documentation for the following metrics on the [internal metrics page](https://vector.dev/docs/reference/configuration/sources/internal_metrics):

- adaptive_concurrency_back_pressure
- adaptive_concurrency_past_rtt_mean
- adaptive_concurrency_reached_limit

### Version

0.41.1

**Comment by jszwedko** [comment]
Thanks @tronboto . These are indeed missing from the docs.

**Comment by tronboto** [comment]
Closing as dupe of https://github.com/vectordotdev/vector/issues/14904
