### ISSUE TITLE
Metric namespace in `log_to_metric` transform is mandatory 

### ISSUE THREAD

**Issue by jorgehermo9** [vectordotdev/vector#21423]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We were trying the newly introduced `parse_influxdb` vrl function, and as the [docs states](https://vector.dev/docs/reference/vrl/functions/#parse_influxdb), we should pass its output to a `log_to_metric` transform to generate Vector metric events from it (contrary to the `decoding.codec=influxdb`, which outputs _real_ metrics without the need of that transform)

We found that the `parse_influxdb` function does not output events with the namespace field
Example:
```json
{"gauge":{"value":82.0},"kind":"absolute","name":"weather_temperature","tags":{"location":"us-midwest"},"timestamp":"2016-06-13T17:43:50.100400200Z"}
```

And although in Vector's metric model the namespace is optional https://github.com/vectordotdev/vector/blob/88d6fe7faca520bd28eba308bf08846eb1823975/lib/vector-core/src/event/metric/series.rs#L99

It seems to be required by the `log_to_metric` transform https://github.com/vectordotdev/vector/blob/88d6fe7faca520bd28eba308bf08846eb1823975/src/transforms/log_to_metric.rs#L800

Should the `log_to_metric` transform to optionally populate the `namespace` field, only if present, and not fail if the namespace field is not present?

I can submit a PR addressing it, just want to ask if this is a desired behaviour

Thanks

### Configuration

```text
[sources.sample]
type = "demo_logs"
lines = ["weather,location=us-midwest temperature=82 1465839830100400200"]
format = "shuffle"

[transforms.influx]
type = "remap"
inputs = ["sample"]
source = """
. = parse_influxdb!(.message)
"""

[transforms.log_to_metric]
type = "log_to_metric"
inputs = ["influx"]
all_metrics = true
metrics = []

[sinks.console]
type = "console"
inputs = ["log_to_metric"]
encoding.codec = "json"
```

### Version

vector 0.41.1 (x86_64-unknown-linux-gnu)

**Comment by jszwedko** [comment]
Nice find @jorgehermo9 . `namespace` should, indeed, be optional. A PR would be more than welcome 🙂
