### ISSUE TITLE
Metric model website documentation shows `namespace` as required

### ISSUE THREAD

**Issue by jorgehermo9** [vectordotdev/vector#21430]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

In the [metric model documentation](https://vector.dev/docs/about/under-the-hood/architecture/data-model/metric/#namespace) the namespace field is depicted as required
![image](https://github.com/user-attachments/assets/5a504a33-964d-4ed7-9974-db5df839c97e)

But in the code, it is optional https://github.com/vectordotdev/vector/blob/3eecbe71635125d1f18af708e31cf23cc66a8536/lib/vector-core/src/event/metric/series.rs#L99 and we can create non-namespaced metric's (as done in https://github.com/vectordotdev/vector/pull/21429 with the `log_to_metric` transform)

Is this a documentation bug or is it intended?

### Version

vector 0.41.1 (x86_64-unknown-linux-gnu)

**Comment by jszwedko** [comment]
Thanks @jorgehermo9 ! I think that is a documentation bug.
