### ISSUE TITLE
vector_http_client_requests_sent_total and vector_http_client_rtt_seconds_count are the same

### ISSUE THREAD

**Issue by kefiras** [vectordotdev/vector#21451]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Both metrics are giving the same value but they are supposed to be different.
```
vector_http_client_requests_sent_total{component_id="splunk_container_logs",component_kind="sink",component_type="splunk_hec_logs",host="log-aggregator-1",method="POST"} 102011 1728395129922
vector_http_client_rtt_seconds_count{component_id="splunk_container_logs",component_kind="sink",component_type="splunk_hec_logs",host="log-aggregator-1"} 102011 1728395129922
```

### Configuration

```text
sources:
  vector_metrics:
    type: "internal_metrics"
sinks:
  prometheus_exporter:
    type: "prometheus_exporter"
    inputs:
      - "vector_metrics"
    address: "0.0.0.0:9100"
```

### Version

vector 0.36.0 (x86_64-unknown-linux-musl a5e48bb 2024-02-13 14:43:11.911392615)

**Comment by jszwedko** [comment]
Hi @kefiras !

Those may actually be the same since `vector_http_client_rtt_seconds` is a histogram so `_count` represents the total number of measurements, one per request, which should generally match `vector_http_client_requests_sent_total`. Let me know if that isn't clear.
