### ISSUE TITLE
Permission denied on Loki sink when used with disk buffer

### ISSUE THREAD

**Issue by P1YU5H-50N1** [vectordotdev/vector#21549]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Vector says permission denied when using a disk buffer. Below is the config being used

Now when I try to deploy it it throws an error saying 
```2024-10-18T14:33:53.217343Z ERROR vector::topology::builder: Configuration error. error=Sink "loki_iv_strike": error occurred when building buffer: failed to build individual stage 1: failed to load/create ledger: ledger I/O error: Permission denied (os error 13)```

### Configuration

```text
loki_sink:
    labels:
      type: "label_x"
    inputs:
      - "transform_y"
    type: "loki"
    endpoint: $VECTOR_LOKI_IP
    buffer:
    - type: memory
      max_events: 3000
      when_full: overflow
    - type: disk
      max_size: 1073741824 # 1GiB.
      when_full: drop_newest
    out_of_order_action: accept
    request:
      concurrency: adaptive
      retry_jitter_mode: Full
      retry_max_duration_secs: 30
      timeout_secs: 60 
      rate_limit_num: 700
    encoding:  
      codec: json
    compression: zstd
```

### Version

vector 0.41.1 (x86_64-unknown-linux-musl 745babd 2024-09-11 14:55:36.802851761)

### Debug Output

```text
2024-10-18T14:47:38.990970Z ERROR vector::topology::builder: Configuration error. error=Sink "loki_sink": error occurred when building buffer: failed to build individual stage 1: failed to load/create ledger: ledger I/O error: Permission denied (os error 13)
```

### Example Data

It fails on initialization

### Additional Context

I'm using the vector via binary installation as recommended [here](https://vector.dev/docs/setup/installation/)

**Comment by jszwedko** [comment]
Hi @P1YU5H-50N1 !

This would indicate that the user that the Vector process is running under doesn't have access to write to `/var/lib/vector` (the default data direcotry).

I'll close this out since it doesn't seem like bug, but let us know if you have trouble fixing file system permissions.

**Comment by P1YU5H-50N1** [comment]
Hey @jszwedko, 
Thanks a lot for the response
Is there any way to change the default data directory, apart from hosting it in a container?

**Comment by jszwedko** [comment]
> Hey @jszwedko, Thanks a lot for the response Is there any way to change the default data directory, apart from hosting it in a container?

You can set a different data directory in the config, for example:

```yaml
data_dir: /my/data/dir
```

See https://vector.dev/docs/reference/configuration/global-options/#data_dir

**Comment by P1YU5H-50N1** [comment]
Thanks a lot @jszwedko it did resolved my issue.
