### ISSUE TITLE
Consider cheaper representations of metric label data

### ISSUE THREAD

**Issue by lukesteensen** [vectordotdev/vector#2160]
We currently represent [metric labels](https://github.com/timberio/vector/blob/a8ed1f7aa62266bd051c120d5f06cd4c105f8709/src/event/metric.rs#L10) as full `String`s. This is a simple and ergonomic choice but has a cost in memory use and copying.

Alternative representations like `Atom` and `Cow`-like structures could reduce this cost. With proper benchmarking, we can evaluate performance differences and weight them with concerns like ergonomics to decide if switching is worthwhile.

Originally brought up by @LucioFranco [here](https://github.com/timberio/vector/pull/1953#discussion_r392329547).

**Comment by jszwedko** [comment]
Closing since we'll let profiling motivate future performance changes.
