### ISSUE TITLE
`static_metrics` documentation out of date

### ISSUE THREAD

**Issue by nzxwang** [vectordotdev/vector#21625]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I tried to set up a simple pipeline using [the emit a heartbeat example of the `static_metrics` documentation](https://vector.dev/docs/reference/configuration/sources/static_metrics/#examples-emit-a-heartbeat) but it yields `ERROR vector::cli: Configuration error. error=invalid type: integer `1`, expected struct variant`. The value of `sources.my_source_id.metrics.value.gauge = 1` fails; it must be nested as `sources.my_source_id.metrics.value.gauge = {value=1}` for this to work. 

### Configuration

```text
[sources.my_source_id]
type = "static_metrics"

    [[sources.my_source_id.metrics]]
    name = "heartbeat"
    kind = "absolute"

        [sources.my_source_id.metrics.value]
        gauge = 1

        [sources.my_source_id.metrics.tags]
        env = "my_env"

[sinks.my_console]
type = "console"
inputs = [ "my_source_id" ]
encoding.codec = "json"
```

### Version

vector 0.42.0 (x86_64-apple-darwin 3d16e34 2024-10-21 14:10:14.375255220)

**Comment by jszwedko** [comment]
Thanks for flagging! I opened https://github.com/vectordotdev/vector/pull/21636 to fix the example.

**Comment by nzxwang** [comment]
Thank you for showing me that. Next time I'll submit a PR to fix the docs directly.
