### ISSUE TITLE
Exposing HTTP headers in `opentelemetry` source

### ISSUE THREAD

**Issue by jblazquez** [vectordotdev/vector#21673]
**Problem statement**

Unlike [`http_server`](https://vector.dev/docs/reference/configuration/sources/http_server/#headers), the `opentelemetry` source does not currently provide a way to enrich events with HTTP headers that were received through the OTLP/HTTP endpoint. Some use cases would greatly benefit from having access to those HTTP headers, for example to retrieve the original IP address of the client pushing the logs, which can be found in the `X-Forwarded-For` header.

It is possible to work around this issue by using a contrived `http_server` source configuration along with a `decoding.protobuf` config that decodes received requests into an OpenTelemetry `ExportLogsServiceRequest` message:

```
[sources.opentelemetry_logs_http_server]
type = "http_server"
address = "0.0.0.0:14318"
path = "/v1/logs"
decoding.codec = "protobuf"
decoding.protobuf.desc_file = "/path/to/opentelemetry-proto.desc"
decoding.protobuf.message_type = "opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest"
headers = [
    # To get access to the client IP address. 
    "x-forwarded-for",
]
```

However, as shown below, the performance of this solution greatly suffers, as the decoding of the protobuf [happens through reflection](https://github.com/vectordotdev/vector/blob/1eb18e2/lib/codecs/src/decoding/format/protobuf.rs#L95). On the other hand, the `opentelemetry` source can use the generated Protobuf types [without relying on reflection](https://github.com/vectordotdev/vector/blob/58114f13/src/sources/opentelemetry/http.rs#L199), which is much faster.

After profiling the cost of the `http_server` source processing OTLP/HTTP requests, compared to the native processing in the `opentelemetry` source, the cost appears to be at least 25 times higher for `http_server`. Here is a flame graph showing a pipeline that relies on the `http_server` source shown above:

![http_server-decoding](https://github.com/user-attachments/assets/1a1a4d72-cde0-4a49-85c8-0bb79affbce1)

And here is the same pipeline, with the only difference being the use of the native `opentelemetry` source:

![opentelemetry-decoding](https://github.com/user-attachments/assets/11685f83-9777-4bea-adbf-a1ba4b436b12)

The cost of decoding the OpenTelemetry logs with `http_server` becomes prohibitive.

**Proposal**

Add a new `http.headers` configuration option to the `opentelemetry` source that behaves similarly to the existing `headers` configuration for `http_server`, by injecting received HTTP headers into the log events.

**Comment by pront** [comment]
Thanks for the detailed write up @jblazquez, this feature request makes sense.
