### ISSUE TITLE
Support skipping first N lines in `file` source

### ISSUE THREAD

**Issue by a-rodin** [vectordotdev/vector#2175]
It would be useful to have an option to support skipping first N lines of the file in `file` source. The primary use case is to skip header rows for structured file formats such as TSV.

The feature was requested in the chat:
> Is it possible, when using sources = file, to skip the first N lines from each new file since they have a description of fields?

**Comment by ktff** [comment]
Blocked on #1020.
For this feature to have a simpler implementation, with `start_at_begining` file source should always start at begining of a file.

**Comment by jszwedko** [comment]
Closing since there doesn't seem to be user demand for this.
