### ISSUE TITLE
vector vrl -z（timezone） not  effective？

### ISSUE THREAD

**Issue by lddlww** [vectordotdev/vector#21766]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

date: 
![image](https://github.com/user-attachments/assets/e7c1707b-f5b0-4c4b-b841-0bb54055dbea)

vector vrl:
![image](https://github.com/user-attachments/assets/b4a39450-4b89-41b3-91a8-f592d488d7fb)

vector vrl -z Asia/Shanghai
![image](https://github.com/user-attachments/assets/0ad75197-68df-432f-af83-ae794ff953b8)

timezone it not effect at all；how can i do to solve it？

### Version

vector 0.41.1 (x86_64-unknown-linux-gnu 745babd 2024-09-11 14:55:36.802851761)

**Comment by jszwedko** [comment]
Hi @lddlww !

Internally in Vector/VRL all timestamps are in UTC. The timezone is only used for parsing timestamps that lack a timezone. This is definitely a bit confusing. https://github.com/vectordotdev/vector/issues/3333 is a tracking issue for having timestamps actually encode a timezone (in which case `now()` would be in `Asia/Shangai` like you are expecting).

Let me know if that doesn't clear it up.

**Comment by lddlww** [comment]
thanks for reply
so is vector also the same？ i mean vector tz is always utc， even if the timezone is set？
![企业微信截图_17313936934137](https://github.com/user-attachments/assets/6185f815-47c1-4fbc-a89d-159649050ddc)

**Comment by jszwedko** [comment]
> so is vector also the same？ i mean vector tz is always utc， even if the timezone is set？

That's correct, timestamps in VRL and Vector are always internally represented in UTC.

**Comment by lddlww** [comment]
oops, thanks again
