### ISSUE TITLE
could parse_timestamp（vrl function） set timezone?

### ISSUE THREAD

**Issue by lddlww** [vectordotdev/vector#21782]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases
my elasticSearch sink dataset parameter  is  setted by %Y-%m-%d ，however vector internal %Y, %m, %d is derived from timestamp field which timezone is always utc， i wanna to set %Y-%m-%d using "Asia/Shang" timezone, but i found i can't  without using  either set ```global timestamp key option.``` or adding extra column which value timezone is setted from format_timestamp 

problem：
vector/vrl now is hardcode timezone value is  utc， which result in  parse_timestamp that default timezone is utc and could not be change , format_timestamp can set timezone, but return value type is string not timestamp ; if parse_timestamp  could support timezone ,that's would be great 

best wishes

**Comment by jszwedko** [comment]
Hi @lddlww !

I think this issue is the same as https://github.com/vectordotdev/vector/issues/14160 so I'll close this one. https://github.com/vectordotdev/vector/issues/3333 is also related. Feel free to follow those other issues.
