### ISSUE TITLE
Troubleshoot a huge loss of container logs in Vector Aggregator pipeline

### ISSUE THREAD

**Issue by namm2** [vectordotdev/vector#21793]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hi, I'm running a centralized Vector Aggregator logs processing pipeline with Vector Agents to collect kubernetes logs. And during a peak traffic where there were a lot of container logs that's created in a short period of time, but many of these logs were not ingested in to the backend system.

On the Vector Aggregator's source metrics we see the amount of incoming events were growing, and the same with the `vector_component_discarded_events_total` metric:

<img width="820" alt="Screenshot 2024-11-14 at 11 12 36" src="https://github.com/user-attachments/assets/8856c4a7-b426-4f28-89f4-0d634de5ccb2">

The Vector Aggreagor was deployed with the helm chart, and there's no resources requests/limits for it. During this time, its CPU usage was ~ 8 CPUs (of the total 16 CPUs instance):

<img width="818" alt="Screenshot 2024-11-14 at 11 17 46" src="https://github.com/user-attachments/assets/4116ee59-08e5-472a-a184-b16485cec583">

On the Vector Agent's internal logs, there were a lot of errors like this:

> `Request failed: status: Internal, message: "protocol error: received message with invalid compression flag: 60 (valid flags are 0 and 1) while receiving response with status: 504 Gateway Timeout", details: [], metadata: MetadataMap { headers: {"content-length": "92", "cache-control": "no-cache", "content-type": "text/html"} }`

I could understand that Vector Agents were receiving requests timeout while trying to send logs to Vector Aggregator, and it got back-pressure from the upstream Aggregator as the result Vector Agent's sink buffer is full (max_events: 50000):

<img width="818" alt="Screenshot 2024-11-14 at 11 12 44" src="https://github.com/user-attachments/assets/25a87fde-5c69-4097-ad47-634c67da5be7">

I guess this is the correlation with the full buffer in its sink, Vector Agent's `vector_source_lag_time_seconds_bucket` metric values were increased, and the worst was 4000 seconds lag:
<img width="821" alt="Screenshot 2024-11-14 at 11 29 27" src="https://github.com/user-attachments/assets/624b8cbc-5c3f-432c-be49-4cc454e28387">

At first my guess for the data loss was due to container logs rotation (GKE logrotate has fixed to 5 log files and 10MB filesize) Vector Agent couldn't read the old log files once Vector Aggregator is healthy. But it seems like it's not the case here, because Vector Aggregator metrics showed it _received_ log events and then _discarded_ some of the log events, then the data loss was at Vector Aggregator as it dropped some of the logs?

### Configuration

```text
Vector agent configs:


  sources:
    kubernetes:
      type: kubernetes_logs
      max_line_bytes: 131072
      delay_deletion_ms: 3600000  # 1 hour
      glob_minimum_cooldown_ms: 2000  # 2 seconds
<snip>

  sinks:
    vector-aggregator:
      type: vector
      buffer:
        max_events: 50000
      batch:
        max_bytes: 5000000  # 5MB
        max_events: 5000
      inputs:
        - kubernetes
      address: vector-aggregator.logging.svc:9088
      compression: true
```

Vector aggregator configs:
```
  sources:
    kubernetes:
      type: vector
      address: 0.0.0.0:9088
```
```


### Version

0.39.0

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

**Comment by jszwedko** [comment]
Do you see any associated error logs in the Aggregator that indicate why it was discarding events?

**Comment by anas-aso** [comment]
@jszwedko this is the error we see with this incident:
```json
{
    "message": "Events dropped",
    "metadata":
    {
        "kind": "event",
        "level": "ERROR",
        "module_path": "vector_common::internal_event::component_events_dropped",
        "target": "vector_common::internal_event::component_events_dropped"
    },
    "pid": 1,
    "reason": "Source send cancelled.",
    "source_type": "internal_logs"
}
```

**Comment by jszwedko** [comment]
Hmm, that could indicate that the Agent terminated the request and will retry it. The logs you found already seem to support this. The aggregator would discard the events associated with the terminated request, but the Agent should retry the request. However, backpressure could be causing it not tail log files fast enough and thus lose logs at that point.

**Comment by namm2** [comment]
> The aggregator would discard the events associated with the terminated request, but the Agent should retry the request. However, backpressure could be causing it not tail log files fast enough and thus lose logs at that point.

This is what we suspect as well, but what is confusing is the `vector_component_received_events_total` metric on the Vector Aggregator indicating it actually _received_ these events while it didn't.

This is the events rate on the Vector Aggregator's source component:
![Screenshot 2024-11-20 at 07 42 30](https://github.com/user-attachments/assets/d5aeead4-a55e-4545-8a32-13344eb351dd)

And this is the events rate on the Vector Agent's sink:
![Screenshot 2024-11-20 at 07 43 57](https://github.com/user-attachments/assets/4c0f5a9d-0c20-4a80-90d0-ffd8e6d894cd)

So if the Vector's Agent's sink throughput was significantly throttled, then how could Vector Aggegator source could report that it received much higher number of events?

**Comment by jszwedko** [comment]
Here we can see that the events are counted as received by the Vector source as soon as the request is parsed:

https://github.com/vectordotdev/vector/blob/3d7f06dca693517900610a9533b61f848179c101/src/sources/vector/mod.rs#L69-L87

However, the received events can fail to be pushed downstream into the topology at which point they are discarded (and `component_events_discarded_total` is incremented).

Also however, the Vector sink doesn't consider the events as "sent" (and increments `component_sent_events_total`) until it gets a positive response from the upstream. This is likely te be why you see a higher number of received events than sent events. Admittedly this is a bit of asymmetry in the way the source/sinks are instrumented 🤔

**Comment by namm2** [comment]
Thanks for the explanation, we now use the `vector_component_discarded_events_total / vector_component_received_events_total` rate as the indicator of the issue.

**Comment by jszwedko** [comment]
Yeah, I think that makes sense. Do you think that resolves this issue and we can close it?

**Comment by pront** [comment]
> Admittedly this is a bit of asymmetry in the way the source/sinks are instrumented 🤔

Thanks for this explanation, we should improve the public docs based on the above discussion.
