### ISSUE TITLE
Refactor internal usage of channels

### ISSUE THREAD

**Issue by LucioFranco** [vectordotdev/vector#2184]
We currently have very prolific usage of channels within our code base. This comes down to using futures 0.1 channel and we use this type everywhere. Including within our `SourceConfig` type we pass down a receiver. This overall isn't bad but as we upgrade API's will change. Most likely with our upgrade to futures 0.3 and tokio 0.2 we will want to start using the tokio based mpsc channel. I suggest instead of updating our code everywhere with the tokio types I suggest we implement our own wrapper type (similar to what we did for runtime) so that we can make changes easier in the future without having to refactor our code everywhere in the future if we decided to update the channel types.

**Comment by jszwedko** [comment]
Closing since we aren't using futures 0.1 anymore and don't currently have a need to try out other channel implementations.
