### ISSUE TITLE
`kubernetes_log` source: Specify a user agent when making requests to the k8s api server

### ISSUE THREAD

**Issue by ganelo** [vectordotdev/vector#21864]
Looking at logs generated by k8s-audit-webhook, I can see that when vector requests the set of pods from the k8s api server, it is not specifying a user agent. This makes it difficult to attribute load on the api server to the correct client (namely, vector).

**Comment by ganelo** [comment]
I have a branch on which I've put together a proposed fix; I'm working through the contributions documentation to bring it up to snuff, but if you want a sneak peak you can find it here: https://github.com/vectordotdev/vector/compare/master...ganelo:vector:og/kubernetes-user-agent

**Comment by jszwedko** [comment]
> I have a branch on which I've put together a proposed fix; I'm working through the contributions documentation to bring it up to snuff, but if you want a sneak peak you can find it here: [master...ganelo:vector:og/kubernetes-user-agent](https://github.com/vectordotdev/vector/compare/master...ganelo:vector:og/kubernetes-user-agent)

Awesome, this seems to be on the right track!

**Comment by pront** [comment]
Thanks @ganelo, I was about to comment that this request seems reasonable and we can add this header. Don't hesitate to open a PR!

**Comment by ganelo** [comment]
Apologies for the delay, I realized that my testing had been exclusively focused on verifying that the header was coming through, but in practice the changes on my branch resulted in the kubernetes logs not being picked up, suggesting some fundamental issue with the approach. I'm going to be trying to get to the bottom of this next week, but odds are it will bleed into the following week given that next week is Thanksgiving.

**Comment by ganelo** [comment]
Found/fixed the issue (minor oversight - wasn't actually handing the InitDone events to the store).

PR here: https://github.com/vectordotdev/vector/pull/21905

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/21905
