### ISSUE TITLE
`topology_swap_transform_is_atomic` test is occasionally failing

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#2186]
The test itself was introduced at #748, and it has had a bit of unreliability since the beginning, see the discussion at #748.

It is now failing more often than before.

It is not clear at this point whether something is broken with our code or it's the test logic that's unreliable (as in it doesn't properly express synchronization requirements, which causes races).

The suspicion that the test is ok and it's the "rest of the system" that's broken takes its roots from the fact that we've recently switched our `tokio` runtime to `tokio-compat`, and, since we seem to be about the only users of the `tokio-compat`, I don't have enough confidence in it in particular. It's also been found to have bugs before, so, rationally, it is deemed to be the weakest link in our `tokio` update efforts.

What makes matters worse is the fact that we can't switch over to `tokio` 0.2 and get rid of `tokio-compat` yet. It would be helpful as to eliminate the possibility that the bug may be at `tokio-compat`, however it's known that the `tokio` 0.1 (which we used before) was consistent in not causing issues, while `tokio-compat` (that combines parts from both 0.2 in a non-trivial way) is troublesome. However, `tokio-compat` might be fine, and the cause of the bug might be in the test itself - we've had poorly written, racy tests before. It is part due to the limited testability of the design we're currently running, but it's nonetheless a problem.

We should investigate this issue and find out what's going on.

However, since we can't play with switching from `tokio-compat` to pure `tokio` 0.2, now might not be the best time to address this (yet).

That said, if someone has an idea on how to tackle this right now - please share, and we can discuss ways of dealing with this.

A bit of context. The problem with racy tests is a global once, and we should address this systematically by improving the testability of our components. Though, it is a separate thing in relation to this particular test failing, addressing this systematically should fix this problem and numerous others. However, since I wasn't able to eliminate the possibility of issues being caused by `tokio-compat` (i.e. races might be caused by something inside the `tokio-compat` implementation details, not by the changes in the `tokio` 0.2 reactor that `tokio-compat` brings with it), I'm simply trying to be extra cautious.

I would look into this, but I already tackled similar bugs, and I realized it would be great if someone with more experience with `vector` internals than me look into this issue. I'm lacking the context of "how things are supposed to work", and when I find what looks like a race, I'm spending an enormous amount of time figuring out whether it's a bug or it by design (meaning that vector internals are ok and the but is at the test). I assume that time may be cut significantly if someone with knowledge of design nits works on this.

**Comment by binarylogic** [comment]
Thanks for the detailed writeup @MOZGIII. I wouldn't worry about it now. If it is causing too much troubled I'd be in favor of temporarily disabling it until we can address it properly. You are right, we'll probably need to make some structural changes that would enable a better testing strategy for these kinds of tests.

**Comment by LucioFranco** [comment]
Also to note a lot of this topology code was refactored at the same time we swapped out tokio-compat. So there could be many reasons why its failing. I think really what we need is a proper rewrite of these tests.

**Comment by a-rodin** [comment]
It should be possible to reuse the approach from https://github.com/timberio/vector/pull/2282 to fix this test too.
