### ISSUE TITLE
parse_etld function has incorrect check for quantity of options

### ISSUE THREAD

**Issue by johnhtodd** [vectordotdev/vector#21868]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The parse_etld function indicates that it can only have two arguments, but there are more combinations possible than that. See example of the use of "plus_parts" and "psl" at the same time, and also the object being looked up.

### Version

vector 0.42.0

### Example Data

```

x Transform "etld1_preparse":
error[E106]: wrong number of function arguments
   ┌─ :12:48
   │
12 │   .responseData.question[0].etld = parse_etld!(.responseData.question[0].domainName, plus_parts: 1, psl: "/etc/vector/public_suffix_list.dat")
   │                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   │                                                │
   │                                                too many function arguments
   │                                                this function takes a maximum of 2 arguments
   │
   = see documentation about function arguments at https://vrl.dev/expressions/#arguments
   = learn more about error code 106 at https://errors.vrl.dev/106
   = see language documentation at https://vrl.dev
   = try your code in the VRL REPL, learn more at https://vrl.dev/examples

```

**Comment by jszwedko** [comment]
I'm having trouble reproducing this @johnhtodd . Are you sure you are using Vector 0.42.0? The error makes me think you are using a version before `psl` was added.

**Comment by johnhtodd** [comment]
@jszwedko Well-spotted; thanks, you are correct.  I picked the one system to try "vector tap" on with that hadn't been upgraded and was still running an older version. This works correctly; ticket can be closed out.  Sorry for the false alarm.
