### ISSUE TITLE
chore(aqua): Replace the local registry with standard registry

### ISSUE THREAD

**Issue by suzuki-shunsuke** [vectordotdev/vector#21922]
Hi, I'm the author of [aqua](https://aquaproj.github.io), which is a CLI Version Manager.
I noticed you use aqua. Thank you so much!

- https://github.com/vectordotdev/vector/tree/c3d91af5288cc4d10806f7724bf7ba0401ba2b7e/aqua
- https://github.com/vectordotdev/vector/pull/18020

Now you manage [a local registry](https://github.com/vectordotdev/vector/blob/c3d91af5288cc4d10806f7724bf7ba0401ba2b7e/aqua/registry.yaml), but I think you can replace it with [the standard registry](https://github.com/aquaproj/aqua-registry).

I noticed that the standard registry missed some tools you used, so I added them and updated some settings.

- https://github.com/aquaproj/aqua-registry/issues/29339
- https://github.com/aquaproj/aqua-registry/releases/tag/v4.265.0

As we mention in the document, we recommend using the standard registry rather than maintaining a local registry.

https://aquaproj.github.io/docs/develop-registry/

> If tools are not private Repositories, we recommend sending a pull request to Standard Registry rather than maintaining them in your custom Registries, because
> 
> - You can get the support from maintainers
> - You don't have to maintain Registry yourself
> - [From aqua v2, you have to allow non Standard Registry explicitly for security](https://aquaproj.github.io/docs/reference/upgrade-guide/v2/only-standard-registry-is-allowed-by-default/), but this is a bit bothersome

Your local registry installs tools by `cargo install`, but some tools provide pre-built binaries.
The standard registry uses them, so users don't need to build tools themselves.

## Registry settings

- https://github.com/aquaproj/aqua-registry/blob/5c720638ac51b388668577111df6f4bbc7d0b9f7/pkgs/rustwasm/wasm-pack/registry.yaml
- https://github.com/aquaproj/aqua-registry/blob/5c720638ac51b388668577111df6f4bbc7d0b9f7/pkgs/crates.io/cargo-deb/registry.yaml
- https://github.com/aquaproj/aqua-registry/blob/5c720638ac51b388668577111df6f4bbc7d0b9f7/pkgs/cross-rs/cross/registry.yaml
- https://github.com/aquaproj/aqua-registry/blob/5c720638ac51b388668577111df6f4bbc7d0b9f7/pkgs/nextest-rs/nextest/cargo-nextest/registry.yaml
- https://github.com/aquaproj/aqua-registry/blob/ad415443fa1221984596046197870ed782333c18/pkgs/EmbarkStudios/cargo-deny/registry.yaml
- https://github.com/aquaproj/aqua-registry/blob/5c720638ac51b388668577111df6f4bbc7d0b9f7/pkgs/foresterre/cargo-msrv/registry.yaml
- https://github.com/aquaproj/aqua-registry/blob/5c720638ac51b388668577111df6f4bbc7d0b9f7/pkgs/crates.io/dd-rust-license-tool/registry.yaml

**Comment by suzuki-shunsuke** [comment]
If you can accept this proposal, I'll send a pull request.

https://github.com/vectordotdev/vector/compare/master...suzuki-shunsuke:vector:chore-use-aqua-standard-registry?expand=1

**Comment by jszwedko** [comment]
Thank you @suzuki-shunsuke ! I had tried out aqua a while ago where the docs pointed me to creating a local registry. We'd definitely be open to any contributions that help us use aqua best-practices.

**Comment by suzuki-shunsuke** [comment]
Thank you!

I've created a pull request.

- https://github.com/vectordotdev/vector/pull/21959
