### ISSUE TITLE
Prometheus scrape does not support gzip header in GET requests

### ISSUE THREAD

**Issue by st-omarkhalid** [vectordotdev/vector#21975]
### Use Cases

The scraper downloads `/metrics` as text. There should be an option of adding `gzip` header. In production we're scraping servers which produce high cardinality metrics with `/metrics` ranging from 4-13MB across the servers. It would be great to download the metrics as compressed. 

```component_type=prometheus_scrape}:http: vector::internal_events::http_client: Sending HTTP request. uri=http://<ip>:8080/metrics method=GET version=HTTP/1.1 headers={"accept": "text/plain", "user-agent": "Vector/0.35.0 (x86_64-unknown-linux-gnu)", "accept-encoding": "identity"} body=[empty]```

### Version

0.35.0

**Comment by jszwedko** [comment]
Thanks for this request @st-omarkhalid . I think it is the same as https://github.com/vectordotdev/vector/issues/20127 so I'll close this one, but feel free to follow the other!
