### ISSUE TITLE
build_info gauge metric behavior differs since 0.43

### ISSUE THREAD

**Issue by garethpelly** [vectordotdev/vector#21988]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Since 0.43, the build_info gauge [metric](https://vector.dev/docs/reference/configuration/sources/internal_metrics/#build_info) is not emitting the last known value "1" indefinitely.  As a result, it appears only once at start up and therefore this impacts the ability to monitor the counts of vector pods and their respective versions.

I noticed that the "metrics" dependency was updated from 0.24.0 to 0.24.1 in the 0.43 release but I can't spot what has changed to impact the behaviour.

### Version

0.43

**Comment by jszwedko** [comment]
I'm also noticing this didn't end up in the release changelog for some reason 🤔

**Comment by jszwedko** [comment]
Oh I see, because it is a `chore` which are skipped when rendering. I opened https://github.com/vectordotdev/vector/pull/21990 to fix the rendering.

**Comment by pront** [comment]
> Oh I see, because it is a `chore` which are skipped when rendering. I opened #21990 to fix the rendering.

Interesting... good catch.
