### ISSUE TITLE
Reduce transform cannot handle keys with spaces

### ISSUE THREAD

**Issue by dekelpilli** [vectordotdev/vector#21983]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

If a log comes in with an (unquoted) key with a space, it will result in an error. With the below config:

Input:
```json
{"a b":1}
{"a b":2}
```
Console output:
```
2024-12-09T02:04:43.802329Z ERROR transform{component_kind="transform" component_id=red component_type=reduce}: vector::internal_events::reduce: Event field could not be reduced. path=KeyString("a b") error=InvalidPathSyntax { path: "a b" } error_type="condition_failed" stage="processing" internal_log_rate_limit=true
2024-12-09T02:04:43.802549Z ERROR transform{component_kind="transform" component_id=red component_type=reduce}: vector::internal_events::reduce: Internal log [Event field could not be reduced.] is being suppressed to avoid flooding.
{"path":"/","source_type":"http_server","timestamp":"2024-12-09T02:04:43.802069Z","timestamp_end":"2024-12-09T02:04:43.802084Z"}
```

This does not happen if the key comes in quoted. It is worth noting that logs that come in with quoted keys have those keys unquoted. I'm not sure if this is an intended consequence of https://github.com/vectordotdev/vector/pull/21201, but I don't believe this behaviour is documented. Regardless, this does "fix" the space issue. With the below config:
Input:
```json
{"\"a b\"":1}
{"\"a b\"":2}
```
Output:
```json
{"a b":3,"path":"/","source_type":"http_server","timestamp":"2024-12-09T02:06:58.705281Z","timestamp_end":"2024-12-09T02:06:58.705292Z"}
```
Note that the output `a b` key is not quoted.

### Configuration

```json
{
  "sources": {
    "m": {
      "type": "http",
      "acknowledgements": false,
      "address": "0.0.0.0:1234",
      "encoding": "ndjson",
      "inputs": []
    }
  },
  "transforms": {
    "red": {
      "type": "reduce",
      "inputs": ["m"],
      "expire_after_ms": 1000
    }
  },
  "sinks": {
    "serr": {
      "encoding": {
        "codec": "json"
      },
      "inputs": ["red"],
      "target": "stderr",
      "type": "console"
    }
  }
}
```

### Version

0.43.0

### References

- https://github.com/vectordotdev/vector/issues/21165
- https://github.com/vectordotdev/vector/pull/21201

**Comment by pront** [comment]
I think this is a regression from https://github.com/vectordotdev/vector/pull/21323. But it is just a misconfiguration the functionality is there already. I am working on https://github.com/vectordotdev/vector/pull/21989 to fix this.
