### ISSUE TITLE
Clickhouse skip_unknown_fields has no effect

### ISSUE THREAD

**Issue by srstrickland** [vectordotdev/vector#22013]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The clickhouse sink option [skip_unknown_fields](https://vector.dev/docs/reference/configuration/sinks/clickhouse/#skip_unknown_fields) likely has no effect.  I say "likely" because it really depends on what the Clickhouse server settings are.  The problem is that [this option is enabled in Clickhouse by default](https://clickhouse.com/docs/en/operations/settings/formats#input_format_skip_unknown_fields).

 The [way this feature is implemented](https://github.com/vectordotdev/vector/blob/master/src/sinks/clickhouse/service.rs#L138-L140), vector will only set option `input_format_skip_unknown_fields=1` when `skip_unknown_fields` is `true`.  If a user explicitly sets it to `false`, they might expect the behavior to be "strict"; that any attempts to send data with additional fields will result in an error.  But this isn't the case; vector simply won't send the option, and the server setting (default 1) will be used.  So with default settings on a Clickhouse instance, there is no way for a user to enable "strict" mode in vector.

Using the "server default setting" should remain an option, so perhaps the configuration needs to:
* Send `input_format_skip_unknown_fields=1` when `skip_unknown_fields: true`
* Send `input_format_skip_unknown_fields=0` when `skip_unknown_fields: false`
* Don't send the parameter at all when this option is not specified, and let the CH server decide what to do

This is a really minor issue, but thought it was worth raising in case anyone else was surprised by the current functionality.  It's entirely possible that the Clickhouse default used to be 0, in which case the current implementation makes a bit more sense... but even so, there should be a way to force one way or another from vector's perspective, independent of the CH server settings.

It's likely that the other vector options for the `clickhouse` sink need to similarly consider what to do for `true`, `false`, and `not-set`, as they are all currently implemented as "only do something if true", and this may lead to unexpected behavior depending on the various levels of defaulting going on (in both vector config & clickhouse config).

### Configuration

```text
sinks:
  my_clickhouse:
    type: clickhouse
    ...
    skip_unknown_fields: false
```

### Version

0.43.1

**Comment by jszwedko** [comment]
Thanks @srstrickland . I agree with your assessment. If unspecified, it shouldn't send the option and use the server default. If specified (either `true` or `false`), it should send the value to override the server default. A PR for this would be welcome.
