### ISSUE TITLE
Messages getting dropped unintentionally on kafka sink 

### ISSUE THREAD

**Issue by heshanperera-alert** [vectordotdev/vector#22026]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I am using Kafka sink to send messages to azure eventhub. I have noted that messages gets dropped when the azure event-hub hits the throttling limits. When I checked the vector's internal metrics, i can see that these messages gets dropped unintenionally. Is there a way to determine whether these events are retried automatically by vector? 

I am going through the documentation on Kafka sink, but there doesn't seem to have a way or a flag to retry these events upon failures

### Version

0.37.1

### Debug Output

vector_common::internal_event::service: Service call failed. No retries or retries exhausted. error=Some(KafkaError (Message production error: PolicyViolation (Broker: Policy violation)))

**Comment by jszwedko** [comment]
Thanks @heshanperera-alert . It does seem like this error should be retried. I think the change would need to be somewhere in here if anyone feels motivated: https://github.com/vectordotdev/vector/blob/f73fb10277b14d3e16884720a96d20c2bbd0550a/src/sinks/kafka/service.rs#L147-L199

**Comment by PriceHiller** [comment]
So would a simple fix be to shove the `RDKafkaErrorCode::PolicyVioltion` into that area like so?

```diff
diff --git a/src/sinks/kafka/service.rs b/src/sinks/kafka/service.rs
index 087795864..4772833e9 100644
--- a/src/sinks/kafka/service.rs
+++ b/src/sinks/kafka/service.rs
@@ -161,7 +161,7 @@ impl Service<KafkaRequest> for KafkaService {
                     }
                     // Producer queue is full.
                     Err((
-                        KafkaError::MessageProduction(RDKafkaErrorCode::QueueFull),
+                        KafkaError::MessageProduction(RDKafkaErrorCode::QueueFull | RDKafkaErrorCode::PolicyViolation),
                         original_record,
                     )) => {
                         if blocked_state.is_none() {

```

I'm not entirely certain how that chunk of code works, it appears to just delay by a bit and retry the request after 100ms if I'm understanding it right.

**Comment by jszwedko** [comment]
> So would a simple fix be to shove the `RDKafkaErrorCode::PolicyVioltion` into that area like so?
> 
> ```diff
> diff --git a/src/sinks/kafka/service.rs b/src/sinks/kafka/service.rs
> index 087795864..4772833e9 100644
> --- a/src/sinks/kafka/service.rs
> +++ b/src/sinks/kafka/service.rs
> @@ -161,7 +161,7 @@ impl Service<KafkaRequest> for KafkaService {
>                      }
>                      // Producer queue is full.
>                      Err((
> -                        KafkaError::MessageProduction(RDKafkaErrorCode::QueueFull),
> +                        KafkaError::MessageProduction(RDKafkaErrorCode::QueueFull | RDKafkaErrorCode::PolicyViolation),
>                          original_record,
>                      )) => {
>                          if blocked_state.is_none() {
> ```
> 
> I'm not entirely certain how that chunk of code works, it appears to just delay by a bit and retry the request after 100ms if I'm understanding it right.

Yeah, I think that would work. And yes, it just waits 100ms and retries.
