### ISSUE TITLE
GITHUB_TOKEN expires before test harness finishes

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#2208]
We are receiving a `Bad Credentials` error during the "Post a comment with results" step:

https://github.com/timberio/vector/runs/555438732?check_suite_focus=true#step:12:301

This is probably due to the token expiring after 1 hour:

https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#about-the-github_token-secret

We probably need to use our own token in the repository secrets that does not expire.

**Comment by binarylogic** [comment]
I'm wondering if https://github.com/timberio/vector/issues/1591 would improve compile times enough to fix this.

**Comment by jszwedko** [comment]
This hasn't been an issue recently.
