### ISSUE TITLE
Add the ability to print the total count on a time interval in the `blackhole` sink

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#2226]
Recently I was helping a customer debug an issue with their Vector pipeline dropping records. Their pipeline is a simple `kafka` -> `json_parser` -> `elasticsearch` setup. They'd send X records through the pipeline and see Y in Elasticsearch. They are unsure where records are being dropped in the pipeline and they want to rule out Vector. There are a number of ways we can solve this:

1. Setup a `blackhole` sink and print the total on an interval. 💩 
2. Metrics / observability :) (#230) Specifically, the ability to observer the total number of events passing through each component.
3. A simple CLI command to see basic Vector stats.

3 and 2 are related. I'd like for 3 to be powered by 2, because I think that is the best, and simplest, UX.

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/8968
