### ISSUE TITLE
Update `elasticsearch` sink docs to touch on the `ignore_malformed` and `coerce` settings

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#2228]
A very common problem we see with Elasticsearch is rejected data due to type mismatches. Elasticsearch offers two options for solving this `ignore_malformed` and `coerce`. Our docs should probably mention these somewhere. Additionally, I'm wondering if we should also mention the `coerce` transform as a way to ensure consistent types.

**Comment by jszwedko** [comment]
Closing since this hasn't seemed to be an issue in practice.
