### ISSUE TITLE
Add `protocol_key` and `address_key` to `socket` source

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#2270]
These are new `socket` source options to unblock #2268. Requirements are:

For the `protocol_key`:

- [ ] Add a new `protocol_key` option that defaults to `protocol`.
- [ ] The value of this field should be set to the `mode` option value.
- [ ] This field can be disabled by setting it to `""`.

For the `address_key`:

- [ ] Add a new `address_key` option that defaults to `address`.
- [ ] The value of this field should be set to the `address` option value.
- [ ] This field can be disabled by setting it to `""`.

**Comment by binarylogic** [comment]
Noting, we plan to solve this but we want to address it in #2414 before doing so. This data is metadata, in my opinion, and should be treated as such.

**Comment by jszwedko** [comment]
Closing since we are taking a different approach to this sort of source metadata in https://github.com/vectordotdev/vector/issues/12187
