### ISSUE TITLE
Add `address_key` option to `logplex` source

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#2271]
Similar to #2269, this is a new `logplex` source option that unblocks #2268. Requirements are:

- [ ] Add a new `address_key` option that defaults to `address`.
- [ ] The value of this field should be set to the `address` option value.
- [ ] This field can be disabled by setting it to `""`.

**Comment by binarylogic** [comment]
Noting, we plan to solve this but we want to address it in #2414 before doing so. This data is metadata, in my opinion, and should be treated as such.

**Comment by jszwedko** [comment]
Closing since we are taking a different approach to this sort of source metadata in https://github.com/vectordotdev/vector/issues/12187
