### ISSUE TITLE
Proposal to update our release process

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#2284]
I'm forgoing an RFC for this proposal to start. If we are unable to obtain consensus I'll promote it and we can move the discussion there.

---

Up until now, Vector has loosely followed a monthly release cadence. The changes included are dictated by the progress on our [roadmap projects](https://github.com/timberio/vector/issues/1538). This has worked well since we're pre-1.0; the API and priorities have been changing and progressing rapidly. But the context has changed: user adoption has grown significantly and our roadmap is much clearer. As such, I think we can improve how we communicate upcoming changes and manage them internally.

## Problems

1. It's not clear when the next release will be available. As noted above, this is generally monthly, but users would benefit from something consistent.
2. Given that we're pre-1.0 all of our version bumps have been minor which has the unfortunate side-effect of not handling breaking changes as seriously as we should. I think we've done a great job with this, but a major version bump keeps us honest.
3. It's not clear which bug fixes, improvements, and features have priority for the next release.

### Process Changes

- [ ] Introduce a 6-week release cadence.
- [ ] Breaking changes (major releases) should queue as pull requests. These changes should be treated with care and released together. This will incentivize us to make the change backward compatible or reduce the footprint to avoid merge conflict maintenance.
- [ ] Move all of our current milestones (projects) as Github projects or labels.
- [ ] Use milestones to represent our upcoming versions: minor and major.

### Communication Changes

- [ ] Document this process and make it publicly available.
- [ ] Link to this process within the `/releases` section on our website.
- [x] Introduce a "Highlights" concept at `/releases/highlights`. These will replace our current `type: announcement` blog posts. This allows us to couple highlights with changes so that releasing is quick and easy. We can also use this to automate announcements (tweets, etc).

**Comment by Hoverbear** [comment]
We could also consider a 6 week stable cycle matching Rustc and Firefox, with nightlies.

**Comment by a-rodin** [comment]
>  Introduce a 2-week release cadence. This is purposefully aligned with our sprint cadence to consolidate and reduce the process.

Should there be a freezing period when no new features are added, but only bug fixes back ported? For example, with the 2-week release frequency the freezing can happen one week before the actual release.

**Comment by binarylogic** [comment]
> We could also consider a 6 week stable cycle matching Rustc and Firefox, with nightlies.

Eh, that feels a little long for our project. Give that we're a new project I want to update and announce regularly. I'd be open to a 4-week cycle unless there is a good argument for 6 weeks.

> Should there be a freezing period when no new features are added

I don't think so for now. This process will mature as the project ages, but I don't want to introduce too many rules unless there is a good reason.

**Comment by lukesteensen** [comment]
My first impression is that 2 weeks seems a little quick. If we're ok with some boring releases then that's fine, but I'm not sure we'll have an exciting announcement every two weeks moving forward.

I don't think we should adopt a freezing period, but it could be interesting to adopt something like Rust's idea of channels. We already have nightlies and mark certain components as "beta" in the docs, but we could try to unify that idea a bit.

**Comment by binarylogic** [comment]
> but it could be interesting to adopt something like Rust's idea of channels. We already have nightlies and mark certain components as "beta" in the docs, but we could try to unify that idea a bit.

I like that. What are you proposing exactly?

**Comment by lukesteensen** [comment]
I don't have a specific idea in mind, but we could use feature flags to mark components as "beta" instead of just documentation. Then we could merge more aggressively, keeping that feature enabled on nightly for people to test but disabled on release builds. Then "releasing" a component is just removing the flag that keeps it out of release builds.

**Comment by jszwedko** [comment]
This has been formalized as https://github.com/vectordotdev/vector/blob/master/RELEASES.md
