### ISSUE TITLE
Feature request: Zstandard compression for sinks

### ISSUE THREAD

**Issue by occasionallydavid** [vectordotdev/vector#2302]
Vector mostly only supports gzip compression in its sinks, which is to say, a compressor specified in 1990 based on already 20 year old methods, that performs string deduplication over a tiny 32KiB window. Deflate is neither quick to compress nor decompress, has tragic ratios for bulk data, and has been roundly obsoleted in every metric except mass adoption by numerous compressors over the past 30 years.

Of those modern compressors, LZMA and Zstandard have some level of adoption and are fit for general use, but for logs analysis in particular, Zstandard hits a massive sweet spot with state of the art compression ratios combined with best in class decompression speed.

It's possible to get 20x compression of logs with Zstandard and decompress those logs for analysis at almost 2GiB/sec with a single thread. This allows a 20 core machine (theoretically) to process 40 GiB/s of decompressed logs while saturating an underlying 2 GiB/s NVMe storage device (assuming no other work except decompression was being performed).

LZMA is competitive with Zstandard in ratio and overall performance, but Zstandard still enjoys a significant lead in terms of absolute decompression performance, which for me is a major deciding factor in long term logs storage.

This is a request to consider modern gzip alternatives, or if there is no time for that, perhaps consider only my suggestion to go the Zstandard route. ;)

Thanks

**Comment by Hoverbear** [comment]
We definitely want to build on our compression feature in the near future! I think giving folks the option can be done similar to how we do encoding.

**Comment by Hoverbear** [comment]
For whoever wants to tackle this: I think adding an `encoding.compression` field might be the way to go?

**Comment by binarylogic** [comment]
@bruceg before we begin work, we should identify sinks where this is compatible.

**Comment by bruceg** [comment]
Sinks currently using gzip compression:
Sink | Allowed Methods | Status
-----|------------------------|----------
aws_s3 | any |
clickhouse | brotli, deflate, gzip ([reference](https://clickhouse.tech/docs/en/interfaces/http/))
elasticsearch | gzip (?)
gcp_cloud_storage | any
http | any
kafka | gzip, lz4, snappy, zstd ([reference](http://kafka.apache.org/documentation.html#compression.type)) | supported via `librdkafka`
splunk_hec | gzip (?)

**Comment by binarylogic** [comment]
So it looks like `aws_s3`, `gcp_cloud_storage`, `http`, and `kafka` are good sinks to target first.

**Comment by lukesteensen** [comment]
Just to be clear, I don't think we have to implement anything for kafka beyond passing the configs down and enabling the relevant features on the crate.

**Comment by hdhoang** [comment]
The `file` sink's new compression option should be tracked here as well.

**Comment by venkat-sneller** [comment]
n00b here - Does vector support `zstd` to the aws s3 sink out of the box already? I dont see it in the allowed `encoding.compression` options in the docs

**Comment by jszwedko** [comment]
Hey @venkat-sneller ! That's correct, we only support `gzip` on the `aws_s3` sink right now. That would be a good addition though.

**Comment by zamazan4ik** [comment]
@hdhoang Sorry for the so late pinging. Did you try to send a Zstd-related PR? If no, could you please try to do it? Thanks in advance!

**Comment by hdhoang** [comment]
no worry! i'll try it again this month.

(currently we still do td-agent + exec zstd as a flush, fwiw)

**Comment by bruceg** [comment]
Related: https://github.com/vectordotdev/vector/pull/14349
In particular, see this comment: https://github.com/vectordotdev/vector/pull/14349#issuecomment-1260246621
We want to merge the compression support in batch buffers with that in the `file` sink, providing a unified configuration and capabilities across sinks that support compression.

**Comment by gaby** [comment]
Has there been any traction on this? I currently have multiple chained vector instances. One of them is running with the HTTP Server sink using `zstd`. The other is using HTTP Output but `zstd` is currently not supported.

**Comment by jszwedko** [comment]
https://github.com/vectordotdev/vector/pull/17371 added support for zstd compression to a good number of sinks (including `http` and `aws_s3`). I'll close this out, but if there is a sink you'd still like zstd compression support for, please open an issue for that specific sink.
