### ISSUE TITLE
Autodiscovery of Prometheus endpoints for scraping

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#2303]
Feedback from our chat

> * 90% of prometheus endpoints require autodiscovery (various orchestration systems like k8s, etc - most used cases) and it's not supported in vector.
> * in most of cases it's better to use native collectors (or compatible ones like https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmagent) and receive benefits - delivery guarantees, deduplication etc. (especially considering that vector native proto does not have delivery guarantees so far)

I tend to agree. This would be a really nice feature for anyone using Prometheus, but it's not easy either :). For reference, [here's the Prometheus configuration](https://prometheus.io/docs/prometheus/latest/configuration/configuration/). Notice all of the cloud settings that enable autodiscovery.

We definitely need to discuss how we can reduce scope of this feature.

/cc @afoninsky

**Comment by MOZGIII** [comment]
Related: https://github.com/timberio/vector/blob/k8s-rfc/rfcs/2020-04-04-2221-kubernetes-integration.md#discover-and-gather-prometheus-metrics-for-kubernetes-api-resources

**Comment by zhongzc** [comment]
Would like to know if any progress on this feature request.

**Comment by jszwedko** [comment]
Unfortunately not, @zhongzc

**Comment by jszwedko** [comment]
(didn't mean to close this 😄 )

**Comment by waynec86** [comment]
FWIW, grafana-agent uses the library in the loki repo for scraping consulagent targets for services running on the local host here: https://github.com/grafana/loki/blob/main/clients/pkg/promtail/discovery/consulagent/consul.go

Would be great if vector had this so we can have one agent that can export all our metrics/logs/traces.

**Comment by valleedelisle** [comment]
I believe that this should be prioritized, it's probably the only thing missing to have vector agent replacing the prometheus operator.

**Comment by pikilisaikiran** [comment]
I'm trying to use a centralized agent to collect logs, metrics, and traces. While it's working fine for logs, manually adding multiple endpoints in [prometheus_scrape](https://vector.dev/docs/reference/configuration/sources/prometheus_scrape/) for metrics requires extra effort.

It would be incredibly valuable if Vector could support auto-discovery for metrics. I just wanted to chime in and emphasize the demand for this feature.

**Comment by equals215** [comment]
For everyone that uses Docker with dynamically assigned host ports (like on HCP Nomad) using Vector for scraping services metrics is impossible.
This addition would make it an absolute go-to for any Nomad user who's serious about observability.

**Comment by kulbirsaini** [comment]
I am trying to replace Grafana Alloy with Vector for scraping cadvisor and kube-state-metrics but without auto discovery for cadvisor endpoints, it's not quite feasible to achieve this goal.

**Comment by equals215** [comment]
> I am trying to replace Grafana Alloy with Vector for scraping cadvisor and kube-state-metrics but without auto discovery for cadvisor endpoints, it's not quite feasible to achieve this goal.

Why are you willing to move from Alloy to Vector?

**Comment by kulbirsaini** [comment]
> > I am trying to replace Grafana Alloy with Vector for scraping cadvisor and kube-state-metrics but without auto discovery for cadvisor endpoints, it's not quite feasible to achieve this goal.
> 
> Why are you willing to move from Alloy to Vector?

My use case is very limited (cadvisor+ksm to my own remote_write endpoint within the cluster) and I want to have the least possible resource footprint. Vector is supposed to consume way less memory in all possible scenarios.

**Comment by valleedelisle** [comment]
Another reason would be to have only one kind of agent for everything. Why would you want vector a bunch of things and then Alloy for some other things? If Vector can do it all, it's the best of all worlds. No need to maintain 2 different kind of configurations, 2 different kind of deployments, etc.

**Comment by pront** [comment]
Hi all, unfortunately we don't have the capacity to work on this. At least not for this quarter. If someone from the community submits a PR, we will make sure to review it as fast as possible!

**Comment by petrzjunior** [comment]
If you did invest in implementing this, it would be a killer feature for about half of deployment of Grafana Agent/Alloy I would guess. Currently in Kubernetes, I deploy vector for logs as it is superior in terms of configuration and resource usage, but also Grafana Alloy for collecting metrics. Alloy consumes 10x the resources while processing a similar amount of data points and the configuration language and documentation is much worse to work with.

Alloy strives to be compatible with all protocols and all scraping methods, but I would love to finally see a collector which does does better than just embedding Prometheus and works at least in the auto-discovery basic cases. vmagent is close, but it can only do metrics, no logs or traces.

**Comment by PrayagS** [comment]
> If you did invest in implementing this, it would be a killer feature for about half of deployment of Grafana Agent/Alloy I would guess. Currently in Kubernetes, I deploy vector for logs as it is superior in terms of configuration and resource usage, but also Grafana Alloy for collecting metrics. Alloy consumes 10x the resources while processing a similar amount of data points and the configuration language and documentation is much worse to work with.
> 
> Alloy strives to be compatible with all protocols and all scraping methods, but I would love to finally see a collector which does does better than just embedding Prometheus and works at least in the auto-discovery basic cases. vmagent is close, but it can only do metrics, no logs or traces.

+1 to vector being much better than Alloy. Resource usage is much much lower in my experience on production.

That said, I'm not sure based on what parameters Datadog team decides to prioritize issues. But if increasing adoption is important, I believe adding this change will go a long way.

**Comment by valleedelisle** [comment]
This makes me think that Datadog is not dogfooding their own software (pun intended), the probably deploy the prometheus-operator or grafana-alloy on their own k8s clusters.

**Comment by darwin67** [comment]
> Related: https://github.com/timberio/vector/blob/k8s-rfc/rfcs/2020-04-04-2221-kubernetes-integration.md#discover-and-gather-prometheus-metrics-for-kubernetes-api-resources

Looks like the RFC is gone.
If one were to contribute, should there be an RFC first?
Or do someone already have a rough API shape in their head that you're willing to share so we can go with a PR attempt right away?

**Comment by LeeTeng2001** [comment]
Would love to try this

**Comment by pront** [comment]
Hello, I don't think we need an RFC here. Feel free to submit a PR! 

Here's a suggested direction to anchor the discussion:

```yaml
    type: prometheus_scrape
    targets:
      - static:
          urls:
            - http://localhost:9090/metrics
      - kubernetes:
          role: pod                        # or: service, node
          namespaces: [default, monitoring]
          label_selector: "app=myservice"
```

The new `targets` field can live alongside the existing `endpoints`. Also, let's add a validation function to make sure that only one of the two is set. The existing `endpoints` field can be deprecated but it should work for backwards compatibility.

For implementation pointers: 
* the scrape source is in `src/sources/prometheus/scrape.rs`. The core scraping loop in `src/sources/util/http_client.rs` clones the target list on every interval tick, so it's already structured to support dynamic target lists. Not sure if we need to forward more data there. That's a concern to be addressed.
* The `kube` crate (with `runtime` features) is an existing deperency. Source `src/sources/kubernetes_logs/` uses kube's list/watch pattern and can be used as a reference.
