### ISSUE TITLE
Implement internal rusoto credential provider

### ISSUE THREAD

**Issue by LucioFranco** [vectordotdev/vector#2344]
Currently, we use rusoto's `AutoRefreshingProvider` coupled with the `ChainProvider` which will attempt to fetch credentials from a multitude of sources. The issue with the `ChainProvider` is that it contains its own internal timeout. We should refactor this to not depend on an external timeout but rather have them error quickly so that the user can get notified that they don't have any credentials setup.

The reason we want to remove the timeout is to let topology control the timeout rather than deeper in the tree of futures. With this as well we can add much needed logging to the way we fetch credentials to allow the user to have a much easier time debugging why their AWS based sinks don't work.

**Comment by binarylogic** [comment]
> We should refactor this to not depend on an external timeout

Can you expand on this? What are you thinking is the right approach?

**Comment by LucioFranco** [comment]
> Can you expand on this? What are you thinking is the right approach?

External timeout aka one that is set externally from the vector code base. In this case there was an explicit timeout set in the rusoto library that we were not directly aware of.

**Comment by akx** [comment]
I think this would also open up an avenue to set credentials per-sink – I don't think that's currently possible?

I have a scenario where I currently need to inject AWS credentials (a regular IAM key) into `/etc/default/vector` so systemd picks them up from there for Vector to read, but it would be more convenient to be able to just put them in an AWS-powered sink's configuration.

**Comment by jszwedko** [comment]
@akx The ability to set the the credentials in the config file itself was recently added in https://github.com/timberio/vector/pull/6188 . This should at least allow the use of differing environment variables to configure components differently. For example:

```
[sinks.aws_s3]
type = "aws_s3"
aws.access_key_id = "$SOME_ACCESS_KEY_ID"
aws.secret_access_key  = "$SOME_SECRET_ACCESS_KEY"
```

Is that along the lines of what you are thinking? You can also hardcode them in the config file rather than using env vars.

**Comment by akx** [comment]
@jszwedko Ah, hey, great. That's exactly what I was thinking :) Apparently not released yet though.

**Comment by jszwedko** [comment]
> @jszwedko Ah, hey, great. That's exactly what I was thinking :) Apparently not released yet though.

:+1: good to hear! And correct, but it should be released in the next couple of weeks.

**Comment by np5** [comment]
Maybe out of topic, but could this be an opportunity to use the instance profile credentials on an IMDSv2 only instance ?

**Comment by jszwedko** [comment]
> Maybe out of topic, but could this be an opportunity to use the instance profile credentials on an IMDSv2 only instance ?

@np5 I believe that should work already. Are you finding that not to be the case?

**Comment by jszwedko** [comment]
Actually, I tested and it does appear to not pick up IMDSv2 credentials. I see someone opened https://github.com/timberio/vector/issues/6847 so we'll cover this there.

**Comment by bruceg** [comment]
This has been obsoleted by the move to the AWS SDK.
