### ISSUE TITLE
Rework `pending_acks` in sinks

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#2381]
It appears the `pending_acks` `HashSet` in the kafka and pulsar sinks are being used as a simple FIFO queue. Since a double-ended queue is a much cheaper data structure for these kinds of uses, replace them with `std::collections::VecDeque`.

Also, while this code is simple, the logic is slightly opaque. It would be good to merge the common paths and document what it is doing.

Note: `BatchServiceSink` appears to have had this conversion done when it was renamed to `PartitionBatchSink` in a2ea56c9cb152d458a14f562ada6c04f126b3ebc

**Comment by jszwedko** [comment]
@bruceg is this still relevant?

**Comment by bruceg** [comment]
No, `pending_acks` was removed along with the `Acker` in #13457
