### ISSUE TITLE
chore(operations): Better diagnostics on `check-fmt`

### ISSUE THREAD

**Issue by Hoverbear** [vectordotdev/vector#2393]
Currently the `check-fmt` make task checks for trailing spaces on files. It does not emit useful errors.

![image](https://user-images.githubusercontent.com/130903/79920018-49133880-83e4-11ea-9e39-533316372dab.png)

It would be useful for contribution flow if this emitted an error line. Or it suggested using the `--fix` option.

Related:

* https://github.com/timberio/vector/pull/1425
* https://github.com/timberio/vector/issues/1423

**Comment by binarylogic** [comment]
Agree. Whenever I've encountered this I usually do a search for `" \n"`

**Comment by jszwedko** [comment]
Closing this since we don't use the `vector-checker` anymore. The markdown lint tool we use now does give clear messages about trailing line breaks.
