### ISSUE TITLE
Event.keys() ignores objects and arrays.

### ISSUE THREAD

**Issue by Hoverbear** [vectordotdev/vector#2410]
In https://github.com/timberio/vector/issues/2407 we saw that `event.keys()` behaves this way:

https://github.com/timberio/vector/blob/76062baf39e542cb86755951ad2415ebb10e723b/src/event/util/log/keys.rs#L36-L53

And given some log:

```json
{
	"message": "cat",
	"parent":
	{
		"child": [
			"my-child"
		]
	},
	"tags": [
		"my-tag"
	]
}
```

The keys are:

```json
[
  "host",
  "message",
  "parent.child[0]",
  "source_type",
  "tags[0]",
  "timestamp",
]
```

![image](https://user-images.githubusercontent.com/130903/80001969-de114280-8473-11ea-8fa0-6bef98bf3e17.png)

It would be very helpful and unsurprising if the function also output `parent.child` and `tags`, instead of just their content.

The reason it doesn't is because it calls `all_fields` which iterates over fields with leaf values.

**Comment by binarylogic** [comment]
@Hoverbear does this need to be assigned to you for work right now? Shouldn't we address this post RFC on the data model?

**Comment by Hoverbear** [comment]
It can be unassigned

**Comment by jszwedko** [comment]
Fixed by https://github.com/vectordotdev/vector/pull/8645
