### ISSUE TITLE
New log_schema.meta_key option as a new metadata convention

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#2415]
In the spirit of #2414, we should consider improving how we handle event metadata. Specific use cases include:

1. The `source_type` field added in #2147 and #2268. This field was primarily added for the `splunk_hec` sink, but could be considered "noise" for non-Splunk use cases (see first point https://github.com/timberio/vector/issues/2398#issuecomment-617559933).
2. Fields used for routing only (https://github.com/timberio/vector/issues/1448#issuecomment-571155170).

Given that we already discussed this in #1448, and solved it with https://github.com/timberio/vector/pull/1915, I don't think we should change our solution. I rather like the solution because it's simple and flexible. It also handles the myriad of edge cases where metadata is already present in the data we receive (what if the user is already using a `@metadata` key?).

So I'd like to propose a new `meta_key` log schema option that defaults to `"_meta"`. This is just a big namespace that we shove fields like `source_type` into. To futher improve this, we should default the new `log_schema.encoding.except_fields` (#2343) to `[{{ meta_key }}]`.

If we agree, I need to update #2272, #2273, #2147, and probably #1150.

**Comment by jszwedko** [comment]
Taking a different approach in https://github.com/vectordotdev/vector/issues/12187
