### ISSUE TITLE
Redacting event content

### ISSUE THREAD

**Issue by myndzi** [vectordotdev/vector#2438]
(moving from gitter)

Not all log data is in our direct control; one example is referer headers from web logs (I've seen some really "interesting" query strings in referer headers, and getting in touch with the external site that generated them is not necessarily quick...)

It can therefore be useful to redact logs at ingestion before they even hit disk. I have used a filter in [Unilog](https://github.com/stripe/unilog) to address this, but observed that the initial naive implementation (a big concatenated regular expression) performed very poorly at volume (at least in Go, with O(dozens) values to match). I was able to fix that by using the [Aho-Corasick algorithm](https://en.wikipedia.org/wiki/Aho%E2%80%93Corasick_algorithm) to perform one-pass string search over the data with a fixed list of query parameters to redact. 

I'm considering what equivalent functionality I could use in Vector, and it seems like Lua is the answer. However, it seems likely that similar performance considerations would apply, or nontrivial code would have to be shipped in Lua alongside Vector.

Initially I was just asking for advice on how to accomplish this goal (redacting query string parameters) efficiently, but @binarylogic suggested I file an issue here for consideration. Ideally all data is in our control, but configurable redaction in a log shipper is a quick and easy place to deal with a problem while a more permanent fix is arranged. So, I submit such a transform for your consideration :)

Other considerations: in my solution, I wound up building the FSM with both url-encoded and url-decoded versions of the target query string keys, because I've seen it both ways in the data 😭

I also generally prefer allow-listing "known-good" things to block-listing "bad" things, but depending on the data you're dealing with, one may be more suitable than the other, and it's a different problem to solve entirely if you're rewriting "everything but" a list of key-values.

**Comment by binarylogic** [comment]
Thanks @myndzi, that's great info. I wasn't aware of unilog. We plan to address data stripping, security, privacy, etc, in a focused project. We have a number of ideas around facilities we can provide to do that and this seems relevant. We'll include this for evaluation when we get there. Thanks for sharing.

**Comment by myndzi** [comment]
Sounds great :)

(Unilog isn't a log shipper really, it's just stdout -> disk -- not the same kind of program as vector)

**Comment by jszwedko** [comment]
Closing this since we have added a `redact` function to VRL that covers basic redaction use-cases. We can open up follow-up issues for any specific enhancements we need.
