### ISSUE TITLE
Inserting empty prefixed keys into events discards them

### ISSUE THREAD

**Issue by LucioFranco** [vectordotdev/vector#2480]
If you insert a key like `".b"` into an event the key/field pair will get somehow discarded.

Failing test:

`src/event/util/log/insert.rs`:
```rust
	#[test]
    fn test_insert_array_empty_prefix() {
        let mut fields = BTreeMap::new();
        insert(&mut fields, "b".into(), Value::Integer(10));
        insert(&mut fields, ".c".into(), Value::Integer(5));

        let expected = fields_from_json(json!({
            "b": 10,
            "c": 5,
        }));
        assert_eq!(fields, expected);
    }
```

Here is the failing assertion of what I would expect the output to be:

```
thread 'event::util::log::insert::test::test_insert_array_empty_prefix' panicked at 'assertion failed: `(left == right)`
  left: `{"b": Integer(10)}`,
 right: `{"b": Integer(10), "c": Integer(5)}`', src/event/util/log/insert.rs:140:9
```

Here it shows that c is not inserted into the event.

This is likely the cause of #2477

cc @binarylogic this is related to what I was mentioning in https://github.com/timberio/vector/pull/2479#issuecomment-620695585

**Comment by binarylogic** [comment]
Noting, I've addressed this in the Schema RFC [here](https://github.com/timberio/vector/pull/2428/files#diff-d70c9071a045922fceb3a69e72920175R157-R158).

**Comment by binarylogic** [comment]
Just noting. This is blocked by the upcoming work to replace our templating/path notation syntax with the new remap syntax. It's like this work will make this irrelevant.

**Comment by jszwedko** [comment]
Closing since paths accept a leading `.` now.
