### ISSUE TITLE
Implement proper TLS tests

### ISSUE THREAD

**Issue by LucioFranco** [vectordotdev/vector#2497]
Currently, we don't have very good coverage around our tls settings and tls connectors. It would be nice if we could setup specific infrastructure for testing our tcp <-> tcp topology with custom certs.

The use cases we want to cover:

- Self signed certificates loaded via the `TlsConfig` type (I believe we already have some coverage here but it would be nice to see more)
- Fetching system root ca certs on windows, mac and linux (for mac we must ensure that openssl certs are not installed and we go through SecurityFramework)
- Each matrix of configuration works, setting verify_hostname or not etc, we should try all permutations of valid configurations for server and client

**Comment by jszwedko** [comment]
Closing since we do have some tests using TLS now.
