### ISSUE TITLE
Produce release artifacts for pull requests

### ISSUE THREAD

**Issue by a-rodin** [vectordotdev/vector#2526]
Produce release artifacts for all PRs and commits to master.

**Comment by binarylogic** [comment]
Removing this from the release epic, we can defer this work.

**Comment by Hoverbear** [comment]
I think we actually produce these in debug form already now we just don't persist them?
![image](https://user-images.githubusercontent.com/130903/98589882-d46df180-2282-11eb-9ec4-ed44b646f690.png)

**Comment by jszwedko** [comment]
We don't currently have plans for this.
