### ISSUE TITLE
Decoders for sources

### ISSUE THREAD

**Issue by lukesteensen** [vectordotdev/vector#257]
For applicable sources, you should be able to configure a decoder (e.g. JSON) that will fully parse and structure the incoming data. The difference between a source-configured decoder and a downstream parsing transform is that a source-configured decoder will be expected to completely parse the entire message into structured data and drop the original raw bytes representation.

This will also require figuring out how downstream transforms and sinks will handle this new type of record with no raw data. Similar to #256, we may need to add a conditional or `match` to detect this case and provide a different default behavior that makes sense for this kind of data.

This would also benefit greatly from #235, so that we could detect and prevent cases where downstream components would try to read the raw original data by default and end up with surprising behavior.

Related to both of the above, there may be decoders (syslog comes to mind) where it makes sense to set one parsed field (e.g. message) as the default target of downstream parsing components.

**Comment by Hoverbear** [comment]
Perhaps it would be reasonable to have this share code with the downstream transforms by having it so users specify the transform in `codec` (or `decoder`?)

Eg.

```toml
[source.console.foo]
# ...
codec = "json_parser"
```

**Comment by tobz** [comment]
This should be addressed already by the framing/decoding work that @pablosichert has done for sources, and anything leftover would be addressed by either #9388 or #9930.

Gonna close for now.
