### ISSUE TITLE
New `throttler` transform

### ISSUE THREAD

**Issue by lukesteensen** [vectordotdev/vector#258]
We should have a sampling transform that limits the maximum output throughput to a configurable threshold.

**Comment by binarylogic** [comment]
@lukesteensen how does this differ from the current `sampler` transform?

**Comment by lukesteensen** [comment]
It would limit the maximum output throughput instead of simply reducing the input throughput by a given fraction. This could be more useful in cases where the input throughput is unknown or can vary dramatically (e.g. error logs).

**Comment by binarylogic** [comment]
Just adding a note here. I would like to think about this from the lens of protecting against runaway costs and allocating throughput to streams. For example, an application within an organization might be allocated 1tb per month and the user wants to break that up into, say, hourly buckets.

**Comment by tyrken** [comment]
Would want this not just for cost reasons, but to protect an limited capacity sink to avoid it being overloaded (or becoming too slow for users), e.g. an ElasticSearch cluster.  Or a network between the Vector instance and a remote sink.

Ideally should be configurable to read a user-defined event field denoting an identity to allow fair throttling.  I.e. so when one app on a node might be logging madly & so throttled, another app on the same node log correctly as it's keeping within the limit, usually specified as a number of events per time period.
