### ISSUE TITLE
Upgrade streaming based sinks

### ISSUE THREAD

**Issue by LucioFranco** [vectordotdev/vector#2642]
This is a tracking issue to track sinks that don't follow our other service or http based sinks. These sinks are based around the `StreamingSink` type and do not do any sort of batching.

## Sinks to upgrade

- [ ] `kafka`
- [ ] `pulsar`
- [ ] `socket`
- [ ] `papertrail`
- [ ] `vector`

## Notes

These sinks will be a bit more complicated to upgrade for two reasons 1) currently vector is not using the new `Sink` api (nor should it) 2) upgrading the libraries might remove the option to use poll based apis.

Suggestions here might be to use the new `streaming_sink` integrations and working directly with async/await instead of poll. This means the upgrade will be a bit more invasive.

There has been more discussion around this design here. https://github.com/timberio/vector/issues/2122

**Comment by jszwedko** [comment]
`StreamingSink` doesn't appear to exist anymore.
