### ISSUE TITLE
Upgrade to tower `0.4`

### ISSUE THREAD

**Issue by LucioFranco** [vectordotdev/vector#2644]
This is a tracking issue to track the usage of the tower git dependency. Currently, vector depends on the `0.4` git version of tower https://github.com/timberio/vector/blob/master/Cargo.toml#L78. Once, `0.4` gets released the `Cargo.toml` should be switched to depend on the `crates.io` version rather than the git version.

Tracking issue in tower https://github.com/tower-rs/tower/issues/431

**Comment by fanatid** [comment]
Not actual while tower:0.4 not released.

**Comment by jszwedko** [comment]
We are running Tower 0.4.13 now.
