### ISSUE TITLE
Revisit the test harness triggering mechanism

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#2651]
We might want to rethink how we trigger test harness. Github Actions seem to be creating a bit of a mess currently.

<Details>

![image](https://user-images.githubusercontent.com/265507/82405406-7e0abd80-9a6c-11ea-9ed3-3869d77d5083.png)

</Details>

Currently, we have Test Harness configured to be triggered directly in the Github Actions via `issue_comment` trigger. This creates noise in the CI dashboard. A minor inconvenience, but it would be nice to fix.

An alternative would be to hook to the same `issue_comment` trigger but via the Github API Webhooks (we can put it in AWS Lambda or sth similar). We then process events and do the filtering there, and if we see a command we pass it back to Github Actions as a `repository_dispatch` event.

This is easier than it sounds. It's not urgent as is just a nice-to-have.

**Comment by jszwedko** [comment]
We no longer use the test harness.
