### ISSUE TITLE
New `trace` event type

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#2661]
Before we can begin work on implementing trace support, we must implement a new `trace` event type. Traces are less complex than metrics but more complex than logs (events). A good framework to follow for our internal `trace` data model is the [OpenTelemetry](https://opentelemetry.io/docs/) project. The goal of that project is to create a vendor-agnostic approach to collecting observability data; this includes traces. We should consider adopting their data model and starting our `trace` support with an `open_telemetry_traces` source and sink.

A few relevant pieces of documentation:

* [OpenTelemetry Semtantic Conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/overview.md#semantic-conventions.md)
* [OpenTelemetry SDK spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md)
* It's likely I'm missing other pieces of documentation, so I'd recommend pursuing their docs for anything else related to their tracing data model.

I'd like to start with an RFC outlining this new data model type. It should be heavily inspired by the OpenTelemetry trace data model unless we determine a better approach.

**Comment by binarylogic** [comment]
Noting. This is currently blocked by internal data model changes and improvements. We'd like to complete that process before introducing a new data type.

**Comment by jtescher** [comment]
The otel spec is in beta but quickly approaching a GA status, may be worth looking at the current rust sdk and see if there is a way for the two projects to be compatible https://github.com/open-telemetry/opentelemetry-rust/tree/master/src/api/trace. Open to making changes there to help out, would be nice if the rust tracing ecosystem were as interoperable as possible 👍

**Comment by kaarolch** [comment]
@binarylogic is there any ETA for Traces and OpenTelemetry support in vector? I've asking because we think about vector as a replacement for some part in our open-telemetry pipeline.

**Comment by jszwedko** [comment]
Hi @kaarolch! We are currently targeting this for the end of this year.

**Comment by gaetansnl** [comment]
One very useful feature would be to have a way to use the full power of vector to replicate this for example: https://grafana.com/docs/tempo/latest/grafana-agent/automatic-logging/. We stopped using opentelemetry collector at my company because it was way too limited compared to what would be possible with something like vector. And we didn't want to load a full additionnal agent like Grafana agent.... We can't way to have trace support in vector ! :)

**Comment by jszwedko** [comment]
Closing this since we introduced a `trace` event type in https://github.com/vectordotdev/vector/pull/10483
