### ISSUE TITLE
Templating Support in Prometheus Sink

### ISSUE THREAD

**Issue by jasonmfehr** [vectordotdev/vector#2739]
I am trying to use templating to set the `namespace` field in the prometheus sink based on a tag value, but I am not seeing metrics in grafana. If I hardcode the `namespace` field to the tag value, then I do see the metrics in grafana.

Sink Config:
```
[sinks.prometheus]
type = "prometheus"
inputs = ["metrics_vector"]
address = "0.0.0.0:55555"
namespace = "{{ tags.namespace }}"
```

I also set up a console sink with a `metrics_vector` input. It is showing that my metrics events look like:
```
{
  "name": "requestURI",
  "timestamp": null,
  "tags": {
    "namespace": "org_app",
    "request_uri": "/health"
  },
  "kind": "incremental",
  "counter": {
    "value": 1
  }
}
```

**Comment by jszwedko** [comment]
Closing since this sink will use the namespace from the metric, if there is one. The config field is now called `default_namespace` to be applied to any metric lacking a namespace.

Note the namespace field is directly on the event, not a tag: `.namespace`.
