### ISSUE TITLE
Triggered Action for a Perf Run

### ISSUE THREAD

**Issue by Hoverbear** [vectordotdev/vector#2747]
For #2006 I have a bench suite I'd like to be able to trigger.

It'd be useful if I had a label like `needs - bench report` on an issue and Github actions could detect it, do a bench run, and report the output criterion reports, then remove the label. It can use Github Action's "Artifacts" for this.

I think this can copy some of the mechanics of how the `test-harness.yml` works.

**Comment by jszwedko** [comment]
Closing since we do have a performance test suite now that does post PR comments with results.
