### ISSUE TITLE
Improve `LogEvent` API with `Into<Lookup>` values.

### ISSUE THREAD

**Issue by Hoverbear** [vectordotdev/vector#2843]
Step 6 of https://github.com/timberio/vector/blob/c4707947bd876a0ff7d7aa36717ae2b32b731593/rfcs/2020-05-25-more-usable-logevents.md#sales-pitch

This step does what #2842 did not do, and cleans/refines the API.

You should try to condense functionality like `insert_path` and `insert` or `remove_path` and `remove` to use `Into<Path>`.

During this time, the main bulk of the work will presumably be **updating component configurations to use** and handle the new `Lookup` type so it can be properly passed to the refined `insert`/`remove` functions.

**Do this at the config/definition level whenever possible. This issue entrusts you to make a distinction between user input and internal code. Turn user input into a `Lookup` as soon as you practically can.**

Depends on #2842

**Comment by Hoverbear** [comment]
Putting a pin in this until 0.11, as we don't want to merge it prior, and it will just constantly merge conflict until after that.

**Comment by binarylogic** [comment]
> we don't want to merge it prior

Any reason why? Just general stability concerns?

**Comment by Hoverbear** [comment]
Kind of, yeah! I'd prefer this this change to be part of the release remap stabilizes since they will use all the same parsing rules. This way we can say "Okay, here, in 0.12 remap and the new lookups happened so all configs which are broken just need to follow these rules globally", instead of "Okay now in these particular transforms the rules are slightly different" or risking finding other inconsistencies after release and requiring a hotfix.

**Comment by jszwedko** [comment]
Closing since we ended up introducing a new implementation for lookups.
