### ISSUE TITLE
Provide `Event::iter` and `Event::iter_mut` functions that yield (Lookup, Value). 

### ISSUE THREAD

**Issue by Hoverbear** [vectordotdev/vector#2845]
Step 8 of https://github.com/timberio/vector/blob/c4707947bd876a0ff7d7aa36717ae2b32b731593/rfcs/2020-05-25-more-usable-logevents.md#sales-pitch.

Remove the `Event::all_fields` function.

**Include tests against https://github.com/timberio/vector/blob/c4707947bd876a0ff7d7aa36717ae2b32b731593/rfcs/2020-05-25-more-usable-logevents.md#a-motivatingly-complex-example**

Depends on #2843

**Comment by Hoverbear** [comment]
@lukesteensen this might be related to #3074 ?

**Comment by jszwedko** [comment]
Closing since we ended up introducing a new implementation for lookups.
