### ISSUE TITLE
TCP compression

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#289]
Some existing forwarders support compression over TCP and I'm wondering if this is a worthwhile feature given the streaming nature of TCP. The examples I've seen treat the option as opaque, offering a `compress = true` setting. Both the sender and receiver must have that setting enabled. I'd prefer that we offer a compression type so that any receiver of the data can decode it. Ex:

```
[sinks.out]
  type = "tcp"
  compression = "lz4"
```

**Comment by StephenWakely** [comment]
There doesn't seem to be any interest in this, so we will close. Feel free to reopen if a need for this arises in the future.
