### ISSUE TITLE
Console sink races with with Vector own logs

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#2891]
When outputting the logs via `console` with `stdout`, it's possible to reach a situation where the generated is not valid UTF-8.
It is most likely caused by a race when writing to stdout when we have multiple working threads.

I triggered this when working on Kubernetes E2E tests.

Steps to reproduce:
1. Prepare an environment that generates logs a log (`kubernetes_logs` would work).
2. Enable `trace` log level to increase a chance of race.
3. Run Vector with `console` sink writing to stdout as JSON and save the stdout output.
4. Inspect the output and validate there's corrupted UTF-8 (you can use rust's [std::str::from_utf8](https://doc.rust-lang.org/std/str/fn.from_utf8.html) or similar).

I noticed it because I was running the test code in rust.

**Comment by jszwedko** [comment]
Closing since Vector writes logs to `stderr` now which allow them to be easily separated from the `console` output on `stdout`.
