### ISSUE TITLE
Use regex for all possible conditions

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#2909]
@bruceg [took the time to benchmark the `contains` and `regex` conditions](https://github.com/timberio/vector/issues/2833#issuecomment-649096299) to see which is faster. It turns out the `regex` condition is faster. We should switch relevant conditions to use regex under the hood as a performance optimization. Specifically:

- [ ] `begins_with`
- [ ] `ends_with`
- [ ] `contains`

@bruceg can you confirm that this list is inclusive and accurate?

**Comment by bruceg** [comment]
Actually, both `begins_with` and `ends_with` were slower with regex matching than plain string matching. Only `contains` was faster. There is no other match in the conditions that would be applicable.

**Comment by jszwedko** [comment]
Closing since `check_fields`-style conditions have been deprecated in-lieu of VRL conditions.
