### ISSUE TITLE
Automatically create canonical streams in sinks

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#2911]
This issue proposes a "plug-and-play" solution for canonical log lines.

## Context

#1437 introduces a transform that can produce canonical log lines. These types of log lines serve as an index for the larger stream of log data. See #1437 for more info.

A big downside of the transform in its current form is ease of use. To properly set this up a user must:

1. Understand what canonical log lines are and why they should use them.
2. Understand how to use them properly downstream in whatever tool they are using for analyzing.
3. Define start and stop conditions for each transaction.
4. Whitelist attributes that should be included in the final canonical log line as well as define merge strategies for each attribute.

## Proposal

I'm proposing that we figure out a way to make this "plug-and-play" for the uninformed user. Something as easy as:

```toml
[sinks.cw_logs]
  type = "aws_cloudwatch_logs"
  group_name = "api/production"
  stream_name = "{{ host }}"
  canonical_group_name = "api/production-canoncial"
```

Notice the `canonical_group_name` option. By adding this option Vector would write to 2 separate groups:

1. `api/production`
2. `api/production-canonical`

Vector would automatically ditch the `message` field since canonical log lines are meant to serve as an index for structured data. Alloy could recognize this naming pattern and/or add a setting that would denote a stream as a "canonical" form of the current stream. Then it could transparently use the canonical stream as an index, finding the appropriate window, and then flip over to the non-canonical stream to load the actual log data.

## Final Thoughts

Even if we can't make it as simple as the above proposition, I think there are ways to simplify adopting this feature.

**Comment by binarylogic** [comment]
I'm realizing this isn't that much better than adding default to the new `transaction` transform and setting up two sinks, but the end state is what's most important here.

**Comment by hadeali** [comment]
#

**Comment by jszwedko** [comment]
Closing due to lack of demand.
