### ISSUE TITLE
Apply BatchSettings builder pattern to TowerRequestConfig

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#2924]
The `TowerRequestSettings` handling of default parameters for batch sinks has never been a particularly good pattern. In PR #2866 a modified builder pattern was introduced for setting up `BatchSettings` that simplified the calling convention and is also `const` ready. This pattern could be applied to the `TowerRequestSettings` creation to improve the readability of the sinks and eliminate the `lazy_static` usage as well.

**Comment by jszwedko** [comment]
Closing as tech debt unlikely to be picked up by itself but only as part of other work. I raised internally if we should just be using code comments for this sort of thing.
