### ISSUE TITLE
Client certificate metadata option for sources

### ISSUE THREAD

**Issue by rwaweber** [vectordotdev/vector#2931]
Hey all! Being able to propagate client certificate information as event metadata is a _really_ useful feature that I've used a lot with logstash in the past. From what I can tell, there isn't a capability to pass along that metadata with vector, at least with the socket and http input plugins that I could find.

It's a helpful feature for being able to collect metrics on specific users/applications while also providing some rudimentary ACLs for outputs when used in conjunction with the [translate](https://www.elastic.co/guide/en/logstash/current/plugins-filters-translate.html) filter, not to mention the added security benefit of using TLS.

Here's an example pipeline I've used before to map a beats input source to a given kafka topic based on the certificate principal they present(great for handling many distinct users over a single port):
```perl
input {
  beats {
    port => 7000
    ssl => true
    ssl_verify_mode => "force_peer"
    ssl_certificate_authorities => [
      "/etc/ssl/beats_server/ca.pem"
    ]
    ssl_certificate => "/etc/ssl/beats_server/certificate.pem"
    ssl_key => "/etc/ssl/beats_server/certificate-key_pkcs8.pem"
    ssl_peer_metadata => true
  }
}
filter {
  translate {
    field => "[@metadata][tls_peer][subject]"
    destination => "[@metadata][destination_topic]"
    dictionary_path => "/etc/logstash/cert_to_topic.yml"
    fallback => "catchall.topic"
    exact => true
  }
}

output {
  kafka {
    ...
    topic_id => "%{[@metadata][destination_topic]}"
  }
}
```

Where the dictionary path in the filter is a file That consists of a mapping of cert principal strings and topic names.

Not really sure how vector handles internal event metadata, but I was curious if you all would be open to supporting client certificate principal data to be extracted from incoming TLS connections(probably with the `socket` and `http` sources at first, but if there's interest maybe this feature could trickle out into some other sources, like the HEC input?) and maybe a translate-like transform(though I'm happy to open another issue for tracking the discussion on that.

What are your thoughts?

**Comment by binarylogic** [comment]
Thanks @rwaweber. @bruceg I'm curious if you have any thoughts on this given that logstash seems to support it.

**Comment by ryn9** [comment]
I would be interested in seeing this feature added as well.

**Comment by ryn9** [comment]
@binarylogic @bruceg @jszwedko wondering if you guys have chatted about this recently. I know I was asking about something similar in https://github.com/vectordotdev/vector/issues/7308

**Comment by jszwedko** [comment]
Hey @ryn9 ! Unfortunately no movement on this lately. We are, of course, always open to PRs if people are motivated and have the ability to contribute 🙂

**Comment by abh** [comment]
FWIW, I worked around it by using the http source in my aggregator (instead of the "plain" vector source) and having my (separate) haproxy-ingress set an `X-SSL-Client-CN` header and then have vector add that header as another field.

**Comment by ryn9** [comment]
Well to that end... I would love to see the following available..

- ip_address
- tls_peer.status
- tls_peer.protocol
- tls_peer.subject
- tls_peer.cipher_suite

If I had the rust skills I would do it myself, but alas....

**Comment by fpytloun** [comment]
What about http and vector sources? 🤔

**Comment by jszwedko** [comment]
@fpytloun this initial implementation just covered TCP sources, but we'd be happy to see this extended to HTTP-based sources as well.

**Comment by fpytloun** [comment]
@jszwedko so should I create new issue to cover HTTP sources? Is there some reason why it was not implemented right away for `http` and `vector`? It doesn't seem to be difficult change.

**Comment by jszwedko** [comment]
> @jszwedko so should I create new issue to cover HTTP sources? Is there some reason why it was not implemented right away for all sources with tls auth? It doesn't seem to be difficult change.

👍 if you don't mind, a separate issue would be great. It was initially done just for TCP-based sources because they share some code where it was possible to do all of them at once. Some HTTP-based sources share different code so we could possibly do them at once too, but others are specialized like the `vector` source.

**Comment by fpytloun** [comment]
@jszwedko here it is: https://github.com/vectordotdev/vector/issues/13596
