### ISSUE TITLE
Flaky `topology::config::watcher::tests::multi_file_update`

### ISSUE THREAD

**Issue by ktff** [vectordotdev/vector#3033]
Ref #2978 

Tests if we detect multiple updates in a row to a config file one after another.
Common scenario for update - save - observe loop.

Flaky on mac.
https://github.com/timberio/vector/pull/3010/checks?check_run_id=857600333

Probably a bug.

**Comment by jszwedko** [comment]
Closing since this test was deleted and evidently doesn't appear to have been needed.
