### ISSUE TITLE
Flaky `test_max_size_resume`

### ISSUE THREAD

**Issue by ktff** [vectordotdev/vector#3039]
Ref. #2978 

Tests that we don't loose any events if internal buffers get full.

[test_max_size_resume.log](https://github.com/timberio/vector/files/4905004/test_max_size_resume.log)
https://github.com/timberio/vector/pull/3044/checks?check_run_id=862915559

Probably a race, but it may be a bug.

**Comment by ktff** [comment]
#3308 doesn't seem as the main cause.

**Comment by jszwedko** [comment]
Closing since this test was deleted and evidently doesn't appear to have been needed.
