### ISSUE TITLE
Flaky `test_udp_syslog`

### ISSUE THREAD

**Issue by ktff** [vectordotdev/vector#3043]
Ref. #2978 

Tests `syslog` source in `udp` mode.

https://github.com/timberio/vector/pull/2955/checks?check_run_id=861560287
https://github.com/timberio/vector/pull/3040/checks?check_run_id=862920206

**Comment by ktff** [comment]
#3308 doesn't seem as the main cause.

**Comment by jszwedko** [comment]
Closing since this test was deleted and evidently doesn't appear to have been needed.
