### ISSUE TITLE
We don't have a `make` target to test `lib` crates

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#3060]
This is related to #2588. A lot of things changed since then, but we're still not there.

I think we should have a `make test-lib` target, as well as `make test-lib-qwe`, where `qwe` is each of the `lib/*` paths. Would be cool if we could derive them automatically, but either way - I think we need to give them more attention.

cc @Hoverbear

**Comment by Hoverbear** [comment]
Yeah! Support! We could make them only run if those libs are changed, too.

I'd like to see these run on all OS if we can.

**Comment by jszwedko** [comment]
Closed since this hasn't seemed to be a hiderance to development.
