### ISSUE TITLE
New `scribe` sink

### ISSUE THREAD

**Issue by l2dy** [vectordotdev/vector#3062]
I'd like to have support for `scribe` sink.

https://github.com/facebookarchive/scribe
https://github.com/fluent/fluent-plugin-scribe

**Comment by binarylogic** [comment]
@l2dy thanks for the recommendation. Are you currently using this? I'm curious because it looks like the project has been deprecated.

**Comment by l2dy** [comment]
Yes, we are using it internally, and it could serve as an example for other Thrift-based sinks.

**Comment by l2dy** [comment]
Is is possible to use a synchronous Thrift library (the official one) to implement the sink?

**Comment by l2dy** [comment]
Seems like there is no interest except us. Closing.

**Comment by everpcpc** [comment]
we are also interest in this, would it be approved? Maybe I can work on it.
ref: https://github.com/douban/scribec-rs

**Comment by l2dy** [comment]
@binarylogic What do you think? Would you accept PRs for this sink?

**Comment by jszwedko** [comment]
Hey @l2dy ! Missed this comment before. We are definitely open to a PR for this.

**Comment by l2dy** [comment]
@everpcpc Do you still have interest?

**Comment by everpcpc** [comment]
> @everpcpc Do you still have interest?

I'm afraid not, I no longer need this.

**Comment by l2dy** [comment]
Closing due to lack of interest.
