### ISSUE TITLE
The `aws_s3` sink is not longer gzipped by default

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#3064]
Opening a separate issue for https://github.com/timberio/vector/issues/2966#issuecomment-658074949. The user is reporting that the `aws_s3` sink is no longer gzipping files by default. This shouldn't have changed, https://github.com/timberio/vector/pull/2962 was closed and not merged. We should verify that this has not changed before we release `0.10.0`.

**Comment by Hoverbear** [comment]
Might block #2961

**Comment by fanatid** [comment]
Tested `v0.9.2` tag and `master` (df65bf98).

Config:
```toml
data_dir = "/home/kirill/tmp/vector-tests/data/shared"

[sources.in]
  type = "socket"
  address = "127.0.0.1:1514"
  mode = "tcp"

[sinks.out]
  inputs = ["in"]
  type = "aws_s3"
  bucket = "vector"
  compression = "gzip" # This line removed for master
  endpoint = "http://localhost:9000"

[sinks.out2]
  inputs = ["in"]
  type = "console"
  encoding = "json"
```

Both instances received text `socket` to socket, result on bucket (first v0.9.2, second master):
```
/ # mc ls local/vector/date=2020-07-15/
[2020-07-15 12:19:55 UTC]     27B 1594815595-a12f6185-7f98-403f-99a3-4f0ba60871f9.log.gz
[2020-07-15 12:31:26 UTC]     27B 1594816286-49ab747c-ba5b-41d0-bdbd-23928a6880f2.log.gz
/ # mc cat local/vector/date=2020-07-15/1594815595-a12f6185-7f98-403f-99a3-4f0ba60871f9.log.gz | gzip -d
socket
/ # mc cat local/vector/date=2020-07-15/1594816286-49ab747c-ba5b-41d0-bdbd-23928a6880f2.log.gz | gzip -d
socket
```

I do not see any bugs here...

**Comment by binarylogic** [comment]
Thanks for verifying.
