### ISSUE TITLE
Simplify concurrency control in pulsar sink

### ISSUE THREAD

**Issue by lukesteensen** [vectordotdev/vector#3083]
The current pulsar sink relies on an `Arc<Mutex<_>>` due to lifetime requirements and its relatively unique nested future design. We should ensure that this is not adversely affecting its internal batching and performance, and try to simplify it away if possible.

The nested futures also led to the pulsar sink implementing `Sink` from scratch as opposed to reusing one of our existing `ServiceSink` utilities, even though the structure is very similar. As part of the above simplification, we should try to find a way to rely on existing components instead of reimplementing a slightly different flavor.

**Comment by leshow** [comment]
I was curious about this, it's a bit tricky. `pulsar-rs` requires `Producer::send` to be `&mut self` https://github.com/wyyerd/pulsar-rs/blob/master/src/producer.rs#L277. And on top of that, `send` is a future that creates another future which must both complete before a thing can be considered 'sent'.

**Comment by jszwedko** [comment]
Closing this as unlikely to be picked up for its own sake.
