### ISSUE TITLE
New `nginx_metrics` source

### ISSUE THREAD

**Issue by otisg** [vectordotdev/vector#3091]
For collecting Nginx (Plus) metrics.

**Comment by otisg** [comment]
Since the RFC for this seems to be done, do you have a rough ETA for this?  No pressure, just trying to plan around this.  Thanks.

**Comment by binarylogic** [comment]
@otisg it'll be in the next sprint, which starts on 9/28.

**Comment by otisg** [comment]
> @otisg it'll be in the next sprint, which starts on 9/28.

Looks like it was removed from there.  @binarylogic do you know if you might have it in by the end of November?

**Comment by jamtur01** [comment]
I think it'll be in before the end of November - we're parsing out some questions about code re-use but that aside we're moving ahead.

**Comment by binarylogic** [comment]
The `apache_metrics` source laid the groundwork and set precedence, so I don't see any reason we wouldn't have it out by then.
