### ISSUE TITLE
Flaky `s3_waits_for_full_batch_or_timeout_before_sending`

### ISSUE THREAD

**Issue by ktff** [vectordotdev/vector#3104]
Ref. #2978

Tests that `aws_s3` sink batches events.

https://github.com/timberio/vector/pull/3099/checks?check_run_id=886641917
https://github.com/timberio/vector/runs/868843252

**Comment by binarylogic** [comment]
Thanks @ktff, just so I understand, is there any reason the linked PR didn't close this?

**Comment by ktff** [comment]
@binarylogic Yes, the linked PR only removed the test, it yet needs to be fixed/rewritten. 

Although it can also stay removed. This and #3043 are nice to have, but they aren't useful too much. In case of this test, the batch code is shared with other sinks so it overlaps with other tests.

**Comment by binarylogic** [comment]
Got it. Let's leave them open so we can review in the future when we get around to tech debt again.

**Comment by jszwedko** [comment]
Closing since this test was deleted and evidently doesn't appear to have been needed.
