### ISSUE TITLE
New `cloudwatch_logs` source RFC

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#3118]
RFC for https://github.com/timberio/vector/issues/2695

**Comment by jamtur01** [comment]
@jszwedko Is this one done? I can't find the RFC?

**Comment by jszwedko** [comment]
@jamtur01 Not yet. We've done some pre-work to identify which approaches we want to take for this which included this issue and #3566 , but I haven't don the RFC specifically for this source yet.

**Comment by jamtur01** [comment]
@jszwedko Ah cool - I'll update it in Zenhub.

**Comment by jszwedko** [comment]
Closing this since we aren't actively working on an RFC and we already have an issue for the new source #2695
