### ISSUE TITLE
New `quota` or `rate_limit` transform

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#315]
In order to prevent volume spikes, we should introduce a new `quota` or `rate_limit` transform that would allow an operator to control volume over a configured window.

## Outstanding questions

1. What is the appropriate behavior when the quota is exceeded? Drop the data? Apply back-pressure? Should this be configurable?
2. Could this be based on bytes instead of event quantity?
3. Is this better implemented at the sink-level?

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/9378
