### ISSUE TITLE
Better way of asserting that test Pod finished at K8s E2E tests

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#3150]
This is a follow up from https://github.com/timberio/vector/pull/2702#discussion_r458218965.

While it's not a problem currently, it'd be a good idea to improve the reliability of the synchronization logic at the K8s E2E tests. Currently, we assume the simple `echo` command that the `Pod` runs ends within 10 seconds. While this can technically be a race, it doesn't seem to be a problem *at this time*. The last part is key here, and we'd want to improve this proactively with a more involved `kubectl` usage. See more details on the design [here](https://github.com/timberio/vector/pull/2702#discussion_r458218965).

**Comment by jszwedko** [comment]
@spencergilbert do you think this is still relevant or can we close it?

**Comment by spencergilbert** [comment]
It's similar to our previous discussions around improving the e2e tests, we could hold this issue to roll it into an epic or close it now and just build the epic from scratch 👍 

No opinion on which to do.
