### ISSUE TITLE
New `internal_traces` source

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#3213]
I'm opening this up for discussion. I realize we have low-level work to do before we can consider this.

A useful tool for Vector operators is to view traces. More specifically, a trace for a single event as it flows through Vector. We should be able to derive this from Vector's internal events. And like other observability practices, it makes sense to start with a simple CLI subcommand that would let users sample traces.

**Comment by jszwedko** [comment]
Closing since we don't have any internal tracing of events that would support this, at the moment. If/when we do, we can revisit this.
