### ISSUE TITLE
Making CI less flaky: workaround for `cargo` connection errors

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#3253]
Occasionally, an error like the one below occurs at CI:

```
warning: spurious network error (2 tries remaining): failed to get 200 response from `https://crates.io/api/v1/crates/futures-task/0.3.5/download`, got 502
warning: spurious network error (2 tries remaining): failed to get 200 response from `https://crates.io/api/v1/crates/hashbrown/0.6.3/download`, got 502
warning: spurious network error (1 tries remaining): failed to get 200 response from `https://crates.io/api/v1/crates/futures-task/0.3.5/download`, got 502
warning: spurious network error (2 tries remaining): failed to get 200 response from `https://crates.io/api/v1/crates/itertools/0.9.0/download`, got 502
warning: spurious network error (1 tries remaining): failed to get 200 response from `https://crates.io/api/v1/crates/hashbrown/0.6.3/download`, got 502
error: failed to download from `https://crates.io/api/v1/crates/futures-task/0.3.5/download`

Caused by:
  failed to get 200 response from `https://crates.io/api/v1/crates/futures-task/0.3.5/download`, got 502
```

This is during cargo.

It makes our CI fail despite code being fine, thus is contributes to the flakiness of the CI. We might want to give it some thought, and maybe apply a workaround.

Possible solutions are:

- cache dependencies somehow (might help a bit, but might also be a lot of work)
- decouple crates download step and `cargo test` step, and retry download once or twice upon failure (should be easy to do)

**Comment by binarylogic** [comment]
https://github.com/timberio/vector/pull/2435 is also relevant.

**Comment by juchiast** [comment]
Would increasing maximum retry times help? Default cargo's config is

```
[net]
retry = 2                   # network retries
```

**Comment by MOZGIII** [comment]
Yep, that's an option. I think we can set `CARGO_NET_RETRY` env var in CI - it's easier than creating config files.

**Comment by MOZGIII** [comment]
Yet another option is vendoring - https://doc.rust-lang.org/cargo/commands/cargo-vendor.html

**Comment by jszwedko** [comment]
Closing since this hasn't been an issue lately.
