### ISSUE TITLE
support for redis

### ISSUE THREAD

**Issue by shumin1027** [vectordotdev/vector#3319]
vector currently does not support `redis` as a data `source` and `sink`

need to extend  plugins to support `redis` (`list`、`channel`、`pattern channel`、`stream`) as a data `source` and `sink`

**Comment by shumin1027** [comment]
I creat  a plugin to support `redis`(`list`、`channel`) as a data `source` and `sink`

https://github.com/shumin1027/vector/tree/redis

the example config:
```
[sources.in]
type = "redis"
url = "redis://127.0.0.1/0"
key = "vector:in"
data_type = "list"

[sinks.out]
type = "redis"
inputs = ["in"]
url = "redis://127.0.0.1/0"
key = "vector:out"
data_type = "channel"
encoding.codec = "json"
```

**Comment by shumin1027** [comment]
sub-issues:
#5696  add redis source support
#5697  add redis sink support

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/7096 and https://github.com/vectordotdev/vector/issues/5697
