### ISSUE TITLE
Integrate Test Harness into E2E test flows

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#3369]
As a continuation of https://github.com/timberio/vector/pull/3353, we can integrate Test Harness to run conditionally in PRs when a certain label is enabled.

## Plan

- Copy Test Harness into E2E suite; leave the current command-based integration as-is, to test which approach works better.
- Test Harness will be disabled by default in PRs; a certain label can be assigned to the PR to opt-in to run the test on each push.
- Test Harness will share the triggers, and thus will be run daily at the same time as K8s E2E tests; pushes to `master` will NOT cause Test Harness to run - they'll be filtered at the job level.

**Comment by jszwedko** [comment]
Closing since we've deprecated the test-harness.
