### ISSUE TITLE
No such configuration property: "batch.size" batch.size

### ISSUE THREAD

**Issue by lorna1** [vectordotdev/vector#3372]
I want to set Kafka producer batch size.This is my config toml.
# Advanced
librdkafka_options."batch.size" = "204800"

# Error
Sink "kafka": creating kafka producer failed: Client config error: No such configuration property: "batch.size" batch.size 204800

**Comment by jamtur01** [comment]
I was just poking at this and thought I'd dump some findings here. The `batch.size` option is added in librdkafka 1.5.0. The rust-rdkafka client currently uses 1.4.2. Looks like the next release will support 1.5.0.

**Comment by jszwedko** [comment]
Closing since Vector v0.23.0 supports librdkafka 1.7.0 now.
