### ISSUE TITLE
documentation: Support SVGBOB graphs

### ISSUE THREAD

**Issue by Hoverbear** [vectordotdev/vector#3386]
As a documentation writer, I would like to be able to create beautiful, understandable graphics that are also suitable for plaintext code comments or reading/editing.

There is a rust lib which helps with this: https://github.com/ivanceras/svgbob

Demo: https://ivanceras.github.io/svgbob-editor/

It would be very cool if we could use this on our website.

keyword: markdown diagrams

**Comment by binarylogic** [comment]
Ha, I really like the idea behind this. We'll definitely consider this for https://github.com/timberio/vector-website/issues/3.

**Comment by Hoverbear** [comment]
![](https://media.giphy.com/media/l3fzNH5k3gX0maobC/giphy.gif)

**Comment by zsherman** [comment]
Should be able to accomplish this with the new system pretty easily, among other things: https://rhanekom.github.io/gatsby-remark-draw-demo/.

**Comment by jszwedko** [comment]
Closing since we haven't _seemed_ to have a need for this, but we can reopen if we do find one.
