### ISSUE TITLE
Flaky `test_reclaim_disk_space`

### ISSUE THREAD

**Issue by ktff** [vectordotdev/vector#3442]
Ref. #2978 
As per https://github.com/timberio/vector/pull/3416#issuecomment-672414018

Tests whether we reduce our disk usage once we empty our disk buffers. 

https://github.com/timberio/vector/runs/973409685

The test fails before we assert disk size.

**Comment by jszwedko** [comment]
Closing since this test was deleted and seemingly wasn't needed.
