### ISSUE TITLE
Tcp pipe test fails intermittently

### ISSUE THREAD

**Issue by StephenWakely** [vectordotdev/vector#3444]
The pipe test in tests/tcp.rs is failing intermittently - about 1 every 10 - 20 times if I am only running the pipe test. If I run all the tests in tcp.rs it fails almost every time.

### Vector Version
master

### Debug Output1
The trace output is different every time. Dropping the num_lines to 10, these are traces from two of the failures:
  
running 1 test
Aug 13 16:21:27.609  INFO vector::topology: Running healthchecks.
Aug 13 16:21:27.609  INFO vector::topology: Starting source "in"
Aug 13 16:21:27.609  INFO vector::topology: Starting sink "out"
Aug 13 16:21:27.610 DEBUG tokio_reactor: adding I/O source: 0
Aug 13 16:21:27.610 DEBUG tokio_reactor::registration: scheduling Write for: 0
Aug 13 16:21:27.610 DEBUG tokio_reactor: dropping I/O source: 0
Aug 13 16:21:27.610  INFO vector::topology::builder: Healthcheck: Passed.
Aug 13 16:21:27.611  INFO source{name=in type=socket}: vector::sources::util::tcp: listening. addr=127.0.0.1:1234
Aug 13 16:21:27.611 DEBUG source{name=in type=socket}: tokio_reactor: adding I/O source: 4194304
Aug 13 16:21:27.611 DEBUG source{name=in type=socket}: tokio_reactor::registration: scheduling Read for: 0
Aug 13 16:21:27.617 DEBUG source{name=in type=socket}:connection{peer_addr=127.0.0.1}: vector::sources::util::tcp: accepted a new connection peer_addr=127.0.0.1:41900
Aug 13 16:21:27.617 DEBUG source{name=in type=socket}: tokio_reactor: dropping I/O source: 0
Aug 13 16:21:27.617 DEBUG source{name=in type=socket}: vector::topology::builder: Finished
Aug 13 16:21:27.618 DEBUG source{name=in type=socket}:connection{peer_addr=127.0.0.1}: vector::sources::util::tcp: Start gracefull shutdown
Aug 13 16:21:27.619 DEBUG source{name=in type=socket}:connection{peer_addr=127.0.0.1}: tokio_reactor: adding I/O source: 8388608
Aug 13 16:21:27.620 DEBUG source{name=in type=socket}:connection{peer_addr=127.0.0.1}: tokio_reactor::registration: scheduling Read for: 0
Aug 13 16:21:27.620 DEBUG source{name=in type=socket}:connection{peer_addr=127.0.0.1}: vector::sources::util::tcp: connection closed.
Aug 13 16:21:27.620 DEBUG source{name=in type=socket}:connection{peer_addr=127.0.0.1}: tokio_reactor: dropping I/O source: 0
Aug 13 16:21:27.621 DEBUG sink{name=out type=socket}: vector::topology::builder: Finished
thread 'pipe' panicked at 'assertion failed: `(left == right)`
  left: `10`,
 right: `0`', tests/tcp.rs:64:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test pipe ... FAILED

failures:

failures:
    pipe

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

### Debug Output2
  
running 1 test
Aug 13 16:23:08.436  INFO vector::topology: Running healthchecks.
Aug 13 16:23:08.436  INFO vector::topology: Starting source "in"
Aug 13 16:23:08.436  INFO vector::topology: Starting sink "out"
Aug 13 16:23:08.436  INFO source{name=in type=socket}: vector::sources::util::tcp: listening. addr=127.0.0.1:1234
Aug 13 16:23:08.437 DEBUG source{name=in type=socket}: tokio_reactor: adding I/O source: 0
Aug 13 16:23:08.437 DEBUG source{name=in type=socket}: tokio_reactor::registration: scheduling Read for: 0
Aug 13 16:23:08.437 DEBUG source{name=in type=socket}:connection{peer_addr=127.0.0.1}: vector::sources::util::tcp: accepted a new connection peer_addr=127.0.0.1:42592
Aug 13 16:23:08.438 DEBUG source{name=in type=socket}: tokio_reactor::registration: scheduling Read for: 0
Aug 13 16:23:08.439 DEBUG source{name=in type=socket}:connection{peer_addr=127.0.0.1}: tokio_reactor: adding I/O source: 4194305
Aug 13 16:23:08.439 DEBUG source{name=in type=socket}:connection{peer_addr=127.0.0.1}: tokio_reactor::registration: scheduling Read for: 1
Aug 13 16:23:08.439 DEBUG source{name=in type=socket}:connection{peer_addr=127.0.0.1}: vector::sources::util::tcp: connection closed.
Aug 13 16:23:08.440 DEBUG source{name=in type=socket}:connection{peer_addr=127.0.0.1}: tokio_reactor: dropping I/O source: 1
Aug 13 16:23:08.440 DEBUG tokio_reactor: adding I/O source: 8388609
Aug 13 16:23:08.440 DEBUG tokio_reactor::registration: scheduling Write for: 1
Aug 13 16:23:08.441 DEBUG tokio_reactor: dropping I/O source: 1
Aug 13 16:23:08.441  INFO vector::topology::builder: Healthcheck: Passed.
Aug 13 16:23:08.443 DEBUG source{name=in type=socket}: tokio_reactor: dropping I/O source: 0
Aug 13 16:23:08.443 DEBUG source{name=in type=socket}: vector::topology::builder: Finished
Aug 13 16:23:08.444 DEBUG sink{name=out type=socket}: vector::topology::builder: Finished
thread 'pipe' panicked at 'assertion failed: `(left == right)`
  left: `10`,
 right: `0`', tests/tcp.rs:64:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test pipe ... FAILED

failures:

failures:
    pipe

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

**Comment by jszwedko** [comment]
Closing since this test doesn't seem to exist anymore.
