### ISSUE TITLE
Observe end-to-end latency

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#3445]
As part of finishing https://github.com/timberio/vector-product/issues/14, we need to track how long each event spends within each component, ultimately tracking end-to-end latency.

Before I outline requirements, I'd like to understand if this is possible at the topology level, or do we need to instrument this within each component?

cc @lukesteensen

**Comment by Hoverbear** [comment]
I'm going to coordinate with @bruceg on his e2e acking work to make sure our solutions compliment each other.

**Comment by NasAmin** [comment]
We need this too. 
We are trying to track end-to-end latency for vector i.e.
application emits log --> vector agent collects it --> process and transform the log --> push to DD.

We are trying to measure the time it takes from first reading the application log from the k8s source and the DD sink. Looking at the internal_metrics, there seems to be no way of stitching this info even from multiple components 🙏

**Comment by NasAmin** [comment]
@jszwedko sorry for tagging you but is there any news on this? Is this on the roadmap at all?

**Comment by jszwedko** [comment]
> @jszwedko sorry for tagging you but is there any news on this? Is this on the roadmap at all?

Hi @NasAmin !

This is something we are considering doing soon, but hasn't officially been scheduled yet.

**Comment by jszwedko** [comment]
Closing in favor of https://github.com/vectordotdev/vector/issues/14379
