### ISSUE TITLE
`socket` sink octet framing

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#3456]
We received feedback that octet encoding/decoding would be a nice feature for the `socket` source and sink:

> I would be very interested in having support for sources & sinks being able to consume/emit length-value messages, e.g. 4 bytes of network-order integer that specifies the message size, then exactly that many bytes following immediately afterward. 

This is similar to [RFC 6587's octet counting requirement](https://tools.ietf.org/html/rfc6587#section-3.4.1).

Ref #3454, #3453, #257.

**Comment by jszwedko** [comment]
This is supported in the `socket` source via the new `framing.method = "octet_framing"`. Repurposing this for the sink.

**Comment by jszwedko** [comment]
Closing in favor of https://github.com/vectordotdev/vector/issues/12434
