### ISSUE TITLE
Huge multi-line logs from file source handled incorrectly with lua transform

### ISSUE THREAD

**Issue by jschaf** [vectordotdev/vector#3464]
It looks like there's a bug in handling really long multi-line logs (> 1000 lines) in large-ish files > 4MB with the Lua runtime transform.  The error is that the lua transform isn't called on the condition pattern of multiline file.  The Lua transform in the example below expects to start at a newline beginning with `2020`. The multiline config in the file source should guarantee that Lua always receives a string starting with `2020` but it does not. When running the following example, many of the log entries contain "failed to parse timestamp" which is only injected by the Lua transform if the line does not begin with `2020`.

I'm having a tough time getting a small reproducible error. The smallest file I can reproduce the error with is 32k lines, about 2MB in size. Some of the individual log entries contain up to 1500 newlines (because we log some Postgres plans as JSON). Here's my setup:

### vector.toml
```
[sources.postgres_csv_raw_src]
  type = "file"
  include = ["/etc/vector/test-bs-4.csv"]
  start_at_beginning = true

  [sources.postgres_csv_raw_src.fingerprinting]
    strategy = "checksum"
    ignored_header_bytes = 0
    fingerprint_bytes = 1024

  [sources.postgres_csv_raw_src.multiline]
    start_pattern = "^20[0-9][0-9]-[0-1][0-9]-[0-3][0-9] [0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]{3} UTC,\""
    mode = "halt_before"
    condition_pattern = "^20[0-9][0-9]-[0-1][0-9]-[0-3][0-9] [0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]{3} UTC,\""
    timeout_ms = 1000

[transforms.postgres_csv_src]
  type = "lua"
  version = "2"
  inputs = ["postgres_csv_raw_src"]
  search_dirs = ["/etc/vector/lua"]
  source = "pg = require('postgres')"
  hooks.process = "pg.parse_csv_entry"

[sinks.test_output]
  type = "file"
  inputs = ["postgres_csv_src"]
  path = "/pkg/src/test-bs-4.out.txt"
  encoding.codec = "ndjson"
```

### postgres.lua

```lua
local pg = {}

function pg.parse_csv_entry(event, emit)
  if string.sub(event.log.message, 1, 4) ~= '2020' then
    event.log.message = "failed to parse timestamp: " .. string.sub(event.log.message, 1, 100)
  end
  emit(event)
end

return pg
```

Some debugging notes:

- If I bisect from 32k lines to 16k lines to either the first or second half of the file, the errors go away.
- If I run Vector on the same file a second time, sometimes there are no errors and sometimes the number of errors change, usually decreasing.

**Comment by jszwedko** [comment]
Hi @jschaf ! Apologies that this was never triaged. Is it still affecting you? Given this issue is a couple of years old we are going to close it, but please feel free to reopen if it is still relevant. If you do reopen, an example input file to trigger the issue would be helpful.
