### ISSUE TITLE
Proper place for `line_agg` (separate crate?)

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#3471]
This is issue is a place where we can discuss the `line_agg`, and where it can be placed. It's a good candidate to be extracted into a dedicated crate, as, currently, it does not have strong connectivity at all with vector-related types.

This is a follow up from https://github.com/timberio/vector/pull/3451#issuecomment-674456398. Also related is #3357.

**Comment by MOZGIII** [comment]
To begin with, technically, it's definitely possible to extract `line_agg` to a dedicated crate. The question is, what motivation do we have to do so.

Let's consider the potential motivations from https://github.com/timberio/vector/pull/3357#pullrequestreview-467151890.

Regarding (1), I'd rather keep the `line_agg` private for now - in a sense that we don't support compatibility beyond the needs of Vector. I'm planning to introduce a few changes to `line_agg` interfaces, and it's quite trivial to conduct in a monorepo-style environment, but not so much if we have to look out for external compatibility. I know technically we can set version < 1, and by semver rules be free to break compat every release - and this would actually be a file solution if we'd want to extract a crate. I wouldn't upload it to crates.io (yet).

For (2) it would hardly be an improvement, due to the simplicity of the change. I feel like for something like `line_agg`, having a dedicated crate wouldn't change the modularity situation - it's a mod already - however it will slightly increase the management overhead. Not sure it's worth it.

With (3) - it should be very easy to actually *measure* the effect. So why don't we try it? I bet it won't be noticeable though.

In general -  I'd love to see the very core logic/rules extracted for community use, but I'd rather give the community a chance to fork it, rather than doing it ourselves. The reason is the logic is sort of very niche, and we might want work a bit more on it, and reserve the flexibility to introduce changes easily. We can extract the crate though - it doesn't matter much in this regard.

**Comment by jszwedko** [comment]
Closing due to lack of motivation.
