### ISSUE TITLE
remove a metric in prometheus sinks when the metric don't update any more

### ISSUE THREAD

**Issue by LinkSyk** [vectordotdev/vector#3477]
I transform a log to metric by log_to_metrics and sink to prometheus. when the metric don't update, the prometheus still keep the metric and don't remove it. there is any way to remove the metric?

**Comment by Miconoclast** [comment]
sinks:prometheus

**Comment by Miconoclast** [comment]
> I transform a log to metric by log_to_metrics and sink to prometheus. when the metric don't update, the prometheus still keep the metric and don't remove it. there is any way to remove the metric?

**Comment by jszwedko** [comment]
This has been added as https://vector.dev/docs/reference/configuration/sinks/prometheus_exporter/#flush_period_secs
