### ISSUE TITLE
Change default in-memory buffer size

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#351]
This is more of an exploratory issue. Currently, buffers default to the `memory` type with a size of `200`. I'm curious what happens when this overflows?

- Does it make more sense to raise this?
- Should this value be changed depending on the role (agent or service)?
- And should this be auto-calculated based on the size of the host?

**Comment by jszwedko** [comment]
Closing since we don't seem to have any motivation to change this. Currently it is 500. Documentation around buffer behavior when full is here: https://vector.dev/docs/about/under-the-hood/architecture/buffering-model/
