### ISSUE TITLE
can't generate Yocto recipe

### ISSUE THREAD

**Issue by chezgi** [vectordotdev/vector#3511]
most of embedded devices use yocto for creating os release.
and vector is a good choice for log in embedded area.
i want to add vector to yocto. after some works i failed to do that.

my steps:
1- cargo-bitbake: auto generate recipe  from  toml file.
2- use meta-rust layer

problem:
some dependencies are from github and cant be used with meta-rust.

solution:
if all dependencies come from stable cargo repositories we can use vector in yocto.

**Comment by fanatid** [comment]
Thanks. Can you share `cargo build` output?

**Comment by chezgi** [comment]
[vector.bb.txt](https://github.com/timberio/vector/files/5148542/vector.bb.txt)

**Comment by chezgi** [comment]
this is bitbake do_compile log:

```
DEBUG: Executing shell function do_compile
NOTE: cargo = /WorkingDir/soodar/soo-yocto/yocto/build/tmp/work/corei7-64-soodaros-linux/vector/0.10.AUTOINC+50686560c8-r3/recipe-sysroot-native/usr/bin/cargo
NOTE: rustc = 
NOTE: cargo build -v --target x86_64-soodaros-linux --release 
    Updating git repository `https://github.com/timberio/leveldb`
error: failed to get `leveldb` as a dependency of package `vector v0.10.0 (/WorkingDir/soodar/soo-yocto/yocto/build/tmp/work/corei7-64-soodaros-linux/vector/0.10.AUTOINC+50686560c8-r3/git)`

Caused by:
  failed to load source for dependency `leveldb`

Caused by:
  Unable to update https://github.com/timberio/leveldb#64265815

Caused by:
  failed to clone into: /WorkingDir/soodar/soo-yocto/yocto/build/tmp/work/corei7-64-soodaros-linux/vector/0.10.AUTOINC+50686560c8-r3/cargo_home/git/db/leveldb-3fa4380c440b6995

Caused by:
  invalid version 3 on git_proxy_options; class=Invalid (3)
WARNING: exit code 101 from a shell command.
ERROR: Execution of '/WorkingDir/soodar/soo-yocto/yocto/build/tmp/work/corei7-64-soodaros-linux/vector/0.10.AUTOINC+50686560c8-r3/temp/run.do_compile.41259' failed with exit code 101:
    Updating git repository `https://github.com/timberio/leveldb`
error: failed to get `leveldb` as a dependency of package `vector v0.10.0 (/WorkingDir/soodar/soo-yocto/yocto/build/tmp/work/corei7-64-soodaros-linux/vector/0.10.AUTOINC+50686560c8-r3/git)`

Caused by:
  failed to load source for dependency `leveldb`

Caused by:
  Unable to update https://github.com/timberio/leveldb#64265815

Caused by:
  failed to clone into: /WorkingDir/soodar/soo-yocto/yocto/build/tmp/work/corei7-64-soodaros-linux/vector/0.10.AUTOINC+50686560c8-r3/cargo_home/git/db/leveldb-3fa4380c440b6995

Caused by:
  invalid version 3 on git_proxy_options; class=Invalid (3)
WARNING: exit code 101 from a shell command.
```

**Comment by fanatid** [comment]
This looks like your issue: https://github.com/rust-lang/rust/issues/63476 :disappointed:

**Comment by chezgi** [comment]
is there any temporary solution to this problem?
what i must do for this?

**Comment by fanatid** [comment]
Hmm, if a problem in cloning with git maybe this can be solved if you clone dependencies to local storage manually and change `git` to `path` in `Cargo.toml`?

**Comment by mickeypash** [comment]
~Bump. I'm also interested in this

**Comment by jszwedko** [comment]
It seems like the linked issue was resolved in Rust. Maybe it would work now? I'm not familiar with Yocto so it'd probably be best if someone who is would give it a shot and let us know if there are any additional issues.

**Comment by jszwedko** [comment]
Closing this due to lack of response since it seems like it should work now as the linked Rust issue was resolved, but please leave a comment if it isn't.

**Comment by antoinefaure** [comment]
Hi,
Has someone successfully written a Yocto recipe for vector ?
