### ISSUE TITLE
generate: UTF-8 errors on Windows.

### ISSUE THREAD

**Issue by Hoverbear** [vectordotdev/vector#3512]
It seems `vector generate stdin//console > foo.toml` or similar commands seem to generate a lot of ` ` characters.

See the clion window here: 
![image](https://user-images.githubusercontent.com/130903/90790940-7d790180-e2bd-11ea-9fdd-c399122b0051.png)

Trying to run this, despite it looking fine on console and in notepad, results in this error:

![image](https://user-images.githubusercontent.com/130903/90791026-95508580-e2bd-11ea-8574-6a2e02c7ee9d.png)

### Vector Version

```powershell
PS C:\Users\ana\CLionProjects\vector> .\target\debug\vector.exe  --version
vector 0.11.0 (gee1651d x86_64-pc-windows-msvc 2020-08-20)
```

### Vector Configuration File

So this is the weird part, reading it from command line gives:

```powershell
PS C:\Users\ana\CLionProjects\vector> cat .\foo.toml
data_dir = "/var/lib/vector/"

[sources.source0]
max_length = 102400
type = "stdin"

[sinks.sink0]
healthcheck = true
inputs = ["source0"]
type = "console"

[sinks.sink0.buffer]
type = "memory"
max_events = 500
when_full = "block"

 ```

And Neovim:

![image](https://user-images.githubusercontent.com/130903/90792004-c7aeb280-e2be-11ea-9080-51d6bacb820c.png)

But when I look at it in clion:

```
d a t a _ d i r   =   " / v a r / l i b / v e c t o r / " 
 
 
 
 [ s o u r c e s . s o u r c e 0 ] 
 
 m a x _ l e n g t h   =   1 0 2 4 0 0 
 
 t y p e   =   " s t d i n " 
 
 
 
 [ s i n k s . s i n k 0 ] 
 
 h e a l t h c h e c k   =   t r u e 
 
 i n p u t s   =   [ " s o u r c e 0 " ] 
 
 t y p e   =   " c o n s o l e " 
 
 
 
 [ s i n k s . s i n k 0 . b u f f e r ] 
 
 t y p e   =   " m e m o r y " 
 
 m a x _ e v e n t s   =   5 0 0 
 
 w h e n _ f u l l   =   " b l o c k " 
 
 
 
 ```

![image](https://user-images.githubusercontent.com/130903/90792028-d09f8400-e2be-11ea-9f7d-94b6aaefa643.png)

And Visual Studio:

![image](https://user-images.githubusercontent.com/130903/90792327-325fee00-e2bf-11ea-94d6-3dd07edb9394.png)

## Suspect Cause

I am reasonably certain this is a line ending (CRLF vs LF etc) issue. Recall that Windows uses prefers CRLF line endings. You can see in the Clion image it's reading the file as a LF ending, and the others are using CRLF. It's likely we're either writing the file in an unexpected way.

Workaround:

1. Open file in clion and notepad at same time. 
2. Copy text in notepad.
3. Delete contents of file in clion.
4. Change line endings from LF to CRLF in Clion.
5. Paste notepad contents over.
6. Save.

```powershell
PS C:\Users\ana\CLionProjects\vector> .\target\debug\vector.exe  --config foo.toml
Aug 20 08:38:41.364  INFO vector::cli: Log level "info" is enabled.
Aug 20 08:38:41.367  INFO vector::cli: Loading configs. path=["foo.toml"]
Aug 20 08:38:41.403 ERROR vector::cli: Configuration error: "foo.toml": missing field `encoding` for key `sinks.sink0`

```

**Comment by jszwedko** [comment]
Closing as stale. We'll let a user re-raise this if it is still an issue.
