### ISSUE TITLE
Further parse Syslog lines

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#353]
Within the `syslog` source we do some light parsing which only extracts 2 fields: `host` and `timestamp`. While I understand the format is not strictly adhered to, we should be able to parse out the [defined Syslog fields](https://tools.ietf.org/html/rfc5424) to something like:

```
{
  "timestamp": "...",
  "host": "...",
  "message": "..."
  "app": "...",
  "proc_id": "...",
  "prioirty": "...",
  "severity": "...",
  "...": "..."
}
```

The severity can be calculated from the priority. In addition, we should also be parsing the structured data. It appears to be in a simple k/v structure:

```
[exampleSDID@32473 iut="3" eventSource="Application" eventID="1011"]
```

And

```
[exampleSDID@32473 iut="3" eventSource="Application" eventID="1011"][examplePriority@32473 class="high"]
```

These fields should explode out into root level keys. So the `eventSource`, `eventID`, and `class` keys would be added to the root level event structure for the above examples.

Both are examples listed in the [RFC](https://tools.ietf.org/html/rfc5424#section-6.3).

**Comment by binarylogic** [comment]
@lukesteensen just confirming, is there any reason these fields aren't included? I'd like to have @kirillt further parse the lines and include this data if not.

**Comment by lukesteensen** [comment]
Oops, answered this elsewhere but forgot to post here.

There is no reason the fields aren't included and we should feel free to go ahead and do so. They already get parsed, we just don't add them to the event. We will want to think about namespacing since they're somewhat hierarchical, but that should be simple enough (e.g. `{{namespace}}.{{key}}`).

**Comment by kirillt** [comment]
@lukesteensen Yep, I implemented basic version of this yesterday. For structured data (where we have map of map) I flatten keys and put entries into events like this: `id1.name11=value11`, `id2.name21=value21`, etc.

**Comment by lukesteensen** [comment]
@kirillt That sounds good!

**Comment by kirillt** [comment]
I figured out one corner case, which works not the way I expected.
Structured data without children, e.g. `[id1]`, produces no map at all.

Personally, I expected that it would produce empty map, but `syslog_rfc5424` works this way.
Should we handle this or this behavious is OK?
