### ISSUE TITLE
Support metrics in the `geoip` transform

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#3549]
In order to properly correlate logs and metrics across geoip dimensions, Vector should support metrics in the `geoip` transform, adding the same logs fields as metric labels.

**Comment by markonen** [comment]
@binarylogic did you have something specific in mind?

As a user, the primary challenge I see with geoip metrics is tag cardinality. Broadly speaking, geoip is only useful on internet-facing services, and those are pretty much guaranteed to get traffic (port scans, if nothing else) from an essentially unlimited number of locations.

The most useful feature to me would be a facility for declaring that I'm interested in a Country metric with, say, "US" and "FI" buckets, with the rest optionally going to an "other" bucket. That metric would then be guaranteed to result in a maximum of three tag values.

But then again, such a facility would be broadly useful in the general case as well, for example when combined with log_to_metric. I'm bit of a Vector metrics n00b so can you confirm that no such facility exists beyond do-it-yourself Lua scripting?

Anyway, geoip automatically emitting metrics for all fields seems like a bit of a foot gun to me, as the use cases I can envision would all require significant filtering.

**Comment by binarylogic** [comment]
Thanks @markonen, I added the above labels to pause work and define the requirements. I agree that we do not want to add high cardinality labels to metrics. I'll review and close if there is not benefit to supporting metrics.

**Comment by jszwedko** [comment]
Closing since we added the ability to enrich from geoip dbs via enrichment tables in #9283
