### ISSUE TITLE
test-shutdown is failing

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#3556]
This appears to be failing consistently:

https://github.com/timberio/vector/pull/3507/checks?check_run_id=1022370783

I'm curious if https://github.com/timberio/vector/pull/3526 is related.

**Comment by ktff** [comment]
@fanatid are you investigating this issue with `env = "VECTOR_QUIET"` added in #2149?

**Comment by fanatid** [comment]
No, I'm not working on this right now. #3526 is not related to a failed test.

I tried to figure out how to fix it but did not found a simple solution. [Arg::env](https://docs.rs/clap/2.33.3/src/clap/args/arg.rs.html#3595-3597) implicitly set `take_value` to `true` so `quiet` / `verbose` do not work correct.

**Comment by jamtur01** [comment]
I think maybe it's worth removing VERBOSE/QUIET as env variables? I could make a case that they aren't overly useful?
