### ISSUE TITLE
Define & document option naming rules

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#3632]
As I work through the reference docs I'm realizing our option names could benefit from some rules and consistency. Specifically:

1. Suffixing options with their unit. Ex: `_seconds`, `_bytes`, etc.
2. Not repeating the namespace in the option name. Ex: `fingerprinting.fingerprint_bytes`.
3. Normalizing around time units where relevant and possible. Ex: using seconds and milliseconds when we should settle on one.
4. Using nouns as category names. Ex: `fingerprint` instead of `fingerprinting`.

**Note: This has a high chance of bikeshedding. I don't care too much about the specifics in the rules, as long as we're consistent since it creates a better UX.**

**Comment by jszwedko** [comment]
Covered by https://github.com/vectordotdev/vector/blob/master/docs/specs/component.md
