### ISSUE TITLE
Rework use of Option<usize> to represent parsed in_flight_limit

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#3678]
Once parsed, the `in_flight_limit` setting may either be automatic (with no explicit maximum) or fixed with a given limit. Since this fits into an `Option<usize>`, that type was used. However, this type lacks clarity, as `None` is used to represent automatic instead of having no limit (there is an internal hard-coded limit), and `Some(_)` is used to represent a fixed limit.

In order to clarify the semantics of this value, this setting should be reworked to use a custom enum like `enum X { Auto, Fixed(usize) }` that properly names the states.

**Comment by jszwedko** [comment]
Closing as tech debt that is unlikely to be picked up on its own.
