### ISSUE TITLE
Refactor sources that scrape an endpoint on an interval

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#3702]
With the upcoming introduction of the `apache_metrics` and `nginix_metrics` sources, we'll have three sources that operate in a very similar manner. Namely:

* Scrape an HTTP endpoint on an interval
* Parse the results to generate metrics

As such, I think it'd be useful to refactor them to share internal components similar to how the HTTP-client-based sinks (`humio`, `splunk`, `http`) do. This should make it easier to add more of these types of sources in the future.

**Comment by bruceg** [comment]
This could also be useful for the host metrics source, except that it won't be scraping a remote endpoint but rather local sources. The process will be much the same otherwise.
