### ISSUE TITLE
New `format_number` remap function

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#3744]
Like #3742 but for numbers.

## Example

Given this event:

```js
{
  "total": 1234.567
}
```

And this remap function:

```
.total = format_number(.total, 2, true)
```

Would result in:

```js
{
  "total": "1,234.56"
}
```

**Comment by JeanMertz** [comment]
As a European, I'm taking the liberty of changing the function signature a bit:

```rust
format_number(value = .foo, scale = 2, decimal_separator = ",", grouping_separator = ".") // "1.234,56"
```

_(using keyword arguments for clarity here, but all keyword arguments can be written as positional arguments)_

* `value` is a required parameter
* `scale` defaults to the existing scale of the value
* `decimal_separator` defaults to `.`
* `grouping_separator` defaults to `⁣` (i.e. none)

**Comment by jszwedko** [comment]
:+1: to allowing the separators to be configured. This feels like one place we could fall back to the system locale if we wanted.

**Comment by bruceg** [comment]
Agreed on falling back to (or defaulting to) the system locale. Would a `locale` parameter be better than manually specifying the separators manually? Also, is this `format_number` or `format_decimal`? (numbers may also be hexadecimal, etc) Would `precision` be a better term than `scale`?

**Comment by JeanMertz** [comment]
Those are all valid points @jszwedko and @bruceg. I have an initial version that doesn't implement your suggestions in https://github.com/timberio/vector/pull/4220.

I suggest we get that one merged first, and then iterate on whatever we think makes sense (either keeping existing options and extending with `locale`, or just using `locale` without anything else, and also looking at system locale for sane defaults.
