### ISSUE TITLE
New `replace` remap function

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#3750]
The `replace` remap function replaces all occurrences of a string.

## Examples

Given the following event:

```js
{
  "message": "I like apples and bananas"
}
```

### String literal

And the following remap instruction set:

```
.message = replace(.message, "a", "o")
```

Would produce:

```js
{
  "message": "I like opples and bononos"
}
```

### Regex

And the following remap instruction set:

```
.message = replace(.message, /a/, "o")
```

Would produce:

```js
{
  "message": "I like opples and bononos"
}
```

**Comment by FungusHumungus** [comment]
I think it would be a good idea to allow for flags to be added to the regexes.

The three I can think of that would be useful are case-insensitive (i), multiline (m) and global (g).

In which case the given example would only replace the first occurrence of `a`.

```
.message = replace(.message, /a/, "o")

{
  "message": "I like opples and bananas"
}
```

But with the global flag would give:


```
.message = replace(.message, /a/g, "o")

{
  "message": "I like opples ond bononos"
}
```

What do you think?

**Comment by binarylogic** [comment]
I'm a fan. Do you think it would be more discoverable as optional arguments?

```
.message = replace(.message, /a/, "o", case_sensitive: false)
```

Thinking about the case where a user would supply a string instead of a regex.

```
.message = replace(.message, "a", "o", case_sensitive: false)
```

**Comment by FungusHumungus** [comment]
Yes, it would be very useful to allow these flags when you supply a string too. The parameter here doesn't have to be a hardcoded string - it could be an event field or the result of a previous computation, so we couldn't say to just fall back to a regex if you need case insensitive searches in those cases.

There might be a case for doing both. The two places I am aware of that use the `/../` syntax for regexes - javascript and vim - both allow the flags after the regex. Personally, I would naturally expect the flags there and probably wouldn't even think to check the docs to see if they should be.

If we did provide both, and the script provided conflicting parameters this is something that could be picked up at parse time so could be validated fairly easily.

But, if we have to choose just one, my vote would be for optional parameters..

**Comment by binarylogic** [comment]
👍 sounds good, supporting both works for me.
