### ISSUE TITLE
cross testing: Tests with timestamp parsing fail.

### ISSUE THREAD

**Issue by Hoverbear** [vectordotdev/vector#3771]
During #3657 we found we could not enable CI testing due to the following tests failing:

```
failures:

---- types::tests::parse_timestamp_auto stdout ----
thread 'types::tests::parse_timestamp_auto' panicked at 'assertion failed: `(left == right)`
  left: `Ok(2001-02-03T14:05:06Z)`,
 right: `Ok(2001-02-03T04:05:06Z)`', src/types.rs:320:9

---- types::tests::timestamp_param_conversion stdout ----
thread 'types::tests::timestamp_param_conversion' panicked at 'assertion failed: `(left == right)`
  left: `Ok(Timestamp(2001-02-03T14:05:06Z))`,
 right: `Ok(Timestamp(2001-02-03T04:05:06Z))`', src/types.rs:310:9

---- types::tests::timestamp_conversion stdout ----
thread 'types::tests::timestamp_conversion' panicked at 'assertion failed: `(left == right)`
  left: `Ok(Timestamp(2001-02-03T14:05:06Z))`,
 right: `Ok(Timestamp(2001-02-03T04:05:06Z))`', src/types.rs:301:9
```

These seem to be related to an incorrectly set timezone somewhere. I worked with @jamtur01 a bit on this but we did not find anything.

Replicated by `make test-x86_64-unknown-linux-gnu AUTOINSTALL=true` on the `cross-targets` branch.

**Comment by MOZGIII** [comment]
Is this still an issue?

**Comment by Hoverbear** [comment]
Indeed.

**Comment by blt** [comment]
Possibly related to https://github.com/timberio/vector/issues/6784

**Comment by jszwedko** [comment]
Closing since I don't think we'll be picking up testing in via `cross` due to the lack of value given I don't think we've ever had a platform specific bug reported that cross would have caught.
