### ISSUE TITLE
K8s: cache the test code builds at CI

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#3796]
In our K8s CI E2E test suite, we have two build steps: building vector itself (into a `.deb`, and eventually a docker image) and building the test code, that's also written in rust. We've discussed the first part a lot in the past, but the second part not so much, yet it can be optimized too.

The test code required a very small amount of time to build - it's one of it's explicit design goals. It doesn't depend on a `vector` crate, and avoids going through building all of the dependencies that vector itself uses. Yet it still takes time to prepare the rust environment at the CI and build this test code - overall increasing one execution by something around 5 to 10 minutes.

We can add caching to the CI for this second build step. It should be very efficient since that code changes very rarely, and the produced binaries are independent of the test target. Furthermore, the footprint of the data to cache should very small, and thus adding caching should be trivial.

**Comment by jszwedko** [comment]
Closing since this hasn't seem to be needed.
