### ISSUE TITLE
Remove `encoding` code duplicates in sinks

### ISSUE THREAD

**Issue by ktff** [vectordotdev/vector#3853]
We can remove duplicates of 
https://github.com/timberio/vector/blob/27ba8b950b752dcb5316bacd40247dbf05437386/src/sinks/util/mod.rs#L52-L55

and variants of
https://github.com/timberio/vector/blob/27ba8b950b752dcb5316bacd40247dbf05437386/src/sinks/util/mod.rs#L62

that we have scattered in our sinks and replace them with those and extract some more shared functionality.

### References
* This issue should wait for #3852 to be merged.

**Comment by jszwedko** [comment]
Closing since this was refactored into a shared layer in `src/codecs`.
