### ISSUE TITLE
Vector should reload added/removed/renamed configuration files when using a wildcard

### ISSUE THREAD

**Issue by ChrisSimmons** [vectordotdev/vector#3857]
### Vector Version

```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
```

### Steps

- Establish configuration files:
  - `/etc/vector/config/1-sources.toml`
  - `/etc/vector/config/2-transforms.toml`
  - `/etc/vector/config/3-sinks.toml`
- Start Vector with `vector --config /etc/vector/config/*.toml`
- Relevant output line:

``` text
INFO vector: Loading configs. path=["/etc/vector/config/1-sources.toml", "/etc/vector/config/2-transforms.toml", "/etc/vector/config/3-sinks.toml"]
```

- Add a new transform TOML config `/etc/vector/config/2.5-transform-special.toml`
- `kill -s SIGHUP pid_of_vector` to reload config

### Expected Behavior

I would think that it would pick up the new configuration file on the reload:

``` text
INFO vector: Reloading configs. path=["/etc/vector/config/1-sources.toml", "/etc/vector/config/2-transforms.toml", "/etc/vector/config/2.5-transform-special.toml", "/etc/vector/config/3-sinks.toml"]
```

### Actual Behavior

It reloads the same set of files it was loaded with initially:

``` text
INFO vector: Reloading configs. path=["/etc/vector/config/1-sources.toml", "/etc/vector/config/2-transforms.toml", "/etc/vector/config/3-sinks.toml"]
```

**Comment by binarylogic** [comment]
Thanks @ChrisSimmons, I agree. We’ll get on it.
