### ISSUE TITLE
Internal instrumentation

### ISSUE THREAD

**Issue by vector-vic** [vectordotdev/vector#3900]
## Summary
As a crucial part of customers' observability infrastructures, it's important that Vector itself be as transparent and understandable as possible.

## Jobs to be done
- Vector should expose instrumentation consistently from every component, and in sufficient detail to help narrow down the cause when something goes wrong.

## Requirements
- There should be a consistent set of metrics emitted from every component that covers the standard performance indicators relevant to all Vector configs
- Each component should be further instrumented with metrics specific to the significant sections of its execution
- Update `vector top` to new in/out component metrics

## Out of scope
- This is about instrumenting Vector and its components to generate the relevant data, not about forwarding or displaying it in any particular way

**Comment by vector-vic** [comment]
Link to feature: https://timber.productboard.com/feature-board/planning/features/5156253

**Comment by jszwedko** [comment]
Just noting that it'd be good to come up with a set of conventions for metric naming as part of this. Right now we have a mix of, for example, "failed' vs "failures" vs "errors" in counter names.

**Comment by binarylogic** [comment]
@jszwedko this is covered by https://github.com/timberio/vector/blob/master/docs/USER_EXPERIENCE_DESIGN.md#metric-naming. We will need to open issues for the inconsistencies.

**Comment by jszwedko** [comment]
Closing this since Vector is fairly well instrumented at this point and we have issues for specific changes we want to make.
