### ISSUE TITLE
Compose sources and sinks with each other

### ISSUE THREAD

**Issue by vector-vic** [vectordotdev/vector#3907]
Level 1 proposed in the [composing components RFC](https://github.com/timberio/vector/blob/master/rfcs/2020-10-06-3791-composing-components-pt-1.md).

**Comment by vector-vic** [comment]
Link to feature: https://timber.productboard.com/feature-board/planning/features/5577236

**Comment by jszwedko** [comment]
Closing this since we have started to do this with new components when possible.
