### ISSUE TITLE
Collect Kubernetes cluster event logs (audit)

### ISSUE THREAD

**Issue by vector-vic** [vectordotdev/vector#3909]
<p></p>

**Comment by vector-vic** [comment]
Link to feature: https://timber.productboard.com/feature-board/planning/features/5609617

**Comment by koolay** [comment]
Any plan about it ?

**Comment by jszwedko** [comment]
Closing since this was just used for tracking. It is covered by https://github.com/vectordotdev/vector/issues/1424

**Comment by MartinEmrich** [comment]
Kubernetes audit logs (https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/) are not kubernetes events (https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/event-v1/)

It looks like #1424 is about the former.

Is there support for (or an open feature request) for the latter? (like tailing `kubectl get events -A -w` into Vector)?

**Comment by jszwedko** [comment]
> Kubernetes audit logs (https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/) are not kubernetes events (https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/event-v1/)
> 
> It looks like #1424 is about the former.
> 
> Is there support for (or an open feature request) for the latter? (like tailing `kubectl get events -A -w` into Vector)?

Thanks for flagging. You are right that #1424 is just about audit logs. We have https://github.com/vectordotdev/vector/issues/1293 tracking events.
