### ISSUE TITLE
Source data - Amazon Web Services (AWS)

### ISSUE THREAD

**Issue by vector-vic** [vectordotdev/vector#3917]
Vector currently offers weak support when it comes to collecting logs & metrics from AWS. While we offer host-level sources like `file` and `journald`, we don't offer guidance around how to use them in the AWS context. Additionally, we don't *collect* log or metrics data from AWS services like CloudWatch, which is arguable the most important log source for AWS. This epic represents our initial effort towards resolving this, it will be a combination of development and documentation efforts.

<p></p>

Note, this epic appears larger than it is. Once we support AWS CloudWatch most of these services can be supported through guides.

# User Needs

As a user, I want the...

1. ABILITY to COLLECT logs from AWS API Gateway, so that I can analyze the logs of my provisioned API Gateway domains.

2. ABILITY to COLLECT logs from AWS CloudWatch, so that I can analyze them in a more capable storage.

3. ABILITY to COLLECT metrics from AWS CloudWatch, so that I can analyze them in a more capable storage.

4. ABILITY to COLLECT logs from AWS CloudTrail, so that I can analyze them in a more capable storage.

5. ABILITY to COLLECT logs from AWS EC2, so that I can analyze the logs of my EC2 hosts.

6. ABILITY to COLLECT logs from AWS ECS, so that I can analyze the logs of my ECS services.

7. ABILITY to COLLECT logs from AWS EKS, so that I can analyze the logs of my EKS services.

8. ABILITY to COLLECT logs from AWS Elasticsearch, so that I can analyze the logs of my ES clusters.

9. ABILITY to COLLECT logs from AWS Kinesis, so that I can analyze the logs of my Kinesis streams.

10. ABILITY to COLLECT logs from AWS Lambda, so that I can analyze the logs of Lambda functions.

11. ABILITY to COLLECT logs from AWS RedShift, so that I can analyze the logs of my Redshift clusters.

12. ABILITY to COLLECT logs from AWS RDS, so that I can analyze the logs of my RDS instances.

#

**Comment by vector-vic** [comment]
Link to feature: https://timber.productboard.com/feature-board/planning/features/5155821

**Comment by jszwedko** [comment]
Closing this since we have individual issues.
