### ISSUE TITLE
Add a CLI command to generate a "getting started" config file

### ISSUE THREAD

**Issue by JeanMertz** [vectordotdev/vector#3931]
We currently support `vector generate` to generate a config file given a list of components. This works great, but it requires at least _some_ knowledge about Vector and its different components.

I had a need yesterday to quickly get a simple `vector.toml` config file without caring too much about what was in it, I basically just wanted it to have the correct structure, and have a simple source->transform->sink set-up.

It would be nice if we had a `vector example` command or something similar that returns a valid config file to stdout, which uses the `stdin` source, the `json_parser` transform (probably with `drop_invalid = false`), and a `console` sink.

That way, wherever I install Vector, I can do:

```
vector example > vector.toml
vector --config vector.toml
```

And have a working example I can play with.

The example could also contain inline comments to explain what's what, and provide links to the documentation to learn more. We could probably also add the `internal_metrics` source and link it up to the `console` sink, but have it commented out by default, so that the user can simply uncomment those lines to see what Vector is doing internally.

---

Now, there are many edge-cases worth considering here (and besides those edge-cases, some might find such a command not worth our time), and @Hoverbear already listed some of those in Discord, but @zsherman still thought it'd be a useful feature to have, and worthy a proper discussion in a GH issue, so here we are.

**Comment by JeanMertz** [comment]
Note that I'm aware we already install example configs and a working `vector.toml` file in `/etc/vector` (or `/usr/local/etc/vector` in my case), but it's still less discoverable.

Maybe we should instead have `vector example` be a way in to print those files without having to look for them on your file system? E.g. `vector example list` lists the names of all example files we ship with the installation, and `vector example show <name>` prints the example to stdout. That wouldn't work on a system that has the `vector` binary, but not the extra files, though.

**Comment by Hoverbear** [comment]
If `vector generate` worked as users expected** (by including required fields in a config), and, say, generated some default config when no argument  were provided, then this ticket is rendered as a simple alias to `vector generate`.

Because of this, I'd sooner suggest we make `vector generate` work better, and not invest time into new commands.

**Comment by jszwedko** [comment]
:+1: I like the idea of `vector generate` with no args generating a simple config (stdin -> json -> console).

**Comment by JeanMertz** [comment]
> and, say, generated some default config when no argument were provided

Sure 👍 I'm not suggesting it _needs_ to be a separate command, merely that having a command that generates something without having to specify any input would increase usability.

In Discord, I proposed `vector init`, but I don't quite like the implication that name gives, `vector example` was the best I could come up with, since `vector generate` already exists, but I do agree that re-using `vector generate` for this purpose, when you don't pass it any arguments, seems like a good fit, given its name.
