### ISSUE TITLE
Route failed events through separate pipelines

### ISSUE THREAD

**Issue by vector-vic** [vectordotdev/vector#3939]
See the [reliability brief requirements](https://docs.google.com/document/d/19lW76R94Rf9AZ5lfZZyeXqa35xNQincc2a-Fx2xmKcI/edit#heading=h.t1cfia9bu3t1) for full context.

**Comment by vector-vic** [comment]
Link to feature: https://timber.productboard.com/feature-board/planning/features/5628989

**Comment by jszwedko** [comment]
Noting this came up in discord: https://discord.com/channels/742820443487993987/746070591097798688/787428006707724309

**Comment by jszwedko** [comment]
Noting this came up again: https://discord.com/channels/742820443487993987/764187584452493323/788165200212656149

**Comment by jszwedko** [comment]
Another discord request for this feature: https://discord.com/channels/742820443487993987/746070591097798688/814418705294426132

**Comment by Spoonbender** [comment]
Is it possible to access metadata about the circumstances in which the event died? e.g. time of death, cause of death?

**Comment by jszwedko** [comment]
Noting this came up again in Discord: https://discord.com/channels/742820443487993987/764187584452493323/835568065076920320

**Comment by jszwedko** [comment]
Another discord request, though a slight variation: https://discord.com/channels/742820443487993987/746070591097798688/846758495008849970

They'd like to use the healthcheck to determine when to send to the fallback sink.

**Comment by JeanMertz** [comment]
Came up today in https://discord.com/channels/742820443487993987/746070591097798688/869518588925603840.

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/9417
