### ISSUE TITLE
Debug Vector - Error codes

### ISSUE THREAD

**Issue by vector-vic** [vectordotdev/vector#3948]
Helping users debug Vector errors goes a long way in improving the operating UX for Vector. Assigning codes to erros will force us to inventory them and connect them with properl documentation. It is our intent to link users to a description of the error, common causes, and suggestions for resolving it.

# User needs

As a user, I need the...

1. Ability to understand, in depth, what an error means, so that I can properly resolve the error.

2. Learn about common causes of an error, so that I can properly resolve the error.

3. Learn about common resolutions to an error, so that I can properly resolve the error.

**Comment by vector-vic** [comment]
Link to feature: https://timber.productboard.com/feature-board/planning/features/5156256

**Comment by jszwedko** [comment]
Closing since this was just used for tracking.
