### ISSUE TITLE
Source traces - Initial support

### ISSUE THREAD

**Issue by vector-vic** [vectordotdev/vector#3949]
Vector aims to receive and process tracing data like other observability data. To kick off these efforts we want to build in support for receiving traces from apps.

# User needs

As a user, I need the...

1. Ability to receive OpenTelmetry traces, so that I can ingest tracing data into Vector for processing and fan-out.

2. Ability to receive Jaeger traces, so that I can ingest tracing data into Vector for processing and fan-out.

**Comment by vector-vic** [comment]
Link to feature: https://timber.productboard.com/feature-board/planning/features/5156111

**Comment by jszwedko** [comment]
Closing this in-lieu of https://github.com/vectordotdev/vector/issues/1444 which is tracking opentelemetry support. We did add support recently for ingesting traces from the Datadog Agent thus laying the groundwork for additional trace sources.
