### ISSUE TITLE
Source logs - Heroku

### ISSUE THREAD

**Issue by vector-vic** [vectordotdev/vector#3960]
This epic deals with collecting logs from Heroku.

# User Needs

As a user, I need the...

1. ABILITY to COLLECT logs from my Heroku apps, so that I can investigate problems.

2. ABILITY to COLLECT logs from my Heroku apps, so that I can generally analyze my logs.

3. ABILITY to COLLECT logs from my Heroku apps, so that I can backup my logs for compliance reasons.

**Comment by vector-vic** [comment]
Link to feature: https://timber.productboard.com/feature-board/planning/features/5154375

**Comment by jszwedko** [comment]
Closing since this was just used for tracking.
