### ISSUE TITLE
Source logs - File source refactor

### ISSUE THREAD

**Issue by vector-vic** [vectordotdev/vector#3972]
The `file` source is one of our oldest components, and we've learned a lot since we created it. It's time we consolidate all of those learnings into a single place so that we can identify the appropriate improvement plan.

As noted in #3480, most of the `file` source issues are UX based, and much of the work here will focus on a better external API that reduces the decisions a user has to make. Once #3480 is complete we can break it down into issues and begin work.

**Comment by vector-vic** [comment]
Link to feature: https://timber.productboard.com/feature-board/planning/features/5310324

**Comment by tshepang** [comment]
is this still a todo

**Comment by jszwedko** [comment]
Hi @tshepang ! Yes, this is still something we want to do eventually.

**Comment by jszwedko** [comment]
Closing this since it was just used for tracking.
