### ISSUE TITLE
Transition to Vector - Logstash

### ISSUE THREAD

**Issue by vector-vic** [vectordotdev/vector#3979]
In order to make it easy to transition from Logstash we need to ensure to eliminate as many blockers as possible. This means achieving feature parity and offering tools that ease the burden of switching, such as configuration migration utilities and education.

**Comment by vector-vic** [comment]
Link to feature: https://timber.productboard.com/feature-board/planning/features/5156239

**Comment by jszwedko** [comment]
Closing since we don't have specific plans for this at the moment.
