### ISSUE TITLE
New `influxdb_metrics` source

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#3992]
Ability to accept Influxdb metrics as a source of data. This would be a HTTP source that would parse the [Influx line protocol](https://docs.influxdata.com/influxdb/v2.0/reference/syntax/line-protocol/) into our internal metrics.

**Comment by bfg111** [comment]
This would be incredibly useful and allow us to collect metrics/logs from one binary.

**Comment by jszwedko** [comment]
Closing this in-lieu of #11337
