### ISSUE TITLE
New `datadog_metrics` source

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#3994]
Ability to receive metrics from the Datadog agent. This helps with transitioning/decoupling from Datadog.

**Comment by zsherman** [comment]
Closing in favor of datadog agent integration issues.

**Comment by szibis** [comment]
I like that 0.13 releases datadog_logs source but if there is any timeline for datatog_metrics source ??

**Comment by zsherman** [comment]
also might be a duplicate, feel free to close @prognant

**Comment by jszwedko** [comment]
This was implemented as the `datadog_agent` source.
