### ISSUE TITLE
Source data - Command execution

### ISSUE THREAD

**Issue by vector-vic** [vectordotdev/vector#3995]
A popular method of collecting host-level data is to execute a command on an interval. Vector would ingest the output of that command as data and allow users to parse it accordingly.

# Prior Art

1. <https://github.com/influxdata/telegraf/tree/master/plugins/inputs/exec>

2. <https://github.com/christiangalsterer/execbeat>

# Open Questions

1. Vector is moving towards opinionated sources and [#3907](https://github.com/timberio/vector/issues/3907) will us to do that easily. This change moves in the opposite direction. We should think about decoupling our parsers in a way that would allow users to create a `cmd` + `parser` macro. That would be a better approach than offering complex parsing logic in a single source.

<p></p>

**Comment by vector-vic** [comment]
Link to feature: https://timber.productboard.com/feature-board/planning/features/5637299

**Comment by jszwedko** [comment]
This was implemented as the `exec` source.
