### ISSUE TITLE
Support more formats in the `http` source

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#3996]
I'm opening this issue to represent the user's need and not immediate work.

Users are asking to make the `http` source more generic:

1. Support more logs formats.
2. Support metrics and a wide variety of formats.

Our solution to this will be #3907, allowing users to couple generic sources with transforms that parse data. For example, pairing the `http` source with a `prometheus_parser` transform will allow user to solve for a matrix of user cases across. (actual implementation is TBD). Therefore, we'd like for #3907 to complete so we can demonstrate how this works.

**Comment by jszwedko** [comment]
Closing this since we added support for codecs to sources, including the `http` source.
