### ISSUE TITLE
Unify field path notation sytnax

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#4005]
Fields paths are used throughout Vector's configuration. For example, the `coercer`, `add_fields`, `remove_fields`, and `rename_fields` all accept field paths to specify which log fields to operate on. We call this the [field path notation](https://vector.dev/docs/reference/field-path-notation/). You'll notice that in addition to accessing nested fields, we also allow for specifying array indices as well as escaping the `.` character.

Unfortunately, the usage of this path is not consistent:

1. #2068 allowed the `rename_fields` transform to accept both TOML tables and strings to specify fields, but did not follow up to add the same support to other components.
2. The new remap syntax offers a new path syntax which you can see [here](https://github.com/timberio/vector/blob/master/rfcs/2020-07-21-2744-remap-syntax.md#guide-level-proposal).

We need to unify this and support only one path syntax. I find the remap syntax easier and more flexible and would like to unify around that.

## Requirements

- [ ] Drop support for TOML tables entirely when specifying fields.
- [ ] Ensure that our docs always used quoted field names.
- [ ] Use the remap path syntax for everything.

**Comment by Hoverbear** [comment]
#4066 gave us some good momentum here. When it merges you'll be able to declare `Lookup` in some `Deserializable` and get a parsed path. :)

**Comment by jszwedko** [comment]
Closing since I'm pretty sure this was done. The mentioned transforms have been removed.

cc/ @JeanMertz @fuchsnj to reopen if I'm wrong.
