### ISSUE TITLE
Consider renaming HttpSink trait

### ISSUE THREAD

**Issue by juchiast** [vectordotdev/vector#4015]
I'm working on #3777 and the naming of this trait bothered me a lot, as it is not a sink that we can send event into, but rather an encoder and request builder. 

Currently:
https://github.com/timberio/vector/blob/d54dfdc2f14c2a1f72ad2d748a77377686fc1674/src/sinks/util/http.rs#L35-L41

Here is my proposal:

``` rust
#[async_trait::async_trait]
pub trait HttpBatchEncoder: Send + Sync + 'static {
    type EncodedEvent;
    type BatchedEvents;

    /// Encode a single event.
    fn encode_event(&self, event: Event) -> Option<Self::EncodedEvent>;

    /// Build HTTP request from multiple batched events.
    async fn build_request(
        &self,
        events: Self::BatchedEvents,
    ) -> crate::Result<http::Request<Vec<u8>>>;
}
```

**Comment by juchiast** [comment]
Places like https://github.com/timberio/vector/blob/d54dfdc2f14c2a1f72ad2d748a77377686fc1674/src/sinks/util/http.rs#L82 should be changed too.

**Comment by jszwedko** [comment]
Closing as unlikely to be picked up at this point. I believe this trait is also going away as part of changes to switch to the "new style sink architecture".
