### ISSUE TITLE
Formalize how options are deprecated

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#4023]
It is inevitable that Vector will rename and reorganize configuration options, https://github.com/timberio/vector/pull/3714 is the latest example. And while these changes are simple, they break backward compatibility and negatively affect UX. In the past we've simply aliased names so that we maintain backward compatibility, but we don't do this in a way that informs the user or marks the option as explicitly deprecated. This means it's unlikely we'll ever clean up this option.

I propose that we formalize how we deprecate options. It would be nice to create a single place where we define deprecated options. This place would perform the mapping as well as long deprecation warnings for users using these options.

**Comment by jszwedko** [comment]
Closing as covered by https://github.com/vectordotdev/vector/blob/master/docs/DEPRECATION.md . Improvements coming in https://github.com/vectordotdev/vector/issues/14983
