### ISSUE TITLE
Consider using `debhelper` for .deb packages

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#4044]
I wonder if we'd want to switch to using `debhelper` for Debian packaging, instead of our custom package building script.
It might improve the reliability and correctness of the packaging process.
However we'd likely need a Debain-like system to perform the packaging, and it might complicate the process.

**Comment by MOZGIII** [comment]
:+1: This might be helpful: https://github.com/MOZGIII/rebootinto/tree/master/debian

**Comment by jszwedko** [comment]
I've also had a good experience with https://github.com/BytePackager/packagecore for building multiple distros/versions at once (it uses docker internally).

**Comment by jszwedko** [comment]
Closing since we use `cargo-deb` now.
