### ISSUE TITLE
Tutorial on https://vector.dev/guides/getting-started/deploying/ failed

### ISSUE THREAD

**Issue by mrjohnnychang** [vectordotdev/vector#4065]
The tutorial on:

https://vector.dev/guides/getting-started/deploying/

Here's what went wrong:
2 issues here

1) In step 4, the configuration for Windows include Linux-like paths
2) Cannot start Vector with the command in the tutorial:  .\bin\vector --config config\vector.toml
PS C:\Program Files\Vector> .\bin\vector --config config\vector.toml
Sep 22 19:46:19.107  INFO vector: Log level "info" is enabled.
Sep 22 19:46:19.139  INFO vector: Loading configs. path=["config\\vector.toml"]
Sep 22 19:46:19.170  INFO vector: Vector is starting. version="0.10.0" git_version="v0.9.0-377-g0f0311a" released="Wed,
22 Jul 2020 19:50:29 +0000" arch="x86_64"
Sep 22 19:46:19.217 ERROR vector::topology: Configuration error: Source "in": data_dir "/var/lib/vector" does not exist

(data_dir needs to be changed to data_dir = "C:\\Program Files\\Vector")  They are not real issues with the client itself but need additional documentation for Windows users to get them started.

**Comment by jszwedko** [comment]
Closing since this doc doesn't seem to exist anymore.
