### ISSUE TITLE
swimlanes transform: Permit `Datatype::Any` instead of `Datatype::Log`

### ISSUE THREAD

**Issue by Hoverbear** [vectordotdev/vector#4086]
Users seeking to attach components which output `Datatype::Metric` or `Datatype::Any` should be able to utilize `swimlanes` as hinted by the existence of the `type` condition: https://vector.dev/docs/reference/transforms/swimlanes/#swimlane-id

Users should be able to create swimlanes over both `type` variants, `is_log`, and `is_metric`.

```toml
lanes.`[swimlane-id]`.type = "is_log"
lanes.`[swimlane-id]`.type = "is_metric"
```

**Comment by jszwedko** [comment]
The `route` transform can accept any data type, now.
