### ISSUE TITLE
Compose sources and sinks with codecs

### ISSUE THREAD

**Issue by vector-vic** [vectordotdev/vector#4097]
This epic deals with improving how we encode and decode data across Vector. Most of the work here deals with decoupling integration and codec concerns. Please see the [architecture RFC](https://github.com/timberio/vector/blob/master/rfcs/2020-06-18-2625-architecture-revisit.md) and [composing components RFC](https://github.com/timberio/vector/blob/master/rfcs/2020-10-06-3791-composing-components-pt-1.md) for required context on codecs in Vector.

# User Needs

As a user, I need the...

1. ABILITY to decode and encode JSON data, so I can use generic sources to process JSON data.

2. ABILITY to decode and encode tokenized datata, so I can use generic sources to process tokenized data.

3. ABILITY to decode and encode logfmt/key-value data, so I can use generic sources to process logfmt/key-value data.

4. ABILITY to decode and encode syslog data, so I can use generic sources to process syslog data.

5. ABILITY to decode and encode octet framed data, so I can use generic sources to process octet framed data.

6. ABILITY to decode and encode Msgpack, so I can use generic sources to process Msgpack data.

7. ABILITY to decode and encode Influx line protocol, so I can process use generic sources to process Influx data.

8. ABILITY to decode and encode Statsd data, so I can process use generic sources to process Statsd metrics data.

9. ABILITY to decode and encode Prometheus data, so I can process use generic sources to process Statsd metrics data.

**Comment by vector-vic** [comment]
Link to feature: https://timber.productboard.com/feature-board/planning/features/5672857

**Comment by jszwedko** [comment]
Closing since sources and sinks do support codecs now (albeit not all of the ones listed above). We can let users open new issues for specific codecs they'd like (e.g. the recent `gelf` codec).
