### ISSUE TITLE
Update `journald` source requirements to recommend the deb/rpm packages

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#4119]
The `journald` requirements specify:

> The Vector user must be part of the systemd-journal group in order to execute the journalctl binary. See the "User Permissions" section for more info.

https://github.com/timberio/vector/pull/4081 handles this automatically. We should clarify this language so the user doesn't feel like they need to do anything extra when using the `deb` and `rpm` packages.

**Comment by jszwedko** [comment]
Just noting that this language doesn't appear to be on the journald source docs anymore, but it does seem good to have, in addition to the note this issue is about adding.
