### ISSUE TITLE
Document the new automatic concurrency feature

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#4121]
We need to properly document https://github.com/timberio/vector/pull/3094. This should not block that PR.

There are a few specific requirements for this:

- [ ] Update the sink-level `request` options to note the automatic concurrency.
- [ ] Add a section in the "How it works" section.
- [ ] Add this to the `/README.md` feature list.

Bonus points:

- [ ] Kick off the "Under the hood" section described in timberio/vector-website#39.
- [ ] Add a callout on the vector.dev homepage that links to the above page.

**Comment by jszwedko** [comment]
Closing since this is documented on each component.

**Comment by spencergilbert** [comment]
I disagree - I'd like to see a dedicated documentation page discussing it more fully (which could just be expanding https://vector.dev/docs/about/under-the-hood/networking/arc/)

**Comment by jszwedko** [comment]
> I disagree - I'd like to see a dedicated documentation page discussing it more fully (which could just be expanding https://vector.dev/docs/about/under-the-hood/networking/arc/)

Yeah, that's fair. I opened a new issue specifically for expanding that page: https://github.com/vectordotdev/vector/issues/13850
