### ISSUE TITLE
Clarify the `splunk_hec` indexer acknowledgement feature

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#4127]
In addition to timberio/vector#2374 we should add this to the "How It Works" section in both the `splunk_hec` source and sink.

**Comment by jszwedko** [comment]
Covered by:

https://github.com/vectordotdev/vector/blob/master/website/cue/reference/components/sources/splunk_hec.cue#L160
https://github.com/vectordotdev/vector/pull/10135/files#diff-04b175e8f755d3bf59d4ba1adea7825c872ed64c3f9d72aab8e0166ca6615defR51
