### ISSUE TITLE
Finish getting started guide series

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#4138]
As part of the new Guides section, I've created a "Getting Started" series. This takes a user from setting up Vector to deployment. Before we launch this new section, we need to update and finish each guide in the series. The previous "Getting Started" guide oversteps a little bit because it was trying to do everything all in one guide. Here are the changes we need to make:

- [x] Update the `1. Hello World` guide to simple install Vector, create a basic pipeline, and display "Hello World". The goal is to demonstrate Vector working on the user's machine as quickly as possible.
- [x] Fill in the new `2. Structuring Your  Log Data` guide with a simple `regex_parser` example. This was partyle done in the previous `Getting Started` guide.
- [ ] Fill in the new `3. Deploying Vector` guide. We should be able to use the new composable installation instructions for this. Where the user can select their platform and be presented with simple install instructions.
- [ ] Fill in the new `4. Monitoring Vector`. This guide is going to be logging only until we get observability in place.
- [ ] Fill in the new `5. Next Steps` guide. This should lead into "Advanced" guides.

**Comment by jszwedko** [comment]
Closing as stale.
