### ISSUE TITLE
Further clarity in docs about 'You SHOULD NOT use Vector for non-observability data such as analytics data.'

### ISSUE THREAD

**Issue by bradmallan** [vectordotdev/vector#4149]
RE: `You SHOULD NOT use Vector for non-observability data such as analytics data.`

I feel like Vector can tick the box of being able to orchestrate any data? I have time series data I want to shepherd from Kafka to Influx ... ... telemetry data which is analytics data in my mind.

Can anyone shed light on the statement above before I spend any cycles on trying out Vector?

**Comment by jszwedko** [comment]
Closing since this warning doesn't seem to be there anymore.
