### ISSUE TITLE
Sink data - Load-balancing & fail-over

### ISSUE THREAD

**Issue by vector-vic** [vectordotdev/vector#4156]

**Comment by vector-vic** [comment]
Link to feature: https://timber.productboard.com/feature-board/planning/features/5706375

**Comment by jszwedko** [comment]
Closing as stale since we aren't using this issue to track any epic work now.

**Comment by Sh4d1** [comment]
@jszwedko I couldn't find any issue about client side load balancing to a vector sink, is it currently not planned?

**Comment by Sh4d1** [comment]
Thanks! Pretty sure it was there, couldn't find it, my bad!
