### ISSUE TITLE
Global `enabled` sink property to enable sinks based on environment

### ISSUE THREAD

**Issue by zcapper** [vectordotdev/vector#4184]
### Current Vector Version

```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-musl 2020-07-22)
```

### Use-cases

I think it would be useful to be able to use a single config file across all my environments, but enable or disable certain sinks (and possibly even inputs or transforms) based on environment variables.

### Attempted Solutions

I've considered using templating (e.g. jinja2 with Ansible) to generate config files with some additional logic to determine what goes to where, but would rather use environment variables to determine run-time behaviour over generating config files for each environment. 

### Proposal

All sinks have a global `enabled` property which defaults to `"true"` but can be set to `"false"`, in which case the sink would be ignored in config.

E.g. 

Where `COLLECT_AUDIT_LOGS` is an environment variable equal to `"true"`:
```
[sinks.system_audit_logs]
  type          = "aws_s3"
  enabled       = "${COLLECT_AUDIT_LOGS}"
  inputs        = ["audit_logs"]
  bucket        = "audit-logs-${AWS_ACCOUNT_ID}"
  region        = "${AWS_DEFAULT_REGION}"

...
```

### References

 --

**Comment by zsherman** [comment]
@lukesteensen could use your approval on this before we dig in

**Comment by jszwedko** [comment]
Hey @zcapper !

We discussed this issue a bit more as part of a similar issue, https://github.com/vectordotdev/vector/issues/13736, and have decided we don't plan on implementing this in Vector for the reasons you see in https://github.com/vectordotdev/vector/issues/13736#issuecomment-1209822534. We welcome any additional thoughts though!
