### ISSUE TITLE
New `fluent` source

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#419]
This will make it easier for users to transition in production environments. We basically want to support the `forward` input and output for Fluentbit. I believe it's the same protocol used for FluentD, but we should investigate further.  They have [a section](https://docs.fluentbit.io/manual/output/forward#fluentd) in their docs that covers this.

- [ ] Add a Fluent transitioning guide that walks through how to do this.

**Comment by snemetz** [comment]
There are more use cases than just transition.
We use AWS fargate which can log to CloudWatch or Fluentd/Fluentbit. Replacing that with vector is not currently an option.
But I'd love to be able to have all of them send to a vector aggregator instead of a fluentd one

**Comment by binarylogic** [comment]
Thanks, @snemetz. I agree, and we'll prioritize this.

**Comment by AntonSmolkov** [comment]
Thanks @jszwedko, this is awesome!
With source I'm going to be able to forward logs from my OpenShift cluster.
(syslog is not an options for now cause it envelops logs into ruby hash)
