### ISSUE TITLE
New `logstash` source

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#420]
We need a `logstash` source that that is compatible with the [filebeat logstash output](https://www.elastic.co/guide/en/beats/filebeat/current/logstash-output.html)

**Comment by somehowchris** [comment]
This would be a big thing for us as the replacement of Logstash though Vector would improve our performance by a huge margin and would be a first step as switching out all the base images on all the apps will take a looooooooooooooong time.

**Comment by cicloid** [comment]
So, the first thing on this effort would be implementing the lumberjack protocol on Rust.

As for cert validation what are the things currently available on the current code?

**Comment by somehowchris** [comment]
If I'm not mistaken the lumberjack protocol has already been implemented in rust https://github.com/talevy/lumberjack-rs

**Comment by jszwedko** [comment]
User requested in discord: https://discord.com/channels/742820443487993987/746076283074773150/801514493938499645

**Comment by yogevyuval** [comment]
This would be pretty big, because this is the one thing that preventing many people from migrating from Logstash to Vector entirely.

**Comment by binarylogic** [comment]
Thanks, everyone. We are prioritizing this and plan to begin work in the next sprint (Feb 1).
