### ISSUE TITLE
Configure Vector - Cleanup options

### ISSUE THREAD

**Issue by vector-vic** [vectordotdev/vector#4201]
This is a simple epic that represents a variety of configuration cleanup tasks. Ensuring that our configuration options are:

<p></p>

1. Consistently named.

2. Follow naming rules.

3. Grouped into categories.

<p></p>

Will make it easier to discover options and configure Vector in general.

**Comment by vector-vic** [comment]
Link to feature: https://timber.productboard.com/feature-board/planning/features/5731233

**Comment by jszwedko** [comment]
Closing since this epic was for planning purposes, but it isn't currently planned.
