### ISSUE TITLE
Hanging of `tcp_stream_detects_disconnect` test on macOS

### ISSUE THREAD

**Issue by leebenson** [vectordotdev/vector#4208]
Sporadic test hanging via `make test` on macOS 10.15.6 (19G2021):

> test sinks::socket::test::tcp_stream_detects_disconnect ... test sinks::socket::test::tcp_stream_detects_disconnect has been running for over 60 seconds

**Comment by jszwedko** [comment]
Closing since this test hasn't shown up as flakey recently.
