### ISSUE TITLE
Add `host` key in the `http` source

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#4221]
The `http` source should add an event `host` key that represents the upstream hostname/IP.

**Comment by vsrivatsa-juspay** [comment]
Whatever happened to this issue?

**Comment by jszwedko** [comment]
> Whatever happened to this issue?

It looks like it is still a valid enhancement request.

**Comment by NishantJoshi00** [comment]
Hey @jszwedko, I was looking into this issue, I would like to take it up!
