### ISSUE TITLE
Ensure Kubernetes metrics and log data is properly correlated

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#4263]
Given that we're supporting metrics in Kubernetes by tailing Prometheus, we should ensure that Vector's log and metrics data are aligned. That means that labels, etc, should be consistent.

Before we work on this, we'll likely need an RFC discussing the current state as well as solutions.

**Comment by MOZGIII** [comment]
@binarylogic not sure what is needed here, can we discuss this issue? Might be related to #5149.

**Comment by jszwedko** [comment]
Closing since it's not clear what this issue was intending.
