### ISSUE TITLE
Decouple metrics parsers as codecs

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#4278]
Like some of our logs sources (`syslog`), our metrics sources are just ingesting data over a protocol and parsing them into our internal metrics data model. Coupling these parsers with their sources means we cannot reuse parsers with other sources as demonstrated in https://github.com/timberio/vector/pull/3984.

This, again, fits into our larger discussion of decoupling codecs from sources in a way that makes it easy to compose various combinations. And macros (#3791) would make it easy to redefine our current sources using lower-level sources. Ex: the `statsd` source could just wrap the `socket` source with a `statsd` codec.

**Comment by jszwedko** [comment]
Closing since we have the scaffolding in place for this. We can create new codecs as-needed.
