### ISSUE TITLE
Nest `docker` source label fields under `label`

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#4300]
The `docker` source adds Docker object labels to the root of the event. We should add these under a `labels` key to avoid clashing and properly structured data.

**Comment by pgassmann** [comment]
linking issue: docker source does automatic nesting of labels with namespaces where it should not. #5716

**Comment by jszwedko** [comment]
Ref: https://github.com/vectordotdev/vector/issues/12187

**Comment by jszwedko** [comment]
Closing as covered by https://github.com/vectordotdev/vector/issues/12187
