### ISSUE TITLE
Ability to drop old and future data

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#443]
Vector needs the ability to drop old and future data. This helps protect against errors that could result in a high number of downstream indexes. For example, if a date is incorrectly extracted this could result in many dates spanning many days. This would subsequently create many downstream indexes/partitions which would not be good for systems like Elasticsearch where this could affect stability.

It's not clear to me how we should implement this just yet, but a few ideas:

1. Global settings that discards data outside of a configured window regardless of the source.
2. Per source settings.
3. A transform that all sources must run through.
4. Per sink settings.

I'm leaning towards 1 to start, since this is the easiest and makes the most sense from a goal standpoint. The goal being to discard stale or data far into the future.

**Comment by jszwedko** [comment]
Closing this since it is achievable via a `remap` transform checking the timestamp against `now()` and using `abort` if it is out-of-range.
