### ISSUE TITLE
Support for Country Specific Azure Cloud Endpoints

### ISSUE THREAD

**Issue by specterz** [vectordotdev/vector#4464]
Hi Team,

- Thank you for providing Azure Monitor Sink.

- It would be nice, if an optional "endpoint" parameter can be provided, which will let user specify different Azure Clouds (e.g. Azure China Cloud, Azure US Gov Cloud).

- Currrently, the link is hardcoded in this [file](https://github.com/timberio/vector/blob/master/src/sinks/azure_monitor_logs.rs), line number 181. `"https://{}.ods.opinsights.azure.com{}?api-version={}",`

- For e.g. Azure China Cloud would use `ods.opinsights.azure.cn`. Found it [here](https://docs.azure.cn/en-us/articles/guidance/developerdifferences#check-endpoints-in-azure)

- Found this idea on [rclone page](https://rclone.org/azureblob/#azureblob-endpoint)

Thanks,
Specterz

**Comment by Hoverbear** [comment]
Here's a bit more info on Azure China: https://docs.microsoft.com/en-us/azure/china/resources-developer-guide, too.

**Comment by specterz** [comment]
I think a optional string field would fit the use case. Just in case, more dedicated cloud regions are added in future, all the user would have to do is specify the URL.

For e.g.
Commercial (Public) - [ods.opinsights.azure.com](https://docs.microsoft.com/en-us/rest/api/loganalytics/create-request#request-uri) (should be kept default)
Azure China Cloud   - [ods.opinsights.azure.cn](https://docs.microsoft.com/en-us/azure/china/resources-developer-guide#check-endpoints-in-azure)
Azure US Gov Cloud  - [ods.opinsights.azure.us](https://docs.microsoft.com/en-us/azure/azure-government/compare-azure-government-global-azure#guidance-for-developers)

If the above endpoint is specified, the healthcheck can perform DNS healthcheck against the above updated URI, instead of built in azure.com
