### ISSUE TITLE
No data on LogDNA Sinked with IBM Cloud Endpoint.

### ISSUE THREAD

**Issue by mtanniru** [vectordotdev/vector#4471]
### Vector Configuration File:
`data_dir = "/var/lib/vector"`
`# Input data. Change me to a valid input source.`
`[sources.in]`
`include = ["/jmeter/performance/*.log"] # required`
`type = "file"`

`# Output data`
`[sinks.out]`
`api_key = "ZXCVB" # required`
`hostname = "IP1" # required`
`# endpoint = "api.us-south.logging.cloud.ibm.com"`
`host = "https://api.us-south.logging.cloud.ibm.com"`
`inputs = ["in"]`
`type = "logdna"`

### Debug Output

`$ vector -v --config /etc/vector/vector.toml -r
Oct 09 14:00:54.018  INFO vector: Log level "debug" is enabled.
Oct 09 14:00:54.020  INFO vector: Loading configs. path=["/etc/vector/vector.toml"]
Oct 09 14:00:54.024  INFO vector: Vector is starting. version="0.10.0" git_version="v0.9.0-377-g0f0311a" released="Wed, 22 Jul 2020 19:45:24 +0000" arch="x86_64"
Oct 09 14:00:54.034  INFO vector::topology: Running healthchecks.
Oct 09 14:00:54.034 DEBUG http: vector::sinks::util::http: sending request. uri=https://api.us-south.logging.cloud.ibm.com//logs/ingest? method=POST
Oct 09 14:00:54.215 DEBUG http: vector::sinks::util::http: response. status=404 version=HTTP/1.1
Oct 09 14:00:54.215  INFO vector::topology::builder: Healthcheck: Passed.
Oct 09 14:00:54.215  INFO vector::topology: All healthchecks passed.
Oct 09 14:00:54.215  INFO vector::topology: Starting source "in"
Oct 09 14:00:54.215  INFO vector::topology: Starting sink "out"
Oct 09 14:00:54.215  INFO source{name=in type=file}: vector::sources::file: Starting file server. include=["/jmeter/performance/*.log"] exclude=[]
Oct 09 14:00:54.216  INFO source{name=in type=file}:file_server: file_source::file_server: Found file to watch. path="/jmeter/performance/pid.log" file_position=601
Oct 09 14:00:54.216  INFO source{name=in type=file}:file_server: file_source::file_server: Found file to watch. path="/jmeter/performance/jmeter-server.log" file_position=242379
^COct 09 14:02:17.832  INFO vector: Shutting down.
Oct 09 14:02:17.833 DEBUG source{name=in type=file}: vector::topology::builder: Finished
Oct 09 14:02:17.833 DEBUG sink{name=out type=logdna}: vector::topology::builder: Finished`

### Actual Behavior

LogDNA have no data to display.

**Comment by jszwedko** [comment]
Apologies for never triaging this @mtanniru . I'll close this since it has been stale since 2020, but please reopen if you are still interested in having this resolved.
