### ISSUE TITLE
New `parse_grok` remap function

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#4473]
The intent is to replace the `grok_parser` transform.

## Example

Given this event

```json
{
  "message": "2020-10-02T23:22:12.223222Z info Hello world"
}
```

And this remap source:

```
.grok_results = parse_grok(.message", "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:message}")
.timestamp = .grok_results.timestamp
.level = .grok_results.level
.message = .grok_results.message
del(.grok_results)
```

The following event would be produced:

```json
{
  "timestamp": "2020-10-02T23:22:12.223222Z",
  "level": "info",
  "message": "Hello world"
}
```

## Requirements

1. #4482

**Comment by bruceg** [comment]
It occurs to me that this function, as well as anything handling regex patterns (like the `split` function in #3745), if implemented naïvely, will end up parsing the pattern repeatedly on each call. As such, implementing these should be accompanied by some way of avoiding this major performance degradation.

A non-intrusive way of doing this would be a cache of the patterns used and their compiled forms. A trivial single-entry cache (ie `Option<CachedEntry>`) is probably sufficient, as it is most likely that the pattern will be constant. This is not particularly efficient (as each call would require evaluating the parameter and then comparing it to the cached pattern). Also, it would probably be wise to at least consider forbidding non-constant patterns. If the pattern comes from the event, there is opportunity for an attacker to cause mischief.

As a follow up from that, the another idea would be to explicitly identify which arguments are constant, for example with a `fn is_literal(&self) -> Option<Value>` in `trait Function`. This could be used to provide the higher functions (`parse_grok` or `split`) with a compiled pattern, either within the function or by some form of constant optimization pass in the parser itself.
