### ISSUE TITLE
Grok parser: provide an option to allow for removing empty matches

### ISSUE THREAD

**Issue by itkovian** [vectordotdev/vector#4482]
### Current Vector Version

```
vector 0.11.0 (ga6248f5 x86_64-unknown-linux-gnu 2020-10-08)
```

### Use-cases

When using the grok parser that has a `(%{A:a}|%{B:b})` somewhere in the parse tree, one of these items will end up being empty in the resulting parsed structure. This means that each grok result will have a set containing all matched and non-matched fields, which is not really usable, especially when the parser needs to produce distinct "objects" for each message type.

### Attempted Solutions

I took a look at the `remove_fields` transform but alas, that only drops empty parents after removing the provided list of fields, which is not really what is needed: `If set to true, after removing fields, remove any parent objects that are now empty.`

### Proposal

Similar to the grok parser in logstash, having a `keep_empty_captures` option that defaults to `no`, would remove all the fields that are empty after matching the line. 

### References

- #4430

**Comment by binarylogic** [comment]
@FungusHumungus assigning this to you. I'm curious if we should add this as an option to the new `parse_grok` function or chain it with a `compact` function call?
