### ISSUE TITLE
Enable TLS for `aws_*` sinks

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#4516]
We should allow for `tls.*` settings for `aws_*` sinks.

**Comment by ChinYing-Li** [comment]
Is this issue still relevant? Just found that I have a patch for this.

**Comment by jszwedko** [comment]
Hey @ChinYing-Li !

Yes it is still relevant. A patch would be great!

**Comment by jszwedko** [comment]
Closed by #10314
