### ISSUE TITLE
Feature request: proxy support for GCS Sink

### ISSUE THREAD

**Issue by chouclee** [vectordotdev/vector#4534]
### Use-cases

We are trying to use Vector to upload event records directly to GCS. For enterprise customers, we need to support non-transparent proxies which are commonly used behind corporate firewalls. 

Currently there is global proxy support feature request in Vector (#1770) and I understand that the Vector dev team has already considered this option.

### Proposal

Since it's still unclear how we can achieve global proxy in Vector, i am proposing that we probably can support proxies at GCS Sink level first and we'd like to contribute to that for our use case. 
I am not quite familiar with the rust http client that Vector is using. But if the rust http client supports proxy already, I guess it shouldn't be a hard change.

### References
#1770

**Comment by jszwedko** [comment]
Closing since HTTP proxy support has been added and is available on the GCS sink.
