### ISSUE TITLE
Vector source for uncooked Splunk data

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#4562]
For users using a [Splunk Forwarder](https://www.splunk.com/en_us/download/universal-forwarder.html) in their pipelines, it would be useful to have vector be able to ingest forwarded data via their [`tcpout` output](https://docs.splunk.com/Documentation/Splunk/8.0.6/Admin/Outputsconf#TCPOUT_SETTINGS).

Some initial investigation in https://github.com/timberio/vector/issues/4466 seems to indicate that the "cooked" format is undocumented and possibly proprietary so we'll start with just supporting uncooked (which is also Splunk's recommendation for forwarding data to external systems). The uncooked format appears to just be newline delimited text over TCP but we should verify.

We should aim to support TLS, client side certificates, and compression which Splunk's `tcpout` supports.

Additionally, we should document the Splunk configuration required to forward to vector along with common examples (like forwarding an individual index).

This could be a separate source or layered into the `socket` source. #4554 is related.

**Comment by MadsRC** [comment]
I can verify that the uncooked data is simply just newline delimited raw data send over TCP. I've used it previously to send raw logs to a Logstash endpoint. It works wonders when you don't need the metadata associated with your data.

When configuring Splunk to send "cooked" data, you're configuring it to use the proprietary S2S protocol (Splunk-to-Splunk).

**Comment by jszwedko** [comment]
Closing this since we have since verified that using `tcpout` with `sendCookedData=false` and Vector's `socket` source does indeed work.
