### ISSUE TITLE
new source: Webhooks

### ISSUE THREAD

**Issue by Hoverbear** [vectordotdev/vector#4568]
Our friends on the Honeycomb slack mentioned to us that they would like to ingest webhooks from different sources. One user in particular wanted to turn various github events into metrics.

This might be a nice integration opportunity, since a generic `webhook` source could wrap our `http` source. It could be refined as, say, a `github_webhooks` source which automatically parses according to the schema provided by Github.

More on webhooks:
* https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks
* https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads

**Comment by jszwedko** [comment]
Closing this since I'm not sure how it differs from the `http` source.
