### ISSUE TITLE
`prometheus` sink isn't sending cumulative histogram

### ISSUE THREAD

**Issue by ktff** [vectordotdev/vector#4628]
Prometheus uses [cumulative histograms](https://prometheus.io/docs/concepts/metric_types/#histogram), and while in the `prometheus` sink we are computing cumulative histogram from `distribution` metric, we aren't doing anything with already aggregated `histogram` which isn't cumulative. 

A simple fix would be to adjust already aggregated `histogram` in `prometheus` sink

**Comment by juchiast** [comment]
Look like we also need to change prometheus source to convert from cumulative histogram to normal histogram.
