### ISSUE TITLE
Add tags related macro/macros?

### ISSUE THREAD

**Issue by fanatid** [vectordotdev/vector#4651]
In https://github.com/timberio/vector/pull/4500 I add `tags!` macro, as @jszwedko [noted](https://github.com/timberio/vector/pull/4500#discussion_r507790177) there few other places where similar pattern is used. Maybe we should define tags related macro/macros in some place for usage.

**Comment by jszwedko** [comment]
Closing since this is minor tech debt that can be tracked in the code itself.
