### ISSUE TITLE
Add PodSecurityPolicy test to the Kubernetes E2E test flow

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#4654]
`PodSecurityPolicy` is a resource that provides additional constraints on how the `Pod` is allowed to behave. This extra-constrained operation mode is toggled cluster-wide, and, if on, any deployed `Pod` *has to have* a `PodSecurityPolicy` configured, describing the constraint mode - without a corresponding `PodSecurityPolicy` resource `Pod` isn't scheduled.

We offer a `PodSecurityPolicy` config out of the box, however it's not properly tested, and has a high chance of getting stale or straight out being broken.

We shall either remove the `PodSecurityPolicy`, or maintain it properly by adding an E2E suite to validate Vector operation in a `PodSecurityPolicy`-enabled cluster.

**Comment by MOZGIII** [comment]
Let's put this on hold, there's going to be a Kubernetes sig-auth meeting soon (11-11-2020) related to `PodSecurityPolicy`, and it might be deprecated. See https://groups.google.com/g/kubernetes-sig-auth/c/mSXHen2oUxo for more info.

**Comment by MOZGIII** [comment]
The meeting results were inconclusive and the discussion will continue.
VOD: https://www.youtube.com/watch?v=ybuthB0-A9I&list=PL69nYSiGNLP0VMOZ-V7-5AchXTHAQFzJw&index=1
I propose we pause this further until the fate of PSP is decided.

**Comment by binarylogic** [comment]
This is blocked given the above comments and the fact that Pod security policies are currently deprecated.

**Comment by jszwedko** [comment]
Closing since `PodSecurityPolicy` is deprecated, as noted.
