### ISSUE TITLE
Place the remap language behind a feature flag.

### ISSUE THREAD

**Issue by StephenWakely** [vectordotdev/vector#4659]
The Timber Remap Language is currently not behind a feature flag. The idea being that the language will be used fairly extensively throughout Vector, so it isn't attached to any particular source or transform.

As the language grows, it has the potential to need to pull in more dependencies. An example is #4632 which means the `syslog_loose` crate now has to always be linked, regardless of what features have been set.

As highlighted by @jszwedko [here](https://github.com/timberio/vector/pull/4632#discussion_r508552783) it would be a good idea to put the Remap functionality behind a feature flag to make the language optional and help with build times.

**Comment by JeanMertz** [comment]
Do we still consider this worthy of pursuing?

I get that there's an advantage to this, but I wonder how large that advantage remains, as VRL is being used in more places. I'm fine keeping it open, just want to make sure we still actually want to do this.

**Comment by FungusHumungus** [comment]
> Do we still consider this worthy of pursuing?

I'm treating it as low priority.

**Comment by jszwedko** [comment]
Closing this due to lack of advantage.
