### ISSUE TITLE
`internal_metrics` source can block event loop when capturing metrics

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#4691]
At the `internal_metrics` source, there's this call that is executing in the `async` context, but it may take a significant amount of time:
https://github.com/timberio/vector/blob/30f23c7c6e154543492e40b2f978d7586451fc76/src/sources/internal_metrics.rs#L65
It can, thus, block the event loop, depending on the number of metrics, for a prolonged amount of time.

At the same time, the actual overhead might not be that high, so the additional investigation is required.

**Comment by lukesteensen** [comment]
My initial hunch is that this is fine. There's nothing here that "blocks" in the sense of waiting on a syscall or socket or anything like that, just some CPU work. If we have evidence of that CPU work taking a meaningful amount of time (e.g. milliseconds? it's not totally clear what would lead to problems) then we can shift it off to a blocking thread context.

**Comment by MOZGIII** [comment]
This is just something that caught my eye in connection to the metrics cardinality issue that we tackled last week (#4582).

**Comment by jszwedko** [comment]
Closing since there doesn't seem to be evidence of this.
