### ISSUE TITLE
Add support for Prometheus remote_write source

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#4697]
Between a Prometheus `remote_read` source (#4162) and a `remote_write` sink (#2058), there exists a third possibility. Prometheus has support for connecting to a remote system and sending metrics to it through the streaming `remote_write` protocol. These metrics are a copy of those written to its database as it receives them from other sources.

Vector would take the role of the remote with this new sink that accepts connections from a Prometheus server and receive a stream of metrics using the `remote_write` protocol. This stream could of course then be transformed and forwarded on to other metrics sinks.

**Comment by spencergilbert** [comment]
This would indeed be super cool

**Comment by langecode** [comment]
This and #2058 would make is possible to use Vector-Vector as a channel for streaming Prometheus data - which would be super interesting :-)

**Comment by bruceg** [comment]
The data exposed by the `remote_write` protocol is very primitive—everything more complex than a counter or gauge is translated into multiple simple metrics. Further, there is no "header" like there is in the text protocol to indicate the original type. There is however some evidence in the translated metrics what the original would have been (for example, the presence of metrics named `X_min` and `X_max` indicate `X` is a summary distribution). Should this source be trying to parse out these structures like it does with the text format, or leave that to a downstream transform (yet to be written)?

**Comment by langecode** [comment]
Well, I know that Vector models different metric types. However, in Prometheus the storage model contains no types. This is dependent on the interpretation of the timeseries - you could call it an implicit contract between the metrics producer and Prometheus.

The overall use case we would like to be able to solve is something like:
```
app <- Prometheus -> Vector  ->  Vector -> remote write (Victoria Metrics, Cortex, ...)
```

So basically we would like to be able to tunnel each of the metric events through Vector into a remote write capable destination.
