### ISSUE TITLE
Increase benchmarking coverage for each Vector component

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#4760]
This is a meta issue to represent raising benchmarking coverage for all Vector components. The idea is to, as much as possible, standardize how we benchmark each component so that we can raise the benchmarking coverage for every Vector component. This will help us reliably compare performance across Vector versions. Each component is unique, so it'll be impossible to standardize this perfectly, but we should have guidelines that ensure basic consistent coverage.

## Requirements

- [ ] Create and agree on a list of benchmarks that increase code and real-world coverage (including changes to existing benchmarks).
- [ ] Open separate issues for each benchmark change.

**Comment by jszwedko** [comment]
After talking with Luke and Ana a bit, it seems like we are particularly interested in testing out specifically high cardinality and low cardinality events with transforms.

**Comment by jamtur01** [comment]
@jszwedko We should spin your Dec 4th comment into a sub-ticket of this and use that as a prototype/pattern for adding further benchmarks.

**Comment by jszwedko** [comment]
Closing this since we've standardized on a benchmark framework.
