### ISSUE TITLE
Support third party sources like Twitter filtered real-time stream with WASM plugin

### ISSUE THREAD

**Issue by smerchan** [vectordotdev/vector#4821]
### Current Vector Version

```
v0.10.0
```

### Use-cases

Add WASM plugin feature to allow easy addition of new third party sources and sinks.  Build a twitter source plugin for listening to a real-time filtered twitter stream. Twitter source would allow monitoring social media activity in real-time using vector.  Vector would be a great alternative to fluentd for listening to twitter streams

### Attempted Solutions

Attempted to use source type HTTP with twitter endpoint. However, adding URL as the address with a query string does not work. 
Example: 
https://stream.twitter.com/1.1/statuses/filter.json?track=twitter&follow=1234

### Proposal

Leverage [WASM Plugin](https://github.com/timberio/vector/pull/2006/files) to support a filtered real-time Twitter stream as a source. Twitter source plugin can use [twitter APIs](https://github.com/twitterdev/Twitter-API-v2-sample-code) to listen to tweets in real time. 

### References

[1] [Introduce WASM Plugins](https://github.com/timberio/vector/pull/2006/files)
[2] [Example plugin model for twitter](https://www.fluentd.org/datasources/twitter)
[3] [Reddit Discussion on WASM Plugin](https://www.reddit.com/r/rust/comments/gsbo60/wasm_plugins_support_in_vector_merged/)
[4] [Twitter APIs](https://github.com/twitterdev/Twitter-API-v2-sample-code)

**Comment by jszwedko** [comment]
Closing since we dropped wasm support #8036
