### ISSUE TITLE
TCP sink: Events lost in FramedWrite buffer

### ISSUE THREAD

**Issue by juchiast** [vectordotdev/vector#4834]
I found this issue while reviewing #4597, but it also occurs before the PR.

`FramedWrite` has a buffer of encoded events, when sending fails, all buffered events are lost. Here is a test:

```rust
    #[tokio::test]
    async fn events_lost_in_buffer() {
        use futures::StreamExt;
        trace_init();

        let listen_addr = next_addr();

        let server = tokio::spawn({
            let listen_addr = listen_addr.clone();
            async move {
                let mut server = tokio::net::TcpListener::bind(listen_addr).await.unwrap();

                let stream = server.accept().await.unwrap().0;
                stream.shutdown(std::net::Shutdown::Both).unwrap();

                let stream = server.accept().await.unwrap().0;
                let mut reader = tokio_util::codec::FramedRead::new(
                    stream,
                    tokio_util::codec::LinesCodec::new(),
                );
                for _ in 0..6 {
                    let x = reader.next().await.unwrap().unwrap();
                    println!("recv {}", x);
                }
                reader
                    .into_inner()
                    .shutdown(std::net::Shutdown::Both)
                    .unwrap();
            }
        });

        let events = (0..6)
            .map(|i| {
                let mut map = std::collections::HashMap::new();
                map.insert(
                    crate::config::log_schema().message_key().to_owned(),
                    crate::event::Value::from(i.to_string()),
                );
                crate::Event::Log(map.into())
            })
            .collect::<Vec<crate::Event>>();

        let (mut sender, receiver) = futures::channel::mpsc::channel(10);

        let config = TcpSinkConfig {
            address: listen_addr.to_string(),
            tls: None,
        };
        let encoding = crate::sinks::util::Encoding::Text.into();
        let encode = move |event| crate::sinks::util::encode_event(event, &encoding);
        let cx = SinkContext::new_test();
        let sink = config.build(cx, encode).unwrap().0;
        let sink = tokio::spawn(async move {
            sink.run(receiver.boxed()).await.unwrap();
        });

        for i in 0..3 {
            sender.try_send(events[i].clone()).unwrap();
        }
        tokio::time::delay_for(Duration::from_secs(1)).await;
        for i in 3..6 {
            sender.try_send(events[i].clone()).unwrap();
        }
        drop(sender);

        let (r1, r2) = futures::future::join(sink, server).await;
        r1.unwrap();
        r2.unwrap();
    }
```

The test simulates:
- A source that:
    - Produces 3 event.
    - Sleep for 1s.
    - Produces another 3 events.
- A server that:
    - Disconnect immediately on the first connection.
    - Read 6 events on the second connection.

Result:
```
running 1 test
recv 3
recv 4
recv 5
thread 'sinks::util::tcp::test::events_lost_in_buffer' panicked at 'called `Option::unwrap()` on a `None` value', src/sinks/util/tcp.rs:263:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'sinks::util::tcp::test::events_lost_in_buffer' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(...)', src/sinks/util/tcp.rs:309:12
test sinks::util::tcp::test::events_lost_in_buffer ... FAILED

failures:

failures:
    sinks::util::tcp::test::events_lost_in_buffer
```

**Comment by jamtur01** [comment]
@lukesteensen Thoughts?

**Comment by lukesteensen** [comment]
It's not surprising that there's a way to lose events when you're just writing out directly to TCP or something similar. With these types of sinks, there is no application-level protocol that provides acknowledgement, so we're fundamentally limited in how much we can do.

The question here is whether or not there's something reasonable we should be doing to try to make this more reliable. We have added a [check](https://github.com/timberio/vector/blob/68cdcf81deccaf0402a9fa081ee2a5482384b75f/src/sinks/util/tcp.rs#L234-L253) to identify disconnects sooner, for example. But there's no real way for us to identify which events have been received by the server, so there's no way to know which might need to be resent in the case of an error.

@juchiast do you have an idea for how the sink should handle this kind of situation? I would consider this incorrect behavior on the part of the server and outside of our control, but if you have a suggestion for how we could reasonably work around it then I'd be happy to discuss it.

**Comment by juchiast** [comment]
I agree that after writing to TCP socket, there is not much we can do.

However, in this case we did not attempt to write the data, disconnect was detected by the mentioned check, but we still loose buffered events because we don't have access to them.

`Framed` seems to provide access to the buffer (https://docs.rs/tokio-util/0.3.1/tokio_util/codec/struct.Framed.html#method.into_parts), I think it could be useful.

**Comment by lukesteensen** [comment]
> However, in this case we did not attempt to write the data, disconnect was detected by the mentioned check, but we still loose buffered events because we don't have access to them.

Whether or not we "attempted" to write the data doesn't really matter. From the perspective of the receiving application, this is no different from data that's on the network itself, in NIC buffers, or even OS buffers that the application has not yet read from. It has terminated the connection abruptly without waiting for the sender to finish, so there will almost certainly be data lost in transit. I don't think it will make a difference if we try to recover some from this one particular buffer.

> `Framed` seems to provide access to the buffer (https://docs.rs/tokio-util/0.3.1/tokio_util/codec/struct.Framed.html#method.into_parts), I think it could be useful.

This looks to be just a chunk of raw bytes, which we would not want to start sending again by itself. We would need to parse out event boundaries in order not to send a partial event, which is far more work than simply reusing the buffer. That is not something that seems feasible or worthwhile to me.

**Comment by jszwedko** [comment]
Closing this based on https://github.com/vectordotdev/vector/issues/4834#issuecomment-726474306
