### ISSUE TITLE
New `encrypt` Remap function

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#4870]
The ability to encrypt a string. Field-level encryption is desired for very sensitive information.

## Examples

```js
.message = encrypt(.message, algorithm="aes256", key=$MY_KEY)
```

I'm open to better signatures. Note that the "key" will likely need to be loaded from an environment variable?

**Comment by binarylogic** [comment]
@bruceg @JeanMertz @FungusHumungus, I'm curious if you have better proposal for how to implement this? This will be an important function for larger companies.

**Comment by JeanMertz** [comment]
I’m not sure how environment variables currently work in a Vector config. If it literally replaces all variables in the config with concrete values before parsing the config, then we don’t need to add any specific support for that in Remap itself.

If we do, then my first though would be to introduce a separate `env_var(“KEY”)` function to support this case.

Other than that, I don’t see anything inherently wrong with this proposal. Although one issue I could see is that different algorithms might require different number of parameters, which might get complicated if we want to keep it all in the same `encrypt` function.

**Comment by binarylogic** [comment]
Yeah, I'm open to an AES specific function. Following Rust's precendence should be pretty safe.

**Comment by bruceg** [comment]
I don't see anything inherently wrong with the proposal as such. We do need some way to fetch environment variables, which is out of scope for this change. I would also argue for more secure storage of the secret keys, as environment variables can be scraped from `/proc` for anyone with sufficient read privileges, but again that's out of scope for just encryption.

We will need more sophisticated algorithm indicators, though. There are three main parts to the algorithm (ignoring authentication codes):

- What encryption base algorithm (ie AES, ChaCha)
- Key size (ie 256 bits)
- Operating mode (ex CBC, XTS, GCM, etc)

So, something more like `"aes-256-ctr"` for the algorithm.

Additionally, the key text can't be used directly for the encryption algorithm, it needs to be hashed to turn it into a binary key, which will of course have a choice of algorithm itself with possible parameters.

As @JeanMertz indicates, some operating modes require additional parameters (any AEAD like GCM requires a nonce, would have to be stored along side the encrypted text) but I think we can mostly ignore that for this use case as we are unlikely to want message authentication.

**Comment by alexey-gusarov** [comment]
Hello
Do you have any news about this issue?
The inability to encrypt stops me from using Vector.dev in our enterprise.

**Comment by JeanMertz** [comment]
We do _not yet_ have support for encrypting data through VRL, but it's on our radar, and I suspect it'll land sometime in the next three months.

We do have `get_env_var` (#6017), which was partly blocking this work.

**Comment by zadunn** [comment]
It would be nice to see the key here support multiple keys.  The rough use case would be to encrypt log values on a per customer base vs using a single master key for all values.

**Comment by JeanMertz** [comment]
> It would be nice to see the key here support multiple keys. The rough use case would be to encrypt log values on a per customer base vs using a single master key for all values.

I think this use-case would be best covered using [iteration](https://github.com/vectordotdev/vector/blob/6b46b08435639bdce6786ce09fa9237d3b89e75e/rfcs/2021-08-29-8381-vrl-iteration-support.md) (which is something we plan to ship this quarter).
