### ISSUE TITLE
`vector` source/sink application level message acknowledgement

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#492]
We should consider application level message acknowledgement with the `vector` source and sink. This ensures data is not dropped. Logstash, for example, has created the [lumberjack protocol](https://github.com/elastic/logstash-forwarder/blob/master/PROTOCOL.md) for this purpose. It might make sense to adopt that protocol since we'll need it for https://github.com/timberio/vector/issues/420.

A couple of questions:

* What kind of performance impact will this have?
* Where do we draw the line on durability before recommending a system designed for this purpose (ex: kinesis / kafka)?

**Comment by anton-ryzhov** [comment]
In current implementation vector protocol definitely loses logs at least because sender can't detect [even graceful] shutdown of receiver and sends some logs to closed socket.

**Comment by spencergilbert** [comment]
@jszwedko I believe this can be closed now 😄

**Comment by jszwedko** [comment]
Oh yes. This was implemented as part of the v2 of the Vector protocol which is gRPC.
