### ISSUE TITLE
Autodiscovery source

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#4920]
I was thinking about the autodiscovery source from the perspective of our internal architecture, and this is what I came up with.

We can add an autodiscovery source.

The way it would work is:
1. User adds `autodiscovery` source to the topology with the desired config (more on this later).
2. Vector performs autodiscovery and adds the relevant sources to the topology implicitly, properly configured out of the box. Sources deliver data to the transforms and sinks connected to the `autodiscovery` source.
3. Vector periodically performs rediscovery and updates the topology accordingly.

### The autodiscovery algorithm & code changes

The only sane way I found to implement the autodiscovery logic is through a custom linear algorithm.

Why not simply implement an `Autodicoverable` trait and poll each source implementing it in a loop? This is because there are cases where the same data can be discovered by multiple sources, and we need to intelligently pick the more preferred sources, and exclude the data from the less preferred sources - as an example of this, there's a `kubernetes_logs` source, `docker` source and a `file` source - with the linear hand-crafted algorithm it would be very easy to implement the logic of configuring the sources together properly, however it's going to very difficult with a trait-local implementation for each.

Does this mean we have to implement everything in some central location? No, only the core decision-making logic has to be linear and in a single place, the mechanisms and helpers to query each source for possible autodiscovery items can and should be implemented in each source individually. Only the core logic of driving all this together and properly configuring/including/excluding sources should be linear. With this approach, we don't even need to generalize the autodiscovery interface for each source - there seems no use for trait-objects or generics, we can quite fine do with direct calls to the relevant sources. In some particular cases though, generalization might make sense if the linear logic demands it.

### Configuration

With Vector being as advanced as it is, users will need a way to configure the autodiscovery mechanism to make it do what they want.

Some configuration values that I figured will be important are:

- `event_types`: `any`/`logs_only`/`metrics_only`

   This is useful for users to finer control what types of events to discover. In case they want to build the downstream topology around just logs or just metrics.

- `locality`: `any`/`local_only`/`global_only`

   Not 100% sure on this, but it might be useful depending on the deployment role of Vector. The idea is we can run Vector as an agent to collect local data from the system it's running at, and we can also run it as an aggregator - possibly on the same node that Vector as an agent runs - and then it's job would be not to collect the data from the node - but rather collect it from the remote data-sources - for instance other Vectors running as agents, or Prometheus server (that aggregates all the metrics through its own autodiscovery already).

- other algorithms specific tweaks, like `deny_docker`: `true`/`false` to opt-out from a particular source being used (or to opt-in into something that can't be on by default)

---

This definitely needs further discussion, quite possibly a whole RFC if we choose to go with it.

I hope you like it :smile:

**Comment by jszwedko** [comment]
Closing this since we don't plan to add autodiscovery to Vector.
