### ISSUE TITLE
The `sampler` transform should take a configurable `field` to apply the pass list against

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#497]
Currently the `pass_list` option in the `sampler` transform only applies to the `message` key. This should be configurable via a `field` option, similar to what we have in the `json_parser`, `regex_parser`, `grok_parser`, and so on.

**Comment by ayshiff** [comment]
@binarylogic Can I work on this?

**Comment by binarylogic** [comment]
@ayshiff go for it, we'd appreciate it.

**Comment by ayshiff** [comment]
@binarylogic Correct me if I'm wrong but I think the transform sampler already has an option to set the key with the `key_field`option.

**Comment by ayshiff** [comment]
Correct me if I'm wrong but I think the `key_field` option of the `sampler` transform already does what we need.   
Knowing that this issue is a bit old and the `pass_list` option is not there anymore I wanted to have your opinion.

**Comment by jszwedko** [comment]
I noted in https://github.com/timberio/vector/pull/6843#issuecomment-804153379 that I think this issue is already solved via the addition of exclude in 58d6e8f.

**Comment by ayshiff** [comment]
> I noted in [#6843 (comment)](https://github.com/timberio/vector/pull/6843#issuecomment-804153379) that I think this issue is already solved via the addition of exclude in [58d6e8f](https://github.com/timberio/vector/commit/58d6e8ffa9f1fe7f5fdf31359435c8bc9f9e26c2).

@jszwedko Sorry, I should have realized it before.
I'll close my PR 👍

**Comment by jszwedko** [comment]
No worries! We should have closed this issue earlier. I appreciate you taking a look.
