### ISSUE TITLE
Flakey OSX test: config::watcher::tests::file_update

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#5000]
```
test config::watcher::tests::file_update ... Nov 11 22:12:12.133  INFO vector::config::watcher: Creating configuration file watcher.
Nov 11 22:12:12.136  INFO vector::config::watcher: Watching configuration files.
thread 'main' panicked at 'Test timed out', src/config/watcher.rs:150:13
```

Observed: https://github.com/timberio/vector/runs/1387418580#step:8:738

**Comment by MOZGIII** [comment]
Happy 5000 get

**Comment by ktff** [comment]
It failed again https://github.com/timberio/vector/runs/1387418580#step:8:738. 
It seams #5866 didn't help.

At this point I don't think the test is wrong, and that it is actually showing that we are missing some file notifications on OSX from time to time.

**Comment by jszwedko** [comment]
Closing to let flakey tests bubble back up.
