### ISSUE TITLE
Update the `reduce` transform to take `break.*` options

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#5068]
To safeguard against user error we should add a new `break` options to the `reduce` transform:

- [ ] `break.time_limit_ms` (default: `30000`) is a rename of `expire_after_ms`.
- [ ] `break.event_limit` (default: `1000`) is a new option that will abort if this quantity is exceeded.
- [ ] `break.action` (default: `abort`, `flush`) is a new option that controls what the transform does when either limit is hit.
  - If this is set to `abort` then the accumulated event will be aborted and flushed as individual events.
  - If this is set to `flush` then the accumulated event will be flushed as one event.

Open to better naming.

**Comment by binarylogic** [comment]
cc @lukesteensen for review/approval.

**Comment by lukesteensen** [comment]
> If this is set to `abort` then the accumulated event will be aborted and flushed as individual events.

This is not so simple. We don't current keep all of the individual events around as we build up the output, just the state that's relevant to the eventual output. I don't think I'd recommend us undoing that, which means our options are really just to flush as-is or drop the data.

> we should add a new `break` options

Less of a big deal, but I don't love this name. I get the urge to put these under a common section, but I'd probably just leave `expire_after_ms` and add a top-level `event_limit`. For `action`, I think we need to figure out the above issue before making a decision.

**Comment by jamtur01** [comment]
@JeanMertz Thoughts?

**Comment by JeanMertz** [comment]
Other than what @lukesteensen already mentioned (and which I verified, just to get a better understanding of the current implementation), I would say for performance reasons we wouldn't want to change the current strategy of only storing the relevant state.

However, if we really think an `abort` option is useful, we can introduce a second strategy that _does_ keep the individual events around to be able to flush them as individual events when needed.

However, this obviously has a (potentially large) performance penalty, and it would make this transform less predictable (its performance varies greatly depending on the `break.action` strategy).

It's also, as Luke said, not so simple as the other proposals in this issue (renaming fields, and adding an event limit).

If we forgo adding a `break.action` option, then I don't think the case for merging the other two fields under a `break` section is as strong (and I also agree that the naming could use some work).

In that case, I'd vote to leave `expire_after_ms`, but maybe for consistency add `expire_after_event_count`, although I do believe `event_limit` catches the purpose of that field very well.

**Comment by binarylogic** [comment]
I'm 👍 on Luke's proposal.

**Comment by JeanMertz** [comment]
Note that `event_limit` was recently requested in #14498, and is planned to be added in the near future.

I'm closing this issue, as it seems the scope was reduced to _only_ that feature in the end, feel free to re-open if that's not the case.
