### ISSUE TITLE
Document Vector's internal events and place them under `components.*.*.telemetry.events`

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#5131]
In addition to documenting which metrics each component exposes, we should document which events are fired. Since events trigger metrics, there is a case to be made that components should only document their events. Which metrics and logs a component emits could be derived from these events. For example, the [`SocketEventReceived` event emits a `events_processed_total` metrics](https://github.com/timberio/vector/blob/69d50d2748404e230db9b20240180997b49d347d/src/internal_events/socket.rs#L33). That could be represented like:

```jscomponents: sources: socket: telemetry: events: {
 	SocketEventReceived: {
		description: "Fires when an event is received over the configured socket."
		log: {
			message: {
				description: "The message of the log"
				type: string: default: "Received one event"
			}
		 	byte_size: {
				description: "The size of the event in bytes."
				type: unit: {}
			}
			mode: {
				description: "The configured socket mode."
				type: configuration.mode.type
			}
		}
		metrics: {
			events_processed_total: {
				// ...
			}
		}
	}
}
```

Then, in `components.cue` we could do something like this is we wanted a list of metrics:

```js
// ...

telemetry: {
	events: #Events	
	metrics: {
		for event_name, event in events {
			for metric_name, metric, in event.metrics {
				"\(metric_name)": metrics
			}
		}
	}
}

// ...
```

**Comment by binarylogic** [comment]
Since errors are just events, this will likely overlap with https://github.com/timberio/vector/issues/978.

**Comment by jszwedko** [comment]
Closing this since we haven't had users ask for it, that I'm aware of. Please leave a comment if this would be useful to you.
