### ISSUE TITLE
Collect metrics from Prometheus server into Vector in Kubernetes

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#5149]
We want to gather metrics from Prometheus server to be able to process them in Vector, however we ned to think about how not to generate a feedback loop with Prometheus gathering metrics from Vector, then Vector gathering metrics from Prometheus, and vice versa.

Related to  #3229.

**Comment by jszwedko** [comment]
I think this issue is lacking detail. It seems like it should be possible to configure Vector to scrape a prometheus endpoint without creating a feedback loop.
