### ISSUE TITLE
Integration tests for S3 partitioning

### ISSUE THREAD

**Issue by lukesteensen** [vectordotdev/vector#516]
The partitioned batch sink itself is tested, but we don't have anything automated that ensures the S3 sink is using it properly, that the key/folder/filename logic is doing what we want, etc. We should backfill some good tests around this functionality so that we can more confidently refactor the batching stuff and be sure the sink is still behaving the same way.

**Comment by jszwedko** [comment]
We have integration tests for the AWS S3 sink now.
