### ISSUE TITLE
Delete github pages environment

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#5169]
We have a lingering Github pages environment on our repo:

https://share.getcloudapp.com/bLu06jYv

Unfortunately, Github does not provide a way to delete these except through their API. This script is required:

https://github.com/VishalRamesh50/Github-Environment-Cleaner

**Before running this script we should audit it to ensure it does what it says and only what it says.**

**Comment by jszwedko** [comment]
I was able to delete this via the UI now.
