### ISSUE TITLE
Ensure `"-"` values are dropped in the `tokenizer` transform

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#523]
It's common in log lines to insert a `-` value to represent blank values:

```
127.0.0.1 - frank [10/Oct/2000:13:55:36 -0700] "GET /apache_pb.gif HTTP/1.0" 200 2326 
```

The `tokenizer` transform should discard these values.

**Comment by binarylogic** [comment]
@lukesteensen what is the consensus on this issue? I'd like to close it if we're not doing anything about this.

**Comment by lukesteensen** [comment]
Personally, I don't think it's worth spending further time on it. It doesn't seem like anyone has asked for it and the existing behavior is not surprising imo.

**Comment by binarylogic** [comment]
Sounds good.
