### ISSUE TITLE
The `blackhole` sink has regressed in peformance

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#5236]
The `blackhole` sink (not used in production) appears to have regressed in performance:

```
                                   __   __  __
                                   \ \ / / / /
                                    \ V / / /
                                     \_/  \/

                                   V E C T O R

--------------------------------------------------------------------------------
Test Comparison
Test name: tcp_to_blackhole_performance
Test configuration: default
Subject: vector
Versions: 0.10.0 nightly/2020-11-25
--------------------------------------------------------------------------------
Metric          | 0.10.0             | nightly/2020-11-25
----------------|--------------------|-------------------
Test count      | 1                  | 1                 
Duration (avg)  | 63s                | 64s               
Duration (max)  | 63s                | 64s               
CPU sys (max)   | 5.1 (+12%)         | 4.5 W             
CPU usr (max)   | 84.4 W             | 84.9 (+0%)        
Load 1m (avg)   | 1.1 (+38%)         | 0.8 W             
Mem used (max)  | 213.1 MiB W        | 221.1 MiB (+3%)   
Disk read (avg) | 580.2 kib/s (-13%) | 668.3 kib/s W     
Disk read (sum) | 35.7 MiB W         | 41.8 MiB (+17%)   
Disk writ (sum) | 17.6 MiB (+45%)    | 12.1 MiB W        
Net recv (avg)  | 28.5 MiB/s W       | 15.3 MiB/s (-46%) 
Net recv (sum)  | 1.8 gib W          | 976.9 MiB (-45%)  
Net send (sum)  | 7.3 MiB            | 3.9 MiB           
TCP estab (avg) | 663                | 671               
TCP syn (avg)   | 3                  | 4                 
TCP close (avg) | 0                  | 0                 
--------------------------------------------------------------------------------
W = winner
vector = 0.10.0
vector = nightly/2020-11-25
```

The primary purpose of this sink is for performance benchmarking and catching performance regressions. Slowing it down throws off baseline performance tracking against historical Vector versions.

I know we recently added the ability to count bytes for reporting purposes, but that deviates from its primary purpose. I'd recommend that we either put the bytes counting behind a feature flag or identify a different method for tracking outgoing bytes.

cc @lucperkins @jszwedko

**Comment by jszwedko** [comment]
@binarylogic We think the primary regression for this is actually the tracing changes per https://discord.com/channels/742820443487993987/751109034827972709/781322443448778792 (examining the difference between the 9/25 and 9/30 nightlies).

Counting bytes by JSON serialization probably slowed it down a little, but I think it is useful to have all sinks report that metric (`bytes_processed_total`) for consistency. I think we can count the bytes more efficiently though.

**Comment by jszwedko** [comment]
Closing since this is stale enough that the current performance can be the new baseline.
