### ISSUE TITLE
Tutorial on https://vector.dev/guides/integrate/sources/syslog/kafka/#what-is-kafka failed

### ISSUE THREAD

**Issue by grahamnicholls** [vectordotdev/vector#5242]
The tutorial on:

https://vector.dev/guides/integrate/sources/syslog/kafka/#what-is-kafka

Here's what went wrong:

# bin/vector -c config/vector.toml 
Nov 26 04:25:46.216  INFO vector: Log level "info" is enabled.
Nov 26 04:25:46.218  INFO vector: Loading configs. path=["config/vector.toml"]
Nov 26 04:25:46.222 ERROR vector: Configuration error: "config/vector.toml": missing field `encoding` for key `sinks.out`

**Comment by jszwedko** [comment]
Closing since this guide doesn't exist anymore.
