### ISSUE TITLE
remap-lang: support querying the type of value

### ISSUE THREAD

**Issue by JeanMertz** [vectordotdev/vector#5261]
I think a fairly common pattern will be to check the type of a value, and act on it accordingly.

For example:

```jsonl
{ "error": 23 }
{ "error": "woops" }
```

```rust
if /* .error is an integer */ {
	.error_code = .error
} else if /* error is a string */ {
	.error_message = .error
}
```

This is a fairly trivial example, but there are many more you can come up with.

I would propose the most simple solution to this problem: introduce individual `is_*` functions for each value variant:

* `is_string` -> `Value::Bytes`
* `is_int` -> `Value::Integer`
* `is_float` -> `Value::Float`
* `is_bool` -> `Value::Boolean`
* `is_map` -> `Value::Map`
* `is_array` -> `Value::Array`
* `is_timestamp` -> `Value::Timestamp`
* `is_null` -> `Value::Null`

These would have the signature:

```rust
fn is_*(value = Expression) -> bool
```

We have existing precedents for this, with the `to_*` functions.

cc @binarylogic @FungusHumungus

**Comment by binarylogic** [comment]
@JeanMertz how about a `type` function as well?

```js
type(.key)
=> 'string'
```

**Comment by JeanMertz** [comment]
@binarylogic that could be added as well, although I fail to think of a use for it that can't be solved with the `is_*` variants.

The benefit of using a function that returns a boolean, is that we can (eventually, still thinking through this) have those functions set invariants in the compiler, such that any expression that occurs inside `if is_bool(.foo) { ... }` is known to receive a bool for `.foo`, and thus reduce the number of fallible expressions.

We can't (we can, but it would be hacky) do the same for `if type(.foo) == 'bool' { ... }`.

Also, typing the above, it seems more error-prone (I typed `== 'boolean'` before changing it to `== 'bool'`).

But maybe you have a use-case in mind? We can definitely add it if we think it'll help certain use-cases 👍

**Comment by JeanMertz** [comment]
> The benefit of using a function that returns a boolean, is that we can (eventually, still thinking through this) have those functions set invariants in the compiler, such that any expression that occurs inside `if is_bool(.foo) { ... }` is known to receive a bool for `.foo`, and thus reduce the number of fallible expressions.

I've thought some more about this.

Currently, an expression implements `type_def`, which tells the compiler about the definition of the type the expression returns.

For this feature to work, we'd have to add new capabilities to expressions, something like:

```rust
trait Expression {
	fn positive_type_defs(&self, state: &state::Compiler) -> Vec<(Target, TypeDef)> {
		vec![]
	}
}
```

What this function tells the compiler is:

> _If_ I return a boolean value `true` at runtime, _then_ I guarantee you that the following targets will have these type definitions.

The compiler can then use this information in any location where the boolean result of a function can impact the control-flow of the program. To start, this would work for if statements:

```rust
if is_bool(.foo) {
	// .foo known to be a boolean
}
```

Using this initial design, this feature remains fairly limited in scope. This is by-design, however. We could for example also choose to allow functions mutable access to the compiler state, so that they can do whatever they want by modifying the existing state, but I don't consider this good practice, as it makes the integrity of the language (e.g. the type state) dependent on the correct implementation of functions.

Of course, that last statement is already partially true, since a function can communicate the wrong information, but it doesn't allow functions to modify information that's irrelevant to their operation, which I believe is a characteristic we should maintain.

Other areas, such as equality checking expressions would bubble up this information, e.g.:

```rust
if is_bool(.foo) { /* .foo known to be bool */ }
if is_bool(.foo) == true { /* .foo known to be bool */ }
if is_bool(.foo) == false {/* .foo known not to be bool */ }
if !is_bool(.foo) {/* .foo known not to be bool */ }
```

Also, as the trait signature shows, this method defaults to now relaying any positive type definitions, so it doesn't break any existing functions.

**Comment by binarylogic** [comment]
@JeanMertz is this still relevant given the latest changes?

**Comment by FungusHumungus** [comment]
I would say so. It's probably not critical as this alternative is possible:

```
if (object(.parsed) ?? null) != null { 
    # .parsed is an object here
  }
```

But a dedicated  `is_object` would still be more succinct.

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/6775
