### ISSUE TITLE
Support templates in splunk_hec sink index configuration

### ISSUE THREAD

**Issue by benzaita** [vectordotdev/vector#5313]
### Current Vector Version

```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-musl 2020-07-22)
```

### Use-cases

Collecting logs for multiple indexes using Vector and shipping them to Splunk.

We have multiple services writing logs to different indexes. Currently they write directly to Splunk, and we would like to first collect the logs using Vector, and then forward them to Splunk.

### Attempted Solutions

I've tried using this option in the `splunk_hec` sink:

```toml
  index = "{{ splunk_index }}"
```

But it does not seem to work. I can't see the entire payload, but it seems to be sending it to the `{{ splunk_index }}` index (verbatim) instead of interpolating it. Furthermore, looking at [the code of the splunk_hec sink](https://github.com/timberio/vector/blob/v0.10.0/src/sinks/splunk_hec.rs#L163) it seems to not use `Template` for this option.

### Proposal

To interpolate this configuration option using a `Template`, like the `source` option.

### References

N/A

**Comment by fanatid** [comment]
Closed with #5418.
