### ISSUE TITLE
request: gcp_pubsub source

### ISSUE THREAD

**Issue by joemiller** [vectordotdev/vector#5343]
A pubsub sink is available but not a Pubsub source. A source would be useful because GCP already has a lot (all?) of its services sending data to the GCP Logging API and it is trivial to setup a pubsub export for all or some of these logs. Vector could be used to read from pubsub, do any filtering or transforms, and then send data to your own storage/indexing system or another provider such as logz.io, humio, etc.

A GCP pubsub source would be the GCP equivalent of the existing AWS kinesis source in Vector.

**Comment by thalin** [comment]
This would be a great help when trying to grab logs out of Google projects! Google Logs Router can send logs to Google Cloud Storage, BigQuery, Google Cloud Logs buckets, or PubSub. PubSub seems like it will be the best bet.

**Comment by nlamirault** [comment]
This would replace Promtail which can retrieve logs in GCP PubSub

**Comment by spencergilbert** [comment]
Note that we should be able to do this with the vector-aggregator chart (beta)

**Comment by binarylogic** [comment]
Thank you everyone. We are scheduling this work for this quarter. I'm closing this issue in favor of #753 since its a duplicate. Feel free to follow that one.
