### ISSUE TITLE
Add support to remap for flattening and unflattening maps

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#5378]
Vector is used to handle where sources emit data with a flattened data structure, such that the structure is expressed as a flat map with dotted keys for example, and sends to sinks that want structured data with such keys broken down into separate maps. The reverse is also needed.

Example data:
```json
{
  "a": "Hello",
  "b": {
    "c": "friends",
    "d": "and family"
  }
}
```
converts to or from:
```json
{
  "a": "Hello",
  "b.c": "friends",
  "b.d": "and family"
}
```

It would probably be useful to include parameters for selection of the separators and similar to allow it to cover the most use cases, defaulting to the most common convention above.

**Comment by FungusHumungus** [comment]
We already have `flatten` which will work on both Arrays and on Map. It currently only uses `.` as a separator for Map though.

Unflatten would still need to be coded.
