### ISSUE TITLE
Improve error type handling

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#543]
Many of Vector's methods use a `Result<_, String>` return type. This is adequate for textual errors, but it makes it impossible for users to pattern match on the error type as well as dropping any cause information encapsulated by some error types. We should switch to proper error types (similar to `std::io::Error`) probably aided by the `failure` crate.

References:
 * https://www.reddit.com/r/rust/comments/8lt8k6/do_i_really_need_failureerrorchain/dzj9kmz
 * https://boats.gitlab.io/failure/

**Comment by bruceg** [comment]
So now, one error return has been converted to an actual error type. Where should this issue go from here?

**Comment by lukesteensen** [comment]
I would say we should take a quick inventory of components still using `String` errors and either add a checklist to this issue or break them out into individual issues so we can track overall progress (probably just a checklist here).

**Comment by bruceg** [comment]
A quick grep shows at least the following modules:

- [ ] src/buffers/disk.rs
- [ ] src/region.rs
- [ ] src/sinks/aws_cloudwatch_logs/mod.rs
- [ ] src/sinks/aws_cloudwatch_metrics.rs
- [ ] src/sinks/aws_kinesis_streams.rs
- [ ] src/sinks/aws_s3.rs
- [ ] src/sinks/blackhole.rs
- [ ] src/sinks/clickhouse.rs
- [ ] src/sinks/console.rs
- [ ] src/sinks/elasticsearch.rs
- [ ] src/sinks/http.rs
- [ ] src/sinks/kafka.rs
- [ ] src/sinks/prometheus.rs
- [ ] src/sinks/splunk_hec.rs
- [ ] src/sinks/tcp.rs
- [ ] src/sinks/util/http.rs
- [ ] src/sinks/vector.rs
- [ ] src/sources/file.rs
- [ ] src/sources/statsd/mod.rs
- [ ] src/sources/statsd/parser.rs
- [ ] src/sources/stdin.rs
- [ ] src/sources/syslog.rs
- [ ] src/sources/tcp.rs
- [ ] src/sources/udp.rs
- [ ] src/sources/util/tcp.rs
- [ ] src/sources/vector.rs
- [ ] src/topology/config/mod.rs
- [ ] src/transforms/add_fields.rs
- [ ] src/transforms/coercer.rs
- [ ] src/transforms/field_filter.rs
- [ ] src/transforms/grok_parser.rs
- [ ] src/transforms/json_parser.rs
- [ ] src/transforms/log_to_metric.rs
- [ ] src/transforms/lua.rs
- [ ] src/transforms/regex_parser.rs
- [ ] src/transforms/remove_fields.rs
- [ ] src/transforms/sampler.rs
- [ ] src/transforms/tokenizer.rs
- [ ] tests/crash.rs

**Comment by LucioFranco** [comment]
@bruceg one commit per sink/source/transform works and then bunch them into their own PR.

**Comment by bruceg** [comment]
I've done all the (for example) transforms as one commit. Are you saying you would rather break them into separate commits per file (which won't actually compile until the last commit) or am I misunderstanding?

**Comment by LucioFranco** [comment]
@bruceg honestly, whatever is easier for you, I'm happy to review it either way.

**Comment by lukesteensen** [comment]
Yeah, please feel free to break it up however is easiest for you.

**Comment by bruceg** [comment]
AFAICT there is one last module that uses `String` error types, and that is the configuration parsing framework.

**Comment by lukesteensen** [comment]
Do you mean just [here](https://github.com/timberio/vector/blob/ec73082da655d5e17c7023fef3b5c1893a4d7bf4/src/main.rs#L71)? That one is so small and isolated I don't think it's worth the effort to do anything fancier.

**Comment by bruceg** [comment]
No, I mean the whole stack starting (roughly) [here](https://github.com/timberio/vector/blob/ec73082da655d5e17c7023fef3b5c1893a4d7bf4/src/topology/config/mod.rs#L198). There are a lot of routines that return `Result<..., Vec<String>>` that I didn't catch before.

**Comment by lukesteensen** [comment]
I see, those evaded my grep as well. I wouldn't say they're high priority, and they might be a little different since we're collecting multiple errors. I'd say we can take a quick stab at them, but be ready to punt if it becomes much of a burden. There's some value to be had there, but not a ton.

**Comment by LucioFranco** [comment]
We can also change the signature to `Result<..., Vec<crate::Error>>`.

**Comment by binarylogic** [comment]
@bruceg just checking in on this. Do you mind letting us know what's left? So we can document it here. If nothing is left, feel free to close.

**Comment by bruceg** [comment]
The whole configuration parsing stack still uses `String` error returns, mostly wrapped into `Vec<String>`. I have started working on this but pushed it aside to work on higher priority issues (TLS mostly). It was turning out to be less of a straightforward conversion that the sinks and sources were.

**Comment by JeanMertz** [comment]
@lukesteensen @bruceg would it make sense to introduce a custom `ConfigError(Vec<Box<dyn Error>>)` struct which impl's `Error` and `Display` and allows pushing more errors onto its list?

That way, we can still have all config-related functions return the default boxed error trait object, but we can either a) downcast at the leaf to capture all individual errors, or b) have the `Display` impl print the individual errors however we want them to be represented.

**Comment by bruceg** [comment]
I think the preferred path would be to introduce a `enum ConfigError` or equivalent and turn all those returns into `Result<…, Vec<ConfigError>>`. At some layer, they may have to be boxed, but at the point they are emitted they can be enumerated and structured. Wrapping the error vector in a newtype as you describe would be a useful additional abstraction, but since they are all config errors, they can stay enumerated there.

**Comment by jszwedko** [comment]
@lukesteensen @bruceg is this still relevant? I think we do use `Box<dyn std::error::Error + Send + Sync + 'static>` in most places now?

**Comment by lukesteensen** [comment]
I'm not sure that it's very high priority, but there is definitely still work that we could do to improve our error handling story. This initial pass at this used `snafu`, but there have been quite a few uses of `anyhow`/`thiserror` that have crept into the codebase over time, as well as a few areas where I think we're still using `String` as our error type. There are also some newer crates like [`color-eyre`](https://docs.rs/color-eyre/latest/color_eyre/) that have some nice integrations with `tracing` spans that could be useful for us. Overall, I think it would definitely be of some value to review what we're doing and choose one consistent pattern.

**Comment by jszwedko** [comment]
Closing this since we wouldn't pick it up for its own sake but only if we needed to better handle errors for some other reason.
