### ISSUE TITLE
Add doc comments throughout the codebase

### ISSUE THREAD

**Issue by LucioFranco** [vectordotdev/vector#545]

**Comment by MOZGIII** [comment]
I've been reading the codebase, and I can definitely vote for adding more comments. Normally I'd expect to see a lot more notes on the design left through comments, and I think adding that would significantly improve the code quality.

**Comment by jszwedko** [comment]
It seems unlikely that we are going to do a pass just for this so I'll close it out. I think we are doing better with this, but would encourage us to do it more as we go along with new changes rather than doing a sweep.
