### ISSUE TITLE
Prometheus sink docs are rendering incorrectly

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#5455]
https://vector.dev/docs/reference/sinks/prometheus_exporter/#help-service_logins-logins
![image](https://user-images.githubusercontent.com/265507/101643367-1e462500-3a45-11eb-9af2-e41a5fa59773.png)

**Comment by bruceg** [comment]
It appears the `#` in the sample output is being interpreted by the docs generator as a markdown top-level header marker.

**Comment by jszwedko** [comment]
This appears to be rendering correctly now.
