### ISSUE TITLE
Enhanced sampling RFC

### ISSUE THREAD

**Issue by lucperkins** [vectordotdev/vector#5457]
The current `sampler` transform supports [constant sampling](https://docs.honeycomb.io/working-with-your-data/best-practices/sampling/#constant-sampling) by specifying `rate` and allows for some limited "bucketing" by specifying a `key_field` (where each discrete value for that field is a new abstract "bucket" for events).

In a new RFC, we should discuss ways of enhancing the `sampler` transform to support:

1. Bucketing based on arbitrarily complex criteria, with Remap expressions as the vehicle
1. More robust key-based sampling by allowing for multiple keys
1. Dynamic sampling for buckets, i.e. adjusting the sample rate in accordance with traffic patterns

**Comment by jszwedko** [comment]
Closing due to lack of a use-case. Happy to reopen if someone has one.
