### ISSUE TITLE
Layered / waterfall / overflow buffer support

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#5462]
We currently support memory and disk buffers, but we do not provide a layered buffer solution that would allow users to overflow buffers in other buffers. For example, overflowing a memory buffer into a disk buffer, or even an external buffer like the one proposed in #5463.

**Comment by jszwedko** [comment]
This is complete and documented on as experimental on https://vector.dev/docs/about/under-the-hood/architecture/buffering-model/#overflow-to-another-buffer-overflow
