### ISSUE TITLE
External buffer support (kafka, kinesis, etc)

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#5463]
Please see #3485 for additional details (this issue was opened unaware of that issue).

We currently offer memory and disk buffers, but we do not allow the use of external systems for buffers. It is interesting to think about configuring Kafka, Kinesis, or even Redis as an external buffer for Vector sinks. This would pair well with #5462.

This is different than using any of these systems as sources/sinks since Vector would transparently handle the partitioning and replaying of the data, shifting the management of these intricacies into Vector.

**Comment by jszwedko** [comment]
Closing in-favor of https://github.com/vectordotdev/vector/issues/9923 which was is the first external buffer we think we'll target.
