### ISSUE TITLE
S3 "latest" folders have incorrect file names

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#5486]
I came across this while investigating https://github.com/timberio/vector-website/issues/235. The `nightly/latest` s3 folder has file name like so:

```
https://packages.timber.io/vector/nightly/latest/vector-0.12.0-arm64.deb
```

It should be:

```
https://packages.timber.io/vector/nightly/latest/vector-latest-arm64.deb
```

We cannot easily produce links for nightly builds in the website since we have no idea what the next version will be. It could be `0.12.0` or `1.0.0`. If we can name it to just `latest` then it should be easy to fix.

**Comment by jszwedko** [comment]
Symlinks exist now for `vector-latest-*` in the `latest` folder.
