### ISSUE TITLE
Investigate Ubuntu parse_timestamp test failures

### ISSUE THREAD

**Issue by LucioFranco** [vectordotdev/vector#551]
In the process of updating our release process, @binarylogic had switched our main builder container for running the `test-stable` build from a Debian based container to a ubuntu one. This caused three local timestamp parsing tests to fail locally. These are the tests that were added from #542 that were originally causing issues and were fixed via adding [this line](https://github.com/timberio/vector/pull/542/commits/f76a8b14fce83f363bfc23a4724e8296c04d7fd1#diff-dfd26227c4842bd3288e9b1f53f0089fR202). They seem to be reoccurring on ubuntu only now. Temp solution has been to move back to a debian based container #550.

We need to evaluate what effect this may have on our users who run vector on ubuntu and what additional steps a contributor using ubuntu must do to get the tests working locally.

**Comment by bruceg** [comment]
I've tried running the tests on my Ubuntu laptop, and they pass for me. Is there an easy way of reproducing them? What is the failure message? The exact values reported by `assert_eq!` should show what failed with the conversion (at least, I assume that's where it's failing).

**Comment by LucioFranco** [comment]
@bruceg were you able to reproduce using this container at all? `timberiodev/vector-tester:latest`

**Comment by lukesteensen** [comment]
I develop on Ubuntu almost exclusively and I don't think I've ever seen one of these failures.

**Comment by bruceg** [comment]
I was able to reproduce with the provided container. However, that container is missing the time zone data files. After installing the `tzdata` package, these tests pass.

**Comment by LucioFranco** [comment]
Does this sound like something that could be useful to be documented?

**Comment by bruceg** [comment]
It would be good to mention something about it. I see the Alpine Linux base image for Docker has no zoneinfo files installed, so it won't be as uncommon a configuration issue as I thought.
