### ISSUE TITLE
Ensure ARC does not negatively affect startup performance and benchmarks

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#5548]
This is an issue I've been thinking about, and I want to make sure ARC does not negatively affect Vector startup performance and benchmarks. This will be important to verify before we switch it to the default. I'd like to discuss ideas, such as:

* Starting with higher, safe defaults (how they're currently configured), and let it adjust from there.
* Do nothing, keep ARC as opt-in (not my preference).
* Adjust the algorithm to increase faster initially.

cc @bruceg and @jszwedko

**Comment by bruceg** [comment]
CC @tobz @binarylogic @blt Noting this is related to #7638 soak testing, datadog sink #7371, and other more recent performance testing work.

**Comment by jszwedko** [comment]
Closing since ARC has been the default for a while now and the benchmark throughput is fairly consistent over time.
