### ISSUE TITLE
Add the capability to assert the event delivery from the sinks to the end destination

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#5574]
The core idea is simple: given an elasticsearch sink, teach Vector to query elasticsearch that the event can be obtained after being written.

When on, Vector will perform this assertion like once every 10 minues. We'll remember one event, send it to the sink (elasticsearch in this example), wait for a bit, and then query the elasticsearch backend to retreive and compare it. If the assertion fails we can report this via a metric or a failed health check.

This a will allow Vector to be the point in the system the ensures/monitors the end-to-end delivery of the events.

**Comment by jszwedko** [comment]
Closing since we've focused on ensuring delivery of events based on the response. If ES returns that an event was accepted, we trust that it accepted it.
