### ISSUE TITLE
New `is_blank` Remap function

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#5576]
This might overlap with existing functions, but we should have a function that can detect common blank values such as:

* `null`
* `""`
* `" "`
* `"  "`
* `"\n"`
* `"-"`

## Usage

```
blank(.field)
=> true
```

**Comment by JeanMertz** [comment]
I would probably name this `is_blank`, similar to other `is_*` functions. Right now it's ambiguous if this function blanks out a field (whatever that means), or does as described in this issue.

Other than that, big 👍 on adding this.
