### ISSUE TITLE
(kafka sink): Add AVRO support to Kafka sink

### ISSUE THREAD

**Issue by erikbos** [vectordotdev/vector#561]
It would be nice to have AVRO support in Kafka sink so data read as JSON gets output'ed as AVRO. Advantages would be input/output validation against schema and less overhead compares to raw JSON.

**Comment by Igosuki** [comment]
Additionally, supporting confluent's schema registry (or other registries for that matter) would add great value. It's simply reading a magic byte then an integer and caching schema responses from the registry.

**Comment by raghu999** [comment]
+1 for avro support , I am new to rust I can try contributing back with some help is this feature an approved usecase for vector?

**Comment by Hoverbear** [comment]
@raghu999 Hi! We'd like to have this feature yes! The first step would be speccing out a proposal. (Eg, how would we know the schema?)

You can do this informally with us here while you play with some ideas and get started looking at  the code. :)

**Comment by Igosuki** [comment]
You can use the avro-rs crate, but it needs to be patched to support fingerprinting schemas.

There are two types of schema resolution, either you have an id of a schema (after the magic byte), which you can use to query a schema registry, or a fingerprint, which you can use to internally resolve a schema from the fingerprint (i.e. the schema has been manually provided by the user).

You can then, map the schema to the internal representation of Vector and that's pretty much it.

I already have a branch started on my computer, just need to find the time

**Comment by Igosuki** [comment]
I'm using Avro instead of protobuf for logging consistent events in avro files or parquet files because the data engineering tooling around it is easier to work with, so that would make vector usable in more than just system logging for me.

**Comment by Hoverbear** [comment]
Sounds like it might be more and more worthwhile to support https://docs.confluent.io/current/schema-registry/index.html

**Comment by Igosuki** [comment]
Both fingerprints and cache registry client with ids are valid implementations. Make sure not to force ppl to deploy schema registry when they can just inline a schema in conf

**Comment by spencergilbert** [comment]
Avro support for source + sink would be interesting to me, @binarylogic would it be good to open a separate issue for source support?

**Comment by fuchsde** [comment]
Avro support for source + sink would be interesting to me as well. +1

**Comment by jianchen2580** [comment]
Avro support for source + sink would be interesting to me as well +1

**Comment by simontilmant** [comment]
Avro support for source + sink would be interesting to me as well +1

**Comment by Akshay2Agarwal** [comment]
Avro support for source + sink would be interesting to me as well +1 along with schema registry option

**Comment by zamazan4ik** [comment]
@jszwedko @spencergilbert Am I right that in current implementation we are already able to use Avro as a message format? As it's already done in `pulsar` sink. As far as I see, it should work: `kafka` sink will use already implemented avro encoder during the serialization. The only missing point here is Schema Registry support - it should be implemented additionally. However, it's still a huge improvement, even without Schema Registry support.

Maybe we just need to update the documentation? However, I didn't test Vector -> Kafka with Avro yet - I just guess based on my understanding of the existing source code.

**Comment by zamazan4ik** [comment]
Regarding Schema Registry support - probably it would be useful to keep in mind: https://github.com/confluentinc/libserdes/

**Comment by yjagdale** [comment]
Any plan to support this one?

**Comment by spencergilbert** [comment]
It's not currently on our roadmap, but we'd be happy to support a community contribution!

**Comment by silverwind** [comment]
Isn't this already supported as per https://vector.dev/docs/reference/configuration/sinks/kafka/#encoding.avro? Why is the issue still open?

**Comment by silverwind** [comment]
My conclusion is that standard Avro encoding is supported on the Kafka sink, but the proprietary [Confluence Schema Registry wire format](https://docs.confluent.io/cloud/current/sr/fundamentals/serdes-develop/index.html#wire-format) is not, see https://github.com/vectordotdev/vector/issues/19872 for that topic. Likely enough to close this issue and continue in the other one.

**Comment by jszwedko** [comment]
> My conclusion is that standard Avro encoding is supported on the Kafka sink, but the proprietary [Confluence Schema Registry wire format](https://docs.confluent.io/cloud/current/sr/fundamentals/serdes-develop/index.html#wire-format) is not, see #19872 for that topic. Likely enough to close this issue and continue in the other one.

Agreed. Closing this since it was implemented by https://github.com/vectordotdev/vector/pull/19342
