### ISSUE TITLE
Emit internal_metrics on buffer usage

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#5654]
### Current Vector Version

```
Dec 21 15:48:26.067 INFO vector: Vector has started. version="0.12.0" git_version="v0.11.0-158-ga2c261d" released="Mon, 21 Dec 2020 04:48:01 +0000" arch="x86_64"
Mon, Dec 21 2020 10:48:26 am
```

### Use-cases

I'd like to be able to graph or alert on sink buffer usage as it could give insight to problems in the logging pipeline (assuming the sink doesn't/can't alert to issues accepting events). 

### Attempted Solutions

None...

### Proposal

I suspect there's already some logic to understand buffer usage (to handle the blocking/dropping of events based on usage), we should be able to emit regular metrics on the usage or available buffer space with the `internal_metrics` source.

**Comment by spencergilbert** [comment]
Related #7185

**Comment by jszwedko** [comment]
Closing this in-lieu of https://github.com/vectordotdev/vector/issues/4936
