### ISSUE TITLE
New `jq` transform

### ISSUE THREAD

**Issue by keneo** [vectordotdev/vector#566]
Run [jq](https://stedolan.github.io/jq/) queries inside vector.

**Comment by binarylogic** [comment]
Adding this for reference: https://docs.rs/jq-rs/0.4.1/jq_rs/

I'd be curious about actual use cases for this since the internal log event is structured.

**Comment by JeanMertz** [comment]
I suppose this will be superseded by our `remap` transform that we're going to stabilize soon, right @binarylogic?

We could still add an explicit `jq` transform for those that are more familiar with its syntax, but it would serve the same purpose, with (arguably) a worse UX.

Having said that, in its current form, `remap` is still less powerful than `jq`, so there might actually be use-cases that remap can't handle, but instead of introducing a new transform to remedy that, I think we should just gradually expand `remap` to cover those use-cases (up to a point, to avoid making things too complex).

**Comment by binarylogic** [comment]
Agree. It is very unlikely we'll support this given the new `remap` transform. I'd like to consolidate the number of ways users can make data as much as possible, and towards something performant.

**Comment by binarylogic** [comment]
Closing in favor of the new `remap` transform. If you have a need for this please comment and let us know.

**Comment by dekelpilli** [comment]
@binarylogic  a jq transform, or a jq function within VRL, would have be very useful for us. There are things JQ can do that VRL cannot (as far as I can tell), namely jq's `select` function, but possibly more. Additionally, the fact that JQ is a well known DSL makes it an easy transformer to expose externally. As is, we will need to add another service that performs the transforms we need before our data reaches Vector.

**Comment by binarylogic** [comment]
Thanks, @dekelpilli. `jq` does have quite a bit more functionality. We can investigate further, but the primary advantages of Remap are safety and performance. If we were to leverage `jq` directly, we would pay a performance penalty and it would be difficult to catch errors at compile-time, hence why we created Remap.

> As is, we will need to add another service that performs the transforms we need before our data reaches Vector.

Can you expand more on this? If you could provide us with a concrete example that would help us fill any gaps or expedite `jq` support.

**Comment by dekelpilli** [comment]
Thanks for the response.

I wouldn't have thought the performance penalty would be significant ([if you compile the JQ command once](https://github.com/onelson/jq-rs#a-note-on-performance)), but perhaps VRL is even faster, although I would be more inclined to compare it to the Lua/WASM alternatives. Given that you wrote about [JQ being used as inspiration for VRL](https://vector.dev/blog/vector-remap-language/#our-solution-vector-remap-language), it would be very interesting to see the performance comparison if that already exists. 

>Can you expand more on this?

Sure. We have customers whose events are going through Vector, and they want to extract certain information from these events. For example, we might get an event that looks like
```json
[{"key": "someImportantKey", "value": 42},
{"key": "otherImportantKey", "value": "foo"},
{"key": "uselessKey", "value": "bar"}]
```
and we want the final output to be
```json
{"someImportantKey": 42,
"otherImportantKey": "foo"}
```
while also not knowing the indexes of the maps ahead of time. A JQ command of `{someImportantKey: .[] | select(.key=="someImportantKey") | .value, otherImportantKey: .[] | select(.key=="otherImportantKey") | .value}` achieves this goal. Additionally, JQ is well known enough that we can let the customers define their own transformation/data extraction, whereas asking them to use VRL is less tenable.

As a result, we're currently using the same jq-rs library mentioned above in a separate service whose only purpose is to act as a transformer for vector.

**Comment by binarylogic** [comment]
Thanks a lot for the detailed info! And that makes sense. I'm reopening for further discussion. We are not opposed to a `jq` transform, we just want to reduce the number of decisions a user has to make to achieve a certain outcome. We felt `jq` and remap overlapped considerably in function, but you are pointing out gaps. We'll take a deeper look next week. Thanks again.

**Comment by jszwedko** [comment]
Hi all!

Vector's focus is on improving VRL to handle all data transformation needs. We want to avoid having a lot of transforms that are similar to `remap` but use a different language, so we won't be prioritizing this. If there is anything that you need that VRL doesn't support, we would welcome an issue for it (I believe the above example could be handled in VRL now that it supports iteration and mapping). There is the potential that we will add support for custom transforms using WASM or some other mechanism so this could also be supported that way.

Thanks for everyone's thoughts here!

**Comment by resttink** [comment]
> Hi all!
> 
> Vector's focus is on improving VRL to handle all data transformation needs. We want to avoid having a lot of transforms that are similar to `remap` but use a different language, so we won't be prioritizing this. If there is anything that you need that VRL doesn't support, we would welcome an issue for it (I believe the above example could be handled in VRL now that it supports iteration and mapping). There is the potential that we will add support for custom transforms using WASM or some other mechanism so this could also be supported that way.
> 
> Thanks for everyone's thoughts here!

Hi! Could you please tell me how can I get JQ's functionality by using remap with "iteration and mapping" in this case.
For instance I have a json like in previous case:
`[{"key": "someImportantKey", "value": 42},
{"key": "otherImportantKey", "value": "foo"},
{"key": "uselessKey", "value": "bar"}]`
and I want to get:
`{"someImportantKey": 42,
"otherImportantKey": "foo"}`

What remap transformation section would be like?

**Comment by pront** [comment]
> > Hi all!
> > Vector's focus is on improving VRL to handle all data transformation needs. We want to avoid having a lot of transforms that are similar to `remap` but use a different language, so we won't be prioritizing this. If there is anything that you need that VRL doesn't support, we would welcome an issue for it (I believe the above example could be handled in VRL now that it supports iteration and mapping). There is the potential that we will add support for custom transforms using WASM or some other mechanism so this could also be supported that way.
> > Thanks for everyone's thoughts here!
> 
> Hi! Could you please tell me how can I get JQ's functionality by using remap with "iteration and mapping" in this case. For instance I have a json like in previous case:
> 
>  [{"key": "someImportantKey", "value": 42},
>  {"key": "otherImportantKey", "value": "foo"},
>  {"key": "uselessKey", "value": "bar"}]
> and I want to get:
> 
>  {"someImportantKey": 42,
>  "otherImportantKey": "foo"}
> What remap transformation section would be like?

Hi @resttink, please create a https://github.com/vectordotdev/vrl/discussions/new?category=q-a to get better support. Thank you.
