### ISSUE TITLE
Terraform resource definitions for `aws_s3` source

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#5660]
This goes back to my thoughts around encoding resources in an abstract way so that we can document them across different tools, such as the AWS CLI, Terraform, and Ansible.

The `aws_s3` source requires a few things to operate properly:

1. AWS S3 bucket
2. AWS SQS queue for bucket notifications
3. Bucket notifications enabled to post to SQS
   1. Only actions that reflect object creation should be posted

All of this would be much easier if we gave users Terraform definitions, etc.

**Comment by lucperkins** [comment]
Though potentially overkill, I think it'd be worth discussing offering a [Terraform module](https://www.terraform.io/docs/modules/index.html).

**Comment by jszwedko** [comment]
Also noting that there is an existing terraform module: https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/v1.17.0/modules/notification

**Comment by jszwedko** [comment]
Closing since I think this is outside of the scope of Vector.
