### ISSUE TITLE
add redis source support

### ISSUE THREAD

**Issue by shumin1027** [vectordotdev/vector#5696]
sub-issue for #5199

support `redis` (list、channel、pattern channel、stream) as a data `source`

**Comment by jszwedko** [comment]
Just noting that I got another request for this source in office hours today. Specifically long polling lists which I believe is what the contributor PR does.

**Comment by leebenson** [comment]
This is on my radar for the next sprint 👍🏻

**Comment by pachico** [comment]
I'm looking forward to test this feature.
We currently use Logstash to pull data from Redis our intention is to replace it with Vector. 
It's quite a simple use case in which applications write potentially big (> 100kb) payloads to Redis and are being pulled by Logstash to then be sent to Elasticsearch.
In case this can be useful, this is the information about Logstash Redis Input Plugin:
https://www.elastic.co/guide/en/logstash/current/plugins-inputs-redis.html

**Comment by pachico** [comment]
@leebenson do you have a target or an estimation about when this could be GA?
I'm not asking out of urgency but rather to plan and allocate some of my time to do testings to finally replace part of our Logstash deployment.
Thanks in advance.

**Comment by leebenson** [comment]
@pachico, I'm likely to be tied up with other priority work streams for the remainder of this sprint, and likely the next -- which will take me up until around the end of this month.

Given the scope of this issue and the urgency a few users have expressed, I'll circulate this internally to see if another team member has the cycles to take a look in the meantime.

I know everyone on the team is pretty busy with our current Q2 priorities, so I can't guarantee a firm ETA right now. Worst case, I'll be able to look myself ~early May.

Will keep you posted in this issue.

**Comment by pachico** [comment]
Thanks a lot, @leebenson . Again, this is just to know when I can/should allocate some time on my end. Cheers

**Comment by shumin1027** [comment]
@leebenson I create a PR #7096 for this issue
but only support redis (list、channel) as a data source

**Comment by pachico** [comment]
Hi @leebenson , this is a friendly ping to check if this has been prioritized in your end since our use case is demanding some attention.

**Comment by jszwedko** [comment]
Thanks for the bump @pachico . We've been reviewing the `redis` sink PR #7078  with the expectation to move onto the source PR once that is merged. The sink PR is almost there so I expect we'll start reviewing the source PR shortly.

**Comment by pachico** [comment]
@jszwedko Thanks a lot! Hopefully our planets will align and I'll be able to use this in the near future. Cheers!

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/7096
