### ISSUE TITLE
The Remap `to_float` function should accept timestamps

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#5731]
Passing a timestamp to `to_float` should return the Unix representation of the time where fractional seconds are represented by decimals:

```
1609082803.232125
```

There should be no loss of precision.

**Comment by jszwedko** [comment]
This is less controversial than #5730, but I still think it feels a bit weird and unexpected. If I wanted to convert a timestamp into a unix timestamp, I would not think to look at `to_float` / `to_int`.

Similar to #5730 I might encourage users to use: `to_float(format_timestamp(...))`.

**Comment by jszwedko** [comment]
Re:

> There should be no loss of precision.

There are the usual caveats that some numbers cannot be represented as floats.

**Comment by JeanMertz** [comment]
Do we still want to pursue this?

On the one hand, there hasn't been a single request for this, and I have never had a need for this in my career either. On the other hand, we merged a PR to support this for `to_int` (and we now also have `to_unix_timestamp`), so maybe it makes sense to do this for consistency?

**Comment by jszwedko** [comment]
👍 I'm fine with iceboxing it until someone asks for it.
