### ISSUE TITLE
create/update index templates and ilm policies inside elasticsearch

### ISSUE THREAD

**Issue by golgoth31** [vectordotdev/vector#5737]
### Use-cases

It would be awesome if elasticsearch sink was able to create/update index templates and ilm policies inside elasticsearch.

### References

A function like this one: https://github.com/uken/fluent-plugin-elasticsearch#enable-index-lifecycle-management should be perfect

I absolutly don't know rust so I coudn't help you on this point but I can make some tests against elasticsearch cluster if needed. Thank you for your job !

**Comment by zsherman** [comment]
@jdrouet might be a dup, feel free to close if so

**Comment by golgoth31** [comment]
Hi,
this is a partial dup of #7745 but only on the ILM part. Adding support of sending templates definition is also important IMHO. It would be awesome to be able to push templates definition based on infex name as index name templating is already supported (https://vector.dev/docs/reference/configuration/sinks/elasticsearch/#index)

**Comment by jszwedko** [comment]
Closing this in-lieu of https://github.com/timberio/vector/issues/7745# . Feel free to add any additional details there though!
