### ISSUE TITLE
Expand scope to include error forwarding

### ISSUE THREAD

**Issue by derekperkins** [vectordotdev/vector#575]
We currently ship errors directly to both hosted Sentry and Stackdriver Error Reporting from every app. I would prefer to send those directly to vector and expose various error services as sinks. In most implementations, I would expect that errors will share all the same labels and metadata as logs and metrics.

**Comment by derekperkins** [comment]
After a conversation with @zsherman, I wanted to update this issue with a feature request for deduping errors. We use hosted Sentry, and if something happens to our db, even if just a failover, we have enough throughput that errors burn through our quota almost immediately. It would be nice if Vector could suppress duplicate errors as they go through.

**Comment by jszwedko** [comment]
I think this is covered by https://github.com/vectordotdev/vector/issues/7383 with the `dedup` transform.
