### ISSUE TITLE
New `redact_values` Remap function

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#5784]
Blocked in #5785. Like #5783, but for the `redact` function.

## Example

Given this event:

```json
{
	"parent": {
		"child": "222"
	}
}
```

And this Remap expression:

```js
replace_values('foo', 'bar')
```

Or

```js
replace_values(/foo/, 'bar')
```

The following event would be produced:

```json
{
	"parent": {
		"child": "bar"
	}
}
```

**Comment by jszwedko** [comment]
Closing since this is supported by VRL iteration now.
