### ISSUE TITLE
logs lost when reload configs.

### ISSUE THREAD

**Issue by chezgi** [vectordotdev/vector#5795]
i have a config for vector sink and it was incorrect after changing it and reloading vector, all old logs lost.

old config:
#--------------------------------
[sources.journal]
    type = "journald"
    current_boot_only = false
    remap_priority = false
[sources.internal_metrics]
  type = "internal_metrics"

[sinks.vector]
  type = "vector" 
  inputs = ["internal_metrics","journal"] 
  address = "http://1.1.1.1.:9191"   # <-------------------------- this line changed

new config
#--------------------------------
[sources.journal]
    type = "journald"
    current_boot_only = false
    remap_priority = false
[sources.internal_metrics]
  type = "internal_metrics"

[sinks.vector]
  type = "vector" 
  inputs = ["internal_metrics","journal"] 
  address = "1.1.1.1.:9000"       # <-------------------------- this line changed

#--------------------------------------------

> systemctl reload vector

only new logs received on other side vector node.
but old logs all lost

vector version: 0.11.1

**Comment by chezgi** [comment]
ping,
nobody assigned to this bug.

**Comment by chezgi** [comment]
@jszwedko

**Comment by jszwedko** [comment]
Apologies @chezgi . I lost track of this issue. When you say the original address was incorrect, was the address itself valid? That is, was Vector sending logs there? My guess here is that the `journald` source checkpointed once it processed the logs. You can reset this by removing the checkpoint file from `/var/lib/vector`.

**Comment by chezgi** [comment]
old address doesn't exist therefore no connection established between vector and loki.
it is old issue. and i does not checked it recently.
maybe it is solved with new version.

**Comment by jszwedko** [comment]
Was the upstream `vector` instance the one sending to Loki? I don't see Loki mentioned in the config above.

**Comment by chezgi** [comment]
excuse me,
it my mind failure,
it's upstream was `vector`.

**Comment by jszwedko** [comment]
Thanks for clarifying @chezgi 

I tried this just now, but I wasn't able to reproduce. It seems like Vector correctly forwarded the old logs. Would you be able to try again with the latest version v0.14? Apologies again for the original delay in responding to this issue.

**Comment by chezgi** [comment]
thanks @jszwedko 
i am working on another project. but i will check it next time the project activated.

**Comment by jszwedko** [comment]
👍 thanks @chezgi

**Comment by lol1501303824** [comment]
?

**Comment by lol1501303824** [comment]
@jszwedko My vector cannot read logs that are no longer updated. Is there any solution?

**Comment by jszwedko** [comment]
Closing as stale, but please leave a comment if you observe this behavior and we can reopen.
