### ISSUE TITLE
Ability to enable/disable specific nodes in Vector's topology graph

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#5799]
From a user in Discord:

> If we can enable and disable a node in the graph it will be more useful. We can configure all processing in the graph and only enable nodes when needed.
> in current config, when i want to remove some nodes i must change anywhere i used it.

Followed up with:

> we can use vector for aggregating multiple prometheus sources inside host. and send it to central vector. then feed it inside prometheus server. therefore we must assign some labels per node in source host or central vector. in vector source component we can not add labels based on source. therefore in host node we must add some useful tags like hostname or ipaddress.

This should be accomplished through the Vector API.

**Comment by leebenson** [comment]
Before we tackle this, do we want to agree on a path forward for updating configuration in the API?

It might be orthogonal, but feels like before offering the ability enable/disable specific components, it might be useful to offer blanket config validation/updating which feels like a superset of this feature.

**Comment by jamtur01** [comment]
Indeed, this heads into the terrain where we should consider auth and access control. I am +1 on starting with less granular.

**Comment by jszwedko** [comment]
Yeah, I agree with @leebenson here that we should just model enabling/disabling of components in the configuration and the API would support a general "update configuration" feature.

**Comment by jszwedko** [comment]
Closing based on reasoning in https://github.com/vectordotdev/vector/issues/13736#issuecomment-1209822534

We are working on a reload API in #15562  though.
