### ISSUE TITLE
New `get_hostname` Remap function

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#5800]
Retrieve the current machine's hostname. I chose the `get_hostname` name to be consistent with other `get_*` functions, even though `gethostname` is used elsewhere.

## Open Questions

1. Should this require caching of any kind? I assume, since this is a local call, there is very little latency, and I'm curious if the native Rust function already achieves this in some way. It is worth verifying.

**Comment by chezgi** [comment]
this can be a list of useful system functions like:
get_cpu_arch
get_kernel_version
get_timezone
get_username
get_uptime
get_hostname
....

**Comment by binarylogic** [comment]
@chezgi sure. Do you have Vector use cases that would require these? We're trying our best to only include functions that add value to observability data processing.

**Comment by chezgi** [comment]
it is only a suggestion list.
some time if we think more general its result may be better.

**Comment by drunkirishcoder** [comment]
Was looking for this remap function. some other thoughts along the same line as @chezgi, it would be useful to be able enrich the events with host metadata inside vector directly, but I also see the problem of trying to include too many things and "polluting" the remap language. There are a couple other ones in addition to `hostname` that I may find useful.

* vector version, a programmatic way to add vector version to the event entry. right now we are hard coding the version value which would be out of sync if we don't manually update the config every time we upgrade vector.
* host ip, maybe less necessary, but similar to hostname, provides more contextual information that the app doesn't have to add.
