### ISSUE TITLE
Use Kafka as a buffer between two Vector instances (decoding Vector data)

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#5809]
#5341 added the ability to send metrics to Kafka by serializing them into plain-old JSON (useful for custom consumers on the other end), but it raises the question of using Kafka as a medium between two Vector instances. In this scenario, Vector events would transparently pass through systems like Kafka in a manner that would preserve their event types on the other end. There are a few questions we must address before doing this:

1. Is this a deployment topology that we want to support? A case could be made that #5463 is a better approach; one that aligns with the real reason a user would use Kafka in this manner (as a buffer). By doing this, we shift more control to Vector, reducing the decisions the user has to make, and improving the UX.
2. Should we use a private format, like our protobufs, or adopt an open standard like OpenTelemetry?
3. How would backward compatibility work? For example, deploying a new version of Vector while old serialized data still lives on Kafka.

In general, I lean towards adopting an open standard assuming it is able to correctly preserve all of our event details.

**Comment by jszwedko** [comment]
Just noting, as a user, that I'd naively expect metrics published by the `kafka` sink to be consumable via the `kafka` source. I'd expect this sort of parity for all matching source/sinks.

**Comment by binarylogic** [comment]
@jszwedko completely agree, see https://github.com/timberio/vector/issues/5341#issuecomment-739006798.

@eeyun have you decided how you'll be handling this in #5124?

**Comment by eeyun** [comment]
I've just started digging in on encoding/decoding today so I haven't really gotten a very strong opinion yet and havent really digged into the metrics angle at all yet.

More generally on encoding -my preference would pretty much _ always_ be to follow an open standard with clear adoption (assuming no clear and explicit reasons to avoid doing so).

**Comment by jszwedko** [comment]
This came up in discord again: https://discord.com/channels/742820443487993987/746070591097798688/826392118095773727

Specifically using Kafka to bridge two vectors

**Comment by tobz** [comment]
Going to close this in favor of #9930.

We plan on exploring a way to simply expose the ability to decode/encode native Vector events. Instead of accepting a particular shape of data from an arbitrary source/sink, the native Vector event representation would be used instead. This is both simpler to implement and would result in higher performance, because ultimately, all data flowing into Vector is converted to our native internal representation.
