### ISSUE TITLE
Define sink-level events and metrics (schema)

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#5810]
We still need to instrument all of Vector's sinks, which raises the question of which metrics we should emit (see https://github.com/timberio/vector/pull/5432). The requirements in issues like #4964 are not comprehensive. While sinks should share basic component-level metrics, like `events_processed` and `events_discarded`, we'll also want to capture other metrics that relate to transmission, retries, failures, and so on. If possible, these metrics should be handled in lower-level sink constructs that enable sinks to inherit these metrics.

As a first step, we should agree on what all of these metrics look like (a schema) and then open issues implementing these metrics in the appropriate places. #4936 is the only issue I'm aware of that covers this, we will need many more like HTTP activity, socket activity, etc.

**Comment by jszwedko** [comment]
Covered by https://github.com/vectordotdev/vector/blob/master/docs/specs/component.md
