### ISSUE TITLE
Consolidate transforms by their high-level function

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#5823]
With the new `remap` transform in place, seeing [this](https://share.getcloudapp.com/NQuK5yqw) makes me happy. It's much easier to grok and understand than [this](https://share.getcloudapp.com/2Nu0WGYk), [this](https://share.getcloudapp.com/rRu0m4p0) or [this](https://share.getcloudapp.com/7KubXY4w). This got me thinking, I like the idea of consolidating transforms around their high-level function (remap, reduce, route, filter, sample, dedupe, program, etc). That said, I propose the following transform changes:

1. `swimlanes` -> `route`
2. `geoip` & `aws_ec2_metadata` => `enrich` (AKA lookups)
3. `sampler` -> `sample` (for consistency)
4. `lua` & `wasm` -> `program` (this one is most controversial)

That's it really. Just because we expose configuration in a way that consolidates transforms by their high-level function does not mean we need to organize the code similarly. We can still keep the code separated by their lower-level function for maintainability. And in many ways, this keeps us honest and consistent with the options we expose by function. It'll also prevent the decision fatigue that has been created with other tools, further contributing to our goal of offering the best UX.

Alternatively, we could keep components aligned with their low-level functions and categorize them in the documentation by their high-level function. I prefer what's proposed above (high-level) since it'll force us to think about how a new component fits into the overall context of its higher-level function.

**Comment by JeanMertz** [comment]
Have your thoughts evolved since posting this issue, @binarylogic? We can discuss this work within the team (not necessarily doing the work, but investigating the effort required, and listing the pro's and cons), or close as "wontfix". Please let me know your thoughts.

**Comment by tshepang** [comment]
looks to me like all these are done, all but the controversial one

**Comment by jszwedko** [comment]
Closing since enrichment has moved towards enrichment tables (including geoip enrichment being migrated). The rest of the items in the list were done.
