### ISSUE TITLE
Consolidate UX around enrichment in the context of Remap

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#5862]
There is currently a lot of discussion around enrichment and where it belongs in Vector. In essence, should enrichment capabilities be defined as Remap functions, separate transforms, or both? If both, what factors determine where it belongs? For more context:

1. See point 2 in #5823.
2. #5800 introduces a new `get_hostname` function which could alternatively be solved with a `host_metadata` transform.
3. #5860 introduces a new `vector_metadata` transform which could alternatively be solved with a `vector_metdata` Remap function.
4. #5647 attempted to add additional DNS context but was closed due to the fact that it issues network calls.
   * @JeanMertz pointed out (https://github.com/timberio/vector/issues/4517#issuecomment-754215441) that this could be trivially solved in Remap.
5. Finally, there is a larger project on the horizon where Vector could join and enrich events from other custom databases which, of course, introduce a lot of variability.

As you can see, there's a lot of inconsistency here. Rules would help clean this up.

## Proposal

From a UX perspective, I'm a big fan of #5823, and I think a single `enrich` transform would help separate responsibilities away from remapping, ensuring that we can implement the facilities necessary (like caching) to ensure high performance. Inevitably there will be additional information needed for advanced enrichment (database connection details, database files, etc.).

Alternatively, as mentioned in #5823, we should just categorize transforms so they are organized by function in the docs, without needing to make changes to our component.

**Comment by JeanMertz** [comment]
@binarylogic what are your thoughts on this issue 1 year on?

We have enrichment tables that can be accessed in VRL, we have ongoing work surrounding event metadata and accessing that data in VRL.

We haven't renamed or re-categorized any existing transforms, so that could still be desirable, depending on your thoughts.

**Comment by jszwedko** [comment]
Closing due to the introduction of enrichment tables since its creation and its not clear what exactly what else is being proposed here.
