### ISSUE TITLE
`del` will fail silently when attempting to delete immutable metric paths

### ISSUE THREAD

**Issue by StephenWakely** [vectordotdev/vector#5887]
Given the work done in #5633 which is making `del` an infallible function there is an issue with Metric events when deleting immutable metric paths.

With log events, the only time when `del` will not actually delete a field is when that field already does not exist - so the end result is the same.

However, with metrics, for example, you cannot delete the metric name. `del(.name)` will not raise an error, however the metric name will not be deleted.

**Comment by jamtur01** [comment]
@FungusHumungus Is this a before 0.12 or after?

**Comment by FungusHumungus** [comment]
> @FungusHumungus Is this a before 0.12 or after?

Definitely after. We at minimum need to be able to identify whether the context remap is running in is log or metric.

**Comment by binarylogic** [comment]
@FungusHumungus isn't remap restricted to tag? So deleting `.name` would delete the `name` _tag_, not the actual metric name.

**Comment by FungusHumungus** [comment]
> @FungusHumungus isn't remap restricted to tag? So deleting `.name` would delete the `name` _tag_, not the actual metric name.

Remap can access `.name`, `.namespace`, `.timestamp`, `.kind` (incremental or absolute (readonly)),  `.type` (counter, gauge, set etc.. (readonly)) as well as `.tags`.

To delete the name tag would be `del(.tags.name)`, that works fine. Just deleting the name `del(.name)` does nothing since a metric without  a name is invalid.

**Comment by JeanMertz** [comment]
Closing this issue, as we now support read-only paths that return a compile-time error when used with `del` and other mutable functions.
