### ISSUE TITLE
Continous long-running soak tests for nightly builds

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#5897]
This overlaps with #5895 in its broad purpose of identifying regressions that fall under our noise threshold.

We should consider soak tests that run over a defined period for our nightly builds. This will help raise issues like #5839.

We should consider other ways that we could identify these types of regressions, like what's proposed in https://github.com/bheisler/criterion.rs/issues/97, before implementing this.

**Comment by tobz** [comment]
I think we can close this now that we run soak tests for all PRs and have the means to run them trivially between two release versions for demonstrating commit-by-commit and release-by-release changes.
