### ISSUE TITLE
Breakdown Kubernetes metadata and define it's source

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#5898]
As part of #5847, we want to draw lines around the Kubernetes metadata and identify a modular, progressive approach to including this data. It has been said that limited support of this metadata would likely cover 90%+ of use cases. To help us identify the value/cost ratio of supporting this metadata we need to group the data into categories based on their implementation so that we can prioritize their implementation. The easiest way to do this would be to demonstrate a _full_ JSON document with example metadata and then describe, and categorize, where that data comes from. For example:

```js
{
	// Local Pod metadata
	"pod_ip": "...",
	"pod_labels": "..."

	// Kubernetes API (ABC endpoint)
	"...": "..."
}
```

Describe each commented service, how difficult it is to retrieve the data, and so on.

**Comment by portante** [comment]
We first might want to consider making sure that the "address" of the log entry is provided by the metadata: (what host, host namespace UUID, what pod UUID, what container UUID, stream ("stdout" or "stderr), and a monotonically increasing number representing the offset of that log entry in the stream).  We might also have to add a kubernetes cluster ID, if not already available, for cases where logs are sent from multiple kubernetes clusters to one log store.

This "address" metadata would be the absolute minimum required, and while we probably already have that metadata today, if any address metadata is missing that might be considered a priority to add.

After that there is a tremendous amount of metadata that could be added to the logs that are sent off host:

 * container metadata (kubectl describe container)
 * pod annotations
 * pod labels
 * pod metadata (kubectl describe pod)
 * namespace annotations
 * namespace metadata (kubectl describe namespace)

I would advocate (and this is controversial and arguable) that it is only a convenience to have a log forwarding system such as vector add all that metadata.  The sink where the data is sent being to should be able to handle adding that metadata efficiently, as long as the log "address" metadata is properly provided by the forwarder.

Adding metadata could make the size of each log entry grow very large, and the cost of collecting all that metadata from Kubernetes can also take a toll on the system.

**Comment by MOZGIII** [comment]
@portante, just FYI, we already have some of the fields you mentioned in the address data available: https://vector.dev/docs/reference/sources/kubernetes_logs/#output. We're currently missing just the container ID and a stream offset. Kubernetes cluster ID is also missing, but it's not a data point that's available through the API afaik - this bit of data has to be injected by the user via some custom means.

> a monotonically increasing number representing the offset of that log entry in the stream

Could you please elaborate on what kind of data point are you looking for here? Would something like a line number/byte offset from the source log file work here? I'm asking to better understand the assumptions and how would you use this data. Is this for deduplication?

> I would advocate (and this is controversial and arguable) that it is only a convenience to have a log forwarding system such as vector add all that metadata. The sink where the data is sent being to should be able to handle adding that metadata efficiently, as long as the log "address" metadata is properly provided by the forwarder.
> 
> Adding metadata could make the size of each log entry grow very large, and the cost of collecting all that metadata from Kubernetes can also take a toll on the system.

I tend to agree, such architecture would definitely be a step up in the possibilities of metadata annotation. One downside is that the sink has to be way more advanced and be aware and possibly coupled with the metadata source. It's obviously less elegant than a sink system being decoupled and accepting the "backbox" log events as is - but the reduction in transmitted log events size may very well worth it!

**Comment by portante** [comment]
> @portante, just FYI, we already have some of the fields you mentioned in the address data available: https://vector.dev/docs/reference/sources/kubernetes_logs/#output.

Great.

> We're currently missing just the container ID and a stream offset. Kubernetes cluster ID is also missing, but it's not a data point that's available through the API afaik - this bit of data has to be injected by the user via some custom means.

Agreed.  See also https://github.com/kubernetes/kubernetes/issues/58638 (now closed, but that would save so many API calls).

> 
> > a monotonically increasing number representing the offset of that log entry in the stream
> 
> Could you please elaborate on what kind of data point are you looking for here? Would something like a line number/byte offset from the source log file work here? I'm asking to better understand the assumptions and how would you use this data. Is this for deduplication?

The byte offset of the start of the data in the would be great, so that when somebody sees a log entry they are looking for they can reconstruct the rest of the logs around it to better understand the context.

A monotonically increasing number is also helpful so that there is a total order of what Vector read across log files so that when you need to look at things forensically the behavior of the collector is clear in the data sink.  Sometimes the data sinks can be a bit "loose" with ordering.

One can also use this for deduplication, but I was mostly thinking about when I had to piece together behaviors and it was a pain to build a picture of how it looked before sent off host.

> 
> > I would advocate (and this is controversial and arguable) that it is only a convenience to have a log forwarding system such as vector add all that metadata. The sink where the data is sent being to should be able to handle adding that metadata efficiently, as long as the log "address" metadata is properly provided by the forwarder.
> > Adding metadata could make the size of each log entry grow very large, and the cost of collecting all that metadata from Kubernetes can also take a toll on the system.
> 
> I tend to agree, such architecture would definitely be a step up in the possibilities of metadata annotation. One downside is that the sink has to be way more advanced and be aware and possibly coupled with the metadata source. It's obviously less elegant than a sink system being decoupled and accepting the "backbox" log events as is - but the reduction in transmitted log events size may very well worth it!

Agreed.

I bring this up so that Vector can consider documenting that adding metadata to logs carries a material cost that can sometimes work against the collector's ability to keep up with the log load.

**Comment by jszwedko** [comment]
Closing this since the `kubernetes_logs` metadata has been pretty static over the last year and is driven from the reflector. We can let users open specific requests for additional metadata like stream offset.
