### ISSUE TITLE
compile VRL to Wasm

### ISSUE THREAD

**Issue by JeanMertz** [vectordotdev/vector#5948]
I've had the goal to be able to run VRL in a browser for some time now, since it allows us to add a playground to Vector's website and have it run locally in the browser without the need for a server to compile the program.

The good news is that we're 99% there. The `remap-lang` crate already compiles on `wasm32-unknown-unknown`:

```
$ cargo build --release --target wasm32-unknown-unknown
...
Finished release [optimized] target(s) in 14.55s
```

We'll have to shave of some bytes to have it be less bloated (it's around ~3 MB right now), but there are [ways to do that](https://rustwasm.github.io/book/reference/code-size.html), so I'm not too worried about that.

Next, we want to be able to use function in the language. I've managed to compile all but the `uuid_v4` and the `parse_grok` functions:

```
cargo build --release --target wasm32-unknown-unknown --no-default-features --features assert,ceil,compact,contains,del,downcase,encode_json,ends_with,exists,flatten,floor,format_number,format_timestamp,includes,ip_cidr_contains,ip_subnet,ip_to_ipv6,ipv6_to_ipv4,is_nullish,log,match,md5,merge,now,ok,only_fields,parse_aws_alb_log,parse_aws_cloudwatch_log_subscription_message,parse_aws_vpc_flow_log,parse_duration,parse_json,parse_key_value,parse_syslog,parse_regex,parse_regex_all,parse_timestamp,parse_url,redact,replace,round,sha1,sha2,sha3,slice,split,starts_with,strip_ansi_escape_codes,strip_whitespace,to_bool,to_float,to_int,to_syslog_level,to_string,to_syslog_severity,to_timestamp,tokenize,truncate,upcase
...
Finished release [optimized] target(s) in 29.06s
```

Interestingly enough, this library ends up at ~2 MB, even though it includes the `remap-lang` dependency. Still though, here too we can shave off quite a few bytes by enabling size optimization features in the Rust compiler, and using `wasm-pack`.

We can fix `uuid_v4` by adding this to Cargo:

```toml
[target.wasm32-unknown-unknown.dependencies]
uuid = { version = "0.8", features = ["v4", "wasm-bindgen"], optional = true }
```

As for `parse_grok`, what one's a bit more involved. It's the `grok` dependency that doesn't compile. Looking into it, it seems it depends on `onig-sys` which [works, but only if you disable some of its default features](https://github.com/rust-onig/rust-onig/issues/153#issuecomment-705170682).

All in all, I think it's only a few hours worth of effort to get a simple html page up that includes the VRL wasm module.

**Comment by jszwedko** [comment]
Closing since we dropped wasm support #8036

**Comment by JeanMertz** [comment]
I'm re-opening this, since discussions with @zsherman revealed the need (at some point) to have a VRL "playground" on our website for people to experiment with. While we could run VRL server-side, it would be more efficient/cost-effective to have it run locally using Wasm.

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/14668
