### ISSUE TITLE
Docs on website include unreleased options

### ISSUE THREAD

**Issue by kamalmarhubi** [vectordotdev/vector#5995]
I was trying to get a docker source going and wanted to use `exclude_containers` as [documented](https://vector.dev/docs/reference/sources/docker_logs/#exclude_containers). After some confusion, I realised that this is not actually available in 0.11, and that I have to use a nightly. (:cry:)

The docs should probably either be for the latest release, or allow choosing among versions and default to the latest release.

**Comment by kamalmarhubi** [comment]
Just a bump: this makes for a pretty bad first-run experience.

**Comment by lukesteensen** [comment]
Hey @kamalmarhubi, sorry for the lack of response here. We definitely agree it's a problem and it's not our intended state of the docs, but for a number of unfortunate reasons, it's persisted far longer than we intended. We're hoping to get the 0.12 release out early next week, which should largely address this, and there's a bigger docs site redesign in the works that should handle versioning much better. Apologies again for the poor experience and thanks for raising the issue!

**Comment by jszwedko** [comment]
We've resolved this issue with the new website release process. `vector.dev` will represent the latest release.
