### ISSUE TITLE
Remap enumerating/looping RFC

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#6031]
We need an RFC that obtains consensus on our approach to enumerating/looping in Remap. There are a few open issues that require this (#5377, #5784, #5783, #5852), and we've had a number of discussions floating around (https://github.com/timberio/vector/issues/5852#issuecomment-755136066). Once we decide on an approach we should update the referenced tickets to reflect it.

Note: this is not blocking 0.12. We will be shipping 0.12 without this feature.

**Comment by jszwedko** [comment]
Just putting this here so I don't lose it again: https://github.com/josevalim/nested-data-structure-traversal

Examples of mapping / iteration in a bunch of languages.

**Comment by binarylogic** [comment]
That project is very interesting! For posterity, [Lua](https://github.com/josevalim/nested-data-structure-traversal/blob/master/lua/reduce/reduce.lua) and [Python](https://github.com/josevalim/nested-data-structure-traversal/tree/master/python) are my favorite due to their immediately obvious and simple nature. I get that we'd need to discuss low-level changes to the language, but from a pure readability perspective those are my favorite.

**Comment by JeanMertz** [comment]
ref #8381

**Comment by dbcfd** [comment]
Given that arrays have a push capability, could a simple first pass just be ```
acc = []
for obj in .array {
  obj.new_field = 1
  push(acc, obj)
}```

More complicated functions could be built later, but this seems like it would solve a lot of use cases.

**Comment by dbcfd** [comment]
Additionally, iterating an object could be accomplished with a tuple object

```
for kv in .object {
  .key = kv.0
  .value = kv.1
  }
  ```

**Comment by binarylogic** [comment]
Closing in favor of https://github.com/vectordotdev/vector/issues/8381
