### ISSUE TITLE
Kafka sink: use signal instead timeout on full buffer

### ISSUE THREAD

**Issue by fanatid** [vectordotdev/vector#6057]
Initially `kafka` sink was changed to use a timeout in https://github.com/timberio/vector/pull/4846. In the same pull request @lukesteensen proposed to use signal instead timeout (https://github.com/timberio/vector/pull/4846#discussion_r516955267). I changed timeout to signal in https://github.com/timberio/vector/pull/5007.
Unfortunately, this caused significant performance decrease (https://github.com/timberio/vector/pull/5007#issuecomment-755586053), so Luke reverted #5007 in https://github.com/timberio/vector/pull/5900 and proposed to use [notify_waiters](https://docs.rs/tokio/1.0.1/tokio/sync/struct.Notify.html#method.notify_waiters) from `tokio:1.0`.

Currently blocked by https://github.com/timberio/vector/issues/5175

**Comment by jszwedko** [comment]
Noting that https://github.com/vectordotdev/vector/issues/5175 is done so this work could seemingly be done.

**Comment by jszwedko** [comment]
I'll close this, though, since it seems like technical debt without user-facing impact.
