### ISSUE TITLE
Support compression on vector sink

### ISSUE THREAD

**Issue by shohamd4** [vectordotdev/vector#6058]
### Current Vector Version
0.11.1

```
...
```

### Proposal
Google Protobuf uses varint encoding that should help to reduce the message by itself, but I think that supporting compression would help to reduce the size of the messages even more. Since Vector sends mostly text, the compression will be very efficient.

**Comment by jszwedko** [comment]
Related to #6032

**Comment by splitice** [comment]
I mainly view vector source/sink as an alternative for RELP. I.e it should provide:
1. reliable delivery of events
2. backpressure
3. encoding handling
4. compression
5. encryption

I'm not sure if the goals of the vector "protocol" (is it just me or is having a source/sink share the name of the underlying software confusing?) have been documented (and my view matches) but I hope it does.

FYI I wonder if #3675 could be avoided by supporting RELP features in the vector protocol.

**Comment by jszwedko** [comment]
Closing since `v2` of the `vector` source/sink does support compression.
