### ISSUE TITLE
Allow configuration of vector source frame size

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#6077]
Requested by user in discord: https://discord.com/channels/742820443487993987/746070591097798688/799288509508747294

Currently we hardcode the frame size maximum as 8 MB, but it'd be nice to allow users to configure it if they have a need to handle very large events.

More discussion: https://discord.com/channels/742820443487993987/746070591097798688/799676053290483742

**Comment by binarylogic** [comment]
@eeyun this is irrelevant given the HTTP change, correct?

**Comment by jszwedko** [comment]
I'd say _might_ be irrelevant depending on the chosen approach. We should be sure to include this configuration consideration with whatever approach is chosen in #5124.

Also, adding it to the existing `vector` source is a relatively small change that could be made much sooner than we swap out the entire communication protocol.

**Comment by zamazan4ik** [comment]
@jszwedko Is it still an issue for the Vector source? After the quick search over the `vector` source, I cannot find anymore related codeline about frame size for the Vector source.

**Comment by zamazan4ik** [comment]
However, as far as I can see, other sources have possibility to configure framing behaviour to the `length_delimited ` mode. And in this case there is no way to configure the maximum length size right now (the default is still 8 Mib, which is defined inside `tokio-util`).

**Comment by jszwedko** [comment]
Thanks @zamazan4ik . You are correct that this is no longer an issue since the new gRPC-based protocol doesn't have the same issue. You are also correct about the default max length for the Tokio codecs. Happy to see a new issue for that :)

**Comment by zamazan4ik** [comment]
> Happy to see a new issue for that

Okay, will do it :) However, I do not think that the issue is important right now (But I could be wrong here).
