### ISSUE TITLE
Add `trim` option to the Remap `split` function

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#6098]
The `split` function could benefit from the ability to trim its values.

## Example

```js
split("first, second,third", ",", trim: true)
```

Produces:

```js
["first", "second", "third"]
```

**Comment by jszwedko** [comment]
I feel like this could also be accomplished by using whatever we provide for iteration. Something like:

```
map(split("first, second, third"), |v| trim(v))
```

This composable approach would let people do whatever modifications they need rather than us needing to augment `split()` to have flags for all of them.

**Comment by jszwedko** [comment]
Closing this since iteration is supported in VRL now and I think that's a better general solution to this than special arguments to `split`.
