### ISSUE TITLE
add `parse_nginx_log` function

### ISSUE THREAD

**Issue by JeanMertz** [vectordotdev/vector#6103]
_split off from https://github.com/timberio/vector/issues/5453#issuecomment-761614440._

We should make parsing default nginx logs as simple as possible by adding a `parse_nginx_log` function similar to our other specialized `parse_*` functions.

The [documentation](https://nginx.org/en/docs/http/ngx_http_log_module.html#log_format) notes the following default access log:

```
log_format combined '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent"';
```

I haven't used Nginx in a while, so someone will have to dig into the specs (e.g. do we need separate functions for access vs error logs), but it should be doable to cover the most common cases.

Some open questions:

- What default log formats are there for Nginx?
- Can we only support those, or can we make the function take optional arguments to support other commonly used nginx log patterns?

**Comment by JeanMertz** [comment]
Some valuable details by @nnz1024 was posted here: https://github.com/timberio/vector/issues/5453#issuecomment-761771964.

Specifically:

> In this case, the main problem is parsing `$upstream_response_time` and `$upstream_addr`. These fields can contain more than one value, according to [documentation](https://nginx.org/en/docs/http/ngx_http_upstream_module.html)
> 
> > keeps the IP address and port, or the path to the UNIX-domain socket of the upstream server. If several servers were contacted during request processing, their addresses are separated by commas, e.g. “192.168.1.1:80, 192.168.1.2:80, unix:/tmp/sock”. If an internal redirect from one server group to another happens, initiated by “X-Accel-Redirect” or error_page, then the server addresses from different groups are separated by colons, e.g. “192.168.1.1:80, 192.168.1.2:80, unix:/tmp/sock : 192.168.10.1:80, 192.168.10.2:80”. If a server cannot be selected, the variable keeps the name of the server group.
> 
> In my case, I can afford not to care about internal redirect, though.
> 
> When you will implement Nginx logs parsing, I think it worth considering to implement `$upstream_*` parser, which can be used with non-standard Nginx log formats, like in my case.
> 
> > Looking at the docs, it appears the default log format is defined as:
> 
> You right, [combined](https://nginx.org/en/docs/http/ngx_http_log_module.html#log_format) is the default format for Nginx HTTP logs. However, when Nginx is used as a reverse proxy, this format is quite insufficient, particularly in regard of upstream information, so it is often overridden by something custom.
> Moreover, when one log destination is used for several virtual hosts (`server` blocks in Nginx terminology), the next problem shows up — `combined` format does not contain anything about virtual host selection.
> 
> So, IMHO, parser for Nginx `combined` will be nice-to-have addition, but definitely is not the number one priority. Parsers for upstream info and for error log format (cannot be redefined) would be much more handy.

**Comment by Alexx-G** [comment]
Another issue to consider is that Nginx Ingress Controller has a different default log format - https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/log-format/

**Comment by JeanMertz** [comment]
Thanks @Alexx-G, that's useful to know.

What I suspect we'll end up with, is something like this:

```rust
parse_nginx_log(.message, format: "nginx_combined")
parse_nginx_log(.message, format: "nginx_error")
parse_nginx_log(.message, format: "kubernetes_upstreaminfo")
parse_nginx_log(.message, format: "$remote_addr - $remote_user [$time_local]")
```

That is, we'll implement a set of known log formats, which you can then provide as the format name, _or_ you provide a custom format in the same format as Nginx (so you should be able to just copy/paste it over from your custom Nginx config), and have it parse the log message.

There's still some open questions here, but this seems to be the most flexible, while still allowing us to make it as easy as possible to parse known default formats.

**Comment by nnz1024** [comment]
Some experience parsing Nginx **error** logs:

Example of error log entry corresponding HTTP 404:
```
2021/01/20 06:39:15 [error] 17755#17755: *3569904 open() "/usr/share/nginx/html/test.php" failed (2: No such file or directory), client: xxx.xxx.xxx.xxx, server: localhost, request: "GET /test.php HTTP/1.1", host: "yyy.yyy.yyy.yyy"
```
Example of log entry corresponding config reload event (`nginx -s reload`):
```
2021/01/20 20:45:18 [notice] 29459#29459: signal process started
```

So, the common parts is date, time (in local TZ), severity, PID#TID and message. Between PID#TID and message also can occur a connection ID, marked by `*` symbol.
Moreover, sometimes message can contain sub-fields with useful information, such as remote client address, Nginx `server { }` name, request string, Nginx host address and referrer URL (absent in examples here).

For parsing such a data, I use following Vector config:
```
[transforms.error_parser]
  type = "regex_parser"
  inputs = ["check_tag.error_log"]

  drop_field = true
  field = "message"
  patterns = ['^(?P<nginx_time>\d+/\d+/\d+ \d+:\d+:\d+) \[(?P<severity>\w+)\] (?P<pid>\d+)#(?P<tid>\d+):(?: \*(?P<connid>\d+))? (?P<message>.*)$']

  types.nginx_time = "timestamp|%Y/%m/%d %T"
  types.pid = "int"
  types.tid = "int"
  types.connid = "int"

[transforms.check_error_fields]
  type = "swimlanes"
  inputs = ["error_parser"]

  lanes.yes.type = "check_fields"
  lanes.yes."message.contains" = "client: "

  lanes.no.type = "check_fields"
  lanes.no."message.not_contains" = "client: "

[transforms.error_fields_parser]
  type = "regex_parser"
  inputs = ["check_error_fields.yes"]

  drop_field = false
  field = "message"
  patterns = ['client: (?P<remote_addr>[^,]*)(?:, server: (?P<server_name>[^,]*))?(?:, request: "(?P<http_method>[A-Za-z]+) (?P<request_uri>/\S+) HTTP/(?P<http_proto>\d+(?:\.\d+)?)")?(?:, upstream: "(?P<upstream>[^"]+)")?(?:, host: "(?P<nginx_host>[^,]+)")?(?:, referrer: "(?P<referrer>[^"]+)")?']
```

In `error_parser` block, the message is separated from the date, time, PID, TID and optional connection ID. Next, `check_error_fields` checks message for `client: ` substring, highly probably indicating the presence of additional sub-fields in message body. If so, the message is sent for additional parsing to `error_fields_parser`. 
Here additional sub-fields will be copied from message string to separate event fields, keeping the main message string untouched.

Finally, after merging `[ "check_error_fields.no", "error_fields_parser"]`, I send it to Elasticsearch. The whole message string allows to easy understand what Nginx wants to tell me, and presence of parsed sub-fields makes search and filtering event in Kibana easier.

I don't think this way is 100% correct and reliable, but it works for me in most cases, and I hope it also can be useful for someone.

**Comment by ThomasLohner** [comment]
nginx error parser does not work in vector 0.14.0:

```
$ parse_nginx_log!("2021/06/17 21:02:55 [notice] 139720#139720: signal process started", "error")
function call error for "parse_nginx_log" at (0:95): failed parsing log line
```

**Comment by jszwedko** [comment]
Thanks @ThomasLohner 

I realized this should have been closed when https://github.com/timberio/vector/pull/6973 was merged so I'll close it now.

Would you mind opening a separate issue for that failure? Are you using a custom error format? If not, could you provide the nginix version?
