### ISSUE TITLE
Tutorial on https://vector.dev/guides/integrate/platforms/docker/clickhouse/ failed

### ISSUE THREAD

**Issue by gangtao** [vectordotdev/vector#6104]
The tutorial on:

https://vector.dev/guides/integrate/platforms/docker/clickhouse/

Here's what went wrong:

an 17 02:58:56.692  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.
Jan 17 02:58:56.693 ERROR vector::topology::builder: Healthcheck: Failed Reason. error=Failed to make HTTP(S) request
Jan 17 02:58:56.693 ERROR source{component_kind="source" component_name=docker_logs component_type=docker_logs}: vector::sources::docker_logs: Listing currently running containers failed. error=error trying to connect: No such file or directory (os error 2)

**Comment by jszwedko** [comment]
Closing since this guide doesn't exist anymore.
