### ISSUE TITLE
Remap syntax highlighter

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#6111]
Now that the remap syntax is solidifying, we should consider a simple syntax highlighter. Given the simplicity of the syntax, this should be relatively straight-forward. [TextMate Language](https://github.com/microsoft/TypeScript-TmLanguage) should be sufficient for all editors.

**Comment by jszwedko** [comment]
Simple Monaco syntax highlighting was added in https://github.com/vectordotdev/vector/pull/15557 .
