### ISSUE TITLE
Add `tls.verify` option

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#6132]
Currently, we have the following `tls` configuration on sources and sinks that support it:

```
  tls.ca_file = "/path/to/certificate_authority.crt" # optional, no default
  tls.crt_file = "/path/to/host_certificate.crt" # optional, no default
  tls.key_file = "/path/to/host_certificate.key" # optional, no default
  tls.key_pass = "${KEY_PASS_ENV_VAR}" # optional, no default
  tls.verify_hostname = true # optional, default
```

It would be nice to additionally have a `tls.verify` option that can be used to disable certificate validation when testing out, or debugging, vector with TLS endpoints. This option would default to `true`.

**Comment by dzirg44** [comment]
looking forward this feature!

**Comment by dannystaple** [comment]
Plus one - since Splunk cloud trials seem to come with a non-optional self-signed cert too (relates to #7775). 

```2021-12-02T11:10:47.974354Z ERROR vector::topology::builder: msg="Healthcheck: Failed Reason." error=Failed to make HTTP(S) request: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1916:: self signed certificate in certificate chain component_kind="sink" component_type="splunk_hec_logs" component_id=splunk component_name=splunk```

**Comment by dannystaple** [comment]
`tls.verify_certificate` is implemented in the Splunk hec log sink, but it is not documented at https://vector.dev/docs/reference/configuration/sinks/splunk_hec_logs/#tls. Found it in the code, and documented at https://vector.dev/docs/reference/configuration/sources/vector/#tls.verify_certificate. Trying it shows it does work.

**Comment by jszwedko** [comment]
Ah, good find @dannystaple . I knew we had `verify_certificate`, but didn't realize that it behaved differently for components that make outbound connections. I'll simply update the docs to reflect that.
