### ISSUE TITLE
New `fatal!` Remap function

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#6157]
Similar to Golang's `logger.fatal` function this would accept an error, log it, and abort the script.

Note, I chose `fatal!` (exclamation) to align with other functions that abort. 

## Example

```
fatal!("Sumthin' ain't right")
```

**Comment by jszwedko** [comment]
This seems very similar to `abort()`. I brought up the idea to @JeanMertz of having `abort()` take an optional message before.

**Comment by JeanMertz** [comment]
> Note, I chose `fatal!` (exclamation) to align with other functions that abort.

Note: if this is a function, you'll _have_ to add the `!`, otherwise VRL wouldn't compile, since this function will be marked as "always fallible".

Of course, we can make it a built-in, but I'd rather not do that if the syntax is the same as a function call.

**Comment by JeanMertz** [comment]
Also note, we do already have `log` which takes an enum of the log level. We could add `fatal` to that list, and have it be a fallible function if that value is provided.

So, you'd do `log(level: "error", "ohoh"), or `log!(level: "fatal", "ohoh"). This would be equivalent to `fatal!` (but I get that we might want to have a separate function that explicitly signals "explicitly want to stop now").

**Comment by JeanMertz** [comment]
We have an `abort` statement now, which does what this issue describes.
