### ISSUE TITLE
Write benches for kafka source and sink

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#6167]
Requires #6165 

Once the framework is in-place, implement benchmarks for the `kafka` source and sink to validate it. We believe this source and sink are relatively complex to mock and so doing so should offer a good example of how to benchmark other source and sink components that require mocking.

**Comment by lukesteensen** [comment]
I'm a little bit unclear on the goal here. The primary purpose of the kafka source and sink is to communicate with kafka, so it seems if we mock that part out then we'll be missing a pretty significant part of its real-world behavior. Are there specific sections of each of these components that we feel both (a) contribute significantly to their real-world performance, and (b) can be separated from kafka itself without compromising the usefulness of the resulting data?

**Comment by jszwedko** [comment]
My thinking here, at least, is that writing criterion benchmarks that use an actual Kafka instance for benching are likely to be noisy enough that they won't be useful for tracking changes in performance. By isolating, and mocking out, the parts that talk to Kafka we are able to tightly control the variables and test our Kafka `source` and `sink` under different parameters. I think the goal here is not to get an idea of real world performance, but just to prevent performance regressions.

Writing vector-test-harness cases, on the other hand, might give us a better picture of "real world performance"; admitting that might still be noisy due to the fact that it'd be bench'ing Kafka as well.

I'm curious what you think though. Thoughts are definitely welcome.

**Comment by lukesteensen** [comment]
> the goal here is not to get an idea of real world performance, but just to prevent performance regressions

This seems like the core of it. I definitely agree that more realistic scenarios have more potential for noise and things would be much easier if they're all in-process criterion benches. But I do think it's important that our goal be to prevent _real world_ performance regressions. More specifically, I worry that too much mocking could lead to us not catching performance regressions that originate in or at the interface with whatever we've mocked out.

A lot of this depends on how we do the mocking. If we do it in a way where we can be confident that the mock is a faithful representation of kafka's behavior and we're still exercising ~all of the relevant sink code, then that'd be fine. That just seems like a difficult thing to accomplish :smile:

**Comment by jszwedko** [comment]
We decided to go a different route with the introduction of the soak test framework.
