### ISSUE TITLE
Provide an interactive VRL tutorial in the VRL REPL

### ISSUE THREAD

**Issue by lucperkins** [vectordotdev/vector#6169]
The VRL REPL as it currently exists offers some nice primitives for providing interactive tutorials, most importantly the ability to load up the REPL with specific event objects. These primitives can be used to provide a tutorial that progressively walks a user through specific VRL scenarios (Syslog, JSON, later on metrics, etc.), asks them to accomplish specific tasks, and provides feedback on their responses.

**Comment by jszwedko** [comment]
Closing since we don't have plans for this.
