### ISSUE TITLE
New `+=` assignment operator in Remap

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#6173]
A `+=` assignment operator would help simplify Remap scripts:

```js
. += parse_json!(.message)
```

This would:

- [ ] Perform in-place addition for numbers.
- [ ] Perform in-place appending for arrays and array items.
- [ ] Shallow merge objects.
- [ ] Concatenate strings.
- [ ] Error for booleans and timestamps.

**Comment by JeanMertz** [comment]
This is an interesting proposal (in that it has some added properties that are nice to have in the context of observability data).

I would add that whatever we make add-assignment do, should mirror the regular assignment approach:

```rust
. = . + parse_json!(.message)
```

**Comment by JeanMertz** [comment]
Another thought we had on Discord:

Add support for `|=` compound assignment to mean "merge fields".

E.g.:

```rust
. = { "foo": "bar" }
. |= { "baz": true }

. == { "foo": "bar", "baz": true }
```

The same could be achieved with:

```rust
. = { "foo": "bar" } | { "baz": true }
```

This would also help with the issue described in #6171.
