### ISSUE TITLE
Tutorial on ECS failed

### ISSUE THREAD

**Issue by twk** [vectordotdev/vector#6189]
I might be completely misunderstanding something, but the tutorial at https://vector.dev/guides/integrate/sources/aws_ecs_metrics/ doesn't make a ton of sense to me. Where exactly am I installing vector in step 1?  Don't I need to get this into my container somehow?

**Comment by jszwedko** [comment]
Hi @twk ,

Agreed, those instructions are missing a bit of detail in this case. The `aws_ecs_metrics` source can be used to pull metrics per ECS task so you'd want to deploy vector as part of your ECS task definition for each task you'd like to monitor.

**Comment by jszwedko** [comment]
Closing since the installation instructions were removed from the source pages.
