### ISSUE TITLE
Abilitly to transform metrics to the influxdb text protocol

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#6190]
Similar to https://github.com/timberio/vector/issues/6100.

A user requested the ability to transform metrics into the influxdb line protocol to be forwarded. This could relate to the idea in #6179 in that it could be a custom remap script that users could use rather than implementing a specific transform or function for it.

**Comment by otisg** [comment]
@jszwedko #6100 is about accepting as input (source) metrics emitted in the influx line protocol.  Is this ticket 6190 about "the other side", meaning transforming metrics V sends *to* influx line protocol - an influx line protocol source, so to speak?

**Comment by jszwedko** [comment]
@otisg Ah, you are right, looking at the user's config again, it does seem like there are shipping to influxdb. I'll verify that they couldn't just use that sink. I thought they were intending to store the data elsewhere, but in that format.

**Comment by jambu** [comment]
From the documentation it is not clear if the following is possible, asking here for confirmation

Influxdb line protocol from telegraf ->  http source in vector -> Influxdb_metrics sink in vector -> Influxdb 
Or any transform is required inbetween to enable this ?

**Comment by jszwedko** [comment]
Hi @jambu ! I think you'll have better luck using the statsd or another output from telegraf to feed the metrics into Vector, but otherwise that seems like it should work. The `http` source in Vector requires a very specific format to decode metrics. Alternatively you may be able to feed them in as logs to Vector and transform them using the `log_to_metric` transform.

**Comment by juvenn** [comment]
Probably if there are `parse_influx_line`, `parse_statsd_line` functions, it would be relatively easy to accept those from any source? And coupled with `log_to_metrics`, it would eliminate the need of telegraf in the middle?

> transform metrics into the influxdb line protocol to be forwarded.

FYI,  I think `influxdb_log` can do that already. For any metrics, transform it with `metrics_to_log`, then annotate the log with any field or tags you want before sinking into influxdb.

**Comment by george-vieira** [comment]
I have a firewall and other platforms that (for whatever reason) only have influxdb as a target to send metrics and/logs. just as we have prometheus remote write source endpoint, would be good to great inflxudb too so I can natively send directly to vector.

**Comment by jszwedko** [comment]
Closing in favor of https://github.com/vectordotdev/vector/issues/11337
