### ISSUE TITLE
Installing docs reference unused $FEATURES environment variable

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#6203]
The installation docs reference using `FEATURES=something make build` to build with reduced features (https://github.com/timberio/vector/blob/82f7fefe2aca0269cf07a56d0624e67df29b59ac/docs/manual/setup/installation/manual/from-source.md#L91), however only `scripts/build.sh` actually references `$FEATURES`, and the `Makefile` does not reference that script.

This needs to be resolved by either adding this feature to the `Makefile` or by eliminating references to `$FEATURES` in the installation documentation.

Discord: https://discord.com/channels/742820443487993987/746070591097798688/802298492081012766

**Comment by jszwedko** [comment]
Closing since the `Makefile` does seem to reference `FEATURES` now.
