### ISSUE TITLE
Investigate failed `exclude_containers` test

### ISSUE THREAD

**Issue by ktff** [vectordotdev/vector#6215]
https://github.com/timberio/vector/runs/1754763872

PR merged some time before it #5998 may be the cause.

Going by the logs, it's a race in Docker where it can close the event stream before we get the event that the container has died, 
as a consequence we again open the event stream for the container. Now, in the second stream we probably got the old log, that we got the first time, but this log should have been filtered out so there is maybe bug in that?

**Comment by jszwedko** [comment]
Closing since we haven't seen this test fail recently.
