### ISSUE TITLE
Versioned Vector configuraton

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#6231]
I could have sworn we had an older issue for this, but we need a strategy for supporting, and upgrading, legacy Vector configurations. As expected, the pre-1.0 phase of Vector has introduced a lot of changes to our configuration that have, over time, accumulated into a mess of aliases and deprecation warnings that are scattered throughout the codebase. This makes it difficult to expire deprecations and maintain an update-to-date schema for our configuration.

## Requirements

- [ ] Introduce a configuration translation later that would decouple the exposed Vector configuration from the underlying components.
- [ ] Provide the ability to specify a `version` attribute that would seamlessly upgrade the user or error with detailed upgrade instructions.
- [ ] Audit existing aliases and deprecations to see which ones we can remove and simplify the code.
- [ ] Is there a way we can align this data with our cue data (nice to have and can be separated into another issue)

**Comment by jszwedko** [comment]
Closing since I don't think we have any intention of doing this at this point, but we can revisit if we find more need.
