### ISSUE TITLE
Update Vector's template syntax to use the same Remap path syntax

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#6253]
In #3836 we decided _against_ using the full Remap language for templating. This was the right decision as it avoided embedding complicated Remap programs just to derive a static value. This makes Vector configs easier to read and manage. Instead, users are forced to shift that logic upstream into a `remap` transform.

As such, we've decided to retain our simple templating syntax (ex: `{{ field_name }}`. If we're going to keep this syntax we should unify the path syntax so users don't have to learn two different syntaxes. In other words:

- [ ] `{{ field_name}}` should become `{{ .field_name }}`
- [ ] `{{ .array[0] }}` should be supported.
- [ ] `{{ .parent.(child1 | child2).value }}` should be supported.
- [ ] And all of the other Remap path syntax capabilities.

**Comment by jszwedko** [comment]
Notably this also affects transforms like `log_to_metric` where it expects the template-style look-up strings rather than the VRL look-up strings.

**Comment by fuchsnj** [comment]
There were several PRs migrating the template syntax to the new "lookup v2" code.
All of the features above are now supported.

https://github.com/vectordotdev/vector/pull/13156 was the last one needed.
