### ISSUE TITLE
What all are the allowed values for "field" under transforms

### ISSUE THREAD

**Issue by ansarpalakottal** [vectordotdev/vector#6276]
My log file contains line by line entries and I need to take each line to parse. What will be the exact configuration for the same ?

**Comment by j-land** [comment]
This doc page describes how to add fields to log events via the `add_fields` transform: https://vector.dev/docs/reference/transforms/add_fields/

The types of values that may be provided are detailed here: https://vector.dev/docs/about/under-the-hood/architecture/data-model/log/#types

**Comment by jszwedko** [comment]
Closing since this question lacks detail. Feel free to reopen with additional details though! Apologies for the delay in response on this one.
