### ISSUE TITLE
Allow wasm to be used with metrics

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#6308]
Currently the `wasm` transform only supports logs, but it could be extended to support metrics as well. We just have to codify a representation of the metrics to be passed back and forth. Naively, we could just use the same encoding as we use with the `console` sink when `encoding.codec = "json"` is used. This would become part of the contract though.

Requested by user in discord: https://discord.com/channels/742820443487993987/746070591097798688/805880448559349781

**Comment by binarylogic** [comment]
Just noting that the `metric_to_log` transform could be used to work around this limitation in the interim.

**Comment by jszwedko** [comment]
@binarylogic true, but I think users might like to emit metrics as well. I don't think there is an easy way to do that right now. I could see updating `log_to_metric` to be able to just handle raw translations back from `log_to_metric`.

**Comment by jszwedko** [comment]
Closing since we dropped wasm support #8036
