### ISSUE TITLE
Coercer timestamp format docs are misrendered

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#6339]
https://vector.dev/docs/reference/transforms/coercer/#timestamp-formats

![2021-02-03-155025_840x634_scrot](https://user-images.githubusercontent.com/316880/106800980-8aa16700-6637-11eb-8e9b-cc2c0ec85897.png)

**Comment by tshepang** [comment]
this gives a 404

**Comment by spencergilbert** [comment]
👍 `coercer` has been removed.
