### ISSUE TITLE
remap `to_timestamp` ignores fractional seconds for floats

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#6399]
https://github.com/timberio/vector/blob/2000686a0d3b8671026ec87e762e9e6964758e21/lib/remap-functions/src/to_timestamp.rs#L57 should take into account the fractional seconds for floats.

Additionally, we should document this support in the docs. Currently it does not document support for floats:

https://github.com/timberio/vector/blob/2000686a0d3b8671026ec87e762e9e6964758e21/docs/reference/remap/functions/to_timestamp.cue#L12

**Comment by mehta-ankit** [comment]
This would be great help if to_timestamp() can handle epoch timestamps with ms (13 digits)

**Comment by jszwedko** [comment]
This was actually fixed in https://github.com/timberio/vector/commit/36054bd67
