### ISSUE TITLE
regex_parser: ability to suppress warnings when regex fails

### ISSUE THREAD

**Issue by jeromekleinen** [vectordotdev/vector#6411]
### Current Vector Version

```
version="0.11.1" git_version="v0.11.1" released="Thu, 17 Dec 2020 17:03:52 +0000" arch="x86_64"
alpine based docker image
```

### Use-cases

I often use a regex with capture groups to try to extract fields from log lines, but not expecting the regex to always match. Afterwards I check the existence and/or value of a captured group to determine further processing of logs. Typically I use this with drop_failed = false and drop_field = false. Currently this causes periodic regex warnings in the logs, despite this being expected in my case. However, I agree that the default should remain to log warnings on regex match failures.

### Attempted Solutions

I don't think there is anything I can try to change this behavior without suppressing all warnings.

### Proposal

Add an option to the regex_parser transform to suppress warnings when the regex does not match.

### References

- #397 added these warnings

**Comment by jszwedko** [comment]
Closing this since regex parsing has moved to VRL which allows users to decide what to do with failures.
