### ISSUE TITLE
Enhancement Request - HTTP sink - retryable codes

### ISSUE THREAD

**Issue by ryn9** [vectordotdev/vector#6420]
### Current Vector Version

```
vector 0.11.1 (v0.11.1 x86_64-unknown-linux-musl 2020-12-17)
```

### Use-cases

For the HTTP sink, it would be nice for Vector to support configurable retry logic based off HTTP codes.
Per the docs the logic for this is currently static.

```
Vector will retry failed requests (status == 429, >= 500, and != 501). Other responses will not be retried. You can control the number of retry attempts and backoff rate with the request.retry_attempts and request.retry_backoff_secs options.
```

### Attempted Solutions

N/A

### Proposal

Add logic akin to Logstash's retryable_codes for http output
https://www.elastic.co/guide/en/logstash/current/plugins-outputs-http.html#plugins-outputs-http-retryable_codes

### References

https://vector.dev/docs/reference/sinks/http/#retry-policy

**Comment by jszwedko** [comment]
Rolling this into https://github.com/vectordotdev/vector/issues/10870
