### ISSUE TITLE
Regex Parser / Key Value Parser - Enhancement 

### ISSUE THREAD

**Issue by modularinput** [vectordotdev/vector#6451]
### Current Vector Version

```
Vector 0.12.0 (g0793e59 x86_64-unknown-linux-musl 2021-02-11)
```

### Use-cases

I would like to be able to write regular expressions with assertions where the capture groups dynamically get assigned to keys or values based on the capture group number. This request is specifically needed to handle ArcSight Common Event Format (CEF) data, but can be used outside of this use case to handle more advanced key value extractions.     

`CEF Example`

```
CEF:0|Netwitness|Informer|1.6|{name}|{name}|Medium | externalId={#sessionid} proto={#ip.proto} categorySignificance=/Normal Check categoryBehavior=/Authentication/Verify categoryDeviceGroup=/OS categoryOutcome=/Attempted Login categoryObject=/Host/Application/Service act={#action} deviceDirection=0 shost={#ip.host} src={#ip.src} spt={#tcp.srcport} dhost={#ip.host} dst={#ip.dst} dport={#tcp.dstport} duser={#username} dproc=27444 fileType=security passed cs1={#did} cs2={#password} cs3=4 cs4=5 cn1={#rid} cn2=0 cn3=0
```

Values are not quoted, and pairs are delimited with space.   

### Attempted Solutions

Reviewed the current capabilities available via the `key_value_parser` and `regex_parser` and found they could not handle my use case. 

- `key_value_parser` seem to handle well delimited keys and values.
- `regex_parser` does not seem to support dynamic assignment via capture groups.  

Checked with @jszwedko on the Vector discord support channel to make sure I was not overlooking something.   

### Proposal

Splunk has a useful way to do this via it's transforms that might be helpful as a reference. This example would capture all keys and values that matched in an event.  

Review 

[`FORMAT = `](https://docs.splunk.com/Documentation/Splunk/8.1.2/Admin/Transformsconf)

```
[transforms.cef_parser]
REGEX = ((?:\w+(?:\.[^\.=\s\|\\\[\]]+)*(?:\[[0-9]+\])?(?==)))=((?:\S|\s++(?!(?:\w+(?:\.[^\.=\s\|\\\[\]]+)*(?:\[[0-9]+\])?(?==))=))*)
FORMAT = $1::$2
```

[logstash-codec-cef](https://github.com/logstash-plugins/logstash-codec-cef/blob/master/lib/logstash/codecs/cef.rb)

### References

Unknown.

**Comment by ktff** [comment]
An alternative solution would be to add `parse_cef` VRL function which would accept a string and output parsed object with fields from header: 
* `version`
* `device_vendor`
* `device_product`
* `device_version`
* `signature_id`
* `name` 
* `severity`

and key values from extension. The function would be fallible and all returned values would be strings. 

cc @jszwedko

**Comment by jszwedko** [comment]
👍 I think having a parser for CEF data makes sense.
