### ISSUE TITLE
Allow the `journald` source to collect kernel/dmesg logs

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#6508]
See https://github.com/timberio/vector/issues/3680#issuecomment-769522159. I'm wondering if this is best served with a separate source? Or, should we do both?

**Comment by bruceg** [comment]
Based on what I'm seeing on my own system, the `journald` source already gets kernel messages, it just ends up needing a filter transform after to drop everything but kernel messages. So this is more a matter of moving that kind of filtering into the source with a simple option that would set the appropriate `journalctl` command line. I don't think this is worth a separate source just for kernel messages through `journald`.

A separate source *just* pulling out kernel messages with `dmesg` (or equivalent on non-Linux systems) is probably still valuable for systems where `journald` is not being used or access to the journal files is difficult, but that is tracked by #3680.

**Comment by jszwedko** [comment]
Closing since this is easily achievable by filtering from the `journald` source.

**Comment by BernhardCW** [comment]
just in case somebody needs a copy-paste-snippet:

```
sources:
  systemd_logs_kernel:
    type: journald
    include_matches:
      SYSLOG_FACILITY: 
        - "0"
```

SYSLOG_FACILITY = 0 -> kernel
https://datatracker.ietf.org/doc/html/rfc5424#section-6.2.1
