### ISSUE TITLE
Optimize disk buffers

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#6512]
As Vector's aggregator role grows in popularity it's important that our disk buffers perform optimally. This is necessary for use cases where Vector cannot apply backpressure upstream and the customer does not want to take on the burden of hosting a Kafka cluster. Vector's disk buffers should be a simpler middle ground that improves durability but not necessarily to the level of Kafka.

## Goals

To bring Vector's disk buffers up to an acceptable industry standard for disk I/O.

**Comment by jszwedko** [comment]
Closing as covered by the [disk v2 project](https://github.com/vectordotdev/vector/issues/9476).
