### ISSUE TITLE
Implement event metadata

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#6516]
Until now Vector has not had a concept of event metadata. For external use cases, we encouraged users to use plain-old keys to stash their metadata and then exclude those keys with the sink levelencode.except_fields` option. But internal use cases are proving the need for event metadata, like end-to-end acknowledgment. This epic focuses on laying the foundation for supporting event metadata and delegating the actual structure to each feature that needs it.

**Comment by jszwedko** [comment]
I think https://github.com/timberio/vector/issues/7308 is related to this. That is, letting users stash keys there too that aren't part of the event. Similar feature in Logstash: https://www.elastic.co/blog/logstash-metadata

**Comment by spencergilbert** [comment]
Brought up in discord (and subsequent issue #8809) again

**Comment by shamil** [comment]
This is very useful feature, and as someone who comes from `logstash` I miss this a lot.

**Comment by jszwedko** [comment]
We have started implementing this as part of https://github.com/vectordotdev/vector/issues/12187. The basics are in place. I'd expect us to officially document and announce it in the next few months.

**Comment by jszwedko** [comment]
Closing this as covered by https://github.com/vectordotdev/vector/issues/12187
