### ISSUE TITLE
Improve the `vector validate` subcommand

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#6521]
The `vector validate` subcommand serves to catch configuration problems before they're applied. This helps operators to seamlessly apply configuration changes with confidence. Currently, this command only catches simple compile-time configuration errors, like syntax errors, invalid component ids, and failing healthchecks, but it does not catch runtime problems that could be just as problematic. Such as severe performance degradations, large increases in data volume, mistakes in processing data, and more.

This epic attempts to raise the confidence in applying a new Vector configuration by covering the runtime errors so that operators are not suprised.

**Comment by jszwedko** [comment]
Closing since this needs more specific product requirements before we'd be able to work on it.
