### ISSUE TITLE
RFC for improving the `vector validate` command

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#6523]
#6521 kicks off a project to improve the `vector validate` subcommand. The intent is to catch runtime errors that could result in pipeline instability _before_ applying the config. This is especially useful for remote configuration, where an operator might not be able to easily roll back changes. An operator should be able to "test" changes before they are applied. This should catch things like:

1. Performance regressions (throughput, memory, etc).
2. Increases in data volume.
3. Increases in field cardinality.
4. Data processing errors.
5. Anything else that could cause problems after applying the new configuration.

It's likely that this will be more like a report with configurable thresholds, allowing the user to decide if they should proceed. In general, the purpose of this task is to create an RFC that covers all of these aspects, outlines and proposes the work necessary for operators to reliably and safely apply configuration changes.

**Comment by jszwedko** [comment]
Closing this since this work wasn't taken up at the time.
