### ISSUE TITLE
Rethink retry strategies

### ISSUE THREAD

**Issue by lukesteensen** [vectordotdev/vector#655]
# Background

There are a few layers of issues that #647 helped to uncover.

## Not enough errors were retriable

This is the lowest level and most direct cause of the issue. We should have been retrying connection refused errors but we were not. This specific instance is addressed in #651.
 
## Error whitelists make us eager to drop data

One step higher, the idea of needing to whitelist errors that we want to retry has put us in a position where we default to dropping data when something goes wrong. This originally stemmed from a desire to ensure we don't "double write", but looking back seems overly conservative. In the context of logging data, double writes are likely preferable to dropped writes in most cases. And in practice, there are only a limited number of error types that would actually lead to double writes in the first place. 

## Retriable isn't a very useful distinction

At the level above that, we should consider whether retriable vs not is the most useful distinction we can make. If we split all errors into two broad categories of environmental vs data-specific, theoretically all environmental errors could resolve on retry, while no data-specific errors would. In other words, we could probably retry every error other than cases where the problem is with the specific data being written (in which case it must be dropped to make progress). Given that there are not often data validation-style errors like this with log data, non-retriable errors become much less of a concern when taking this view.

It seems then like the more useful distinction is between errors that we don't expect to resolve without operator intervention (e.g. bad credentials) and those that we do (e.g. connection reset). And if that's the distinction we want to represent, what difference should there be in how we respond to those two cases? Both can be retried, so we could simply always retry. On the other hand it may be surprising to users if these two types of errors result in the same behavior. There may be an expectation that error likely requiring operator intervention be "louder" than other errors. Being "loud" could mean more logging, aborting and restarting the component where the error occurred, or aborting the whole vector process. 

# Proposal

## Short term

Instead of a whitelist of error types we will retry, we should move to a blacklist of error types that we strongly believe are related to a specific data item and should not be retried. For many sinks there may be no such error types.

In addition, we should add extra logging around errors that are highly likely to require operator intervention. Otherwise, these errors will follow the normal retry path.

## Longer term

Depending on our experience with the short term solutions, we can evaluate making some of this behavior configurable. For example, some users may wish to terminate the process if we receive an invalid credentials error.

We can also revisit the tradeoff between double writes and lost writes, potentially allowing users to configure behavior per-sink that favors one or the other.

**Comment by jszwedko** [comment]
Missed this when creating https://github.com/vectordotdev/vector/issues/10870 . I'll close it to roll it into that issue.
