### ISSUE TITLE
Clickhouse sink should error on start-up for invalid endpoint value

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#6559]
Reported by a user in discord: https://discord.com/channels/742820443487993987/746070591097798688/814503410451742760

Vector starts up, but the sink fails because it cannot parse the endpoint value as a URL. Vector should consider this a fatal error.

![unknown](https://user-images.githubusercontent.com/316880/109167686-675c6a00-7754-11eb-9027-e5f6f3bf9746.png)

**Comment by zamazan4ik** [comment]
@jszwedko What is the current behaviour for other sinks with a wrong endpoint? I see at least two possible ways, how to fix it:
* Perform more strict URI validity check (possibly during reading the value from a config)
* Fill missing URI parts with some reasonable defaults

As an endpoint Vector uses `UriSerde` struct which already has `with_default_parts` method. If we apply to the provided URI from the config, it starts to work like a charm (modified the corresponding source code locally and tested it). `UriSerde` is designed to represent not only fully-defined URIs but and others too (with some missing parts).

From my perspective, the second way with filling missing parts with reasonable defaults should be preferred here.

**Comment by jszwedko** [comment]
Hi @zamazan4ik !

I think the sink should try to parse the configuration option into a `Uri` at configuration load time. It can default unknown parts as you suggest if there are sensible defaults.

**Comment by zamazan4ik** [comment]
> I think the sink should try to parse the configuration option into a Uri at configuration load time

I have just grepped Vector sources: `UriSerde` is used as a URI representation in `Config` struct in many other places. So you suggest rework all other similar cases?

**Comment by jszwedko** [comment]
> 

Aha, I see. I misread the earlier comment. I think calling`with_default_parts` for `clickhouse` sink makes sense. I'm wondering if the deserialization implementation for `UriSerde` shouldn't just call that 🤔

**Comment by zamazan4ik** [comment]
@jszwedko I have investigated the codebase a little bit. So I would say now - "It depends". E.g. in Papertrail sink, `UriSerde` is also used for the `endpoint` configuration. However, it establishes just a TCP connection, so it don't need a `http://` prefix in URI.

In other words, I don't think that we need to change a `UriSerde` default behaviour. And I suggest just fix all endpoints usages, where it need to be fixed. Regarding `clickhouse` sink, I suggest just use `with_default_parts` in rights places or introduce some internal `Uri` variable, which will be once filled after the configuration with default parts (if it could be done easily).

What do you think?
