### ISSUE TITLE
Tutorial on https://vector.dev/guides/integrate/platforms/docker/ failed

### ISSUE THREAD

**Issue by gdsmith** [vectordotdev/vector#6567]
The tutorial on:

https://vector.dev/guides/integrate/platforms/docker/

Here's what went wrong:

Vector failed to start, you get the error output
```
Feb 26 07:38:46.589 ERROR source{component_kind="source" component_name=logs component_type=docker_logs}: vector::sources::docker_logs: Listing currently running containers failed. error=error trying to connect: No such file or directory (os error 2)
```

I needed to mount the `docker.sock` in order to get it to stay up:

```
-v /var/run/docker.sock:/var/run/docker.sock
```

**Comment by jszwedko** [comment]
Hi @gdsmith, that tutorial is meant to be for running vector outside of docker, where you wouldn't need to mount the socket, but I admit it'd probably be common for users to be running vector in docker when looking at that page. I'll leave this open to improve that documentation.

**Comment by jszwedko** [comment]
Closing since this page doesn't exist anymore.
