### ISSUE TITLE
Forbid assigning a non-object to root in VRL

### ISSUE THREAD

**Issue by lucperkins** [vectordotdev/vector#6596]
It's currently possible to assign a non-object to the root object in VRL:

```ruby
$ . = "foo"
"foo"

$ . = {}
target must be a valid object, got "string": "foo"
```

The problem is that there's no way out of this. The root becomes "invalid" which means that you can't assign anything else to it without triggering an error. As assigning a non-object to the root doesn't serve any real purpose, it should be forbidden and emit a nice, helpful error message.

As far as I can tell this is only an issue in environments like the REPL, the CLI tutorial, and the (future) web interface. But in my view that should be reason enough to fix it.

**Comment by jszwedko** [comment]
Closing since we do plan to allow this now.
