### ISSUE TITLE
Ability of file-source to publish line offset as part of the log event

### ISSUE THREAD

**Issue by ashrithr** [vectordotdev/vector#6633]
Currently file-source does not publish line offset (log event starting position in file), which could be useful for use-cases where files have to be reconstructed for audit purposes. Filebeat does expose this via `file.offset` as part of their [event](https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields-log.html).

**Comment by ashrithr** [comment]
@jszwedko

**Comment by ypid-geberit** [comment]
There is another, in my eyes more important, reason to have the `file.offset` and that is to use it to "fake" a more precise timestamp than the resolution of the origin (in the case of syslog). For example with https://www.elastic.co/guide/en/elasticsearch/reference/current/date_nanos.html. Consider this example:

```
Jan 25 04:38:06 info - Link up on P4.
Jan 25 04:38:06 info - Link down on P4.
```

Here the order is only determinate by the time the event was received.

**Comment by binarylogic** [comment]
Thanks @ypid-geberit, we will do this as part of our `file` source improvements work.

**Comment by atibdialpad** [comment]
Was this done ?

**Comment by jszwedko** [comment]
@atibdialpad not yet! Happy to accept PRs for this as it isn't on our near term roadmap.

**Comment by atibdialpad** [comment]
I was looking at the checkpointing file :  
```
{"version":"1","checkpoints":[{"fingerprint":{"first_lines_checksum":9968418820536520945},"position":578849,"modified":"2022-07-02T04:18:52.411152331Z"}]}
```
the 'position' seems to be the file offset right ? I can check if there is an easy way to expose this to the event. Probably like a metadata ?

**Comment by sproberts92** [comment]
I got this working a little while ago, have been meaning to put up a PR for it. Have opened one now.

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/13422
