### ISSUE TITLE
Allow fractions of seconds in rate_limit_secs parameter of VRL log function

### ISSUE THREAD

**Issue by pablosichert** [vectordotdev/vector#6643]
Being able to set the `rate_limit_secs` parameter in VRL's `log` function to e.g. `0.1s` or `1.5s` would be useful.

Some additional hints for the implementation taken from https://github.com/timberio/vector/pull/6622#discussion_r588203258:

> The internal rate limiting logic only handles seconds right now. Interestingly it looks like tracing doesn't have support for passing floats around (https://docs.rs/tracing/0.1.25/tracing/trait.Value.html) so we'd need to adjust it to be something like internal_rate_limit_ms to allow finer granularity. Here it could still be represented as a float though and just marshalled (whenever ms support would be added).

**Comment by binarylogic** [comment]
@pablosichert was this requested by a user? I'm curious why 1.5 would be necessary instead of 1?

**Comment by pablosichert** [comment]
You're right that `1.5s` is a bit contrived (other than I don't see a reason why it shouldn't be allowed). I can see a need for `0.1s` or `0.5s`, but also happy to wait for users to share their use cases 😄

**Comment by jszwedko** [comment]
Closing due to lack of demand. Please leave a comment if this feature would be interesting to you.
