### ISSUE TITLE
Loadbalancing vector aggregators

### ISSUE THREAD

**Issue by amitde69** [vectordotdev/vector#6653]
### Use-cases

I run vector on kubernetes I want to use vector-aggregator to relieve load off of the vector-agents because I cant allocate a lot of CPU to the daemonset.

I have a daemonset of vector-agents collecting logs from k8s nodes and sending them with vector type sink to aggregator behind k8s service. 

I would expect to be able to horizontally scale the vector-aggregators to fit the required CPU usage but it seems like the agents dont load balance the traffic.
once the agents start up they create a connection to a specific aggregator and dont reconnect to another one again unless restarted.

### Attempted Solutions
- create a fixed amount of many aggregators without autoscale. but this doesnt exactly solve the problem since the load balancing of the traffic is depended on the order in which the agents were started.
- create aggregator group per specific usage (logs, metrics, large/small log amount pool etc )
- split the logs/metrics to 3 transforms and send them to specific aggregators with a headless service.

### Proposal
Im not sure exactly how the traffic is handled currently between the vector sink and the vector source but I would expect it handle load balancing correctly, or maybe use http protocol here.

Thanks, if anybody has a suggestion on how to implement the use case with existing features let me know.

**Comment by vladimirfx** [comment]
Network load balancing implemented by k8s:
https://kubernetes.io/docs/concepts/services-networking/service/#proxy-mode-ipvs

I've suggested you use `lc` mode to balance aggregators.

One question to vector team: It is possible to set agent-aggregator connection TTL?

It is useful to rebalance connection from already running agents to newly created aggregators. Reconnection should be done with DNS resolution (not required for IPVS mode but useful for DNS balancing).

As workaround agents can be restarted for rebalancing.

**Comment by amitde69** [comment]
Hey, thanks for the quick reply.
Its not very helpful since Im running on EKS and ipvs mode is not currently natively supported.

Yes I can restart the agents for rebalancing but once the system scales up, the balancing is going out of whack.

**Comment by amanmahajan26** [comment]
Hi @amitde69 , did you find a solution to this problem?

**Comment by jszwedko** [comment]
Closing since the newer version of the `vector` source/sink protocol (`version = "2"`) uses gRPC which can be load balanced using an HTTP load balancer.
