### ISSUE TITLE
New `javascript` transform

### ISSUE THREAD

**Issue by a-rodin** [vectordotdev/vector#667]
Recently Fabrice Bellard, creator of QEMU and FFMPEG, released [QuickJS](https://bellard.org/quickjs/) embeddable JavaScript engine.

It is MIT licensed and its compiled size is just a few hundred kilobytes.

So it might be a good idea to add `javascript` transform, similar to `lua` transform.

**Comment by zsherman** [comment]
Wow, this would be really useful from my perspective.

**Comment by afoninsky** [comment]
Guys, can you specify what's the status of this pull request? Look forward to seeing this feature in the next release. Thank you.

**Comment by jszwedko** [comment]
Hi all!

Vector's focus is on improving VRL to handle all data transformation needs. We want to avoid having a lot of transforms that are similar to remap but use a different language, so we won't be prioritizing this. If there is anything that you need that VRL doesn't support, we would welcome an issue for it. There is the potential that we will add support for custom transforms using WASM or some other mechanism so this could also be supported that way.

Thanks for everyone's thoughts here!
