### ISSUE TITLE
Aggegeration of Statsd metrics

### ISSUE THREAD

**Issue by volfco** [vectordotdev/vector#676]
It would be very awesome if you could selectively enable aggegeration of statsd metrics on a per metric type basis. 

So, you can say "aggegerate gauges on a 5/10s interval" before they are sent.

**Comment by binarylogic** [comment]
Thanks @volfco, we're actively working through a bunch of core metrics features and will add this to our list.

**Comment by volfco** [comment]
@binarylogic Awesome. If I get bandwidth at work I'll help work on this. This actively aligns with a project I'm going to be working on. So win win all around!

I'll drop some more feature requests surrounding this as well in a bit.

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/7846
