### ISSUE TITLE
Use dedicated structs for intermediate values in sinks

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#6782]
Several sinks use `serde_json::Value` as an intermediate value for the encoded event (`type HttpSink::Input`). In some cases, this value has fixed fields which could be represented by a struct to avoid the overhead of creating and destroying a dynamic hash table. We should investigate the feasibility of using a custom struct for each such sink.

**Comment by lukesteensen** [comment]
@bruceg do you think there's a benefit here beyond performance? If it cleans up the code then I think we can go ahead and do it, but if it's performance-only or even makes the code a little less ergonomic then I'd rather wait until it shows up as meaningful in our profiling.

**Comment by jszwedko** [comment]
Agreed with Luke here. We should let profiling guide this.
