### ISSUE TITLE
Release build artifacts with wasm

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#6812]
User in discord was looking for a docker image with wasm already included: https://discord.com/channels/742820443487993987/746070591097798688/822174608626286632

I feel like our WASM integration has been around long enough that we may want to consider either publishing separate artifacts with it enabled or just add it to the default set of features. Not doing so certainly puts a high bar for those who want to try out writing a WASM module for vector. We can still mark it as experimental for now.

Notably we'll probably want to solve https://github.com/timberio/vector/issues/5106 before including it in the default featureset.

**Comment by binarylogic** [comment]
The biggest blocker was the binary size, and the processing speed was not nearly as fast as we'd like it do be due to serialization at the FFI (if I recall properly).

**Comment by jszwedko** [comment]
Yeah, it's definitely slow, but functional 😄 We can still clearly label it as experimental so that people are aware the FFI might change.

**Comment by jszwedko** [comment]
Closing since the `wasm` transform was removed.
