### ISSUE TITLE
Write up another WASM example using a different language

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#6813]
A discord user was specifically looking for an example in Go: https://discord.com/channels/742820443487993987/746070591097798688/822175978246635590

But it prompted me to realize that we provide Rust helpers (the `vector-wasm` crate) for writing Rust Vector WASM modules which may make it less clear on how to do it with another language. I think implementing in at least one more language will allow us to make sure the documentation is generalized.

**Comment by afoninsky** [comment]
I assume some sort of SDK is required in order to access vector-specific things like logs/metrics.
As it was done with envoy: https://github.com/tetratelabs/proxy-wasm-go-sdk

**Comment by jszwedko** [comment]
My knowledge of WASM is still limited at this point, but I think it'd be possible to write a vector integration in another language now, it would just be difficult without an SDK to help. You can see the interface Vector exposes here: https://github.com/timberio/vector/blob/4702571ad410263f27fc7b2c2e30e8fb70dad144/lib/vector-wasm/src/hostcall.rs#L51-L59

**Comment by jszwedko** [comment]
Closing since we dropped wasm support #8036
