### ISSUE TITLE
Allow metrics to be sent and received with `http` source and sink

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#6825]
I thought we had an issue for this already, but I couldn't find it.

A user in discord requested the ability to send metrics through the `http` sink: https://discord.com/channels/742820443487993987/746070591097798688/822512060624666684

Ideally the `http` source would be able to receive metrics sent this way as well. This would allow users to send events between vector instances over HTTP though we should still push for people to use the `vector` source and sink when possible.

They were able to use `metric_to_log`, but this seems like a suboptimal workaround.

**Comment by binarylogic** [comment]
I think the correct solution here is codecs. The ability to specify a `prometheus`, `influx`, etc codec for metrics formats would solve this.

**Comment by tobz** [comment]
This should be addressed by #9930, so gonna close for now.
