### ISSUE TITLE
Data source: AWS SQS

### ISSUE THREAD

**Issue by pachico** [vectordotdev/vector#6830]
### Current Vector Version

At the moment it is possible to sink data in AWS SQS but there is no data source for that.
Being SQS a queue simple message queue system, it plays nicely with applications like Vector. And being a fully managed service, it's quite convenient for messages that require reliability. In addition, it's fully integrated with the entire AWS ecosystem.

### Use-cases

My use cases are:
* fallback logging target for applications when primary (TCP socket) is not available
* AWS service events

**Comment by jszwedko** [comment]
Requested in discord: https://discord.com/channels/742820443487993987/746076283074773150/851261369402785823

**Comment by ocrlgv** [comment]
my use case was for metrics though but I don't see why not have anything which is a stream/queue (kinesis data stream/firehose, SQS) handle both. I need metrics queued for reasons that our billing relies on metrics whether or not they are delayed due to an network or edge outage, etc.

**Comment by benzaita** [comment]
Some additional points and expectations:

1. will it be possible to configure the parallelism of this source? Like how many workers are pulling batches of messages?
2. When will this source acknowledge (delete) messages from the queue? Ideally it will be when the messages has completed processing in vector (by all sinks)?
3. Will this source emit metrics such as processing latency (from reading a message to deleting it)?
