### ISSUE TITLE
Reduce Allocator Pressure

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#6831]
We understand that Vector's performance is harmed in certain workloads by cloning too much. For instance, #6770. This allocator pressure limits our throughput as `Event` instances that move through the system must be cloned. This epic is intended to collect tickets that relate to allocator pressure. We expect it to be a long-running epic.

**Comment by jszwedko** [comment]
Closing since this issue was just used for tracking and isn't currently a focus.
