### ISSUE TITLE
Support AWS instance metadata v2

### ISSUE THREAD

**Issue by inian** [vectordotdev/vector#6847]
### Vector Version
vector 0.11.1 (v0.11.1 aarch64-unknown-linux-musl 2020-12-17)

Vector does not work with [AWS instance metadata v2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html). I have some instances with instance metadata v1 disabled for security reasons and Vector is unable to pick the right AWS credentials in those instances. 

### Debug Output
```
 Request failed. error=CloudwatchError::Describe: Couldn't find AWS credentials in environment, credentials file, or IAM role.
```

Possibly related - https://github.com/timberio/vector/issues/2894

**Comment by jszwedko** [comment]
Verified that this is also the case with:

```
vector 0.12.1 (v0.12.1 x86_64-unknown-linux-gnu 2021-03-12)
```

**Comment by binarylogic** [comment]
I'm pretty sure we never supported v2 given some of the complexity with authentication. But I agree, we should support it.

**Comment by jszwedko** [comment]
👍 usually the AWS SDK handles it transparently. We can see if `bollard` does.

Oddly we _only_ support v2 for the `aws_ec2_metadata` transform: https://github.com/timberio/vector/issues/1890

**Comment by arubdesu** [comment]
Just wanted to point out that this bit us as per https://github.com/rusoto/rusoto/issues/1818. Glad to see a milestone has been assigned!

**Comment by jszwedko** [comment]
This was closed by the migration to the AWS SDK (https://github.com/vectordotdev/vector/pulls?q=is%3Apr+%22Migrate+to+AWS+SDK%22+is%3Aclosed+author%3Afuchsnj). It will go out in 0.21.0.
