### ISSUE TITLE
Quickstart with Docker

### ISSUE THREAD

**Issue by kaihendry** [vectordotdev/vector#6860]
https://vector.dev/docs/setup/quickstart/ assumes you will download and execute a binary on your host system which is a bit of an ask. I expected a `docker run timberio/vector:latest-alpine` style example 

### Use-cases

For interested users to better experiment with vector in a slightly sandboxed way.

### Attempted Solutions

This doesn't work. I am not sure why:

```
(ins)[hendry@t14s logs]$ cat vector.toml
[sources.in]
  type = "stdin"

[sinks.out]
  inputs = ["in"]
  type = "console"
  encoding.codec = "text"
(ins)[hendry@t14s logs]$ cat run.sh
echo 'Hello World!' | docker run -i \
  -v ~/vector.toml:/etc/vector/vector.toml:ro \
  -p 8383:8383 timberio/vector:latest-alpine
```

It just exits `INFO vector::shutdown: All sources have finished.`

**Comment by kaihendry** [comment]
This appears to be a way to get going:
```
test -s "$1" || exit

docker run -i \
	-v $PWD/vector.toml:/etc/vector/vector.toml:ro \
	-p 8383:8383 timberio/vector:latest-alpine < $1
```

**Comment by jszwedko** [comment]
@kaihendry I actually see the "Hello World" output with your first example.

```
Mar 24 21:00:48.281  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info"
Mar 24 21:00:48.281  INFO vector::sources::host_metrics: PROCFS_ROOT is unset. Using default '/proc' for procfs root.
Mar 24 21:00:48.281  INFO vector::sources::host_metrics: SYSFS_ROOT is unset. Using default '/sys' for sysfs root.
Mar 24 21:00:48.281  INFO vector::app: Loading configs. path=[("/etc/vector/vector.toml", Some(TOML))]
Mar 24 21:00:48.288  INFO vector::topology: Running healthchecks.
Mar 24 21:00:48.288  INFO vector::topology: Starting source. name="in"
Mar 24 21:00:48.288  INFO vector::topology: Starting sink. name="out"
Mar 24 21:00:48.288  INFO vector::topology::builder: Healthcheck: Passed.
Mar 24 21:00:48.289  INFO vector: Vector has started. version="0.12.1" git_version="v0.12.1" released="Fri, 12 Mar 2021 21:32:07 +0000" arch="x86_64"
Mar 24 21:00:48.289  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.
Mar 24 21:00:48.289  INFO vector::sources::stdin: Capturing STDIN.
Mar 24 21:00:48.291  INFO vector::shutdown: All sources have finished.
Mar 24 21:00:48.291  INFO vector: Vector has stopped.
Hello World!
Mar 24 21:00:48.291  INFO source{component_kind="source" component_name=in component_type=stdin}: vector::sources::stdin: Finished sending.
```

I take it you are not?

**Comment by dreamerlzl** [comment]
Though not the same exact problem, I find the suggested alias setting misleadning 
`alias vector='docker run -it --rm timberio/vector:0.21.2'`

1. There are no tags named `0.21.2`; please either mention this or replace it with `0.21.2-distroless-libc` or something else
2. Apparently `echo 'Hello world!' | vector --config ./vector.toml` would not work for docker install; no volume option set!
3. If you don't remove the option `-t`, an error would occur saying `the input device is not tty`. An easy fix is removing `-t`
4. A working solution for me is `echo 'hello world' | docker run -it -v $(pwd)/vector.toml:/etc/vector/vector.toml --rm timberio/vector:0.21.2-distroless-libc`

**Comment by spencergilbert** [comment]
Ah - yes, I think we've neglected to update the quickstart since we made some changes to the Dockerfiles. I'll see if we can fix this up by next week.
