### ISSUE TITLE
Does the elasticsearch sink support multi endpoints?

### ISSUE THREAD

**Issue by OrdinaryFan** [vectordotdev/vector#6872]
My elasticsearch has three nodes. What should i do to use all nodes?
Now the endpoint config only support one host.

**Comment by OrdinaryFan** [comment]
`endpoint = ["http://host1:9201", "http://host2:9201", "http://host3:9201"]`

**Comment by OrdinaryFan** [comment]
like the filebeat config:
```
output.elasticsearch:
  hosts: ["http://10.45.3.2:9220", "http://10.45.3.1:9230"] 
```

**Comment by gilgameshfreedom** [comment]
+ 1

**Comment by sim0nx** [comment]
Duplicate of https://github.com/vectordotdev/vector/issues/3649

**Comment by spencergilbert** [comment]
As noted by @sim0nx - duplicate of an existing issue 🙂
