### ISSUE TITLE
VRL expression docs inexplicably shout `Enum!`

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#6899]
For example, the coalesce operator docs: https://vector.dev/docs/reference/vrl/expressions/#coalesce . It appears in 5 places though.

<img width="522" alt="Screen Shot 2021-03-26 at 9 44 59 AM" src="https://user-images.githubusercontent.com/316880/112640791-0e95f500-8e18-11eb-9496-a5ec1cfd045e.png">

**Comment by spencergilbert** [comment]
No longer happening.
