### ISSUE TITLE
VECTOR_WATCH_CONFIG env var accepts any value to turn on config monitoring

### ISSUE THREAD

**Issue by marcojck** [vectordotdev/vector#6918]
Hi!

Unlike `VECTOR_REQUIRE_HEALTHY` env var, which requires `true/false` as valid values, `VECTOR_WATCH_CONFIG` env var accepts any values to turn the configuration monitoring feature on. This causes some confusion, especially when automating vector install since both vars are expected to behave accordingly. 

Vector version:  0.12.1 (v0.12.1 x86_64-unknown-linux-gnu 2021-03-12)
O.S.:  CentOS Linux release 7.8.2003 (Core)

Steps to reproduce:

- Vector fails to start with `VECTOR_REQUIRE_HEALTHY` set to a value not equals to `true/false`, which is the expected behavior:

```bash
VECTOR_REQUIRE_HEALTHY=foobar vector
error: Invalid value for '--require-healthy <require-healthy>': provided string was not `true` or `false`
```

- On the other hand, Vector starts and activates config monitoring with `VECTOR_WATCH_CONFIG` set to **any value**. This is confusing since it was expected the same `true/false` validation observed in `VECTOR_REQUIRE_HEALTHY`.

```bash
VECTOR_WATCH_CONFIG=foobar vector
...
Mar 29 11:02:33.437  INFO vector::config::watcher: Watching configuration files.
```

Is this correct or I misunderstood the value required by `VECTOR_WATCH_CONFIG`?

Thanks!

**Comment by jszwedko** [comment]
This appears to no longer be an issue:

```
$ VECTOR_WATCH_CONFIG=foobar vector-0.26.0
error: 'foobar' isn't a valid value for '--watch-config'
  [possible values: true, false]

For more information try '--help'
```
