### ISSUE TITLE
Implement framing/codec support for sources

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#6958]
## Summary

Users want the flexibility of ingesting data into Vector from sources that they do not have control over the encoding and framing of. We want to modify the `socket` source and sink to have improved codec support to serve as a pattern for other components to use.

## Jobs to be done
- `socket` source supports configuration of codecs

## Requirements
- `socket` source supports octet framing
- `socket` source supports arbitrary delimiter framing (right now we only support newline)
- `socket` source supports "one event per packet" framing for UDP
- `socket` source support syslog codec for encoding/decoding

Ideally this would be implemented in a way that is easy to share the code and configuration for to other components (like `kafka`).

## Out of scope
- Additional compression and framing formats

**Comment by pablosichert** [comment]
This has been completed with #7463 and #9209.
