### ISSUE TITLE
Document and test topology back-pressure application

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#6961]
## Summary

It is important that Vector has robust and easy to understand back-pressure functionality to avoid consuming additional events when one or more sinks are lagging.

## Jobs to be done
- Add tests for back pressure to ensure it is correctly applied for serial and fan-out topologies
- Document how back pressure propagates on the website

## Requirements
- A sink is able to propagate back-pressure to its inputs when the inputs are fanning out (for example one source, to many sinks)

## Out of scope
- Modifying how back pressure works

**Comment by jszwedko** [comment]
So, I believe this actually may already be Vector's behavior, but we should verify it.

If it is, we should:

- Add tests
- Add external documentation to the website

If it isn't, we should make it the behavior, and then also do those things.

**Comment by AntonSmolkov** [comment]
> this actually may already be Vector's behavior

No, unfortunately it's not. See https://github.com/timberio/vector/issues/8238

**Comment by jszwedko** [comment]
@AntonSmolkov I think that is a slightly different issue in that the back pressure is not being handled appropriately by the sources using `tcp`. This ticket is just about how it propagates in fan-out scenarios.

We should definitely fix #8238 though.

**Comment by lukesteensen** [comment]
This is how Vector's topology has always worked, so it's definitely supported. Even the two "out of scope" this are already possible via buffer configuration. I'm not sure whether we have an explicit test for it in general, but that could be valuable especially if it were able to catch bugs like #8238.

**Comment by jszwedko** [comment]
I've updated the title and description here to be specific to testing and documentation given Vector was already functioning the way we wanted it to for fan-out topologies.
