### ISSUE TITLE
Revamp unit testing

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#6964]
## Summary

Unit testing is one of the most loved Vector features and gives users more confidence in their configs. We have not revisited it since we introduced VRL, but we believe the feature can be made more usable through it.

## Jobs to be done
- Vector's unit testing framework is rethought in the context of VRL

## Requirements
- Unit tests with Remap conditions should display the source of a failed test
- Rewrite documentation using Remap conditions as examples
- Add `assert` function / keyword to Remap for use with unit tests

**Comment by JeanMertz** [comment]
It _might_ be worth it to rename `type = "remap"` to `type = "vrl"`, given that we now have multiple transforms that use VRL, which makes it a bit strange that you'd use the name of _one_ of those transforms as opposed to one of the others.

**Comment by JeanMertz** [comment]
I've seen several people confused that only the last expression is used in the test result.

Example: https://discord.com/channels/742820443487993987/764187584452493323/855040865239957545

It's something we discussed before, but I think we need to either document this properly, or rethink our approach here somehow.

**Comment by jszwedko** [comment]
> ~(this becomes a bit less relevant when/if we switch to VRL being the default, we can also do the rename at that point, to have one big "breaking change")~ Wait, did we make the switch already?

This switch did happen, also to my surprise since the docs were not updated. I think it is still safe to swap `type = "remap"` for `type = "vrl"` since I imagine everyone that is using VRL conditions is just using `condition = "<vrl source>"`.

> I've seen several people confused that only the last expression is used in the test result.

Agreed, I think I'm going to deprecate that mode of failing a unit test in-lieu of using `assert()` and `assert_eq()`.

**Comment by JeanMertz** [comment]
Someone asked for a "non fail-fast" setting when running tests (e.g. see all failed errors, not just the the first one hit by `assert`).

https://discord.com/channels/742820443487993987/764187584452493323/906069677321646120

**Comment by jszwedko** [comment]
These changes have been made.
