### ISSUE TITLE
Improve Remap enrichment

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#6989]
Currently there are open questions around enriching data in Remap, especially enrichment that requires I/O (network, disk, etc). To ensure this type of functionality is performant and reliable we'll need to implement caching and failure handling, things that deviate from the simple nature of Remap. This epic represents that work, including an RFC to establish consensus (even if we decide not to do it).

**Comment by jszwedko** [comment]
Closing this as covered by https://github.com/vectordotdev/vector/blob/master/lib/vrl/DESIGN.md
