### ISSUE TITLE
Add function to generate a random number to VRL

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#7049]
Requested by user in discord: https://discord.com/channels/742820443487993987/746070591097798688/829767928122703982

**Comment by blake-mealey** [comment]
Is there any way to achieve this atm with the existing `random_bytes` function? I've tried:

* `to_int(random_bytes(len))` - `to_int` seems to be assuming the string is utf8/ascii and decimal encoded
* `parse_int(random_bytes(len), 2)` - assumes utf8/ascii with various encodings

I _think_ `parse_int(encode_base16(random_bytes(len)), 16)` would work but unfortunately this is not available on my current version of Vector.

**Comment by jszwedko** [comment]
I opened https://github.com/vectordotdev/vector/pull/16768 adding a few random functions. I'm curious to get any feedback from those following this issue.
