### ISSUE TITLE
Add unique identifiers to source configuration

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#7066]
The first step for the end-to-end acknowledgement process is to provide sources with an identifier that may be used in the metadata to uniquely identify the source. While creating such an identifier is trivial, we must ensure that it remains constant when the source is reloaded (maintaining state), while remaining unique when vector is restarted (losing state).

Ref #6517

**Comment by binarylogic** [comment]
This may be a dumb question, but don’t we already supply IDs when defining a source? Ex:

```toml
[sources.my_id]
# …
```

**Comment by bruceg** [comment]
Those assigned names *are* indeed unique within the current pipeline, but are no longer unique when considering restarting vector or reloading the config having a different source with the same name. This is relevant for buffered events with acknowledgements which can no longer be delivered to the original source as it no longer exists even though it may have the same name.

**Comment by binarylogic** [comment]
Is there an easy solution here? Otherwise I'm ok with this caveat since it only affects disk buffers.

**Comment by bruceg** [comment]
The solution for this is indeed easy, but it is unnecessary until we do the work to actually handle acknowledgements after events are buffered. See also https://github.com/timberio/vector/pull/7119#issuecomment-839941736

**Comment by bruceg** [comment]
As this work is only relevant for end-to-end acknowledgements through disk buffers, and we have decided to count buffered events as acknowledged, this work is no longer needed.
