### ISSUE TITLE
Integrate `Lookup` into vector 

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#7073]
Once the lookup crate introduced in #7071 is available we want to see it incorporated into vector. We expect that this will require a great deal of mechanical work. If possible this cut-over should be done gradually, as @FungusHumungus suggests [is possible](https://github.com/timberio/vector/pull/5374#issuecomment-816810507).

**Comment by fuchsnj** [comment]
This is being tracked by https://github.com/vectordotdev/vector/issues/7070 now.
