### ISSUE TITLE
Datadog codec

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#7109]
We currently have a `datadog_logs` source that will accept log data from upstream Datadog agents. This allows for direct communication with Datadog agents, but there will be scenarios where customers will want to write data to a queue/log first (like Kakfa). By decoupling the codec aspect into a generic "datadog" codec, users should be able to encode and decode Datadog agent data without losing information. This enables users to use generic sources where data is proxied through them, like the `kafka`, `http`, and `socket` sources.

Epics #4097 and #6958 should unblock this.

**Comment by jszwedko** [comment]
@binarylogic I might be misunderstanding, but I think this would be more of a `vector` <-> `vector` codec. We should aim to have data coming from a `datadog_logs` source -> `kafka` sink -> `kafka` source -> `datadog_logs` sink have the same end-result as writing doing `datadog_logs` source -> `datadog_logs` sink in one vector instance, but I think passing data through Kafka between Vector instances is more about having a Vector serialization format that can be passed through Kafka. This is related to the current work using protobuf + GRPC over HTTP to send data between vector instances; we could reuse the same data representation.

**Comment by tobz** [comment]
I believe this will be answered via #9930, so I'm going to close this for now.
