### ISSUE TITLE
Add ability to easily format strings in VRL

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#7117]
Requested by user in discord: https://discord.com/channels/742820443487993987/764187584452493323/831828809358770226

Currently users can use `+` to concat strings, but this is a bit unwieldily for creating formatted strings. It would be nice to support some sort of sprintf-style function.

**Comment by zsherman** [comment]
Alternatively we could support something akin to [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)?
