### ISSUE TITLE
Make it easier to determine how many events are stored in Vector's buffers

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#7185]
A user was interested in knowing how many events are stored in its disk buffers on shutdown. Right now, I think they'd need to query the leveldb database directly.

One option would be to expose an internal gauge metric (this wouldn't be 100% real-time, but would likely be close enough).

**Comment by jszwedko** [comment]
`events_in_total` - `events_out_total` might also get close once those are consistently defined. For reference, it is possible to query the leveldb dbs directly like:

```python
import leveldb
db = leveldb.LevelDB('/var/lib/vector/out_buffer')
print(len(list(db.RangeIter())))
```

**Comment by pavel-elkin-klarna** [comment]
Would it be possible for vector to report the number of log messages left in buffers on shutdown, e.g. in logs? The question we're trying to answer is how many messages have not been delivered when the instances are shut down or restarted. Or maybe it could be a separate metric, though I'm not sure it's possible if the metrics are pulled by the agent, not pushed.

**Comment by jszwedko** [comment]
@pavel-elkin-klarna 👍 we could put it in the logs too. The metrics are stored internally but can be accessed by the [`internal_metrics`](https://vector.dev/docs/reference/configuration/sources/internal_metrics/) source and sent to a sink like [`prometheus_exporter`](https://vector.dev/docs/reference/configuration/sinks/prometheus_exporter/).

**Comment by benzaita** [comment]
A related use case is to be able to alert when internal buffers are about to be full (and drip events). For that we’d need some metric about the utilization of the buffers.

**Comment by jszwedko** [comment]
One liner for counting across all components:

```
find /var/lib/vector/ -maxdepth 1 -mindepth 1 -type d -exec python -c 'import leveldb; import sys; db = leveldb.LevelDB(sys.argv[-1]); print(str(len(list(db.RangeIter()))).ljust(8),sys.argv[-1])'  '{}' \;
```

**Comment by jszwedko** [comment]
Closing this in-lieu of https://github.com/vectordotdev/vector/issues/4936
