### ISSUE TITLE
Cannot pass path with hyphens to remap funcitons

### ISSUE THREAD

**Issue by dekelpilli** [vectordotdev/vector#7196]
### Vector Version

```
vector 0.12.2 (v0.12.2 x86_64-apple-darwin 2021-03-30)
```

### Vector Configuration File

```json
{
  "sources": {
    "my_socket": {
      "type": "socket",
      "mode": "tcp",
      "address": "0.0.0.0:1234"
    }
  },
  "transforms": {
    "my_filter": {
      "type": "filter",
      "condition": "(\".hyphenated-field\" == s'desired value')",
      "inputs": ["my_socket"]
    },
    "my_xform": {
      "type": "remap",
      "source": "del(.hyphenated-field)",
      "inputs": ["my_filter"]
    }
  },
  "sinks": {
    "my_sink": {
      "encoding": {
        "codec": "json"
      },
      "inputs": ["my_xform"],
      "target": "stdout",
      "type": "console"
    }
  }
}
```

### Debug Output

```
Apr 21 16:25:44.496 ERROR vector::topology: Configuration error. error=Transform "my_xform":
error[E630]: fallible argument
  ┌─ :1:5
  │
1 │ del(.hyphenated-field)
  │     ^^^^^^^^^^^^^^^^^
  │     │
  │     this expression can fail
  │     handle the error before passing it in as an argument
  │
  = see documentation about error handling at https://errors.vrl.dev/#handling
  = see language documentation at https://vrl.dev
  ```

or if I set the source to be `"del(\".hyphenated-field\")"`:

```
Apr 21 16:27:16.972 ERROR vector::topology: Configuration error. error=Transform "my_xform":
error[E610]: function compilation error
  ┌─ :1:1
  │
1 │ del(".hyphenated-field")
  │ ^^^^^^^^^^^^^^^^^^^^^^^^
  │ │
  │ unexpected expression for argument "target"
  │ expected: query
  │ received: literal
  │
  = see language documentation at https://vrl.dev
```

### Expected Behavior

I'm not sure what the intent is for users referencing paths with non-`a-zA-Z0-9_` characters, but it seems to me that it should be possible. My instinct would be to allow quoting the path, just as I did in the `my_filter` transform.

### Additional Context

As you can see, referencing the hyphenated field in `my_filter` works fine with quoting, but it seems to interpret `.hyphenated-field` as an arithmetic operation and `".hyphenated-field"` as a string literal rather than a path. The same issue would be had with non-ASCII characters in the path, although that's not something that impacts me at the moment.

**Comment by StephenWakely** [comment]
@dekelpilli For quoted fields you need the `.` to be outside the quotes. So:

```
del(."hyphenated-field")
```

should do what you need.

**Comment by jszwedko** [comment]
Just noting that this is mentioned here: https://vector.dev/docs/reference/vrl/expressions/#path_segments

**Comment by dekelpilli** [comment]
Thanks for that! I see now that I simply misread the docs (not noticing the dot was on the other side of the quote", and in my filter example above I would actually be comparing the string `.hyphenated-field`, not the value in that key.
