### ISSUE TITLE
`vector validate` should fail for invalid VRL programs

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#7198]
Reported by user in discord: https://discord.com/channels/742820443487993987/746070591097798688/834437031966801970

The user observed that their VRL script causes an error on `vector` start, but not when using `vector validate`.

VRL program error:

```
error[E105]: call to undefined function
  ┌─ :7:4
  │
7 │ if is_null(err) {
  │    ^^^^^^^
  │    │
  │    undefined function
  │    did you mean "is_nullish"?
  │
  = learn more about error code 105 at https://errors.vrl.dev/105
  = see language documentation at https://vrl.dev
```

**Comment by akasprzok** [comment]
This would be _immensely_ useful for pre-commit and ci/cd purposes.

**Comment by jszwedko** [comment]
Apparently this does happen if you don't specify `--no-environment`, but we should also validate it when not validating the environment.

**Comment by binarylogic** [comment]
This likely overlaps with #9468 and #9470. Components should have a concept of being valid that `vector validate` can hook into. Specific component checks should not be done at the `vector validate` level.

**Comment by myndzi** [comment]
I came looking for a similar issue: `vector validate` can take an extremely long time timing out on health checks if there are many sinks, which means that `--no-environment` is desirable in my use-case. However, `--no-environment` also disables VRL checks, making `vector validate` pretty limited in its utility. I'd still like to be able to check that the config for the sinks is correct, I would like to be able to tell it to do everything _except_ run health checks (a network operation that could produce inconsistent results, or be invalild in CI)

**Comment by jszwedko** [comment]
Thanks for the input @myndzi . We are hoping to address this this quarter.

**Comment by jszwedko** [comment]
Closing as duplicate of https://github.com/vectordotdev/vector/issues/15037 since that issue has more details.
