### ISSUE TITLE
Build a Vector Kubernetes operator

### ISSUE THREAD

**Issue by JeanMertz** [vectordotdev/vector#7282]
Placeholder issue for future work to develop a Kubernetes "[Operator](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/)" utility to deploy/manage Vector as an aggregator in a Kubernetes cluster. This could potential replace  our Helm charts in the future.

@zsherman shared a good example at https://github.com/banzaicloud/logging-operator.

**Comment by binarylogic** [comment]
Ref #768
