### ISSUE TITLE
Enhancement request - provide meta data of network and tls inputs as variables

### ISSUE THREAD

**Issue by ryn9** [vectordotdev/vector#7308]
### Current Vector Version

```
vector 0.13.1 (v0.13.1 x86_64-unknown-linux-musl 2021-04-29)
```

### Use-cases

It would be beneficial for Vector to provide, as variables, meta data of network and tls inputs.

This would be like Logstash provides for some sources.
For example - using Logtash's beats input, the user then can make sure of the following provided variables:
@metadata.ip_address
@metadata.tls_peer.status
@metadata.tls_peer.protocol
@metadata.tls_peer.subject
@metadata.tls_peer.cipher_suite

*Note - @metadata is not passed onward to configured sinks

### Attempted Solutions

N/A - support channel requested an enhancement request be opened

### Proposal

Start a standard for metadata variables for use in vector and take requests from the community regarding what metadata may be useful.

In this case - I would like to see meta data such as the provided examples:
ip_address
tls_peer.status
tls_peer.protocol
tls_peer.subject
tls_peer.cipher_suite

### References

https://www.elastic.co/guide/en/logstash/current/plugins-inputs-beats.html#plugins-inputs-beats-ecs_metadata

**Comment by brianpham** [comment]
This would be useful for our use case as well.

**Comment by ryn9** [comment]
@jszwedko might you be label this against pretty much all sources?

If there is not an appetite to handle this with standard metadata fields (more like how logstash does it), perhaps the inputs offer more options to push this data to user configured fields (more like how fluent* does it)?

fluentd example - https://docs.fluentd.org/input/tcp#source_address_key

**Comment by jszwedko** [comment]
@ryn9 yeah agreed, I've tagged all the sources I think that are relevant.

> This would be useful for our use case as well since we use @metadata with logstash. The general concept of having metadata that is not passed to the sink would be very useful.

Agreed, this would be very useful, but I'd like to scope this issue to just adding the requested metadata as fields on events coming from that source. Having a separate concept of metadata that is not passed along to sinks is a much broader issue that'll probably require broader design (e.g. how are these fields accessed in `remap`?). https://github.com/timberio/vector/issues/2343 is somewhat related.

**Comment by colin-grapl** [comment]
This is very relevant for our usecase where we're running a Vector instance in a VM where we also run untrusted code. Having our logs decorated with cryptographically verifiable data is one thing we've explicitly called out as a desired feature.

FWIW, happy to contribute as well if someone's willing to help out.

**Comment by jszwedko** [comment]
Thanks @colin-grapl ! That makes sense. We'd be happy to guide a PR implementing it if you want to take a shot. The biggest issue I foresee is doing it in a way that is easily re-used across source components that support TLS. I'd suggest just starting with one source, maybe the `socket` source, as a way to prove out the idea. The [CONTRIBUTING.md](https://github.com/timberio/vector/blob/master/CONTRIBUTING.md) doc is a good place to start.

**Comment by rwaweber** [comment]
Adding this related issue (includes a logstash pipeline that leans on some cert metadata from the beats input plugin, if that's interesting to those here):

https://github.com/timberio/vector/issues/2931

Would be happy to collaborate on this feature too!

**Comment by jszwedko** [comment]
This has strong overlap with https://github.com/vectordotdev/vector/issues/2931 so I'll close this to center the discussion over there.
