### ISSUE TITLE
Insufficient explanation for Warning on docker source

### ISSUE THREAD

**Issue by pgassmann** [vectordotdev/vector#7361]
The Warning on the docker source documentation page is not documented with evidence.

 >   Collecting logs directly from the Docker Engine is known to have performance problems for very large setups. If you have a large setup, please consider alternative collection methods, such as the Docker syslog or Docker journald driver drivers.

I could not find the source of "is known". Which performance is affected and how? What is a large setup? many containers or many log lines?

How does vector get the logs? from the http api? How is reading the logs from journald better?
https://docs.docker.com/engine/api/v1.41/#operation/ContainerLogs
https://docs.docker.com/engine/api/v1.41/#operation/ContainerAttach

@jszwedko wrote in a [comment](https://github.com/timberio/vector/issues/5716#issuecomment-825756127):
> We use the HTTP ContainerLogs endpoint you linked. I'm actually not aware of what the limits of ingesting logs from the API are or why journald would be preferred. It looks like @binarylogic added that note to the docs in #4547, maybe he has some more details.

**Comment by jszwedko** [comment]
@binarylogic are you aware of why we have this warning?
