### ISSUE TITLE
Emit metric for events dropped by buffer

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#7379]
Requested by [user in discord](https://discord.com/channels/742820443487993987/746070591097798688/840264314354270279).

They'd like to see us emit a metric for dropped events for monitoring purposes.

**Comment by binarylogic** [comment]
@001wwang , this will be closed with #9327 right?

**Comment by 001wwang** [comment]
Yep, #9327 includes the `buffer_discarded_events_total` metric.

**Comment by binarylogic** [comment]
Dup of #4936
