### ISSUE TITLE
geoip transformer incompatible with elasticsearch sink

### ISSUE THREAD

**Issue by lifeofguenter** [vectordotdev/vector#7384]
The current geoip transformer implementation (https://vector.dev/docs/reference/configuration/transforms/geoip/) is not compatible with the `geo_point` field type in elasticsearch (https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html)

I understand this can be "fixed" with another remap transformer, but would be great if it could also just work out-of-the-box.

**Comment by fasterfox** [comment]
> I understand this can be "fixed" with another remap transformer, but would be great if it could also just work out-of-the-box.

Hello @lifeofguenter!  Can you share with your "fix" via another remap transformer. I have the same problem. Vectors geoip returns latitude and longitude only in string format, but for elastic or opensearch it need to be as geo_point.

**Comment by jszwedko** [comment]
A `remap` for this would look something like:

```
geoip = del(.geoip)
.location = { lat: to_float!(geoip.latitude), lon: to_float!(geoip.longitude) }
```

Assuming `location` is the geopoint field, and `geoip` is where the `geiop_transform` was configured to put the data.

**Comment by jszwedko** [comment]
Closing this since there isn't an expectation that the geoip enrichment is compatible with every sink's geoip representation. Users will need to map as appropriate.
