### ISSUE TITLE
`buffer/Acker` -- avoid duplication of `events_out_total`

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#7405]
When we migrated `buffers` into vector-core this left the dependency on `internal_events` in a weird place. The dependency was broken by duplicating "events_out_total" metric in the `Acker::ack` but this is obviously undesirable in the long-term. Feasible to address but there will have to be some leg work done to achieve it. 

_Originally posted by @jszwedko in https://github.com/timberio/vector/pull/7400#discussion_r630158290_

**Comment by blt** [comment]
I'm moving this into the backlog. It's not totally clear how to address this and seems very low priority as-is, especially consider we've go the duplication well-documented.

**Comment by jszwedko** [comment]
This was removed in d216b5300
