### ISSUE TITLE
kafka source: Avro decoding support

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#7434]
Similar to: #561

Avro support has been requested before (for both kafka source and sink), and brought up again today in discord:
https://discord.com/channels/742820443487993987/746070591097798688/842049054657347605

Possibly tie into the framing/codec work #7351

**Comment by spencergilbert** [comment]
@jszwedko did this accidentally get closed?

**Comment by jszwedko** [comment]
Oops, yeah, I had mistakenly associated this with #7470. I corrected it in the Github description, but forgot to fix it in the merge commit. Thanks for noting!

**Comment by hhromic** [comment]
We are looking very forward to Kafka + AVRO + Schema Registry interoperability within Vector.
Thanks in advance for working on the AVRO side already. We are more than happy to help you test/debug in our environment when the time comes for it. And thanks again for Vector, we really think is quality software engineering.

**Comment by neoliant** [comment]
+1

**Comment by Igosuki** [comment]
I've been involved in porting avro to some apache project so here's some prior art : 
https://github.com/apache/avro/tree/master/lang/rust
https://github.com/jorgecarleitao/arrow2/tree/main/src/io/avro

**Comment by wanisfahmyDE** [comment]
any news on integrating avro support soon?

**Comment by jszwedko** [comment]
Hi @wanisfahmyDE !

Nothing planned yet, but we would accept PRs for it. It's a bit more complicated than other decoders since it requires a schema definition (ignoring registry support which would add even more complexity).

If anyone is interested in contributing this, https://github.com/vectordotdev/vector/tree/master/src/codecs/decoding would be a good place to start looking.

**Comment by ghakobyan-sqsp** [comment]
Literally the only reason I have to keep Logstash somewhere =/ Hope this is implemented eventually.

**Comment by jszwedko** [comment]
👍 We do actually have `avro` encoding support now. I'll repurpose this issue to be just about decoding.

**Comment by schenksj** [comment]
Is there any current activity on decoding support?  This would be an appreciated feature indeed!

**Comment by jszwedko** [comment]
Nothing yet, but happy to help guide in a contribution here if anyone feels motivated 🚀

**Comment by jszwedko** [comment]
> @jszwedko I'd love to help here, not sure I can dedicate the time at the moment. Quick question though, decoding support generally works across source types, not just kafka, correct? Like if I had a file full of sequential avro data, such an enhancement would support that as well?

Yeah, the codecs are implemented in a shared manner such that adding one makes it available to each source or each sink.

**Comment by tom-leahy** [comment]
I too am interested in getting Avro deserialization support - but looking through the list of open PRs I noticed this: https://github.com/vectordotdev/vector/pull/17521 which seems to at least implement for a single schema source (not the more complicated registry but a good start imho). I'm assuming this issue would remain open until support for registry exists (to allow for the topic name regex as input topics in the source), but wanted to check on how close this first PR is to merging? Looks like it's been open for 2 months. @jszwedko @cameronbraid @fuchsnj

**Comment by tom-leahy** [comment]
Thanks @jszwedko !

**Comment by pront** [comment]
Thanks @Ion-manden, closing this issue since the work has been completed.

**Comment by mcarbonneaux** [comment]
and schema registry support ?

**Comment by jszwedko** [comment]
> and schema registry support ?

This is tracked by https://github.com/vectordotdev/vector/issues/19546

**Comment by danil-melkin** [comment]
> > and schema registry support ?
> 
> This is tracked by [#19546](https://github.com/vectordotdev/vector/issues/19546)

Is there any progress on SR support? Or maybe you know some way how to read messages in two schema versions from the same topic?
