### ISSUE TITLE
Investigate performance characteristics of end-to-end acknowledgements

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#7447]
With the development of end-to-end acknowledgements, there have been additional mechanisms introduced into the travel of an event from source to sink. This will necessarily increase the latency to respond to each source request, but beyond that we have no good notion of how this feature is changing the performance characteristics of Vector. This needs to be measured and documented to ensure we minimize the cost of this feature.

**Comment by binarylogic** [comment]
cc @tobz and @blt to coordinate on a low-effort solution for this. (e.g. just verifying that things aren't significantly slower)

**Comment by blt** [comment]
Once #7643 is in place we can deploy soaker variants that do and do not have acks enabled. If we find a serious difference we'll have to dig in further, but this'll get us a high-level notion at least.

**Comment by bruceg** [comment]
Closed by #10255
