### ISSUE TITLE
Support static string expressions when string literals are required in VRL

### ISSUE THREAD

**Issue by hhromic** [vectordotdev/vector#7519]
Currently, VRL requires string literals in some cases, like grok patterns for `parse_grok`. This prohibits the use of even static string concatenation which is useful to break the pattern up over multiple lines.

See original bug report below:

### Vector Version

```
vector 0.13.1 (v0.13.1 x86_64-unknown-linux-gnu 2021-04-29)
```

### Expected Behavior

According to the [documentation](https://vector.dev/docs/reference/vrl/functions/#parse_grok), the `pattern` parameter in the `parse_grok()` function is of type `<string>`:

    parse_grok(value: <string>, pattern: <string>, [remove_empty: <boolean>]) :: <object>, <error>

Which should allow for string-based operations such as `str1 + str2` to work:
```
$ parse_grok!(
    "2020-10-02T23:22:12.223222Z info Hello world",
    "%{TIMESTAMP_ISO8601:timestamp}" + " %{LOGLEVEL:level}" + " %{GREEDYDATA:message}"
)
```

The use-case for this is to be able to write very long patterns in multiple lines for readability:
```
$ parse_grok(myvar, "%{TIMESTAMP_ISO8601:timestamp}" +
                    " %{LOGLEVEL:level}" +
                    " %{GREEDYDATA:message}" +
                    ...)
```

Another use-case is to be able to conditionally assemble a pattern to match.

### Actual Behavior

However, the VRL compiler seems to not be evaluating the string opeartion correctly:
```
error[E610]: function compilation error
  ┌─ :1:1
  │
1 │ ╭ ╭ ╭ parse_grok!(
2 │ │ │ │     "2020-10-02T23:22:12.223222Z info Hello world",
3 │ │ │ │     "%{TIMESTAMP_ISO8601:timestamp}" + " %{LOGLEVEL:level}" + " %{GREEDYDATA:message}"
4 │ │ │ │ )
  │ ╰─│─│─^ unexpected expression for argument "pattern"
  │   ╰─│─' received: operation
  │     ╰─' expected: literal
  │
  = see language documentation at https://vrl.dev
```

Note that the same done to the `value` argument (also of type `<string>`) DOES work as expected:
```
$ parse_grok!(
    "2020-10-02T23:22:12.223222Z" + " info" + " Hello world",
    "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:message}"
)
{ "level": "info", "message": "Hello world", "timestamp": "2020-10-02T23:22:12.223222Z" }
```

I tested other functions with `<string>` arguments and they all seem to work as expected:
```
$ parse_csv!("foo" + " bar", delimiter: " " + "")
["foo", "bar"]

$ parse_key_value!("key=val" + " other_key=other_val", "=" + "")
{ "key": "val", "other_key": "other_val" }

$ parse_timestamp!("10-Oct-2020" + " 16:00+00:00", format: "%v" +" %R %:z")
t'2020-10-10T16:00:00Z'
```

**Comment by jszwedko** [comment]
Thanks @hhromic ! The issue here is that vector wants the grok pattern to be static so it can compile it when the program compiles rather than on each event. I think we can enhance it to support expressions that are just static string concatenation though. I'll remodel this issue to reflect that.

**Comment by hhromic** [comment]
@jszwedko Ah I see, thanks for the clarification, and I'm happy that you spotted the actual problem in no time!

I think is important for all functions to have a consistent API. I'm not familiar with Vector's source code but the functions where the string concatenation _does work_ (as per the issue description), is because they already support static string concatenation? Or they also would need to be reworked for consistency?

**Comment by jszwedko** [comment]
@hhromic those ones, where it works currently, allow dynamic values at runtime so you can use, for example, variables or function calls. For example, it also allows for:

```
other_val = if exists(.foo) {
  .foo
} else {
  .bar
}
parse_key_value!("key=val" + " other_key=" + other_val", "=" + "")
```

For functions like `parse_regex` and `parse_grok` we opted to require static expressions so that we can compile that at vector boot time rather than need to compile them for each incoming event as compiling regular expressions and grok patterns are expensive and drastically reduce throughput (by a factor of 10-100x).

Unfortunately, this does lead to some inconsistency in the function APIs in that some places can only take literals where others can take dynamic values. I think we may want to revisit our approach to this at some point to reconcile this limitation. One thing we could consider doing is allowing dynamic values there, compiling on each event, but caching the result.

**Comment by hhromic** [comment]
Hi @jszwedko ,

> For functions like `parse_regex` and `parse_grok` we opted to require static expressions so that we can compile that at vector boot time rather than need to compile them for each incoming event as compiling regular expressions and grok patterns are expensive and drastically reduce throughput (by a factor of 10-100x).
> 

That makes sense and I fully agree that blindly re-compiling regexes per event is a bad idea.

> Unfortunately, this does lead to some inconsistency in the function APIs in that some places can only take literals where others can take dynamic values. I think we may want to revisit our approach to this at some point to reconcile this limitation. One thing we could consider doing is allowing dynamic values there, compiling on each event, but caching the result.

Those are good ideas, however look more ambitious.

Another idea, given that the primary use-case (for us at least) is to split long-lines into multi-lines, is to implement a line continuation token into VRL. For example the classic back-slash line continuation symbol: `\`. And also to implement concatenation of string literals at the grammar level instead of as a concatenation expression (Python and C/C++ can do this for instance).

For example:
```
$ parse_grok(myvar, "%{TIMESTAMP_ISO8601:timestamp}" \
                    " %{LOGLEVEL:level}" \
                    " %{GREEDYDATA:message}" \
                    ...)
```
That could be parsed by Vector as if it were:
```
$ parse_grok(myvar, "%{TIMESTAMP_ISO8601:timestamp}" " %{LOGLEVEL:level}" " %{GREEDYDATA:message}" ...)
```
Which in turn can be translated as a literal at compile-time to:
```
$ parse_grok(myvar, "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:message} ...")
```

This idea might be easier and safer to implemement perhaps? And it would have the added benefit to automatically optimise everywhere else where string literals need to be concatenated.

**Comment by jszwedko** [comment]
👍 that would be a simpler initial implementation for this case. Eventually I'd still like to see us do something to smooth over that rough edge of literals being required for some arguments. Or at least make it more obvious when they are and why.

**Comment by hhromic** [comment]
> Eventually I'd still like to see us do something to smooth over that rough edge of literals being required for some arguments. Or at least make it more obvious when they are and why.

Totally agree. I think what I proposed can be done independently as well, I don't think you have to choose one or the other. My proposal can help a lot writing more readable config files, specially those with very long lines (i.e. multiple chained functions or more elaborate patterns) that can't be multi-lined at the moment.

**Comment by jszwedko** [comment]
Agreed, I think we can do `\` for splitting up strings over newlines for now.

**Comment by hhromic** [comment]
> Agreed, I think we can do `\` for splitting up strings over newlines for now.

That sounds good enough for us! Looking forward and let me know if you need testing.

**Comment by StephenWakely** [comment]
I could see us introducing an optimization stage at some point that resolves all static expressions at compile time, which would be the ultimate solution to this issue.
