### ISSUE TITLE
Make a WARN=error flag and/or config item

### ISSUE THREAD

**Issue by stribb** [vectordotdev/vector#7528]
### Current Vector Version

0.13.1

### Use-cases

I sometimes write logically valid but practically broken configs. The most recent time I did this, I had a source and a transform, but my sink was only reading from the source -- the transform was unused. 

### Attempted Solutions

As things stand, a WARN log is emitted when configurations such as mine are applied.

### Proposal

At the top level of a Vector config, add an additional flag, `initial_warnings = "fatal", or add code to `--deny-warnings` to make it work in production rather than just in `validate` mode.

### References

https://discord.com/channels/742820443487993987/746070591097798688/844967457156497418

**Comment by jszwedko** [comment]
Rolling this into https://github.com/vectordotdev/vector/issues/13056
