### ISSUE TITLE
New `gcp_pubsub` source

### ISSUE THREAD

**Issue by vladifwix** [vectordotdev/vector#753]
Hello,
Vector supports Kafka and aws Kinesis (where vector agents publish events to)
It will be great to add support for Google pub/sub
Why?

1. GCP and pub/sub specifically is gaining more and more popularity , especialy in the data processing world
2. Integrate pub/sub with Vector consumer
3. Google BiqQuery is extremely popular so streaming events to it will be very beneficial for the Vector adoption

Thanks
Vladi Feigin

**Comment by bruceg** [comment]
Is there anything to test an implementation against comparable to the "localstack" image for AWS services?

**Comment by bruceg** [comment]
So a quick survey of the landscape reveals the following (short term) difficulties:

1. Using pull mode with either the REST or gRPC API, requires polling for new data, which is inefficient.
2. Using push mode with the REST API appears to require opening up a HTTP[S] server port for GCP to make connections to, which may be impossible due to firewalling, container networking, etc.
3. There appears to be better streaming support with the gRPC API, but the gRPC landscape is a bit confused, especially with our efforts to transition to futures 0.3 and tokio 0.2. Any work done today would likely require a full rewrite to use different support crates after the futures/tokio transition due to incompatible dependencies.

Given the above, I think writing a pull mode client (with a dynamic request backoff) makes the most sense at this point, and then reevaluate once the futures landscape settles somewhat. Does that make sense, or have I missed a better option?

**Comment by lukesteensen** [comment]
That sounds reasonable to me.

Depending on the priority of this source and the timeline of the futures/tokio migration, we could also choose to just wait until there's a clear path for GRPC. I'm sure @LucioFranco has some thoughts on that subject :smile:

**Comment by LucioFranco** [comment]
Once the tokio-compat upgrade is in place, it should be quite trivial to use `tonic` and in-fact I already have a gcp pubsub example https://github.com/hyperium/tonic/tree/master/examples/src/gcp

Now that the FD leak has been fixed I suspect by end of next week we should be on tokio-compat.

I think using h2's streaming would be much better than any sort of h1 solution.

**Comment by bruceg** [comment]
Ok, I will defer this one until that work is ready to use.

**Comment by hprotzek** [comment]
Hi there, any update on this? A pubsub source would be very handy for our use-case, to replace logstash with vector :-)

**Comment by jamtur01** [comment]
Some notes from a user:

Google Cloud Platform (in contrast to AWS) has a very centralized approach to account and service log management. GCP allows all logging to be centralized into stackdriver and made available over the pub/sub service. It is possible to generate a single log subscription filter to gather logs for all services in all accounts and make them available to a single pub/sub. Stackdeiver logs made available in this format are well-structured self-describing JSON objects that do not require the same manipulation that AWS CloudTrail etc logs do.

Two modes supported for GCP pub/sub:
1. Pull mode for typical collectors where they authenticate to the service and pull new messages
2. Push mode for SaaS collection (NOTE: requires domain ownership validation)

**Comment by kamalmarhubi** [comment]
@bruceg @LucioFranco it looks like the dust has settled on the futures 0.3 / tokio 0.2 migration. Does this mean this will be easier to add now?

**Comment by lukesteensen** [comment]
@kamalmarhubi there's still a little bit left to do for that upgrade, but I would be surprised if any of it were a blocker here. This is likely due for another look.

Does that seem right to you @bruceg?

**Comment by rrs45** [comment]
Eagerly waiting on this for our use case. Pull and/or streaming pull would do. Thanks

**Comment by rrs45** [comment]
There is new Rust client for GCP which has support for pub-sub but still in development: https://github.com/mozilla-services/google-cloud-rust

**Comment by atibdialpad** [comment]
Hi Folks, wanted to check how are we doing on this requirement ? Are there any serious blockers which would delay this feature. We are planning to migrate fully from logstash to Vector and this is the one requirement that is stopping us to do  that. We currently use the logstash pubsub source to pull logs from a topic where logs are made avaiable by GCP Stackdriver.

**Comment by jszwedko** [comment]
Hi @atibdialpad ! This is actually on the docket for this quarter so hopefully not too much longer 😄

**Comment by kamalmarhubi** [comment]
@jszwedko nice! does that mean the meta:blocked tag should get removed?

**Comment by joscha-alisch** [comment]
With this quarter coming to a close, is there any update on this @jszwedko? 

This is the last missing bit for us to fully migrate our logstash configuration to Vector, so we are very much looking forward to it :)

**Comment by bruceg** [comment]
@joscha-alisch I am actually planning to work on this this week and hope to complete it in that time frame.

**Comment by joscha-alisch** [comment]
Great @bruceg , thanks!

@ferozsalam , thanks for the workaround - I'll have a look. Although I do suspect this not to be reliable enough for us. We get around 2TB of data through there per day and I'd rather not go with piping this through a local file if avoidable.

**Comment by rrs45** [comment]
@bruceg thanks! we currently use custom tool that subscribes to pubsub with a batch size of 1 and maxwaittime of 45min. We use it for getting GCP log. Looking forward to this new source.
