### ISSUE TITLE
vector sink/source requires authentication/token

### ISSUE THREAD

**Issue by ocrlgv** [vectordotdev/vector#7553]
We are planning to run vector in the cloud as a global endpoint to all our accounts and behind a classic load balancer but realised that there is no authentication at all with vector.
I understand when I asked on discord that the response was that there was going to be an overhaul of the protocol but wanted to know if there's any way to add auth or token based authentication to at least unblock us moving forward?

Being behind a load balancer, it would require a health check method that works with aws network or application load balancer.

Maybe on the new version you can add multi instance auth so eg if an aws is compromised, we can revoke any token that is stolen rather than a global single token that would need to reset on every account/host etc.

**Comment by eplightning** [comment]
I'm using TLS mutual authentication in my setup which works fine with vector sink/source.

It's not perfect mind you, but it works. On top of TLS being complex in general, Vector doesn't support any certificate revocation (I might be wrong here but it seems that way) so you'd have to replace everything in an event of compromise - or use short certificates with really short lifetime.

**Comment by jszwedko** [comment]
Hi @ocrlgv ! This is something we are thinking about for the reimplementation of the vector source/sink protocol. I couldn't find an issue specifically representing that though so we can use this one for that. This overhaul is being worked on now so it should be available in the coming months.

**Comment by ocrlgv** [comment]
yeah "months" may be outside my deployment plans. is there any way to add a simple single token method for now? I'm using nightly for features I've needed. I'm not a rust developer.

**Comment by jszwedko** [comment]
@ocrlgv understood. I don't think it is something we'll add to the existing protocol as this this is just raw TCP over protobuf so we'd need to implement a custom handshake. We do plan to address this with the reimplementation though. Theoretically it could make it out this next month, but I can't say for sure.

For now, my recommendation would be to use TLS for authentication as suggested in https://github.com/timberio/vector/issues/7553#issuecomment-846993191

**Comment by jszwedko** [comment]
Another user request in discord: https://discord.com/channels/742820443487993987/746070591097798688/849611471604547595

**Comment by ahsandar** [comment]
has this made it to a (nightly) release, nothing available in docs on vector.dev.

**Comment by jszwedko** [comment]
Closing this in-lieu of https://github.com/vectordotdev/vector/issues/2017

**Comment by jszwedko** [comment]
(responded over there to the question)
