### ISSUE TITLE
`hdfs` sink: Support writing to HDFS

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#7557]
Requested by user: https://github.com/timberio/vector/discussions/7512#discussion-3372711

They'd like to sink data to HDFS. It seems like using WebHDFS would be sufficient for them. This is also [how fluentd does it](https://docs.fluentd.org/how-to-guides/http-to-hdfs).

**Comment by jeromekleinen-kbc** [comment]
Also logstash has a webhdfs output.

**Comment by vassilevsky** [comment]
WebHDFS is indeed sufficient. It is usually installed alongside HDFS for non-Java apps.

**Comment by zamazan4ik** [comment]
Seems like right now it's should be still possible to write to HDFS with the current Vector with `S3` sink and Apache Hadoop Ozone: https://ozone.apache.org/docs/1.2.1/interface/s3.html

**Comment by Xuanwo** [comment]
Hello, I have added support for `webhdfs`. Please try it out and provide me with your feedback. I am willing to fix any potential bugs. Have a great day!

Hey @spencergilbert, is it okay to close this issue? Any future bug reports should be submitted as a new issue.
