### ISSUE TITLE
Documentation improvement for route

### ISSUE THREAD

**Issue by asyd** [vectordotdev/vector#7607]
Current header doc about `route` transform display:

```
[transforms.my_transform_id]
  # General
  type = "route" # required
  inputs = ["my-source-or-transform-id", "prefix-*"] # required

  # Route
  route."*" = '.status_code != 200 && !includes(["info", "debug"], .severity)' # example
```

It's not clear about the use case, I suggest to have something like:

```
[transforms.my_transform_id]
  # General
  type = "route" # required
  inputs = ["my-source-or-transform-id", "prefix-*"] # required

  # Route
  route.debug = '.level == "debug"'
  route.info = '.level == "info"'
  route.warn = '.level == "warn"'
  route.error = '.level == "error"'
```

**Comment by jeromekleinen-kbc** [comment]
Personally I would also be inclined to add a more explicit comment on what happens to events that don't match any of the routes.

**Comment by spencergilbert** [comment]
> Personally I would also be inclined to add a more explicit comment on what happens to events that don't match any of the routes.

A frequent question that comes up as well.

**Comment by jszwedko** [comment]
Rolling this into https://github.com/vectordotdev/vector/issues/9014
