### ISSUE TITLE
V2 of the Vector source and sink need documentation

### ISSUE THREAD

**Issue by StephenWakely** [vectordotdev/vector#7632]
As mentioned [here](https://github.com/timberio/vector/pull/7618#issue-655212606) there are differences between Version 1 and Version 2, these differences should be documented.

**Comment by binarylogic** [comment]
I'd really like to have @lucperkins involved since this...

1. Requires polymorphism based on some other field (e.g. `version`)
2. Requires deprecation notices / statuses for the polymorphic aspects (e.g. all of version 1 is deprecated)

**Comment by tshepang** [comment]
this looks like it overlaps with #12409

**Comment by jszwedko** [comment]
Closing since the docs reflect v2 now.
