### ISSUE TITLE
Alerting for soak tests

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#7655]
Now that we have the ability to view soak test trends we also want to get automatic alerts when key thresholds are violated. Success for this ticket will send alerts to the team when soak tests violate some as yet to be defined CPU and memory thresholds. If we can establish these alerts in a way that allows per-soaker configuration in the future all's the better. Our goal is to detect regression and each configuration will naturally vary.

**Comment by jszwedko** [comment]
Rolling this into https://github.com/vectordotdev/vector/issues/9946
