### ISSUE TITLE
Add acknowledgements support to `aws_kinesis_streams` sink

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#7660]
Ref #7337

**Comment by 21kyu** [comment]
This issue is still open, but does the `was_kinesis_streams` sink also support acknowledgements?

**Comment by dsmith3197** [comment]
> update) looking at the implementations under `sinks/aws_kinesis`, there doesn't seem to be a part where it retrieves the metadata of the event passed from the source and calls the `update_status()` method.

That's correct. `aws_kinesis_streams` should support acknowledgements due to the code path mentioned above ([ref](https://github.com/vectordotdev/vector/blob/381e38bd7bab6d11d33ce71cf7abcbae9aa70ca9/lib/vector-stream/src/driver.rs#L198)). We can close this issue.
