### ISSUE TITLE
Add Vector acknowledgements support to `splunk_hec` sink

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#7666]
Ref #7337

**Comment by bruceg** [comment]
Noting that the `humio_logs` shares the `splunk_hec` infrastructure, so resolving this may complete support for both.

**Comment by binarylogic** [comment]
Also noting that this differs from the Splunk specific acknowledgements mentioned in #2374

**Comment by jszwedko** [comment]
I think this and #2374 are very related though. If we add support for e2e's acks to the `splunk_hec` sink, I think it should be wired up using Splunk's idea of acknowledgements.

**Comment by jszwedko** [comment]
This was wired up in https://github.com/vectordotdev/vector/pull/10135
