### ISSUE TITLE
Merge the two identical implementations of `sum_metrics` in the API

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#7727]
It would be nice to avoid this code duplication and have just one `sum_metrics` function. The two cases that use `sum_metrics_owned` could use the reference version above but at the cost of an unconditional `clone` for each sum produced. Is that an acceptable cost @leebenson?

_Originally posted by @bruceg in https://github.com/timberio/vector/pull/7699#r643540933_

**Comment by jszwedko** [comment]
This seems like pretty minor tech debt that could be cleaned up as needed when working in that area.
