### ISSUE TITLE
Support `/services/collector` endpoint for `splunk_hec` source

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#7756]
A user expected the Vector `splunk_hec` source to accept events on `/services/collector` which is the first route mentioned on https://docs.splunk.com/Documentation/Splunk/8.2.0/RESTREF/RESTinput#services.2Fcollector . It seems roughly the same as the `/services/collector/event` which we do support so it may just be a matter of aliasing it.

**Comment by jsokol89** [comment]
I am currently experiencing the same issue. `splunk_hec` doesn't handle any of the requests sent over to `/services/collector` - re-routing exactly the same requests to `/services/collector/event` works as expected.

Having an `/services/collector` alias for `/services/collector/event` would be great.
