### ISSUE TITLE
Clean up CI runners periodically to prevent filling up disks.

### ISSUE THREAD

**Issue by tobz** [vectordotdev/vector#7758]
Our CI runners explicitly cache much of their Cargo home directory, which includes the crates.io registry, Git checkouts of crates, and so on.  Over time, as versions are updated, and dependencies are added, this cache grows and grows. We've recently started hitting the limits of our current CI runners in terms of disk usage.  This generates errors on CI runs as the disk is full, which generates false positives for PR check failures, wasting time.

Rather than simply expand the disks, we should simply tweak the OS image used to periodically clean up this cruft.  We can easily accomplish this by installing `cargo-cache` and pointing it at the Cargo home used by CI runners.  This could easily run every night at midnight, or something to that effect.

**Comment by jszwedko** [comment]
Closing since we only use hosted runners now.
