### ISSUE TITLE
Question SDK Mobile

### ISSUE THREAD

**Issue by charleston10** [vectordotdev/vector#7791]
Is there a sdk to use on mobile? (android or ios)

**Comment by jszwedko** [comment]
Hi @charleston10 ! Do you mean that you'd like to run vector (or a subset of it) on Android or iOS to transform / route logs and metrics? We don't currently support something like this, but there has been some discussion of it in #4085

**Comment by leebenson** [comment]
I'll go ahead and close this since it's hung out for a while without a response, but would encourage further [discussion](https://github.com/vectordotdev/vector/discussions) on potential use-cases we've not yet considered.
