### ISSUE TITLE
Add batching to `kafka` source

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#7794]
The `kafka` sources reads data from a stream source, which returns one message at a time. These are then turned into events one at a time. Since our current pipeline only processes events one at a time, this has not introduced significant performance issues. However, with the introduction of acknowledgements into both sources (#7459 #7460) this will result in both a finalization channel and a new task being spawned for each event when the feature is turned on. This is likely to cause significant performance degradation, so we should think about how to improve this situation.

One idea I had was to group messages into a batch by time. That is, after the first message is received, start a short configurable timer (say 1-100ms), and collect all messages received within the interval into a batch and drop the timer. This introduces a delay into starting to handle messages, but guarantees an upper bound on that delay. This solution should apply similarly to both sources.

Another possibility is to use a polling consumer, and fetch all available messages each polling interval. We could minimize the overhead this causes with a backoff on the polling interval, but I'm still less excited about this path.

**Comment by bruceg** [comment]
Note from @lukesteensen on Slack:
> so it's a little confusing with librdkafka because it does those thing under the hood, at least as far as i understand it, we just don't really get that view of it
> it's possible using a lower-level api could help, or maybe even internal batching of our own between components?

**Comment by jszwedko** [comment]
Closing since we'd be unlikely to pick up this issue unless we have another issue around "improve Kafka performance" at which point this strategy could be investigated.
