### ISSUE TITLE
prometheus_remote_writer not working for AWS Managed Prometheus

### ISSUE THREAD

**Issue by george-vieira** [vectordotdev/vector#7814]
Version is current nightly build.

using config

```
[sinks.sink_prometheus]
  type                      = "prometheus_remote_write" # required
  inputs                    = ["aggregate_metrics_*"]
  default_namespace         = "node"
  endpoint                  = "https://aps-workspaces.us-west-2.amazonaws.com/workspaces/...../api/v1/remote_write
```

produces the error:

`... body: b"{\"message\":\"Missing Authentication Token\"}"`

My EC2 instance is in ap-southeast-2 and prometheus is in us-west-2. 
Using a separate EC2 with downloaded prometheus and have it send to AWS prometheus via a remote_writer works fine when specifying `region: us-west-2` and the url containing only up to the workspace id (not containers the /api/ etc). I assume prometheus adds it, no idea?

Would be great if AWS managed prometheus was also supported and what configuration changes would be needed.

This is a blocker for me as we are planning to use AWS Prometheus so will have to use our local prometheus as a proxy to AWS.

**Comment by jszwedko** [comment]
Discussed in discord, but this work is actually represented by https://github.com/timberio/vector/issues/6204 so I'll close this in-lieu. Thanks for bringing it up though @george-vieira !
