### ISSUE TITLE
Build dynamic sources  

### ISSUE THREAD

**Issue by prognant** [vectordotdev/vector#7819]
### Use-cases

Dynamically generate sources for new ressources:
* K8s pods/containers that need more that just stdout logs
* Service published inside directory like consul or etcd

### Proposal
Vector could:
* read annotation or label for k8s (could also serve as an on/off flag for generic pods logs collection)
* read labels for docker container
* read metadata in selected service discovery providers
* etc.

And create the source accordingly.

**Comment by kong62** [comment]
good idea, I need too

**Comment by jszwedko** [comment]
Closing this since we don't have plans to introduce service discovery into Vector (though this could be something we consider in the future).
