### ISSUE TITLE
Rewrite documentation using Remap conditions as examples

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#7832]
The current docs still use the `check_fields` syntax.

https://vector.dev/docs/reference/configuration/tests/
https://vector.dev/guides/level-up/unit-testing/

These should be updated to use the VRL-style checks.

**Comment by mhratson** [comment]
Before docs are updated are there any tests/snippets I could check out?

**Comment by jszwedko** [comment]
Hey @mhratson ! You can check out some examples here: https://github.com/timberio/vector/tree/master/tests/behavior/transforms

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/9377
