### ISSUE TITLE
CSV enrichment transform

### ISSUE THREAD

**Issue by zsherman** [vectordotdev/vector#7843]
A common use case that keeps coming up is the need to augment events with data from local CSV files. Often this can be a lookup on a user, organization or any other custom fields. This should probably work similarly to other transforms like https://vector.dev/docs/reference/configuration/transforms/geoip/, but ideally work in a type safe manner with remap if possible.

Also see https://github.com/timberio/vector/issues/6989.

**Comment by tshepang** [comment]
I think this is done https://vector.dev/docs/reference/glossary/#enrichment-tables

**Comment by spencergilbert** [comment]
Thanks!
