### ISSUE TITLE
Error if assigning a path on a null value

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#7856]
Currently, if `.` is set to a `null` then assigning any paths into it are simply ignored. Instead, we should throw an error at runtime (or possibly compile time if we know the possible types).

This bit a user over here: https://github.com/timberio/vector/issues/7854

This change to allow `null` to be assigned to `.` was introduced with the work to allow mulitple events to be emitted from a `remap` transform in #7267.

**Comment by fuchsnj** [comment]
This now results in a compile-time error if the type is known to not be an object, and you try to assign a field on it.
