### ISSUE TITLE
Auto shutdown after consumed all inputs

### ISSUE THREAD

**Issue by juvenn** [vectordotdev/vector#7880]
### Use-cases

We're trying to use vector to implement ELT(or ETL) pipelines. For example, we have a bunch of log files downloaded **daily** from a vendor, in the form of `logs/*.gz`. By using vector, we can use the `file` source, `remap` transform, and such to sink the logs into a few databases, ES, ClickHouse for example.

All sounds good, except one caveat, vector does not exit automatically. It waits for more from stream.

Ideally, we'd like it exit cleanly after processing all input though. And we'd like to run the pipeline in a daily basis.

### Attempted Solutions

jszwedko@discord has suggested `remove_after_secs` from `file` source, where vector will delete the input files after all done. With a wrapper script we watch the input files, and shutdown vector as soon as they are gone.

I did not try it yet, but I think it should work.

### Proposal

I don't have a proposal at hand unfortunately, but I'll keep mind on it.

**Comment by jszwedko** [comment]
I created https://github.com/vectordotdev/vector/issues/11095 as a blanket issue so I'll close this to move discussion there.

**Comment by breathe** [comment]
Any suggestions for this -- I'd like some way of knowing when vector has consumed (and delivered) all the events from a set of log files ...  Need this for ephemeral hosts so that they can be safely shut down and destroyed ...

**Comment by jszwedko** [comment]
Hi @breathe . Nothing yet, but you can follow along in https://github.com/vectordotdev/vector/issues/11095
