### ISSUE TITLE
Ensure all `sources` have a default address and port

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#7901]
Specifically, for any `source` that accepts network connections we should ensure we have a unique address and port Vector will listen on. This is necessary for enabling ports by default, allowing for dynamic configuration changes without the need to reconfigure firewalls.

**Comment by jszwedko** [comment]
I'm not opposed to defaulting to localhost and a default port for each source, but I think I'm missing what this has to do with reconfiguring firewalls. Supposing that the user wanted to use the non-default port, would this cause issues with what we are trying to do with the aggregator chart?

**Comment by binarylogic** [comment]
When Vector is deployed as an aggregator the common ports need to be available and accessible by upstream clients. This allows sources to be enabled on the fly without requiring system-level or network-level changes. This is critical for the aggregator since, especially when we have the UI, since configuration will be managed by multiple teams simultaneously.

**Comment by jszwedko** [comment]
> When Vector is deployed as an aggregator the common ports need to be available and accessible by upstream clients.

My personal preference here would be to expose the ports corresponding to the sources that Vector is actually listening on as this would:

* Allow users to use non-default ports easily. This is especially important if they want to use multiple of the same source to separate out intake from different senders
* Avoid opening ports that Vector isn't actually listening on. As a sysadmin I'd be a little confused if the firewall was allowing traffic that nothing was actually listening on

I could be convinced that defaulting to allowing traffic to every source's default port is ok, though I need a little more convincing 😄, but will we still allow users to easily configure alternative ports? If so, how?

**Comment by spencergilbert** [comment]
> I could be convinced that defaulting to allowing traffic to every source's default port is ok, though I need a little more convincing 😄, but will we still allow users to easily configure alternative ports? If so, how?

With regards to configuring, should be doable through the chart still 👍

**Comment by binarylogic** [comment]
I'm going to close this since it's solved with the new default configurations for each role. I actually think this is more explicit and discoverable compared to default ports. A user can look at a Vector config and see, immediately, which ports are enabled.
