### ISSUE TITLE
Add template syntax for clickhouse sink "table" param

### ISSUE THREAD

**Issue by ThomasLohner** [vectordotdev/vector#7912]
### Current Vector Version

```
vector 0.14.0
```

### Use-cases

Different logs may require different columns in clickhouse. I would love to create a generic clickhouse sink config that writes to different tables depending on a filed, i.e. `.appname` for syslog messages. The `elasticsearch` sink accepts template syntax for the param `index`. I think this is exactly the same usecase as dynamic tables in clickhouse.

### Proposal

Add template syntax for `table` param in clickhouse sink.

**Comment by malivin** [comment]
is any update here? nice feature

**Comment by spencergilbert** [comment]
It's not on our current roadmap, but we're always happy to help a community member contribute the feature.

**Comment by spencergilbert** [comment]
Closing as a duplicate of https://github.com/vectordotdev/vector/issues/14283 as it mentions more fields.
