### ISSUE TITLE
vrl parse_grok fails if [square brackets] in message 

### ISSUE THREAD

**Issue by ThomasLohner** [vectordotdev/vector#7917]
### Vector Version
```
vector 0.14.0
```

### Expected Behavior

Grok patterns can be enclosed in [square brackets] when these are escaped. See this example of default nginx error log:
```
2021/06/17 21:02:55 [notice] 139720#139720: signal process started

%{DATESTAMP:timestamp} \[%{WORD:serverity}\] %{NUMBER:pid}#%{NUMBER:tid}: %{GREEDYDATA:msg}
``` 

You can test this pattern at http://grokdebug.herokuapp.com

### Actual Behavior

In vrl `parse_grok` square brackets cannot be escaped:

```
$ parse_grok!("2021/06/17 21:02:55 [notice] 139720#139720: signal process started", "%{DATESTAMP:timestamp} \[%{WORD}\] %{GREEDYDATA}")

error[E202]: syntax error
  ┌─ :1:1
  │
1 │ parse_grok!("2021/06/17 21:02:55 [notice] 139720#139720: signal process started", "%{DATESTAMP:timestamp} \[%{WORD}\] %{GREEDYDATA}")
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unexpected error: invalid escape character: \[
  │
```

If square brackets are not escaped the pattern does not match:
```
parse_grok!("2021/06/17 21:02:55 [notice] 139720#139720: signal process started", "%{DATESTAMP:timestamp} [%{WORD}] %{GREEDYDATA}")
function call error for "parse_grok" at (0:131): unable to parse input with grok pattern
```
This is actually correct behavior according to http://grokdebug.herokuapp.com

### Additional Context

The same bug seems to impact parse_nginx_log, because this also does not work:

```
$ parse_nginx_log!("2021/06/17 21:02:55 [notice] 139720#139720: signal process started", "error")
function call error for "parse_nginx_log" at (0:95): failed parsing log line
```

**Comment by ThomasLohner** [comment]
Workaround until this is fixed:

```
$ parse_regex!("2021/06/17 21:02:55 [notice] 139720#139720: signal process started", r'^(?P<nginx_time>\d+/\d+/\d+ \d+:\d+:\d+) \[(?P<severity>\w+)\] (?P<pid>\d+)#(?P<tid>\d+):(?: \*(?P<connid>\d+))? (?P<message>.*)$')
{ "connid": null, "message": "signal process started", "nginx_time": "2021/06/17 21:02:55", "pid": "139720", "severity": "notice", "tid": "139720" }
```

_Originally posted by @nnz1024 in https://github.com/timberio/vector/issues/6103#issuecomment-763834310_

**Comment by jszwedko** [comment]
Thanks for opening this with more detail @ThomasLohner !

I think the issue here is that there is multiple levels of escaping needed. With strings quoted by `"` in Vector, it will attempt to interpret any escape sequences. In this case `\[` is not a valid escape sequence so it throws an error. I could see us maybe just passing those through as-is when `\<character>` does not match an escape sequence. I'm curious what @JeanMertz @StephenWakely think there.

You can work around this by escaping the `\` or by using `s'<your pattern>'` to create a string literal that does not interpret escape sequences. Example:

```
$ parse_grok!("2021/06/17 21:02:55 [notice] 139720#139720: signal process started", "%{DATESTAMP:timestamp} \\[%{WORD}\\] %{GREEDYDATA}")
{ "timestamp": "21/06/17 21:02:55" }
```

Or

```
$ parse_grok!("2021/06/17 21:02:55 [notice] 139720#139720: signal process started", s'%{DATESTAMP:timestamp} \[%{WORD}\] %{GREEDYDATA}')
{ "timestamp": "21/06/17 21:02:55" }
```

Granted, the pattern doesn't seem to be matching the full text here, but it doesn't match when I use it in http://grokdebug.herokuapp.com/ either so it probably needs to be adjusted.

**Comment by jszwedko** [comment]
Ah, I missed your full pattern at the top, that one works:

```
$ parse_grok!("2021/06/17 21:02:55 [notice] 139720#139720: signal process started", s'%{DATESTAMP:timestamp} \[%{WORD:serverity}\] %{NUMBER:pid}#%{NUMBER:tid}: %{GREEDYDATA:msg}')
{ "msg": "signal process started", "pid": "139720", "serverity": "notice", "tid": "139720", "timestamp": "21/06/17 21:02:55" }
```

Or:

```
$ parse_grok!("2021/06/17 21:02:55 [notice] 139720#139720: signal process started", "%{DATESTAMP:timestamp} \\[%{WORD:serverity}\\] %{NUMBER:pid}#%{NUMBER:tid}: %{GREEDYDATA:msg}")
{ "msg": "signal process started", "pid": "139720", "serverity": "notice", "tid": "139720", "timestamp": "21/06/17 21:02:55" }
```
```

**Comment by yxyx520** [comment]
> Ah, I missed your full pattern at the top, that one works:
> 
> ```
> $ parse_grok!("2021/06/17 21:02:55 [notice] 139720#139720: signal process started", s'%{DATESTAMP:timestamp} \[%{WORD:serverity}\] %{NUMBER:pid}#%{NUMBER:tid}: %{GREEDYDATA:msg}')
> { "msg": "signal process started", "pid": "139720", "serverity": "notice", "tid": "139720", "timestamp": "21/06/17 21:02:55" }
> ```
> 
> Or:
> 
> ```
> $ parse_grok!("2021/06/17 21:02:55 [notice] 139720#139720: signal process started", "%{DATESTAMP:timestamp} \\[%{WORD:serverity}\\] %{NUMBER:pid}#%{NUMBER:tid}: %{GREEDYDATA:msg}")
> { "msg": "signal process started", "pid": "139720", "serverity": "notice", "tid": "139720", "timestamp": "21/06/17 21:02:55" }
> ```

I use yaml config do not works
```
transforms:
  transforms_pipelines_test:
    type: remap
    inputs:
      - transforms_prerouting.test
    source: |-
      .tmp_parse_groks = parse_groks!(
        .log.original,
        patterns: [
          s'\[%{GREEDYDATA:test_message}'
        ]
      )
      . = merge(., .tmp_parse_groks)
      del(.tmp_parse_groks)
```
.log.original
```
[2022-02-17T03:16:39.927+0000] log content
```
error log
```
function call error for \"parse_groks\" at (59:145): unable to parse grok: value does not match any rule
```
