### ISSUE TITLE
Expose batches of lines from file source server

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#7935]
The file server library used in the `file` and `kubernetes-logs` sources internally reads lines from source files in batches, but sends them one-by-one down the channel to vector. This leads to extra work being done, as the filename is duplicated for each line sent down the pipeline. Additionally, each line is seen as a separate "batch" for end-to-end acknowledgements, which likely leads to a significant performance degradation when this feature is enabled.

The file server should instead collect together lines from a single file read into one batch, and communicate these batches down the pipeline. This should be a relatively isolated change, so I'm not clear if this should be considered part of the file source modernization epic #6962 or as a follow-up to the data type changes in #7816.

**Comment by jszwedko** [comment]
This strikes me as work that could be done if it is motivated by other desires (like performance).
