### ISSUE TITLE
Log files keep on getting opened and closed

### ISSUE THREAD

**Issue by mkarg75** [vectordotdev/vector#7948]
### Vector Version
```
0.14.0
```

### Vector Configuration File
```
data_dir = "/var/lib/vector"

[api]
enabled = true
address = "127.0.0.1:8686"
playground = true

[sources.kubernetes_logs]
type = "file"
include = ["/var/log/pods/test_log-*/log-generator/*.log"]
read_from = "beginning"

[sinks.kafka]
type = "kafka"
inputs = ["kubernetes_logs"]
bootstrap_servers = "my-cluster-kafka-bootstrap.amq:9092"
topic = "vector-topic"
encoding.codec = "json"
```

### Expected Behavior
We would expect vector to open the log file and keep it open while it keeps reading from it, until the file gets rotated and a new file is being created. 

### Actual Behavior
If the source is configured to use log files, we can see a constant stream of openat() and close() calls onto the respective log files. This behaviour seems to be mitigated by sheer CPU power if vector runs on bare-metal, but exhibits a performance slow-down if vector is run in a container on OpenShift e.g. 

### Example Data
This is an excerpt from vector being run under strace:
```
7448  statx(AT_FDCWD, "/logs/c/log_file1.txt", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=516888897, ...}) = 0
7448  openat(AT_FDCWD, "/logs/c/log_file1.txt", O_RDONLY|O_CLOEXEC) = 9
7448  lseek(9, 0, SEEK_SET)             = 0
7448  read(9, "1 This is a log file line\n2 This is a log file line\n3 This is a log file line\n4 This is a log file line\n5 This is a log file line\n6 This is a log file line\n7 This is a log file line\n8 This is a log file line\n9 This is a log file line\n10 This is a log file line\n11 This is a log file line\n12 This is a log file  line\n13 This is a log file line\n14 This is a log file line\n15 This is a log file line\n16 This is a log file line\n17 This is a log file line\n18 This is a log file line\n19 This is a log file line\n20 This is a log file line\n21 This is a log file line\n22 This is a log file line\n23 This is a log file line\n24 This is a log file line\n25 This is a log file line\n26 This is a log file line\n27 This is a log file line\n28 This is a log file line\n29 This is a log file line\n30 This is a log file line\n31 This is a log file line\n32 This is a log file line\n33 This is a log file line\n34 This is a log file line\n35 This is a log file line\n36 This is a log file line\n37 This is a log file line\n38 This is a log file line\n39 This is a log file line\n40 This is a log file line\n41 This is a log file line\n42 This is a log file line\n43 This is a log file line\n44 This is a log file line\n45 This is a log file line\n46 This is a log file line\n47 This is a log file line\n48 This is a log file line\n49 This is a log file line\n50 This is a log file line\n51 This is a log file line\n52 This is a log file line\n53 This is a log file line\n54 This is a log file line\n55 This is a log file line\n56 This is a log file li"..., 102400) = 102400
7448  close(9)                          = 0
```

Looking at the summary strace gives, the problem is even clearer:
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ------------------
 96.63 4022.515922         259  15477242   4539981 futex
  2.98  124.084944        5243     23666           epoll_wait
  0.25   10.282445           8   1242262      1251 sendto
  0.07    2.995689           5    569756           read
  0.05    2.213527           5    424955           sched_yield
  0.00    0.170256         400       425           fsync
  0.00    0.149565           5     29505        26 statx
  0.00    0.140668           5     25661           write
  0.00    0.111449           8     12398         1 openat
  0.00    0.053515           4     12404           close
```
In this example I used 7 log files only, resulting in roughly 1770 openat() calls per file (Not accounting for opening the config files and other library files of course).

### Additional Context

We found this problem as we tried to get close to the throughput figures published on the vector website, but barely managed to get up to 20000 msgs / sec or ~ 10 MiB / s through vector. On bare-metal the impact is not as bad as in a container but the large number of openat() calls still slows down vector compared to e.g. the internal generator (which is not an entirely fair comparison regardless).

It's totally possible that we're missing a configuration switch here, but we're pretty sure that the call sequence of 
statx() -> openat() -> lseek() -> read() -> close() 
is not desired. 

We can certainly upload the strace captures, but they are huge and easy to re-create. The command we've used is this:
```
strace -o output.txt -s 1500 -C -f -tt vector -c /etc/vector/vector.toml
```
which will follow child processes and add timestamps to every line plus a summary at the end.

**Comment by mkarg75** [comment]
One thing to add: We've tested without kafka to ensure it's not the sink that's slow in this combination. The throughput was identical if we used a tcp sink like netcat on the far end or a vector blackhole.

**Comment by spencergilbert** [comment]
Interesting, do you also see this behavior when using the `kubernetes_logs` source?

**Comment by mkarg75** [comment]
No, with kubernetes as a source the number of openat() calls is significantly lower - there the files are being kept open until the end of our test runs:
```
395   08:19:25.398346 openat(AT_FDCWD, "/var/log/pods/test_log-generator-a687ead7-nt4sw_25c9cff9-b269-4a49-9450-bc7e0663bf57/log-generator/0.log", O_RDONLY|O_CLOEXEC) = 44
395   08:19:25.398388 statx(44, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0600, stx_size=6696000, ...}) = 0
395   08:19:25.398429 statx(44, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0600, stx_size=6696000, ...}) = 0
395   08:19:25.398468 statx(44, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0600, stx_size=6696000, ...}) = 0
395   08:19:25.398509 read(44, "..."..., 8192) = 8192
395   08:19:25.398556 lseek(44, 0, SEEK_SET) = 0
395   08:19:25.398597 write(1, "\33[2mJun 17 08:19:25.398\33[0m \33[32m INFO\33[0m \33[1msource\33[0m\33[1m{\33[0mcomponent_kind=\"source\" component_name=kubernetes_logs component_type=kubernetes_logs\33[1m}\33[0m:\33[1mfile_server\33[0m: vector::internal_events::file::source: Found new file to watch. path=/var/log/pods/test_log-generator-a687ead7-nt4sw_25c9cff9-b269-4a49-9450-bc7e0663bf57/log-generator/0.log\n", 356) = 356
...
310   08:44:31.458552 +++ exited with 0 +++
```

So as you can see the file got opened and not closed before we killed vector under strace, about 27 minutes later.

**Comment by spencergilbert** [comment]
Thanks for all of the details - incredibly helpful

**Comment by jszwedko** [comment]
Would you mind taking a look at this @ktff ? I feel like i'd be well suited for it.

**Comment by ktff** [comment]
@mkarg75 which version of Kubernetes are you using and what platform (EKS, GKS, etc.) if any? Also could you post debug logs for that vector process.

My current idea is that there is some problem in path discovery used in file source, which is different for kube source, and I expect it to depend on either version or platform of Kubernetes.

**Comment by mkarg75** [comment]
I've been using Openshift 4.7.18. What debug logs do you mean? The strace reports? 
I've done the same test on a plain RHEL machine with vector reading from plain old files and the issue with huge numbers of openat() and close() calls is also visible there.

**Comment by ktff** [comment]
@mkarg75 
> What debug logs do you mean?

That's not necessary any more. 

So the file discovery is opening and closing files, kubernetes source has a different discovery so it's not affected. For now this can be mitigated by increasing `glob_minimum_cooldown_ms` option in `file` source, something like `10000` or `60000` should do the trick. I'll see what can be done on our side.

**Comment by ktff** [comment]
So there are some small changes that can be done:
1. Write checkpoints only on change. This will help reduce filesystem calls in idle case.
2. Increase default `glob_minimum_cooldown_ms` to at least 5 sec, maybe 10 sec.
3. Document that increasing `glob_minimum_cooldown_ms` can help with performance issues regarding filesystem calls.

cc. @jszwedko

**Comment by mkarg75** [comment]
I haven't read the code, but what's the reason for the open / close sequence compared to other sources like kubernetes? There the files are being kept open. Is this due to the file-rotation problem? If so, wouldn't inotify be a way to watch for new files while keeping the current ones open?

**Comment by ktff** [comment]
The file discovery searches every `glob_minimum_cooldown_ms` for files and on finding some it opens them to fetch information it needs to identify them. This opening/closing is independent of files currently being open for fetching lines. Kubernetes on other hand knows which files it can expect where based on pod information it's fetching. 

>  Is this due to the file-rotation problem? If so, wouldn't inotify be a way to watch for new files while keeping the current ones open?

From what I see/know Inotify isn't robust enough, especially on Mac, and it doesn't quite help in not idle case where it would notify us all the time since the file is being written all the time. Current solution is quite robust, but it has this performance issue. But either way I'll see if we can do something with Inotify, or at least find out why we can't.

**Comment by spencergilbert** [comment]
> 1. Write checkpoints only on change. This will help reduce filesystem calls in idle case.
> 2. Increase default `glob_minimum_cooldown_ms` to at least 5 sec, maybe 10 sec.
> 3. Document that increasing `glob_minimum_cooldown_ms` can help with performance issues regarding filesystem calls.

The caveat on 2. is that we run into issues (specifically for kubernetes_logs) where entire log files can be lost if they're rotated out before the globbing happens

**Comment by ktff** [comment]
> where entire log files can be lost if they're rotated out before the globbing happens

`kubernetes_logs` won't be affected by 2., but yes that is one of the downsides. I was for the increase from 1 to 5 sec, but considering that it's worse to lose some logs than be less performant the default value should prioritize the logs, so let's go without 2. (also just found https://github.com/timberio/vector/issues/7840 which covers this point) and instead focus on 3.
