### ISSUE TITLE
Update Vector source/sink to allow connections established in either direction

### ISSUE THREAD

**Issue by mikehardenize** [vectordotdev/vector#7949]
### Current Vector Version

```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
```

### Use-cases

We wish to transfer logs between two vector instances using the vector sink and source, however, the host that is generating the logs can not connect to the host which should store the logs, only a connection in the other direction would work. The current implementation of the vector source and sink demands that the tcp connection is established in the other direction. Why not support connections being established in either direction?

### Proposal

Update the vector source so that you can optionally supply an address to connect to (rather than listen on), and update the vector sink, so that you can optionally supply an address to listen on (rather than connect to).

**Comment by jszwedko** [comment]
Unfortunately I think this is unlikely to be something we support for the `vector` source/sink. We do have an for allowing the `socket` source to behave like this though so I'll close this in-lieu of that one, https://github.com/vectordotdev/vector/issues/2042.
