### ISSUE TITLE
Tracing spans should be linked more directly

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#7966]
As of #7929 we have traces in place in vector. In #7965 and #7964 we'll have more, but our tracing regime is an awkward fit considering we don't have a clean transaction like a web service would have. This makes our existing spans very wide or artificially short. Consider the following as potential goals/questions:

* Can we trace the path of an event through its ingress to egress? 
* What do our traces look like if we model each node in a topology as a "service" in the tracing jargon?
* Can we replicate the utilization data already present in vector but from trace info?

Consider that because there's a research, scope narrowing aspect to this ticket we should consider it lower priority than other, more focused work.

**Comment by jszwedko** [comment]
Closing since we dropped tracing https://github.com/vectordotdev/vector/pull/9041
