### ISSUE TITLE
GELF input\output format

### ISSUE THREAD

**Issue by dzirg44** [vectordotdev/vector#801]
Could you consider including GELF log format ? 
This format has some features like gzip compression and native docker support.
what would be nice to have:
  - udp
  - compression
  - docker tags,labels,env's
  - tcp
  - tls(tcp)

I think many people can agree with me, that `logstash` isn't a lightweight solution but we still haven't had any nice alternative . 

_Sorry for my b Eng._

**Comment by binlab** [comment]
Will be great to have this functionality near future!

**Comment by KHiis** [comment]
Any update on the issue?

**Comment by dm3ch** [comment]
FYI: I have tested current ability of vector to work with GELF messages. Here's results of my tests - https://github.com/timberio/vector/issues/4868#issuecomment-782740639

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/issues/4868
