### ISSUE TITLE
Vector Tracing

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#8025]
Inspired by the work in #7638 we believe we can get significant boost in debugging efforts by emitting structured traces from vector internals. This epic captures that work, being completed when we have explicable traces from vector that can be enabled in soak test environment without killing the vector instance. Non-goals are making the feature production safe -- performance degradation is acceptable in the short term -- and exposing an interface for users to gather traces themselves. 

Long-term we will want to enable traces in a manner similar to how we enable metrics, with similar configuration et al. If we can build in that direction cool, but the goal is to get _something_ we can use to good effect in development.

**Comment by jszwedko** [comment]
@lukesteensen it seems to me like we should close this out given #8723 ?

**Comment by lukesteensen** [comment]
Yep! Good catch. If/when we revisit internal tracing we can write up a new issue.
