### ISSUE TITLE
Add benchmarks for `datadog_search` conditions

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8062]
These benchmarks should give us a rough idea of the maximum throughput of these conditions and allow us to measure improvements.

They should cover a set of representative search queries.

**Comment by leebenson** [comment]
@vladimir-dd, I've assigned this to you, as a sibling issue to #10151 to cover benchmarking of Datadog Search Syntax filters/conditions.

**Comment by jszwedko** [comment]
Closing this since it's been deprioritized for the time being.
