### ISSUE TITLE
Vector to vector load balancing & failover

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#807]
Similar to #288, I'd like to see us implement load balancing in the `vector` sink. Since the `vector` sink uses TCP under the hood we should be able to accomplish this once #288 is done. The only open question is failover, which could be considered an alternative load balancing strategy.

**Comment by LucioFranco** [comment]
We should be using tower's middleware to support these use cases.

**Comment by lukesteensen** [comment]
These aren't using request/response protocols, so I'm not sure how tower would fit in.

**Comment by LucioFranco** [comment]
@lukesteensen technically TCP uses ACK to kinda be a response? I think there should be a way to use tower with it. A lot of that state machine for doing reconnects etc are already implemented with tower middleware. Not a big deal just thinking here.

**Comment by lukesteensen** [comment]
I mean _technically_, sure, but none of that is at the application layer :smile:.

I'm sure we could use tower for it. If that makes the code simpler and lets us ship the feature faster, then great, we should use it. I just want to be sure that's the case before we start applying something that isn't obviously a great fit for the use case.

**Comment by LucioFranco** [comment]
@lukesteensen I don't believe in the OSI MODEL! 😄 

Yeah I agree and I am happy to take a look to spec out how that might work before we start working on this.

**Comment by silversupreme** [comment]
Adding a note here that periodic re-resolving all records for DNS names given ("round-robin DNS"), and refreshing the size/entries of the pool based on that, will be a powerful feature that can help set Vector apart from the pack. Very rare to see an agent that does that properly by default, in my experience.

**Comment by sc0rp10** [comment]
I agree with @silversupreme. This would definitely be a useful feature when using many redundant vector servers. The current behavior of the agents is "stick to a random server from the pool and never change the server until the connection fails", which leads to very uneven loading of the servers.

For example, imagine that you have 3 servers with DNS SD (DNS record `vector.foo` resolves to three IP addresses of servers) and 300 agents that pointed to vector sink at `vector.foo:9000`. Ideally the workload will be distributed equally among servers: 100 / 100 / 100 agents per server. But when you restart your servers one by one, agents re-connects to the first available server and workload looks like 300 / 0 / 0, and will never change until server restarted.
This is absolutely real-world experience that annoying our ops.

I think the solution is re-connecting (and re-resolving its address) to the vector sink every N seconds, then after connection restarting, agent picks a random server and workload can be split equally.

What do you think about it, @binarylogic ?

**Comment by krikkiteer** [comment]
just commenting - really would love to see this feature for vector-sinks! :)
failover in vector-to-vector connections would be even higher prioritized (at least for me) than loadbalancing... (which of course also would be nice at some point)

**Comment by NoX1De** [comment]
I'd really like to add a resounding +1 in favor of adding full client-side load balancing/support for multiple log export targets in sink configurations in Vector.  This would be incredibly useful, there are a number of popular/growing in popularity logging solutions that do not have out-of-the-box lb support server-side nor a native log shipper client that implements this feature on the client-side (e.g. LogScale/Humio etc.) the benefit here if Vector implements client-side load-balancing for high volume log shipping would be significant.

Is there any update on if this has made it into the road-map? The value this feature adds helps immensely to simplify logging infrastructure and the value added may be significantly under-appreciated. @binarylogic @jszwedko 

This would reduce/eliminate any need for introducing the administrative/operational overhead of being forced to run separate load-balancing infrastructure in front of logging solution servers to perform load-balancing of distributed log collection across multiple backend logging server cluster nodes performing ingest etc.

Thank you for your time.

**Comment by jszwedko** [comment]
Unfortunately nothing yet. We recognize it would be useful, but is a lot of logic to add into Vector so it's been difficult to prioritize given that load balancers are already a good solution here (even if it does require running additional infrastructure).

**Comment by jszwedko** [comment]
Rolling this up into https://github.com/vectordotdev/vector/issues/18249
