### ISSUE TITLE
aws_kinesis_firehose source fails to respond to GET requests

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8109]
Reported by user: https://discord.com/channels/742820443487993987/759154784309215252/859997827140681739

They captured a GET request from Firehose:

```
GET / HTTP/1.1
X-Forwarded-For: a.b.c.d
X-Forwarded-Proto: https
X-Forwarded-Port: 443
Host: 3.106.36.241
X-Amzn-Trace-Id: Root=1-60dd33d5-6be0b0757df82c7662ee4f6d
[_`l0
[_`l0
7HTTP/1.1 500 Internal Server Error
content-type: application/json
content-length: 87
date: Thu, 01 Jul 2021 03:17:41 GMT
{"requestId":"","timestamp":1625109461908,"errorMessage":"Rejection(MethodNotAllowed)"}
```

This _appears_ to be a healthcheck ping from Firehose but I can't find any documentation on it.

**Comment by anglinb** [comment]
👋  We've been having issues where kinesis firehose will stop sending data to vector, which I believe may have something to do with the health check. I'm going to do some digging to see if I can find more documentation but we have to keep re-creating the delivery stream to restart it 🤷

**Comment by anglinb** [comment]
Reading the docs for Kinesis Firehose, I see no mention of a POST vs GET, it seems that the server may have to respond with a 200 no matter what https://docs.aws.amazon.com/firehose/latest/dev/httpdeliveryrequestresponse.html

**Comment by richardfan1126** [comment]
I've raised an AWS support ticket regarding this issue and they confirmed me that Kinesis Firehose uses POST to send data to custom HTTP endpoint.

Those GET request may be coming from other source (e.g. scanning bot) rather than Kinesis Firehost.

**Comment by anglinb** [comment]
👋 I think you may be right @richardfan1126, the issues with delivery we were having was actually not related to this behavior in the end.

**Comment by StephenWakely** [comment]
I'm closing this as there doesn't seem to be any action we need to take here. If the issues with Kinesis Firehose stopping sending data occurs again, we should raise a separate issue as it seems unrelated to this.

**Comment by amanmahajan26** [comment]
I am facing the same issue. Getting the following error message in vector:

`2023-09-05T14:16:05.658920Z ERROR source{component_kind="source" component_id=firehose component_type=aws_kinesis_firehose component_name=firehose}: vector::internal_events::aws_kinesis_firehose: Error occurred while handling request. error="Rejection(MethodNotAllowed)" stage="receiving" error_type="request_failed" error_code=http_response_500 internal_log_rate_secs=10 request_id=`

This ping request is from the ALB's target group as part of healthcheck. I think that `aws_kinesis_firehose` should support both GET and POST requests for this reason (to ensure that healthchecks don't fail). Am I missing something?

Details: 
Vector version: 0.24
Configuration: 
```
[api]
      enabled = true
    
[sources.firehose]
type = "aws_kinesis_firehose"
address = "0.0.0.0:443" 
access_key = <ACCESS_KEY>
[sources.firehose.healthcheck]
enabled = true

[transforms.parse_firehose_events]
type = "remap"
inputs = ["firehose"]
drop_on_error = false
source = '''
  parsed = parse_aws_cloudwatch_log_subscription_message!(.message)
  . = unnest(parsed.log_events)
  . = map_values(.) -> |value| {
    event = del(value.log_events)
    value |= event
    
  }
'''

[sinks.firehose_sink]
type = "file"
inputs = [ "parse_firehose_events" ]
path = "/tmp/firehose.log"
  [sinks.firehose_sink.encoding]
  codec = "json"
