### ISSUE TITLE
Weird error with conditional in remap

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8114]
Reported by discord user: https://discord.com/channels/742820443487993987/746070591097798688/860292457991372811

### Vector Version

```
vector 0.14.0 (x86_64-apple-darwin 5f3a319 2021-06-03)
```

### Vector Configuration File

```toml
[sources.in]
type = "stdin"

[transforms.remap]
type = "remap"
inputs = ["in"]
source = '''
.timestamp = "foo"
if .value == "string" {
  timestamp_wtz = .timestamp + "+0000"
  .timestamp = parse_timestamp!(timestamp_wtz, "%F %T%.6f %z")
}
'''

[sinks.out]
type = "console"
inputs = ["remap"]
encoding.codec = "json"
```

### Debug Output

```
Jul 01 16:03:52.710  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info"
Jul 01 16:03:52.710  INFO vector::app: Loading configs. path=[("/tmp/tmp.toml", None)]
Jul 01 16:03:52.713  INFO vector::sources::stdin: Capturing STDIN.
Jul 01 16:03:52.715 ERROR vector::topology: Configuration error. error=Transform "remap":
error[E100]: unhandled error
  ┌─ :2:1
  │
2 │ ╭ ╭ if .value == "string" {
3 │ │ │   timestamp_wtz = .timestamp + "+0000"
4 │ │ │   .timestamp = parse_timestamp!(timestamp_wtz, "%F %T%.6f %z")
5 │ │ │ }
  │ ╰─│─^ expression can result in runtime error
  │   ╰─' handle the error case to ensure runtime success
  │
  = see documentation about error handling at https://errors.vrl.dev/#handling
  = learn more about error code 100 at https://errors.vrl.dev/100
  = see language documentation at https://vrl.dev

```

### Expected Behavior

Vector runs.

### Actual Behavior

Vector exits with the given error.

### Additional Context

It works if you remove the conditional.

**Comment by JeanMertz** [comment]
I _suspect_ it's because you are comparing `.value` to `"string"`. We don't know the type of `.value` and thus it errors because comparing an object to a string (f.e.) doesn't make sense.

You could argue it should just return false, but I worry that might obfuscate potential user-errors in assuming a field is of one type, but it being something different.

The error itself could be improved though (cc #7204).

**Comment by roussidis** [comment]
If we change the if block with the block below it works though

`if .value == "string" {
  timestamp_wtz = .timestamp + "+0000"
  .timestamp_wtz = parse_timestamp!(timestamp_wtz, "%F %T%.6f %z")
  .timestamp = del(.timestamp_wtz)
}`

**Comment by jszwedko** [comment]
This doesn't appear to be an issue in v0.26.0.
