### ISSUE TITLE
Add an option which disables reading all existing logs in Kubernetes from the time of cluster creation

### ISSUE THREAD

**Issue by gartemiev** [vectordotdev/vector#8124]
Please add an option so during complete redeployment of vector in Kubernetes to read logs by using Kubernetes source - to read latest logs but not all existing which were created from the vary beginning of K8S cluster creation. Because currently, I didn't notice such option in Kubernetes source.

**Comment by spencergilbert** [comment]
We could expose [`ignore_older_secs`](https://vector.dev/docs/reference/configuration/sources/file/#ignore_older_secs), or the [`read_from`](https://vector.dev/docs/reference/configuration/sources/file/#read_from) options in the `kubernetes_logs` source.

@gartemiev would either of those cover your needs?

**Comment by gartemiev** [comment]
@spencergilbert , I think yes, it would allow to specify starting from what period/position start reading logs

**Comment by briend** [comment]
We would find this very handy; we just want to read from the end/latest (for journald as well as kubernetes logs) and don't need any of the fingerprinting or checkpoint options.

**Comment by jszwedko** [comment]
Closing in favor of https://github.com/vectordotdev/vector/issues/15738
