### ISSUE TITLE
`to_int` VRL function rounds (same as `round` function) numbers

### ISSUE THREAD

**Issue by ypid-geberit** [vectordotdev/vector#8135]
### Vector Version

```
vector 0.15.0 (x86_64-unknown-linux-gnu cac40e1 2021-07-06)
vector 0.14.0 (x86_64-unknown-linux-gnu 5f3a319 2021-06-03)
```

### Vector VRL

```
to_int(1.618)
```

### Expected Behavior

Returns int 1.

### Actual Behavior

Returns int 2.

### Additional Context

"Expected Behavior" is based on the other languages I know, for example Python3. My feeling tells me that the "Expected Behavior" is more common among programming languages.

So it should be at least documented that `to_int` behaves differently than people might expect it when passing a float.

Workaround:

```
to_int(floor(1.618))
```

### References

Related but not relevant for this issue: #3729

**Comment by JeanMertz** [comment]
I agree, `to_int` should discard non-integer parts (e.g. truncate).
