### ISSUE TITLE
Limit Vector config environment variable injection to `${FOO}` but not `$FOO`

### ISSUE THREAD

**Issue by JeanMertz** [vectordotdev/vector#8136]
Vector supports environment variable injection in its config using `${FOO}` and `$FOO` (see [docs](https://vector.dev/docs/reference/configuration/#environment-variables)).

Unfortunately, this means that regex capture group references (e.g. `$1`) are also treated as environment variables, and thus get filtered out of the final config.

Basically, this:

```coffee
replace(msg,r'(auth=token)(.*?):(.*?)(\S{8})&', "$1$2:*$4&")
```

Becomes this:

```coffee
replace(msg,r'(auth=token)(.*?):(.*?)(\S{8})&', ":*&")
```

(assuming neither `$1`, nor `$2` and `$4` are actually set as environment variables)

People are running into this problem (#7445,  #8067), and aren't sure what is going on.

The solution is to escape `$` using `$$1`, but this isn't as discoverable as we'd like.

Interestingly, the [Vector documentation](https://vector.dev/docs/reference/configuration/#environment-variables) does _not_ mention `$FOO` as a way to reference environment variables, only mentioning `${FOO}` as valid syntax.

I wonder if we should **ignore** `$FOO` variables, such that `$1` etc work as expected. Obviously, this is a breaking change, and one that I wouldn't have proposed if the documentation had mentioned this feature, but since it does not, I figured it's worth raising this as a potential solution.

Alternatively, we can have Vector error on boot if it tries to substitute a non-existing environment variable, which would make it more clear what's going on, but might also potentially be annoying to people who don't care whether a variable is set or not.

cc @jszwedko

**Comment by hhromic** [comment]
> The solution is to escape `$` using `$$1`, but this isn't as discoverable as we'd like.

This is exactly how [variables substitution](https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution) works too in Docker Compose files. So for me this is not "surprising".

Their documentation is quite clear and explicit:
> You can use a $$ (double-dollar sign) when your configuration needs a literal dollar sign. This also prevents Compose from interpolating a value, so a $$ allows you to refer to environment variables that you don’t want processed by Compose.

The current Vector variable substitution works very similar (if not exactly the same?) to the Docker Compose one, making me feel very "familiar already" with how it works out of the box.

So in my humble opinion, I think is better to document this behaviour better in Vector and maintain consistency with other widely used tools. Senior developers will be thankful :)

**Comment by hhromic** [comment]
I re-read again the Docker Compose documentation and they actually address this "confusion" nicely:

> If you forget and use a single dollar sign ($), Compose interprets the value as an environment variable and warns you:
> The VAR_NOT_INTERPOLATED_BY_COMPOSE is not set. Substituting an empty string.

Maybe this is what Vector could do as well to help?

**Comment by jszwedko** [comment]
We do actually currently output a warning that is somewhat similar:

```
Jul 06 09:56:18.290  WARN vector::config::loading: Unknown env var in config. name = "1"
```

We could maybe highlight it more though.

I agree that continuing to support `$FOO` seems reasonable. It is unfortunate that `$` is used for replacement capture groups too though as I can see it is very easy to get tripped up by that if you aren't aware of Vector's env var replacement.

**Comment by JeanMertz** [comment]
I should note that we've also had reports of users running into this when they try to access an event field with a `$` in it, e.g. `."$id" = "foo"` would be converted to `."" = "foo"`, which results in an error.

**Comment by JeanMertz** [comment]
I suspect this ship has sailed, so I'll close this issue. We can re-evaluate this if more problems arise.
