### ISSUE TITLE
Initial AWS EKS support

### ISSUE THREAD

**Issue by timberio-campfire** [vectordotdev/vector#814]
We'd like to officially support Amazon's EKS platform.

<p></p>

1. We should start with a specification to determine the best path forward.

2. Its possible this might just wrap existing sources.

3. Its possible this might just be an installation page in our documentation.

**Comment by timber-productboard** [comment]
Link to feature: https://timber.productboard.com/feature-board/planning/features/2784927

**Comment by LucioFranco** [comment]
@binarylogic I think this makes sense, do we also want to open a more generic kube issue since I believe the implementation that will work for eks will work for any kube deployment?

**Comment by binarylogic** [comment]
Yes, #260 handles that.

**Comment by ktff** [comment]
Current Kubernetes implementation in #893 was tested with AWS EKS ec2 cluster, and it works out of the box. Except of one bug found during testing.

So as @binarylogic said, this will be solved with #260. I anticipate that only retesting it on EKS will be needed.

**Comment by LucioFranco** [comment]
There is nothing to spec out here. Our current kube implementation covers this. What we will need is deployment guides around kube in general and these can be applied to EKS just like how you might apply it to any other kube cluster. Based on that I think this issue can be closed technically?

cc @binarylogic

**Comment by ktff** [comment]
I wouldn't close this issue until #1060 is implemented. The reason being that `namespace` information is necessary on EKS to properly filter out system logs. #893 on it's own isn't capable of doing that on EKS. Although, the number of system logs isn't large, it would still bother users.

**Comment by LucioFranco** [comment]
@ktff I've updated #1060 to include that additional filter.

**Comment by Alexx-G** [comment]
Is there anything Vector is missing for AWS EKS and it should be considering when deploying there? I've deployed it to AWS EKS (on managed worker nodes) and didn't notice any issues so far. However, it's still being validated in a staging environment.

**Comment by ktff** [comment]
@Alexx-G No, everything is in place, not only for EKS, but basically for any Kubernetes, with exception of Kubernetes backed by Windows nodes which they started recently supporting. But I would wait for 0.9 release as there is a breaking change in how Vector should be run, more specifically #2188.

**Comment by Alexx-G** [comment]
@ktff Thanks for details! I was expecting `0.9` to have breaking changes and there's a number of fixes I need, so this is fine. 
Since https://github.com/timberio/vector/pull/1888 has been merged, I suppose after `0.9` you don't expect any breaking changes (at least for event schema for kubernetes source)?

**Comment by binarylogic** [comment]
@Alexx-G that's the goal. `0.10.0` is the "Kubernetes Release", where we will officially announce the integration. I don't foresee any major changes between `0.9.0` and `0.10.0`, but we will also be rigorously QA'ing the integration during that time.

**Comment by MOZGIII** [comment]
We should verify things work as expected before we consider this done.

**Comment by binarylogic** [comment]
Just clarifying the work here. We should verify and test this, possibly even add an integration test, but we should defer for it now. We have an epic to verify integration with a variety of hosted K8s platforms.

**Comment by MOZGIII** [comment]
I've started working is this. Apparently EKS integrations breaks in unexpected places, so I'll create issues to fix what I've found.

**Comment by Dragotic** [comment]
Hello, any news about the AWS EKS Support?

**Comment by jszwedko** [comment]
I'll close this since we do have people running Vector on EKS, but we can open up follow-up issues if there is any support lacking.
