### ISSUE TITLE
Datadog sources/sinks update to support Datadog API v2

### ISSUE THREAD

**Issue by prognant** [vectordotdev/vector#8141]
As shown here https://github.com/DataDog/datadog-agent/pull/8555 the datadog agent is going to support a new API version, it does not change a lot of things but we probably should support the v2 API in both datadog_logs source & sink.

**Comment by vladimir-dd** [comment]
I'll created a dedicated issue for sink #9297

**Comment by prognant** [comment]
Closing as both `datadog_logs` sink & `datadog_agent` sources now support API v2 for logs.
