### ISSUE TITLE
VRL compiler improvements

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8221]
## Summary
VRL is a cornerstone of Vector. As such, we'd like to spend some time on compiler improvements to improve the UX.

## Requirements
- [ ] #13031
- [ ] #13032
- [ ] https://github.com/vectordotdev/vector/issues/11773
- [x] #12686

**Comment by JeanMertz** [comment]
Closing this issue, as all listed items have been either solved, or moved into dedicated issues, tracked in this [Compiler Improvements milestone](https://github.com/vectordotdev/vector/milestone/89).
