### ISSUE TITLE
Validate website links, internal and extermal

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#8228]
As part of moving to the new website we should validate internal and external links. The old site used a short link system that automatically validated links as part of the markdown generation process. Because we no longer have a generation process we should consider another method to validate links. Ideally this would be a PR check that runs against the changes in the PR. For example, [this plugin](https://github.com/Munter/netlify-plugin-checklinks).

**Comment by jszwedko** [comment]
CI does check for broken links.
