### ISSUE TITLE
document breaking change in vector source/sink

### ISSUE THREAD

**Issue by JeanMertz** [vectordotdev/vector#8239]

**Comment by tshepang** [comment]
is this a version 1 vs version 2 thing, or is it something else

**Comment by JeanMertz** [comment]
Good question @tshepang. This is about the upgrade from v1 to v2. We did document how to upgrade, but didn't document any breaking changes. I don't have those changes top-of-mind, but I believe there were minor differences.

We still do support v1, but default to v2, so at some point when we force people to use v2, we need to inform them how it _might_ impact their data.

**Comment by jszwedko** [comment]
Closing this as I believe all undocumented changes have had issues filed around them.
