### ISSUE TITLE
Revamp the generator source to be useful for performance work 

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#8249]
We have a generator source in place in vector for testing purposes but it is far, far too slow for performance work. In [lading](https://github.com/blt/lading) we have been experimenting with a similar process but with stable throughput. That project has evolved a 'common' library with the eventual goal of unification into vector somehow for the purposes of resolving tickets just like this one. We might also prefer to use the basic technique of lading -- pre-build a large buffer of input before emission -- and avoid any of the throughput controls that lading has.

**Comment by blt** [comment]
Alright, in looking at this in earnest I have learned some things. Firstly, here's how the generator source bills itself today:

> Generate fake events, which can be useful for testing, benchmarking, and demos

That's three use cases:

* testing
* benchmarking
* demos

In practice _I_ had only ever encountered the benchmarking use case, a problem as the source is not suitable for that kind of work. The source's defects are that it generate line-at-a-time, lumps additional functionality into each line generation -- true randomness, parsing, event manipulation -- and has an awkward interval-per-chunk method of describing load goals. These defects inspired this ticket and they're straightforward to address by removing functionality, generating ready-made `Event` instances in blocks.

However. The changes necessary to support loading vector internals undermines the other two use cases, demo-ing most of all. For instance, to support a benchmark use case we would want to drop as much work per-Event as possible, implying the framing/decoding options would go. We expect these to be useful in demoing vector to users, a problem. Testing _seemingly_ is mostly concerned with `format` option but if we drop true randomness from the generation loop we potentially undermine that as well. There are two many use cases for the current generator source to support at once and it appears from talking with folks that the order of importance is:

* demo
* testing
* benchmark 

This is maybe a self-fulfilling ordering considering how poor the source is at generating load but that's what we've got today. I _think_ the reasonable thing to do here is drop the 'benchmark' use case from the source and strike it from the documentation, possibly with pointers to extra-vector load generation methods. @binarylogic proposed renaming `generator` to `demo` and adding a new load-oriented source. That could work. The format generation crate -- based on fakedata -- could probably be reworked to support a `demo` and a `load` source without impacting the interface of either source. 

The ultimate question to answer here is: do we believe that load generation in-vector is valuable enough to warrant a new source? Today we're well served in soak tests by extra-vector load generation and there's no reason why we couldn't document that kind of set up for users. Our soak tests are meant to be run by anyone with access to enough CPUs, memory, for example.

**Comment by tobz** [comment]
I'm personally a little worried about the notion of depending on Vector to generate load for itself in the sense of having that perturb the performance of downstream components in the pipeline that we're observing.. but I think if we're OK with a little perturbation -- basically, as long as it hurts performance equally across different runs -- then it's probably fine.  We can likely make it fast enough to saturate anything unless we're on an otherwise very resource-constrained host.

If nothing else, it _would_ almost certainly pollute profiling output.

**Comment by blt** [comment]
> If nothing else, it would almost certainly pollute profiling output.

That's the killer to me. What I had in mind when I originally wrote this ticket was a quick spruce-up that would make the generator source not so surprisingly slow, since it's something I see stick the team now and again. But if we were to _actually_ use the source for, say, soaks we'd absolutely pollute the profile and would end up over-stressing the scheduler in a non-representative way. So it's this weird middle ground of only being useful for quick-and-dirty things but without necessarily being representative. 

Based on what I've learned I'm inclined to say writing something in-vector is not super duper useful, adjusting `generator` -> `demo` and changing the docs to note that it's _not_ useful for profiling is the way to go.
