### ISSUE TITLE
Allow vector to track its own CPU / memory consumption

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#8251]
Today vector is unable to track its own process' CPU and memory consumption. We would like to achieve this in a cross-platform manner. Our integration with [heim](https://github.com/heim-rs/heim) appears to have preliminary support for process tracking, covering exactly what we are concerned with in this ticket. We might also consider using the libc/windows crate directly.

**Comment by spencergilbert** [comment]
Does `heim` seem a little unmaintained? It doesn't seem super active at the moment

**Comment by blt** [comment]
It's not terribly active. Short of maintaining something heim-like in vector itself I don't know of a better option. We might contact the author and ask if they'd appreciate a hand.

**Comment by spencergilbert** [comment]
I'd definitely think helping to support `heim` > rebuilding inhouse

**Comment by jszwedko** [comment]
Agreed, I think we'd are in a good position to contribute to `heim` if they are open to it.

**Comment by jszwedko** [comment]
Closing in favor of https://github.com/vectordotdev/vector/issues/3530
