### ISSUE TITLE
Website configuration examples for filter component is showing json config rather than toml

### ISSUE THREAD

**Issue by ross** [vectordotdev/vector#8305]
### Vector Version

Website as of 2021-07-14T00:30:58Z

### Expected Behavior

Configuration examples for the filter component should show toml, but it's json.

URL: https://vector.dev/docs/reference/configuration/transforms/filter/#examples

### Actual Behavior

The configuration snippet is showing `json`, 2nd code snippet box:

<img width="1804" alt="Screen Shot 2021-07-14 at 5 31 45 PM" src="https://user-images.githubusercontent.com/12789/125709777-449ec1fa-a437-456a-b1fe-bc7d6931c5d4.png">

Not sure if it's just this one or others are affected too. I've spot checked a couple and haven't found any w/example sections that are broken, but didn't check them all.

This is closely related to https://github.com/timberio/vector/issues/8304

**Comment by ross** [comment]
Looks like there are at least some others that show json, just ran across https://vector.dev/docs/reference/configuration/transforms/aggregate/#examples.

**Comment by lucperkins** [comment]
This aspect of the docs could use some further polish but I think that #8274 covers this initial issue
