### ISSUE TITLE
VRL comment inside of `if` block with `'` causes a syntax error

### ISSUE THREAD

**Issue by ross** [vectordotdev/vector#8326]
### Vector Version

```
vector 0.14.0 (x86_64-unknown-linux-gnu 5f3a319 2021-06-03)
```

### Vector Configuration File

VRL snippet from a remap source.

```
if contains!(.message, "bytes_rx=") {
  # it's a connection/request
  .log_type = "request"
}
```

### Expected Behavior

Valid VRL. An if with a comment inside the branch.

### Actual Behavior

```
vector_1   | error[E202]: syntax error
vector_1   |   ┌─ :1:1
vector_1   |   │
vector_1   | 1 │ ╭ if contains!(.message, "bytes_rx=") {
vector_1   | 2 │ │   # it's a connection/request
vector_1   | 3 │ │   .log_type = "request"
vector_1   | 4 │ │ }
vector_1   | 5 │ │
vector_1   |   │ ╰^ unexpected error: invalid literal
vector_1   |   │
vector_1   |   = see language documentation at https://vrl.dev
vector_1   |
```

### Additional Context

If i remove the comment it compiles fine.

**Comment by ypid-geberit** [comment]
I have been using comments in branches without issues so I was wondering. The actual issue seems to be the combination of "within an `if` block" and the comment having `'` at some spots. 

Workaround would be to not use `'` or use the typographically correct `’` 😉 This works:

```
if (contains!(.message, "bytes_rx=")) {
  # It’s a connection/request.
  .log_type = "request"
}
```
