### ISSUE TITLE
Expose pod annotations in kubernetes_logs

### ISSUE THREAD

**Issue by djablonski-moia** [vectordotdev/vector#8338]
### Current Vector Version

```
vector 0.14.0 (x86_64-apple-darwin 5f3a319 2021-06-03)
```

### Use-cases

For some workloads being managed by an operator, it is not possible to add pod labels, so you have to fall back to annotations (e.g. `istio-operator`).

Since pod annotations are not exposed, I cannot handle the logs properly.

### Attempted Solutions

none

### Proposal

Expose pod annotations, maybe optionally, being disabled by default.

**Comment by aquarhead** [comment]
Hello, is there any progress on this? I'd like to contribute if there's no existing effort, cheers.

**Comment by spencergilbert** [comment]
Hey @aquarhead! We don't currently have anyone working on this and would be happy to accept a PR, feel free to tag me for review or drop into our discord if you have any questions.

**Comment by djablonski-moia** [comment]
Thank you! 😀
