### ISSUE TITLE
Add socket_file_mode to the socket source like in dnstap.

### ISSUE THREAD

**Issue by ronaldfenner** [vectordotdev/vector#8352]
Currently when using a socket source with a unix socket the socket is created with the proper owner/group however the socket is only useable by a service with the same owner. It was pointed out that dnstap source has the socket_file_mode parameter to set the file mode so it would be nice if the socket source could gain the same functionality so you can set the mode in the config for the soccket.

**Comment by jszwedko** [comment]
Closing in-lieu of https://github.com/vectordotdev/vector/issues/9241 which has more details.
