### ISSUE TITLE
Enable k8s end to end tests for all pull requests

### ISSUE THREAD

**Issue by StephenWakely** [vectordotdev/vector#8362]
Currently the k8s e2e tests are only run on pull requests that have the labels  `ci-condition: k8s e2e all targets` and `ci-condition: k8s e2e tests enable` added to them.

Given the tests now run in approximately 20 minutes eg. [this one](https://github.com/timberio/vector/pull/8287/checks?check_run_id=3088286914), we should look to enabling the tests for all pull requests.

**Comment by jszwedko** [comment]
Closing since we haven't decided to do this yet.
