### ISSUE TITLE
`parse_grok` VRL function: Support to create nested fields from within pattern

### ISSUE THREAD

**Issue by ypid-geberit** [vectordotdev/vector#8382]
### Current Vector Version

```
vector 0.16.0 (x86_64-unknown-linux-gnu b8a891a 2021-07-20)
vector 0.15.0 (x86_64-unknown-linux-gnu 994d812 2021-07-16)
```

### Use-cases

I would like to use `parse_grok` to parse a log and create nested fields from within the pattern. The reason for this is that with [ECS](https://www.elastic.co/what-is/ecs) nested fields are quite common so I would like to avoid workarounds as discussed in #4465. Logstash supports to create nested fields using the `grok` "filter".

### Attempted Solutions

I tried this Vector VRL expression:

```
parse_grok!("info", "%{LOGLEVEL:log.level}")
```

But that returns this object:

```json
{ "log.level": "info" }
```

Then I tried the syntax that works in Logstash to create nested fields:

```
parse_grok!("info", "%{LOGLEVEL:[log][level]}")
```

Same issue:

```json
{ "[log][level]": "info" }
```

### Proposal

```
parse_grok!("info", "%{LOGLEVEL:log.level}")
```

should return:

```json
{ "log": { "level": "info" } }
```

I would argue that this is worth "breaking backwards compatibility" because nested fields are probably more common. Something like this could be supported to create a literal field `log.level`:

```
parse_grok!("info", "%{LOGLEVEL:[log.level]}")
```

With that, probably even

```
parse_grok!("info", "%{LOGLEVEL:[log][level]}")
```

should be supported to make it behave the same as Logstash. Ref: https://www.elastic.co/guide/en/logstash/current/event-dependent-configuration.html#logstash-config-field-references

### References

- #4465 Basically the same issue but it was tried to do this without VRL so I created this new issue to restate the issue clearly.

**Comment by jszwedko** [comment]
Yeah, this makes sense to me. Thanks for suggesting @ypid-geberit !

**Comment by atibdialpad** [comment]
any news on this front ?

**Comment by JeanMertz** [comment]
There's ongoing work for a new function `parse_groks`, which has this feature. We're discussing how to port this over to the `parse_grok` function.

See: https://github.com/vectordotdev/vector/issues/10287

**Comment by jszwedko** [comment]
Closing since this'll be covered by https://github.com/vectordotdev/vector/issues/12612
