### ISSUE TITLE
Add `bytes_in_total` and `bytes_out_total` for transforms

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8405]
Given https://github.com/timberio/vector/pull/8396 added a way to calculate the in-memory size of events I think we can add these `bytes_in_total` and `bytes_out_total` to transforms.

**Comment by bruceg** [comment]
I think we should take care with this one. As indicated, the size calculated in #8396 is an in-memory size (not counting alignment overhead, of course). By contrast, other `bytes` metrics are calculating the serialized size of events. These two numbers will be roughly proportional, but could be significantly different for events with small data but complex structures. It is worth noting the distinction in case the byte size would not be an adequate approximation.

**Comment by jszwedko** [comment]
Yeah, agreed, this will need some thought around how we explain what these values mean to users. We could even separate the metrics like: `serialized_bytes_in_total` / `serialized_bytes_out_total` for sources / sinks respectively where they would also have the same `bytes_out_total` / `bytes_in_total`, again respectively.

**Comment by jszwedko** [comment]
Closing this since we added the estimated JSON measures in #14801
