### ISSUE TITLE
Customizable template syntax delimiters

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#8410]
https://vector.dev/docs/reference/configuration/template-syntax/#event-fields

The current `{{ ... }}` syntax clashes with Helm and causes a lot of headache when configuring Vector via our Helm charts.

We should allow for configuration of the delimiters to make configuration easier for users.

Ref: https://svn.python.org/projects/external/Jinja-1.2/docs/html/altsyntax.html

**Comment by spencergilbert** [comment]
See some examples of painful config that includes curly braces: https://github.com/helm/helm/issues/2798

**Comment by LinTechSo** [comment]
Hi, same issue, any updates?

**Comment by jszwedko** [comment]
Duplicate of https://github.com/vectordotdev/vector/issues/7586

**Comment by szibis** [comment]
> Hi @LinTechSo - this work has yet to be prioritized but does have a workaround, see [here](https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/README.md#using-template-syntax-in-customconfig) where I included Vector templates within a helm templated file.

Will not work just as example in https://github.com/vectordotdev/vector/issues/7586. When using helmfile for example with helm we will have double templating in place which needs to be double escaped and this is crazy.
