### ISSUE TITLE
Add integration tests for `datadog` sources and sinks

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8442]
To catch things like https://github.com/timberio/vector/pull/8441

The tests should run in CI and hit a real Datadog account to validate compatibility.

**Comment by blt** [comment]
Also https://github.com/vectordotdev/vector/issues/9484 and #9475

**Comment by jszwedko** [comment]
Related: https://github.com/vectordotdev/vector/issues/10249
