### ISSUE TITLE
`vector top` doesn't shutdown on `esc`, `q`, or `ctrl-c` if  `vector` is shutdown before it

### ISSUE THREAD

**Issue by ktff** [vectordotdev/vector#8449]
### Vector Version

```
vector 0.15.0 (x86_64-unknown-linux-gnu 994d812 2021-07-16)
```

### Vector Configuration File

Any with `api` enabled.

### Expected Behavior

`vector top` closing on `esc`, `q`, or `ctrl-c`.

### Actual Behavior

`vector top` stalls.

### Steps to reproduce it

1. Run  `vector -c ./...` with any config with `api` enabled.
2. Start `vector top`.
3. Shutdown `vector -c ./...` and wait for it to finish.
4. Try to close `vector top` which will then stall with just this printed in the console
```
Jul 25 11:28:37.566  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info" enable_datadog_tracing=false


```

### References

#7757 is maybe relevant.

**Comment by leebenson** [comment]
I suspect we just need to bring signal handling up to the subcommand level to explicitly quit the process.

**Comment by apollo13** [comment]
One observation that I just made is that if I shutdown the normal vector process `vector top` uses 100% of a single CPU on my system. So it might be that it also enters a busy loop here that might (?) prevent the handling of the signal.

**Comment by leebenson** [comment]
@apollo13, that's a good thought, though I suspect that's actually a separate issue.

Locally, CTRL+C doesn't respond even during an active connection, when `vector tap` has a CPU load of ~1-2%.

When the main Vector process quits (the one being observed), CPU spikes to 99%+.

I'll open a separate issue to track that.
