### ISSUE TITLE
`datadog_events` sink requires pruning keys for use

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8486]
Noted by @atibdialpad in https://github.com/timberio/vector/issues/7218#issuecomment-888258647

If this is something that is required, we should handle it at the sink level.

**Comment by ktff** [comment]
The sink is pruning keys, there is a test for it `filter_out_fields`, but it seems something is passing it. 

@atibdialpad could you post example of an event that isn't being delivered to Datadog, but is if it's manually pruned.

**Comment by jszwedko** [comment]
Closing since this is stale. If you do have an example @atibdialpad feel free to re-open this.
