### ISSUE TITLE
Standardize metric encoding

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8494]
Standardize metric encoding support so that users can decode JSON (or other data) as metrics directly

* Create a standard JSON encoding for metrics
* All sources and sinks that accept logs should also accept metrics

**Comment by jszwedko** [comment]
👍 I think your sense is right, that we should just consider what it means to encode `Event` generally.

**Comment by tobz** [comment]
Closing this in favor of #9930, which explores encoding/decoding of native Vector events in general, and not just metrics.
