### ISSUE TITLE
Memory usage keeps increasing with many short lived pods

### ISSUE THREAD

**Issue by Mrngilles** [vectordotdev/vector#8500]
### Vector Version

```
vector 0.15.0 (x86_64-unknown-linux-gnu 994d812 2021-07-16)
```

### Vector Configuration File

Sorry, I am using the helm chart and just have a configuration as Yaml.
```yaml
sinks:
  elasticsearch:
    type: "elasticsearch"
    inputs: ["parser"]
    doc_type: "_doc"
    request:
      concurrency: adaptive

transforms:
  parser:
    type: remap
    inputs: ["kubernetes_logs"]
    source: |-
      message, err = parse_json(.message)
      if err == null {
          if is_object(message) {
              merged, err = merge(., message, deep: true)
              if err == null {
                  . = merged
              }
          }
      }

      .@timestamp, err = to_timestamp(.@timestamp)
      if err != null {
          .@timestamp = now()
      }

      .timestamp, err = to_timestamp(.timestamp)
      if err != null {
          .timestamp = now()
      }
```

### Expected Behavior

I would expect a stable"ish" memory usage

### Actual Behavior

The memory usage keeps increasing as the number of pods created and destroyed increases

### Example Data

I can observe the memory following perfectly the number of `files_added` and `files_unwatched`

### Additional Context

This is running in Kubernetes

**Comment by jszwedko** [comment]
This seems likely to have been due to increased internal metric cardinality due to tagging metrics with `file`. An option to expire metrics was added in a recent version of Vector (I believe 0.24.0?) that can be used to allow these internal metrics to expire and reduce memory usage.

I'll close this, but if you upgrade and still see this, please reopen.
