### ISSUE TITLE
Move sink `request` configuration into `SinkOuter`

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#8513]
Most of the sinks accept a `request` group of settings to configure how they make requests. As suggested in https://github.com/timberio/vector/pull/8205#discussion_r679176310 we should consider moving this into `SinkOuter` to provide it in common to all sinks (to be ignored by those that don't support it). Turning this `TowerRequestConfig` into `TowerRequestSettings` requires a set of defaults that are custom to the particular sink, so this could be handled centrally by adding a method to `trait SinkConfig` that returns said defaults.

**Comment by lukesteensen** [comment]
This seems reasonable, though I do think that we'd still want to return an error if it's configured on sinks where it doesn't apply. Silently ignoring things can lead to a lot of confusion for users.

**Comment by jszwedko** [comment]
Closing this since I think we especially won't want to do it now that the documentation is being generated from configuration structs and we wouldn't want the `request` configuration to appear on components that do not support it.
