### ISSUE TITLE
clickhouse sink table key is a string, not template-able

### ISSUE THREAD

**Issue by haithem-b-charrada** [vectordotdev/vector#8528]
Hi there, the Docs say that the table key is a string, not template-able in clickhouse sink 
i'am trying to sink data in a table depending on attribute value

**Comment by Steuf** [comment]
It's will be a good feature to add template on "table" and "database" param. In my (extreme) use case I have to setup sink on 3 databases and 5 table by database. 

Actually I have 15 sink setup for clickhouse (:/) and the real problem are in this case that the buffer max_size are difficult to setup ;)

**Comment by haithem-ben-charrada** [comment]
@jszwedko

**Comment by haithem-ben-charrada** [comment]
👍

**Comment by jszwedko** [comment]
Duplicate of https://github.com/vectordotdev/vector/issues/7912
