### ISSUE TITLE
Role specific systemd file (aggregator / agent)

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#8531]
To unify the setup experience that we're introducing in the Vector Helm charts, we should consider adding role specific Systemd files for both the aggregator and agent roles. This will allow users to setup Vector for their use case with reasonable defaults. For example, it's a much better user experience to install the aggregator with common sources (`syslog`, `fluent`, `logstash`, `vector`, etc) than it is to force users through the tedious process of configuring all of this. Systemd file can also specify system resource, like ports, so it should be a mostly turn key install for users.

**Comment by jszwedko** [comment]
Closing since we decided not to do this.
