### ISSUE TITLE
Support dropping deleted files in `file` source

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8591]
Requested by user in https://github.com/timberio/vector/issues/8101#issuecomment-889720409

The user would prefer to lose the unread logs than hold onto the deleted files as it is causing disk space pressure issues for them.

I think we could support this as an option on the `file` and `kubernetes_logs` sources.

**Comment by szibis** [comment]
Any plans for this feature to be implemented ?? In bigger setups, this is very important because Vector is holding a lot of files, and space on drives is shrinking a lot.

**Comment by jszwedko** [comment]
Hi @szibis . It hasn't been scheduled yet. Of course, we are always open to contributions 🙂

**Comment by aenshin-pp** [comment]
The same thing just happened to us - disk usage grew up, other Pods were evicted. Fun time for our production :)

Is there any good solution for this?

**Comment by jszwedko** [comment]
This is actually supported now via https://vector.dev/docs/reference/configuration/sources/file/#rotate_wait_secs which was added by https://github.com/vectordotdev/vector/pull/18904. I think we neglected to close this issue.
