### ISSUE TITLE
Make it even clearer that internal log rate limits refer to the log and not events

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8635]
In #5223 we attempted to make it clearer that the internal log rate limiting was specific to the log and not that Vector was actually rate limiting events.

This is still confusing people though: https://github.com/timberio/vector/discussions/8634 . We should attempt make it even clearer.

**Comment by DimitriosPrasakis** [comment]
+1

**Comment by jszwedko** [comment]
Duplicate of https://github.com/vectordotdev/vector/issues/996
