### ISSUE TITLE
Retries are not moderated by rate limiting.

### ISSUE THREAD

**Issue by tobz** [vectordotdev/vector#8647]
Based on how we construct our instances of `PartitionBatchSink` and `BatchSink`, we currently have retries ordered _after_ our rate limiting.  This is simply due to the order of the builder methods used on `ServiceBuilder`.  This means that, retries can be created without contributing to the rate limit statistics, allowing extra load to be generated.

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/9026
