### ISSUE TITLE
Allow using "managed identities" for azure_blob sink

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8667]
Requested by a user in Slack.

https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-msi

**Comment by JeanMertz** [comment]
Another request for this was logged on Slack.

The library we use for accessing Azure APIs [already has support for this](https://github.com/Azure/azure-sdk-for-rust/blob/08090ef44b5b4a8393d5beaf385bf39f9175812c/sdk/identity/src/token_credentials/managed_identity_credentials.rs), so it should mostly be a matter of exposing this to the end-user through the sink's configuration properties.

**Comment by HighWatersDev** [comment]
This would probably be a better practice versus having credentials stored in config file.

**Comment by HighWatersDev** [comment]
Since it's related, it'd be great to have the same functionality of using "managed identity" for azure_monitor_logs sink as well.

Looking forward to this feature!

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/12821
