### ISSUE TITLE
aws_ec2_metadata documentation for default fields missing instance_type

### ISSUE THREAD

**Issue by jasongilman** [vectordotdev/vector#8678]
The default fields listed in the documentation are `[instance-id local-hostname local-ipv4 public-hostname public-ipv4 ami-id availability-zone vpc-id subnet-id region]`

It appears that the code includes instance type as well https://github.com/timberio/vector/blob/v0.15.1/src/transforms/aws_ec2_metadata.rs#L54

**Comment by jszwedko** [comment]
Closed by https://github.com/timberio/vector/pull/8683
