### ISSUE TITLE
Don't cap `retry_attempts`, document the setting

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#8687]
Our request structure contains a `retry_attempts` field that is by default set to `isize::MAX`. The setting is otherwise undocumented. Some sinks -- influxdb metrics for instance -- set lower retry attempts without documenting the fact. We should both document this field and remove any low retries.

**Comment by jszwedko** [comment]
Closing in-lieu of https://github.com/vectordotdev/vector/issues/8686
