### ISSUE TITLE
Establish polymorphism configuration pattern in UX policy

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#8688]
See [this comment](https://github.com/DataDog/vector-enterprise/pull/174/files#r686213622). If this is a pattern we want to establish, we should add it to the user experience design doc and ensure it's consistently followed throughout Vector.

**Comment by jszwedko** [comment]
Closing since this was added: https://github.com/vectordotdev/vector/blob/master/docs/specs/configuration.md#polymorphism
