### ISSUE TITLE
Component in/out metrics should be better aligned with the lifecycle of the events.

### ISSUE THREAD

**Issue by tobz** [vectordotdev/vector#8693]
Currently, we generically emit metrics for components related to the lifecycle of events: events in, events out, processed bytes (how many bytes we shipped out) and so on.  There is a natural alignment of event lifecycle that people would typically imagine: an event "in" is when the component gets the event, the event "out" is when we know it's left the component and so on.

In practice, we do not always do this.

In some scenarios, like the Elasticsearch or generic HTTP sink, we emit the number of processed bytes when events are encoded, which does not account for making sure we actually sent the events payload, whether successful or not.  Merely batching the event triggers this, and so while internal backpressure in general tends to have a smoothing effect on how often these metrics are emitted, which is generally coupled with the requests being sent/responded to, it's not quite representative of reality.

The good news is that we often have common framework points -- `Pipeline`, `HttpClient`, etc -- where we could more accurately emit these metrics.

**Comment by blt** [comment]
I'm pro making a pass to ensure that all of our components of a kind emit the same telemetry with all the same labels -- REF https://github.com/timberio/vector/issues/8368 -- and make sure they align on the same lifecycle boundaries. I think it would valuable to know:

* bytes/events in
* bytes/events successfully out
* bytes/events fail out
* retry count
* downstream response count + label info for statuses 
* inbound buffer queue length

The last I'm not totally sure how to pull off but if we did have it we'd get two legs of Little's Law and be able to compute the average wait time for an event in vector, which would be quite valuable. 

Our current processed bytes would be equivalent to fail + success bytes out, to be clear.

**Comment by jszwedko** [comment]
Related: #8709

**Comment by bruceg** [comment]
@tobz @blt Are the issues raised here adequately addressed by the component spec in #8858?

**Comment by tobz** [comment]
@bruceg I do believe it does, yes. :)

**Comment by blt** [comment]
I believe so as well.
