### ISSUE TITLE
Fetch last timestamp from loki for unknown streams

### ISSUE THREAD

**Issue by ktff** [vectordotdev/vector#8727]
### Use-cases
Enables the sink to fix out of order events from the start. 

Currently if the first events are out of order, loki will refuse them and events will be lost. This will continue to happen until the sink encounters first event that is in order.

### Proposal
When encontering a stream for the first time query loki for the last timestamp. There are multiple endpoints through which this can be done. https://grafana.com/docs/loki/latest/api/#loki-http-api

### References
Proposed by @splitice in https://github.com/timberio/vector/issues/6651#issuecomment-837649284

**Comment by jszwedko** [comment]
Closing since loki supports out-of-order timestamps now.
