### ISSUE TITLE
`top` + `tap` spike CPU to 100% when the observed instance quits

### ISSUE THREAD

**Issue by leebenson** [vectordotdev/vector#8770]
Context: https://github.com/timberio/vector/issues/8449#issuecomment-899579283

Also happens with `top`.

I suspect this is a retry loop against the dropped WebSocket, but haven't dug any deeper.

**Comment by jszwedko** [comment]
Replaced by https://github.com/vectordotdev/vector/issues/11514 since we decided we want to do reloading.
