### ISSUE TITLE
Migrate to Route 53

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#8799]
The Vector.dev DNS is currently managed by Netlify, which is not a great place to manage DNS. We used this for the following reasons:

1. Previous version documentation. By hosting DNS with Netlify subdomains were automatically created for Vector's release branches. Users could access subdomains like v0-13.vector.dev. We no longer do this since it's not a great solution for past version documentation. We plan to solve this differently, for the reference docs only.
2. Redirects. In order for the [`netlify.toml` redirects](https://github.com/timberio/vector/blob/7f1b05b2165c701db2ae999a850713428b239c90/netlify.toml#L31) to work properly with any subdomain Netlify had to manage the DNS.

TODOs:

- [ ] Audit the [`netlify.toml` redirects](https://github.com/timberio/vector/blob/7f1b05b2165c701db2ae999a850713428b239c90/netlify.toml#L31) for any _subdomain_ redirects, and manage those with Route 53 or Terraform (resources repo) in some way.
- [ ] Leave non-subdomain (path) redirects in the `netlify.toml` file for easy website redirects.
- [ ] Ensure all Route 53 resources are defined in Teerraform (resources repo)
- [ ] Ensure master.vector.dev works as expected.
- [ ] Ensure SSL (https) works as expected for all domains.

**Comment by lucperkins** [comment]
@binarylogic Could you specify which specific DNS management features are missing in Netlify? Having DNS management in the same interface as other site things is a nice feature that I feel like we should back away from only if there are things we can't achieve in Netlify.

**Comment by jszwedko** [comment]
Closing this since we need to re-investigate where to move DNS.
