### ISSUE TITLE
Validate Datadog API key on start-up in `[datadog]` section

### ISSUE THREAD

**Issue by leebenson** [vectordotdev/vector#8811]
After #8791, it'd be useful to validate a provided Datadog API key synchronously on start-up, to catch any obvious issues before topology is configured.

Currently, dud keys surface obscure error messages asynchronously, referencing internally managed components that may be confusing to unsuspecting users.

**Comment by jszwedko** [comment]
Closing since this functionality is being moved out of Vector proper. cc/ @001wwang just for context.
