### ISSUE TITLE
Enrichment Table issues

### ISSUE THREAD

**Issue by StephenWakely** [vectordotdev/vector#8815]
I'm dropping a list of followup issues that need finalizing before the Enrichment Table functionality is ready for production.

1. [x]  ~~Encryption~~
We need the ability to load from encrypted data files.

We will be deferring this for now as the user is able to use disk encryption, thus won't need to rely on Vector for this.

2. [x] Check for duplicate indexes.
Currently each time an `get_enrichment_table_record` is compiled it will add an index into the lookup table. The file table source is not actually checking if the given fields have already been indexed, so the fields are indexed again. This does not stop it working, but it does use additional memory uneccessarily.

Fixed in #9056 

3. [ ] Is it necessary for the `EnrichmentTableRegistry` to be global?
As per [this comment](https://github.com/timberio/vector/pull/8524#discussion_r692871406). I couldn't work out a way to avoid creating a registry as a global registry. It is possible that this is the best way, bit it would be good to get some feedback on it to see if this could be improved upon.

4. [x] Make `vrl::Compiler` generic over `enrichment::TableSetup`
As per [this comment](https://github.com/timberio/vector/pull/8524#discussion_r692892212). Currently it is storing the enrichment tables as a `Box<dyn enrichment::TableSetup`. This is probably not necessary.

Fixed in #8979 

5. [x] Add an example to `get_enrichment_table_record`.
As per [this comment](https://github.com/timberio/vector/pull/8660#discussion_r692868605). There is currently no example in the `get_enrichment_table_record` vrl function since the tests don't have any enrichment tables to test against. We could either add a test enrichment table to the tests, or add an example that handles the failure.

Addressed by #9435 

6. [x] Look into getting rid of `EmptyEnrichmentTables` and work with `Option<EnrichmentTable>` instead.
As per [this comment](https://github.com/timberio/vector/pull/8660#discussion_r692865252).

Fixed in #8979

7. [x] Check how likely `seahash` is to cause collisions. 
Currently [seahash](https://crates.io/crates/seahash) is used to hash the search condition to lookup in the index. I'm fairly certain the chance of collision is pretty low, but don't have the actual numbers. It may be worth not risking it and perform a sequential scan on the results of the index lookup to make sure the data we have fetched is actually the data we searched for and not just data that just happens to have hashed to the same value. There will be a performance hit, but it is likely to be pretty small, and correctness is more important speed.

Addressed by #9021 

8. [x]  Add the `find_enrichment_table_records` function that returns an array of multiple records.

Addressed by #9069 

9. [x] Allow for searches within a date range.

We need to enable criteria for fields that fall within two dates. The first version will perform an indexed lookup on all exact conditions and then a sequential scan for the date ranges. Performance should be adequate provided the exact match searches return a sufficiently reduced dataset for the sequential scan to work with.

Addressed by #9021 

10. [x] Add schema support to the CSV enrichment config

If we are searching for date ranges we want to know which columns are dates so that we can search through them without performing the conversion at runtime.

Addressed by #9021 

11. [x] Add a `select` parameter to the VRL function.
Addressed by #9102

This function limits the columns returned from the enrichment table.

12. [x] Add an option to do case sensitive searches.

Addressed by #9085 

13. [x] Enable some mechanism to reload the enrichment file data when the underlying file is updated.

Addressed by #9371 

14. [x] Documentation

Addressed by #8817 

15. [x] Performance testing

16. [x] Loading in unit tests

Addressed by #9095

17. [ ] Add benchmarks for VRL functions.

**Comment by StephenWakely** [comment]
Thinking about number 4 in this list, I think we have the wrong solution here. Really Enrichment Tables are not, and should not be a concern of the Compiler. The only reason it has been added to this struct is because we need a way to pass the Enrichment Tables from Vector to the `get_enrichment_table_row` function and the compiler is the only means to do so. 

Making Compiler generic over `enrichment::TableSetup`, ie.. `vrl::Compiler<T: enrichment::TableSetup>`, is just mixing concerns that should not be mixed. Supposing a new feature needs to be added which also requires passing data between Vector and a specific VRL function, we would then have `vrl::Compiler<T: enrichment::TableSetup, U: something::Else>`. And it would get bigger the more that data needs passing to functions. If VRL were to be used in a different project these now uneccessary concerns would still need to be pulled in.

I propose a different solution. What if we were to add a collection of `std::any::Any` to Compiler? This way only users of VRL that provide enrichment tables would need to add `enrichment::TableSetup` to that collection. `Compiler` has no way of really knowing or caring what this data is. It is only the `get_enrichment_table_row` function that would attempt to pull out an `enrichment::TableSetup` struct from this data collection in order to use it.

Off the top of my head something like:

```rust
struct Compiler {
  data: Vec<Box<dyn Any>>,
 ..
}

impl Compiler {
  fn add_data(&self, data: Box<dyn Any>) {
    self.data.push(data);
  }

  fn get_data<T>(&self) -> Option<T> {
    self.data.find_map(|data| data.downcast_ref::<T>())
  }
}
```

Then `get_enrichment_table_row` would just do `let tables: enrichment::TableSetup = compiler.get_data().expect("no enrichment tables")`.

One possible downside would be that `enrichment::TableSetup` would need to be a concrete type and not a trait object. This means the enrichment tables would need to be accessible by the VRL function. I'm not convinced that enrichment tables are a concern of the VRL standard library. We could possibly create a new crate, call it `enrichment` that defines all the core enrichment table functionality (the stuff that is currently in `vrl_core`) together with the implementation of the `get_enrichment_table_row` function. Currently all VRL functions are in `vrl::stdlib`, but I don't think they all need to be, or even should be, kept together.

The result is that any users of VRL that don't care about enrichment tables, currently a lot of the tests, the VRL cli and the tests don't need to concern themselves with enrichment tables at all. This would sort out the dilema between `EmptyEnrichmentTables` or `Option<EnrichmentTable>`.

I'd be interested in your thoughts @JeanMertz.

**Comment by JeanMertz** [comment]
I'm a fan of the overall idea of decoupling enrichment tables, and I agree that it's a concept that doesn't always make sense to get as baggage with the rest of VRL.

We can quibble on the eventual naming of things (I think we should think about this as "external context", not so much as general "data", since it can be used for more than data-gathering purposes).

For posterity, here's a [playground link with a working example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a8e66b26f0412f210beab00d69ec7dae).

> One possible downside would be that `enrichment::TableSetup` would need to be a concrete type and not a trait object. This means the enrichment tables would need to be accessible by the VRL function.

I don't have a clear picture on the consequences of this just yet. Could you elaborate on what would differ from the existing set-up?

> Currently all VRL functions are in `vrl::stdlib`, but I don't think they all need to be, or even should be, kept together.

This I agree with. Technically, this is already the case, since each function is behind a feature flag, so you can mix-and-match whichever way you like when compiling stdlib, but I can see the case for some more exotic functions living in a separate crate, to create a more clear barrier between what we consider "minimally required for using VRL the way its intended" and "additional utility not always needed".

**Comment by StephenWakely** [comment]
> I think we should think about this as "external context", not so much as general "data", since it can be used for more than data-gathering purposes.

Agree, `external_context` is a much better name.

> Could you elaborate on what would differ from the existing set-up?

Currently there are`TableSetup` and `TableSearch` traits in `lib/vrl/compiler/src/enrichment.mod`. These are implemented in `vector-core`. The `find_enrichment_table_row` VRL function calls the enrichment tables via this trait.

The change would involve the following:

1. Delete the `TableSetup` and `TableSearch` traits.
2. Move the implementation of these traits from `vector-core` into a new `enrichment` crate.
3. Also move the implementation of `get_enrichment_table_row` into the `enrichment` crate. So now the function has access to the concrete struct.
4. Vector will still build these structs when it builds the config, this remains unchanged. When the Remap transform and conditions create the VRL compiler it will pass the `TableSetup` struct into the `external_context`.
5. `get_enrichment_table_row` will access `TableSetup` from the `external_context` and call `get_readonly` to retrieve `TableSearch` that it can store.
6. The VRL tests and cli won't add any `TableSetup` to the `external_context` and will also not make the `get_enrichment_table_row` function available.

**Comment by dbcfd** [comment]
It looks like enrichment tables are not being properly loaded in test.

```
> vector validate -C configs/
√ Loaded ["configs"]
√ Component configuration
√ Health check "prometheus"
√ Health check "amqp_sink"
```

```
> vector test --config-yaml configs/aggregate_events.yaml -- tests/test_aggregate_events.yaml
Sep 04 18:27:16.717  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,lapin=info" enable_datadog_tracing=false
Running tests
Sep 04 18:27:16.759 ERROR vector::unit_test: Failed to execute tests:
Failed to build test 'test-aggregate':
  failed to build transform 'prepare_aggregate_events':
  error[E610]: function compilation error: error[E401] invalid enum variant"
    ┌─ :9:30
    │
  9 │       possible_vendor, err = get_enrichment_table_record("name_of_table", condition: { "field": field_lookup })
    │                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    │                              │
    │                              invalid enum variant for argument "table"
    │                              expected one of:
    │                              received: "name_of_table"
    │
    = learn more about error code 401 at https://errors.vrl.dev/401
    = see language documentation at https://vrl.dev
```

**Comment by dbcfd** [comment]
Unit test does not seem to load enrichment tables: https://github.com/timberio/vector/blob/master/src/config/unit_test.rs#L461

Builder does load enrichment tables: https://github.com/timberio/vector/blob/master/src/topology/builder.rs#L129

Let me know if you want a PR with this fixed.

**Comment by StephenWakely** [comment]
@dbcfd Good catch. Thanks for reporting it. 

If you have the time a PR would be much appreciated! Many thanks. Feel free to ping me if you need a hand with anything.

**Comment by jszwedko** [comment]
@StephenWakely should we close this and make separate issues for any follow-ups?

**Comment by StephenWakely** [comment]
Yes, this can be closed now. I am discussing with @blt today about creating some soak tests for the enrichment tables which should cover the remaining task.
