### ISSUE TITLE
Enhance parse_key_value to support duplicate keys

### ISSUE THREAD

**Issue by sim0nx** [vectordotdev/vector#8841]
### Current Vector Version

```
vector 0.15.2 (x86_64-unknown-linux-gnu a216c34 2021-08-11)
```

### Use-cases

I have a logsource (sylsog) which produces key-value pairs, and it does include duplicate keys.
 e.g.  ```a="xx" b="xx" a="yy"```

Using parse_key_value does a great job at parsing except that it doesn't seem to play well with duplicate keys, i.e. it only results in one of the duplicate keys, any other is dropped.

### Attempted Solutions

I did try with:
```
. |= parse_key_value!(.message,
                     key_value_delimiter: "=",
                     field_delimiter: " ",
                     whitespace: "lenient",
                     accept_standalone_key: true
                    )
```
but as noted, this drops any duplicate keys.

### Proposal

My proposal would be to extend parse_key_value to accept duplicate keys.
If a duplicate key is found, it would create an array and just append the new value(s).

### References

https://discord.com/channels/742820443487993987/746070604192415834/879397882954919988
https://discord.com/channels/742820443487993987/746070604192415834/879400861850288148

**Comment by cholcombe973** [comment]
@spencergilbert and @jszwedko were just discussing this ticket. We think it might also be helpful as a first step to emit a warning that keys are being dropped so that it can later be investigated.
