### ISSUE TITLE
config: Use a consistent name for addresses and endpoints

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#8877]
The following components define an `address` field:

- Sinks
  - socket 
  - statsd
  - vector

The `socket`, `statsd`, and `vector` sinks are inconsistent with the others as Vector isn't _binding_ to the address in their case, they are target/remote addresses that Vector sends requests to. 

Based on the [UX Design](https://github.com/timberio/vector/blob/master/docs/USER_EXPERIENCE_DESIGN.md#build-momentum-with-consistency) we should ensure these options are consistent and reflect the nature of what's being configured.

Additionally most "target/remote" addresses Vector sends requests to are named in a mixture of `endpoint(s)` and `uri` which we could also consolidate on and use a single term for consistency.

Related https://github.com/timberio/vector/pull/8858

**Comment by jszwedko** [comment]
Spencer had suggested using `bind` when Vector is binding to the address. I like this.

**Comment by spencergilbert** [comment]
`bind`, `bind_address`, `listen_address`...
