### ISSUE TITLE
Document meaning of `text` encoding for `encoding.codec`

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8879]
Frequently users are surprised that the `text` encoding just serializes the `message` field from the event. I couldn't find anywhere where this was documented currently.

**Comment by spencergilbert** [comment]
And again: https://discord.com/channels/742820443487993987/746070591097798688/894718019668951052

**Comment by jszwedko** [comment]
This is actually done now.

See, for example, https://vector.dev/docs/reference/configuration/sinks/http/#encoding.codec

<img width="726" alt="Screen Shot 2021-10-05 at 3 02 08 PM" src="https://user-images.githubusercontent.com/316880/136094434-19e8a844-40b5-4084-a2ca-87b598f585fa.png">

**Comment by spencergilbert** [comment]
Nice - didn't notice that!
