### ISSUE TITLE
Create docs/ARCHITECTURE.md

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#8908]
We need an architectural document that can evolve over time. [This comment](https://github.com/timberio/vector/pull/8524#discussion_r696870601) should be materialized in an architecture document that other developers can consult. It'll also be nice to formally define this as we consider changes to our current architecture.

**Comment by jszwedko** [comment]
Closing since this was added https://github.com/vectordotdev/vector/blob/master/docs/ARCHITECTURE.md
