### ISSUE TITLE
Backpressure detection

### ISSUE THREAD

**Issue by lukesteensen** [vectordotdev/vector#892]
Related to #841 

One of the most difficult symptoms to debug is when a pipeline is running slower than it should be. It often comes down to a single component providing backpressure that flows throughout the processing graph. It can even cause confusing semi-related symptoms to pop up in other components (e.g. #763).

To help diagnose these kinds of issues, it would be very helpful if Vector had some mechanism for helping to determine where exactly backpressure in the system is coming from. After some digging, I think there are three areas where we could consider building this kind of functionality:

1. `BatchServiceSink`
2. Trace events around `poll_ready` and `start_send`
3. A custom `Forward` implementation

The `BatchServiceSink` is a somewhat unique place where we [explicitly check](https://github.com/timberio/vector/blob/503bbc0494eca9b2d62267b4a29adc3c2ce27ff4/src/sinks/util/mod.rs#L150) whether the wrapped sink service is ready for the next batch of events or not. We don't use it for every sink, which is a major drawback to this approach, but it does gives us one place to insert some bookkeeping on how "busy" a bunch of common sinks are during operation.

Another option would be to leverage trace events to instrument the various `poll_ready` and `start_send` implemenations of our sinks and services. This would let us cover every type of sink, but we'd have to do the actual instrumentation for each one. This would also be complicated if we want to use sinks/services from libraries or when we want to [nest a bunch of service layers together](https://github.com/timberio/vector/blob/ec73082da655d5e17c7023fef3b5c1893a4d7bf4/src/sinks/aws_cloudwatch_logs/mod.rs#L84-L94).

Finally, what I think could be the most interesting option is to build a custom implementation of [`Forward`](https://github.com/rust-lang-nursery/futures-rs/blob/a00d35efcb5bfa5581f695618ca7b77068998fa0/src/stream/forward.rs#L94-L98) that does this kind of bookkeeping. These basically represent the edges between each component in our processing graph, and they have enough information to tell how often the source stream is producing new data and how often the destination sink is able to accept it. We could provide a single implementation that we use in our topology building that would apply to every pair of communicating components in the process.

Once we have a place to collect the raw information, we'll need to come up with a set of heuristics to determine when there is notable backpressure that we should warn the user about. Done poorly, this could cause a lot of false positives during normal use, so we probably want to be conservative in what we actively report. We could also have some functionality for dumping the state of the raw data somewhere for out-of-band analysis. This could be a very useful tool for debugging issues reported by users where we can't poke at the running process or easily reproduce it.

## Related issues

- [ ] #9500

**Comment by jszwedko** [comment]
@lukesteensen is this still relevant?

**Comment by lukesteensen** [comment]
There are some interesting ideas in here, but I think it's largely been superseded by utilization metrics. I would lean towards closing.

**Comment by jszwedko** [comment]
Sounds good, I agree.
