### ISSUE TITLE
Count number of values in an array

### ISSUE THREAD

**Issue by JeanMertz** [vectordotdev/vector#8976]
A use-case that was requested is to count the number of occurrences of a value within an array.

e.g.:

```coffee
array = ["a", "a", "b", "a", "c", "c"]

count(value: array, match: "a") # 3
count(value: array, match: "b") # 1
count(value: array, match: "c") # 2
```

This will become possible using iteration once #8381 lands, but until then, it's worth considering adding such a function to resolve this specific problem.

**Comment by sfc-gh-btilahun** [comment]
Thanks @JeanMertz . Would it be possible to extend this functionality to also support a string separated with a delimiter and  return the count.  The count method take the string value and a delimiter and what value to count. i:e count(<raw_value>,<count_value>,<delimiter>) and return the count of 
raw_value = The raw value that  eg "a|b|b|b|c|d|d"
count_value = the value that needs to be counted eg "b"
delimiter = The delimiter used to split the string eg "|"

Maybe some kind of method overloading 
count(value) will  take an array and count the repetitive value in the array and returns a map. 
count(value,<count_value>) will take an array and returns an integer with the count value 
count(value,count_value>,delimiter) Will take a string and return an integer with the count value

**Comment by JeanMertz** [comment]
@sfc-gh-btilahun would combining `count` with [`split`](https://vector.dev/docs/reference/vrl/functions/#split) suffice here?

```coffee
string = "a|b|b|b|c|d|d"
array = split(string, "|") # ["a", "b", "b", "b", "c", "d", "d"]

count(value: array, "a") # 3
count(value: array, "b") # 1
count(value: array, "c") # 2
```

**Comment by JeanMertz** [comment]
Closing this, as this was solved using the `tally` function, and can also be achieved using [iteration in VRL](https://vector.dev/highlights/2022-05-18-vrl-iteration-support).
