### ISSUE TITLE
Greater verbosity on errors in `vector::internal_events::http_client`

### ISSUE THREAD

**Issue by chaychoong** [vectordotdev/vector#8978]
When the `http_client` returns a `403` (or any other) errors, the body object is obfuscated, making it difficult to troubleshoot things.

I was running the `0.16.0-distroless-static` image on the `github.com/timberio/vector/distribution/kubernetes/vector-agent?ref=v0.15.2` ref by mistake, and the `kubernetes_log` source was attempting to access the `namespaces` API (introduced in #8287) when it was not equipped with the sufficient permissions. Even with the `trace` log level, it was difficult to pin down the root cause, and some guesswork had to be done to realise my configuration error.

**Comment by jszwedko** [comment]
Closing in favor of https://github.com/vectordotdev/vector/issues/5024
