### ISSUE TITLE
Verify ARC performance in soak tests

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#8982]
Now that ARC is on by default, we need to verify that performance was not negatively impacted. If it is, we need to open investigation issues.

**Comment by bruceg** [comment]
I have taken a quick look into our existing soak tests, and have not seen a performance drop at the point when ARC is turned on by default and the new algorithm is introduced (Aug 27). If anything, sinks sending to external services increased in performance, which was the point. So, I think this can be closed.

**Comment by binarylogic** [comment]
Very nice!

**Comment by zsherman** [comment]
🎉 🎉 🎉
