### ISSUE TITLE
The `route` documentation page does not document the `route` option properly

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#9014]
The [`route` documentation page](https://vector.dev/docs/reference/configuration/transforms/route/) lacks documentation on how to use the `routes` option. Specifically:

- [ ] There is no example of defining a route in the configuration example.
- [ ] The [individual option definition](https://vector.dev/docs/reference/configuration/transforms/route/#route) is very confusing. It's not clear what that option accepts.
- [ ] There's no example on how to use the route with a downstream component.

**Comment by jszwedko** [comment]
A couple of related issues:

https://github.com/timberio/vector/issues/7607
https://github.com/timberio/vector/issues/6496

**Comment by filip-coder** [comment]
In docs it should be noted that routes are not exclusive - I mean, if two or more conditions are met - events are duplicated into two or more routes.

**Comment by diegomontoya** [comment]
Just read the routes doc and also agree with that it needs to be updated/fixed. The examples are really bad. Add a downstream reference to route-id (via source usage) would resolve some of the problem.

**Comment by jszwedko** [comment]
Yeah, agreed, thanks @diegomontoya . We are planning to make a docs push early this year to audit all of the component docs and adjust the examples.

**Comment by ktmq** [comment]
+1 for this issue -- I just set up `route` transform in my config and definitely would not have been able to figure it out with the official docs alone. The examples provided in this github issue saved me :)

**Comment by zpriddy** [comment]
I just ran across this looking to see if routes are exclusive.. That should be in the documentation as it is causing me issues at the moment.. Now that i have an answer from the comments above.. that is helpful.. 

I do think that there should be an option to make routes exclusive - in the order that they are listed as it ends the routing on the first match and does not continue.. Thoughts? I would open up a Feature Request if there seems to be some support of this idea..
