### ISSUE TITLE
Set up compliance documentation for all components

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#9017]
In order to ensure we have covered all of the aspects of the [component specification](https://github.com/timberio/vector/blob/master/docs/specs/component.md) for all components, we will need some documentation as to which components are compliant with which parts of the specification. Ideally, this should be in some form that will track the separate parts of the specification, and will be updated along with the component.

My thoughts are:
* Use a structured document, either well-formatted text or data such as Cue or TOML, to allow it to be parsed by a script.
* Include a date stamp with each component, to track the last time the compliance was updated.
* Each facet of the component spec will be a separate data point on each component.
* A script will be built that may be run in the CI pipeline once all components are fully documented and compliant to ensure the document stays up to date.

**Comment by binarylogic** [comment]
> Use a structured document, either well-formatted text or data such as Cue or TOML, to allow it to be parsed by a script.
> Include a date stamp with each component, to track the last time the compliance was updated.
> Each facet of the component spec will be a separate data point on each component.

👍 

> A script will be built that may be run in the CI pipeline once all components are fully documented and compliant to ensure the document stays up to date.

How would this work if the document is updated with a new requirement? Would CI fail? Would every component need to adhere immediately? I'd like if components are required to answer one way or another, even if adherence is deferred. This will guide new component development.

---

Did you consider any code-level adherence strategies that would bring adherence closer to implementation? Like explicitly marking compliance in the Rust source file?

**Comment by bruceg** [comment]
> How would this work if the document is updated with a new requirement? Would CI fail? Would every component need to adhere immediately? I'd like if components are required to answer one way or another, even if adherence is deferred. This will guide new component development.

My preference would be to introduce new requirements at a granular level along with adjusting all the components to adhere to the requirement. I suspect it will need, at some point, to have the ability to issue warnings on some requirements and fail on others. I agree at least having an answer to each would be a good requirement.

> Did you consider any code-level adherence strategies that would bring adherence closer to implementation? Like explicitly marking compliance in the Rust source file?

Yes, that is a possibility that appeals to me — something structured in a top-level doc comment in each component that a specialized parser can extract. I'll make that my primary target.

**Comment by bruceg** [comment]
Closing this in favor of the scripted compliance setup.
