### ISSUE TITLE
Add integration test for `index` and `indexed_fields` in Humio sink

### ISSUE THREAD

**Issue by pablosichert** [vectordotdev/vector#9034]
Add integration tests for the `index` and `index_fields` option for Humio, analoguously to integration tests with Splunk:

https://github.com/timberio/vector/blob/e20ce939ef5a84845b671e9600386ed7f7de7222/src/sinks/splunk_hec.rs#L531-L617

Note that the indexed fields provided to Humio likely must start with an `#`, looking at the case of a [Discord user](https://discord.com/channels/742820443487993987/764187584452493323/881851428514193429) who used the `splunk_hec` sink with Humio instead and [Humio's docs  for the HEC](https://library.humio.com/preview/docs/ingesting-data/log-shippers/hec/index.html#format-of-data). However, I wasn't able to confirm this since I have no means to try it out right now.

I tried adding them, but these do not seem to work, and I suspect this is because we use an old version of Humio in our integration test setup due to licensing issues.

**Comment by jszwedko** [comment]
Closing this since we cannot upgrade the humio docker image we are using.
