### ISSUE TITLE
List support for ip_cidr_contains

### ISSUE THREAD

**Issue by gso-trifork-security** [vectordotdev/vector#9068]
### Current Vector Version
```
v0.16.1
```
VRL function `ip_cidr_contains` only support one CIDR input. I have a usecase where I want to check if a IP is a RFC1918 and also if it's a part of my external IP address blocks.

Example: 
```
ip_cidr_contains!(["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"], .ip_src)
```

**Comment by jszwedko** [comment]
This is also related to some work we are doing around adding iteration support to VRL cc/ @JeanMertz

**Comment by JeanMertz** [comment]
With iteration support as currently proposed (#9001), this would work as follows:

```coffee
any(["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]) { |_, ip|
	ip_cidr_contains!(ip, .ip_src)
}
```

**Comment by JeanMertz** [comment]
Closing this issue, as iteration support has landed, and makes this possible without the need for changes to the `ip_cidr_contains` functions.

I have created #13026 to track the addition of the `any` function, to make this easier.
