### ISSUE TITLE
Improve test compile times

### ISSUE THREAD

**Issue by LucioFranco** [vectordotdev/vector#909]
Currently, we have 6 integration tests that live within `tests`. Not all of these tests really need to live in this folder, they can be moved to live within the main code base. The issue is that each of these files requires vector to be recompiled for each one. This makes the `cargo test` time very substantial. To fix this, I suggest, that we move most of the tests into the main repo. Every test file in `tests` beside the topology one should be moved into the appropriate directory or file.

**Comment by hdost** [comment]
I am unable to replicate this. Are you running just `cargo test`? With a fresh clone I didn't notice this.

**Comment by Hoverbear** [comment]
I have also not noticed this. I suspect it may have been resolved. I'll close this. :)

**Comment by Hoverbear** [comment]
Our new GA boxes seem like they might benefit from this for linker pressure reasons.

**Comment by jszwedko** [comment]
Closing since this hasn't been an issue recently.
