### ISSUE TITLE
Update to Rust 1.55

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#9092]

**Comment by bruceg** [comment]
[Announcement here](https://blog.rust-lang.org/2021/09/09/Rust-1.55.0.html)

I think the biggest thing to be aware of in this release is the [changes to `ErrorKind`](https://blog.rust-lang.org/2021/09/09/Rust-1.55.0.html#stdioerrorkind-variants-updated), so we'll have to check if we're matching on `Other`.
