### ISSUE TITLE
S3 sink confuses batch parameters(size in bytes and size in events)

### ISSUE THREAD

**Issue by vladimir-dd** [vectordotdev/vector#9105]
When we initialise Batcher parameters in S3 sink we pass `batch_size_bytes ` and `batch_size_events` in the wrong order [here](https://github.com/timberio/vector/blob/master/src/sinks/aws_s3/sink.rs#L118) This might cause memory allocation errors in case of big numbers.

**Comment by blt** [comment]
@jszwedko was kind enough to land a quick PR to switch the arguments in #9106 but @bruceg had the good suggestion that we consider passing a struct for long argument lists in sensitive areas like this. Might also make use of a builder pattern to achieve the same effect, though we have to build those by hand.

**Comment by jszwedko** [comment]
Closed https://github.com/vectordotdev/vector/issues/9105
