### ISSUE TITLE
[Loki] support sending gzipped content

### ISSUE THREAD

**Issue by vbichov** [vectordotdev/vector#9122]
### Current Vector Version

```
 ./bin/vector --version
vector 0.15.2 (x86_64-unknown-linux-gnu a216c34 2021-08-11)
```

### Use-cases

decrease network usage and upload speed as a result

### Attempted Solutions

None

### Proposal

Loki now supports ingestion of gzipped content https://github.com/grafana/loki/issues/3205.

Please consider adding the same on vector's side

### References

https://github.com/grafana/loki/issues/3205

**Comment by 3JIou-home** [comment]
did u have any information about timings this feature request?

**Comment by vmrm** [comment]
same question as above? is there any ETA?

**Comment by 3JIou-home** [comment]
same
