### ISSUE TITLE
Add cue docs feature for framing/decoding in sources

### ISSUE THREAD

**Issue by pablosichert** [vectordotdev/vector#9126]
We need a new feature that documents the `framing` and `decoding` config keys for sources.

When `DecodingConfig` is used within a source's config, all `framing` and `decoding` variants become available for it.

@jszwedko suggested adding an option similar to 

https://github.com/timberio/vector/blob/9837d36d26bf1f8b2cbd739d89631ad132cf182f/website/cue/reference/components/sinks.cue#L154-L212

However, the name only (e.g. `character_delimited`) is not enough since `framing`/`decoding` configs can have additional fields, e.g. `character_delimited.delimiter`.

**Comment by binarylogic** [comment]
@pablosichert I would go ahead and add this. Let us know if you have any problems.
