### ISSUE TITLE
Migrate remaining references to timberio to vectordotdev

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#9137]
Now that we've renamed the Github organization, we should also:

- [ ] Update installation instructions
- [ ] Create new dockerhub organization ([cannot rename](https://hub.docker.com/support/doc/how-do-i-rename-a-docker-hub-repository)) and migrate images

**Comment by spencergilbert** [comment]
re: dockerhub organization, would this be a good time to move to another image hoster (GCP/AWS/whatever Datadog is using) or would we still be using both?

**Comment by jszwedko** [comment]
Aha, I missed #8797 

I think we should still push to dockerhub regardless given that is where `docker` searches by default, but we can still plan to push the additional repositories as part of #6715

**Comment by jszwedko** [comment]
Closing since this was just used for scheduling and we have other issues covering the changes.
