### ISSUE TITLE
Remove tracing span used for log function rate limiting in remap

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#9141]
In https://github.com/vectordotdev/vector/pull/8579 it was observed that the tracing span that we wrap VRL execution in to enable:

* Rate limiting log messages
* Showing position of `log` call in the VRL program (character number)

Has a substantive performance penalty.

It was re-added in https://github.com/vectordotdev/vector/pull/8995 re-introduce the rate limiting behavior, but we should see if there is another way we can achieve this without the performance penalty.

**Comment by StephenWakely** [comment]
The initial implementation of this didn't use the tracing span, so I imagine something like this could work.

https://github.com/vectordotdev/vector/pull/6622/commits/85c67b6d71355802b8b377f0a7431ac476495f61

**Comment by blt** [comment]
For what it's worth #8579 now accounts for around 30% of the runtime in the `log_aggregation` soak test so finding an alternate solution would be a pretty cost-effective way to bump remap throughput performance.
