### ISSUE TITLE
Additional response for `api` health endpoint

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#9160]
### Current Vector Version

```
version="0.16.1" arch="x86_64" build_id="739e878 2021-08-26"
```

### Use-cases

Supporting zero-downtime deployments in Kubernetes requires the application to respond to readiness and liveness probes, to be properly added and removed from Service resources

### Attempted Solutions

Using the existing existing endpoint as a healthcheck causes 502's during deploys.

### Proposal

The endpoint should be more _responsive_, hooking into our shutdown logic we can signal observers that the instance _will be going away_ when the shutdown period begins. This should avoid load balancers from sending traffic to a vector instance that is up but no longer accepting connections.

**Comment by jszwedko** [comment]
@spencergilbert is this still relevant? Could you add more details to the proposal if so? It isn't clear exactly why the described issue occurs or what you are proposing to change.

**Comment by spencergilbert** [comment]
This seems like a duplicate of the issue closed by https://github.com/vectordotdev/vector/pull/11183
