### ISSUE TITLE
Please add 'section' field to the Debian control file

### ISSUE THREAD

**Issue by adeptg** [vectordotdev/vector#9162]
### Current Vector Version

```
0.16.1
```

### Use-cases

reprepro refuses to create a Debian repository with vector because the Debian control file doesn't have a 'section' field which is recommended by [debian policy](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-section)

### Attempted Solutions

It helps to add 
> Section: admin

to DEBIAN/control

### Proposal

add section string to the deb package build scripts

**Comment by jszwedko** [comment]
Thanks for the report @adeptg ! I added in https://github.com/vectordotdev/vector/pull/9164
