### ISSUE TITLE
Add support for sketches into the metric datamodel

### ISSUE THREAD

**Issue by prognant** [vectordotdev/vector#9181]
### Use-cases
Accurately represent distribution, perform operation on those, send sketches to endpoint that support that kind of data for better accuracy and flexibility.

### Proposal

Based on the current supported [metric types](https://github.com/vectordotdev/vector/blob/master/lib/vector-core/src/event/metric.rs#L138-L169) two option can be envisioned:
1. Switch an existing type to be the facade for sketches (e.g. the `Distribution` type)
2. Add a new Sketch type and expose conversion between relevant type in VRL

Option #2 seems more reasonable: no compatibility issue, user can do what they want if conversion are consistently implemented between relevant types. The sketch format would likely be ddsketch.

### References
The problem: [Streaming quantiles](https://edoliberty.github.io/papers/streamingQuantiles.pdf)
Datadog approach: [ddsketch](https://arxiv.org/abs/1908.10693)

**Comment by tobz** [comment]
+1 for option 2.

I think `Distribution` should stay as-is, and option 2 follows more closely to the OpenTelemetry metrics stuff IIRC, where sketch type/parameters can be encoded such that downstream systems have enough information to interact with the data natively, allowing better passthrough/avoids loss of accuracy.

**Comment by yandooo** [comment]
Hi @jszwedko wondering when it is possible to support point #2 from the description? In particular, would be amazing to have VRL lang extension to convert DDSketch -> Histogram and Histogram -> DDSketch. Thanks

**Comment by jszwedko** [comment]
Closing since we do have a model for sketches now.
