### ISSUE TITLE
Defaults are not documented for VRL function arguments

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#9187]
For example, the [`parse_grok` function](https://vector.dev/docs/reference/vrl/functions/#parse_grok) does not document that the `remove_empty` option [defaults to `true`](https://github.com/vectordotdev/vector/blob/9025c6655726c042f5e8c1db705d066062955d5e/website/cue/reference/remap/functions/parse_grok.cue#L33)

**Comment by jszwedko** [comment]
This was closed by #9263
