### ISSUE TITLE
VRL function argument optionality is not obvious

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#9189]
VRL function arguments are [color coded](https://share.getcloudapp.com/YEuOwDoZ) to signal optionality. This is problemsome because:

1. It's not obvious. I didn't realize this was the case until someone pointed it out. This is partly due to a bad choice in color selection.
2. It breaks convention. I've never seen docs do this, making it less obvious.
3. Colors should not be used as a sole communication method for accessibility reasons. ~8% of the population is color blind.

It's fine as an enhancement, but this should be made more clear in the docs in other ways.

**Comment by jszwedko** [comment]
The options now have brackets around them as they did before, but I think we could still improve on this by adding `required` or `optional` as another column in the argument table.
