### ISSUE TITLE
VRL function signatures are no longer accurate

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#9190]
The documented VRL function signatures are no longer accurate. For example, the [`parse_grok` function](https://vector.dev/docs/reference/vrl/functions/#parse_grok) exposes this signature:

```
parse_grok(value: <string>, pattern: <string>, remove_empty: <boolean>) :: <object>
```

When it should be

```
parse_grok(value: <string>, pattern: <string>, [remove_empty: <boolean>]) :: <object>, <error>
```

The two things missing are:

1. Optionality via the brackets (`[...]`)
2. The return signature including the error

**Comment by lucperkins** [comment]
@binarylogic I can add the brackets but it's not really correct to say that the signatures are no longer accurate. Optional/required is expressed via color coding in both the function signature and the argument table.
