### ISSUE TITLE
Document `datadog_logs` timeout footgun

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#9193]
See https://github.com/vectordotdev/vector/pull/9185#issuecomment-921159011. This applies for any upstream source, not just the Datadog Agent, and is worth documenting so that users don't run into this.

**Comment by jszwedko** [comment]
Closing since we did overhaul the batch timeouts recently. I'm not sure the footgun described in that comment is actually true. The Datadog Agent shouldn't retransmit requests if the previous request is still in-flight.
