### ISSUE TITLE
Consider making `tag_cardinality_limit` a sink-level concern

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#9195]
Similar to quotas, metric tag cardinality feels like it should be a first-class sink-level concern, not a transform that a user has to tack on. This is inline with the ["be opinionated" UX principle](https://github.com/vectordotdev/vector/blob/master/docs/USER_EXPERIENCE_DESIGN.md#be-opinionated--reduce-decisions) to reduce decisions and guide the user into reliable performant deploys of Vector.

**Comment by jszwedko** [comment]
Closing since our approach has been to continue to lean on transforms for this sort of thing. It offers more flexibility in both configuring the metrics to limit as well as what to do with the metrics that hit the limit.
