### ISSUE TITLE
Publish a metric for Vector config reloads

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#9217]
Requested by user in Slack.

They are particularly interested in failed reloads, but I think we could publish them for all reloads with a tag of whether it was successful or not.

**Comment by 001wwang** [comment]
Closing as these metrics already exist. See `VectorReloaded` and `VectorReloadFailed` internal events in https://github.com/vectordotdev/vector/blob/master/src/internal_events/process.rs
