### ISSUE TITLE
Accept out-of-order writes for `loki` sink

### ISSUE THREAD

**Issue by nazar554** [vectordotdev/vector#9223]
There is going to be a new configuration option to remove out-of-order write limitation in upcoming Loki 2.4. 
It is configured server side, comes with a small performance penalty, and it's already available on Grafana Cloud.

### Current Vector Version
```
0.16.1
```

### Use-cases

- Support situations when log lines arrive out of order

### Attempted Solutions

It's possible to add `OutOfOrderAction::Ignore`, to skip updating and checking `latest_timestamp` inside `LokiBuffer::push`.
However more changes are need inside `LokiBuffer::finish`

https://github.com/vectordotdev/vector/blob/37debb72a7f03de38f38e6f8aa7902e76c4218c0/src/sinks/util/buffer/loki.rs#L157

Also inside Loki docs it's mentioned that when `unordered_writes` is set to `true`, the log lines are accepted only when their timestamp is not earlier than `time_of_most_recent_line - (max_chunk_age/2)`. 

Maybe it makes sense to add `OutOfOrderAction::Unordered { max_chunk_age: Duration }` instead and handle this inside `LokiBuffer`. 

Not sure how to track `time_of_most_recent_line` though.

### Proposal

Add an option to ignore timestamps inside out of order log events, and buffer them.

### References
[Avoid dropped logs due to out-of-order timestamps with a new Loki feature](https://grafana.com/blog/2021/09/16/avoid-dropped-logs-due-to-out-of-order-timestamps-with-a-new-loki-feature/?utm_source=grafana_news&utm_medium=rss)

[Loki docs](https://grafana.com/docs/loki/next/configuration/#accept-out-of-order-writes)

[New feature in Loki 2.4: no more ordering constraint](https://grafana.com/blog/2021/12/03/new-feature-in-loki-2.4-no-more-ordering-constraint/?utm_source=grafana_news&utm_medium=rss)

**Comment by jszwedko** [comment]
Hey @anglinb ! If you are able to, we'd definitely love a contribution. We are happy to review.

**Comment by nazar554** [comment]
It seems that Loki 2.4 was [released yesterday](https://grafana.com/blog/2021/11/10/loki-2.4-is-easier-to-run-with-a-new-simplified-deployment-model/?utm_source=grafana_news&utm_medium=rss)
