### ISSUE TITLE
Installation pages no longer include setup steps

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#9233]
The new installation pages no longer guide users to a point of success. They display the installation commands but don't tell the user how to configure Vector or observe that it's working. For example, the [current APT installation page](https://share.getcloudapp.com/9ZuQJpyv) lacks the same level of detail on the [old API installation page](https://share.getcloudapp.com/YEuObE4X). I don't think this is prohibiting users from setting up Vector, but could be a nice enhancement to bring back to the new site.

**Comment by jszwedko** [comment]
Closing as stale since this hasn't seemed to be a point of friction in practice.
