### ISSUE TITLE
Installation pages have regressed in readability

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#9234]
The new installation pages has regressed in in in terms of readability and aesthetics. For example, the [new APT installation page](https://vector.dev/docs/setup/installation/package-managers/apt/) information hierarchy is not nearly as obvious as the [old API installation page](https://vector-backup.netlify.app/docs/setup/installation/package-managers/apt/) This is subjective, so I'm curious what others think.

**Comment by jszwedko** [comment]
It seems unlikely we'll pick this up at this point. I think we should just open new issues for the things we want to add.
