### ISSUE TITLE
The new website is slower to navigate

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#9235]
Clicking through the new website is slower than the old website. This is noticeable while trying to _actually_ configure Vector, where you need to click around [the reference docs](https://vector.dev/docs/reference) to build a configuration. It's not prohibitive, but worth documenting to see if there are ways we can speed up page load times. For comparison, try clicking around the [old reference docs](https://vector-backup.netlify.app/docs/reference/configuration/transforms/filter/).

**Comment by lucperkins** [comment]
@binarylogic We may be able to cut down on static asset sizes but there are limits to how well we'll be able to compete with a single-page app framework.

**Comment by jszwedko** [comment]
Closing this since we haven't heard user complaints.
