### ISSUE TITLE
Our docs are no longer editable by users

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#9237]
The old website included an "edit this page" link on every page. This linked to the markdown or cue files so that users could make edits and contributions. Quite a few users did this and it helped to ensure our docs were quality.

**Comment by lucperkins** [comment]
@binarylogic While I think that directing people to the source file for pages is a good idea (and something I had as a TODO that got lost in the shuffle), but my experience with guiding people to the edit page directly is un-great on projects with a DCO requirement.

1. User clicks the **Edit** button
2. User goes to the Edit page, makes some edits, and clicks **Submit**
3. Our team gets a PR without a DCO and we then need to bug the person to add one. Sometimes one gets added quickly and without fuss, sometimes the PR is abandoned as-is and if we like the changes we need to make them ourselves.

But I'll add both buttons and we can see how it goes.

**Comment by spencergilbert** [comment]
Technically the DCO isn't required for minor (say docs only) changes, it still shows 🔴  on the PR checks though
