### ISSUE TITLE
Quickstart instructions should say 'bash' not 'sh'

### ISSUE THREAD

**Issue by candlerb** [vectordotdev/vector#9265]
The [quickstart install instructions](https://vector.dev/docs/setup/quickstart/) say:

```
curl --proto '=https' --tlsv1.2 -sSf https://sh.vector.dev | sh
```

However, this is a bash script (it starts with `#!/bin/bash`) and uses bash features.

Tested with Ubuntu 18.04: if you run it with `sh` as shown above then you get:

```
...
>>> Ready to proceed? (y/n)

>>> y

--------------------------------------------------------------------------------

sh: 220: [[: not found
sh: 227: [[: not found
>>> Unknown architecture from ldd: ldd (Ubuntu GLIBC 2.27-3ubuntu1.4) 2.27
...
```

**Comment by jszwedko** [comment]
Thanks for reporting this @candlerb . I opened https://github.com/vectordotdev/vector/issues/9265 to fix it.
