### ISSUE TITLE
Vector's configuration directory should implement implicit name-spacing

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#9273]
Credit to @jdrouet for this idea. As we navigate more advanced configurations that require collaboration (via the new transform-based pIpelines feature), we're finding the need to break up Vector's configuration into many different files, mostly to align with collaboration boundaries. Instead of leaving this as a creative exercise for the user, we should consider implicit namespace based on the directory structure. For example:

```
/etc/vector/vector.toml # no namespace
/etc/vector/sources/datadog_agent.toml # sources.datdog_agent namespace
/etc/vector/transforms/redact.toml # transforms.redact namespace
```

Each file would only contain the option as the namespace dictated by the nesting.

**Comment by jdrouet** [comment]
Many questions popped out
- in `/etc/vector/sources/datadog_agent.toml # sources.datdog_agent namespace` should we only be allowed to put sources? if not, maybe this example is misleading and we should use something like `team_a/datadog_agent`.
- can the component names in the namespace `A` conflict with those in `B`?
- how am I supposed to reference the component `foo` in namespace `bar` in `/etc/vector/vector.toml`?

**Comment by hhromic** [comment]
This is a great conceptual idea to implement in Vector. My suggestion would be to not forget to apply this also to the `tests` top-level configuration. Having the unit tests in their own separte file would be big improvement on readability for pipeline configurations. Often in our pipelines, the unit tests definitions are longer than the pipeline itself.

**Comment by binarylogic** [comment]
@jdrouet I'm not sure I understand the questions. I feel like we might be thinking about different models.

> in /etc/vector/sources/datadog_agent.toml # sources.datdog_agent namespace should we only be allowed to put sources? if not, maybe this example is misleading and we should use something like team_a/datadog_agent.

In my example, `/etc/vector/sources/` would add an implicit namespace of `sources`. Sub directories would add another namespace and so on.

> can the component names in the namespace A conflict with those in B?

No. By nature of being in separate namespaces they will not conflict.

> how am I supposed to reference the component foo in namespace bar in /etc/vector/vector.toml?

What do you mean? You'd reference them just like any other component. The namespacing doesn't prevent that. In other words, all of the files are joined together into a single configuration file with the directories added as namespaces. The end result between a single file with explicit namespaces is exactly the same.

**Comment by jszwedko** [comment]
Closing since implicit directory namespacing is supported now.
