### ISSUE TITLE
Add geoip enrichment table

### ISSUE THREAD

**Issue by sim0nx** [vectordotdev/vector#9283]
It would be of great help if VRL had support for a geoip function as this would make configs a lot lighter.

### Current Vector Version

```
vector 0.16.1 (x86_64-unknown-linux-gnu 739e878 2021-08-26)
```

### Use-cases
I am working with various different sources of logs, which tend to also have specific separate sinks and different formats. They often contain at least two fields where a part of the geoip information would be useful.

### Attempted Solutions
The way I currently do it is to have:
source -> transform[1..n] -> transform_geoip[1..n] -> transform (remove unused geoip fields) -> sink

Which translates to:
- source
- one or more transforms to parse and normalise the data.
- one or more geoip transforms, depending on how many fields there are
- final transform for that specific log source, which extracts the required geoip fields and removes the geoip object
- sink

Handling many different sources, this feels a bit cumbersome.

### Proposal

Having a VRL geoip function would make this a lot lighter, not requiring 1-n geoip transforms and no post-processing transform for removing unused fields and renaming fields.

**Comment by jszwedko** [comment]
Just noting there were some oddities I found in the `geoip` transform while implementing https://github.com/vectordotdev/vector/pull/12803 that we could avoid when implementing this as a VRL function. See that PR for the list.

**Comment by ktff** [comment]
## Description
VRL function to enrich events with geolocation data from the MaxMind GeoIP2-City, GeoLite2-City, GeoIP2-ISP and GeoLite2-ASN databases.

## Design
A VRL function `get_geoip` with signature:
```
get_geoip(ip: <string>, database: <string>)
:: <object> , <error>
```
Arguments:
- `ip`- IP in string format - required 
- `database` - Path to the [MaxMind GeoIP2](https://dev.maxmind.com/geoip/geoip2/downloadable) or [GeoLite2 binary city database](https://dev.maxmind.com/geoip/geoip2/geolite2/#Download_Access) file - literal - required

Errors:
- `ip` isn’t a valid IP address

Returns:
- Object containing all geolocation data as fields. Depending on the database used, either the city or the ISP field is populated.

The database is loaded during compile time and can fail if `database` isn't a valid path, or database isn't present, or some other IO error occurs.

## Implementation
The functionality is the same as `geoip` transform so the code can be shared, once extracted.

cc. @jszwedko @sim0nx

**Comment by jszwedko** [comment]
Hey @ktff !

I talked it over a bit with the team and we think this _might_ actually fit better as a new enrichment table type?

I think the configuration could look something:

```toml
[enrichment_tables.lookup]
type = "geoip"

[enrichment_tables.users.geoip]
path = "/var/lib/vector/data/db.mmdb"
```

Then it would be called like:

```toml
[transforms.remap_user_info]
type = "remap"
inputs = ["user_info_messages"]
source = """
. = parse_json(.message) ?? {}
. |= get_enrichment_table_record("lookup", { "ip": .ip }) ?? {}
"""
```

If you aren't familiar with the enrichment table concept, you can see a demo here: https://github.com/vectordotdev/vector-demos/tree/main/csv-enrichment

In this particular case, the _only_ valid lookup is by IP and so this could be verified at compile time. We could even constrain it more so that, when the enrichment table is a geoip table, it doesn't take a map of conditions as an argument, it just takes the ip address so you could call like:

```
[transforms.remap_user_info]
type = "remap"
inputs = ["user_info_messages"]
source = """
. = parse_json(.message) ?? {}
. |= get_enrichment_table_record("lookup", .ip) ?? {}
"""
```

What do you think of this? I realize it's a bit more of an effort, but this lookup does seem to very much fit into the enrichment table model.

**Comment by StephenWakely** [comment]
The main caveat I can see around using an enrichment table is if you want to read from the database using `async` since the enrichment tables, or any part of VRL, doesn't provide for `async`.  

Can you load the data into memory at boot time and query it from there?

**Comment by jszwedko** [comment]
Thanks for the thoughts all!

> The main caveat I can see around using an enrichment table is if you want to read from the database using `async` since the enrichment tables, or any part of VRL, doesn't provide for `async`.
> 
> Can you load the data into memory at boot time and query it from there?

The maxminddb crate `lookup` function, interestingly, appears to not be async: https://docs.rs/maxminddb/latest/maxminddb/struct.Reader.html#method.lookup

So it seems like we can sidestep that question for now though I think we'll need to make enrichment tables async at some point (consider if/when we add things like redis).

> * The need to set it up
>   
>   * Seems unavoidable to get the benefits that this model provides.
> * Slightly more complex to call
>   
>   * Can be handled, as you said, by making it take just the ip address. This deviation from convention should be documented, or handled in some other way.

Yeah, I agree with these critiques though you could have made the same claims about CSV lookup that we ended up creating the enrichment table concept for so I think the geoip lookup fits neatly in that pattern. Modeling it as a separate table makes it more explicit that it is a shared resource.

> * Discoverability issue
>   
>   * Just from reading the function documentation, it isn't clear what's doable with enrichment functions. Having a simple mention/list of supported types of tables in that documentation would help quite a bit.

Yeah, agreed, the docs could be improved here.

**Comment by ktff** [comment]
> Can you load the data into memory at boot time and query it from there?

@StephenWakely yes. This ties to what @sim0nx assumed in that this would only load DB once, while a dedicated vrl function approach would, by default, load it as many times as it's mentioned in vrl.

**Comment by jszwedko** [comment]
Ah, yes, @ktff is right, the database is loaded into memory. That makes more sense why it isn't async then 😅

**Comment by JeanMertz** [comment]
Given the consensus here, I propose we update this ticket to reflect the fact that we'd want this feature to be accessible through enrichment tables, instead of a custom VRL function.
