### ISSUE TITLE
Update Error events in HttpSink-based sinks to new component spec

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#9302]
This is the second part of #9225 — all those sinks updated to emit the new component spec metrics for sent events also need to have their error events updated to have the correct naming, properties, and tags. The sinks involved are listed below.

* [ ] `azure_monitor_logs`
* [ ] `clickhouse`
* [ ] `datadog_events`
* [ ] `elasticsearch`
* [ ] `gcp_pubsub`
* [ ] `gcp_stackdriver_logs`
* [ ] `gcp_stackdriver_metrics`
* [ ] `honeycomb`
* [ ] `http`
* [ ] `humio_logs`
* [ ] `humio_metrics`
* [ ] `influxdb_logs`
* [ ] `influxdb_metrics`
* [ ] `logdna`
* [ ] `loki`
* [ ] `new_relic_logs`
* [ ] `sematext_logs`
* [ ] `splunk_hec_logs`
* [ ] `splunk_hec_metrics`

**Comment by jszwedko** [comment]
I believe this was completed by the recent instrumentation sweep.
