### ISSUE TITLE
Splunk TCP (S2S)

### ISSUE THREAD

**Issue by satellite-no** [vectordotdev/vector#9305]
### Current Vector Version
```
vector 0.13.1 (v0.13.1 x86_64-unknown-linux-gnu 2021-04-29)
```

### Use-cases

Combine, filter, and route Splunk native traffic from HFs & UFs to Splunk indexers and some logs to AWS S3. 

### Attempted Solutions

With the current setup no solution was attempted however "Cribl" provides this functionality along with Splunk DSP. 

### Proposal

A new Splunk TCP source and Destination would have to be create and reverse engineered from the Splunk internal communications for both "cooked and uncooked" data. 

### References

NA

**Comment by jszwedko** [comment]
Hi @satellite-no ! Thanks for opening this. I think it is actually covered by https://github.com/vectordotdev/vector/issues/3848 and https://github.com/vectordotdev/vector/issues/4562. Would you agree? Or is there something missing from one of those?

**Comment by satellite-no** [comment]
Agreed, I missed those but just saw #2537 that again is pretty much the same. Thanks!

**Comment by jszwedko** [comment]
Oh yes, also that one! Thanks for verifying @satellite-no . I'll close this one out, but feel free to follow the others for updates or leave any additional thoughts there.
