### ISSUE TITLE
Compile error in `lib/vector-core/buffers/examples/soak.rs`

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#9309]
I'm getting a compile error when checking the above source with `cargo check --all-targets --no-default-features --workspace`:

```
error[E0599]: no variant named `Disk` found for enum `Variant`
   --> lib/vector-core/buffers/examples/soak.rs:102:28
    |
102 |     let variant = Variant::Disk {
    |                            ^^^^ variant not found in `Variant`

```

If we add a `#if` guard to that variant, we'll have to eliminate the whole example, but I'm not sure if this is the right approach, or if something else could still be used there for an example.

**Comment by blt** [comment]
Hmm, troubling that we didn't see this in CI already. I'm happy to see the example be deleted. I expect to remove the disk feature flag next quarter and I don't see why we should keep this failing example around meanwhile.
