### ISSUE TITLE
Audit transforms to ensure compliance with the component spec

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#9324]
This issue represents the work required to bring all transforms into compliance with the component observability spec. With the completion of #9111, all that should remain is to audit the error events they emit.

- [ ] Instrument the `add_fields` transform to adhere to the component spec
- [ ] Instrument the `add_tags` transform to adhere to the component spec
- [ ] Instrument the `aggregate` transform to adhere to the component spec
- [ ] Instrument the `ansi_stripper` transform to adhere to the component spec
- [ ] Instrument the `aws_cloudwatch_logs_subscription_parser` transform to adhere to the component spec
- [ ] Instrument the `aws_ec2_metadata` transform to adhere to the component spec
- [ ] Instrument the `coercer` transform to adhere to the component spec
- [ ] Instrument the `compound` transform to adhere to the component spec
- [ ] Instrument the `concat` transform to adhere to the component spec
- [ ] Instrument the `dedupe` transform to adhere to the component spec
- [ ] Instrument the `field_filter` transform to adhere to the component spec
- [ ] Instrument the `filter` transform to adhere to the component spec
- [ ] Instrument the `geoip` transform to adhere to the component spec
- [ ] Instrument the `grok_parser` transform to adhere to the component spec
- [ ] Instrument the `json_parser` transform to adhere to the component spec
- [ ] Instrument the `key_value_parser` transform to adhere to the component spec
- [ ] Instrument the `log_to_metric` transform to adhere to the component spec
- [ ] Instrument the `logfmt_parser` transform to adhere to the component spec
- [ ] Instrument the `lua` transform to adhere to the component spec
- [ ] Instrument the `merge` transform to adhere to the component spec
- [ ] Instrument the `metric_to_log` transform to adhere to the component spec
- [ ] Instrument the `reduce` transform to adhere to the component spec
- [ ] Instrument the `regex_parser` transform to adhere to the component spec
- [ ] Instrument the `remap` transform to adhere to the component spec
- [ ] Instrument the `remove_fields` transform to adhere to the component spec
- [ ] Instrument the `remove_tags` transform to adhere to the component spec
- [ ] Instrument the `rename_fields` transform to adhere to the component spec
- [ ] Instrument the `route` transform to adhere to the component spec
- [ ] Instrument the `sample` transform to adhere to the component spec
- [ ] Instrument the `split` transform to adhere to the component spec
- [ ] Instrument the `tag_cardinality_limit` transform to adhere to the component spec
- [ ] Instrument the `tokenizer` transform to adhere to the component spec

**Comment by leebenson** [comment]
Much of this has already been completed by @jdrouet, but I've moved each of the checklist above to separate issues in Jira so this can be tracked and confirmed. Closing.
