### ISSUE TITLE
Instrument sinks with event processing metrics

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#9325]
This issue represents the work required to bring all sinks not covered by #9225 and #9302 into compliance with the *event processing* metrics in the component observability spec.

- [x] #9504
- [x] #9525
- [x] #9705 
- [ ] Instrument the `aws_cloudwatch_logs` sink with event processing metrics
- [ ] Instrument the `aws_cloudwatch_metrics` sink with event processing metrics
- [ ] Instrument the `aws_kinesis_firehose` sink with event processing metrics
- [x] #8710
- [ ] Instrument the `aws_kinesis_streams` sink with event processing metrics
- [x] #9597
- [ ] Instrument the `aws_sqs` sink with event processing metrics
- [ ] Instrument the `azure_blob` sink with event processing metrics
- [ ] Instrument the `blackhole` sink with event processing metrics
- [ ] Instrument the `console` sink with event processing metrics
- [x] Instrument the `datadog_archives` sink with event processing metrics
- [ ] Instrument the `datadog_logs` sink with event processing metrics
- [ ] Instrument the `datadog_metrics` sink with event processing metrics
- [x] https://github.com/vectordotdev/vector/pull/9611
- [x] #9588
- [ ] Instrument the `gcp_cloud_storage` sink with event processing metrics
- [x] #9835 
- [ ] Instrument the `nats` sink with event processing metrics
- [ ] Instrument the `papertrail` sink with event processing metrics
- [ ] Instrument the `prometheus_exporter` sink with event processing metrics
- [ ] Instrument the `prometheus_remote_write` sink with event processing metrics
- [ ] Instrument the `pulsar` sink with event processing metrics
- [ ] Instrument the `redis` sink with event processing metrics
- [ ] Instrument the `sematext_metrics` sink with event processing metrics
- [ ] Instrument the `socket` sink with event processing metrics
- [ ] Instrument the `splunk_hec_logs` sink with event processing metrics
- [ ] Instrument the `splunk_hec_metrics` sink with event processing metrics
- [ ] Instrument the `statsd` sink with event processing metrics
- [x] #9642

**Comment by binarylogic** [comment]
Closing in favor of #12921
