### ISSUE TITLE
Change `StreamSink::run` to take `self` instead of `&mut self`

### ISSUE THREAD

**Issue by fuchsnj** [vectordotdev/vector#9328]
```rust
#[async_trait]
pub trait StreamSink {
    async fn run(&mut self, input: BoxStream<'_, Event>) -> Result<(), ()>;
}
```

The `run` function of this trait is designed to be ran only once. Changing the signature can potentially cleanup some code a bit. There is some code that has to do a runtime check / panic if it already ran.

Example: https://github.com/vectordotdev/vector/blob/e10294c7b41b7328f708c03a37740c9e617270d8/src/sinks/s3_common/sink.rs#L97-L108)

I don't currently see any reason this can't be changed or why it was written this way (maybe historical reasons?)

**Comment by jszwedko** [comment]
cc/ @tobz @blt for thoughts.

**Comment by tobz** [comment]
Seems fine to me.  Running that change through Rust Playground quickly doesn't yield any weird quirks with `async_trait`.

**Comment by blt** [comment]
Yeah, I think having this be `self` more accurately captures the intent we have implicit in the code base, and would allow us to avoid `Option` taking here and there.
