### ISSUE TITLE
Integrate `Decoder`/`DecodingConfig` with `exec` source

### ISSUE THREAD

**Issue by pablosichert** [vectordotdev/vector#9336]
The `exec` source could benefit from the general decoding capabilities available in `DecodingConfig`.

**Comment by jszwedko** [comment]
Hi @hhromic ! Yep, that's right. The exact config schema is still being settled in https://github.com/vectordotdev/vector/pull/9196 but it'll look something close to that.

**Comment by hhromic** [comment]
That's great! Looking very forward to this functionality! For sure will simplify and make more robust/consistent a lot of things.
