### ISSUE TITLE
Datadog Logs sink send date unix timestamp in seconds instead of milliseconds

### ISSUE THREAD

**Issue by vladimir-dd** [vectordotdev/vector#9351]
If users set `encoding.timestamp_format` to `unix` Datadog Logs sink sets `date` to the unix timestamp in seconds, but Datadog expects [milliseconds](https://docs.datadoghq.com/logs/log_configuration/processors/?tab=ui#log-date-remapper)

**Comment by jszwedko** [comment]
@vladimir-dd Should users even be able to set `encoding.timestamp_format` on the `datadog_logs` sink given Datadog has a specific format it requires?

**Comment by vladimir-dd** [comment]
@jszwedko, good question. So far both formats are supported(provided we send timestamp in millis), but I agree with you that it's probably better to not let users change this(don't see why would they need this).
Should I just change this to always send milliseconds then(faster serializing/deserializing)?

**Comment by jszwedko** [comment]
@vladimir-dd 👍 that sounds reasonable to me; to always use millisecond timestamps.

**Comment by vladimir-dd** [comment]
Closed by https://github.com/vectordotdev/vector/pull/9436
