### ISSUE TITLE
[VRL] Improve `timestamp` integer coercion resolution

### ISSUE THREAD

**Issue by hhromic** [vectordotdev/vector#9368]
### Current Vector Version

```
vector 0.16.1 (x86_64-unknown-linux-gnu 739e878 2021-08-26)
```

### Use-cases

Conversion of `timestamp` types to numeric [Unix time representation](https://en.wikipedia.org/wiki/Unix_time).

### Attempted Solutions

At the moment, VRL supports converting `timestamp` types to Unix time using the `to_int()` coercion function:
```rust
ts = now()
// t'2021-09-29T09:12:01.521850900Z'
to_int(ts)
// 1632906721
```

However, this coercion is losing resolution, i.e. missing the sub-second information from the `timestamp`.

One way to circumvent this limitation is to adopt one of the following options:

* If we are to keep using integers, change the unit to _milliseconds_ instead of _seconds_ (the [Java](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/Instant.html#toEpochMilli()) and [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime) way):
  ```rust
  to_int(to_float!(format_timestamp!(ts, format: "%s.%f")) * 1000)
  // 1632906721521
  ```

* Or slightly simpler if we are to use floats and keep the unit as _seconds_ (the [Python](https://docs.python.org/3/library/time.html#time.time) way):
  ```rust
  to_float!(format_timestamp!(ts, format: "%s.%f"))
  // 1632906721.5218508
  ```

Note that both of the above workarounds involve conversions to-from strings and thus not very nice/performant.

### Proposal

I see two solutions with pros/cons:

* Change the `to_int()` coercion function to return milliseconds instead of seconds.
  * Pro: most use-cases I am aware of use this representation (probably thanks to Java/JavaScript).
  * Con: is a breaking change and existing users of this use-case would need to adapt: either by dividing by `1000` and re-coercing again to an integer or rounding (introducing extra calculations); or by adapting the schemas further in their pipelines (users love to do this /sarcasm).
  * Con: this approach still loses a bit of precision as the sub-second part is truncated to three digits.
* Implement `timestamp` coercion in the `to_float()` function and still return seconds.
  * Pro: this is purely functionality addition and not functionality changing -> nothing existing breaks.
  * Con: to get milliseconds, a calculation is needed (multiplying by `1000` and then either rounding or coercing to integer).

I personally think that the second option is the better/safer approach given the pros/cons.

Option 1 example for existing users to retain existing behaviour:
```rust
ts = now()
// t'2021-09-29T09:12:01.521850900Z'
to_int(to_int(ts) / 1000)
// 1632906721
```

Option 2 example for new users to get milliseconds as integer:
```rust
ts = now()
// t'2021-09-29T09:12:01.521850900Z'
round(to_float(ts) * 1000)
// 1632906721522
```

**Comment by spencergilbert** [comment]
@hhromic there's also a [`to_unix_timestamp`](https://vector.dev/docs/reference/vrl/functions/#to_unix_timestamp) which might be more what you're looking for?

I'm not sure why there's somewhat duplicate behavior between functions here, maybe @jszwedko, @JeanMertz, @StephenWakely know the history behind that choice.

**Comment by jszwedko** [comment]
I foretold this issue: https://github.com/vectordotdev/vector/issues/5730#issuecomment-751735849 😅 

`to_unix_timestamp` is the recommended path for converting timestamps to integers. We do have an issue for `to_float` support for timestamp conversion though: https://github.com/vectordotdev/vector/issues/5731

**Comment by hhromic** [comment]
> @hhromic there's also a [`to_unix_timestamp`](https://vector.dev/docs/reference/vrl/functions/#to_unix_timestamp) which might be more what you're looking for?

Ah dang, how come I missed that function? That does *exactly* what we needed.
```rust
ts = now()
// t'2021-09-29T14:45:29.402960700Z'
to_unix_timestamp(ts)
// 1632926729
to_unix_timestamp(ts, unit: "milliseconds")
// 1632926729402
```

I wonder if this function was added not so long ago and I just missed it all this time :)

Anyway, this completely solves our particular use-case. I still would add the coercion to `to_float()` for completeness. But yes using `to_unix_timestamp()` is by far more useful and concise than relying on coercions. Perhaps you can consider simply removing `timestamp` from `to_int()` to encourage this function?

Thanks for the tip. I will close this issue as irrelevant now.

**Comment by jszwedko** [comment]
👍 I opened https://github.com/vectordotdev/vector/pull/9373 to add timestamp conversion to `to_float` since I think it is odd that `to_int` supports it, but `to_float` does not.

**Comment by hhromic** [comment]
Nice one!  Yes consistency is key for an elegant language. Either both have it or both don't. Thanks!
