### ISSUE TITLE
Cache the byte size of events

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#9383]
Through the observability features, vector is gaining a number of call sites where the byte size of an `Event` is being calculated. For example, it is calculated both when an event is sent into a pipeline and when it is received. For a `LogEvent`, this calculation results in a recursive scan through the internal `Value` type, which may be a bad idea for an operation in the critical hot path.

I propose to add a "cache" wrapper around the `enum Event` type that maintains the calculated size in an `Option<NonZeroUsize>` (which will likely need to be wrapped in a `Cell` or atomic in order to maintain exterior immutability). Whenever the inner event is modified (through a `mut` dereference), that cache will need to be reset, and then recalculated when `size_of` is called.

Unfortunately, the addition of a wrapper will end up impacting a lot of code. In particular, everything that does a `match` on the outer event with the assumption that it is an `enum` will need to be handled differently. It would be worth investigating how much time is being spent in the `size_of` function before moving ahead with this.

Related work:

- [ ] #9202

**Comment by bruceg** [comment]
Hmm, I have overthought the difficulties of actually implementing this. It can be implemented individually in each of `LogEvent` and `Metric` the way the finalizers are done, which means no external code should need to change. Wrapping the value in a `Cell` provides the interior mutability needed, making it a fairly straightforward optimization.

This technique should be generally applicable to all complex types that are defined within the vector crates, though the extra size cost and branch may end up being larger than any performance gain for some such types.

**Comment by blt** [comment]
Instead of adding a wrapper we might also just consider this an implementation detail of the `ByteSizeOf` impl for `Event`. As it is we currently traverse the structure on every call to `size_of`, as you point out, but most `Event` instances are small and we might not beat the overhead of maintaining a counter in-Event except for deep, larger instances. 

I'd, personally, like to see the `ByteSizeOf` implementation show up as a hot-spot in profiling before we tackle this issue.

**Comment by jszwedko** [comment]
Closing this since I agree it should be driven by profiling.
