### ISSUE TITLE
Send-Q and Recv-Q metrics

### ISSUE THREAD

**Issue by zsherman** [vectordotdev/vector#9392]
[Send-Q and Recv-Q metrics](https://linux.die.net/man/8/netstat) as part of netstat can be helpful to identify TCP issues on machines, and it would be nice if those could be captured by Vector as part of [host metrics](https://vector.dev/docs/reference/configuration/sources/host_metrics/) collection.

**Comment by jszwedko** [comment]
This is a duplicate of https://github.com/vectordotdev/vector/issues/9316
