### ISSUE TITLE
Generate a hash from a `Config`

### ISSUE THREAD

**Issue by leebenson** [vectordotdev/vector#9422]
Ensure `Config` is hashable, and can generate a string hash that feeds through context to metrics reported to enterprise Pipelines.

The hash string generated should reflect the shape of the marshalled struct, and not the underlying JSON/TOML. This should allow two configurations that define components out of order, but otherwise identically, to produce the same hash.

**Comment by jszwedko** [comment]
@leebenson this is closed by #9575 , no?

**Comment by leebenson** [comment]
Yes, thanks for the prompt - closing!
