### ISSUE TITLE
Nested options not being rendered on website

### ISSUE THREAD

**Issue by pablosichert** [vectordotdev/vector#9423]
The section produced by 

https://github.com/vectordotdev/vector/blob/fa7a6582d78c027a9f658f96eee6de44cabca1ff/website/cue/reference/components/sources.cue#L158-L191

fails to render the nested options object, as can be observed in https://github.com/vectordotdev/vector/pull/9196#issuecomment-921756935.

**Comment by lucperkins** [comment]
@pablosichert Could you point to a doc where you would expect to see this but aren't?

**Comment by pablosichert** [comment]
Hey @lucperkins, I noticed this while looking at the deploy preview of #9196. You can see it e.g. on the new `framing` and `decoding` options for `socket`:

https://deploy-preview-9196--vector-project.netlify.app/docs/reference/configuration/sources/socket/#decoding

**Comment by lucperkins** [comment]
@pablosichert Ah, gotcha. That explains why those changes weren't in `master` 😄

**Comment by lucperkins** [comment]
@pablosichert Since there are no other double-nested configs, it's a bit tricky to template this. So I think maybe the best way will be to just push some templating changes directly to your branch.

**Comment by jszwedko** [comment]
Closed by #9196
