### ISSUE TITLE
conf.d(toml.d?) - to convenient update

### ISSUE THREAD

**Issue by denser** [vectordotdev/vector#9428]
### Current Vector Version
0.16.1

While future updates apk manager will detect difference in vector.toml.

I think need to make include **conf.d** or **toml.d** to keep my config separate from repo version of timl.

**Comment by denser** [comment]
In debian-based system is painful to update i.e. graylog or other elk apps)

**Comment by denser** [comment]
Pardon me, if that info in docs? Can't find it by myself.

Thx for this, definitely useful for me :)

**Comment by jszwedko** [comment]
Closing as complete.
