### ISSUE TITLE
remap transform: Incorrect docs

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#9455]
https://vector.dev/docs/reference/configuration/transforms/remap/

Example config shows both `file` and `source` options which is invalid, and `timezone` is not documented.

**Comment by jszwedko** [comment]
This is being worked in https://github.com/vectordotdev/vector/pull/9870

**Comment by jszwedko** [comment]
Closing in-lieu of https://github.com/vectordotdev/vector/issues/10169
