### ISSUE TITLE
Protect against runaway metrics cardinality

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#9458]
Users often complain of high metrics cardinality that can be due to a variety of factors:

- High cardinality tag names (e.g., `user_<id>=true` style tags)
- High cardinality tag values (e.g., `user_id=<id>` style tags)
- Many tags added that the user does not want or need
- Slow growth of tags over time (lack of governance)
- ...and more

Users need more control over ever growing tag cardinality. Before we begin work, we should create a brief that covers this issue at a high level.

**Comment by jszwedko** [comment]
Closing until we have a more detailed proposal.
