### ISSUE TITLE
Integrate `codecs::Encoder` with sinks

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#9459]
Like #9404 but for encoding/sinks

Issues that will be resolved with the integration:
- [x] #3454

Native encoding issues:

- [x] Issues with parsing encoding configurations that prevent the user from specifying that there should be no framing (see review comments on https://github.com/vectordotdev/vector/pull/10684)
- [ ] #12135
- [x] https://github.com/vectordotdev/vector/issues/12134

Other issues:

- [ ] #12434
- [x] #13331

Priority of sinks (check means "has open PR" or "marked as not applicable"):
- [x] `socket`
- [x] `http`
- [x] `kafka`
- [x] `datadog_archives`
- [x] `datadog_events`
- [x] `datadog_logs`
- [x] `datadog_traces`
- [x] `aws_s3`
- [x] `azure_blob`
- [x] `gcp_cloudstorage`
- [x] `gcp_pubsub`
- [x] `gcp_stackdriver_logs`
- [x] `console`
- [x] `file`
- [x] `vector`
- [x] `aws_sqs`
- [x] `elasticsearch`
- [x] `splunk_hec_logs`
- [x] `loki`
- [x] `aws_cloudwatch_logs`
- [x] `aws_kinesis_firehose`
- [x] `aws_kinesis_streams`
- [x] `azure_monitor_logs`
- [x] `blackhole`
- [x] `clickhouse`
- [x] `honeycomb`
- [x] `humio_logs`
- [x] `influxdb`
- [x] `logdna`
- [x] `nats`
- [x] `new_relic`
- [x] `new_relic_logs`
- [x] `papertrail`
- [x] `pulsar`
- [x] `redis`
- [x] `sematext`
- [x] `websocket`

| Sink | Issue | PR | Status | Comment | Legacy encoding |
| - | - | - | - | - | - |
|`aws_cloudwatch_logs`| - | #12175 | Merged | - | `EncodingConfig<StandardEncodings>` |
|`aws_kinesis_firehose`| - | #12176 | Merged | - | `EncodingConfig<StandardEncodings>` |
|`aws_kinesis_streams`| - | #12177 | Merged | - | `EncodingConfig<StandardEncodings>` |
|`aws_s3`| - | #12136 | Merged | - | `EncodingConfig<StandardEncodings>` |
|`aws_sqs`| - | #12550 | Merged | - | `EncodingConfig<(Text,Json)>` |
|`azure_blob`| - | #12179 | Merged | - | `EncodingConfig<StandardEncodings>` |
|`azure_monitor_logs`| - | | Blocked | Needs improvements to `Encoder` to emit JSON value when serializer supports JSON. (Part of #12495.) | `EncodingConfigWithDefault<(Default)>` |
|`blackhole`| - | - | Not applicable | - | - |
|`clickhouse`| - | - | Not applicable | Has opinionated fixed encoding | `EncodingConfigWithDefault<(Default)>` |
|`console`| - | #12181 | In review | | `EncodingConfig<StandardEncodings>` |
|`datadog_archives`| - | - | Not applicable | Has opinionated fixed encoding | - |
|`datadog_events`| - | - | Not applicable | Has opinionated fixed encoding | - |
|`datadog_logs`| - | - | Not applicable | Has opinionated fixed encoding | - |
|`datadog_traces`| - | - | Not applicable | Has opinionated fixed encoding | - |
|`elasticsearch`| - | | Needs clarification | The Elasticsearch [Bulk API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#docs-bulk) expects entries in JSON format. | `EncodingConfigFixed<{doc_type,suppress_type_name}>` |
|`file`| - | #12548 | Merged | - | `EncodingConfig<(Text,Ndjson)>` |
|`gcp_cloud_storage`| - | #12488 | Merged | - | `EncodingConfig<StandardEncodings>` |
|`gcp_pubsub`| - | #12718 | In review | | `EncodingConfigWithDefault<(Default)>` |
|`gcp_stackdriver_logs`| - | #12719 | Blocked | Needs improvements to `Encoder` to emit JSON value when serializer supports JSON. (Part of #12495.) | `EncodingConfigWithDefault<(Default)>` |
|`honeycomb`| - | #12764 | Blocked | Needs improvements to `Encoder` to emit JSON value when serializer supports JSON. (Part of #12495.) | - |
|`http`| #11579 | #11647 | Merged | - | `EncodingConfig<(Text,Ndjson,Json)>` |
|`humio_logs`| - | #12495 | In review | | `EncodingConfig<(Json,Text)>` |
|`influxdb`| - | #12583 | Merged | - | `EncodingConfigWithDefault<(Default)>` |
|`kafka`| - | #12133 | Merged | - | `EncodingConfig<StandardEncodings>` |
|`logdna`| - | | | | `EncodingConfigWithDefault<(Default)>` |
|`loki`| - | #12558 | Merged | - | `EncodingConfig<(Json,Text,Logfmt)>` |
|`nats`| - | #12586 | Merged | - | `EncodingConfig<(Text,Json)>` |
|`new_relic`| - | | | | `EncodingConfigFixed<(Default)>` |
|`new_relic_logs`| - | | | | `EncodingConfigWithDefault<(Json)>` |
|`papertrail`| - | #12589 | Merged | - | `EncodingConfig<(Text,Json)>` |
|`pulsar`| - | #13139 | In review | | `EncodingConfig<(Text,Json,Avro)>` |
|`redis`| - | #12596 | Merged | - | `EncodingConfig<(Text,Json)>` |
|`sematext`| - | | | | `EncodingConfigFixed<{doc_type,suppress_type_name}>` |
|`socket`| - | #10684 | Merged | - | `EncodingConfig<(Text,Json)>` |
|`splunk_hec_logs`| - | #12495 | In review | | `EncodingConfig<(Json,Text)>` |
|`vector`| - | - | Not applicable | - | - |
|`websocket`| - | #13054 | In review | - | `EncodingConfig<StandardEncodings>` |

**Comment by jszwedko** [comment]
Closing this epic since it was complete. Remaining work is tracked separately.
