### ISSUE TITLE
Filter can't accept "contains" function without handling

### ISSUE THREAD

**Issue by denser** [vectordotdev/vector#9462]
### Vector Version

```
vector 0.16.1 (x86_64-unknown-linux-gnu 739e878 2021-08-26)
```

### Vector Configuration File

```toml
[transforms.dhcp_warning]
type = "filter"
inputs = ["syslog"]
condition = 'contains(.message, "dhcp,warning")'
```

### Debug Output

```
Oct 05 13:41:55 GRAYLOG vector[30625]: √ Loaded ["/etc/vector/vector.toml"]
Oct 05 13:41:55 GRAYLOG vector[30625]: Component errors
Oct 05 13:41:55 GRAYLOG vector[30625]: ----------------
Oct 05 13:41:55 GRAYLOG vector[30625]: x Transform "dhcp_warning":
Oct 05 13:41:55 GRAYLOG vector[30625]: error[E100]: unhandled error
Oct 05 13:41:55 GRAYLOG vector[30625]:   ┌─ :1:1
Oct 05 13:41:55 GRAYLOG vector[30625]:   │
Oct 05 13:41:55 GRAYLOG vector[30625]: 1 │ contains(.message, "dhcp,warning")
Oct 05 13:41:55 GRAYLOG vector[30625]:   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 05 13:41:55 GRAYLOG vector[30625]:   │ │
Oct 05 13:41:55 GRAYLOG vector[30625]:   │ expression can result in runtime error
Oct 05 13:41:55 GRAYLOG vector[30625]:   │ handle the error case to ensure runtime success
Oct 05 13:41:55 GRAYLOG vector[30625]:   │
Oct 05 13:41:55 GRAYLOG vector[30625]:   = see documentation about error handling at https://errors.vrl.dev/#handling
Oct 05 13:41:55 GRAYLOG vector[30625]:   = learn more about error code 100 at https://errors.vrl.dev/100
Oct 05 13:41:55 GRAYLOG vector[30625]:   = see language documentation at https://vrl.dev

```

### Expected Behavior

I wan to detect if "dhcp,warning" contains in .message and filter only this messages

### Actual Behavior

error while restart service

**Comment by jeromekleinen-kbc** [comment]
This is because vector cannot know for sure that the .message field is a string, see https://github.com/vectordotdev/vector/issues/9406 for multiple possible solutions.

**Comment by spencergilbert** [comment]
@jeromekleinen-kbc has it correct - we can't know ahead of time for sure that `.message` is actually a _string_. We're working on schema support that would allow you to declare and ensure that at compile time circumventing this issue.

**Comment by jeromekleinen-kbc** [comment]
@denser in the issue I linked there is literally an example on how you should adjust your config. I suggest you read it again and try yourself first as this will be more educational than me just giving you the answer.

**Comment by spencergilbert** [comment]
> Okay, so how can i add handling in filter? According documentation there must be boolean thing. Hint me please how to do it via little example.

```toml
[transforms.dhcp_warning]
type = "filter"
inputs = ["syslog"]
condition = 'contains(string!(.message), "dhcp,warning")'
```

or

```toml
[transforms.dhcp_warning]
type = "filter"
inputs = ["syslog"]
condition = 'contains!(.message, "dhcp,warning")'
```

See https://vector.dev/docs/reference/vrl/expressions/#function-call for details around error handling and the `abort` argument.
