### ISSUE TITLE
`vector tap` should error if there are no matches for a tapped component name

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#9467]

**Comment by leebenson** [comment]
Just noting that this would be a breaking change.

`tap` is currently designed to accommodate:

1. Component filter patterns, such as `component*`, to catch anything that matches, either now or later -- e.g. _component1_, _componentB_, etc.

2. Changes that may occur _during_ an active tap session -- such as a config reloading. A previous `NOT_MATCHED` response can return `MATCHED` later over the WebSocket if a new component matches.

We could fire off a preemptive query to determine whether anything matches initially, but it might be worth at least adding a CLI switch to opt in to the the 'follow' behaviour.

**Comment by binarylogic** [comment]
cc @jszwedko since this was originally raised by him. If we find it moot then we should close this.

**Comment by jszwedko** [comment]
This was prompted by a user in discord if I remember correctly. The issue is that it isn't clear to the user if the pattern didn't match anything, or the matched components are not outputting any events. I'm happy to see this solved a different way though (for example by outputting that no components were matched as a warning to stderr).

**Comment by spencergilbert** [comment]
I think improving the UI/UX of `tap` to be more "TUI" (like `top`) could be beneficial, it could more clearly show "yes you're connected, there's not matching components at this time" rather than a blank screen and wondering if it's working properly

**Comment by 001wwang** [comment]
Based on the discussion, I'll move forward with outputting an error/warning on no match rather than exiting.
