### ISSUE TITLE
Add component health status the `/heath` endpoint

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#9469]
See #10555 and #10556. Assuming #10555 is approved, we should include each component's health in the response payload for the `/health` endpoint:

```json
{
  "health": {
    "status": "green"
  },
  "components": {
    "<component-id>": {
      "status": "green"
      "reasons": "..."
   }
}
```

**Comment by spencergilbert** [comment]
Logically `.heath.status = "yellow"` anytime a `.components.*.status == "yellow"` - maybe it should just be `.health.status` for global and `.health.<component_id>.status` rather than the separate nesting for components?

**Comment by jszwedko** [comment]
Closing in-lieu of https://github.com/vectordotdev/vector/issues/10555 having an RFC before we break down the work.
