### ISSUE TITLE
Add component health status to `vector validate`

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#9470]

**Comment by jszwedko** [comment]
Closing this until we revisit this since I think it needs an RFC before we make any changes.

**Comment by jszwedko** [comment]
Decided to just leave it open since it is referenced by https://github.com/vectordotdev/vector/issues/10555

**Comment by jszwedko** [comment]
Closing in-lieu of https://github.com/vectordotdev/vector/issues/10555 having an RFC before we break down the work.
