### ISSUE TITLE
Datadog Logs sink doesn't work with v1 API

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#9484]
As a follow-up from #9475 we have discovered that the logs sink no longer correctly works with either the v1 API. In #9437 we adjusted the healthcheck to accept only 202 ACCEPTED as success, which is only valid for the v2 version of the API. While we did, in #9437, adjust the service to convert ACCEPTED to a `LogApiResponse::OK` we did not update the comment block to reflect this, leaving the note about 200 OK in place. In https://github.com/vectordotdev/vector/pull/9277/ we adjusted all endpoints to use v2 by default but it is not clear from that PR if we intend the sink to function against v1 at all. 

That said, the v2 API is not yet documented at https://docs.datadoghq.com/api/latest/logs/#send-logs as of this writing. From experimentation the healthcheck and service should expect 202 ACCEPTED or 200 OK in order to remain compatible with both API versions. This bug indicates strongly that the logs sink needs an integration test for any supported API version users are allowed to set.

**Comment by vladimir-dd** [comment]
btw there is an internal documentation for v2 API https://github.com/DataDog/architecture/blob/master/rfcs/event-platform-intake-api-v2/rfc.md
