### ISSUE TITLE
PodDisruptionBudget for Vector-aggregator helm chart

### ISSUE THREAD

**Issue by mehta-ankit** [vectordotdev/vector#9493]
### Current Vector Version

```
vector 0.16.0 (x86_64-unknown-linux-gnu 944678d 2021-07-28)
```

### Use-cases

Have an option for pod disruption budget for vector aggregator helm chart.
https://kubernetes.io/docs/tasks/run-application/configure-pdb/

This will allow us to set minAvailable for vector replica pods in case nodes go down for various reasons (scale down, HW failure etc.)

### Attempted Solutions

N.A

### Proposal

Add PDB resource as part of the helm chart. An example is how ElasticSearch deploys it: https://github.com/elastic/helm-charts/blob/master/elasticsearch/templates/poddisruptionbudget.yaml

### References
did not find any related issues.

**Comment by mehta-ankit** [comment]
@jszwedko Sorry for tagging you on a closed issue, but is there a plan to add PDB to the vector-aggregator helm chart ? Was there a reason to not add it to that chart in  https://github.com/vectordotdev/helm-charts/pull/57 🤔

**Comment by spencergilbert** [comment]
> @jszwedko Sorry for tagging you on a closed issue, but is there a plan to add PDB to the vector-aggregator helm chart ? Was there a reason to not add it to that chart in [vectordotdev/helm-charts#57](https://github.com/vectordotdev/helm-charts/pull/57) 🤔

The `vector-aggregator` and `vector-agent` charts are being deprecated in favor of [`vector`](https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/README.md).

**Comment by jszwedko** [comment]
Just to add some more context, the new `vector` chart is a superset of the two existing role based charts. We plan to release it and deprecate the old charts within the next week.

**Comment by mehta-ankit** [comment]
Thank you for the reply!
