### ISSUE TITLE
Polish transform branching

### ISSUE THREAD

**Issue by lukesteensen** [vectordotdev/vector#9514]
The basic functionality was merged in #9169, but there's a bit we should still do to make it more solid:

- [x] Replace `fn named_outputs(&self) -> Vec<String>` with something that more fully models outputs, including name, data type, and whether it is required to be read from. Then drive topology building more directly off of that type. (https://github.com/vectordotdev/vector/pull/10640)
- [x] Revisit the design of the transform enum and traits to simplify and more directly model branching (done as part of https://github.com/vectordotdev/vector/pull/10265)
- [x] Adjust the component spec to break out metrics by output (#10687)
- [x] #10615
- [x] #10660
- [x] Add support for testing them to unit tests (#10540)
- [x] #10871
  - We should consider how `vector top`s TUI should be updated to deal with statistics for named outputs
- [x] Ensure `vector tap` still works
  - That we can `vector tap some_remap.dropped` for just the dropped events or `vector tap some_remap` for the "default output". We should also be able to `vector tap some_route.*` to see all events.
  - `vector tap` functionality was verified against a local build of `master (671109076)`. [Here is the config used for testing](https://gist.github.com/001wwang/696db1bbf0b548724ce9123b1df7f2c6). Checked the following behavior
    - Can `tap` the default output of a `remap` transform
    - Can `tap` the dropped output of a `remap` transform
    - Can `tap` each route of a `route` transform
    - Can `tap` a glob of outputs for `remap` and `route`
  - Will follow this up with adding unit tests. #10972 
- [x] #10832 
- [x] https://github.com/vectordotdev/vector/issues/10686

**Comment by 001wwang** [comment]
Closing this as all the associated tasks are complete.
