### ISSUE TITLE
Track response latency in `splunk_hec` source, others.

### ISSUE THREAD

**Issue by tobz** [vectordotdev/vector#9520]
Currently, one major observability gap that exists in Vector is the inability to understand whether or not Vector is currently the primary bottleneck within an observability pipeline.  While we do expose internal telemetry -- response latencies for sinks, component utilization, and so on -- one piece of the puzzle that is missing is source performance.

In the case of sources, they can generally be grouped in two ways: sources that _pull_ from somewhere, and sources that are _pushed_ into.  In both cases, we still care about operation latency -- how long did it take to process a single message/event? -- but this is far more important in push-based sources.  For callers pushing _into_ Vector, their response latency is almost entirely predicated on Vector's performance, which encompasses everything from Vector itself to downstream sinks being used.

With all of that said, we should start to provide response latency metrics for sources where it makes sense, starting with `splunk_hec`.  It's a common source and response latencies for HTTP are understandable: as soon as we have a request come in, we can trivially track the response latency at multiple levels: time to push to the next component, time to being acknowledged, etc.  Essentially, how long does it take for us to provide a response once we receive the request, regardless of what modes we're in such as blocking buffers, acknowledgements enabled, etc.  How much time is the client spending waiting for us?

While some applications can instrument this themselves -- and should! there are other components in between that could be adding latency before hitting Vector -- we already have the substrate via our internal telemetry to capture and expose this easily.

**Comment by dsmith3197** [comment]
This was done in https://github.com/vectordotdev/vector/pull/18887
