### ISSUE TITLE
Improve pipeline `EventsSent` batching

### ISSUE THREAD

**Issue by fuchsnj** [vectordotdev/vector#9521]
The `EventsSent` metric on pipelines can be further batched for significant performance improvements. It currently sends an `EventsSent` metric for every `poll_flush` on the sink.

(Code below for context)
```rust
if self.events_outstanding > 0 {
    emit!(&EventsSent {
        count: self.events_outstanding,
        byte_size: self.bytes_outstanding,
    });
    self.events_outstanding = 0;
    self.bytes_outstanding = 0;
}
```

During perf testing, if the 0 is changed to 500 (actual value TBD), there is a _significant_ drop in CPU usage (I was seeing ~30% reduction).

Unfortunately this prevents the metrics from being flushed properly when the sink isn't being used anymore.
It should be possible to gracefully close the pipeline sinks and fully flush them, to enable more batching here.

Another concern of increasing this is increased latency for low throughput sinks. (Can add an additional time check for flushing to help with low throughput sinks)

Credit to @tobz for initially thinking of this.

**Comment by bruceg** [comment]
Note that this code path has been overhauled in #9503. The end effect is the same (one emit per flush), but the mechanism and timing is different.

**Comment by jszwedko** [comment]
Closing since this transform was removed for now.
