### ISSUE TITLE
Account for error output in transforms separately from the normal path

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#9524]
The error output path in the topology emits the same event (and so increments the same counters) as the non-error output path. We should consider if these should be distinct events and/or metrics, either in the naming or by the addition of labels.

Ref: https://github.com/vectordotdev/vector/pull/9169#discussion_r723592343

**Comment by lukesteensen** [comment]
This may be handled by #10869

**Comment by jszwedko** [comment]
Indeed, I'll close this in-lieu of https://github.com/vectordotdev/vector/issues/10832
