### ISSUE TITLE
The `path` attribute is included in the `syslog` source example and it should not be

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#9526]
The `path` attribute is only relevant if the `type` is set to `unix`.

https://vector.dev/docs/reference/configuration/sources/syslog/

**Comment by jszwedko** [comment]
I think this is another motivating example to have the examples hand-written (still in cue) rather than generated from the configuration.

**Comment by spencergilbert** [comment]
> I think this is another motivating example to have the examples hand-written (still in cue) rather than generated from the configuration.

I think I've opened a similar issue, `remap` maybe where source and file are both set in the example

**Comment by jszwedko** [comment]
Closing in favor of https://github.com/vectordotdev/vector/issues/10169
