### ISSUE TITLE
Autoscale CI runners

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#9543]
Today we self-host most of our CI runners and do so with a flat provision. This works sort of okay but will rapidly not as we start building more release containers. It's now possible to autoscale self-hosted runners -- see [this document](https://docs.github.com/en/actions/hosting-your-own-runners/autoscaling-with-self-hosted-runners) -- and we're very much going to need this.

**Comment by jszwedko** [comment]
Closing since runners are hosted now.
