### ISSUE TITLE
vrl-parser is a dependency of vrl-core and takes 130 seconds to build in a 150 second build

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#9547]
While working on https://github.com/vectordotdev/vector/issues/9531 I've found several opportunities to either remove dependencies or shuffle them around in the build order to improve build speed. See that ticket for details. When building Vector with `cargo +nightly build -Z timings --no-default-features` from 89e2b08584428b66bf06f60698968892ab5de4b3 I find that the total build time on my system is 150 seconds and 130 seconds of that is `vrl-parser`. I haven't investigated why this crate is slow to build -- though https://github.com/lalrpop/lalrpop/issues/65 and https://github.com/lalrpop/lalrpop/issues/260 probably give an indication -- but it dominates build time. 

Top-level vector requires `vector-core/vrl` which in turn depends on `vrl-core`. The dependency tree of vrl has a diamond present in it:

```
core -> {parser, compiler, diagnostic}
compiler -> {parser, diagnostic}
parser -> {diagnostic}
diagnostic -> {}
stdlib -> {core}
cli -> {core}
```

Reordering VRL internals to remove this diamond or flag out pieces of it that are not necessary unless we're actually parsing VRL in calling code would substantially improve our build speed. We might also avoid whatever makes the parser so slow to build, but that's probably a larger project considering the open tickets linked above.

**Comment by JeanMertz** [comment]
One thing that has crept in over time, is that we added more `pub` rules to the parser grammar. We can remove those by having a single top-level `pub` rule, which should cut down on generated code significantly.

I'll assign myself to this issue so that I can work on it somewhere in the next couple of weeks.

**Comment by JeanMertz** [comment]
Also, just to make sure we're on the same page; this should only happen on the _first build_, it shouldn't re-generate the parser on incremental builds as long as the grammar isn't updated, although I realize this isn't much of a solution for situations when you _want_ to do a fresh build (or when you have no choice, such as in some CI set-ups).
