### ISSUE TITLE
Reduce cloning in internal events

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#9593]
This proposal stems from two observations:

1. Our internal event framework breaks apart emitting observability data into `emit_logs` and `emit_metrics`. However, these two functions are only ever called in one place, which calls both in sequence.
2. Both of the above trait functions take `self` by reference, which means none of the internal event data is owned by these called functions. However, when emitting metrics, the values of all associated labels must be owned (or have a lifetime of `'static`). This frequently requires any textual data provided to those metrics to be cloned more than necessary.

Proposal: merge the two trait functions into one `fn emit(self)` which will own the internal event data, which will allow for direct emission of owned data into the metrics. This may still require a clone to put the data into the event, but should allow for eliminating at least one such clone in a number of cases.

**Comment by blt** [comment]
I buy it for sure.

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/11800
