### ISSUE TITLE
Collect process metrics

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#9626]
A user requested the ability to record metrics by process (like CPU, memory, etc.).

I think this could be a separate source or incorporated into the `host_metrics` source.

**Comment by LeeTeng2001** [comment]
I would love to see this

**Comment by LeeTeng2001** [comment]
Currently I rely on vector host metrics to scrape details about host machine, it's awesome as I don't need another agent like node scrapper to provide this information

**Comment by LeeTeng2001** [comment]
can i get my hands on this?

**Comment by jszwedko** [comment]
> can i get my hands on this?

Sure!

**Comment by LeeTeng2001** [comment]
Hi, since heim wouldn't be replaced in a short while, I cannot implement process metrics using heim crates. can we use both dependencies and only sysinfo for process metrics?

**Comment by LeeTeng2001** [comment]
In other word, should I make a PR that only uses sysinfo for process metrics or a PR with heim completely replaced?

**Comment by LeeTeng2001** [comment]
I already got a working sample, thanks for the kind & quick response! Vector is a great software, would love to contribute

**Comment by pront** [comment]
Hi @LeeTeng2001, first of all, thank you for your interest in contributing!

> Hi, since heim wouldn't be replaced in a short while, I cannot implement process metrics using heim crates. can we use both dependencies and only sysinfo for process metrics?

I think it is fine using sysinfo to implement things that heim doesn't support.

Regarding the heim vs sysinfo debate, the only concern IMO if [sysinfo](https://crates.io/crates/sysinfo) can satisfy all metrics produced by the [host_metrics source](https://vector.dev/docs/reference/configuration/sources/host_metrics/). 

It is obvious that sysinfo is significantly more popular now and generally I would be in favor of using it going forward. But that will require some extra work and validation. 

And yes, ideally we should only use one dependency.

**Comment by LeeTeng2001** [comment]
I would like to remove heim but I fell like it would be too much of a PR & out of this issue scope, I'd like to keep the PR small and only implement process metrics for now.

**Comment by LeeTeng2001** [comment]
This issue is closed, may I asked when will the next release be? I would love to use this feature

**Comment by pront** [comment]
The next release is 0.43. Expected to happen on Dec 2nd. You can see this via the [milestone](https://github.com/vectordotdev/vector/milestone/135). Also, you can see our public calendar.vector.dev

**Comment by pront** [comment]
https://github.com/vectordotdev/vector/issues/21861
