### ISSUE TITLE
[sink] [http] `events_out_total` internal metric is incorrect (prometheus exporter)

### ISSUE THREAD

**Issue by hhromic** [vectordotdev/vector#9647]
### Vector Version

```
vector 0.17.0 (x86_64-unknown-linux-gnu 3d34cde 2021-10-08)
```

### Vector Configuration File

Consider the following example pipeline to send dummy events to HTTPBin:
```yaml
api:
  enabled: true
  address: 0.0.0.0:8686

sources:
  logs:
    type: generator
    format: syslog
  metrics:
    type: internal_metrics

sinks:
  http:
    type: http
    inputs:
      - logs
    uri: http://httpbin.org/post
    encoding: ndjson
  prometheus:
    type: prometheus_exporter
    inputs:
      - metrics
    address: 0.0.0.0:9598
```

### Expected Behavior

The above configuration generates one dummy event per second and then sends them to HTTPBin, which can be verified running `vector top` (observe how the number of events out of `generator` matches the number of events in/out in `http`):

![image](https://user-images.githubusercontent.com/5802993/137555050-711ebfef-2099-4196-a1a6-a5a6bc6ed158.png)

At the same time, when scraping the internal metrics using the `prometheus` sink, I expect the same events count:
```
$ curl -s http://127.0.0.1:9598/metrics | grep -E 'vector_events_(in|out)_total' | grep http
vector_events_in_total{component_id="http",component_kind="sink",component_name="http",component_type="http"} 62 1634333281514
vector_events_out_total{component_id="http",component_kind="sink",component_name="http",component_type="http"} 62 1634333281514
```

### Actual Behavior

The actual reading of the `out` metric when scraping the Prometheus exporter is somewhat double the real value:
```
$ curl -s http://127.0.0.1:9598/metrics | grep -E 'vector_events_(in|out)_total' | grep http
vector_events_in_total{component_id="http",component_kind="sink",component_name="http",component_type="http"} 62 1634333281514
vector_events_out_total{component_id="http",component_kind="sink",component_name="http",component_type="http"} 121 1634333281514
```

**Comment by hhromic** [comment]
I just realised that the documentation now says that `events_in_total` and `events_out_total` are deprecated:
> This metric is deprecated and will be removed in a future version. Use component_sent_events_total instead.
> This metric is deprecated and will be removed in a future version. Use component_received_events_total instead.

I went to check these metrics and they are indeed correct:
```
$ curl -s localhost:9598/metrics | grep -E '^vector_component_(sent|received)_events' | grep http
vector_component_received_events_total{component_id="http",component_kind="sink",component_name="http",component_type="http"} 157 1634387794253
vector_component_sent_events_total{component_id="http",component_kind="sink",component_name="http",component_type="http"} 157 1634387794253
```

I still think `events_(in|out)_total` should be correct until fully removed though.

**Comment by jszwedko** [comment]
Interesting, thanks for noting that @hhromic and agreed, `events_out_total` should be correct until it is removed.
