### ISSUE TITLE
Migrate off of `chrono` to `time`

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#9675]
`chrono` is lightly maintained these das (no release in a year nor responsive to issues, including security issues) and the `time` crate reportedly implements much of what `chrono` is used for.

We should:

* Remove our own dependency on `chrono`
  * We should maintain support for the `strftime` specifiers for parsing and formatting. The `time` crate [does not support this] so we will need to implement it ourselves.
* Open issues on all dependencies that depend on chrono to see if they are open to migrating. Ideally we could open PRs on the dependencies to help expedite the process.

This would resolve `RUSTSEC-2020-0071`.

**Comment by jszwedko** [comment]
We might be able to translate `strftime` specifiers into their specifiers https://github.com/time-rs/format-converter.

**Comment by spencergilbert** [comment]
> Does the `time` crate have support for timezones, like is present in [`chrono-tz`](https://github.com/chronotope/chrono-tz/)? We use this for handling local times.

Possible option: https://github.com/Yuri6037/time-tz

**Comment by spencergilbert** [comment]
[`chrono`](https://github.com/chronotope/chrono) appears to be getting picked back up

**Comment by jszwedko** [comment]
Closing this since `chrono` seems to have more active maintenance these days.
