### ISSUE TITLE
[RUSTSEC-2020-0159] Potential segfault in localtime_r invocations

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#9679]
We worked around this by patching chrono to remove the dependency on `time` `v0.1` but we should resolve this either by https://github.com/vectordotdev/vector/issues/9675 or https://github.com/chronotope/chrono/pull/578.

**Comment by spencergilbert** [comment]
https://github.com/chronotope/chrono/issues/602 <- Updates on this vuln
