### ISSUE TITLE
Audit sources to ensure compliance with the component spec

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#9687]
The [component spec](https://github.com/vectordotdev/vector/blob/master/docs/specs/component.md) contains specifications for configuration, event processing metrics, and error reporting. #9326 tracks enhancing sources with the full event processing metrics, but they still need to be audited for compliance with the remainder of the spec. Some of these may already be completed by the closing of the associated issue in #9326.

- [ ] Audit the `apache_metrics` source to adhere to the component spec 
- [ ] Audit the `aws_ecs_metrics` source to adhere to the component spec 
- [ ] Audit the `aws_kinesis_firehose` source to adhere to the component spec 
- [ ] Audit the `aws_s3` source to adhere to the component spec 
- [ ] Audit the `datadog` source to adhere to the component spec 
- [ ] Audit the `dnstap` source to adhere to the component spec 
- [ ] Audit the `docker_logs` source to adhere to the component spec 
- [ ] Audit the `eventstoredb_metrics` source to adhere to the component spec 
- [ ] Audit the `exec` source to adhere to the component spec 
- [ ] Audit the `file` source to adhere to the component spec 
- [ ] Audit the `fluent` source to adhere to the component spec 
- [ ] Audit the `generator` source to adhere to the component spec 
- [ ] Audit the `heroku_logs` source to adhere to the component spec 
- [ ] Audit the `host_metrics` source to adhere to the component spec 
- [ ] Audit the `http` source to adhere to the component spec 
- [ ] Audit the `internal_logs` source to adhere to the component spec 
- [ ] Audit the `internal_metrics` source to adhere to the component spec 
- [ ] Audit the `journald` source to adhere to the component spec 
- [ ] Audit the `kafka` source to adhere to the component spec 
- [ ] Audit the `kubernetes_logs` source to adhere to the component spec 
- [ ] Audit the `logstash` source to adhere to the component spec 
- [ ] Audit the `mongodb_metrics` source to adhere to the component spec 
- [ ] Audit the `nats` source to adhere to the component spec 
- [ ] Audit the `nginx_metrics` source to adhere to the component spec 
- [ ] Audit the `postgresql_metrics` source to adhere to the component spec 
- [ ] Audit the `prometheus` source to adhere to the component spec 
- [ ] Audit the `prometheus_remote_write` source to adhere to the component spec 
- [ ] Audit the `prometheus_scrape` source to adhere to the component spec 
- [ ] Audit the `socket` source to adhere to the component spec 
- [ ] Audit the `splunk_hec` source to adhere to the component spec 
- [ ] Audit the `statsd` source to adhere to the component spec 
- [ ] Audit the `stdin` source to adhere to the component spec 
- [ ] Audit the `syslog` source to adhere to the component spec 
- [ ] Audit the `vector` source to adhere to the component spec

**Comment by binarylogic** [comment]
Closing in favor of #12921
