### ISSUE TITLE
Audit sinks to ensure compliance with the component spec

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#9688]
The [component spec](https://github.com/vectordotdev/vector/blob/master/docs/specs/component.md) contains specifications for configuration, event processing metrics, and error reporting. #9325 tracks enhancing sinks with the full event processing metrics, but they still need to be audited for compliance with the remainder of the spec. Some of these may be completed by the closing of the associated issue in #9325.

- [ ] Audit the `aws_cloudwatch_logs` sink to adhere to the component spec 
- [ ] Audit the `aws_cloudwatch_metrics` sink to adhere to the component spec 
- [ ] Audit the `aws_kinesis_firehose` sink to adhere to the component spec 
- [ ] Audit the `aws_kinesis_streams` sink to adhere to the component spec 
- [ ] Audit the `aws_s3` sink to adhere to the component spec 
- [ ] Audit the `aws_sqs` sink to adhere to the component spec 
- [ ] Audit the `azure_blob` sink to adhere to the component spec 
- [ ] Audit the `azure_monitor_logs` sink to adhere to the component spec 
- [ ] Audit the `blackhole` sink to adhere to the component spec 
- [ ] Audit the `clickhouse` sink to adhere to the component spec 
- [ ] Audit the `console` sink to adhere to the component spec 
- [ ] Audit the `datadog_archives` sink to adhere to the component spec 
- [ ] Audit the `datadog_events` sink to adhere to the component spec 
- [ ] Audit the `datadog_logs` sink to adhere to the component spec 
- [ ] Audit the `datadog_metrics` sink to adhere to the component spec 
- [ ] Audit the `elasticsearch` sink to adhere to the component spec 
- [ ] Audit the `file` sink to adhere to the component spec 
- [ ] Audit the `gcp_cloud_storage` sink to adhere to the component spec 
- [ ] Audit the `gcp_pubsub` sink to adhere to the component spec 
- [ ] Audit the `gcp_stackdriver_logs` sink to adhere to the component spec 
- [ ] Audit the `gcp_stackdriver_metrics` sink to adhere to the component spec 
- [ ] Audit the `honeycomb` sink to adhere to the component spec 
- [ ] Audit the `http` sink to adhere to the component spec 
- [ ] Audit the `humio_logs` sink to adhere to the component spec 
- [ ] Audit the `humio_metrics` sink to adhere to the component spec 
- [ ] Audit the `influxdb_logs` sink to adhere to the component spec 
- [ ] Audit the `influxdb_metrics` sink to adhere to the component spec 
- [ ] Audit the `kafka` sink to adhere to the component spec 
- [ ] Audit the `logdna` sink to adhere to the component spec 
- [ ] Audit the `loki` sink to adhere to the component spec 
- [ ] Audit the `mod` sink to adhere to the component spec 
- [ ] Audit the `nats` sink to adhere to the component spec 
- [ ] Audit the `new_relic_logs` sink to adhere to the component spec 
- [ ] Audit the `papertrail` sink to adhere to the component spec 
- [ ] Audit the `prometheus_exporter` sink to adhere to the component spec 
- [ ] Audit the `prometheus_remote_write` sink to adhere to the component spec 
- [ ] Audit the `pulsar` sink to adhere to the component spec 
- [ ] Audit the `redis` sink to adhere to the component spec 
- [ ] Audit the `sematext_logs` sink to adhere to the component spec 
- [ ] Audit the `sematext_metrics` sink to adhere to the component spec 
- [ ] Audit the `socket` sink to adhere to the component spec 
- [ ] Audit the `splunk_hec_logs` sink to adhere to the component spec 
- [ ] Audit the `splunk_hec_metrics` sink to adhere to the component spec 
- [ ] Audit the `statsd` sink to adhere to the component spec 
- [ ] Audit the `vector` sink to adhere to the component spec

**Comment by binarylogic** [comment]
Closing in favor of #12921
