### ISSUE TITLE
No new vector version(0.17.2) in helm repo https://helm.vector.dev

### ISSUE THREAD

**Issue by enkov** [vectordotdev/vector#9714]
In the new helm repository, there is no new chart version. But in the old repository it is. And also charts in these two repos have some diffs.
```
helm search repo vector
timberio/vector           	0.11.1       	0.11.1     	A Helm chart for Vector observability stack
timberio/vector-agent     	0.17.2       	0.17.2     	A Helm chart to collect Kubernetes logs with Ve...
timberio/vector-aggregator	0.17.2       	0.17.2     	A Helm chart to aggregate data with Vector
vector/vector-agent       	0.17.0       	0.16.1     	A Helm chart to collect Kubernetes logs with Ve...
vector/vector-aggregator  	0.17.1       	0.16.1     	A Helm chart to aggregate data with Vector
vector/vector-shared      	0.1.0        	           	Shared dependencies of Vector Helm charts
```

**Comment by spencergilbert** [comment]
> @spencergilbert are we at the point yet that we could drop the charts in this repo? At the least, I imagine we should drop it from the release process.

Definitely, we're not pushing any changes to these at this point. There's still some weirdness about getting the kubernetes manifests released and updated
