### ISSUE TITLE
[VRL] Add IPv6 support to `ip_aton()` and `ip_ntoa()`

### ISSUE THREAD

**Issue by hhromic** [vectordotdev/vector#9716]
### Current Vector Version

```
vector 0.17.2 (x86_64-unknown-linux-gnu cc07286 2021-10-19)
```

### Use-cases

The current implementation of VRL's `ip_aton()` and `ip_ntoa()` only considers IPv4 addresses.
However, as briefly discussed in the initial implementing PR, an extension to support IPv6 addresses is welcomed.

Before, [I suggested](
https://github.com/vectordotdev/vector/pull/8042#issuecomment-868857109
) to adopt a standard bytes array representation for IPv6 addresses as this is used by other software, i.e. Python and Vertica. I think this is a nice and easy to use representation that Vector can easily adopt as well.

The use-case for this is the same as for storing IPv4 addresses in numeric form: to be able to more efficiently compute IP address operations, e.g. network memberships, in the data in contrast to having to parse string-based representations. Normally for this, the storage layer implements a schema that includes both the string representation and a numeric/bytes array representation. Vector can then directly convert the data before insertion in the storage layer of the use-case later.

### Attempted Solutions

As far as I am aware, there is currently no easy way in VRL to convert an IPv6 string into a bytes array that doesn't involve manually parsing an IPv6 address segment-by-segment and then octet-by-octet.

### Proposal

There are two big approaches to provide the desired functionality:
1. Implement IPv6 support to the existing `ip_aton()` and `ip_ntoa()` functions
2. Implement a separate set of functions for IPv6 addresses, i.e. `ip6_aton()` and `ip6_ntoa()`.

I did a bit of research and turns out Rust is pretty good at handling both types of address automagically:
```rust
use std::net::IpAddr;

fn main() {
    let values = [
        "192.168.0.1",
        "2001:0db8:85a3:0000:0000:8a2e:0370:7334",
        "127.0.0.1",
        "::1",
    ];

    for value in values {
        let ip = value.parse::<IpAddr>().unwrap();

        match ip {
          IpAddr::V4(ipv4) => println!("ipv4: {}, numeric: {:?}", ipv4, u32::from(ipv4)),
          IpAddr::V6(ipv6) => println!("ipv6: {}, bytes array: {:?}", ipv6, ipv6.octets()),
        }
    }
}
```
```
ipv4: 192.168.0.1, numeric: 3232235521
ipv6: 2001:db8:85a3::8a2e:370:7334, bytes array: [32, 1, 13, 184, 133, 163, 0, 0, 0, 0, 138, 46, 3, 112, 115, 52]
ipv4: 127.0.0.1, numeric: 2130706433
ipv6: ::1, bytes array: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
```

Thus option (1) could be very easily implemented and is more towards an unified API (doesn't matter what kind of IP address you want to convert, it will get the job done).

However, option (2) provides a cleaner API as the return type will always be the same for each set of functions instead of the mixture of `u32` (for IPv4) and `[u8; 16]` (for IPv6). Cleaner API means that if we don't know in advance the type of address, we will have to do "try-and-error" at VRL.

Looking forward for your thoughts :)

### References

- #7188
- #8042
- #9208

**Comment by jszwedko** [comment]
Thanks for opening this detailed issue @hhromic ! I'm partial to the separate functions, for now, given the return types are so different.

**Comment by hhromic** [comment]
Separate functions sounds good to us as well. We could easily use an error coalesce chain pattern in that case:
```coffee
.ipNum = ip_aton(.ip) ?? ipv6_aton(.ip) ?? null
```

The reason I was suggesting both functions to be unified is that other [IP-based functions](https://vector.dev/docs/reference/vrl/functions/#ip-functions)  already seem to work with IPv4/IPv6 addresses interchangeably. However, it is true that those existing functions do not return different types according to the IP address version (they mostly return strings and booleans), which makes `ip_aton`/`ip_ntoa` "special" in this case.
