### ISSUE TITLE
Ability to override existing HTTP request headers in the HTTP sink.

### ISSUE THREAD

**Issue by tobz** [vectordotdev/vector#9768]
A user on [Discord](https://discord.com/channels/742820443487993987/746070591097798688/901096371157880873) asked if there was a way to override the `Content-Type` header when using the HTTP sink, as the downstream service they were sending to requires a specific value for that header.  Since custom headers defined via `request.headers` are added after-the-fact, and do not override existing headers, this only allows users to add either new headers or add a duplicate of headers which Vector itself defines on the request.

It could be useful to allow the HTTP sink to specify whether or not custom headers can override the headers which Vector itself defines.

**Comment by NicolasFloquet** [comment]
Hello,

This is indeed something that would be great.
We tried using http sink to send data to an Azure EventHub. Sadly, EventHub relies on Content-Type header to discriminate a single JSON event containing an array, and a batch of JSON event. For this last situation, content-type "application/vnd.microsoft.servicebus.json" should be used.
 
Would it be an acceptable behavior to simply override default headers when specified in sink configuration?

**Comment by jszwedko** [comment]
Hi @NicolasFloquet !

Yeah, I think that would be reasonable: to just apply the user configured headers last so that they override any Vector adds by default. We'd welcome a contribution if you are up for it.

**Comment by shokohsc** [comment]
Hello, isn't it already implemented [there](https://github.com/vectordotdev/vector/blob/master/src/sinks/http.rs#L292) ? 
I'm not familiar with rust but What I understand is this: if the object delimiter is a comma, the Content-type will have 'application/json' value, obviously I must be wrong but could anyone explain it to me ?

**Comment by jszwedko** [comment]
> Hello, isn't it already implemented [there](https://github.com/vectordotdev/vector/blob/master/src/sinks/http.rs#L292) ? I'm not familiar with rust but What I understand is this: if the object delimiter is a comma, the Content-type will have 'application/json' value, obviously I must be wrong but could anyone explain it to me ?

Hey @shokohsc ! It is, but then you can see that more headers are added lower down. I think we want to allow users to override the automatically added headers by applying those last.

**Comment by shokohsc** [comment]
Oh ok, thank you @jszwedko

**Comment by jacksgt** [comment]
Hi folks,

I just wanted to chime in and say that this appears to work now (i.e. user-supplied headers overwrite default headers) with the following configuration:

```
[sinks.http]
type = "http"
inputs = [ "*" ]
uri = "http://httpbin:80/status/200"
encoding.codec = "json"
request.headers.content-type = "application/json; charset=UTF-8; foo=bar; baz"
```

Result in the following request being send:
```
POST /status/200 HTTP/1.1
content-type: application/json; charset=UTF-8; foo=bar; baz
accept-encoding: gzip
user-agent: Vector/0.29.1 (x86_64-unknown-linux-musl 74ae15e 2023-04-20 14:50:42.739094536)
host: httpbin
content-length: 880

...
```

(captured with `nc -Nl 8080`)

**Comment by StephenWakely** [comment]
> I just wanted to chime in and say that this appears to work now

Ah, perfect. Thanks for letting us know. Have tested and can confirm it works.
