### ISSUE TITLE
Vrl Performance

### ISSUE THREAD

**Issue by StephenWakely** [vectordotdev/vector#9811]
Vrl frequently flags up as a bottleneck in our performance testing. We could benefit greatly from optimising the language.

We will start with an RFC to discuss the various options for moving the language forwards.

**Comment by JeanMertz** [comment]
I'll close this, as we never created the RFC (I believe, other than the VM RFC), but did do a lot of work to improve performance. Anything else we can still do is best described in specific issues to tackle specific performance problems.
