### ISSUE TITLE
vector过滤规则失效

### ISSUE THREAD

**Issue by olyhao** [vectordotdev/vector#9844]
问题：业务日志打到kafka中，使用vector sources为kafka，sinks为本地日志文件，想使用transforms规则删除log字段失败。

源日志内容:
"@timestamp":"2021-10-29T08:54:59.762993Z","@filepath":"/var/log/eks-log-agent/test_test-nginx-1-86cc9c8bd-7568q_61f3db85-681a-451e-88a2-38a963aa3f88/containers/nginx/rootfs/02c3963347ce5sdf6e2d94e4d02edb13309702c8fed0d18c9253d24da0274a22b8/var/log/nginx.log","log":"111","kubernetes":"{\"pod_name\":\"test-nginx-1-86cc9c8bd-7568q\",\"namespace\":\"test\",\"annotations\":{\"eks.tke.cloud.tencent.com/cluster-id\":\"cls-sfknxvhi1\"},\"labels\":{\"nginx\":\"nginx1\",\"pod-template-hash\":\"86cc9c8bd\"}}"}

vector配置：
[sources.test-nginx-1]
type = "kafka"
bootstrap_servers = "172.16.4.183:9092,172.16.8.166:9092,172.16.32.29:9092"
group_id = "test-consumer-group"
#key_field = "message_key"
topics = [ "oly-nginx" ]

[transforms.modifys]
type = "remap"
inputs = ["test-nginx-1"]
source = '''
         del(.log)
'''

[sinks.myfile]
type = "file"
inputs = [ "modifys" ]
compression = "none"
path = "/tmp/nginx1/%Y-%m-%d/nginx1-%Y-%m-%d-%H.log"
encoding = "text"

**Comment by jszwedko** [comment]
Hi @olyhao ! What is the failure you are seeing?

**Comment by olyhao** [comment]
@jszwedko hi, I read the official document many times and tried many times for this problem; I solved it with the help of my friend.
Configure decoding.codec = "json" in sources; configure encoding.codec = "ndjson" in sinks; you can implement the del(.log) function.
But I encountered another problem. Our log volume is very large. When we started multiple vector processes to consume Kafka, we found a large amount of messages accumulated. What configuration parameters need to be changed to solve this problem, thank you.

**Comment by olyhao** [comment]
Hope to get your help, thank you

**Comment by jszwedko** [comment]
Hi @olyhao !

Thank you for sharing how you fixed your issue.

I'm not very familiar with tuning Kafka consumers, but there are a large number of configuration options you could investigate on the library we use, librdkafka: https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md . These can be configured on the `kafka` source under [`librdkafka_options`](https://vector.dev/docs/reference/configuration/sources/kafka/#librdkafka_options).

How many messages and bytes per second do you see being consumed per Vector instance? I am just trying to get a rough idea of the performance you are seeing to see if it is out-of-the-ordinary.

Scaling out horizontally, of course, is easy to do for Kafka sources.

**Comment by jszwedko** [comment]
Closing since this is stale. Feel free to re-open if you have any additional questions.
