### ISSUE TITLE
Add support for end-to-end acknowledgements to all relevant sources

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#9856]
Reopened and reformatted from #7336

- [x] #10119
- [x] #7653
- [x] #10121
- [x] Add support for end-to-end acknowledgements to `logstash` source 
- [x] #7652

---

- [ ] #7462
- [ ] #10848
- [ ] #10849
- [ ] #10850
- [x] #7647
- [x] #7648
- [x] #9947
- [x] #7650
- [x] #7459
- [x] #7431
- [x] #7651
- [x] #7460
- [x] #7461

**Comment by jszwedko** [comment]
Closing this out since we did the high priority sources. The remaining sources have their own issues.
