### ISSUE TITLE
Add support for end-to-end acknowledgement in all sinks

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#9857]
Revised and reformatted from #7337

- [x] #7657
- [x] Add support for end-to-end acknowledgements to `aws_cloudwatch_logs` sink
- [x] Add support for end-to-end acknowledgements to `aws_kinesis_firehose` sink
- [x] Add support for end-to-end acknowledgements to `aws_kinesis_streams` sink
- [x] #7536
- [x] Add support for end-to-end acknowledgements to `aws_sqs` sink
- [x] Add support for end-to-end acknowledgements to `azure_blob` sink
- [x] #7411
- [x] Add support for end-to-end acknowledgements to `blackhole` sink
- [x] #13022
- [x] Add support for end-to-end acknowledgements to `datadog_archives` sink
- [x] Add support for end-to-end acknowledgements to `datadog_events` sink
- [x] #7354
- [x] #7520
- [x] #7448
- [x] #7664
- [x] Add support for end-to-end acknowledgements to `gcp_cloud_storage` sink
- [x] #7265
- [x] Add support for end-to-end acknowledgements to `humio_logs` sink
- [x] Add support for end-to-end acknowledgements to `humio_metrics` sink
- [x] Add support for end-to-end acknowledgements to `kafka` sink
- [x] Add support for end-to-end acknowledgements to `nats` sink
- [x] Add support for end-to-end acknowledgements to `new_relic_logs` sink
- [x] Add support for end-to-end acknowledgements to `papertrail` sink
- [x] #13742
- [x] #13755
- [x] #13743
- [X] Add support for end-to-end acknowledgements to `redis` sink
- [X] Add support for end-to-end acknowledgements to `sematext_logs` sink
- [x] Add support for end-to-end acknowledgements to `socket` sink
- [x] Add support for end-to-end acknowledgements to `splunk_hec_metrics` sink
- [x] Add support for end-to-end acknowledgements to `statsd` sink
- [x] #7625
- [x] Add support for end-to-end acknowledgements to `websocket` sink

**Comment by bruceg** [comment]
Noting that all new-style stream sinks that use the `Driver` framework have acknowledgement support automatically enabled, so they can get checked off here when they are merged.

**Comment by jszwedko** [comment]
These will be tackled by the sink rewrites https://github.com/vectordotdev/vector/issues/9261

**Comment by bruceg** [comment]
All tasks are now done.
