### ISSUE TITLE
Improve the default vector.toml configuration file

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#986]
This is a follow up to https://github.com/timberio/vector/issues/980.

The [current default `vector.toml` configuration file](https://github.com/timberio/vector/blob/master/config/vector.toml) is a simple `stdin` and `stdout` setup. The purpose of this is to ensure vector starts by default with new installations but it's pretty unhelpful. I think we can do better with new user experiences:

1. Using the `fake` source referenced above with a helpful onboarding message.
2. Collecting system stats (ex: CPU/memory usage events) and emitting them.
3. Leaving it the way it is but producing more meaningful logs that direct the user to update the `/etc/vector/vector.toml` file.

**Comment by jszwedko** [comment]
Closing since this was looped into #11491 to create better default configurations.
