### ISSUE TITLE
vector top displays N/A for Events Out for sinks

### ISSUE THREAD

**Issue by 001wwang** [vectordotdev/vector#9875]
Reported by [user in discord](https://discord.com/channels/742820443487993987/746070591097798688/905103873843290163). Based on limited testing to reproduce, the `N/A` issue seems to occur for at least the `file` and `blackhole` sinks. 
### Vector Version

```
vector 0.17.3 (x86_64-apple-darwin d72c6e7 2021-10-21)
```

### Vector Configuration File
Here's a quick sample config.
```
[api]
enabled = true

[sources.gen]
type = "generator"
format = "syslog"
interval = 2

[sinks.file]
type = "file"
inputs = ["gen"]
path = "data_dir/file.log"
encoding = "ndjson"
```

### Expected Behavior

`Events Out` metric is displayed for the sink in the `top` gui.

### Actual Behavior

`Events Out` is `N/A` for the sink in the `top` gui.

**Comment by jszwedko** [comment]
I think this will be covered by #9325 . We are currently in the process of ensuring that all components are consistently instrumented.
