### ISSUE TITLE
Complete end-to-end acknowledgements

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#9877]
Copied from #1107

- [x] #9856 
- [x] #7382
- [x] #8020
- [x] #4127
- [x] #7447
- [x] #9880
- [x] #10290
- [x] #10356
- [x] #10291
- [x] #7412
- [x] #9587 

Deferred:

- [x] #10543
- [x] #10378
- [ ] #10273
- [ ] #9857 (being worked on as part of sink rewrites)
- [ ] #10292 
- [ ] #7369

**Comment by jszwedko** [comment]
I added  #10378 here to look into to since it seems to be related to e2e acks.

**Comment by jszwedko** [comment]
Closing since epic work was complete and we have issues tracking the remainder.
