### ISSUE TITLE
Ignore `rate_limit_secs` tracing attribute for rate limited logs

### ISSUE THREAD

**Issue by LucioFranco** [vectordotdev/vector#989]
Currently, when we have an event that requires rate-limiting we add an attribute to its tracing event like so `info!(rate_limit_secs = 30)`. It would be nice to avoid having to print this via the `FmtSubscriber`. 

## Solution

Not sure what the best method here is for trying to filter out an attribute from being printed. This would require the `tracing-subscriber` crate to support this feature.

/cc @hawkw

**Comment by hawkw** [comment]
@LucioFranco https://github.com/tokio-rs/tracing/issues/73 is a feature request for adding a way to specify skipped field values, this should work with `FmtSubscriber` pretty easily. It's currently blocked on https://github.com/tokio-rs/tracing/pull/241, which I'd like to merge soon.

**Comment by jszwedko** [comment]
Closing this in-lieu of https://github.com/vectordotdev/vector/issues/996
