### ISSUE TITLE
Add trace path in pipelines transforms

### ISSUE THREAD

**Issue by jdrouet** [vectordotdev/vector#9897]
Following https://github.com/vectordotdev/vector/pull/9733
Requires the `trace` feature to be ready

**Comment by jdrouet** [comment]
The latest implementation of traces is based on logs, therefore, this part of the pipelines transform feature is not needed anymore.

**Comment by jszwedko** [comment]
Let's leave this open until https://github.com/vectordotdev/vector/pull/9634 is merged. I think we will need to have traces as a first-class data type for routing to be able to easily send them to tracing specific endpoints. For example, we wouldn't want to forward traces from the `datadog_agent` source to `datadog_logs`.
