### ISSUE TITLE
Find a better way to clone the ConfigBuilder and PipelinesConfig

### ISSUE THREAD

**Issue by jdrouet** [vectordotdev/vector#9898]
Following [this comment](https://github.com/vectordotdev/vector/pull/9733#discussion_r741983883) 

Right now, to clone a TransformConfig we need to serialize and deserialize it.

This hack is present on the [ConfigBuilder](https://github.com/vectordotdev/vector/blob/d849e22f8154442f276757f597e374673b67fb00/src/config/builder.rs#L43) and on the [PipelinesConfig](https://github.com/vectordotdev/vector/pull/9733/files#diff-967c13643e8c3f738a2676c994829132e64d81f82a88e62e98de7fc2b9792061R81).

**Comment by jszwedko** [comment]
Closing since this transform was removed for now.
