### ISSUE TITLE
Vector logs an error message when unit testing a task transform

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#9919]
When unit testing a task transform (like `lua`), Vector outputs a log at the ERROR level:

```
ERROR vector::config::unit_test: Using a recently refactored `TaskTransform` in a unit test. You may experience limited support for multiple inputs.
```

This should really be a warning instead.

**Comment by spencergilbert** [comment]
I _definitely_ brought this up before I joined and it was determined that was the correct level... let me see if I can find it.

**Comment by jszwedko** [comment]
Yeah, that sounds vaguely familiar to me too, but I'm struggling to think why. If unit tests really can't/shouldn't be used with task transforms, we should probably just fail to run the unit tests if they are.

**Comment by jszwedko** [comment]
@001wwang this issue is moot with your work in https://github.com/vectordotdev/vector/pull/10540, right?

**Comment by jszwedko** [comment]
👍 thanks for confirming! I'll close this out.
