### ISSUE TITLE
Buffer Improvements: update topology builder to understand/use new-style buffer implementation

### ISSUE THREAD

**Issue by tobz** [vectordotdev/vector#9922]
_Part of the Buffer Improvements RFC ([RFC](https://github.com/vectordotdev/vector/blob/ac2b1f04fe12251b9c24af58461891100cc0ffe2/rfcs/2021-10-14-9477-buffer-improvements.md), #9476)_

Once we have suitable buffer replacements to be at parity with the existing buffer options, we'll need to update the topology builder in `vector` to fully utilize the new style of buffer configuration, and actually use the new buffers.

At this point, effectively, the new system would be active and usable... overflowing, and all of that.

**Comment by jszwedko** [comment]
Closing since Vector has supported the new v2 buffers for a while now.
