### ISSUE TITLE
Improve soak comment aesthetic

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#9926]
As a follow on to #9515 with #9925 having landed the aesthetics of the posted PR comment could use some improvement. Namely:

* the preamble is structured like a git commit for no reason
* units are declared to be "in bytes" when they are "bytes/second"
* bytes is awkward and we should be using human-oriented scales of units

The comment table is a product of `soaks/bin/analyze_experiment.sh` so we need only to modify what that script kicks out.

**Comment by spencergilbert** [comment]
I definitely appreciate @jszwedko's impression that collapsed sections would just make people not read them 🤔

**Comment by blt** [comment]
I think an upfront, compact section that shows deltas between baseline and comparison would be ideal, uncollapsed. That way, no matter what, the information is present for people to inspect. We can fiddle with collapsing or not collapsing the larger, more detailed tables below. 

One thing we do want to keep aware of is avoiding inattentional blindness. Present too much info and people will tune it out, especially important because I want to avoid making the soaks a required CI step.

**Comment by blt** [comment]
It would also be useful if the comment would link to the action summary.

**Comment by binarylogic** [comment]
Just posting this here after chatting with @blt . I think we should consider reducing the noise if no regression is detected. The fact that we're introducing a pass/fail regression mechanism means we can rely on regular old CI checks instead of PR comments.

**Comment by blt** [comment]
> Just posting this here after chatting with @blt . I think we should consider reducing the noise if no regression is detected. The fact that we're introducing a pass/fail regression mechanism means we can rely on regular old CI checks instead of PR comments.

Considering our soak runners don't autoscale it can take an hour to get soak results, which makes me nervous about making this a CI check. That said, flagging regressions in the comment and rolling up bits that are not regressed is a good change and is feasible.

**Comment by blt** [comment]
Closed by #10184
