### ISSUE TITLE
tests: disable internal log rate limiter during unit tests

### ISSUE THREAD

**Issue by hhromic** [vectordotdev/vector#9929]
### Current Vector Version

```
vector 0.17.3 (x86_64-unknown-linux-gnu d72c6e7 2021-10-21)
```

### Use-cases

Unit testing of Vector pipelines (transforms, end-to-end, etc).

### Attempted Solutions

Consider the following Vector toy pipeline with associated unit tests:
```yaml
transforms:
  my-transform:
    type: remap
    inputs:
      - dummy
    drop_on_error: true
    source: |-
      . = parse_json!(.message)

tests:
  - name: test1
    inputs:
      - insert_at: my-transform
        type: log
        log_fields:
          message: 'bad json value'
    no_outputs_from:
      - my-transform
  - name: test2
    inputs:
      - insert_at: my-transform
        type: log
        log_fields:
          message: '{"key": "value"}'
    outputs:
      - extract_from: my-transform
        conditions:
          - type: vrl
            source: |-
              assert!(.key == "value")
  - name: test3
    inputs:
      - insert_at: my-transform
        type: log
        log_fields:
          message: '{"key": another bad json value}'
    no_outputs_from:
      - my-transform

```

When unit tests are run, you get the internal logs rated limited by Vector:
```
$ vector test vector.yaml
Running tests
Nov 05 12:40:25.470  WARN vector::internal_events::remap: Mapping failed with event; discarding event. error="function call error for \"parse_json\" at (4:25): unable to parse json: expected value at line 1 column 1" internal_log_rate_secs=30
test test1 ... passed
test test2 ... passed
Nov 05 12:40:25.470  WARN vector::internal_events::remap: Internal log [Mapping failed with event; discarding event.] is being rate limited.
test test3 ... passed
```

The problem with this is that you are unable to see the actual error log anymore. For example, you cannot see the location of the bad JSON data for the second failed case.  In this particular toy pipeline is a bit meaningless but in more complex pipelines the rate limiter becomes _very_ annoying and frustrating when debugging the pipeline.

During unit testing, much more useful would be for all logging to be output, without the rate limiter in the middle:
```
$ vector test vector.yaml
Running tests
Nov 05 12:40:25.470  WARN vector::internal_events::remap: Mapping failed with event; discarding event. error="function call error for \"parse_json\" at (4:25): unable to parse json: expected value at line 1 column 1" internal_log_rate_secs=30
test test1 ... passed
test test2 ... passed
Nov 05 12:51:54.222  WARN vector::internal_events::remap: Mapping failed with event; discarding event. error="function call error for \"parse_json\" at (4:25): unable to parse json: expected value at line 1 column 9" internal_log_rate_secs=30
test test3 ... passed
```

### Proposal

One solution is to disable the internal log rate limiter when running unit tests.

However, I have found myself sometimes wanting to temporarily disable or tune the rate limiter during actual pipeline running (also for debugging/validation), but Vector at the moment does not provide any means to configure the internal log rate limiter (as far as I am aware).

Therefore, another more useful solution could be to make the rate limiter configurable, i.e. enable/disable or set the rate limits. In this way we can disable/configure it at will during unit tests or during normal pipeline running.

**Comment by jszwedko** [comment]
Yeah, this makes sense to me, thanks for the suggestion @hhromic !

**Comment by hhromic** [comment]
No problem, and thanks for considering our feedback, much appreciated!

**Comment by hhromic** [comment]
Closing this issue because it is now addressed in the following PRs:
* https://github.com/vectordotdev/vector/pull/14381
* https://github.com/vectordotdev/vector/pull/14458

To disable rate limiting during tests, simply provide `VECTOR_INTERNAL_LOG_RATE_LIMIT=0` (env) or `-i 0` (CLI). 🎉
