### ISSUE TITLE
soak tests fail on kernels without support for the 9p filesystem

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#9948]
When it tries to `minikube mount`: 

```
X Exiting due to GUEST_MOUNT: mount with cmd /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=39947,trans=tcp,version=9p2000.L 192.168.49.1 /captures" : /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=39947,trans=tcp,version=9p2000.L 192.168.49.1 /captures": Process exited with status 32
stdout:

stderr:
mount: /captures: unknown filesystem type '9p'.
```

I'm running on Amazon Linux 2 which is based on RHEL 7.

```
➜  vector git:(jesse-temp) ✗ uname -a
Linux a-8cktst39ij0a 4.14.232-176.381.amzn2.x86_64 #1 SMP Wed May 19 00:31:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
➜  vector git:(jesse-temp) ✗ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

Ref: https://github.com/kubernetes/minikube/issues/8202

I wonder if there is another way we could share files? I was able to run the soak tests on this system at one point. Alternatively we can close this as `wontfix` and I'll just run these elsewhere when needed 😄 

Curious what you think @blt

**Comment by blt** [comment]
Oh interesting. I'm open to alternatives to mounting but I think our cross-platform support options are limited. I had originally forwarded the prometheus service from inside the cluster and ran observer externally, but that played poorly with OS X. Writing to blob storage would be interesting, if we could contrive to square the circle of local run, remote run support.

**Comment by jszwedko** [comment]
Yeah, I think this can be pretty low priority. We can see if anyone else runs into it aside from me. I'm happy to keep a separate EC2 instance with a newer kernel for running soak tests when needed.

**Comment by jszwedko** [comment]
Closing this since the soak tests no longer use minikube.
