### ISSUE TITLE
Create a `docker_events` source

### ISSUE THREAD

**Issue by jdrouet** [vectordotdev/vector#9951]
We have a `docker_logs` source but nothing related to log the events (`start`, `stop`, `kill`, `die`...) although it's available from with the [docker events command](https://docs.docker.com/engine/reference/commandline/events/) and with [`bollard`](https://docs.rs/bollard/0.11.0/bollard/struct.Docker.html#method.events).

Having this feature would also avoid needing the dd agent to log those events.

**Comment by hhromic** [comment]
This would be very useful for us too. Thanks for proposing :)

**Comment by jszwedko** [comment]
Indeed, this would be useful. I think this is a duplicate of https://github.com/vectordotdev/vector/issues/1546 though so I'll close in-lieu of that one.
