### ISSUE TITLE
compact function doesn't compact empty objects

### ISSUE THREAD

**Issue by anas-aso** [vectordotdev/vector#9958]
### Vector Version

```
vector 0.17.3 (x86_64-apple-darwin d72c6e7 2021-10-21)
```

### Vector Configuration File

```toml
...
```

### Debug Output
```
error[E108]: unknown function argument keyword
  ┌─ :1:30
  │
1 │ hello = compact(value: test, object: true)
  │         -------              ^^^^^^ unknown keyword
  │         │
  │         this function accepts the following keywords: "value", "recursive", "null", "string", "map", "array", "nullish"
  │
  = learn more about error code 108 at https://errors.vrl.dev/108
  = see language documentation at https://vrl.dev
```

### Expected Behavior
considering empty objects as empty value as being documented : https://vector.dev/docs/reference/vrl/functions/#compact

### Actual Behavior
see error above

### Example Data
Run the following in `vector vrl`

```
$ test = { "aaa":"b","hello":"{}"}
{ "aaa": "b", "hello": "{}" }

$ hello = compact(value: test, object: true)
```

**Comment by jszwedko** [comment]
Hi @anas-aso !

This appears to be an issue with the documentation not matching the implementation. We'll fix this, but, for now, you can use `map: true` in the arguments to compact empty objects.
