### ISSUE TITLE
Add explicit rate support in Datadog metric sinks

### ISSUE THREAD

**Issue by prognant** [vectordotdev/vector#9969]
Minor follow up of #9563 where we convert incoming rate into counter.

Datadog support rates, but Vector cannot really explicitly send rate to Datadog.

Pending for schema support or a new metadata field (that could serve for other sinks), counter could be submitted as rate if that marker is present.

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/13394

**Comment by PGBI** [comment]
@jszwedko Which version of Vector did this change ship with? I may have missed it, but I don't see anything regarding this feature in the release notes.

**Comment by jszwedko** [comment]
Hi @PGBI ! It will be released in the upcoming 0.24.0 release.

**Comment by PGBI** [comment]
@jszwedko Awesome, thanks!
